[tool.poetry]
name = "quarks2_fractal"
version = "0.1.5"
description = "Integrated image classification and semantic segmentation package"
authors = ["PrakashJay <vanapalli.prakash@fractal.ai>", "Sindhura <sindhura.k@fractal.ai>"]
license = "Apache-2.0"

[tool.poetry.dependencies]
python = "3.6.9"
torch = "1.3.0"
torchvision = "0.4.1"
pretrainedmodels = "^0.7.4"
efficientnet_pytorch = "0.5.1"
EasyDict = "^1.9"
pandas = "^0.25.2"
loguru = "^0.3.2"
hyperdash = "^0.15.3"
ipython = "^7.8"
click = "^7.0"
torchnet = "^0.0.4"
albumentations = "^0.4.1"
ipykernel = "^5.1"
scikit-learn = "^0.21.3"
captum = "^0.1.0"
opencv-python = "^4.1"

[tool.poetry.dev-dependencies]
jupyterlab = "^1.1"
jupyter = "^1.0"

[tool.poetry.scripts]
train = "quarks2_fractal.engine.trainer:main"
infer_img = "quarks2_fractal.engine.infer:infer_img_click"
infer_video = "quarks2_fractal.engine.infer:infer_video_click"

f1_score = "quarks2_fractal.utils.f1_score:f1_score"
batched_inference = "quarks2_fractal.utils.batched_inference:batched_inference"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"


