#AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"build_model": "demo.ipynb",
         "autoencoder": "demo.ipynb",
         "plot_acc": "demo.ipynb",
         "plot_loss": "demo.ipynb"}

modules = ["core.py"]

git_url = "https://github.com/fastai/fraud_detection_autoencoders/tree/master/"

def custom_doc_links(name): return None