[tool.poetry]
name = "pmeta"
version = "0.1.0"
description = "Python for Meta Analysis"
authors = ["Yajie Zhu <yajiez.me@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
