[tool.poetry]
name = "obstacle"
version = "0.1.0"
authors = ["Stelios Tymvios <solliet@protonmail.com>"]
description = "Obstacle Tower Challenge Environment"
license = "Apache-2.0"

[tool.poetry.dependencies]
python = "^3.7"
mlagents-envs = "0.10"
gym = "^0.15.4"
click = "^7.0"
wget = "^3.2"
toml = "^0.10.0"
pyyaml = "^5.2"
torch = "^1.3.1"
attrs = "^19.3.0"
opencv-python = "^4.1.2"
opencv-contrib-python = "^4.1.2"
dill = "^0.3.1"
pendulum = "^2.0.5"

[tool.poetry.dev-dependencies]
mypy = "^0.761"
black = {version = "^19.10b0", allow-prereleases = true}
rope = "^0.14.0"

[tool.poetry.scripts]
ariadne = 'obstacle.console:cli'

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"


