PENDING_CHOICE = 10
PAID_CHOICE = 20
REJECTED_CHOICE = 30
CANCELLED_CHOICE = 40
REFUNDED_CHOICE = 50
CHARGED_BACK_CHOICE = 60
PAYMENT_STATUS_CHOICES = (
    (PENDING_CHOICE, 'Pendiente'),
    (PAID_CHOICE, 'Pagado'),
    (REJECTED_CHOICE, 'Rechazado'),
    (CANCELLED_CHOICE, 'Cancelado'),
    (REFUNDED_CHOICE, 'Reversado'),
    (CHARGED_BACK_CHOICE, 'Reversado'),
)
