
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-01-08T13:45:28-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "4c31deb07cb723cad5b71344fc048b1d23c39b51",
 "version": "2.0.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
