[tool.poetry]
name = "alphanum"
version = "0.1.1"
description = "Generates random alphanumeric strings."
authors = ["Cody Logan <clpo13@gmail.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/clpo13/alphanum"
repository = "https://github.com/clpo13/repository"
keywords = ['string', 'random', 'pseudo-random', 'generator']

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
