
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-01-14T17:54:02-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "66cfe8f07df043a91df75c4c0a7a302718cf7334",
 "version": "1.5.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
