[tool.poetry]
name = "gtk-formatted-textview"
version = "0.0.0"
description = "A Gtk Textview widget with a toolbar for adding formatting as bold, italics, underline, linkx, etc"
authors = ["BeatLink <beatlink@protonmail.com>"]
license = "GPL-3.0+"

packages = [{include = "format_textview"}]

[tool.poetry.dependencies]
python = "^3.6"
pygobject = "^3.32.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
