[tool.poetry]
name = "kragle"
version = "0.1.1"
description = "glue and tape"
authors = ["Arni Inaba Kjartansson <arni@inaba.is>"]
license = "MIT"
repository = "https://github.com/arni-inaba/kragle"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
pytest = "^5.3"
mypy = {version = "=0.720.0", allows-prereleases = true}
asynctest = "^0.13.0"
flake8 = "^3.7"
black = {version = "^18.3-alpha.0", allows-prereleases = true}
pytest-asyncio = "^0.10.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
