
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-01-17T15:26:47-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "1e14a00d473eece35b7dfe6791137af2ddd569ee",
 "version": "1.10.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
