# Base Configuration file for artellapipe-tools-alembicmanager

# Defines tool name
name: Changelog

# Unique ID for the tool
id: artellapipe-tools-changelog

# Defines logo name of the tool
logo: changelog_logo

# Defines icon of the tool
icon: document

# Description of the tool
description: Tool that shows changelog of the different versions

# URL to tool documentation web page
url: www.google.es

# Tags relatedi with this tool
tags: ['changelog']

# Defines the ID used by Sentry to monitorize error traces
sentry_id: https://780f09885fe84358a3d54f5f475a82fc@sentry.io/1764084

# Directory where tool logger will be created
logger_dir: ${join(user, "artellapipe", "logs", "tools")}

# Default logger level used by tool logger
logger_level: WARNING

# Directory where tool resources are located
resources_path: ${join(filename, "resources")}

# File that defines tool logger settings
logging_file: ${join(filename, "__logging__.ini")}

# Menu representation of this tool
menu_ui:
  label: "Changelog"
  is_checkable: False
  is_checked: False
  load_on_startup: False

# Tool Menu definition where this tool is registered
menu:
  - label: General
    type: menu
    children:
      - id: artellapipe-tools-changelog
        type: tool

# Tool Shelf definition
shelf:
  - name: General
    children:
      - id: artellapipe-tools-changelog
        displayLabel: False
        type: tool