# Base Configuration for Artella Shaders

# Defines list of paths where shaders can be found
paths: []

# Defines the template name used to define shader files
file_type: "shader"

# Defines the template name used to define shader path
shader_path_file_type: "shaders"