# Base Configuration file for artellapipe-tools-artellamanager

# Defines tool name
name: Artella Manager

# Unique ID for the tool
id: artellapipe-tools-artellamanager

# Defines logo name of the tool
logo: artellamanager_logo

# Defines icon of the tool
icon: artella

# Description of the tool
description: Artella Pipeline Module that contains project-specific configuration files

# URL to tool documentation web page
url: www.google.es

# Tags relatedi with this tool
tags: ['artella', 'manager', 'files']

# Defines the ID used by Sentry to monitorize error traces
sentry_id: https://040ed0435de64013afb25a47d04e3cf1@sentry.io/1763161

# Directory where tool logger will be created
logger_dir: ${join(user, "artellapipe", "logs", "tools")}

# Default logger level used by tool logger
logger_level: WARNING

# Directory where tool resources are located
resources_path: ${join(filename, "resources")}

# File that defines tool logger settings
logging_file: ${join(filename, "__logging__.ini")}

# List that defines the import order of the tool modules
import_order:
  - widgets
  - core

# Menu representation of this tool
menu_ui:
  label: "Artella Manager"
  is_checkable: False
  is_checked: False
  load_on_startup: False

# Tool Menu definition where this tool is registered
menu:
  - label: Artella
    type: menu
    children:
      - id: artellapipe-tools-artellamanager
        type: tool

# Tool Shelf definition
shelf:
  - name: Artella
    children:
      - id: artellapipe-tools-artellamanager
        displayLabel: False
        type: tool
