
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-01-17T21:35:31+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "ed99df8c27ba95f0e6983f473543efcb51a1607e",
 "version": "v1.4.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
