[tool.poetry]
name = "ddtrace-aiomisc"
version = "1.0.2"
description = "ddtrace miscellaneous utils"
authors = ["m.shlyamov <m.shlyamov@yandex.com>"]
homepage = "https://github.com/SandLabs/ddtrace-aiomisc"
readme = "README.md"
license = "MIT"
classifiers = [
    'Intended Audience :: Developers',
    'Natural Language :: English',
    'Programming Language :: Python',
    'Programming Language :: Python :: 3',
    'Programming Language :: Python :: 3.6',
    'Programming Language :: Python :: 3.7',
    'Programming Language :: Python :: 3.8',
    'Programming Language :: Python :: 3 :: Only',
    'Topic :: Software Development',
    'Topic :: Software Development :: Libraries',
    'Operating System :: Microsoft :: Windows',
    'Operating System :: POSIX',
    'Operating System :: Unix',
    'Operating System :: MacOS',
]

[tool.poetry.dependencies]
python = "^3.6"
ddtrace = "^0.31"

[tool.poetry.dev-dependencies]
prospector = "^1.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
