package: dmriprep
sections:
- name: Summary
  reportlets:
  - bids: {datatype: anat, desc: summary, suffix: T1w}
- name: Anatomical
  reportlets:
  - bids:
      datatype: anat
      desc: conform
      extension: [.html]
      suffix: T1w
  - bids: {datatype: anat, suffix: dseg}
    caption: This panel shows the template T1-weighted image (if several T1w images
      were found), with contours delineating the detected brain mask and brain tissue
      segmentations.
    subtitle: Brain mask and brain tissue segmentation of the T1w
  - bids: {datatype: anat, space: .*, suffix: T1w, regex_search: True}
    caption: Spatial normalization of the T1w image to the <code>{space}</code> template.
    description: Results of nonlinear alignment of the T1w reference one or more template
      space(s). Hover on the panels with the mouse pointer to transition between both
      spaces.
    static: false
    subtitle: Spatial normalization of the anatomical T1w reference
  - bids: {datatype: anat, desc: reconall, suffix: T1w}
    caption: Surfaces (white and pial) reconstructed with FreeSurfer (<code>recon-all</code>)
      overlaid on the participant's T1w template.
    subtitle: Surface reconstruction
- name: Diffusion
  ordering: session,acquisition,run
  reportlets:
  - bids: {datatype: dwi, desc: validation, suffix: dwi}
  - bids: {datatype: dwi, desc: brain, suffix: mask}
    caption: Average b=0 that serves for reference in early preprocessing steps.
    descriptions: The reference b=0 is obtained as the voxel-wise median across
      all b=0 found in the dataset, after accounting for signal drift.
      The red contour shows the brain mask calculated using this reference b=0.
    subtitle: Reference b=0 and brain mask
- name: About
  reportlets:
  - bids: {datatype: anat, desc: about, suffix: T1w}
