[tool.black]
line_length = 79

[tool.poetry]
name = "aiohttp-middlewares"
version = "1.0.0b1"
description = "Collection of useful middlewares for aiohttp applications."
authors = ["Igor Davydenko <iam@igordavydenko.com>"]
license = "BSD-3-Clause"
readme = "README.rst"
homepage = "https://igordavydenko.com/projects.html#aiohttp-middlewares"
repository = "https://github.com/playpauseandstop/aiohttp-middlewares"
documentation = "https://aiohttp-middlewares.readthedocs.io/"
keywords = ["aiohttp", "middlewares"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Environment :: Web Environment",
    "Operating System :: OS Independent",
    "Topic :: Utilities",
    "Topic :: Internet :: WWW/HTTP :: Dynamic Content",
    "Topic :: Internet :: WWW/HTTP :: WSGI",
    "Topic :: Internet :: WWW/HTTP :: WSGI :: Application"
]

[tool.poetry.dependencies]
python = "^3.6"
aiohttp = "^3.5"
async-timeout = "^1.2 || ^2 || ^3"

[tool.poetry.dev-dependencies]
coveralls = "^1.7"
pytest = "^5.0"
pytest-aiohttp = "^0.3.0"
pytest-cov = "^2.7"

[tool.tox]
legacy_tox_ini = """
[tox]
envlist = py36,py37,py38
skipsdist = True

[testenv]
passenv =
    PYTHONPATH
    PYTEST_ADDOPTS
setenv =
    PYTHONPATH=.
skip_install = True
whitelist_externals = poetry
commands_pre =
    poetry install
commands =
    poetry run python -m pytest tests/ --cov=aiohttp_middlewares --cov-branch --cov-fail-under=90 --cov-report=term-missing:skip-covered --no-cov-on-fail
"""
