[tool.poetry]
name = "lms-prepaid"
version = "0.1.1"
description = "A script to query Last Mile Solutions prepaid card values"
authors = ["asmw <asmw@asmw.org>"]
readme = "README.md"
license = "MIT"
homepage = "https://gitlab.com/asmw/lms-prepaid"

[tool.poetry.dependencies]
python = "^3.7"
requests = "^2.22.0"
click = "^7.0"
tritise = "^0.1.0"

[tool.poetry.scripts]
lms-prepaid = "lms_prepaid.lms_prepaid:query"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
pylint = "^2.4.4"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
