language: python
matrix:
  include:
    - os: linux
      sudo;: required
      python: 2.7
      env: TOXENV=py27
    - os: linux
      sudo;: required
      python: 3.4
      env: TOXENV=py34
    - os: linux
      sudo;: required
      python: 3.5
      env: TOXENV=py35
    - os: linux
      sudo;: required
      python: 3.6
      env: TOXENV=py36
    - os: linux
      sudo;: required
      python: 3.7
      env: TOXENV=py37
  allow_failures:
    - os: linux
      sudo;: required
      python: 2.7
      env: TOXENV=py27

before_install:
- pip freeze
install:
- pip install tox
- python setup.py clean build install sdist
script:
- tox -e "flake8,$TOXENV"
after_success:
- tox -e docs