[tool.poetry]
name = "mecab2pandas"
version = "0.2.2"
description = "MeCab to pandas"
authors = ["Lucky <phatbowie@gmail.com>"]
homepage = "https://github.com/Lucky-Mano/mecab2pandas"
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
mecab-python3 = "*"
pandas = "*"

[tool.poetry.dev-dependencies]
flake8 = "*"
pydocstyle = "*"
nose = "*"
isort = "*"
pre-commit = "*"
mypy = "*"
black = { version="*", allow-prereleases = true }

[tool.black]
line-length = 100
target-version = ["py37"]
exclude = '''
(
  \.eggs
  | \.git
  | \.mypy_cache
  | \.pytest_cache
  | dist
)
'''

[tool.isort]
include_trailing_comma = true
line_length = 100
multi_line_output = 3

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
