[tool.poetry]
name = "netizenship"
version = "0.1.1"
description = "A Tool to check the online membership in popular websites like Facebook, Twitter, etc."
authors = ["Rahul Raj"]
license = "MIT"

[tool.poetry.dependencies]
python = "3.7"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.poetry.scripts]
netizenship = 'netizenship:main'