[tool.poetry]
name = "trase"
version = "0.1.0"
description = ""
authors = ["Trase Team <info@trase.earth>"]

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
