[tool.poetry]
name = "autocensus"
version = "1.0.7"
description = "A tool for collecting ACS and geospatial data from the Census API"
license = "MIT"
authors = ["Christopher Setzer <chris.setzer@socrata.com>"]
readme = "readme.md"
homepage = "https://github.com/socrata/autocensus"
keywords = ["census", "acs", "api", "data", "socrata"]
classifiers = [
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research"
]

[tool.poetry.dependencies]
python = "^3.7"
aiohttp = "^3.6.2"
appdirs = "^1.4.3"
Fiona = "^1.8.13"
geopandas = "^0.6.2"
nest-asyncio = "^1.2.1"
pandas = "^0.25.3"
shapely = "^1.6.4"
socrata-py = "^0.4.21"
tenacity = "^6.0.0"
titlecase = "^0.12.0"
yarl = "^1.4.2"

[tool.poetry.dev-dependencies]
black = "^19.10b0"
flake8 = "^3.7.9"
mypy = "^0.761"
pydocstyle = "^5.0.2"

[tool.black]
line-length = 99
target-version = ["py37"]
skip-string-normalization = true

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
