specfile_path: python-requre.spec
synced_files:
  - python-requre.spec
  - .packit.yaml
# package project name what correspond to package name in setup.py
upstream_package_name: requre
# name what you used as name in specfile (for python packages it starts with python-)
downstream_package_name: python-requre

jobs:
- job: copr_build
  trigger: pull_request
  metadata:
    targets:
    - fedora-stable
