# THIS FILE IS GENERATED BY DALIUGE'S SETUP.PY
# DO NOT MODIFY BY HAND
version = '0.8.1'
git_version = '3c6cdda47790479251d780d061a0a2178a7e9d5c'
full_version = '0.8.1'
is_release = True

if not is_release:
    version = full_version