[tool.poetry]
name = "phorg"
version = "0.0.1"
description = "Command-line application to help reduce photography's organization time consumption."
authors = ["NunoPalma"]
license = "MIT"

[tool.poetry.dependencies]
python = "3.8.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.poetry.scripts]
phorg = 'phorg:main'
