[tool.poetry]
name = "dophon-properties"
version = "0.1.4r4"
description = "dophon properties module"
authors = ["CallMeE <ealohu@163.com>"]

[tool.poetry.dependencies]
python = "^3.6"
PyYAML="*"

[tool.poetry.dev-dependencies]
pytest = "^3.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
