# coding: utf-8

"""
    MMS Example API

    Documentation for MMS API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import mms_python_client
from mms_python_client.api.permissions_lookup_controller_api import PermissionsLookupControllerApi  # noqa: E501
from mms_python_client.rest import ApiException


class TestPermissionsLookupControllerApi(unittest.TestCase):
    """PermissionsLookupControllerApi unit test stubs"""

    def setUp(self):
        self.api = mms_python_client.api.permissions_lookup_controller_api.PermissionsLookupControllerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_lookup_permissions(self):
        """Test case for lookup_permissions

        """
        pass


if __name__ == '__main__':
    unittest.main()
