# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: agent.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='agent.proto',
  package='iams.agent',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0b\x61gent.proto\x12\niams.agent\x1a\x1bgoogle/protobuf/empty.proto\",\n\x0eSimulationData\x12\x0c\n\x04uuid\x18\x01 \x01(\x0c\x12\x0c\n\x04time\x18\x02 \x01(\x02\"f\n\x12\x43onnectionResponse\x12\r\n\x05\x61gent\x18\x01 \x01(\t\x12\r\n\x05image\x18\x02 \x01(\t\x12\x0f\n\x07version\x18\x03 \x01(\t\x12\x11\n\tinterface\x18\x04 \x01(\t\x12\x0e\n\x06kwargs\x18\x05 \x01(\x0c\"a\n\x0fServiceResponse\x12\r\n\x05\x61gent\x18\x01 \x01(\t\x12\r\n\x05image\x18\x02 \x01(\t\x12\x0f\n\x07version\x18\x03 \x01(\t\x12\x0f\n\x07service\x18\x04 \x01(\t\x12\x0e\n\x06kwargs\x18\x05 \x01(\x0c\"9\n\x14\x43onnectionAddRequest\x12\x11\n\tinterface\x18\x04 \x01(\t\x12\x0e\n\x06kwargs\x18\x05 \x01(\x0c\")\n\x14\x43onnectionDelRequest\x12\x11\n\tinterface\x18\x04 \x01(\t\".\n\x0cPingResponse\x12\r\n\x05image\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\t2\xc2\x03\n\x05\x41gent\x12L\n\x0e\x63onnection_get\x12\x16.google.protobuf.Empty\x1a\x1e.iams.agent.ConnectionResponse\"\x00\x30\x01\x12L\n\x0e\x63onnection_add\x12 .iams.agent.ConnectionAddRequest\x1a\x16.google.protobuf.Empty\"\x00\x12L\n\x0e\x63onnection_del\x12 .iams.agent.ConnectionDelRequest\x1a\x16.google.protobuf.Empty\"\x00\x12\x46\n\x0bservice_get\x12\x16.google.protobuf.Empty\x1a\x1b.iams.agent.ServiceResponse\"\x00\x30\x01\x12K\n\x13simulation_continue\x12\x1a.iams.agent.SimulationData\x1a\x16.google.protobuf.Empty\"\x00\x12:\n\x04ping\x12\x16.google.protobuf.Empty\x1a\x18.iams.agent.PingResponse\"\x00\x62\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])




_SIMULATIONDATA = _descriptor.Descriptor(
  name='SimulationData',
  full_name='iams.agent.SimulationData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uuid', full_name='iams.agent.SimulationData.uuid', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='time', full_name='iams.agent.SimulationData.time', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=56,
  serialized_end=100,
)


_CONNECTIONRESPONSE = _descriptor.Descriptor(
  name='ConnectionResponse',
  full_name='iams.agent.ConnectionResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='agent', full_name='iams.agent.ConnectionResponse.agent', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='image', full_name='iams.agent.ConnectionResponse.image', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='version', full_name='iams.agent.ConnectionResponse.version', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='interface', full_name='iams.agent.ConnectionResponse.interface', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='kwargs', full_name='iams.agent.ConnectionResponse.kwargs', index=4,
      number=5, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=102,
  serialized_end=204,
)


_SERVICERESPONSE = _descriptor.Descriptor(
  name='ServiceResponse',
  full_name='iams.agent.ServiceResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='agent', full_name='iams.agent.ServiceResponse.agent', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='image', full_name='iams.agent.ServiceResponse.image', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='version', full_name='iams.agent.ServiceResponse.version', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='service', full_name='iams.agent.ServiceResponse.service', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='kwargs', full_name='iams.agent.ServiceResponse.kwargs', index=4,
      number=5, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=206,
  serialized_end=303,
)


_CONNECTIONADDREQUEST = _descriptor.Descriptor(
  name='ConnectionAddRequest',
  full_name='iams.agent.ConnectionAddRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='interface', full_name='iams.agent.ConnectionAddRequest.interface', index=0,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='kwargs', full_name='iams.agent.ConnectionAddRequest.kwargs', index=1,
      number=5, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=305,
  serialized_end=362,
)


_CONNECTIONDELREQUEST = _descriptor.Descriptor(
  name='ConnectionDelRequest',
  full_name='iams.agent.ConnectionDelRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='interface', full_name='iams.agent.ConnectionDelRequest.interface', index=0,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=364,
  serialized_end=405,
)


_PINGRESPONSE = _descriptor.Descriptor(
  name='PingResponse',
  full_name='iams.agent.PingResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='image', full_name='iams.agent.PingResponse.image', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='version', full_name='iams.agent.PingResponse.version', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=407,
  serialized_end=453,
)

DESCRIPTOR.message_types_by_name['SimulationData'] = _SIMULATIONDATA
DESCRIPTOR.message_types_by_name['ConnectionResponse'] = _CONNECTIONRESPONSE
DESCRIPTOR.message_types_by_name['ServiceResponse'] = _SERVICERESPONSE
DESCRIPTOR.message_types_by_name['ConnectionAddRequest'] = _CONNECTIONADDREQUEST
DESCRIPTOR.message_types_by_name['ConnectionDelRequest'] = _CONNECTIONDELREQUEST
DESCRIPTOR.message_types_by_name['PingResponse'] = _PINGRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SimulationData = _reflection.GeneratedProtocolMessageType('SimulationData', (_message.Message,), {
  'DESCRIPTOR' : _SIMULATIONDATA,
  '__module__' : 'agent_pb2'
  # @@protoc_insertion_point(class_scope:iams.agent.SimulationData)
  })
_sym_db.RegisterMessage(SimulationData)

ConnectionResponse = _reflection.GeneratedProtocolMessageType('ConnectionResponse', (_message.Message,), {
  'DESCRIPTOR' : _CONNECTIONRESPONSE,
  '__module__' : 'agent_pb2'
  # @@protoc_insertion_point(class_scope:iams.agent.ConnectionResponse)
  })
_sym_db.RegisterMessage(ConnectionResponse)

ServiceResponse = _reflection.GeneratedProtocolMessageType('ServiceResponse', (_message.Message,), {
  'DESCRIPTOR' : _SERVICERESPONSE,
  '__module__' : 'agent_pb2'
  # @@protoc_insertion_point(class_scope:iams.agent.ServiceResponse)
  })
_sym_db.RegisterMessage(ServiceResponse)

ConnectionAddRequest = _reflection.GeneratedProtocolMessageType('ConnectionAddRequest', (_message.Message,), {
  'DESCRIPTOR' : _CONNECTIONADDREQUEST,
  '__module__' : 'agent_pb2'
  # @@protoc_insertion_point(class_scope:iams.agent.ConnectionAddRequest)
  })
_sym_db.RegisterMessage(ConnectionAddRequest)

ConnectionDelRequest = _reflection.GeneratedProtocolMessageType('ConnectionDelRequest', (_message.Message,), {
  'DESCRIPTOR' : _CONNECTIONDELREQUEST,
  '__module__' : 'agent_pb2'
  # @@protoc_insertion_point(class_scope:iams.agent.ConnectionDelRequest)
  })
_sym_db.RegisterMessage(ConnectionDelRequest)

PingResponse = _reflection.GeneratedProtocolMessageType('PingResponse', (_message.Message,), {
  'DESCRIPTOR' : _PINGRESPONSE,
  '__module__' : 'agent_pb2'
  # @@protoc_insertion_point(class_scope:iams.agent.PingResponse)
  })
_sym_db.RegisterMessage(PingResponse)



_AGENT = _descriptor.ServiceDescriptor(
  name='Agent',
  full_name='iams.agent.Agent',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=456,
  serialized_end=906,
  methods=[
  _descriptor.MethodDescriptor(
    name='connection_get',
    full_name='iams.agent.Agent.connection_get',
    index=0,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=_CONNECTIONRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='connection_add',
    full_name='iams.agent.Agent.connection_add',
    index=1,
    containing_service=None,
    input_type=_CONNECTIONADDREQUEST,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='connection_del',
    full_name='iams.agent.Agent.connection_del',
    index=2,
    containing_service=None,
    input_type=_CONNECTIONDELREQUEST,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='service_get',
    full_name='iams.agent.Agent.service_get',
    index=3,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=_SERVICERESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='simulation_continue',
    full_name='iams.agent.Agent.simulation_continue',
    index=4,
    containing_service=None,
    input_type=_SIMULATIONDATA,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ping',
    full_name='iams.agent.Agent.ping',
    index=5,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=_PINGRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_AGENT)

DESCRIPTOR.services_by_name['Agent'] = _AGENT

# @@protoc_insertion_point(module_scope)
