# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from . import framework_pb2 as framework__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


class FrameworkStub(object):
  """
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.agents = channel.unary_stream(
        '/iams.servicer.Framework/agents',
        request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        response_deserializer=framework__pb2.AgentData.FromString,
        )
    self.images = channel.unary_unary(
        '/iams.servicer.Framework/images',
        request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        response_deserializer=framework__pb2.ImagesData.FromString,
        )
    self.create = channel.unary_unary(
        '/iams.servicer.Framework/create',
        request_serializer=framework__pb2.AgentData.SerializeToString,
        response_deserializer=framework__pb2.AgentData.FromString,
        )
    self.update = channel.unary_unary(
        '/iams.servicer.Framework/update',
        request_serializer=framework__pb2.AgentData.SerializeToString,
        response_deserializer=framework__pb2.AgentData.FromString,
        )
    self.booted = channel.unary_unary(
        '/iams.servicer.Framework/booted',
        request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
    self.destroy = channel.unary_unary(
        '/iams.servicer.Framework/destroy',
        request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
    self.sleep = channel.unary_unary(
        '/iams.servicer.Framework/sleep',
        request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
    self.upgrade = channel.unary_unary(
        '/iams.servicer.Framework/upgrade',
        request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
    self.wake = channel.unary_unary(
        '/iams.servicer.Framework/wake',
        request_serializer=framework__pb2.WakeAgent.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )


class FrameworkServicer(object):
  """
  """

  def agents(self, request, context):
    """
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def images(self, request, context):
    """
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def create(self, request, context):
    """
    send this command to create a agent

    fails with invalid_arguemnt if argument missing or incorrect
    fails with already exists if name already exists
    fails with not found if image is not found or image is invalid
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def update(self, request, context):
    """
    send this command to update a agent

    fails with invalid_arguemnt if argument missing or incorrect
    fails with already exists if name already exists
    fails with not found if agent or image is not found or image is invalid
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def booted(self, request, context):
    """
    agent sends this command to signalize its operational
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def destroy(self, request, context):
    """
    agent sends this command to destroy himself (service is removed)
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def sleep(self, request, context):
    """
    agent sends this command to shut himself down (service is scaled to 0)
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def upgrade(self, request, context):
    """
    agent sends this command to update himself (update is forced on service)
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def wake(self, request, context):
    """
    agent sends this command to start another agent (service is scaled to 1)
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_FrameworkServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'agents': grpc.unary_stream_rpc_method_handler(
          servicer.agents,
          request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
          response_serializer=framework__pb2.AgentData.SerializeToString,
      ),
      'images': grpc.unary_unary_rpc_method_handler(
          servicer.images,
          request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
          response_serializer=framework__pb2.ImagesData.SerializeToString,
      ),
      'create': grpc.unary_unary_rpc_method_handler(
          servicer.create,
          request_deserializer=framework__pb2.AgentData.FromString,
          response_serializer=framework__pb2.AgentData.SerializeToString,
      ),
      'update': grpc.unary_unary_rpc_method_handler(
          servicer.update,
          request_deserializer=framework__pb2.AgentData.FromString,
          response_serializer=framework__pb2.AgentData.SerializeToString,
      ),
      'booted': grpc.unary_unary_rpc_method_handler(
          servicer.booted,
          request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
      'destroy': grpc.unary_unary_rpc_method_handler(
          servicer.destroy,
          request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
      'sleep': grpc.unary_unary_rpc_method_handler(
          servicer.sleep,
          request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
      'upgrade': grpc.unary_unary_rpc_method_handler(
          servicer.upgrade,
          request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
      'wake': grpc.unary_unary_rpc_method_handler(
          servicer.wake,
          request_deserializer=framework__pb2.WakeAgent.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'iams.servicer.Framework', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
