[tool.poetry]
name = "timeflake"
version = "0.1.0"
description = "Timeflakes are 64-bit roughly-ordered, globally-unique, URL-safe UUIDs."
authors = ["Anthony Najjar Simon <anthonynsimon@users.noreply.github.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
black = "^19.10b0"
pytest = "^5.3.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
