[tool.poetry]
name = "owutil"
version = "0.1.5"
description = ""
authors = ["drys262 <koeichavez17@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.poetry.scripts]
owutil = 'owutil:main'

