language: python
addons:
  apt:
    packages:
    - bc
    - findutils
sudo: false
dist: bionic
python:
  - '3.6'
  - '3.7'
  - '3.8'
env:
  - TOX_ENV=unit
  - TOX_ENV=pep8
  - TOX_ENV=pylint
  - TOX_ENV=cover
  - TOX_ENV=docs
install:
  - pip install tox-travis
script:
  - tox
