# Python CircleCI 2.0 configuration file
version: 2
jobs:
  build:
    environment:
      CC_TEST_REPORTER_ID: a5ecea450cd1211c6f4510ef184fed8f51e5d98588e5710e2a8685e5bbfd5185
    docker:
      - image: circleci/python:3.6.1

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            # CI, CircleCI dependencies
            python3 -m venv venv
            . venv/bin/activate
            # CI, codeclimate dependencies
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
            pip install codeclimate-test-reporter
            # project dependencies
            pip install setuptools==40.0.0
            pip install tox
            pip install coverage==4.2

      - run:
          name: Install project
          command: |
            . venv/bin/activate
            python setup.py clean build install sdist

      - run:
          name: Before Tests
          command: |
            ./cc-test-reporter before-build

      - run:
          name: Run Tests
          command: |
            . venv/bin/activate
            tox -e flake8,coverage

      - run:
          name: After Tests
          command: |
            . venv/bin/activate
            tox -e docs
            codeclimate-test-reporter --token $CC_TEST_REPORTER_ID --file .coverage

      - store_artifacts:
          path: dist
          destination: dist
