#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['structured_data', 'structured_data.templatetags']

package_data = \
{'': ['*']}

install_requires = \
['django>=2.2']

setup(name='django-structured-data',
      version='0.5.1',
      description='Template tags to assist in adding structured metadata to views and models.',
      author='Luke Rogers',
      author_email='luke@dmptr.com',
      url='https://github.com/dmptrluke/django-structured-data',
      packages=packages,
      package_data=package_data,
      install_requires=install_requires,
      python_requires='>=3.6',
     )
