

// This file is autogenerated. DO NOT EDIT

#pragma once
#include <robotpy_build.h>

#include <..\..\_impl\include\frc\interfaces\Accelerometer.h>



namespace rpygen {

using namespace frc;

template <typename CxxBase>
struct Pyfrc__Accelerometer : CxxBase {
    using CxxBase::CxxBase;



#ifndef RPYGEN_DISABLE_SetRange_i
    void SetRange(frc::Accelerometer::Range range) override {
PYBIND11_OVERLOAD_PURE_NAME(void, CxxBase, "setRange", SetRange,range);
    }
#endif

#ifndef RPYGEN_DISABLE_GetX_v
    double GetX() override {
PYBIND11_OVERLOAD_PURE_NAME(double, CxxBase, "getX", GetX,);
    }
#endif

#ifndef RPYGEN_DISABLE_GetY_v
    double GetY() override {
PYBIND11_OVERLOAD_PURE_NAME(double, CxxBase, "getY", GetY,);
    }
#endif

#ifndef RPYGEN_DISABLE_GetZ_v
    double GetZ() override {
PYBIND11_OVERLOAD_PURE_NAME(double, CxxBase, "getZ", GetZ,);
    }
#endif



};

}; // namespace rpygen