"""
This type stub file was generated by pyright.
"""

from typing import Dict, Iterable
from pathlib import Path
from io import StringIO

class ReportWriter:
    data: StringIO
    delim: str
    default_delim = ...
    default_newline = ...
    def __init__(self, data=..., delim: str = ...):
        self.data = ...
        self.delim = ...
    
    def indentation(self, indent: int) -> str:
        ...
    
    def writeindent(self, indent: int):
        ...
    
    def write(self, val, indent: int = ...):
        ...
    
    def writeline(self, val=..., indent: int = ...):
        ...
    
    def writedelim(self):
        ...
    
    def writecols(self, vals: Iterable[str], indent: int = ...):
        ...
    
    def writevals(self, *vals, indent: int = ..., newline: bool = ...):
        ...
    
    def writerows(self, vals: Iterable[str], indent: int = ...):
        ...
    
    def writedicts(self, dicts: Iterable[Dict]):
        ...
    
    @property
    def value(self):
        ...
    
    def __str__(self):
        ...
    
    def writeto(self, path: Path):
        ...
    


