[tool.poetry]
name = "netizenship"
version = "0.1.2"
description = "Tool to check the username with popular websites for membership"
authors = ["Rahul Raj <rahulrajpl@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.poetry.scripts]
netizenship = 'netizenship:main'
