---
- id: zuul-lint
  name: Zuul Job Linter
  description: Verifies if Zuul CI jobs files have valid syntax.
  language: python
  files: '^(zuul.d/|.?zuul).*\.yaml$'
  pass_filenames: true
  verbose: true
  entry: zuul-lint
