[tool.poetry]
name = "polyquack-django"
version = "0.0.1a1"
# description = "Django utilities for polyglots"
description = "Placeholder package to reserve name - do not use"
authors = ["Patryk Bratkowski <git@patryk.tech>"]
license = "BSD-3-Clause"
readme = "README.md"
repository = "https://gitlab.com/patryk-media/polyquack"
keywords = ["polyglot", "i18n", "pluralization"]
classifiers = [
    "Development Status :: 1 - Planning",
    "Framework :: Django :: 2.2",
    "Framework :: Django :: 3.0",
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Topic :: Communications",
    "Topic :: Internet :: WWW/HTTP :: Dynamic Content",
    "Topic :: Software Development :: Internationalization",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Text Processing :: Linguistic"
]

[tool.poetry.dependencies]
python = ">=3.6"
polyquack = ">=0.2,<0.3"
Django = ">2.2,<4"

[tool.poetry.dev-dependencies]
pytest = "~5.3"
pytest-cov = "~2.8"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
