# coding: utf-8

"""
    ORY Hydra

    Welcome to the ORY Hydra HTTP API documentation. You will find documentation for all HTTP APIs here.  # noqa: E501

    The version of the OpenAPI document: latest
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import ory_hydra_client
from ory_hydra_client.models.name import Name  # noqa: E501
from ory_hydra_client.rest import ApiException


class TestName(unittest.TestCase):
    """Name unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testName(self):
        """Test Name"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ory_hydra_client.models.name.Name()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
