
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "f0a1d0ee4dfd6c092df302ff2c9e149eb9bbcd06",
 "version": "7.6.1.beta2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
