cfg_title = "15-1"

[inputs]
stop1 = "Lines"
stop2 = "PMT1"
stop3 = "Empty"
stop4 = "Empty"
stop5 = "Empty"
start = "TAG Lens"

[image]
num_of_frames = 1
x_pixels = 512
y_pixels = 2048
z_pixels = 512
imaging_software = "ScanImage"

[outputs]
data_filename = "/data/Lior/lst/2020/2020_01_15/TLP1_188k62p_GCaMP7_mouse_1p5x_zoom_512l_0p5slow_FOV4_-100um_365.lst"
summed = true
memory = false
stack = true
flim = false

[advanced]
debug = false
phase = -0.4
reprate = 80000000.0
gating = false
binwidth = 1e-10
tag_freq = 189000.0
tag_pulses = 1
tag_offset = 0
fill_frac = 72.0
bidir = true
keep_unidir = false
flim = false
censor = false
line_freq = 7930.0
sweeps_as_lines = false
frame_delay = 0.001
interleaved = false

[tagbits]
tag_bits = false

[tagbits.group1]
label1 = "None"
start1 = 1
end1 = 3

[tagbits.group2]
label2 = "None"
start2 = 4
end2 = 5

[tagbits.group3]
label3 = "None"
start3 = 6
end3 = 16
