---
- name: "declaring output vars"
  set_fact:
    topology_outputs_aws_ec2: []
    topology_outputs_aws_s3: []
    topology_outputs_aws_ec2_key: []
    topology_outputs_aws_cfn: []
    topology_outputs_aws_net: []

- name: "Initiating Provisioning of aws resource group"
  include: provision_resource_group.yml res_grp={{ item }}
  with_items:
    - "{{ resources }}"
  when: state == "present"
  check_mode: "{{ _check_mode }}"

- name: "Initiating Teardown of aws resource group"
  include: teardown_resource_group.yml res_grp={{ item }}
  with_items:
    - "{{ resources }}"
  when: state == "absent"
