[tool.poetry]
name = "tranfort"
version = "0.1.0"
description = "Transformer for Tabular Data Learning"
authors = ["yajiez <yajiez.me@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
numpy = "^1.18.1"
pandas = "^0.25.3"
torch = "^1.4.0"
scikit-learn = "^0.22.1"
matplotlib = "^3.1.2"
transformers = "^2.3.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
utify = "^0.2.5"
ipykernel = "^5.1.3"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
