sudo: false
addons:
  apt:
    packages: fonts-lmodern inkscape latexmk libxml2-utils python3-all python3-all-dev
      texlive-fonts-recommended texlive-latex-base texlive-latex-extra texlive-xetex
language: python
cache: pip
matrix:
  include:
  - python: 3.7
    env: TOXENV=py37
  - python: 3.7
    env: TOXENV=docs
  - python: 3.7
    env: TOXENV=pep8
  - python: 3.7
    env: TOXENV=bindep
install: pip install tox
script: tox
deploy:
  provider: pypi
  user: __token__
  password:
    secure: UFAQUMBdFedf/masRhXOHClyoM09UCcgTLxHIhxw+XtY1uiZLGYu8ygnWnH5ISI0q139F7Tut9I2nNzOW+r1nwxIe5PBb93csiZgIj8lt5K2XGccDWa3Er/etqGgEVvFxMUy7RjYEEi/1ruphen8vtBDFz+5j6TGridJYARxCtwj+0MHFNYhDzBoWMa2xdIZPcArRwpep9Ig3rX4I6s/O8kFBh5hXn1H94KLlREGmcbGA3tcghQg7uOdjBQkaIDGl2hEmF4SW+AbA8ecAoP60bnqAZw2YxdFdeOPkMvnIGCoXLYan5C//fHl7nm7IptMcE20TkWsbQMBQ8UAHBlxv8edW7LhNx8iVkRKSKaw4rho+FM7t6495p1POKj7O9Q9uBXbkn3g+8Q2DMA2OCpNJLidQFswbLa+UdKH8H6GE/6atXKvJVTViZOg4pF1qxHP1tHn86yw1fbJdw9YLhX4LCmGovyQxCD9B438fsyRFG84R/WtEtVJwQuFbrnHICWH4XxswAFerVlPSII7az6crA0vH9RdiLlqj1z36svUVobN1Gs2lxP7HovyffuNWZGqlfrrGNqUzVIRT+jHZ5yvDLsQPmwDij6thM1pYlwBniv8ZhxqmVC9B1RbITbkJB+XRLxLeR+eFtlfsjvxylDWKq3cIBj4/j/gDIC5Choowms=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: OpenTelekomCloud/otcdocstheme
    condition: "$TOXENV = py37"
