[tool.poetry]
name = "sipy"
version = "0.2.1"
description = ""
authors = ["Samuel Broster <sbroster@undo.io>"]

[tool.poetry.dependencies]
python = "^3.6"
toml = "^0.10.0"

[tool.poetry.dev-dependencies]
pytest = "^4.6"
mypy = "^0.761"
pytest-steps = "^1.7.1"
black = "^19.10b0"
pylint = "^2.4.4"
pytest-cov = "^2.8.1"
radon = "^4.0.0"
pre-commit = "^1.20.0"
pydeps = "^1.9.0"
isort = "^4.3.21"
ipython = "^7.11.1"
pdoc3 = "^0.7.2"

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
known_third_party = ["pytest", "pytest_steps", "toml"]
import_heading_stdlib = "Standard Library"
import_heading_thirdparty = "Third Party"
import_heading_firstparty = "SIpy"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
