# This file is automatically generated by Znake
from textwrap import dedent

__version__ = '1.0.0-0'
__updated__ = '2020-01-18'
deb_package_name = 'znake'
description = 'Build system for Python projects.'
long_description = dedent('''\\
    Znake is a build system for Python projects.
    ''')
maintainer = 'Andreas Nilsson'
maintainer_email = 'andni233@gmail.com'

changelog = [
    {
        'version': '1.0.0',
        'date': 'Sat, 11 May 2019 06:00:00 +0000',
        'changes': [
            '''First open source version.''',
        ],
    },
]
