- project:
    templates:
      - check-requirements
      - openstack-cover-jobs
      - openstack-lower-constraints-jobs
      - openstack-python-jobs
      - openstack-python35-jobs
      - openstack-python36-jobs
      - openstack-python37-jobs
      - openstackclient-plugin-jobs
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
    check:
      jobs:
        - ironicclient-functional
        - ironicclient-functional-python2
        - ironicclient-tempest
        - ironicclient-tempest-python2
    gate:
      queue: ironic
      jobs:
        - ironicclient-functional
        - ironicclient-functional-python2
        - ironicclient-tempest
        - ironicclient-tempest-python2
