
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-01-12T14:56:29+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "0eceb86e1ba0c98f7ebf2579f82bb4a63ab353a8",
 "version": "0.10.15.post.dev6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
