version: 2.1

jobs:
  build_and_check:
    parameters:
      py_version:
        type: string
        default: ''

    docker:
      - image: circleci/python:<< parameters.py_version >>
    steps:
      - checkout

      # TODO preserve apt and pip caches?

      # no tox by default?
      - run: python3 -m pip install --user tox
      - run: python3 -m tox


# TODO py3.6 is not present in circlci python:lastest image and not clear where to find image with all interpreters..
# this is so fucking repetitive.. I'd rather have a python file that generates CI config

workflows:
  version: 2

  build_and_check_3_6:
    jobs:
      - build_and_check:
          py_version: '3.6'

  build_and_check_3_7:
    jobs:
      - build_and_check:
          py_version: '3.7'
