
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-01-10T17:03:22+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "21eb5b28d9295625241b73b820fc8892b00fc6b0",
 "version": "0.2.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
