# Configuration for Solstice Project

# Define configuration variables for Solstice
id_number: "2"
id: "2252d6c8-407d-4419-a186-cf90760c9967"
url: "https://www.solsticeshortfilm.com/"
documentation_url: "https://solstice-short-film.github.io/solstice-docs/pipeline/"
emails:
  - tpovedatd@gmail.com
extensions:
  - ma
  - abc
  - ass
default_extension: ma
departments:
  - Modeling
  - Shading
  - FX
  - Lighting
  - Comp
  - Grooming
  - Rigging
  - Layout

#  outliner_categories:


# Define configuration variables for project shots
shot:
  regex: "(\\A[^_]+_\\d{2,2}_\\d{2,3})"
  file_types:
    - "Layout"
    - "Animation"
    - "FX"
    - "Lighting"

# Define configuration variables for project progress bar
progress_bar:
  color0: "245, 180, 148"
  color1: "75, 70, 170"

# Defines available libs
libs:
  - artella
  - naming
  - kitsu
  - pyblish
  - alembic

tools:
  - welcome
  - changelog
  - bugtracker
  - alembicmanager
  - artellamanager
  - artellauploader
  - assetsmanager
  - shadersmanager
  - lightrigsmanager
  - assetslibrary
  - namemanager
  - playblastmanager
  - snowgenerator
  - modelchecker
  - assetspublisher
  - outliner
#  - toolbox
  - tagger
  - dependenciesmanager
  - xgenmanager