[tool.poetry]
name = "starmocks"
version = "0.1.0"
description = ""
authors = ["Pedro Werneck <pjwerneck@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.6"
attrdict = "^2.0"

[tool.poetry.dev-dependencies]
pytest = "^5.3"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
