exclude: "^(?!odoo/)|.pot$|.po$"
repos:
- repo: https://github.com/ambv/black
  rev: 18.9b0
  hooks:
  - id: black
    language_version: python3.6
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.0.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: debug-statements
  - id: flake8
    name: flake8 except __init__.py
    args: [--exclude=__init__.py]
    additional_dependencies: [
        "flake8-bugbear == 18.8.0",
        "flake8-per-file-ignores == 0.6",
    ]
    language_version: python3.6
  - id: flake8
    name: flake8 only __init__.py
    args: [--ignore=F401]  # ignore imported unused in __init__.py
    files: __init__.py
    language_version: python3.6
- repo: https://github.com/pre-commit/mirrors-pylint
  rev: v2.3.1
  hooks:
  - id: pylint
    name: pylint odoo
    # check only specific Odoo addons
    files: odoo/addons/
    types: ['file', 'python']   # to not check .csv and .conf files
    args: []
    additional_dependencies: [pylint-odoo==3.0.1]
    language_version: python3.6
- repo: https://github.com/asottile/pyupgrade
  rev: v1.6.1
  hooks:
  - id: pyupgrade
    language_version: python3.6
- repo: https://github.com/asottile/seed-isort-config
  rev: v1.3.0
  hooks:
  - id: seed-isort-config
    language_version: python3.6
- repo: https://github.com/pre-commit/mirrors-isort
  rev: v4.3.4
  hooks:
  - id: isort
    language_version: python3.6
