
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "2633bb67ce01f2db516d21c666cced3aca9a29e3",
 "version": "7.6.1.beta1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
