[tool.poetry]
name = "matrix_transform"
version = "1.0.2"
description = "scikit-image geometric transform module, no extra shit"
authors = ["m.shlyamov <m.shlyamov@yandex.com>"]
homepage = "https://github.com/SandLabs/matrix_transform"
license = "MIT"
readme = "README.md"
classifiers = [
    'Intended Audience :: Developers',
    'Intended Audience :: Science/Research',
    'Programming Language :: Python',
    'Programming Language :: Python :: 3',
    'Programming Language :: Python :: 3.5',
    'Programming Language :: Python :: 3.6',
    'Programming Language :: Python :: 3.7',
    'Programming Language :: Python :: 3 :: Only',
    'Topic :: Scientific/Engineering',
    'Operating System :: Microsoft :: Windows',
    'Operating System :: POSIX',
    'Operating System :: Unix',
    'Operating System :: MacOS',
]

[tool.poetry.dependencies]
python = ">=3.5"
numpy = ">=1.13"
scipy = ">=0.17"

[tool.poetry.dev-dependencies]
prospector = "^1.1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
