[build-system]
requires = ["flit_core >=2,<3"]
build-backend = "flit_core.buildapi"

[tool.flit.metadata]
module = "meta_sphinx"
author = "Jan Freyberg"
author-email = "jan.freyberg@elementai.com"
home-page = "https://github.com/elementai/meta-sphinx"
requires = [
    "sphinx>=2.1",
    "m2r>=0.2.1",
    "pyyaml>=5.1",
    "jinja2>=2.10",
    "markdown>=3.1",
    "python-slugify>=3.0",
    "click>=7.0"
]

[tool.flit.metadata.requires-extra]
dev = [
    "ipython",
    "ipdb",
    "rope",
    "black"
]

[tool.flit.entrypoints.console_scripts]
meta_sphinx_k8s = 'meta_sphinx.generate_hosting:generate_kubernetes_volumes'

[tool.black]
line-length = 79
