[tool.poetry]
name = "froi"
version = "0.4.7"
description = "A Flask wrapper to easily handle routes defined as Python native objects"
authors = ["Almer Mendoza <atmalmer23@gmail.com>"]
readme = "README.rst"
repository = "https://github.com/mamerisawesome/froi"
keywords = ["flask wrapper", "router", "router interface", "interface", "wrapper"]
license = "MIT"
include = ["LICENSE.txt"]
exclude = [".venv/", ".vscode/", ".pytest_cache/"]

[tool.poetry.dependencies]
python = "^3.6"
flask = "^1.0"

[tool.poetry.dev-dependencies]
pytest = "^3.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
