[tool.poetry]
name = "redash-toolbelt"
version = "0.1.0"
description = "Redash API client and tools to manage your instance."
authors = ["Redash Maintainers"]
license = "BSD-2-Clause"

packages = [
    { include = "redash-toolbelt" }
]

[tool.poetry.dependencies]
python = "^3.6"
requests = "^2.22.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
