# THIS FILE IS GENERATED BY DALIUGE'S SETUP.PY
# DO NOT MODIFY BY HAND
version = '0.8.3'
git_version = 'bff730eb7639480853a412cc68b9a5b085369fb1'
full_version = '0.8.3'
is_release = True

if not is_release:
    version = full_version