[tool.poetry]
name = "sqlxray"
version = "0.1.0"
description = ""
authors = ["Khalid <khalidck@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
sqlparse = "^0.3.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
mypy = "^0.761"
pylint = "^2.4.4"
autopep8 = "^1.4.4"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
