from setuptools import setup
setup(name='topsis53004pack2',
version='0.1',
description='Library that implements the "The Technique for Order of Preference by Similarity to Ideal Solution (TOPSIS)"',
url='https://github.com/Ashutosh2088/topsis53004pack2',
download_url='https://github.com/Ashutosh2088/topsis53004pack2/archive/v0.2.tar.gz',
author='Ashutosh Rattan',
author_email='ashutosh544@gmail.com',
license='MIT',
packages=['topsis53004pack2'],
zip_safe=False,
classifiers=[
    'Development Status :: 3 - Alpha',      
    'Intended Audience :: Developers',      
    'Topic :: Software Development :: Build Tools',
    'License :: OSI Approved :: MIT License',   
    'Programming Language :: Python :: 3',      
    'Programming Language :: Python :: 3.4',
    'Programming Language :: Python :: 3.5',
    'Programming Language :: Python :: 3.6',
  ],
)
