# Base Configuration file for artellapipe-tools-renamer

# Defines tool name
name: Renamer

# Unique ID for the tool
id: artellapipe-tools-renamer

# Defines logo name of the tool
logo: renamer_logo

# Description of the tool
description: Tool to rename DCC objects in an easy way

# URL to tool documentation web page
url: www.google.es

# Tags relatedi with this tool
tags: ['renamer', 'tpNameIt']

# Defines the ID used by Sentry to monitorize error traces
sentry_id: https://0e351be2ec4d4360980db9b85980e176@sentry.io/1864142

# Directory where tool logger will be created
logger_dir: ${join(user, "artellapipe", "logs", "tools")}

# Default logger level used by tool logger
logger_level: INFO

# Directory where tool resources are located
resources_path: ${join(filename, "resources")}

# File that defines tool logger settings
logging_file: ${join(filename, "__logging__.ini")}

# Menu representation of this tool
menu_ui:
  label: "Renamer"
  is_checkable: False
  is_checked: False
  load_on_startup: False

# Tool Menu definition where this tool is registered
menu:
  - label: General
    type: menu
    children:
      - id: artellapipe-tools-renamer
        type: tool

# Tool Shelf definition
shelf:
  - name: General
    children:
      - id: artellapipe-tools-renamer
        displayLabel: False
        type: tool