
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-01-12T22:27:34-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "9f401bfb81571efd26146bd6583c983d644f7da5",
 "version": "v0.3.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
