
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "193b56a8c4f1d5ad78dd9a1c9c9ff02e5eb002df",
 "version": "7.6.1.beta4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
