[tool.poetry]
name = "har2postman"
version = "0.1.2"
description = "Convert HAR(HTTP Archive) to Postman Collection"
authors = ["ysansan"]
license = "MIT"
homepage = "https://github.com/whitexie/Har2Postman"
repository = "https://github.com/whitexie/Har2Postman"
keywords = ["har", "postman"]
readme = "README.md"


[tool.poetry.dependencies]
python = "^3.6"
jsonpath = "^0.82.0"

[tool.poetry.dev-dependencies]
coverage = "^4.5.4"
coveralls = "^1.8.2"
pytest = "^5.3"



[tool.poetry.scripts]
harto = "har2postman.cli:main"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

