# This file automatically generated by
#    C:\Jenkins\workspace\python\python-scripted-build-pipeline\couchbase-python-client\couchbase_version.py
# at
#    2020-01-20 16:11:55.593490
__version__ = '3.0.0b3'