# Kopp14 Thermal Expansion Pipeline

pre-process:
  task1:
    executable: "python"
    cpu:
      processes: 1
      process-type: None
      threads-per-process: 1
      thread-type: None
    pre_exec: "tar -xzf kopp14_thermalexp_preprocess_data.tgz; pip install numpy"
    script: "kopp14_preprocess_thermalexp.py"
    options:
      - "scenario"
      - "model_dir"
      - "no_drift_corr"
      - "pipeline_id"
    upload_input_data:
      - "./modules/kopp14/thermalexpansion/kopp14_preprocess_thermalexp.py"
      - "./modules/kopp14/thermalexpansion/IncludeModels.py"
      - "./modules/kopp14/thermalexpansion/SmoothZOSTOGA.py"
      - "./modules/kopp14/thermalexpansion/DriftCorr.py"
      - "./modules/kopp14/thermalexpansion/Smooth.py"
      - "./modules/kopp14/thermalexpansion/read_CSIRO.py"
      - "./modules/kopp14/thermalexpansion/readMarzeion.py"
      - "./modules/kopp14/thermalexpansion/data/kopp14_thermalexp_preprocess_data.tgz"
#    download_output_data:
#      - "%PIPELINE_ID%_config.pkl"
#      - "%PIPELINE_ID%_ZOSTOGA.pkl"


fit:
  task1:
    executable: "python"
    cpu:
      processes: 1
      process-type: None
      threads-per-process: 1
      thread-type: None
    pre_exec: ""
    script: "kopp14_fit_thermalexp.py"
    options:
      - "pipeline_id"
    upload_input_data:
      - './modules/kopp14/thermalexpansion/kopp14_fit_thermalexp.py'
    copy_input_data:
      pre-process:
        task1:
          - "%PIPELINE_ID%_config.pkl"
          - "%PIPELINE_ID%_ZOSTOGA.pkl"
#    download_output_data:
#      - "%PIPELINE_ID%_fit.pkl"


project:
  task1:
    executable: "python"
    cpu:
      processes: 1
      process-type: None
      threads-per-process: 1
      thread-type: None
    pre_exec: ""
    script: "kopp14_project_thermalexp.py"
    options:
      - "nsamps"
      - "seed"
      - "pipeline_id"
    upload_input_data:
      - './modules/kopp14/thermalexpansion/kopp14_project_thermalexp.py'
    copy_input_data:
      pre-process:
        task1:
          - "%PIPELINE_ID%_config.pkl"
      fit:
        task1:
          - "%PIPELINE_ID%_fit.pkl"
    download_output_data:
      - "%PIPELINE_ID%_globalsl.nc"
#      - "%PIPELINE_ID%_projections.pkl"

post-process:
  task1:
    executable: "python"
    cpu:
      processes: 1
      process-type: None
      threads-per-process: 1
      thread-type: None
    pre_exec: "tar -xzf kopp14_thermalexp_postprocess_data.tgz"
    script: "kopp14_postprocess_thermalexp.py"
    options:
      - "site_ids"
      - "pipeline_id"
    upload_input_data:
      - './modules/kopp14/thermalexpansion/kopp14_postprocess_thermalexp.py'
      - './modules/kopp14/thermalexpansion/read_bkgdrate.py'
      - './modules/kopp14/thermalexpansion/data/kopp14_thermalexp_postprocess_data.tgz'
    copy_input_data:
      project:
        task1:
          - "%PIPELINE_ID%_projections.pkl"
    download_output_data:
      - "%PIPELINE_ID%_localsl.nc"