[build-system]
requires = ["flit"]
build-backend = "flit.buildapi"

[tool.flit.metadata]
module = "etcmaint"
author = "Xavier de Gaye"
author-email = "xdegaye@gmail.com"
home-page = "https://gitlab.com/xdegaye/etcmaint"
requires = [
            "zstandard"
           ]
description-file="README.rst"
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Topic :: System :: Software Distribution",
    ]
requires-python = ">=3.6"
keywords = "ArchLinux pacman"

[tool.flit.metadata.urls]
Documentation = "https://xdegaye.gitlab.io/etcmaint/"

[tool.flit.scripts]
etcmaint = "etcmaint.etcmaint:main"
