
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-01-16T11:18:31+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "82c48b8793c2718040a48c53fa973c03f7b76c59",
 "version": "0.9.11.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
