[tool.poetry]
name = "calendarweek"
version = "0.1.0"
description = "Utilities for working with calendar weeks in Python and Django"
authors = ["Dominik George <nik@naturalnet.de>", "Jonathan Weth <git@jonathanweth.de>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
Django = {version = ">=2.2, <4.0", optional = true}

[tool.poetry.extras]
django = ["Django"]

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
