[tool.poetry]
name = "pycrime"
version = "0.0.0"
description = ""
authors = ["Luke Hodkinson <furious.luke@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
requests = "^2.22.0"

[tool.poetry.dev-dependencies]
flake8 = "^3.7"
