image: python:3.7

services:
  - postgres:latest
  - mongo:latest

variables:
  POSTGRES_DB: spinta

cache:
  paths:
    - ~/.cache/pip/

before_script:
  - python --version
  # - apt-get update -q && apt-get install nodejs -yqq
  - python -m venv ci/env
  - ci/env/bin/pip install -r requirements-dev.txt -e .

test:
  variables:
    SPINTA_BACKENDS_DEFAULT_DSN: postgresql://postgres:postgres@postgres:5432/$POSTGRES_DB
    SPINTA_DATASETS_DEFAULT_SQL_DB: postgresql://postgres:postgres@postgres:5432/$POSTGRES_DB
    SPINTA_BACKENDS_MONGO_DSN: mongodb://mongo/
  script:
    - ci/env/bin/py.test -vvxra --tb=native --log-level=debug --cov=spinta --cov-report=term-missing tests
