
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-01-14T10:48:30-1000",
 "dirty": false,
 "error": null,
 "full-revisionid": "45525f7552e7694dcaeeca2aa397b98fc3d4d36e",
 "version": "0.2.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
