version: 1
disable_existing_loggers: False
formatters:
  with_process_name:
    format: "%(asctime)s [%(name)s] %(levelname)s: %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: with_process_name
    stream: ext://sys.stdout
loggers:
  dataprep.infrastructure:
    level: DEBUG
    propagate: True
  dataprep.api:
    level: DEBUG
    propagate: True
  dataprep.cli:
    level: DEBUG
    propagate: True
  dataprep.vocab:
    level: DEBUG
    propagate: True
  dataprep.parse_projects:
    level: DEBUG
    propagate: True
  dataprep.to_repr:
    level: DEBUG
    propagate: True
root:
  level: DEBUG
  handlers: [console]