[tool.poetry]
name = "fsttest"
version = "0.2.1"
description = "Test Foma FSTs"
authors = ["Eddie Antoio Santos <Eddie.Santos@nrc-cnrc.gc.ca>"]
license = "MPL-2.0"
readme = "README.md"
homepage = "https://github.com/eddieantonio/fsttest"
repository = "https://github.com/eddieantonio/fsttest.git"

[tool.poetry.dependencies]
python = "^3.6"
toml = "^0.10.0"
blessings = "^1.7"

[tool.poetry.dev-dependencies]
isort = "^4.3.21"
mypy = "^0.761"
black = "^19.10b0"
pytest = "^5.3.2"

[tool.poetry.scripts]
fsttest = "fsttest.__main__:main"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
