[tool.poetry]
name = "pytest-shell"
version = "0.2.3"
description = "A pytest plugin for testing shell scripts and line-based processes"
authors = ["Daniel Murray <daniel@darkdisco.net>"]
license = "MIT"

# pypi stuff
classifiers = [
        'Framework :: Pytest',
        'Intended Audience :: Developers',
        'Topic :: Software Development :: Testing',
        'Operating System :: OS Independent',
        'License :: OSI Approved :: MIT License',
]
homepage = "https://hg.sr.ht/~danmur/pytest-shell"
documentation = "https://hg.sr.ht/~danmur/pytest-shell/browse/default/README.rst"
readme = 'README.rst'

[tool.poetry.dependencies]
python = ">=3.5|^2.7"

[tool.poetry.dev-dependencies]
pytest = [{version = "^5.3.3", python = "^3.5"}, {version = "^4.6.9", python = "^2.7"}]

[tool.poetry.plugins.pytest11]
shell = "pytest_shell"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
