# Base Configuration for Artella Files for Solstice

# Defines dictionary of file types (textures, model, etc) used by the project
files:
  textures:
    name: Textures
    class: solstice.files.texture.SolsticeTextureAssetFile
    extensions:
      - tx
      - png
      - jpg
      - jpeg
  model:
    name: Model
    class: solstice.files.model.SolsticeModelAssetFile
    extensions:
      - ma
  shading:
    name: Shading
    class: solstice.files.shading.SolsticeShadingAssetFile
    extensions:
      - ma
  shaders:
    name: Shaders
    class: solstice.files.shader.SolsticeShaderAssetFile
    extensions:
      - sshader
  shadersmapping:
    name: Shaders Mapping
    class: solstice.files.shader.SolsticeShaderMappingAssetFile
    extensions:
      - json
  rig:
    name: Rig
    class: solstice.files.rig.SolsticeRigAssetFile
    extensions:
      - ma
  groom:
    name: Groom
    class: solstice.files.groom.SolsticeGroomAssetFile
    extensions:
      - ma
  alembic:
    name: Alembic
    class: solstice.files.alembic.SolsticeAlembicAssetFile
    extensions:
      - abc
  gpualembic:
    name: GPU Cache
    class: solstice.files.alembic.SolsticeGpuAlembicAssetFile
    extensions:
      - abc
  standin:
    name: Standin
    class: solstice.files.standin.SolsticeStandinAssetFile
    extensions:
      - ass
  lightrig:
    name: Light Rig
    class: solstice.files.lightrig.SolsticeLightRigFile
    rule: lightrig
    template: lightrig
    extensions:
      - ma
  shader:
    name: Shader
    class: solstice.files.shader.SolsticeShaderFile
    template: shader
    extensions:
      - sshader
  master:
    name: Master Layout
    class: solstice.files.masterlayout.SolsticeMasterLayoutSequenceFile
    template: master_layout
    extensions:
      - ma