[tool.poetry]
name = "latexcornouaille"
version = "0.1.1"
description = "custom python package for latex"
authors = ["David Couronné <couronne.david@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.4"

[tool.poetry.dev-dependencies]

[tool.poetry.scripts]
latexcornouaille = 'latexcornouaille.cli:main'

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
