[tool.poetry]
name = "logx"
version = "0.1.1579232358"
authors = [ "Robert Lechte <robertlechte@gmail.com>",]
license = "Unlicense"
readme = "README.md"
description = "best practice python logging with zero config"
repository = "https://github.com/djrobstep/logx"
homepage = "https://github.com/djrobstep/logx"
[[tool.poetry.packages]]
include = "logx"

[[tool.poetry.packages]]
include = "logxutil"

[tool.poetry.dependencies]
python = "*"
pyyaml = "*"
logging_tree = "*"

[tool.poetry.dev-dependencies]
sqlbag = "*"
pytest = "*"
pytest-cov = "*"
pytest-xdist = "*"
tox = "*"
flake8 = "*"
twine = "*"
wheel = "*"
isort = "*"

[tool.poetry.dev-dependencies.black]
python = ">3.6"
version = "^18.9b0"
