language: python
python:
- '2.7'
- '3.7'
- '3.8'
install:
- pip install -U pip wheel tox-travis
script:
- tox
deploy:
  provider: pypi
  user: __token__
  password:
    secure: Kni00HkI7rLk4Vr0uMEIx4QfAEar2RB3/KANp5txaKYo3Infu1BKO1UHecypBNg/MW3FLWc1iF3B1nQRMNoPsi6mFvCUbXeiR3IZqo8NEziTq3TNijhPR7ot/vOMUk6o0qh2s/B3vONeOPKDj6JfUhEMuwkOuPgn6T5WbZoP57NtbaPpLqBxB8eO9O01cPZpHgZQQLVwIqcQebYlwMenCpNoz5N19iBxyG9lfSTrjVleLvWLcaQ4nXHJbClvh+U1vLfpI/bf8Vu9tL+J6GyxpM1BaVKoFpSja624H74NriybI1Wxg0ZFffjc6CcIVdlusNNue9d250V4Hkd1CBD6C5zVPMSZkZTw1AOtHmi/+nh5wXs9wyQyK9TK4TvHF6xGAci0dFeOeleI7npG5D7oGqr6PjjLqk0wzrKBmkpnT/4hX5WF1PlW9bLkPqiaZKI69sOZMxzNBeBVlDBKvYBqEEC2/ZJk6QDMsYLDeyMqfAl/EtaYMPWFBowOoNZswASVzMXK176GAXPe7pnX7ZFB8BY94ClURxJjW4BA9XvVVPn1cWVPbpetz1cSgjNr1MwPBNOjyRozV3IDKzMiv8JNTixjV3NSPC0fVB2awuWUgUpjurKwj0JreTuKFzpU1VHvDSajgNsZ9nTEhiYzQlTr5IiJgu7rDMp7cI1EQ+8J0YI=
  distributions: sdist bdist_wheel
  docs_dir: docs/build/html
  on:
    tags: true
    python: '3.7'
    all_branches: true
    repo: mdomke/schwifty
