# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.8
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (3, 0, 0):
    new_instancemethod = lambda func, inst, cls: _itkNMinimaMaximaImageCalculatorPython.SWIG_PyInstanceMethod_New(func)
else:
    from new import instancemethod as new_instancemethod
if version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_itkNMinimaMaximaImageCalculatorPython', [dirname(__file__)])
        except ImportError:
            import _itkNMinimaMaximaImageCalculatorPython
            return _itkNMinimaMaximaImageCalculatorPython
        if fp is not None:
            try:
                _mod = imp.load_module('_itkNMinimaMaximaImageCalculatorPython', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _itkNMinimaMaximaImageCalculatorPython = swig_import_helper()
    del swig_import_helper
else:
    import _itkNMinimaMaximaImageCalculatorPython
del version_info
try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.


def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        object.__setattr__(self, name, value)
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr_nondynamic(self, class_type, name, static=1):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    if (not static):
        return object.__getattr__(self, name)
    else:
        raise AttributeError(name)

def _swig_getattr(self, class_type, name):
    return _swig_getattr_nondynamic(self, class_type, name, 0)


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object:
        pass
    _newclass = 0



def _swig_setattr_nondynamic_method(set):
    def set_attr(self, name, value):
        if (name == "thisown"):
            return self.this.own(value)
        if hasattr(self, name) or (name == "this"):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add attributes to %s" % self)
    return set_attr


import itkIndexPython
import itkOffsetPython
import itkSizePython
import pyBasePython
import ITKCommonBasePython
import itkImageRegionPython
import itkImagePython
import itkCovariantVectorPython
import itkFixedArrayPython
import vnl_vectorPython
import stdcomplexPython
import vnl_matrixPython
import itkVectorPython
import vnl_vector_refPython
import itkRGBPixelPython
import itkSymmetricSecondRankTensorPython
import itkMatrixPython
import itkPointPython
import vnl_matrix_fixedPython
import itkRGBAPixelPython

def itkNMinimaMaximaImageCalculatorID3_New():
  return itkNMinimaMaximaImageCalculatorID3.New()


def itkNMinimaMaximaImageCalculatorIF3_New():
  return itkNMinimaMaximaImageCalculatorIF3.New()


def itkNMinimaMaximaImageCalculatorIUS3_New():
  return itkNMinimaMaximaImageCalculatorIUS3.New()


def itkNMinimaMaximaImageCalculatorIUC3_New():
  return itkNMinimaMaximaImageCalculatorIUC3.New()


def itkNMinimaMaximaImageCalculatorISS3_New():
  return itkNMinimaMaximaImageCalculatorISS3.New()


def itkNMinimaMaximaImageCalculatorID2_New():
  return itkNMinimaMaximaImageCalculatorID2.New()


def itkNMinimaMaximaImageCalculatorIF2_New():
  return itkNMinimaMaximaImageCalculatorIF2.New()


def itkNMinimaMaximaImageCalculatorIUS2_New():
  return itkNMinimaMaximaImageCalculatorIUS2.New()


def itkNMinimaMaximaImageCalculatorIUC2_New():
  return itkNMinimaMaximaImageCalculatorIUC2.New()


def itkNMinimaMaximaImageCalculatorISS2_New():
  return itkNMinimaMaximaImageCalculatorISS2.New()

class itkNMinimaMaximaImageCalculatorID2(ITKCommonBasePython.itkObject):
    """Proxy of C++ itkNMinimaMaximaImageCalculatorID2 class."""

    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr

    def __New_orig__() -> "itkNMinimaMaximaImageCalculatorID2_Pointer":
        """__New_orig__() -> itkNMinimaMaximaImageCalculatorID2_Pointer"""
        return _itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorID2___New_orig__()

    __New_orig__ = staticmethod(__New_orig__)

    def Clone(self) -> "itkNMinimaMaximaImageCalculatorID2_Pointer":
        """Clone(itkNMinimaMaximaImageCalculatorID2 self) -> itkNMinimaMaximaImageCalculatorID2_Pointer"""
        return _itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorID2_Clone(self)


    def SetImage(self, _arg: 'itkImageD2') -> "void":
        """SetImage(itkNMinimaMaximaImageCalculatorID2 self, itkImageD2 _arg)"""
        return _itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorID2_SetImage(self, _arg)


    def ComputeMinima(self) -> "void":
        """ComputeMinima(itkNMinimaMaximaImageCalculatorID2 self)"""
        return _itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorID2_ComputeMinima(self)


    def ComputeMaxima(self) -> "void":
        """ComputeMaxima(itkNMinimaMaximaImageCalculatorID2 self)"""
        return _itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorID2_ComputeMaxima(self)


    def Compute(self) -> "void":
        """Compute(itkNMinimaMaximaImageCalculatorID2 self)"""
        return _itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorID2_Compute(self)


    def GetMinima(self) -> "std::vector< double,std::allocator< double > > const &":
        """GetMinima(itkNMinimaMaximaImageCalculatorID2 self) -> vectorD"""
        return _itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorID2_GetMinima(self)


    def GetMaxima(self) -> "std::vector< double,std::allocator< double > > const &":
        """GetMaxima(itkNMinimaMaximaImageCalculatorID2 self) -> vectorD"""
        return _itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorID2_GetMaxima(self)


    def GetIndicesOfMinima(self) -> "std::vector< itkIndex2,std::allocator< itkIndex2 > > const &":
        """GetIndicesOfMinima(itkNMinimaMaximaImageCalculatorID2 self) -> std::vector< itkIndex2,std::allocator< itkIndex2 > > const &"""
        return _itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorID2_GetIndicesOfMinima(self)


    def GetIndicesOfMaxima(self) -> "std::vector< itkIndex2,std::allocator< itkIndex2 > > const &":
        """GetIndicesOfMaxima(itkNMinimaMaximaImageCalculatorID2 self) -> std::vector< itkIndex2,std::allocator< itkIndex2 > > const &"""
        return _itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorID2_GetIndicesOfMaxima(self)


    def SetRegion(self, region: 'itkImageRegion2') -> "void":
        """SetRegion(itkNMinimaMaximaImageCalculatorID2 self, itkImageRegion2 region)"""
        return _itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorID2_SetRegion(self, region)


    def GetN(self) -> "unsigned long":
        """GetN(itkNMinimaMaximaImageCalculatorID2 self) -> unsigned long"""
        return _itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorID2_GetN(self)


    def SetN(self, _arg: 'unsigned long const') -> "void":
        """SetN(itkNMinimaMaximaImageCalculatorID2 self, unsigned long const _arg)"""
        return _itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorID2_SetN(self, _arg)

    __swig_destroy__ = _itkNMinimaMaximaImageCalculatorPython.delete_itkNMinimaMaximaImageCalculatorID2

    def cast(obj: 'itkLightObject') -> "itkNMinimaMaximaImageCalculatorID2 *":
        """cast(itkLightObject obj) -> itkNMinimaMaximaImageCalculatorID2"""
        return _itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorID2_cast(obj)

    cast = staticmethod(cast)

    def New(*args, **kargs):
        """New() -> itkNMinimaMaximaImageCalculatorID2

        Create a new object of the class itkNMinimaMaximaImageCalculatorID2 and set the input and the parameters if some
        named or non-named arguments are passed to that method.

        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.

        The named parameters are used by calling the method with the same name prefixed by 'Set'.

        Ex:

          itkNMinimaMaximaImageCalculatorID2.New( reader, Threshold=10 )

        is (most of the time) equivalent to:

          obj = itkNMinimaMaximaImageCalculatorID2.New()
          obj.SetInput( 0, reader.GetOutput() )
          obj.SetThreshold( 10 )
        """
        obj = itkNMinimaMaximaImageCalculatorID2.__New_orig__()
        import itkTemplate
        itkTemplate.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)

itkNMinimaMaximaImageCalculatorID2.Clone = new_instancemethod(_itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorID2_Clone, None, itkNMinimaMaximaImageCalculatorID2)
itkNMinimaMaximaImageCalculatorID2.SetImage = new_instancemethod(_itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorID2_SetImage, None, itkNMinimaMaximaImageCalculatorID2)
itkNMinimaMaximaImageCalculatorID2.ComputeMinima = new_instancemethod(_itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorID2_ComputeMinima, None, itkNMinimaMaximaImageCalculatorID2)
itkNMinimaMaximaImageCalculatorID2.ComputeMaxima = new_instancemethod(_itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorID2_ComputeMaxima, None, itkNMinimaMaximaImageCalculatorID2)
itkNMinimaMaximaImageCalculatorID2.Compute = new_instancemethod(_itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorID2_Compute, None, itkNMinimaMaximaImageCalculatorID2)
itkNMinimaMaximaImageCalculatorID2.GetMinima = new_instancemethod(_itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorID2_GetMinima, None, itkNMinimaMaximaImageCalculatorID2)
itkNMinimaMaximaImageCalculatorID2.GetMaxima = new_instancemethod(_itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorID2_GetMaxima, None, itkNMinimaMaximaImageCalculatorID2)
itkNMinimaMaximaImageCalculatorID2.GetIndicesOfMinima = new_instancemethod(_itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorID2_GetIndicesOfMinima, None, itkNMinimaMaximaImageCalculatorID2)
itkNMinimaMaximaImageCalculatorID2.GetIndicesOfMaxima = new_instancemethod(_itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorID2_GetIndicesOfMaxima, None, itkNMinimaMaximaImageCalculatorID2)
itkNMinimaMaximaImageCalculatorID2.SetRegion = new_instancemethod(_itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorID2_SetRegion, None, itkNMinimaMaximaImageCalculatorID2)
itkNMinimaMaximaImageCalculatorID2.GetN = new_instancemethod(_itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorID2_GetN, None, itkNMinimaMaximaImageCalculatorID2)
itkNMinimaMaximaImageCalculatorID2.SetN = new_instancemethod(_itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorID2_SetN, None, itkNMinimaMaximaImageCalculatorID2)
itkNMinimaMaximaImageCalculatorID2_swigregister = _itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorID2_swigregister
itkNMinimaMaximaImageCalculatorID2_swigregister(itkNMinimaMaximaImageCalculatorID2)

def itkNMinimaMaximaImageCalculatorID2___New_orig__() -> "itkNMinimaMaximaImageCalculatorID2_Pointer":
    """itkNMinimaMaximaImageCalculatorID2___New_orig__() -> itkNMinimaMaximaImageCalculatorID2_Pointer"""
    return _itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorID2___New_orig__()

def itkNMinimaMaximaImageCalculatorID2_cast(obj: 'itkLightObject') -> "itkNMinimaMaximaImageCalculatorID2 *":
    """itkNMinimaMaximaImageCalculatorID2_cast(itkLightObject obj) -> itkNMinimaMaximaImageCalculatorID2"""
    return _itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorID2_cast(obj)

class itkNMinimaMaximaImageCalculatorID3(ITKCommonBasePython.itkObject):
    """Proxy of C++ itkNMinimaMaximaImageCalculatorID3 class."""

    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr

    def __New_orig__() -> "itkNMinimaMaximaImageCalculatorID3_Pointer":
        """__New_orig__() -> itkNMinimaMaximaImageCalculatorID3_Pointer"""
        return _itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorID3___New_orig__()

    __New_orig__ = staticmethod(__New_orig__)

    def Clone(self) -> "itkNMinimaMaximaImageCalculatorID3_Pointer":
        """Clone(itkNMinimaMaximaImageCalculatorID3 self) -> itkNMinimaMaximaImageCalculatorID3_Pointer"""
        return _itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorID3_Clone(self)


    def SetImage(self, _arg: 'itkImageD3') -> "void":
        """SetImage(itkNMinimaMaximaImageCalculatorID3 self, itkImageD3 _arg)"""
        return _itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorID3_SetImage(self, _arg)


    def ComputeMinima(self) -> "void":
        """ComputeMinima(itkNMinimaMaximaImageCalculatorID3 self)"""
        return _itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorID3_ComputeMinima(self)


    def ComputeMaxima(self) -> "void":
        """ComputeMaxima(itkNMinimaMaximaImageCalculatorID3 self)"""
        return _itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorID3_ComputeMaxima(self)


    def Compute(self) -> "void":
        """Compute(itkNMinimaMaximaImageCalculatorID3 self)"""
        return _itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorID3_Compute(self)


    def GetMinima(self) -> "std::vector< double,std::allocator< double > > const &":
        """GetMinima(itkNMinimaMaximaImageCalculatorID3 self) -> vectorD"""
        return _itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorID3_GetMinima(self)


    def GetMaxima(self) -> "std::vector< double,std::allocator< double > > const &":
        """GetMaxima(itkNMinimaMaximaImageCalculatorID3 self) -> vectorD"""
        return _itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorID3_GetMaxima(self)


    def GetIndicesOfMinima(self) -> "std::vector< itkIndex3,std::allocator< itkIndex3 > > const &":
        """GetIndicesOfMinima(itkNMinimaMaximaImageCalculatorID3 self) -> std::vector< itkIndex3,std::allocator< itkIndex3 > > const &"""
        return _itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorID3_GetIndicesOfMinima(self)


    def GetIndicesOfMaxima(self) -> "std::vector< itkIndex3,std::allocator< itkIndex3 > > const &":
        """GetIndicesOfMaxima(itkNMinimaMaximaImageCalculatorID3 self) -> std::vector< itkIndex3,std::allocator< itkIndex3 > > const &"""
        return _itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorID3_GetIndicesOfMaxima(self)


    def SetRegion(self, region: 'itkImageRegion3') -> "void":
        """SetRegion(itkNMinimaMaximaImageCalculatorID3 self, itkImageRegion3 region)"""
        return _itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorID3_SetRegion(self, region)


    def GetN(self) -> "unsigned long":
        """GetN(itkNMinimaMaximaImageCalculatorID3 self) -> unsigned long"""
        return _itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorID3_GetN(self)


    def SetN(self, _arg: 'unsigned long const') -> "void":
        """SetN(itkNMinimaMaximaImageCalculatorID3 self, unsigned long const _arg)"""
        return _itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorID3_SetN(self, _arg)

    __swig_destroy__ = _itkNMinimaMaximaImageCalculatorPython.delete_itkNMinimaMaximaImageCalculatorID3

    def cast(obj: 'itkLightObject') -> "itkNMinimaMaximaImageCalculatorID3 *":
        """cast(itkLightObject obj) -> itkNMinimaMaximaImageCalculatorID3"""
        return _itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorID3_cast(obj)

    cast = staticmethod(cast)

    def New(*args, **kargs):
        """New() -> itkNMinimaMaximaImageCalculatorID3

        Create a new object of the class itkNMinimaMaximaImageCalculatorID3 and set the input and the parameters if some
        named or non-named arguments are passed to that method.

        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.

        The named parameters are used by calling the method with the same name prefixed by 'Set'.

        Ex:

          itkNMinimaMaximaImageCalculatorID3.New( reader, Threshold=10 )

        is (most of the time) equivalent to:

          obj = itkNMinimaMaximaImageCalculatorID3.New()
          obj.SetInput( 0, reader.GetOutput() )
          obj.SetThreshold( 10 )
        """
        obj = itkNMinimaMaximaImageCalculatorID3.__New_orig__()
        import itkTemplate
        itkTemplate.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)

itkNMinimaMaximaImageCalculatorID3.Clone = new_instancemethod(_itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorID3_Clone, None, itkNMinimaMaximaImageCalculatorID3)
itkNMinimaMaximaImageCalculatorID3.SetImage = new_instancemethod(_itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorID3_SetImage, None, itkNMinimaMaximaImageCalculatorID3)
itkNMinimaMaximaImageCalculatorID3.ComputeMinima = new_instancemethod(_itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorID3_ComputeMinima, None, itkNMinimaMaximaImageCalculatorID3)
itkNMinimaMaximaImageCalculatorID3.ComputeMaxima = new_instancemethod(_itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorID3_ComputeMaxima, None, itkNMinimaMaximaImageCalculatorID3)
itkNMinimaMaximaImageCalculatorID3.Compute = new_instancemethod(_itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorID3_Compute, None, itkNMinimaMaximaImageCalculatorID3)
itkNMinimaMaximaImageCalculatorID3.GetMinima = new_instancemethod(_itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorID3_GetMinima, None, itkNMinimaMaximaImageCalculatorID3)
itkNMinimaMaximaImageCalculatorID3.GetMaxima = new_instancemethod(_itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorID3_GetMaxima, None, itkNMinimaMaximaImageCalculatorID3)
itkNMinimaMaximaImageCalculatorID3.GetIndicesOfMinima = new_instancemethod(_itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorID3_GetIndicesOfMinima, None, itkNMinimaMaximaImageCalculatorID3)
itkNMinimaMaximaImageCalculatorID3.GetIndicesOfMaxima = new_instancemethod(_itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorID3_GetIndicesOfMaxima, None, itkNMinimaMaximaImageCalculatorID3)
itkNMinimaMaximaImageCalculatorID3.SetRegion = new_instancemethod(_itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorID3_SetRegion, None, itkNMinimaMaximaImageCalculatorID3)
itkNMinimaMaximaImageCalculatorID3.GetN = new_instancemethod(_itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorID3_GetN, None, itkNMinimaMaximaImageCalculatorID3)
itkNMinimaMaximaImageCalculatorID3.SetN = new_instancemethod(_itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorID3_SetN, None, itkNMinimaMaximaImageCalculatorID3)
itkNMinimaMaximaImageCalculatorID3_swigregister = _itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorID3_swigregister
itkNMinimaMaximaImageCalculatorID3_swigregister(itkNMinimaMaximaImageCalculatorID3)

def itkNMinimaMaximaImageCalculatorID3___New_orig__() -> "itkNMinimaMaximaImageCalculatorID3_Pointer":
    """itkNMinimaMaximaImageCalculatorID3___New_orig__() -> itkNMinimaMaximaImageCalculatorID3_Pointer"""
    return _itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorID3___New_orig__()

def itkNMinimaMaximaImageCalculatorID3_cast(obj: 'itkLightObject') -> "itkNMinimaMaximaImageCalculatorID3 *":
    """itkNMinimaMaximaImageCalculatorID3_cast(itkLightObject obj) -> itkNMinimaMaximaImageCalculatorID3"""
    return _itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorID3_cast(obj)

class itkNMinimaMaximaImageCalculatorIF2(ITKCommonBasePython.itkObject):
    """Proxy of C++ itkNMinimaMaximaImageCalculatorIF2 class."""

    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr

    def __New_orig__() -> "itkNMinimaMaximaImageCalculatorIF2_Pointer":
        """__New_orig__() -> itkNMinimaMaximaImageCalculatorIF2_Pointer"""
        return _itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorIF2___New_orig__()

    __New_orig__ = staticmethod(__New_orig__)

    def Clone(self) -> "itkNMinimaMaximaImageCalculatorIF2_Pointer":
        """Clone(itkNMinimaMaximaImageCalculatorIF2 self) -> itkNMinimaMaximaImageCalculatorIF2_Pointer"""
        return _itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorIF2_Clone(self)


    def SetImage(self, _arg: 'itkImageF2') -> "void":
        """SetImage(itkNMinimaMaximaImageCalculatorIF2 self, itkImageF2 _arg)"""
        return _itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorIF2_SetImage(self, _arg)


    def ComputeMinima(self) -> "void":
        """ComputeMinima(itkNMinimaMaximaImageCalculatorIF2 self)"""
        return _itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorIF2_ComputeMinima(self)


    def ComputeMaxima(self) -> "void":
        """ComputeMaxima(itkNMinimaMaximaImageCalculatorIF2 self)"""
        return _itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorIF2_ComputeMaxima(self)


    def Compute(self) -> "void":
        """Compute(itkNMinimaMaximaImageCalculatorIF2 self)"""
        return _itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorIF2_Compute(self)


    def GetMinima(self) -> "std::vector< float,std::allocator< float > > const &":
        """GetMinima(itkNMinimaMaximaImageCalculatorIF2 self) -> vectorF"""
        return _itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorIF2_GetMinima(self)


    def GetMaxima(self) -> "std::vector< float,std::allocator< float > > const &":
        """GetMaxima(itkNMinimaMaximaImageCalculatorIF2 self) -> vectorF"""
        return _itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorIF2_GetMaxima(self)


    def GetIndicesOfMinima(self) -> "std::vector< itkIndex2,std::allocator< itkIndex2 > > const &":
        """GetIndicesOfMinima(itkNMinimaMaximaImageCalculatorIF2 self) -> std::vector< itkIndex2,std::allocator< itkIndex2 > > const &"""
        return _itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorIF2_GetIndicesOfMinima(self)


    def GetIndicesOfMaxima(self) -> "std::vector< itkIndex2,std::allocator< itkIndex2 > > const &":
        """GetIndicesOfMaxima(itkNMinimaMaximaImageCalculatorIF2 self) -> std::vector< itkIndex2,std::allocator< itkIndex2 > > const &"""
        return _itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorIF2_GetIndicesOfMaxima(self)


    def SetRegion(self, region: 'itkImageRegion2') -> "void":
        """SetRegion(itkNMinimaMaximaImageCalculatorIF2 self, itkImageRegion2 region)"""
        return _itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorIF2_SetRegion(self, region)


    def GetN(self) -> "unsigned long":
        """GetN(itkNMinimaMaximaImageCalculatorIF2 self) -> unsigned long"""
        return _itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorIF2_GetN(self)


    def SetN(self, _arg: 'unsigned long const') -> "void":
        """SetN(itkNMinimaMaximaImageCalculatorIF2 self, unsigned long const _arg)"""
        return _itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorIF2_SetN(self, _arg)

    __swig_destroy__ = _itkNMinimaMaximaImageCalculatorPython.delete_itkNMinimaMaximaImageCalculatorIF2

    def cast(obj: 'itkLightObject') -> "itkNMinimaMaximaImageCalculatorIF2 *":
        """cast(itkLightObject obj) -> itkNMinimaMaximaImageCalculatorIF2"""
        return _itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorIF2_cast(obj)

    cast = staticmethod(cast)

    def New(*args, **kargs):
        """New() -> itkNMinimaMaximaImageCalculatorIF2

        Create a new object of the class itkNMinimaMaximaImageCalculatorIF2 and set the input and the parameters if some
        named or non-named arguments are passed to that method.

        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.

        The named parameters are used by calling the method with the same name prefixed by 'Set'.

        Ex:

          itkNMinimaMaximaImageCalculatorIF2.New( reader, Threshold=10 )

        is (most of the time) equivalent to:

          obj = itkNMinimaMaximaImageCalculatorIF2.New()
          obj.SetInput( 0, reader.GetOutput() )
          obj.SetThreshold( 10 )
        """
        obj = itkNMinimaMaximaImageCalculatorIF2.__New_orig__()
        import itkTemplate
        itkTemplate.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)

itkNMinimaMaximaImageCalculatorIF2.Clone = new_instancemethod(_itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorIF2_Clone, None, itkNMinimaMaximaImageCalculatorIF2)
itkNMinimaMaximaImageCalculatorIF2.SetImage = new_instancemethod(_itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorIF2_SetImage, None, itkNMinimaMaximaImageCalculatorIF2)
itkNMinimaMaximaImageCalculatorIF2.ComputeMinima = new_instancemethod(_itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorIF2_ComputeMinima, None, itkNMinimaMaximaImageCalculatorIF2)
itkNMinimaMaximaImageCalculatorIF2.ComputeMaxima = new_instancemethod(_itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorIF2_ComputeMaxima, None, itkNMinimaMaximaImageCalculatorIF2)
itkNMinimaMaximaImageCalculatorIF2.Compute = new_instancemethod(_itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorIF2_Compute, None, itkNMinimaMaximaImageCalculatorIF2)
itkNMinimaMaximaImageCalculatorIF2.GetMinima = new_instancemethod(_itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorIF2_GetMinima, None, itkNMinimaMaximaImageCalculatorIF2)
itkNMinimaMaximaImageCalculatorIF2.GetMaxima = new_instancemethod(_itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorIF2_GetMaxima, None, itkNMinimaMaximaImageCalculatorIF2)
itkNMinimaMaximaImageCalculatorIF2.GetIndicesOfMinima = new_instancemethod(_itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorIF2_GetIndicesOfMinima, None, itkNMinimaMaximaImageCalculatorIF2)
itkNMinimaMaximaImageCalculatorIF2.GetIndicesOfMaxima = new_instancemethod(_itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorIF2_GetIndicesOfMaxima, None, itkNMinimaMaximaImageCalculatorIF2)
itkNMinimaMaximaImageCalculatorIF2.SetRegion = new_instancemethod(_itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorIF2_SetRegion, None, itkNMinimaMaximaImageCalculatorIF2)
itkNMinimaMaximaImageCalculatorIF2.GetN = new_instancemethod(_itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorIF2_GetN, None, itkNMinimaMaximaImageCalculatorIF2)
itkNMinimaMaximaImageCalculatorIF2.SetN = new_instancemethod(_itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorIF2_SetN, None, itkNMinimaMaximaImageCalculatorIF2)
itkNMinimaMaximaImageCalculatorIF2_swigregister = _itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorIF2_swigregister
itkNMinimaMaximaImageCalculatorIF2_swigregister(itkNMinimaMaximaImageCalculatorIF2)

def itkNMinimaMaximaImageCalculatorIF2___New_orig__() -> "itkNMinimaMaximaImageCalculatorIF2_Pointer":
    """itkNMinimaMaximaImageCalculatorIF2___New_orig__() -> itkNMinimaMaximaImageCalculatorIF2_Pointer"""
    return _itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorIF2___New_orig__()

def itkNMinimaMaximaImageCalculatorIF2_cast(obj: 'itkLightObject') -> "itkNMinimaMaximaImageCalculatorIF2 *":
    """itkNMinimaMaximaImageCalculatorIF2_cast(itkLightObject obj) -> itkNMinimaMaximaImageCalculatorIF2"""
    return _itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorIF2_cast(obj)

class itkNMinimaMaximaImageCalculatorIF3(ITKCommonBasePython.itkObject):
    """Proxy of C++ itkNMinimaMaximaImageCalculatorIF3 class."""

    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr

    def __New_orig__() -> "itkNMinimaMaximaImageCalculatorIF3_Pointer":
        """__New_orig__() -> itkNMinimaMaximaImageCalculatorIF3_Pointer"""
        return _itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorIF3___New_orig__()

    __New_orig__ = staticmethod(__New_orig__)

    def Clone(self) -> "itkNMinimaMaximaImageCalculatorIF3_Pointer":
        """Clone(itkNMinimaMaximaImageCalculatorIF3 self) -> itkNMinimaMaximaImageCalculatorIF3_Pointer"""
        return _itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorIF3_Clone(self)


    def SetImage(self, _arg: 'itkImageF3') -> "void":
        """SetImage(itkNMinimaMaximaImageCalculatorIF3 self, itkImageF3 _arg)"""
        return _itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorIF3_SetImage(self, _arg)


    def ComputeMinima(self) -> "void":
        """ComputeMinima(itkNMinimaMaximaImageCalculatorIF3 self)"""
        return _itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorIF3_ComputeMinima(self)


    def ComputeMaxima(self) -> "void":
        """ComputeMaxima(itkNMinimaMaximaImageCalculatorIF3 self)"""
        return _itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorIF3_ComputeMaxima(self)


    def Compute(self) -> "void":
        """Compute(itkNMinimaMaximaImageCalculatorIF3 self)"""
        return _itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorIF3_Compute(self)


    def GetMinima(self) -> "std::vector< float,std::allocator< float > > const &":
        """GetMinima(itkNMinimaMaximaImageCalculatorIF3 self) -> vectorF"""
        return _itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorIF3_GetMinima(self)


    def GetMaxima(self) -> "std::vector< float,std::allocator< float > > const &":
        """GetMaxima(itkNMinimaMaximaImageCalculatorIF3 self) -> vectorF"""
        return _itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorIF3_GetMaxima(self)


    def GetIndicesOfMinima(self) -> "std::vector< itkIndex3,std::allocator< itkIndex3 > > const &":
        """GetIndicesOfMinima(itkNMinimaMaximaImageCalculatorIF3 self) -> std::vector< itkIndex3,std::allocator< itkIndex3 > > const &"""
        return _itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorIF3_GetIndicesOfMinima(self)


    def GetIndicesOfMaxima(self) -> "std::vector< itkIndex3,std::allocator< itkIndex3 > > const &":
        """GetIndicesOfMaxima(itkNMinimaMaximaImageCalculatorIF3 self) -> std::vector< itkIndex3,std::allocator< itkIndex3 > > const &"""
        return _itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorIF3_GetIndicesOfMaxima(self)


    def SetRegion(self, region: 'itkImageRegion3') -> "void":
        """SetRegion(itkNMinimaMaximaImageCalculatorIF3 self, itkImageRegion3 region)"""
        return _itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorIF3_SetRegion(self, region)


    def GetN(self) -> "unsigned long":
        """GetN(itkNMinimaMaximaImageCalculatorIF3 self) -> unsigned long"""
        return _itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorIF3_GetN(self)


    def SetN(self, _arg: 'unsigned long const') -> "void":
        """SetN(itkNMinimaMaximaImageCalculatorIF3 self, unsigned long const _arg)"""
        return _itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorIF3_SetN(self, _arg)

    __swig_destroy__ = _itkNMinimaMaximaImageCalculatorPython.delete_itkNMinimaMaximaImageCalculatorIF3

    def cast(obj: 'itkLightObject') -> "itkNMinimaMaximaImageCalculatorIF3 *":
        """cast(itkLightObject obj) -> itkNMinimaMaximaImageCalculatorIF3"""
        return _itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorIF3_cast(obj)

    cast = staticmethod(cast)

    def New(*args, **kargs):
        """New() -> itkNMinimaMaximaImageCalculatorIF3

        Create a new object of the class itkNMinimaMaximaImageCalculatorIF3 and set the input and the parameters if some
        named or non-named arguments are passed to that method.

        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.

        The named parameters are used by calling the method with the same name prefixed by 'Set'.

        Ex:

          itkNMinimaMaximaImageCalculatorIF3.New( reader, Threshold=10 )

        is (most of the time) equivalent to:

          obj = itkNMinimaMaximaImageCalculatorIF3.New()
          obj.SetInput( 0, reader.GetOutput() )
          obj.SetThreshold( 10 )
        """
        obj = itkNMinimaMaximaImageCalculatorIF3.__New_orig__()
        import itkTemplate
        itkTemplate.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)

itkNMinimaMaximaImageCalculatorIF3.Clone = new_instancemethod(_itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorIF3_Clone, None, itkNMinimaMaximaImageCalculatorIF3)
itkNMinimaMaximaImageCalculatorIF3.SetImage = new_instancemethod(_itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorIF3_SetImage, None, itkNMinimaMaximaImageCalculatorIF3)
itkNMinimaMaximaImageCalculatorIF3.ComputeMinima = new_instancemethod(_itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorIF3_ComputeMinima, None, itkNMinimaMaximaImageCalculatorIF3)
itkNMinimaMaximaImageCalculatorIF3.ComputeMaxima = new_instancemethod(_itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorIF3_ComputeMaxima, None, itkNMinimaMaximaImageCalculatorIF3)
itkNMinimaMaximaImageCalculatorIF3.Compute = new_instancemethod(_itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorIF3_Compute, None, itkNMinimaMaximaImageCalculatorIF3)
itkNMinimaMaximaImageCalculatorIF3.GetMinima = new_instancemethod(_itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorIF3_GetMinima, None, itkNMinimaMaximaImageCalculatorIF3)
itkNMinimaMaximaImageCalculatorIF3.GetMaxima = new_instancemethod(_itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorIF3_GetMaxima, None, itkNMinimaMaximaImageCalculatorIF3)
itkNMinimaMaximaImageCalculatorIF3.GetIndicesOfMinima = new_instancemethod(_itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorIF3_GetIndicesOfMinima, None, itkNMinimaMaximaImageCalculatorIF3)
itkNMinimaMaximaImageCalculatorIF3.GetIndicesOfMaxima = new_instancemethod(_itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorIF3_GetIndicesOfMaxima, None, itkNMinimaMaximaImageCalculatorIF3)
itkNMinimaMaximaImageCalculatorIF3.SetRegion = new_instancemethod(_itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorIF3_SetRegion, None, itkNMinimaMaximaImageCalculatorIF3)
itkNMinimaMaximaImageCalculatorIF3.GetN = new_instancemethod(_itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorIF3_GetN, None, itkNMinimaMaximaImageCalculatorIF3)
itkNMinimaMaximaImageCalculatorIF3.SetN = new_instancemethod(_itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorIF3_SetN, None, itkNMinimaMaximaImageCalculatorIF3)
itkNMinimaMaximaImageCalculatorIF3_swigregister = _itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorIF3_swigregister
itkNMinimaMaximaImageCalculatorIF3_swigregister(itkNMinimaMaximaImageCalculatorIF3)

def itkNMinimaMaximaImageCalculatorIF3___New_orig__() -> "itkNMinimaMaximaImageCalculatorIF3_Pointer":
    """itkNMinimaMaximaImageCalculatorIF3___New_orig__() -> itkNMinimaMaximaImageCalculatorIF3_Pointer"""
    return _itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorIF3___New_orig__()

def itkNMinimaMaximaImageCalculatorIF3_cast(obj: 'itkLightObject') -> "itkNMinimaMaximaImageCalculatorIF3 *":
    """itkNMinimaMaximaImageCalculatorIF3_cast(itkLightObject obj) -> itkNMinimaMaximaImageCalculatorIF3"""
    return _itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorIF3_cast(obj)

class itkNMinimaMaximaImageCalculatorISS2(ITKCommonBasePython.itkObject):
    """Proxy of C++ itkNMinimaMaximaImageCalculatorISS2 class."""

    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr

    def __New_orig__() -> "itkNMinimaMaximaImageCalculatorISS2_Pointer":
        """__New_orig__() -> itkNMinimaMaximaImageCalculatorISS2_Pointer"""
        return _itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorISS2___New_orig__()

    __New_orig__ = staticmethod(__New_orig__)

    def Clone(self) -> "itkNMinimaMaximaImageCalculatorISS2_Pointer":
        """Clone(itkNMinimaMaximaImageCalculatorISS2 self) -> itkNMinimaMaximaImageCalculatorISS2_Pointer"""
        return _itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorISS2_Clone(self)


    def SetImage(self, _arg: 'itkImageSS2') -> "void":
        """SetImage(itkNMinimaMaximaImageCalculatorISS2 self, itkImageSS2 _arg)"""
        return _itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorISS2_SetImage(self, _arg)


    def ComputeMinima(self) -> "void":
        """ComputeMinima(itkNMinimaMaximaImageCalculatorISS2 self)"""
        return _itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorISS2_ComputeMinima(self)


    def ComputeMaxima(self) -> "void":
        """ComputeMaxima(itkNMinimaMaximaImageCalculatorISS2 self)"""
        return _itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorISS2_ComputeMaxima(self)


    def Compute(self) -> "void":
        """Compute(itkNMinimaMaximaImageCalculatorISS2 self)"""
        return _itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorISS2_Compute(self)


    def GetMinima(self) -> "std::vector< short,std::allocator< short > > const &":
        """GetMinima(itkNMinimaMaximaImageCalculatorISS2 self) -> vectorSS"""
        return _itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorISS2_GetMinima(self)


    def GetMaxima(self) -> "std::vector< short,std::allocator< short > > const &":
        """GetMaxima(itkNMinimaMaximaImageCalculatorISS2 self) -> vectorSS"""
        return _itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorISS2_GetMaxima(self)


    def GetIndicesOfMinima(self) -> "std::vector< itkIndex2,std::allocator< itkIndex2 > > const &":
        """GetIndicesOfMinima(itkNMinimaMaximaImageCalculatorISS2 self) -> std::vector< itkIndex2,std::allocator< itkIndex2 > > const &"""
        return _itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorISS2_GetIndicesOfMinima(self)


    def GetIndicesOfMaxima(self) -> "std::vector< itkIndex2,std::allocator< itkIndex2 > > const &":
        """GetIndicesOfMaxima(itkNMinimaMaximaImageCalculatorISS2 self) -> std::vector< itkIndex2,std::allocator< itkIndex2 > > const &"""
        return _itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorISS2_GetIndicesOfMaxima(self)


    def SetRegion(self, region: 'itkImageRegion2') -> "void":
        """SetRegion(itkNMinimaMaximaImageCalculatorISS2 self, itkImageRegion2 region)"""
        return _itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorISS2_SetRegion(self, region)


    def GetN(self) -> "unsigned long":
        """GetN(itkNMinimaMaximaImageCalculatorISS2 self) -> unsigned long"""
        return _itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorISS2_GetN(self)


    def SetN(self, _arg: 'unsigned long const') -> "void":
        """SetN(itkNMinimaMaximaImageCalculatorISS2 self, unsigned long const _arg)"""
        return _itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorISS2_SetN(self, _arg)

    __swig_destroy__ = _itkNMinimaMaximaImageCalculatorPython.delete_itkNMinimaMaximaImageCalculatorISS2

    def cast(obj: 'itkLightObject') -> "itkNMinimaMaximaImageCalculatorISS2 *":
        """cast(itkLightObject obj) -> itkNMinimaMaximaImageCalculatorISS2"""
        return _itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorISS2_cast(obj)

    cast = staticmethod(cast)

    def New(*args, **kargs):
        """New() -> itkNMinimaMaximaImageCalculatorISS2

        Create a new object of the class itkNMinimaMaximaImageCalculatorISS2 and set the input and the parameters if some
        named or non-named arguments are passed to that method.

        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.

        The named parameters are used by calling the method with the same name prefixed by 'Set'.

        Ex:

          itkNMinimaMaximaImageCalculatorISS2.New( reader, Threshold=10 )

        is (most of the time) equivalent to:

          obj = itkNMinimaMaximaImageCalculatorISS2.New()
          obj.SetInput( 0, reader.GetOutput() )
          obj.SetThreshold( 10 )
        """
        obj = itkNMinimaMaximaImageCalculatorISS2.__New_orig__()
        import itkTemplate
        itkTemplate.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)

itkNMinimaMaximaImageCalculatorISS2.Clone = new_instancemethod(_itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorISS2_Clone, None, itkNMinimaMaximaImageCalculatorISS2)
itkNMinimaMaximaImageCalculatorISS2.SetImage = new_instancemethod(_itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorISS2_SetImage, None, itkNMinimaMaximaImageCalculatorISS2)
itkNMinimaMaximaImageCalculatorISS2.ComputeMinima = new_instancemethod(_itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorISS2_ComputeMinima, None, itkNMinimaMaximaImageCalculatorISS2)
itkNMinimaMaximaImageCalculatorISS2.ComputeMaxima = new_instancemethod(_itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorISS2_ComputeMaxima, None, itkNMinimaMaximaImageCalculatorISS2)
itkNMinimaMaximaImageCalculatorISS2.Compute = new_instancemethod(_itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorISS2_Compute, None, itkNMinimaMaximaImageCalculatorISS2)
itkNMinimaMaximaImageCalculatorISS2.GetMinima = new_instancemethod(_itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorISS2_GetMinima, None, itkNMinimaMaximaImageCalculatorISS2)
itkNMinimaMaximaImageCalculatorISS2.GetMaxima = new_instancemethod(_itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorISS2_GetMaxima, None, itkNMinimaMaximaImageCalculatorISS2)
itkNMinimaMaximaImageCalculatorISS2.GetIndicesOfMinima = new_instancemethod(_itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorISS2_GetIndicesOfMinima, None, itkNMinimaMaximaImageCalculatorISS2)
itkNMinimaMaximaImageCalculatorISS2.GetIndicesOfMaxima = new_instancemethod(_itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorISS2_GetIndicesOfMaxima, None, itkNMinimaMaximaImageCalculatorISS2)
itkNMinimaMaximaImageCalculatorISS2.SetRegion = new_instancemethod(_itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorISS2_SetRegion, None, itkNMinimaMaximaImageCalculatorISS2)
itkNMinimaMaximaImageCalculatorISS2.GetN = new_instancemethod(_itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorISS2_GetN, None, itkNMinimaMaximaImageCalculatorISS2)
itkNMinimaMaximaImageCalculatorISS2.SetN = new_instancemethod(_itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorISS2_SetN, None, itkNMinimaMaximaImageCalculatorISS2)
itkNMinimaMaximaImageCalculatorISS2_swigregister = _itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorISS2_swigregister
itkNMinimaMaximaImageCalculatorISS2_swigregister(itkNMinimaMaximaImageCalculatorISS2)

def itkNMinimaMaximaImageCalculatorISS2___New_orig__() -> "itkNMinimaMaximaImageCalculatorISS2_Pointer":
    """itkNMinimaMaximaImageCalculatorISS2___New_orig__() -> itkNMinimaMaximaImageCalculatorISS2_Pointer"""
    return _itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorISS2___New_orig__()

def itkNMinimaMaximaImageCalculatorISS2_cast(obj: 'itkLightObject') -> "itkNMinimaMaximaImageCalculatorISS2 *":
    """itkNMinimaMaximaImageCalculatorISS2_cast(itkLightObject obj) -> itkNMinimaMaximaImageCalculatorISS2"""
    return _itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorISS2_cast(obj)

class itkNMinimaMaximaImageCalculatorISS3(ITKCommonBasePython.itkObject):
    """Proxy of C++ itkNMinimaMaximaImageCalculatorISS3 class."""

    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr

    def __New_orig__() -> "itkNMinimaMaximaImageCalculatorISS3_Pointer":
        """__New_orig__() -> itkNMinimaMaximaImageCalculatorISS3_Pointer"""
        return _itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorISS3___New_orig__()

    __New_orig__ = staticmethod(__New_orig__)

    def Clone(self) -> "itkNMinimaMaximaImageCalculatorISS3_Pointer":
        """Clone(itkNMinimaMaximaImageCalculatorISS3 self) -> itkNMinimaMaximaImageCalculatorISS3_Pointer"""
        return _itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorISS3_Clone(self)


    def SetImage(self, _arg: 'itkImageSS3') -> "void":
        """SetImage(itkNMinimaMaximaImageCalculatorISS3 self, itkImageSS3 _arg)"""
        return _itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorISS3_SetImage(self, _arg)


    def ComputeMinima(self) -> "void":
        """ComputeMinima(itkNMinimaMaximaImageCalculatorISS3 self)"""
        return _itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorISS3_ComputeMinima(self)


    def ComputeMaxima(self) -> "void":
        """ComputeMaxima(itkNMinimaMaximaImageCalculatorISS3 self)"""
        return _itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorISS3_ComputeMaxima(self)


    def Compute(self) -> "void":
        """Compute(itkNMinimaMaximaImageCalculatorISS3 self)"""
        return _itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorISS3_Compute(self)


    def GetMinima(self) -> "std::vector< short,std::allocator< short > > const &":
        """GetMinima(itkNMinimaMaximaImageCalculatorISS3 self) -> vectorSS"""
        return _itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorISS3_GetMinima(self)


    def GetMaxima(self) -> "std::vector< short,std::allocator< short > > const &":
        """GetMaxima(itkNMinimaMaximaImageCalculatorISS3 self) -> vectorSS"""
        return _itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorISS3_GetMaxima(self)


    def GetIndicesOfMinima(self) -> "std::vector< itkIndex3,std::allocator< itkIndex3 > > const &":
        """GetIndicesOfMinima(itkNMinimaMaximaImageCalculatorISS3 self) -> std::vector< itkIndex3,std::allocator< itkIndex3 > > const &"""
        return _itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorISS3_GetIndicesOfMinima(self)


    def GetIndicesOfMaxima(self) -> "std::vector< itkIndex3,std::allocator< itkIndex3 > > const &":
        """GetIndicesOfMaxima(itkNMinimaMaximaImageCalculatorISS3 self) -> std::vector< itkIndex3,std::allocator< itkIndex3 > > const &"""
        return _itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorISS3_GetIndicesOfMaxima(self)


    def SetRegion(self, region: 'itkImageRegion3') -> "void":
        """SetRegion(itkNMinimaMaximaImageCalculatorISS3 self, itkImageRegion3 region)"""
        return _itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorISS3_SetRegion(self, region)


    def GetN(self) -> "unsigned long":
        """GetN(itkNMinimaMaximaImageCalculatorISS3 self) -> unsigned long"""
        return _itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorISS3_GetN(self)


    def SetN(self, _arg: 'unsigned long const') -> "void":
        """SetN(itkNMinimaMaximaImageCalculatorISS3 self, unsigned long const _arg)"""
        return _itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorISS3_SetN(self, _arg)

    __swig_destroy__ = _itkNMinimaMaximaImageCalculatorPython.delete_itkNMinimaMaximaImageCalculatorISS3

    def cast(obj: 'itkLightObject') -> "itkNMinimaMaximaImageCalculatorISS3 *":
        """cast(itkLightObject obj) -> itkNMinimaMaximaImageCalculatorISS3"""
        return _itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorISS3_cast(obj)

    cast = staticmethod(cast)

    def New(*args, **kargs):
        """New() -> itkNMinimaMaximaImageCalculatorISS3

        Create a new object of the class itkNMinimaMaximaImageCalculatorISS3 and set the input and the parameters if some
        named or non-named arguments are passed to that method.

        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.

        The named parameters are used by calling the method with the same name prefixed by 'Set'.

        Ex:

          itkNMinimaMaximaImageCalculatorISS3.New( reader, Threshold=10 )

        is (most of the time) equivalent to:

          obj = itkNMinimaMaximaImageCalculatorISS3.New()
          obj.SetInput( 0, reader.GetOutput() )
          obj.SetThreshold( 10 )
        """
        obj = itkNMinimaMaximaImageCalculatorISS3.__New_orig__()
        import itkTemplate
        itkTemplate.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)

itkNMinimaMaximaImageCalculatorISS3.Clone = new_instancemethod(_itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorISS3_Clone, None, itkNMinimaMaximaImageCalculatorISS3)
itkNMinimaMaximaImageCalculatorISS3.SetImage = new_instancemethod(_itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorISS3_SetImage, None, itkNMinimaMaximaImageCalculatorISS3)
itkNMinimaMaximaImageCalculatorISS3.ComputeMinima = new_instancemethod(_itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorISS3_ComputeMinima, None, itkNMinimaMaximaImageCalculatorISS3)
itkNMinimaMaximaImageCalculatorISS3.ComputeMaxima = new_instancemethod(_itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorISS3_ComputeMaxima, None, itkNMinimaMaximaImageCalculatorISS3)
itkNMinimaMaximaImageCalculatorISS3.Compute = new_instancemethod(_itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorISS3_Compute, None, itkNMinimaMaximaImageCalculatorISS3)
itkNMinimaMaximaImageCalculatorISS3.GetMinima = new_instancemethod(_itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorISS3_GetMinima, None, itkNMinimaMaximaImageCalculatorISS3)
itkNMinimaMaximaImageCalculatorISS3.GetMaxima = new_instancemethod(_itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorISS3_GetMaxima, None, itkNMinimaMaximaImageCalculatorISS3)
itkNMinimaMaximaImageCalculatorISS3.GetIndicesOfMinima = new_instancemethod(_itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorISS3_GetIndicesOfMinima, None, itkNMinimaMaximaImageCalculatorISS3)
itkNMinimaMaximaImageCalculatorISS3.GetIndicesOfMaxima = new_instancemethod(_itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorISS3_GetIndicesOfMaxima, None, itkNMinimaMaximaImageCalculatorISS3)
itkNMinimaMaximaImageCalculatorISS3.SetRegion = new_instancemethod(_itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorISS3_SetRegion, None, itkNMinimaMaximaImageCalculatorISS3)
itkNMinimaMaximaImageCalculatorISS3.GetN = new_instancemethod(_itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorISS3_GetN, None, itkNMinimaMaximaImageCalculatorISS3)
itkNMinimaMaximaImageCalculatorISS3.SetN = new_instancemethod(_itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorISS3_SetN, None, itkNMinimaMaximaImageCalculatorISS3)
itkNMinimaMaximaImageCalculatorISS3_swigregister = _itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorISS3_swigregister
itkNMinimaMaximaImageCalculatorISS3_swigregister(itkNMinimaMaximaImageCalculatorISS3)

def itkNMinimaMaximaImageCalculatorISS3___New_orig__() -> "itkNMinimaMaximaImageCalculatorISS3_Pointer":
    """itkNMinimaMaximaImageCalculatorISS3___New_orig__() -> itkNMinimaMaximaImageCalculatorISS3_Pointer"""
    return _itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorISS3___New_orig__()

def itkNMinimaMaximaImageCalculatorISS3_cast(obj: 'itkLightObject') -> "itkNMinimaMaximaImageCalculatorISS3 *":
    """itkNMinimaMaximaImageCalculatorISS3_cast(itkLightObject obj) -> itkNMinimaMaximaImageCalculatorISS3"""
    return _itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorISS3_cast(obj)

class itkNMinimaMaximaImageCalculatorIUC2(ITKCommonBasePython.itkObject):
    """Proxy of C++ itkNMinimaMaximaImageCalculatorIUC2 class."""

    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr

    def __New_orig__() -> "itkNMinimaMaximaImageCalculatorIUC2_Pointer":
        """__New_orig__() -> itkNMinimaMaximaImageCalculatorIUC2_Pointer"""
        return _itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorIUC2___New_orig__()

    __New_orig__ = staticmethod(__New_orig__)

    def Clone(self) -> "itkNMinimaMaximaImageCalculatorIUC2_Pointer":
        """Clone(itkNMinimaMaximaImageCalculatorIUC2 self) -> itkNMinimaMaximaImageCalculatorIUC2_Pointer"""
        return _itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorIUC2_Clone(self)


    def SetImage(self, _arg: 'itkImageUC2') -> "void":
        """SetImage(itkNMinimaMaximaImageCalculatorIUC2 self, itkImageUC2 _arg)"""
        return _itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorIUC2_SetImage(self, _arg)


    def ComputeMinima(self) -> "void":
        """ComputeMinima(itkNMinimaMaximaImageCalculatorIUC2 self)"""
        return _itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorIUC2_ComputeMinima(self)


    def ComputeMaxima(self) -> "void":
        """ComputeMaxima(itkNMinimaMaximaImageCalculatorIUC2 self)"""
        return _itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorIUC2_ComputeMaxima(self)


    def Compute(self) -> "void":
        """Compute(itkNMinimaMaximaImageCalculatorIUC2 self)"""
        return _itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorIUC2_Compute(self)


    def GetMinima(self) -> "std::vector< unsigned char,std::allocator< unsigned char > > const &":
        """GetMinima(itkNMinimaMaximaImageCalculatorIUC2 self) -> vectorUC"""
        return _itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorIUC2_GetMinima(self)


    def GetMaxima(self) -> "std::vector< unsigned char,std::allocator< unsigned char > > const &":
        """GetMaxima(itkNMinimaMaximaImageCalculatorIUC2 self) -> vectorUC"""
        return _itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorIUC2_GetMaxima(self)


    def GetIndicesOfMinima(self) -> "std::vector< itkIndex2,std::allocator< itkIndex2 > > const &":
        """GetIndicesOfMinima(itkNMinimaMaximaImageCalculatorIUC2 self) -> std::vector< itkIndex2,std::allocator< itkIndex2 > > const &"""
        return _itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorIUC2_GetIndicesOfMinima(self)


    def GetIndicesOfMaxima(self) -> "std::vector< itkIndex2,std::allocator< itkIndex2 > > const &":
        """GetIndicesOfMaxima(itkNMinimaMaximaImageCalculatorIUC2 self) -> std::vector< itkIndex2,std::allocator< itkIndex2 > > const &"""
        return _itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorIUC2_GetIndicesOfMaxima(self)


    def SetRegion(self, region: 'itkImageRegion2') -> "void":
        """SetRegion(itkNMinimaMaximaImageCalculatorIUC2 self, itkImageRegion2 region)"""
        return _itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorIUC2_SetRegion(self, region)


    def GetN(self) -> "unsigned long":
        """GetN(itkNMinimaMaximaImageCalculatorIUC2 self) -> unsigned long"""
        return _itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorIUC2_GetN(self)


    def SetN(self, _arg: 'unsigned long const') -> "void":
        """SetN(itkNMinimaMaximaImageCalculatorIUC2 self, unsigned long const _arg)"""
        return _itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorIUC2_SetN(self, _arg)

    __swig_destroy__ = _itkNMinimaMaximaImageCalculatorPython.delete_itkNMinimaMaximaImageCalculatorIUC2

    def cast(obj: 'itkLightObject') -> "itkNMinimaMaximaImageCalculatorIUC2 *":
        """cast(itkLightObject obj) -> itkNMinimaMaximaImageCalculatorIUC2"""
        return _itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorIUC2_cast(obj)

    cast = staticmethod(cast)

    def New(*args, **kargs):
        """New() -> itkNMinimaMaximaImageCalculatorIUC2

        Create a new object of the class itkNMinimaMaximaImageCalculatorIUC2 and set the input and the parameters if some
        named or non-named arguments are passed to that method.

        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.

        The named parameters are used by calling the method with the same name prefixed by 'Set'.

        Ex:

          itkNMinimaMaximaImageCalculatorIUC2.New( reader, Threshold=10 )

        is (most of the time) equivalent to:

          obj = itkNMinimaMaximaImageCalculatorIUC2.New()
          obj.SetInput( 0, reader.GetOutput() )
          obj.SetThreshold( 10 )
        """
        obj = itkNMinimaMaximaImageCalculatorIUC2.__New_orig__()
        import itkTemplate
        itkTemplate.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)

itkNMinimaMaximaImageCalculatorIUC2.Clone = new_instancemethod(_itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorIUC2_Clone, None, itkNMinimaMaximaImageCalculatorIUC2)
itkNMinimaMaximaImageCalculatorIUC2.SetImage = new_instancemethod(_itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorIUC2_SetImage, None, itkNMinimaMaximaImageCalculatorIUC2)
itkNMinimaMaximaImageCalculatorIUC2.ComputeMinima = new_instancemethod(_itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorIUC2_ComputeMinima, None, itkNMinimaMaximaImageCalculatorIUC2)
itkNMinimaMaximaImageCalculatorIUC2.ComputeMaxima = new_instancemethod(_itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorIUC2_ComputeMaxima, None, itkNMinimaMaximaImageCalculatorIUC2)
itkNMinimaMaximaImageCalculatorIUC2.Compute = new_instancemethod(_itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorIUC2_Compute, None, itkNMinimaMaximaImageCalculatorIUC2)
itkNMinimaMaximaImageCalculatorIUC2.GetMinima = new_instancemethod(_itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorIUC2_GetMinima, None, itkNMinimaMaximaImageCalculatorIUC2)
itkNMinimaMaximaImageCalculatorIUC2.GetMaxima = new_instancemethod(_itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorIUC2_GetMaxima, None, itkNMinimaMaximaImageCalculatorIUC2)
itkNMinimaMaximaImageCalculatorIUC2.GetIndicesOfMinima = new_instancemethod(_itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorIUC2_GetIndicesOfMinima, None, itkNMinimaMaximaImageCalculatorIUC2)
itkNMinimaMaximaImageCalculatorIUC2.GetIndicesOfMaxima = new_instancemethod(_itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorIUC2_GetIndicesOfMaxima, None, itkNMinimaMaximaImageCalculatorIUC2)
itkNMinimaMaximaImageCalculatorIUC2.SetRegion = new_instancemethod(_itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorIUC2_SetRegion, None, itkNMinimaMaximaImageCalculatorIUC2)
itkNMinimaMaximaImageCalculatorIUC2.GetN = new_instancemethod(_itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorIUC2_GetN, None, itkNMinimaMaximaImageCalculatorIUC2)
itkNMinimaMaximaImageCalculatorIUC2.SetN = new_instancemethod(_itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorIUC2_SetN, None, itkNMinimaMaximaImageCalculatorIUC2)
itkNMinimaMaximaImageCalculatorIUC2_swigregister = _itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorIUC2_swigregister
itkNMinimaMaximaImageCalculatorIUC2_swigregister(itkNMinimaMaximaImageCalculatorIUC2)

def itkNMinimaMaximaImageCalculatorIUC2___New_orig__() -> "itkNMinimaMaximaImageCalculatorIUC2_Pointer":
    """itkNMinimaMaximaImageCalculatorIUC2___New_orig__() -> itkNMinimaMaximaImageCalculatorIUC2_Pointer"""
    return _itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorIUC2___New_orig__()

def itkNMinimaMaximaImageCalculatorIUC2_cast(obj: 'itkLightObject') -> "itkNMinimaMaximaImageCalculatorIUC2 *":
    """itkNMinimaMaximaImageCalculatorIUC2_cast(itkLightObject obj) -> itkNMinimaMaximaImageCalculatorIUC2"""
    return _itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorIUC2_cast(obj)

class itkNMinimaMaximaImageCalculatorIUC3(ITKCommonBasePython.itkObject):
    """Proxy of C++ itkNMinimaMaximaImageCalculatorIUC3 class."""

    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr

    def __New_orig__() -> "itkNMinimaMaximaImageCalculatorIUC3_Pointer":
        """__New_orig__() -> itkNMinimaMaximaImageCalculatorIUC3_Pointer"""
        return _itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorIUC3___New_orig__()

    __New_orig__ = staticmethod(__New_orig__)

    def Clone(self) -> "itkNMinimaMaximaImageCalculatorIUC3_Pointer":
        """Clone(itkNMinimaMaximaImageCalculatorIUC3 self) -> itkNMinimaMaximaImageCalculatorIUC3_Pointer"""
        return _itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorIUC3_Clone(self)


    def SetImage(self, _arg: 'itkImageUC3') -> "void":
        """SetImage(itkNMinimaMaximaImageCalculatorIUC3 self, itkImageUC3 _arg)"""
        return _itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorIUC3_SetImage(self, _arg)


    def ComputeMinima(self) -> "void":
        """ComputeMinima(itkNMinimaMaximaImageCalculatorIUC3 self)"""
        return _itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorIUC3_ComputeMinima(self)


    def ComputeMaxima(self) -> "void":
        """ComputeMaxima(itkNMinimaMaximaImageCalculatorIUC3 self)"""
        return _itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorIUC3_ComputeMaxima(self)


    def Compute(self) -> "void":
        """Compute(itkNMinimaMaximaImageCalculatorIUC3 self)"""
        return _itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorIUC3_Compute(self)


    def GetMinima(self) -> "std::vector< unsigned char,std::allocator< unsigned char > > const &":
        """GetMinima(itkNMinimaMaximaImageCalculatorIUC3 self) -> vectorUC"""
        return _itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorIUC3_GetMinima(self)


    def GetMaxima(self) -> "std::vector< unsigned char,std::allocator< unsigned char > > const &":
        """GetMaxima(itkNMinimaMaximaImageCalculatorIUC3 self) -> vectorUC"""
        return _itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorIUC3_GetMaxima(self)


    def GetIndicesOfMinima(self) -> "std::vector< itkIndex3,std::allocator< itkIndex3 > > const &":
        """GetIndicesOfMinima(itkNMinimaMaximaImageCalculatorIUC3 self) -> std::vector< itkIndex3,std::allocator< itkIndex3 > > const &"""
        return _itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorIUC3_GetIndicesOfMinima(self)


    def GetIndicesOfMaxima(self) -> "std::vector< itkIndex3,std::allocator< itkIndex3 > > const &":
        """GetIndicesOfMaxima(itkNMinimaMaximaImageCalculatorIUC3 self) -> std::vector< itkIndex3,std::allocator< itkIndex3 > > const &"""
        return _itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorIUC3_GetIndicesOfMaxima(self)


    def SetRegion(self, region: 'itkImageRegion3') -> "void":
        """SetRegion(itkNMinimaMaximaImageCalculatorIUC3 self, itkImageRegion3 region)"""
        return _itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorIUC3_SetRegion(self, region)


    def GetN(self) -> "unsigned long":
        """GetN(itkNMinimaMaximaImageCalculatorIUC3 self) -> unsigned long"""
        return _itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorIUC3_GetN(self)


    def SetN(self, _arg: 'unsigned long const') -> "void":
        """SetN(itkNMinimaMaximaImageCalculatorIUC3 self, unsigned long const _arg)"""
        return _itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorIUC3_SetN(self, _arg)

    __swig_destroy__ = _itkNMinimaMaximaImageCalculatorPython.delete_itkNMinimaMaximaImageCalculatorIUC3

    def cast(obj: 'itkLightObject') -> "itkNMinimaMaximaImageCalculatorIUC3 *":
        """cast(itkLightObject obj) -> itkNMinimaMaximaImageCalculatorIUC3"""
        return _itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorIUC3_cast(obj)

    cast = staticmethod(cast)

    def New(*args, **kargs):
        """New() -> itkNMinimaMaximaImageCalculatorIUC3

        Create a new object of the class itkNMinimaMaximaImageCalculatorIUC3 and set the input and the parameters if some
        named or non-named arguments are passed to that method.

        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.

        The named parameters are used by calling the method with the same name prefixed by 'Set'.

        Ex:

          itkNMinimaMaximaImageCalculatorIUC3.New( reader, Threshold=10 )

        is (most of the time) equivalent to:

          obj = itkNMinimaMaximaImageCalculatorIUC3.New()
          obj.SetInput( 0, reader.GetOutput() )
          obj.SetThreshold( 10 )
        """
        obj = itkNMinimaMaximaImageCalculatorIUC3.__New_orig__()
        import itkTemplate
        itkTemplate.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)

itkNMinimaMaximaImageCalculatorIUC3.Clone = new_instancemethod(_itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorIUC3_Clone, None, itkNMinimaMaximaImageCalculatorIUC3)
itkNMinimaMaximaImageCalculatorIUC3.SetImage = new_instancemethod(_itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorIUC3_SetImage, None, itkNMinimaMaximaImageCalculatorIUC3)
itkNMinimaMaximaImageCalculatorIUC3.ComputeMinima = new_instancemethod(_itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorIUC3_ComputeMinima, None, itkNMinimaMaximaImageCalculatorIUC3)
itkNMinimaMaximaImageCalculatorIUC3.ComputeMaxima = new_instancemethod(_itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorIUC3_ComputeMaxima, None, itkNMinimaMaximaImageCalculatorIUC3)
itkNMinimaMaximaImageCalculatorIUC3.Compute = new_instancemethod(_itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorIUC3_Compute, None, itkNMinimaMaximaImageCalculatorIUC3)
itkNMinimaMaximaImageCalculatorIUC3.GetMinima = new_instancemethod(_itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorIUC3_GetMinima, None, itkNMinimaMaximaImageCalculatorIUC3)
itkNMinimaMaximaImageCalculatorIUC3.GetMaxima = new_instancemethod(_itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorIUC3_GetMaxima, None, itkNMinimaMaximaImageCalculatorIUC3)
itkNMinimaMaximaImageCalculatorIUC3.GetIndicesOfMinima = new_instancemethod(_itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorIUC3_GetIndicesOfMinima, None, itkNMinimaMaximaImageCalculatorIUC3)
itkNMinimaMaximaImageCalculatorIUC3.GetIndicesOfMaxima = new_instancemethod(_itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorIUC3_GetIndicesOfMaxima, None, itkNMinimaMaximaImageCalculatorIUC3)
itkNMinimaMaximaImageCalculatorIUC3.SetRegion = new_instancemethod(_itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorIUC3_SetRegion, None, itkNMinimaMaximaImageCalculatorIUC3)
itkNMinimaMaximaImageCalculatorIUC3.GetN = new_instancemethod(_itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorIUC3_GetN, None, itkNMinimaMaximaImageCalculatorIUC3)
itkNMinimaMaximaImageCalculatorIUC3.SetN = new_instancemethod(_itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorIUC3_SetN, None, itkNMinimaMaximaImageCalculatorIUC3)
itkNMinimaMaximaImageCalculatorIUC3_swigregister = _itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorIUC3_swigregister
itkNMinimaMaximaImageCalculatorIUC3_swigregister(itkNMinimaMaximaImageCalculatorIUC3)

def itkNMinimaMaximaImageCalculatorIUC3___New_orig__() -> "itkNMinimaMaximaImageCalculatorIUC3_Pointer":
    """itkNMinimaMaximaImageCalculatorIUC3___New_orig__() -> itkNMinimaMaximaImageCalculatorIUC3_Pointer"""
    return _itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorIUC3___New_orig__()

def itkNMinimaMaximaImageCalculatorIUC3_cast(obj: 'itkLightObject') -> "itkNMinimaMaximaImageCalculatorIUC3 *":
    """itkNMinimaMaximaImageCalculatorIUC3_cast(itkLightObject obj) -> itkNMinimaMaximaImageCalculatorIUC3"""
    return _itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorIUC3_cast(obj)

class itkNMinimaMaximaImageCalculatorIUS2(ITKCommonBasePython.itkObject):
    """Proxy of C++ itkNMinimaMaximaImageCalculatorIUS2 class."""

    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr

    def __New_orig__() -> "itkNMinimaMaximaImageCalculatorIUS2_Pointer":
        """__New_orig__() -> itkNMinimaMaximaImageCalculatorIUS2_Pointer"""
        return _itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorIUS2___New_orig__()

    __New_orig__ = staticmethod(__New_orig__)

    def Clone(self) -> "itkNMinimaMaximaImageCalculatorIUS2_Pointer":
        """Clone(itkNMinimaMaximaImageCalculatorIUS2 self) -> itkNMinimaMaximaImageCalculatorIUS2_Pointer"""
        return _itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorIUS2_Clone(self)


    def SetImage(self, _arg: 'itkImageUS2') -> "void":
        """SetImage(itkNMinimaMaximaImageCalculatorIUS2 self, itkImageUS2 _arg)"""
        return _itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorIUS2_SetImage(self, _arg)


    def ComputeMinima(self) -> "void":
        """ComputeMinima(itkNMinimaMaximaImageCalculatorIUS2 self)"""
        return _itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorIUS2_ComputeMinima(self)


    def ComputeMaxima(self) -> "void":
        """ComputeMaxima(itkNMinimaMaximaImageCalculatorIUS2 self)"""
        return _itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorIUS2_ComputeMaxima(self)


    def Compute(self) -> "void":
        """Compute(itkNMinimaMaximaImageCalculatorIUS2 self)"""
        return _itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorIUS2_Compute(self)


    def GetMinima(self) -> "std::vector< unsigned short,std::allocator< unsigned short > > const &":
        """GetMinima(itkNMinimaMaximaImageCalculatorIUS2 self) -> vectorUS"""
        return _itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorIUS2_GetMinima(self)


    def GetMaxima(self) -> "std::vector< unsigned short,std::allocator< unsigned short > > const &":
        """GetMaxima(itkNMinimaMaximaImageCalculatorIUS2 self) -> vectorUS"""
        return _itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorIUS2_GetMaxima(self)


    def GetIndicesOfMinima(self) -> "std::vector< itkIndex2,std::allocator< itkIndex2 > > const &":
        """GetIndicesOfMinima(itkNMinimaMaximaImageCalculatorIUS2 self) -> std::vector< itkIndex2,std::allocator< itkIndex2 > > const &"""
        return _itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorIUS2_GetIndicesOfMinima(self)


    def GetIndicesOfMaxima(self) -> "std::vector< itkIndex2,std::allocator< itkIndex2 > > const &":
        """GetIndicesOfMaxima(itkNMinimaMaximaImageCalculatorIUS2 self) -> std::vector< itkIndex2,std::allocator< itkIndex2 > > const &"""
        return _itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorIUS2_GetIndicesOfMaxima(self)


    def SetRegion(self, region: 'itkImageRegion2') -> "void":
        """SetRegion(itkNMinimaMaximaImageCalculatorIUS2 self, itkImageRegion2 region)"""
        return _itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorIUS2_SetRegion(self, region)


    def GetN(self) -> "unsigned long":
        """GetN(itkNMinimaMaximaImageCalculatorIUS2 self) -> unsigned long"""
        return _itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorIUS2_GetN(self)


    def SetN(self, _arg: 'unsigned long const') -> "void":
        """SetN(itkNMinimaMaximaImageCalculatorIUS2 self, unsigned long const _arg)"""
        return _itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorIUS2_SetN(self, _arg)

    __swig_destroy__ = _itkNMinimaMaximaImageCalculatorPython.delete_itkNMinimaMaximaImageCalculatorIUS2

    def cast(obj: 'itkLightObject') -> "itkNMinimaMaximaImageCalculatorIUS2 *":
        """cast(itkLightObject obj) -> itkNMinimaMaximaImageCalculatorIUS2"""
        return _itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorIUS2_cast(obj)

    cast = staticmethod(cast)

    def New(*args, **kargs):
        """New() -> itkNMinimaMaximaImageCalculatorIUS2

        Create a new object of the class itkNMinimaMaximaImageCalculatorIUS2 and set the input and the parameters if some
        named or non-named arguments are passed to that method.

        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.

        The named parameters are used by calling the method with the same name prefixed by 'Set'.

        Ex:

          itkNMinimaMaximaImageCalculatorIUS2.New( reader, Threshold=10 )

        is (most of the time) equivalent to:

          obj = itkNMinimaMaximaImageCalculatorIUS2.New()
          obj.SetInput( 0, reader.GetOutput() )
          obj.SetThreshold( 10 )
        """
        obj = itkNMinimaMaximaImageCalculatorIUS2.__New_orig__()
        import itkTemplate
        itkTemplate.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)

itkNMinimaMaximaImageCalculatorIUS2.Clone = new_instancemethod(_itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorIUS2_Clone, None, itkNMinimaMaximaImageCalculatorIUS2)
itkNMinimaMaximaImageCalculatorIUS2.SetImage = new_instancemethod(_itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorIUS2_SetImage, None, itkNMinimaMaximaImageCalculatorIUS2)
itkNMinimaMaximaImageCalculatorIUS2.ComputeMinima = new_instancemethod(_itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorIUS2_ComputeMinima, None, itkNMinimaMaximaImageCalculatorIUS2)
itkNMinimaMaximaImageCalculatorIUS2.ComputeMaxima = new_instancemethod(_itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorIUS2_ComputeMaxima, None, itkNMinimaMaximaImageCalculatorIUS2)
itkNMinimaMaximaImageCalculatorIUS2.Compute = new_instancemethod(_itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorIUS2_Compute, None, itkNMinimaMaximaImageCalculatorIUS2)
itkNMinimaMaximaImageCalculatorIUS2.GetMinima = new_instancemethod(_itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorIUS2_GetMinima, None, itkNMinimaMaximaImageCalculatorIUS2)
itkNMinimaMaximaImageCalculatorIUS2.GetMaxima = new_instancemethod(_itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorIUS2_GetMaxima, None, itkNMinimaMaximaImageCalculatorIUS2)
itkNMinimaMaximaImageCalculatorIUS2.GetIndicesOfMinima = new_instancemethod(_itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorIUS2_GetIndicesOfMinima, None, itkNMinimaMaximaImageCalculatorIUS2)
itkNMinimaMaximaImageCalculatorIUS2.GetIndicesOfMaxima = new_instancemethod(_itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorIUS2_GetIndicesOfMaxima, None, itkNMinimaMaximaImageCalculatorIUS2)
itkNMinimaMaximaImageCalculatorIUS2.SetRegion = new_instancemethod(_itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorIUS2_SetRegion, None, itkNMinimaMaximaImageCalculatorIUS2)
itkNMinimaMaximaImageCalculatorIUS2.GetN = new_instancemethod(_itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorIUS2_GetN, None, itkNMinimaMaximaImageCalculatorIUS2)
itkNMinimaMaximaImageCalculatorIUS2.SetN = new_instancemethod(_itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorIUS2_SetN, None, itkNMinimaMaximaImageCalculatorIUS2)
itkNMinimaMaximaImageCalculatorIUS2_swigregister = _itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorIUS2_swigregister
itkNMinimaMaximaImageCalculatorIUS2_swigregister(itkNMinimaMaximaImageCalculatorIUS2)

def itkNMinimaMaximaImageCalculatorIUS2___New_orig__() -> "itkNMinimaMaximaImageCalculatorIUS2_Pointer":
    """itkNMinimaMaximaImageCalculatorIUS2___New_orig__() -> itkNMinimaMaximaImageCalculatorIUS2_Pointer"""
    return _itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorIUS2___New_orig__()

def itkNMinimaMaximaImageCalculatorIUS2_cast(obj: 'itkLightObject') -> "itkNMinimaMaximaImageCalculatorIUS2 *":
    """itkNMinimaMaximaImageCalculatorIUS2_cast(itkLightObject obj) -> itkNMinimaMaximaImageCalculatorIUS2"""
    return _itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorIUS2_cast(obj)

class itkNMinimaMaximaImageCalculatorIUS3(ITKCommonBasePython.itkObject):
    """Proxy of C++ itkNMinimaMaximaImageCalculatorIUS3 class."""

    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr

    def __New_orig__() -> "itkNMinimaMaximaImageCalculatorIUS3_Pointer":
        """__New_orig__() -> itkNMinimaMaximaImageCalculatorIUS3_Pointer"""
        return _itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorIUS3___New_orig__()

    __New_orig__ = staticmethod(__New_orig__)

    def Clone(self) -> "itkNMinimaMaximaImageCalculatorIUS3_Pointer":
        """Clone(itkNMinimaMaximaImageCalculatorIUS3 self) -> itkNMinimaMaximaImageCalculatorIUS3_Pointer"""
        return _itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorIUS3_Clone(self)


    def SetImage(self, _arg: 'itkImageUS3') -> "void":
        """SetImage(itkNMinimaMaximaImageCalculatorIUS3 self, itkImageUS3 _arg)"""
        return _itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorIUS3_SetImage(self, _arg)


    def ComputeMinima(self) -> "void":
        """ComputeMinima(itkNMinimaMaximaImageCalculatorIUS3 self)"""
        return _itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorIUS3_ComputeMinima(self)


    def ComputeMaxima(self) -> "void":
        """ComputeMaxima(itkNMinimaMaximaImageCalculatorIUS3 self)"""
        return _itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorIUS3_ComputeMaxima(self)


    def Compute(self) -> "void":
        """Compute(itkNMinimaMaximaImageCalculatorIUS3 self)"""
        return _itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorIUS3_Compute(self)


    def GetMinima(self) -> "std::vector< unsigned short,std::allocator< unsigned short > > const &":
        """GetMinima(itkNMinimaMaximaImageCalculatorIUS3 self) -> vectorUS"""
        return _itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorIUS3_GetMinima(self)


    def GetMaxima(self) -> "std::vector< unsigned short,std::allocator< unsigned short > > const &":
        """GetMaxima(itkNMinimaMaximaImageCalculatorIUS3 self) -> vectorUS"""
        return _itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorIUS3_GetMaxima(self)


    def GetIndicesOfMinima(self) -> "std::vector< itkIndex3,std::allocator< itkIndex3 > > const &":
        """GetIndicesOfMinima(itkNMinimaMaximaImageCalculatorIUS3 self) -> std::vector< itkIndex3,std::allocator< itkIndex3 > > const &"""
        return _itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorIUS3_GetIndicesOfMinima(self)


    def GetIndicesOfMaxima(self) -> "std::vector< itkIndex3,std::allocator< itkIndex3 > > const &":
        """GetIndicesOfMaxima(itkNMinimaMaximaImageCalculatorIUS3 self) -> std::vector< itkIndex3,std::allocator< itkIndex3 > > const &"""
        return _itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorIUS3_GetIndicesOfMaxima(self)


    def SetRegion(self, region: 'itkImageRegion3') -> "void":
        """SetRegion(itkNMinimaMaximaImageCalculatorIUS3 self, itkImageRegion3 region)"""
        return _itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorIUS3_SetRegion(self, region)


    def GetN(self) -> "unsigned long":
        """GetN(itkNMinimaMaximaImageCalculatorIUS3 self) -> unsigned long"""
        return _itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorIUS3_GetN(self)


    def SetN(self, _arg: 'unsigned long const') -> "void":
        """SetN(itkNMinimaMaximaImageCalculatorIUS3 self, unsigned long const _arg)"""
        return _itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorIUS3_SetN(self, _arg)

    __swig_destroy__ = _itkNMinimaMaximaImageCalculatorPython.delete_itkNMinimaMaximaImageCalculatorIUS3

    def cast(obj: 'itkLightObject') -> "itkNMinimaMaximaImageCalculatorIUS3 *":
        """cast(itkLightObject obj) -> itkNMinimaMaximaImageCalculatorIUS3"""
        return _itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorIUS3_cast(obj)

    cast = staticmethod(cast)

    def New(*args, **kargs):
        """New() -> itkNMinimaMaximaImageCalculatorIUS3

        Create a new object of the class itkNMinimaMaximaImageCalculatorIUS3 and set the input and the parameters if some
        named or non-named arguments are passed to that method.

        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.

        The named parameters are used by calling the method with the same name prefixed by 'Set'.

        Ex:

          itkNMinimaMaximaImageCalculatorIUS3.New( reader, Threshold=10 )

        is (most of the time) equivalent to:

          obj = itkNMinimaMaximaImageCalculatorIUS3.New()
          obj.SetInput( 0, reader.GetOutput() )
          obj.SetThreshold( 10 )
        """
        obj = itkNMinimaMaximaImageCalculatorIUS3.__New_orig__()
        import itkTemplate
        itkTemplate.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)

itkNMinimaMaximaImageCalculatorIUS3.Clone = new_instancemethod(_itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorIUS3_Clone, None, itkNMinimaMaximaImageCalculatorIUS3)
itkNMinimaMaximaImageCalculatorIUS3.SetImage = new_instancemethod(_itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorIUS3_SetImage, None, itkNMinimaMaximaImageCalculatorIUS3)
itkNMinimaMaximaImageCalculatorIUS3.ComputeMinima = new_instancemethod(_itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorIUS3_ComputeMinima, None, itkNMinimaMaximaImageCalculatorIUS3)
itkNMinimaMaximaImageCalculatorIUS3.ComputeMaxima = new_instancemethod(_itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorIUS3_ComputeMaxima, None, itkNMinimaMaximaImageCalculatorIUS3)
itkNMinimaMaximaImageCalculatorIUS3.Compute = new_instancemethod(_itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorIUS3_Compute, None, itkNMinimaMaximaImageCalculatorIUS3)
itkNMinimaMaximaImageCalculatorIUS3.GetMinima = new_instancemethod(_itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorIUS3_GetMinima, None, itkNMinimaMaximaImageCalculatorIUS3)
itkNMinimaMaximaImageCalculatorIUS3.GetMaxima = new_instancemethod(_itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorIUS3_GetMaxima, None, itkNMinimaMaximaImageCalculatorIUS3)
itkNMinimaMaximaImageCalculatorIUS3.GetIndicesOfMinima = new_instancemethod(_itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorIUS3_GetIndicesOfMinima, None, itkNMinimaMaximaImageCalculatorIUS3)
itkNMinimaMaximaImageCalculatorIUS3.GetIndicesOfMaxima = new_instancemethod(_itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorIUS3_GetIndicesOfMaxima, None, itkNMinimaMaximaImageCalculatorIUS3)
itkNMinimaMaximaImageCalculatorIUS3.SetRegion = new_instancemethod(_itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorIUS3_SetRegion, None, itkNMinimaMaximaImageCalculatorIUS3)
itkNMinimaMaximaImageCalculatorIUS3.GetN = new_instancemethod(_itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorIUS3_GetN, None, itkNMinimaMaximaImageCalculatorIUS3)
itkNMinimaMaximaImageCalculatorIUS3.SetN = new_instancemethod(_itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorIUS3_SetN, None, itkNMinimaMaximaImageCalculatorIUS3)
itkNMinimaMaximaImageCalculatorIUS3_swigregister = _itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorIUS3_swigregister
itkNMinimaMaximaImageCalculatorIUS3_swigregister(itkNMinimaMaximaImageCalculatorIUS3)

def itkNMinimaMaximaImageCalculatorIUS3___New_orig__() -> "itkNMinimaMaximaImageCalculatorIUS3_Pointer":
    """itkNMinimaMaximaImageCalculatorIUS3___New_orig__() -> itkNMinimaMaximaImageCalculatorIUS3_Pointer"""
    return _itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorIUS3___New_orig__()

def itkNMinimaMaximaImageCalculatorIUS3_cast(obj: 'itkLightObject') -> "itkNMinimaMaximaImageCalculatorIUS3 *":
    """itkNMinimaMaximaImageCalculatorIUS3_cast(itkLightObject obj) -> itkNMinimaMaximaImageCalculatorIUS3"""
    return _itkNMinimaMaximaImageCalculatorPython.itkNMinimaMaximaImageCalculatorIUS3_cast(obj)



