
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-01-16T13:48:22+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "097217d8b2bcf4b08dfddc19240d6bedbce4dd74",
 "version": "0.4.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
