[tool.poetry]
name = "person_tracking"
version = "0.1.3"
description = "person tracking"
authors = ["Sindhura <sindhura.k@fractal.ai>"]
license = "GPL-3.0+"

[tool.poetry.dependencies]
python = "3.6.9"
torch = "^1.3"
opencv-python = "^4.1"
progressbar = "^2.5"
torchvision = "^0.5.0"
PILLOW = "^7.0"
matplotlib = "^3.1"
scipy = "^1.4"
sklearn = "^0.0.0"

[tool.poetry.dev-dependencies]
jupyterlab = "^1.1"
jupyter = "^1.0"
ipykernel = "^5.1"
flake8 = "^3.7"
mypy = "^0.740.0"

[tool.poetry.scripts]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"