[tool.poetry]
name = "fracx"
version = "0.1.6"
description = "This project is used to interface with [PDSEnergy's](https://pdsenergy.com/frac-interference-exchange/) FracX platform to programmatically submit and download frac schedules."
authors = ["Brock Friedrich <brocklfriedrich@gmail.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/la-mar/permian-frac-exchange"
repository = "https://github.com/la-mar/permian-frac-exchange"
keywords = ["fracx", "frac", "oil", "gas"]

[tool.poetry.dependencies]
python = "^3.8"
pyyaml = "^5.2"
xlrd = "^1.2.0"
python-dotenv = "^0.10.3"
click = "^7.0"
colorama = "^0.4.3"
spacy = "^2.2.3"
sqlalchemy = "^1.3.12"
pyproj = "^2.4.2"
psycopg2-binary = "^2.8.4"
tomlkit = "^0.5.8"
attrdict = "^2.0.1"
datadog = "^0.33.0"
json_log_formatter = "^0.2.0"
logutils = "^0.3.5"
flask-sqlalchemy = "^2.4.1"
attr = "^0.3.1"
attrs = "^19.3.0"
pyparsing = "^2.4.6"
python-dateutil = "^2.8.1"


[tool.poetry.dev-dependencies]
black = { version = "*", allow-prereleases = true }
mypy = "*"
ipython = "*"
pytest = "*"
pytest-cov = "*"
docker = "*"
boto3 = "*"
hypothesis = "*"
requests-mock = "*"
codecov = "^2.0.15"
coverage = {version = "^5.0", extras = ["toml"]}
flake8 = "^3.7.9"

[tool.poetry.scripts]
fracx = "fracx.manage:main"

[tool.coverage.report]
# Regexes for lines to exclude from consideration
exclude_lines = [
    "pragma: no cover",
    "if self.debug",
    "raise AssertionError",
    "raise NotImplementedError",
    "logger.debug",
    "if 0:",
    "if __name__ == .__main__.:"
]

[tool.isort]
force_grid_wrap = 0
include_trailing_comma = true
line_length = 120
lines_after_imports = 2
multi_line_output = 3
use_parentheses = true

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

