name: Trigger Jenkins checks

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Trigger Jenkins checks
      run: |
        curl http://admin:${{ '{{' }} secrets.jenkins_password {{ '}}' }}@{{ cookiecutter.jenkins_server }}/job/{{ cookiecutter.jenkins_job }}/build\?token\=${{ '{{' }} secrets.jenkins_token {{ '}}' }}
