.build_template: &build_template
  stage: build
  variables:
    WORKSPACE: $CI_PROJECT_DIR
  script:
    - ./.ci/${OS}/install
    - ./.ci/${OS}/build
    - ./.ci/${OS}/post_build

pages:
  stage: build
  image: debian:stretch
  variables:
    LC_ALL: C.UTF-8
    LANG: C.UTF-8
  script:
    - apt-get update
    - apt-get install -y python3-pip
    - pip3 install sphinx sphinx_rtd_theme
    - make -C docs html
    - mv docs/_build/html/ public/
  artifacts:
    paths:
      - public
  only:
    - master

build_stretch:
  extends: .build_template
  image: debian:stretch
  variables:
    OS: deb
  # Check the code samples in the documentation
  after_script:
    - apt-get update
    - apt-get install -y python3-pip
    - pip3 install sphinx sphinx_rtd_theme
    - make -C docs html
    - python3 docs/check_code_samples.py build 

build_bionic:
  extends: .build_template
  image: ubuntu:bionic
  variables:
    OS: deb
