language: minimal

matrix:
  include:
    - name: "Debian 9 (Stretch)"
      os: linux
      sudo: required
      services:
        - docker
      env: 
        - CI_TYPE=deb
        - PYTHON=python3 
        - WORKSPACE=${TRAVIS_BUILD_DIR}
        - RUNNER="docker exec -w ${TRAVIS_BUILD_DIR} -e PYTHON=${PYTHON} -e WORKSPACE=${WORKSPACE} debian_stretch"
      before_install:
        - docker run -di -v ${TRAVIS_BUILD_DIR}:${TRAVIS_BUILD_DIR} --name debian_stretch --rm debian:stretch
      after_success:
        - docker kill debian_stretch
    
    - name: "Debian 10 (Buster)"
      os: linux
      sudo: required
      services:
        - docker
      env: 
        - CI_TYPE=deb
        - PYTHON=python3 
        - WORKSPACE=${TRAVIS_BUILD_DIR}
        - RUNNER="docker exec -w ${TRAVIS_BUILD_DIR} -e PYTHON=${PYTHON} -e WORKSPACE=${WORKSPACE} debian_buster"
      before_install:
        - docker run -di -v ${TRAVIS_BUILD_DIR}:${TRAVIS_BUILD_DIR} --name debian_buster --rm debian:buster
      after_success:
        - docker kill debian_buster
    
    - name: "Ubuntu 18.04 (Bionic Beaver)"
      os: linux
      sudo: required
      services:
        - docker
      env: 
        - CI_TYPE=deb
        - PYTHON=python3 
        - WORKSPACE=${TRAVIS_BUILD_DIR}
        - RUNNER="docker exec -w ${TRAVIS_BUILD_DIR} -e PYTHON=${PYTHON} -e WORKSPACE=${WORKSPACE} ubuntu_bionic"
      before_install:
        - docker run -di -v ${TRAVIS_BUILD_DIR}:${TRAVIS_BUILD_DIR} --name ubuntu_bionic --rm ubuntu:bionic
      after_success:
        - docker kill ubuntu_bionic
    
    - name: "macOS 10.14 (Mojave)"
      os: osx
      osx_image: xcode11
      env: 
        - CI_TYPE=brew 
        - PYTHON=/usr/local/bin/python3
        - PYTHON_LIBRARY=/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/libpython3.7m.dylib
        - WORKSPACE=${TRAVIS_BUILD_DIR}
        # FIXME: link error with libomp
        - CMAKE_OPTIONS="-DUSE_OPENMP=OFF -DPYTHON_EXECUTABLE=${PYTHON} -DPYTHON_LIBRARY=${PYTHON_LIBRARY}"
        - RUNNER=""

script: |
  ${RUNNER} ./.ci/${CI_TYPE}/install
  ${RUNNER} ./.ci/${CI_TYPE}/build
  ${RUNNER} ./.ci/${CI_TYPE}/post_build
