
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-01-08T15:28:32+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "b92b3b923f9279239885f3207a1843979eba5588",
 "version": "0.10"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
