
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-01-21T11:43:40-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "ea1271514fadf4509e76cd2526fa0b391e69ef99",
 "version": "2020.1.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
