import os
import xlsxwriter

def generate_run():
    desktop_path = os.path.join(os.path.join(os.environ['USERPROFILE']), 'Desktop')
    os_workbook = xlsxwriter.Workbook(desktop_path + '/IO.xlsx')
    os_worksheet = os_workbook.add_worksheet('IO')
    os_worksheet.write(0, 0, 'Minimum_Green_A')
    os_worksheet.write(0, 1, 'Minimum_Green_B')
    os_worksheet.write(0, 2, 'Minimum_Green_C')
    os_worksheet.write(0, 3, 'Minimum_Green_D')
    os_worksheet.write(0, 4, 'Minimum_Green_E')
    os_worksheet.write(0, 5, 'Minimum_Green_F')
    os_worksheet.write(0, 6, 'Minimum_Green_G')
    os_worksheet.write(0, 7, 'Amber_A')
    os_worksheet.write(0, 8, 'Amber_B')
    os_worksheet.write(0, 9, 'Amber_C')
    os_worksheet.write(0, 10, 'Amber_D')
    os_worksheet.write(0, 11, 'Amber_E')
    os_worksheet.write(0, 12, 'Amber_F')
    os_worksheet.write(0, 13, 'Amber_G')
    os_worksheet.write(0, 14, 'Red_A')
    os_worksheet.write(0, 15, 'Red_B')
    os_worksheet.write(0, 16, 'Red_C')
    os_worksheet.write(0, 17, 'Red_D')
    os_worksheet.write(0, 18, 'Red_E')
    os_worksheet.write(0, 19, 'Red_F')
    os_worksheet.write(0, 20, 'Red_G')
    os_worksheet.write(0, 21, 'Clearance_1')
    os_worksheet.write(0, 22, 'Clearance_2')
    os_worksheet.write(0, 23, 'Clearance_3')
    os_worksheet.write(0, 24, 'Clearance_4')
    os_worksheet.write(0, 25, 'Clearance_5')
    os_worksheet.write(0, 26, 'Clearance_6')
    os_worksheet.write(0, 27, 'Clearance_7')
    os_worksheet.write(0, 28, 'Clearance_8')
    os_workbook.close()

generate_run()
