[tool.poetry]
name = "pylovepdf"
version = "1.3.4"
description = "ilovepdf.com python API library"

license = "GPL-3.0-only"

authors = [
    "Andrea Bruschi <moonx2006@gmail.com>"
]

readme = 'README.md'

repository = "https://github.com/AndyBTuttofare/pylovepdf"
homepage = "https://github.com/AndyBTuttofare/pylovepdf"

keywords = ['pdf', 'unlock', 'compress', 'manipulate', 'edit', 'protect', 'pdftojpg', 'jpgtopdf', 'pdfa']

classifiers = [
    'Development Status :: 5 - Production/Stable',
    'License :: OSI Approved :: GNU General Public License v3 (GPLv3)',
    'Programming Language :: Python :: 3.6',
    'Topic :: Software Development :: Libraries :: Python Modules',
]

[tool.poetry.dependencies]
python = "3.*"
requests = '>2.19.0'
urllib3 = '>1.23'
