# coding: utf-8

"""
    ORY Hydra

    Welcome to the ORY Hydra HTTP API documentation. You will find documentation for all HTTP APIs here.  # noqa: E501

    The version of the OpenAPI document: latest
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from ory_hydra_client.configuration import Configuration


class IPNet(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'ip': 'list[int]',
        'mask': 'list[int]'
    }

    attribute_map = {
        'ip': 'IP',
        'mask': 'Mask'
    }

    def __init__(self, ip=None, mask=None, local_vars_configuration=None):  # noqa: E501
        """IPNet - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._ip = None
        self._mask = None
        self.discriminator = None

        if ip is not None:
            self.ip = ip
        if mask is not None:
            self.mask = mask

    @property
    def ip(self):
        """Gets the ip of this IPNet.  # noqa: E501

        Note that in this documentation, referring to an IP address as an IPv4 address or an IPv6 address is a semantic property of the address, not just the length of the byte slice: a 16-byte slice can still be an IPv4 address.  # noqa: E501

        :return: The ip of this IPNet.  # noqa: E501
        :rtype: list[int]
        """
        return self._ip

    @ip.setter
    def ip(self, ip):
        """Sets the ip of this IPNet.

        Note that in this documentation, referring to an IP address as an IPv4 address or an IPv6 address is a semantic property of the address, not just the length of the byte slice: a 16-byte slice can still be an IPv4 address.  # noqa: E501

        :param ip: The ip of this IPNet.  # noqa: E501
        :type: list[int]
        """

        self._ip = ip

    @property
    def mask(self):
        """Gets the mask of this IPNet.  # noqa: E501


        :return: The mask of this IPNet.  # noqa: E501
        :rtype: list[int]
        """
        return self._mask

    @mask.setter
    def mask(self, mask):
        """Sets the mask of this IPNet.


        :param mask: The mask of this IPNet.  # noqa: E501
        :type: list[int]
        """

        self._mask = mask

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, IPNet):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, IPNet):
            return True

        return self.to_dict() != other.to_dict()
