#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['validobj']

package_data = \
{'': ['*'],
 'validobj': ['.hypothesis/*',
              '.hypothesis/examples/*',
              '.hypothesis/examples/66b546102d4d247b/*',
              '.hypothesis/examples/c4c4a85301afd0d4/*',
              '.hypothesis/examples/c5d9bb7ef3a9062b/*',
              '.hypothesis/tmp/*',
              '.hypothesis/unicodedata/*',
              '.hypothesis/unicodedata/11.0.0/*',
              '.pytest_cache/*',
              '.pytest_cache/v/*',
              '.pytest_cache/v/cache/*',
              'htmlcov/*',
              'tests/*',
              'tests/.hypothesis/*',
              'tests/.hypothesis/examples/*',
              'tests/.pytest_cache/*',
              'tests/.pytest_cache/v/*',
              'tests/.pytest_cache/v/cache/*',
              'tests/htmlcov/*']}

setup(name='validobj',
      version='0.1',
      description='A simple validation library.',
      author='Zahari Kassabov',
      author_email='zaharid@protonmail.com',
      url='https://github.com/Zaharid/re5',
      packages=packages,
      package_data=package_data,
     )
