environment:
  COVERALLS_PARALLEL: true
  COVERALLS_REPO_TOKEN:
    secure: dZWaKkr6xvP+aDksWLreF0p0L7LLiybUY2bUgGAqc3m/uVWHszncQcsXe5X1+rrf
  matrix:
    - PYTHON: "C:\\Python36-x64"
      TOXENV: py36
    - PYTHON: "C:\\Python37-x64"
      TOXENV: py37
    - PYTHON: "C:\\Python38-x64"
      TOXENV: py38

install:
  - "%PYTHON%\\python.exe -m pip install wheel tox"

build: off

test_script:
  - "%PYTHON%\\python.exe -m tox"

