
'''
This is auto-generated file,
which includes metadata for module Cisco_IOS_XR_infra_sla_datatypes
'''

from ydk._core._dm_meta_info import _MetaInfoClassMember, _MetaInfoClass, _MetaInfoEnum
from ydk._core._dm_meta_info import ATTRIBUTE, REFERENCE_LIST, REFERENCE_LEAFLIST, REFERENCE_BITS, REFERENCE_UNION
from ydk._core._dm_meta_info import REFERENCE_CLASS, REFERENCE_IDENTITY_CLASS, REFERENCE_ENUM_CLASS, ANYXML_CLASS
from ydk._core._importer import _yang_ns

_meta_table = {
    'SlaBurstIntervalUnitsEnum' : _MetaInfoEnum('SlaBurstIntervalUnitsEnum',
        'ydk.models.cisco_ios_xr.Cisco_IOS_XR_infra_sla_datatypes', 'SlaBurstIntervalUnitsEnum',
        '''Sla burst interval units enum''',
        {
            'once':'once',
            'milliseconds':'milliseconds',
            'seconds':'seconds',
            'minutes':'minutes',
            'hours':'hours',
        }, 'Cisco-IOS-XR-infra-sla-datatypes', _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-infra-sla-datatypes']),
    'SlaThresholdTypeEnum' : _MetaInfoEnum('SlaThresholdTypeEnum',
        'ydk.models.cisco_ios_xr.Cisco_IOS_XR_infra_sla_datatypes', 'SlaThresholdTypeEnum',
        '''Sla threshold type enum''',
        {
            'stateless':'stateless',
        }, 'Cisco-IOS-XR-infra-sla-datatypes', _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-infra-sla-datatypes']),
    'SlaSend' : _MetaInfoEnum('SlaSend',
        'ydk.models.cisco_ios_xr.Cisco_IOS_XR_infra_sla_datatypes', 'SlaSend',
        '''Sla send''',
        {
            'packet':'packet',
            'burst':'burst',
        }, 'Cisco-IOS-XR-infra-sla-datatypes', _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-infra-sla-datatypes']),
    'SlaActionTypeEnum' : _MetaInfoEnum('SlaActionTypeEnum',
        'ydk.models.cisco_ios_xr.Cisco_IOS_XR_infra_sla_datatypes', 'SlaActionTypeEnum',
        '''Sla action type enum''',
        {
            'log':'log',
        }, 'Cisco-IOS-XR-infra-sla-datatypes', _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-infra-sla-datatypes']),
    'SlaProbeIntervalDayEnum' : _MetaInfoEnum('SlaProbeIntervalDayEnum',
        'ydk.models.cisco_ios_xr.Cisco_IOS_XR_infra_sla_datatypes', 'SlaProbeIntervalDayEnum',
        '''Sla probe interval day enum''',
        {
            'monday':'monday',
            'tuesday':'tuesday',
            'wednesday':'wednesday',
            'thursday':'thursday',
            'friday':'friday',
            'saturday':'saturday',
            'sunday':'sunday',
        }, 'Cisco-IOS-XR-infra-sla-datatypes', _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-infra-sla-datatypes']),
    'SlaPacketIntervalUnitsEnum' : _MetaInfoEnum('SlaPacketIntervalUnitsEnum',
        'ydk.models.cisco_ios_xr.Cisco_IOS_XR_infra_sla_datatypes', 'SlaPacketIntervalUnitsEnum',
        '''Sla packet interval units enum''',
        {
            'once':'once',
            'milliseconds':'milliseconds',
            'seconds':'seconds',
            'minutes':'minutes',
            'hours':'hours',
        }, 'Cisco-IOS-XR-infra-sla-datatypes', _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-infra-sla-datatypes']),
    'SlaOnDemandRepeatIntervalUnitsEnum' : _MetaInfoEnum('SlaOnDemandRepeatIntervalUnitsEnum',
        'ydk.models.cisco_ios_xr.Cisco_IOS_XR_infra_sla_datatypes', 'SlaOnDemandRepeatIntervalUnitsEnum',
        '''Sla on demand repeat interval units enum''',
        {
            'seconds':'seconds',
            'minutes':'minutes',
            'hours':'hours',
        }, 'Cisco-IOS-XR-infra-sla-datatypes', _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-infra-sla-datatypes']),
    'SlaProbeDurationUnitsEnum' : _MetaInfoEnum('SlaProbeDurationUnitsEnum',
        'ydk.models.cisco_ios_xr.Cisco_IOS_XR_infra_sla_datatypes', 'SlaProbeDurationUnitsEnum',
        '''Sla probe duration units enum''',
        {
            'seconds':'seconds',
            'minutes':'minutes',
            'hours':'hours',
            'day':'day',
            'week':'week',
        }, 'Cisco-IOS-XR-infra-sla-datatypes', _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-infra-sla-datatypes']),
    'SlaStatisticTypeEnum' : _MetaInfoEnum('SlaStatisticTypeEnum',
        'ydk.models.cisco_ios_xr.Cisco_IOS_XR_infra_sla_datatypes', 'SlaStatisticTypeEnum',
        '''Sla statistic type enum''',
        {
            'round-trip-delay':'round_trip_delay',
            'one-way-delay-sd':'one_way_delay_sd',
            'one-way-delay-ds':'one_way_delay_ds',
            'round-trip-jitter':'round_trip_jitter',
            'one-way-jitter-sd':'one_way_jitter_sd',
            'one-way-jitter-ds':'one_way_jitter_ds',
            'one-way-loss-sd':'one_way_loss_sd',
            'one-way-loss-ds':'one_way_loss_ds',
        }, 'Cisco-IOS-XR-infra-sla-datatypes', _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-infra-sla-datatypes']),
    'SlaBucketsSizeUnitsEnum' : _MetaInfoEnum('SlaBucketsSizeUnitsEnum',
        'ydk.models.cisco_ios_xr.Cisco_IOS_XR_infra_sla_datatypes', 'SlaBucketsSizeUnitsEnum',
        '''Sla buckets size units enum''',
        {
            'buckets-per-probe':'buckets_per_probe',
            'probes-per-bucket':'probes_per_bucket',
        }, 'Cisco-IOS-XR-infra-sla-datatypes', _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-infra-sla-datatypes']),
    'SlaThresholdConditionEnum' : _MetaInfoEnum('SlaThresholdConditionEnum',
        'ydk.models.cisco_ios_xr.Cisco_IOS_XR_infra_sla_datatypes', 'SlaThresholdConditionEnum',
        '''Sla threshold condition enum''',
        {
            'max':'max',
            'mean':'mean',
            'sample-count':'sample_count',
        }, 'Cisco-IOS-XR-infra-sla-datatypes', _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-infra-sla-datatypes']),
    'SlaProbeIntervalUnitsEnum' : _MetaInfoEnum('SlaProbeIntervalUnitsEnum',
        'ydk.models.cisco_ios_xr.Cisco_IOS_XR_infra_sla_datatypes', 'SlaProbeIntervalUnitsEnum',
        '''Sla probe interval units enum''',
        {
            'minutes':'minutes',
            'hours':'hours',
            'day':'day',
            'week':'week',
        }, 'Cisco-IOS-XR-infra-sla-datatypes', _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-infra-sla-datatypes']),
    'SlaOnDemandStartMonthEnum' : _MetaInfoEnum('SlaOnDemandStartMonthEnum',
        'ydk.models.cisco_ios_xr.Cisco_IOS_XR_infra_sla_datatypes', 'SlaOnDemandStartMonthEnum',
        '''Sla on demand start month enum''',
        {
            'january':'january',
            'february':'february',
            'march':'march',
            'april':'april',
            'may':'may',
            'june':'june',
            'july':'july',
            'august':'august',
            'september':'september',
            'october':'october',
            'november':'november',
            'december':'december',
        }, 'Cisco-IOS-XR-infra-sla-datatypes', _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-infra-sla-datatypes']),
    'SlaPaddingPattern' : _MetaInfoEnum('SlaPaddingPattern',
        'ydk.models.cisco_ios_xr.Cisco_IOS_XR_infra_sla_datatypes', 'SlaPaddingPattern',
        '''Sla padding pattern''',
        {
            'hex':'hex',
            'pseudo-random':'pseudo_random',
        }, 'Cisco-IOS-XR-infra-sla-datatypes', _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-infra-sla-datatypes']),
    'SlaOnDemandStartTimeTypesEnum' : _MetaInfoEnum('SlaOnDemandStartTimeTypesEnum',
        'ydk.models.cisco_ios_xr.Cisco_IOS_XR_infra_sla_datatypes', 'SlaOnDemandStartTimeTypesEnum',
        '''Sla on demand start time types enum''',
        {
            'now':'now',
            'absolute':'absolute',
            'relative':'relative',
        }, 'Cisco-IOS-XR-infra-sla-datatypes', _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-infra-sla-datatypes']),
    'SlaOnDemandProbeDurationUnitsEnum' : _MetaInfoEnum('SlaOnDemandProbeDurationUnitsEnum',
        'ydk.models.cisco_ios_xr.Cisco_IOS_XR_infra_sla_datatypes', 'SlaOnDemandProbeDurationUnitsEnum',
        '''Sla on demand probe duration units enum''',
        {
            'seconds':'seconds',
            'minutes':'minutes',
            'hours':'hours',
        }, 'Cisco-IOS-XR-infra-sla-datatypes', _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-infra-sla-datatypes']),
    'SlaOnDemandStartTimeRelativeUnitsEnum' : _MetaInfoEnum('SlaOnDemandStartTimeRelativeUnitsEnum',
        'ydk.models.cisco_ios_xr.Cisco_IOS_XR_infra_sla_datatypes', 'SlaOnDemandStartTimeRelativeUnitsEnum',
        '''Sla on demand start time relative units enum''',
        {
            'seconds':'seconds',
            'minutes':'minutes',
            'hours':'hours',
        }, 'Cisco-IOS-XR-infra-sla-datatypes', _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-infra-sla-datatypes']),
}
