
'''
This is auto-generated file,
which includes metadata for module Cisco_IOS_XR_ikev2_oper
'''

from ydk._core._dm_meta_info import _MetaInfoClassMember, _MetaInfoClass, _MetaInfoEnum
from ydk._core._dm_meta_info import ATTRIBUTE, REFERENCE_LIST, REFERENCE_LEAFLIST, REFERENCE_BITS, REFERENCE_UNION
from ydk._core._dm_meta_info import REFERENCE_CLASS, REFERENCE_IDENTITY_CLASS, REFERENCE_ENUM_CLASS, ANYXML_CLASS
from ydk._core._importer import _yang_ns

_meta_table = {
    'IkEv2.Nodes.Node.Session.Session_.Sa' : {
        'meta_info' : _MetaInfoClass('IkEv2.Nodes.Node.Session.Session_.Sa', REFERENCE_LIST,
            '''SA List''',
            False, 
            [
            _MetaInfoClassMember('tunnel-id', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                Tunnel ID
                ''',
                'tunnel_id',
                'Cisco-IOS-XR-ikev2-oper', False, is_config=False),
            _MetaInfoClassMember('local-addr-port', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Local Addr Port
                ''',
                'local_addr_port',
                'Cisco-IOS-XR-ikev2-oper', False, is_config=False),
            _MetaInfoClassMember('remote-addr-port', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Remote Addr Port
                ''',
                'remote_addr_port',
                'Cisco-IOS-XR-ikev2-oper', False, is_config=False),
            _MetaInfoClassMember('state', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                State
                ''',
                'state',
                'Cisco-IOS-XR-ikev2-oper', False, is_config=False),
            _MetaInfoClassMember('encr', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Encryption
                ''',
                'encr',
                'Cisco-IOS-XR-ikev2-oper', False, is_config=False),
            _MetaInfoClassMember('keysize', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                Keysize
                ''',
                'keysize',
                'Cisco-IOS-XR-ikev2-oper', False, is_config=False),
            _MetaInfoClassMember('prf', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                PRF
                ''',
                'prf',
                'Cisco-IOS-XR-ikev2-oper', False, is_config=False),
            _MetaInfoClassMember('hash', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Hash
                ''',
                'hash',
                'Cisco-IOS-XR-ikev2-oper', False, is_config=False),
            _MetaInfoClassMember('dh-group', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                DH Group
                ''',
                'dh_group',
                'Cisco-IOS-XR-ikev2-oper', False, is_config=False),
            _MetaInfoClassMember('auth-sign', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Auth Sign
                ''',
                'auth_sign',
                'Cisco-IOS-XR-ikev2-oper', False, is_config=False),
            _MetaInfoClassMember('auth-verify', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Auth Verify
                ''',
                'auth_verify',
                'Cisco-IOS-XR-ikev2-oper', False, is_config=False),
            _MetaInfoClassMember('life-active', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Life-Active Time
                ''',
                'life_active',
                'Cisco-IOS-XR-ikev2-oper', False, is_config=False),
            _MetaInfoClassMember('session-id', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                Session ID
                ''',
                'session_id',
                'Cisco-IOS-XR-ikev2-oper', False, is_config=False),
            _MetaInfoClassMember('status-desc', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Status Description
                ''',
                'status_desc',
                'Cisco-IOS-XR-ikev2-oper', False, is_config=False),
            _MetaInfoClassMember('local-spi', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Local SPI
                ''',
                'local_spi',
                'Cisco-IOS-XR-ikev2-oper', False, is_config=False),
            _MetaInfoClassMember('remote-spi', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Remote SPI
                ''',
                'remote_spi',
                'Cisco-IOS-XR-ikev2-oper', False, is_config=False),
            _MetaInfoClassMember('local-id', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Local ID
                ''',
                'local_id',
                'Cisco-IOS-XR-ikev2-oper', False, is_config=False),
            _MetaInfoClassMember('remote-id', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Remote ID
                ''',
                'remote_id',
                'Cisco-IOS-XR-ikev2-oper', False, is_config=False),
            _MetaInfoClassMember('sa-initiator', ATTRIBUTE, 'bool', 'boolean',
                None, None,
                [], [],
                '''                Sa Initiator
                ''',
                'sa_initiator',
                'Cisco-IOS-XR-ikev2-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-ikev2-oper',
            'sa',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-ikev2-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_ikev2_oper',
            is_config=False,
        ),
    },
    'IkEv2.Nodes.Node.Session.Session_.ChildSa' : {
        'meta_info' : _MetaInfoClass('IkEv2.Nodes.Node.Session.Session_.ChildSa', REFERENCE_LIST,
            '''Child SA List''',
            False, 
            [
            _MetaInfoClassMember('local-selector', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Local Selector
                ''',
                'local_selector',
                'Cisco-IOS-XR-ikev2-oper', False, is_config=False),
            _MetaInfoClassMember('remote-selector', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Remote Selector
                ''',
                'remote_selector',
                'Cisco-IOS-XR-ikev2-oper', False, is_config=False),
            _MetaInfoClassMember('esp-spi-in-out', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                ESP SPI In Out
                ''',
                'esp_spi_in_out',
                'Cisco-IOS-XR-ikev2-oper', False, is_config=False),
            _MetaInfoClassMember('encr', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Encryption
                ''',
                'encr',
                'Cisco-IOS-XR-ikev2-oper', False, is_config=False),
            _MetaInfoClassMember('keysize', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                Keysize
                ''',
                'keysize',
                'Cisco-IOS-XR-ikev2-oper', False, is_config=False),
            _MetaInfoClassMember('hmac', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                ESP HMAC
                ''',
                'hmac',
                'Cisco-IOS-XR-ikev2-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-ikev2-oper',
            'child-sa',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-ikev2-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_ikev2_oper',
            is_config=False,
        ),
    },
    'IkEv2.Nodes.Node.Session.Session_' : {
        'meta_info' : _MetaInfoClass('IkEv2.Nodes.Node.Session.Session_', REFERENCE_LIST,
            '''Session List''',
            False, 
            [
            _MetaInfoClassMember('session-id', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                Session ID
                ''',
                'session_id',
                'Cisco-IOS-XR-ikev2-oper', False, is_config=False),
            _MetaInfoClassMember('session-status', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Session Status
                ''',
                'session_status',
                'Cisco-IOS-XR-ikev2-oper', False, is_config=False),
            _MetaInfoClassMember('ike-cnt', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                IKE Count
                ''',
                'ike_cnt',
                'Cisco-IOS-XR-ikev2-oper', False, is_config=False),
            _MetaInfoClassMember('child-cnt', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                Child Count
                ''',
                'child_cnt',
                'Cisco-IOS-XR-ikev2-oper', False, is_config=False),
            _MetaInfoClassMember('sa', REFERENCE_LIST, 'Sa', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_ikev2_oper', 'IkEv2.Nodes.Node.Session.Session_.Sa',
                [], [],
                '''                SA List
                ''',
                'sa',
                'Cisco-IOS-XR-ikev2-oper', False, is_config=False),
            _MetaInfoClassMember('child-sa', REFERENCE_LIST, 'ChildSa', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_ikev2_oper', 'IkEv2.Nodes.Node.Session.Session_.ChildSa',
                [], [],
                '''                Child SA List
                ''',
                'child_sa',
                'Cisco-IOS-XR-ikev2-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-ikev2-oper',
            'session',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-ikev2-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_ikev2_oper',
            is_config=False,
        ),
    },
    'IkEv2.Nodes.Node.Session' : {
        'meta_info' : _MetaInfoClass('IkEv2.Nodes.Node.Session', REFERENCE_CLASS,
            '''IKEv2 Session data''',
            False, 
            [
            _MetaInfoClassMember('session', REFERENCE_LIST, 'Session_', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_ikev2_oper', 'IkEv2.Nodes.Node.Session.Session_',
                [], [],
                '''                Session List
                ''',
                'session',
                'Cisco-IOS-XR-ikev2-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-ikev2-oper',
            'session',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-ikev2-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_ikev2_oper',
            is_config=False,
        ),
    },
    'IkEv2.Nodes.Node.Sa.LocalV4.Ip.Sa_' : {
        'meta_info' : _MetaInfoClass('IkEv2.Nodes.Node.Sa.LocalV4.Ip.Sa_', REFERENCE_LIST,
            '''SA list''',
            False, 
            [
            _MetaInfoClassMember('tunnel-id', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                Tunnel ID
                ''',
                'tunnel_id',
                'Cisco-IOS-XR-ikev2-oper', False, is_config=False),
            _MetaInfoClassMember('local-addr-port', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Local Addr Port
                ''',
                'local_addr_port',
                'Cisco-IOS-XR-ikev2-oper', False, is_config=False),
            _MetaInfoClassMember('remote-addr-port', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Remote Addr Port
                ''',
                'remote_addr_port',
                'Cisco-IOS-XR-ikev2-oper', False, is_config=False),
            _MetaInfoClassMember('state', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                State
                ''',
                'state',
                'Cisco-IOS-XR-ikev2-oper', False, is_config=False),
            _MetaInfoClassMember('encr', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Encryption
                ''',
                'encr',
                'Cisco-IOS-XR-ikev2-oper', False, is_config=False),
            _MetaInfoClassMember('keysize', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                Keysize
                ''',
                'keysize',
                'Cisco-IOS-XR-ikev2-oper', False, is_config=False),
            _MetaInfoClassMember('prf', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                PRF
                ''',
                'prf',
                'Cisco-IOS-XR-ikev2-oper', False, is_config=False),
            _MetaInfoClassMember('hash', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Hash
                ''',
                'hash',
                'Cisco-IOS-XR-ikev2-oper', False, is_config=False),
            _MetaInfoClassMember('dh-group', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                DH Group
                ''',
                'dh_group',
                'Cisco-IOS-XR-ikev2-oper', False, is_config=False),
            _MetaInfoClassMember('auth-sign', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Auth Sign
                ''',
                'auth_sign',
                'Cisco-IOS-XR-ikev2-oper', False, is_config=False),
            _MetaInfoClassMember('auth-verify', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Auth Verify
                ''',
                'auth_verify',
                'Cisco-IOS-XR-ikev2-oper', False, is_config=False),
            _MetaInfoClassMember('life-active', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Life-Active Time
                ''',
                'life_active',
                'Cisco-IOS-XR-ikev2-oper', False, is_config=False),
            _MetaInfoClassMember('session-id', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                Session ID
                ''',
                'session_id',
                'Cisco-IOS-XR-ikev2-oper', False, is_config=False),
            _MetaInfoClassMember('status-desc', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Status Description
                ''',
                'status_desc',
                'Cisco-IOS-XR-ikev2-oper', False, is_config=False),
            _MetaInfoClassMember('local-spi', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Local SPI
                ''',
                'local_spi',
                'Cisco-IOS-XR-ikev2-oper', False, is_config=False),
            _MetaInfoClassMember('remote-spi', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Remote SPI
                ''',
                'remote_spi',
                'Cisco-IOS-XR-ikev2-oper', False, is_config=False),
            _MetaInfoClassMember('local-id', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Local ID
                ''',
                'local_id',
                'Cisco-IOS-XR-ikev2-oper', False, is_config=False),
            _MetaInfoClassMember('remote-id', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Remote ID
                ''',
                'remote_id',
                'Cisco-IOS-XR-ikev2-oper', False, is_config=False),
            _MetaInfoClassMember('sa-initiator', ATTRIBUTE, 'bool', 'boolean',
                None, None,
                [], [],
                '''                Sa Initiator
                ''',
                'sa_initiator',
                'Cisco-IOS-XR-ikev2-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-ikev2-oper',
            'sa',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-ikev2-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_ikev2_oper',
            is_config=False,
        ),
    },
    'IkEv2.Nodes.Node.Sa.LocalV4.Ip' : {
        'meta_info' : _MetaInfoClass('IkEv2.Nodes.Node.Sa.LocalV4.Ip', REFERENCE_LIST,
            '''IKEv2 SA data based on address''',
            False, 
            [
            _MetaInfoClassMember('address', ATTRIBUTE, 'str', 'inet:ipv4-address-no-zone',
                None, None,
                [], [b'(([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])(%[\\p{N}\\p{L}]+)?'],
                '''                Address
                ''',
                'address',
                'Cisco-IOS-XR-ikev2-oper', True, is_config=False),
            _MetaInfoClassMember('sa', REFERENCE_LIST, 'Sa_', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_ikev2_oper', 'IkEv2.Nodes.Node.Sa.LocalV4.Ip.Sa_',
                [], [],
                '''                SA list
                ''',
                'sa',
                'Cisco-IOS-XR-ikev2-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-ikev2-oper',
            'ip',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-ikev2-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_ikev2_oper',
            is_config=False,
        ),
    },
    'IkEv2.Nodes.Node.Sa.LocalV4' : {
        'meta_info' : _MetaInfoClass('IkEv2.Nodes.Node.Sa.LocalV4', REFERENCE_CLASS,
            '''IKEv2 SA lookup on local IP''',
            False, 
            [
            _MetaInfoClassMember('ip', REFERENCE_LIST, 'Ip', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_ikev2_oper', 'IkEv2.Nodes.Node.Sa.LocalV4.Ip',
                [], [],
                '''                IKEv2 SA data based on address
                ''',
                'ip',
                'Cisco-IOS-XR-ikev2-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-ikev2-oper',
            'local-v4',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-ikev2-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_ikev2_oper',
            is_config=False,
        ),
    },
    'IkEv2.Nodes.Node.Sa.RemoteV4.Ip.Sa_' : {
        'meta_info' : _MetaInfoClass('IkEv2.Nodes.Node.Sa.RemoteV4.Ip.Sa_', REFERENCE_LIST,
            '''SA list''',
            False, 
            [
            _MetaInfoClassMember('tunnel-id', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                Tunnel ID
                ''',
                'tunnel_id',
                'Cisco-IOS-XR-ikev2-oper', False, is_config=False),
            _MetaInfoClassMember('local-addr-port', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Local Addr Port
                ''',
                'local_addr_port',
                'Cisco-IOS-XR-ikev2-oper', False, is_config=False),
            _MetaInfoClassMember('remote-addr-port', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Remote Addr Port
                ''',
                'remote_addr_port',
                'Cisco-IOS-XR-ikev2-oper', False, is_config=False),
            _MetaInfoClassMember('state', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                State
                ''',
                'state',
                'Cisco-IOS-XR-ikev2-oper', False, is_config=False),
            _MetaInfoClassMember('encr', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Encryption
                ''',
                'encr',
                'Cisco-IOS-XR-ikev2-oper', False, is_config=False),
            _MetaInfoClassMember('keysize', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                Keysize
                ''',
                'keysize',
                'Cisco-IOS-XR-ikev2-oper', False, is_config=False),
            _MetaInfoClassMember('prf', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                PRF
                ''',
                'prf',
                'Cisco-IOS-XR-ikev2-oper', False, is_config=False),
            _MetaInfoClassMember('hash', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Hash
                ''',
                'hash',
                'Cisco-IOS-XR-ikev2-oper', False, is_config=False),
            _MetaInfoClassMember('dh-group', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                DH Group
                ''',
                'dh_group',
                'Cisco-IOS-XR-ikev2-oper', False, is_config=False),
            _MetaInfoClassMember('auth-sign', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Auth Sign
                ''',
                'auth_sign',
                'Cisco-IOS-XR-ikev2-oper', False, is_config=False),
            _MetaInfoClassMember('auth-verify', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Auth Verify
                ''',
                'auth_verify',
                'Cisco-IOS-XR-ikev2-oper', False, is_config=False),
            _MetaInfoClassMember('life-active', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Life-Active Time
                ''',
                'life_active',
                'Cisco-IOS-XR-ikev2-oper', False, is_config=False),
            _MetaInfoClassMember('session-id', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                Session ID
                ''',
                'session_id',
                'Cisco-IOS-XR-ikev2-oper', False, is_config=False),
            _MetaInfoClassMember('status-desc', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Status Description
                ''',
                'status_desc',
                'Cisco-IOS-XR-ikev2-oper', False, is_config=False),
            _MetaInfoClassMember('local-spi', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Local SPI
                ''',
                'local_spi',
                'Cisco-IOS-XR-ikev2-oper', False, is_config=False),
            _MetaInfoClassMember('remote-spi', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Remote SPI
                ''',
                'remote_spi',
                'Cisco-IOS-XR-ikev2-oper', False, is_config=False),
            _MetaInfoClassMember('local-id', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Local ID
                ''',
                'local_id',
                'Cisco-IOS-XR-ikev2-oper', False, is_config=False),
            _MetaInfoClassMember('remote-id', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Remote ID
                ''',
                'remote_id',
                'Cisco-IOS-XR-ikev2-oper', False, is_config=False),
            _MetaInfoClassMember('sa-initiator', ATTRIBUTE, 'bool', 'boolean',
                None, None,
                [], [],
                '''                Sa Initiator
                ''',
                'sa_initiator',
                'Cisco-IOS-XR-ikev2-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-ikev2-oper',
            'sa',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-ikev2-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_ikev2_oper',
            is_config=False,
        ),
    },
    'IkEv2.Nodes.Node.Sa.RemoteV4.Ip' : {
        'meta_info' : _MetaInfoClass('IkEv2.Nodes.Node.Sa.RemoteV4.Ip', REFERENCE_LIST,
            '''IKEv2 SA data based on address''',
            False, 
            [
            _MetaInfoClassMember('address', ATTRIBUTE, 'str', 'inet:ipv4-address-no-zone',
                None, None,
                [], [b'(([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])(%[\\p{N}\\p{L}]+)?'],
                '''                Address
                ''',
                'address',
                'Cisco-IOS-XR-ikev2-oper', True, is_config=False),
            _MetaInfoClassMember('sa', REFERENCE_LIST, 'Sa_', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_ikev2_oper', 'IkEv2.Nodes.Node.Sa.RemoteV4.Ip.Sa_',
                [], [],
                '''                SA list
                ''',
                'sa',
                'Cisco-IOS-XR-ikev2-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-ikev2-oper',
            'ip',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-ikev2-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_ikev2_oper',
            is_config=False,
        ),
    },
    'IkEv2.Nodes.Node.Sa.RemoteV4' : {
        'meta_info' : _MetaInfoClass('IkEv2.Nodes.Node.Sa.RemoteV4', REFERENCE_CLASS,
            '''IKEv2 SA lookup on remote IP''',
            False, 
            [
            _MetaInfoClassMember('ip', REFERENCE_LIST, 'Ip', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_ikev2_oper', 'IkEv2.Nodes.Node.Sa.RemoteV4.Ip',
                [], [],
                '''                IKEv2 SA data based on address
                ''',
                'ip',
                'Cisco-IOS-XR-ikev2-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-ikev2-oper',
            'remote-v4',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-ikev2-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_ikev2_oper',
            is_config=False,
        ),
    },
    'IkEv2.Nodes.Node.Sa.All.Sa_' : {
        'meta_info' : _MetaInfoClass('IkEv2.Nodes.Node.Sa.All.Sa_', REFERENCE_LIST,
            '''SA list''',
            False, 
            [
            _MetaInfoClassMember('tunnel-id', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                Tunnel ID
                ''',
                'tunnel_id',
                'Cisco-IOS-XR-ikev2-oper', False, is_config=False),
            _MetaInfoClassMember('local-addr-port', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Local Addr Port
                ''',
                'local_addr_port',
                'Cisco-IOS-XR-ikev2-oper', False, is_config=False),
            _MetaInfoClassMember('remote-addr-port', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Remote Addr Port
                ''',
                'remote_addr_port',
                'Cisco-IOS-XR-ikev2-oper', False, is_config=False),
            _MetaInfoClassMember('state', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                State
                ''',
                'state',
                'Cisco-IOS-XR-ikev2-oper', False, is_config=False),
            _MetaInfoClassMember('encr', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Encryption
                ''',
                'encr',
                'Cisco-IOS-XR-ikev2-oper', False, is_config=False),
            _MetaInfoClassMember('keysize', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                Keysize
                ''',
                'keysize',
                'Cisco-IOS-XR-ikev2-oper', False, is_config=False),
            _MetaInfoClassMember('prf', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                PRF
                ''',
                'prf',
                'Cisco-IOS-XR-ikev2-oper', False, is_config=False),
            _MetaInfoClassMember('hash', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Hash
                ''',
                'hash',
                'Cisco-IOS-XR-ikev2-oper', False, is_config=False),
            _MetaInfoClassMember('dh-group', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                DH Group
                ''',
                'dh_group',
                'Cisco-IOS-XR-ikev2-oper', False, is_config=False),
            _MetaInfoClassMember('auth-sign', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Auth Sign
                ''',
                'auth_sign',
                'Cisco-IOS-XR-ikev2-oper', False, is_config=False),
            _MetaInfoClassMember('auth-verify', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Auth Verify
                ''',
                'auth_verify',
                'Cisco-IOS-XR-ikev2-oper', False, is_config=False),
            _MetaInfoClassMember('life-active', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Life-Active Time
                ''',
                'life_active',
                'Cisco-IOS-XR-ikev2-oper', False, is_config=False),
            _MetaInfoClassMember('session-id', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                Session ID
                ''',
                'session_id',
                'Cisco-IOS-XR-ikev2-oper', False, is_config=False),
            _MetaInfoClassMember('status-desc', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Status Description
                ''',
                'status_desc',
                'Cisco-IOS-XR-ikev2-oper', False, is_config=False),
            _MetaInfoClassMember('local-spi', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Local SPI
                ''',
                'local_spi',
                'Cisco-IOS-XR-ikev2-oper', False, is_config=False),
            _MetaInfoClassMember('remote-spi', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Remote SPI
                ''',
                'remote_spi',
                'Cisco-IOS-XR-ikev2-oper', False, is_config=False),
            _MetaInfoClassMember('local-id', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Local ID
                ''',
                'local_id',
                'Cisco-IOS-XR-ikev2-oper', False, is_config=False),
            _MetaInfoClassMember('remote-id', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Remote ID
                ''',
                'remote_id',
                'Cisco-IOS-XR-ikev2-oper', False, is_config=False),
            _MetaInfoClassMember('sa-initiator', ATTRIBUTE, 'bool', 'boolean',
                None, None,
                [], [],
                '''                Sa Initiator
                ''',
                'sa_initiator',
                'Cisco-IOS-XR-ikev2-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-ikev2-oper',
            'sa',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-ikev2-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_ikev2_oper',
            is_config=False,
        ),
    },
    'IkEv2.Nodes.Node.Sa.All' : {
        'meta_info' : _MetaInfoClass('IkEv2.Nodes.Node.Sa.All', REFERENCE_CLASS,
            '''IKEv2 SA all data''',
            False, 
            [
            _MetaInfoClassMember('sa', REFERENCE_LIST, 'Sa_', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_ikev2_oper', 'IkEv2.Nodes.Node.Sa.All.Sa_',
                [], [],
                '''                SA list
                ''',
                'sa',
                'Cisco-IOS-XR-ikev2-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-ikev2-oper',
            'all',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-ikev2-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_ikev2_oper',
            is_config=False,
        ),
    },
    'IkEv2.Nodes.Node.Sa' : {
        'meta_info' : _MetaInfoClass('IkEv2.Nodes.Node.Sa', REFERENCE_CLASS,
            '''IKEv2 SA data''',
            False, 
            [
            _MetaInfoClassMember('local-v4', REFERENCE_CLASS, 'LocalV4', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_ikev2_oper', 'IkEv2.Nodes.Node.Sa.LocalV4',
                [], [],
                '''                IKEv2 SA lookup on local IP
                ''',
                'local_v4',
                'Cisco-IOS-XR-ikev2-oper', False, is_config=False),
            _MetaInfoClassMember('remote-v4', REFERENCE_CLASS, 'RemoteV4', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_ikev2_oper', 'IkEv2.Nodes.Node.Sa.RemoteV4',
                [], [],
                '''                IKEv2 SA lookup on remote IP
                ''',
                'remote_v4',
                'Cisco-IOS-XR-ikev2-oper', False, is_config=False),
            _MetaInfoClassMember('all', REFERENCE_CLASS, 'All', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_ikev2_oper', 'IkEv2.Nodes.Node.Sa.All',
                [], [],
                '''                IKEv2 SA all data
                ''',
                'all',
                'Cisco-IOS-XR-ikev2-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-ikev2-oper',
            'sa',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-ikev2-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_ikev2_oper',
            is_config=False,
        ),
    },
    'IkEv2.Nodes.Node.Policies.Policy' : {
        'meta_info' : _MetaInfoClass('IkEv2.Nodes.Node.Policies.Policy', REFERENCE_LIST,
            '''IKEv2 policy data''',
            False, 
            [
            _MetaInfoClassMember('name', ATTRIBUTE, 'str', 'xr:Cisco-ios-xr-string',
                None, None,
                [(1, 32)], [],
                '''                Name of the IKEv2 policy
                ''',
                'name',
                'Cisco-IOS-XR-ikev2-oper', True, is_config=False),
            _MetaInfoClassMember('policy-name', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Name of the policy
                ''',
                'policy_name',
                'Cisco-IOS-XR-ikev2-oper', False, is_config=False),
            _MetaInfoClassMember('addr', REFERENCE_LEAFLIST, 'str', 'inet:ipv4-address',
                None, None,
                [], [b'(([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])(%[\\p{N}\\p{L}]+)?'],
                '''                Match address of peer
                ''',
                'addr',
                'Cisco-IOS-XR-ikev2-oper', False, is_config=False),
            _MetaInfoClassMember('proposal', REFERENCE_LEAFLIST, 'str', 'String1',
                None, None,
                [], [],
                '''                List of proposals
                ''',
                'proposal',
                'Cisco-IOS-XR-ikev2-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-ikev2-oper',
            'policy',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-ikev2-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_ikev2_oper',
            is_config=False,
        ),
    },
    'IkEv2.Nodes.Node.Policies' : {
        'meta_info' : _MetaInfoClass('IkEv2.Nodes.Node.Policies', REFERENCE_CLASS,
            '''IKEv2 policies on this node''',
            False, 
            [
            _MetaInfoClassMember('policy', REFERENCE_LIST, 'Policy', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_ikev2_oper', 'IkEv2.Nodes.Node.Policies.Policy',
                [], [],
                '''                IKEv2 policy data
                ''',
                'policy',
                'Cisco-IOS-XR-ikev2-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-ikev2-oper',
            'policies',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-ikev2-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_ikev2_oper',
            is_config=False,
        ),
    },
    'IkEv2.Nodes.Node.Proposals.Proposal' : {
        'meta_info' : _MetaInfoClass('IkEv2.Nodes.Node.Proposals.Proposal', REFERENCE_LIST,
            '''IKEv2 proposal data''',
            False, 
            [
            _MetaInfoClassMember('name', ATTRIBUTE, 'str', 'xr:Cisco-ios-xr-string',
                None, None,
                [(1, 32)], [],
                '''                Name of the IKEv2 proposal
                ''',
                'name',
                'Cisco-IOS-XR-ikev2-oper', True, is_config=False),
            _MetaInfoClassMember('proposal-name', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Name of the proposal
                ''',
                'proposal_name',
                'Cisco-IOS-XR-ikev2-oper', False, is_config=False),
            _MetaInfoClassMember('encryption-alg', REFERENCE_LEAFLIST, 'str', 'String1',
                None, None,
                [], [],
                '''                Encryption Algorithm
                ''',
                'encryption_alg',
                'Cisco-IOS-XR-ikev2-oper', False, is_config=False),
            _MetaInfoClassMember('hash-alg', REFERENCE_LEAFLIST, 'str', 'String1',
                None, None,
                [], [],
                '''                Integrity Algorithm
                ''',
                'hash_alg',
                'Cisco-IOS-XR-ikev2-oper', False, is_config=False),
            _MetaInfoClassMember('prf-alg', REFERENCE_LEAFLIST, 'str', 'String1',
                None, None,
                [], [],
                '''                PRF Algorithm
                ''',
                'prf_alg',
                'Cisco-IOS-XR-ikev2-oper', False, is_config=False),
            _MetaInfoClassMember('group-alg', REFERENCE_LEAFLIST, 'str', 'String1',
                None, None,
                [], [],
                '''                Group Algorithm
                ''',
                'group_alg',
                'Cisco-IOS-XR-ikev2-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-ikev2-oper',
            'proposal',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-ikev2-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_ikev2_oper',
            is_config=False,
        ),
    },
    'IkEv2.Nodes.Node.Proposals' : {
        'meta_info' : _MetaInfoClass('IkEv2.Nodes.Node.Proposals', REFERENCE_CLASS,
            '''IKEv2 proposals on this node''',
            False, 
            [
            _MetaInfoClassMember('proposal', REFERENCE_LIST, 'Proposal', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_ikev2_oper', 'IkEv2.Nodes.Node.Proposals.Proposal',
                [], [],
                '''                IKEv2 proposal data
                ''',
                'proposal',
                'Cisco-IOS-XR-ikev2-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-ikev2-oper',
            'proposals',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-ikev2-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_ikev2_oper',
            is_config=False,
        ),
    },
    'IkEv2.Nodes.Node.Profiles.Profile' : {
        'meta_info' : _MetaInfoClass('IkEv2.Nodes.Node.Profiles.Profile', REFERENCE_LIST,
            '''IKEv2 profile data''',
            False, 
            [
            _MetaInfoClassMember('name', ATTRIBUTE, 'str', 'xr:Cisco-ios-xr-string',
                None, None,
                [(1, 32)], [],
                '''                Name of the IKEv2 profile
                ''',
                'name',
                'Cisco-IOS-XR-ikev2-oper', True, is_config=False),
            _MetaInfoClassMember('profile-name', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Name of the Profile
                ''',
                'profile_name',
                'Cisco-IOS-XR-ikev2-oper', False, is_config=False),
            _MetaInfoClassMember('keyring-name', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Name of the keyring
                ''',
                'keyring_name',
                'Cisco-IOS-XR-ikev2-oper', False, is_config=False),
            _MetaInfoClassMember('match-any', ATTRIBUTE, 'bool', 'boolean',
                None, None,
                [], [],
                '''                Match Any Criteria
                ''',
                'match_any',
                'Cisco-IOS-XR-ikev2-oper', False, is_config=False),
            _MetaInfoClassMember('lifetime', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                Lifetime
                ''',
                'lifetime',
                'Cisco-IOS-XR-ikev2-oper', False, is_config=False),
            _MetaInfoClassMember('dpd-interval', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                DPD Interval
                ''',
                'dpd_interval',
                'Cisco-IOS-XR-ikev2-oper', False, is_config=False),
            _MetaInfoClassMember('dpd-retry', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                DPD Retry
                ''',
                'dpd_retry',
                'Cisco-IOS-XR-ikev2-oper', False, is_config=False),
            _MetaInfoClassMember('addr', REFERENCE_LEAFLIST, 'str', 'inet:ipv4-address',
                None, None,
                [], [b'(([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])(%[\\p{N}\\p{L}]+)?'],
                '''                Match address of peer
                ''',
                'addr',
                'Cisco-IOS-XR-ikev2-oper', False, is_config=False),
            _MetaInfoClassMember('mask', REFERENCE_LEAFLIST, 'str', 'inet:ipv4-address',
                None, None,
                [], [b'(([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])(%[\\p{N}\\p{L}]+)?'],
                '''                Mask of peer
                ''',
                'mask',
                'Cisco-IOS-XR-ikev2-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-ikev2-oper',
            'profile',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-ikev2-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_ikev2_oper',
            is_config=False,
        ),
    },
    'IkEv2.Nodes.Node.Profiles' : {
        'meta_info' : _MetaInfoClass('IkEv2.Nodes.Node.Profiles', REFERENCE_CLASS,
            '''IKEv2 profiles on this node''',
            False, 
            [
            _MetaInfoClassMember('profile', REFERENCE_LIST, 'Profile', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_ikev2_oper', 'IkEv2.Nodes.Node.Profiles.Profile',
                [], [],
                '''                IKEv2 profile data
                ''',
                'profile',
                'Cisco-IOS-XR-ikev2-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-ikev2-oper',
            'profiles',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-ikev2-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_ikev2_oper',
            is_config=False,
        ),
    },
    'IkEv2.Nodes.Node.Keyrings.Keyring.Peer' : {
        'meta_info' : _MetaInfoClass('IkEv2.Nodes.Node.Keyrings.Keyring.Peer', REFERENCE_LIST,
            '''List of peers''',
            False, 
            [
            _MetaInfoClassMember('peer-name', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Name of the peer
                ''',
                'peer_name',
                'Cisco-IOS-XR-ikev2-oper', False, is_config=False),
            _MetaInfoClassMember('ip-address', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                IP Address of the peer
                ''',
                'ip_address',
                'Cisco-IOS-XR-ikev2-oper', False, is_config=False),
            _MetaInfoClassMember('subnet', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Subnet mask of the peer
                ''',
                'subnet',
                'Cisco-IOS-XR-ikev2-oper', False, is_config=False),
            _MetaInfoClassMember('local-psk', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Local PSK
                ''',
                'local_psk',
                'Cisco-IOS-XR-ikev2-oper', False, is_config=False),
            _MetaInfoClassMember('remote-psk', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Remote PSK
                ''',
                'remote_psk',
                'Cisco-IOS-XR-ikev2-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-ikev2-oper',
            'peer',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-ikev2-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_ikev2_oper',
            is_config=False,
        ),
    },
    'IkEv2.Nodes.Node.Keyrings.Keyring' : {
        'meta_info' : _MetaInfoClass('IkEv2.Nodes.Node.Keyrings.Keyring', REFERENCE_LIST,
            '''IKEv2 keyring data''',
            False, 
            [
            _MetaInfoClassMember('name', ATTRIBUTE, 'str', 'xr:Cisco-ios-xr-string',
                None, None,
                [(1, 32)], [],
                '''                Name of the IKEv2 keyring
                ''',
                'name',
                'Cisco-IOS-XR-ikev2-oper', True, is_config=False),
            _MetaInfoClassMember('keyring-name', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Name of the Keyring
                ''',
                'keyring_name',
                'Cisco-IOS-XR-ikev2-oper', False, is_config=False),
            _MetaInfoClassMember('peer', REFERENCE_LIST, 'Peer', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_ikev2_oper', 'IkEv2.Nodes.Node.Keyrings.Keyring.Peer',
                [], [],
                '''                List of peers
                ''',
                'peer',
                'Cisco-IOS-XR-ikev2-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-ikev2-oper',
            'keyring',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-ikev2-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_ikev2_oper',
            is_config=False,
        ),
    },
    'IkEv2.Nodes.Node.Keyrings' : {
        'meta_info' : _MetaInfoClass('IkEv2.Nodes.Node.Keyrings', REFERENCE_CLASS,
            '''IKEv2 keyrings on this node''',
            False, 
            [
            _MetaInfoClassMember('keyring', REFERENCE_LIST, 'Keyring', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_ikev2_oper', 'IkEv2.Nodes.Node.Keyrings.Keyring',
                [], [],
                '''                IKEv2 keyring data
                ''',
                'keyring',
                'Cisco-IOS-XR-ikev2-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-ikev2-oper',
            'keyrings',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-ikev2-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_ikev2_oper',
            is_config=False,
        ),
    },
    'IkEv2.Nodes.Node' : {
        'meta_info' : _MetaInfoClass('IkEv2.Nodes.Node', REFERENCE_LIST,
            '''IKEv2 operational data for a particular node''',
            False, 
            [
            _MetaInfoClassMember('node-name', ATTRIBUTE, 'str', 'xr:Node-id',
                None, None,
                [], [b'([a-zA-Z0-9_]*\\d+/){1,2}([a-zA-Z0-9_]*\\d+)'],
                '''                The identifier for the node
                ''',
                'node_name',
                'Cisco-IOS-XR-ikev2-oper', True, is_config=False),
            _MetaInfoClassMember('session', REFERENCE_CLASS, 'Session', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_ikev2_oper', 'IkEv2.Nodes.Node.Session',
                [], [],
                '''                IKEv2 Session data
                ''',
                'session',
                'Cisco-IOS-XR-ikev2-oper', False, is_config=False),
            _MetaInfoClassMember('sa', REFERENCE_CLASS, 'Sa', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_ikev2_oper', 'IkEv2.Nodes.Node.Sa',
                [], [],
                '''                IKEv2 SA data
                ''',
                'sa',
                'Cisco-IOS-XR-ikev2-oper', False, is_config=False),
            _MetaInfoClassMember('policies', REFERENCE_CLASS, 'Policies', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_ikev2_oper', 'IkEv2.Nodes.Node.Policies',
                [], [],
                '''                IKEv2 policies on this node
                ''',
                'policies',
                'Cisco-IOS-XR-ikev2-oper', False, is_config=False),
            _MetaInfoClassMember('proposals', REFERENCE_CLASS, 'Proposals', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_ikev2_oper', 'IkEv2.Nodes.Node.Proposals',
                [], [],
                '''                IKEv2 proposals on this node
                ''',
                'proposals',
                'Cisco-IOS-XR-ikev2-oper', False, is_config=False),
            _MetaInfoClassMember('profiles', REFERENCE_CLASS, 'Profiles', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_ikev2_oper', 'IkEv2.Nodes.Node.Profiles',
                [], [],
                '''                IKEv2 profiles on this node
                ''',
                'profiles',
                'Cisco-IOS-XR-ikev2-oper', False, is_config=False),
            _MetaInfoClassMember('keyrings', REFERENCE_CLASS, 'Keyrings', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_ikev2_oper', 'IkEv2.Nodes.Node.Keyrings',
                [], [],
                '''                IKEv2 keyrings on this node
                ''',
                'keyrings',
                'Cisco-IOS-XR-ikev2-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-ikev2-oper',
            'node',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-ikev2-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_ikev2_oper',
            is_config=False,
        ),
    },
    'IkEv2.Nodes' : {
        'meta_info' : _MetaInfoClass('IkEv2.Nodes', REFERENCE_CLASS,
            '''Per node IKEv2 operational data''',
            False, 
            [
            _MetaInfoClassMember('node', REFERENCE_LIST, 'Node', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_ikev2_oper', 'IkEv2.Nodes.Node',
                [], [],
                '''                IKEv2 operational data for a particular node
                ''',
                'node',
                'Cisco-IOS-XR-ikev2-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-ikev2-oper',
            'nodes',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-ikev2-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_ikev2_oper',
            is_config=False,
        ),
    },
    'IkEv2' : {
        'meta_info' : _MetaInfoClass('IkEv2', REFERENCE_CLASS,
            '''IKEv2 operational data''',
            False, 
            [
            _MetaInfoClassMember('nodes', REFERENCE_CLASS, 'Nodes', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_ikev2_oper', 'IkEv2.Nodes',
                [], [],
                '''                Per node IKEv2 operational data
                ''',
                'nodes',
                'Cisco-IOS-XR-ikev2-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-ikev2-oper',
            'ik-ev2',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-ikev2-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_ikev2_oper',
            is_config=False,
        ),
    },
}
_meta_table['IkEv2.Nodes.Node.Session.Session_.Sa']['meta_info'].parent =_meta_table['IkEv2.Nodes.Node.Session.Session_']['meta_info']
_meta_table['IkEv2.Nodes.Node.Session.Session_.ChildSa']['meta_info'].parent =_meta_table['IkEv2.Nodes.Node.Session.Session_']['meta_info']
_meta_table['IkEv2.Nodes.Node.Session.Session_']['meta_info'].parent =_meta_table['IkEv2.Nodes.Node.Session']['meta_info']
_meta_table['IkEv2.Nodes.Node.Sa.LocalV4.Ip.Sa_']['meta_info'].parent =_meta_table['IkEv2.Nodes.Node.Sa.LocalV4.Ip']['meta_info']
_meta_table['IkEv2.Nodes.Node.Sa.LocalV4.Ip']['meta_info'].parent =_meta_table['IkEv2.Nodes.Node.Sa.LocalV4']['meta_info']
_meta_table['IkEv2.Nodes.Node.Sa.RemoteV4.Ip.Sa_']['meta_info'].parent =_meta_table['IkEv2.Nodes.Node.Sa.RemoteV4.Ip']['meta_info']
_meta_table['IkEv2.Nodes.Node.Sa.RemoteV4.Ip']['meta_info'].parent =_meta_table['IkEv2.Nodes.Node.Sa.RemoteV4']['meta_info']
_meta_table['IkEv2.Nodes.Node.Sa.All.Sa_']['meta_info'].parent =_meta_table['IkEv2.Nodes.Node.Sa.All']['meta_info']
_meta_table['IkEv2.Nodes.Node.Sa.LocalV4']['meta_info'].parent =_meta_table['IkEv2.Nodes.Node.Sa']['meta_info']
_meta_table['IkEv2.Nodes.Node.Sa.RemoteV4']['meta_info'].parent =_meta_table['IkEv2.Nodes.Node.Sa']['meta_info']
_meta_table['IkEv2.Nodes.Node.Sa.All']['meta_info'].parent =_meta_table['IkEv2.Nodes.Node.Sa']['meta_info']
_meta_table['IkEv2.Nodes.Node.Policies.Policy']['meta_info'].parent =_meta_table['IkEv2.Nodes.Node.Policies']['meta_info']
_meta_table['IkEv2.Nodes.Node.Proposals.Proposal']['meta_info'].parent =_meta_table['IkEv2.Nodes.Node.Proposals']['meta_info']
_meta_table['IkEv2.Nodes.Node.Profiles.Profile']['meta_info'].parent =_meta_table['IkEv2.Nodes.Node.Profiles']['meta_info']
_meta_table['IkEv2.Nodes.Node.Keyrings.Keyring.Peer']['meta_info'].parent =_meta_table['IkEv2.Nodes.Node.Keyrings.Keyring']['meta_info']
_meta_table['IkEv2.Nodes.Node.Keyrings.Keyring']['meta_info'].parent =_meta_table['IkEv2.Nodes.Node.Keyrings']['meta_info']
_meta_table['IkEv2.Nodes.Node.Session']['meta_info'].parent =_meta_table['IkEv2.Nodes.Node']['meta_info']
_meta_table['IkEv2.Nodes.Node.Sa']['meta_info'].parent =_meta_table['IkEv2.Nodes.Node']['meta_info']
_meta_table['IkEv2.Nodes.Node.Policies']['meta_info'].parent =_meta_table['IkEv2.Nodes.Node']['meta_info']
_meta_table['IkEv2.Nodes.Node.Proposals']['meta_info'].parent =_meta_table['IkEv2.Nodes.Node']['meta_info']
_meta_table['IkEv2.Nodes.Node.Profiles']['meta_info'].parent =_meta_table['IkEv2.Nodes.Node']['meta_info']
_meta_table['IkEv2.Nodes.Node.Keyrings']['meta_info'].parent =_meta_table['IkEv2.Nodes.Node']['meta_info']
_meta_table['IkEv2.Nodes.Node']['meta_info'].parent =_meta_table['IkEv2.Nodes']['meta_info']
_meta_table['IkEv2.Nodes']['meta_info'].parent =_meta_table['IkEv2']['meta_info']
