
'''
This is auto-generated file,
which includes metadata for module Cisco_IOS_XR_crypto_macsec_mka_oper
'''

from ydk._core._dm_meta_info import _MetaInfoClassMember, _MetaInfoClass, _MetaInfoEnum
from ydk._core._dm_meta_info import ATTRIBUTE, REFERENCE_LIST, REFERENCE_LEAFLIST, REFERENCE_BITS, REFERENCE_UNION
from ydk._core._dm_meta_info import REFERENCE_CLASS, REFERENCE_IDENTITY_CLASS, REFERENCE_ENUM_CLASS, ANYXML_CLASS
from ydk._core._importer import _yang_ns

_meta_table = {
    'MkaAuthenticationMode' : _MetaInfoEnum('MkaAuthenticationMode',
        'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_macsec_mka_oper', 'MkaAuthenticationMode',
        '''Mka authentication mode''',
        {
            'auth-mode-invalid':'auth_mode_invalid',
            'auth-mode-psk':'auth_mode_psk',
            'auth-mode-eap':'auth_mode_eap',
        }, 'Cisco-IOS-XR-crypto-macsec-mka-oper', _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-crypto-macsec-mka-oper']),
    'MacsecServicePort' : _MetaInfoEnum('MacsecServicePort',
        'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_macsec_mka_oper', 'MacsecServicePort',
        '''Macsec service port''',
        {
            'macsec-service-port-none':'macsec_service_port_none',
            'macsec-service-port-encryption':'macsec_service_port_encryption',
            'macsec-service-port-decryption':'macsec_service_port_decryption',
        }, 'Cisco-IOS-XR-crypto-macsec-mka-oper', _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-crypto-macsec-mka-oper']),
    'MacsecCipherSuite' : _MetaInfoEnum('MacsecCipherSuite',
        'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_macsec_mka_oper', 'MacsecCipherSuite',
        '''Macsec cipher suite''',
        {
            'cipher-suite-none':'cipher_suite_none',
            'cipher-suite-gcm-aes-128':'cipher_suite_gcm_aes_128',
            'cipher-suite-gcm-aes-256':'cipher_suite_gcm_aes_256',
            'cipher-suite-gcm-aes-128-xpn':'cipher_suite_gcm_aes_128_xpn',
            'cipher-suite-gcm-aes-256-xpn':'cipher_suite_gcm_aes_256_xpn',
        }, 'Cisco-IOS-XR-crypto-macsec-mka-oper', _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-crypto-macsec-mka-oper']),
    'Macsec.Mka.Interfaces.Interface.Session.SessionSummary.OuterTag' : {
        'meta_info' : _MetaInfoClass('Macsec.Mka.Interfaces.Interface.Session.SessionSummary.OuterTag', REFERENCE_CLASS,
            '''VLAN Outer TAG''',
            False, 
            [
            _MetaInfoClassMember('ether-type', ATTRIBUTE, 'int', 'uint16',
                None, None,
                [('0', '65535')], [],
                '''                EtherType
                ''',
                'ether_type',
                'Cisco-IOS-XR-crypto-macsec-mka-oper', False, is_config=False),
            _MetaInfoClassMember('priority', ATTRIBUTE, 'int', 'uint8',
                None, None,
                [('0', '255')], [],
                '''                Priority
                ''',
                'priority',
                'Cisco-IOS-XR-crypto-macsec-mka-oper', False, is_config=False),
            _MetaInfoClassMember('cfi', ATTRIBUTE, 'int', 'uint8',
                None, None,
                [('0', '255')], [],
                '''                Cannonical Format Identifier
                ''',
                'cfi',
                'Cisco-IOS-XR-crypto-macsec-mka-oper', False, is_config=False),
            _MetaInfoClassMember('vlan-id', ATTRIBUTE, 'int', 'uint16',
                None, None,
                [('0', '65535')], [],
                '''                Vlan Id
                ''',
                'vlan_id',
                'Cisco-IOS-XR-crypto-macsec-mka-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-crypto-macsec-mka-oper',
            'outer-tag',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-crypto-macsec-mka-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_macsec_mka_oper',
            is_config=False,
        ),
    },
    'Macsec.Mka.Interfaces.Interface.Session.SessionSummary.InnerTag' : {
        'meta_info' : _MetaInfoClass('Macsec.Mka.Interfaces.Interface.Session.SessionSummary.InnerTag', REFERENCE_CLASS,
            '''VLAN Inner TAG''',
            False, 
            [
            _MetaInfoClassMember('ether-type', ATTRIBUTE, 'int', 'uint16',
                None, None,
                [('0', '65535')], [],
                '''                EtherType
                ''',
                'ether_type',
                'Cisco-IOS-XR-crypto-macsec-mka-oper', False, is_config=False),
            _MetaInfoClassMember('priority', ATTRIBUTE, 'int', 'uint8',
                None, None,
                [('0', '255')], [],
                '''                Priority
                ''',
                'priority',
                'Cisco-IOS-XR-crypto-macsec-mka-oper', False, is_config=False),
            _MetaInfoClassMember('cfi', ATTRIBUTE, 'int', 'uint8',
                None, None,
                [('0', '255')], [],
                '''                Cannonical Format Identifier
                ''',
                'cfi',
                'Cisco-IOS-XR-crypto-macsec-mka-oper', False, is_config=False),
            _MetaInfoClassMember('vlan-id', ATTRIBUTE, 'int', 'uint16',
                None, None,
                [('0', '65535')], [],
                '''                Vlan Id
                ''',
                'vlan_id',
                'Cisco-IOS-XR-crypto-macsec-mka-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-crypto-macsec-mka-oper',
            'inner-tag',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-crypto-macsec-mka-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_macsec_mka_oper',
            is_config=False,
        ),
    },
    'Macsec.Mka.Interfaces.Interface.Session.SessionSummary' : {
        'meta_info' : _MetaInfoClass('Macsec.Mka.Interfaces.Interface.Session.SessionSummary', REFERENCE_CLASS,
            '''Session summary''',
            False, 
            [
            _MetaInfoClassMember('outer-tag', REFERENCE_CLASS, 'OuterTag', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_macsec_mka_oper', 'Macsec.Mka.Interfaces.Interface.Session.SessionSummary.OuterTag',
                [], [],
                '''                VLAN Outer TAG
                ''',
                'outer_tag',
                'Cisco-IOS-XR-crypto-macsec-mka-oper', False, is_config=False),
            _MetaInfoClassMember('inner-tag', REFERENCE_CLASS, 'InnerTag', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_macsec_mka_oper', 'Macsec.Mka.Interfaces.Interface.Session.SessionSummary.InnerTag',
                [], [],
                '''                VLAN Inner TAG
                ''',
                'inner_tag',
                'Cisco-IOS-XR-crypto-macsec-mka-oper', False, is_config=False),
            _MetaInfoClassMember('interface-name', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                macsec configured interface
                ''',
                'interface_name',
                'Cisco-IOS-XR-crypto-macsec-mka-oper', False, is_config=False),
            _MetaInfoClassMember('inherited-policy', ATTRIBUTE, 'bool', 'boolean',
                None, None,
                [], [],
                '''                Is Inherited Policy
                ''',
                'inherited_policy',
                'Cisco-IOS-XR-crypto-macsec-mka-oper', False, is_config=False),
            _MetaInfoClassMember('policy', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Policy Name
                ''',
                'policy',
                'Cisco-IOS-XR-crypto-macsec-mka-oper', False, is_config=False),
            _MetaInfoClassMember('priority', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                Key Server Priority
                ''',
                'priority',
                'Cisco-IOS-XR-crypto-macsec-mka-oper', False, is_config=False),
            _MetaInfoClassMember('my-mac', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                My MAC
                ''',
                'my_mac',
                'Cisco-IOS-XR-crypto-macsec-mka-oper', False, is_config=False),
            _MetaInfoClassMember('delay-protection', ATTRIBUTE, 'bool', 'boolean',
                None, None,
                [], [],
                '''                Delay Protect
                ''',
                'delay_protection',
                'Cisco-IOS-XR-crypto-macsec-mka-oper', False, is_config=False),
            _MetaInfoClassMember('replay-protect', ATTRIBUTE, 'bool', 'boolean',
                None, None,
                [], [],
                '''                Replay Protect
                ''',
                'replay_protect',
                'Cisco-IOS-XR-crypto-macsec-mka-oper', False, is_config=False),
            _MetaInfoClassMember('window-size', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                Replay Window Size
                ''',
                'window_size',
                'Cisco-IOS-XR-crypto-macsec-mka-oper', False, is_config=False),
            _MetaInfoClassMember('include-icv-indicator', ATTRIBUTE, 'bool', 'boolean',
                None, None,
                [], [],
                '''                IncludeICVIndicator
                ''',
                'include_icv_indicator',
                'Cisco-IOS-XR-crypto-macsec-mka-oper', False, is_config=False),
            _MetaInfoClassMember('confidentiality-offset', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                Confidentiality Offset
                ''',
                'confidentiality_offset',
                'Cisco-IOS-XR-crypto-macsec-mka-oper', False, is_config=False),
            _MetaInfoClassMember('algo-agility', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                Alogorithm Agility
                ''',
                'algo_agility',
                'Cisco-IOS-XR-crypto-macsec-mka-oper', False, is_config=False),
            _MetaInfoClassMember('capability', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                MACSec Capability
                ''',
                'capability',
                'Cisco-IOS-XR-crypto-macsec-mka-oper', False, is_config=False),
            _MetaInfoClassMember('mka-cipher-suite', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                MKA Cipher Suite
                ''',
                'mka_cipher_suite',
                'Cisco-IOS-XR-crypto-macsec-mka-oper', False, is_config=False),
            _MetaInfoClassMember('configured-mac-sec-cipher-suite', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                configured cipher suite
                ''',
                'configured_mac_sec_cipher_suite',
                'Cisco-IOS-XR-crypto-macsec-mka-oper', False, is_config=False),
            _MetaInfoClassMember('mac-sec-desired', ATTRIBUTE, 'bool', 'boolean',
                None, None,
                [], [],
                '''                MACSec Desired
                ''',
                'mac_sec_desired',
                'Cisco-IOS-XR-crypto-macsec-mka-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-crypto-macsec-mka-oper',
            'session-summary',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-crypto-macsec-mka-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_macsec_mka_oper',
            is_config=False,
        ),
    },
    'Macsec.Mka.Interfaces.Interface.Session.Vp.FallbackKeepalive.PeersStatus.Peer.PeerData' : {
        'meta_info' : _MetaInfoClass('Macsec.Mka.Interfaces.Interface.Session.Vp.FallbackKeepalive.PeersStatus.Peer.PeerData', REFERENCE_CLASS,
            '''Peer Status Data''',
            False, 
            [
            _MetaInfoClassMember('mi', ATTRIBUTE, 'str', 'string',
                None, None,
                [(0, 25)], [],
                '''                Member ID
                ''',
                'mi',
                'Cisco-IOS-XR-crypto-macsec-mka-oper', False, is_config=False),
            _MetaInfoClassMember('icv-status', ATTRIBUTE, 'str', 'string',
                None, None,
                [(0, 10)], [],
                '''                ICV Status
                ''',
                'icv_status',
                'Cisco-IOS-XR-crypto-macsec-mka-oper', False, is_config=False),
            _MetaInfoClassMember('icv-check-timestamp', ATTRIBUTE, 'str', 'string',
                None, None,
                [(0, 128)], [],
                '''                ICV Check Timestamp
                ''',
                'icv_check_timestamp',
                'Cisco-IOS-XR-crypto-macsec-mka-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-crypto-macsec-mka-oper',
            'peer-data',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-crypto-macsec-mka-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_macsec_mka_oper',
            is_config=False,
        ),
    },
    'Macsec.Mka.Interfaces.Interface.Session.Vp.FallbackKeepalive.PeersStatus.Peer' : {
        'meta_info' : _MetaInfoClass('Macsec.Mka.Interfaces.Interface.Session.Vp.FallbackKeepalive.PeersStatus.Peer', REFERENCE_LIST,
            '''Peer List''',
            False, 
            [
            _MetaInfoClassMember('peer-data', REFERENCE_CLASS, 'PeerData', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_macsec_mka_oper', 'Macsec.Mka.Interfaces.Interface.Session.Vp.FallbackKeepalive.PeersStatus.Peer.PeerData',
                [], [],
                '''                Peer Status Data
                ''',
                'peer_data',
                'Cisco-IOS-XR-crypto-macsec-mka-oper', False, is_config=False),
            _MetaInfoClassMember('sci', ATTRIBUTE, 'str', 'string',
                None, None,
                [(0, 17)], [],
                '''                Rx SCI
                ''',
                'sci',
                'Cisco-IOS-XR-crypto-macsec-mka-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-crypto-macsec-mka-oper',
            'peer',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-crypto-macsec-mka-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_macsec_mka_oper',
            is_config=False,
        ),
    },
    'Macsec.Mka.Interfaces.Interface.Session.Vp.FallbackKeepalive.PeersStatus' : {
        'meta_info' : _MetaInfoClass('Macsec.Mka.Interfaces.Interface.Session.Vp.FallbackKeepalive.PeersStatus', REFERENCE_CLASS,
            '''Peers Status''',
            False, 
            [
            _MetaInfoClassMember('tx-mkpdu-timestamp', ATTRIBUTE, 'str', 'string',
                None, None,
                [(0, 128)], [],
                '''                Tx MKPDU Timestamp
                ''',
                'tx_mkpdu_timestamp',
                'Cisco-IOS-XR-crypto-macsec-mka-oper', False, is_config=False),
            _MetaInfoClassMember('peer-count', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                Peer Count
                ''',
                'peer_count',
                'Cisco-IOS-XR-crypto-macsec-mka-oper', False, is_config=False),
            _MetaInfoClassMember('peer', REFERENCE_LIST, 'Peer', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_macsec_mka_oper', 'Macsec.Mka.Interfaces.Interface.Session.Vp.FallbackKeepalive.PeersStatus.Peer',
                [], [],
                '''                Peer List
                ''',
                'peer',
                'Cisco-IOS-XR-crypto-macsec-mka-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-crypto-macsec-mka-oper',
            'peers-status',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-crypto-macsec-mka-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_macsec_mka_oper',
            is_config=False,
        ),
    },
    'Macsec.Mka.Interfaces.Interface.Session.Vp.FallbackKeepalive' : {
        'meta_info' : _MetaInfoClass('Macsec.Mka.Interfaces.Interface.Session.Vp.FallbackKeepalive', REFERENCE_LIST,
            '''Fallback Keepalive''',
            False, 
            [
            _MetaInfoClassMember('peers-status', REFERENCE_CLASS, 'PeersStatus', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_macsec_mka_oper', 'Macsec.Mka.Interfaces.Interface.Session.Vp.FallbackKeepalive.PeersStatus',
                [], [],
                '''                Peers Status
                ''',
                'peers_status',
                'Cisco-IOS-XR-crypto-macsec-mka-oper', False, is_config=False),
            _MetaInfoClassMember('ckn', ATTRIBUTE, 'str', 'string',
                None, None,
                [(0, 65)], [],
                '''                CKN
                ''',
                'ckn',
                'Cisco-IOS-XR-crypto-macsec-mka-oper', False, is_config=False),
            _MetaInfoClassMember('mi', ATTRIBUTE, 'str', 'string',
                None, None,
                [(0, 25)], [],
                '''                Member Identifier
                ''',
                'mi',
                'Cisco-IOS-XR-crypto-macsec-mka-oper', False, is_config=False),
            _MetaInfoClassMember('mn', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                Message Number
                ''',
                'mn',
                'Cisco-IOS-XR-crypto-macsec-mka-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-crypto-macsec-mka-oper',
            'fallback-keepalive',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-crypto-macsec-mka-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_macsec_mka_oper',
            is_config=False,
        ),
    },
    'Macsec.Mka.Interfaces.Interface.Session.Vp' : {
        'meta_info' : _MetaInfoClass('Macsec.Mka.Interfaces.Interface.Session.Vp', REFERENCE_CLASS,
            '''Virtual Pointer Info''',
            False, 
            [
            _MetaInfoClassMember('my-sci', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Local SCI(MAC)
                ''',
                'my_sci',
                'Cisco-IOS-XR-crypto-macsec-mka-oper', False, is_config=False),
            _MetaInfoClassMember('virtual-port-id', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                Virtual Port ID
                ''',
                'virtual_port_id',
                'Cisco-IOS-XR-crypto-macsec-mka-oper', False, is_config=False),
            _MetaInfoClassMember('latest-rx', ATTRIBUTE, 'bool', 'boolean',
                None, None,
                [], [],
                '''                Latest Rx status
                ''',
                'latest_rx',
                'Cisco-IOS-XR-crypto-macsec-mka-oper', False, is_config=False),
            _MetaInfoClassMember('latest-tx', ATTRIBUTE, 'bool', 'boolean',
                None, None,
                [], [],
                '''                Latest Tx status
                ''',
                'latest_tx',
                'Cisco-IOS-XR-crypto-macsec-mka-oper', False, is_config=False),
            _MetaInfoClassMember('latest-an', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                Latest SAK AN
                ''',
                'latest_an',
                'Cisco-IOS-XR-crypto-macsec-mka-oper', False, is_config=False),
            _MetaInfoClassMember('latest-ki', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Latest SAK KI
                ''',
                'latest_ki',
                'Cisco-IOS-XR-crypto-macsec-mka-oper', False, is_config=False),
            _MetaInfoClassMember('latest-kn', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                Latest SAK KN
                ''',
                'latest_kn',
                'Cisco-IOS-XR-crypto-macsec-mka-oper', False, is_config=False),
            _MetaInfoClassMember('old-rx', ATTRIBUTE, 'bool', 'boolean',
                None, None,
                [], [],
                '''                Old Rx status
                ''',
                'old_rx',
                'Cisco-IOS-XR-crypto-macsec-mka-oper', False, is_config=False),
            _MetaInfoClassMember('old-tx', ATTRIBUTE, 'bool', 'boolean',
                None, None,
                [], [],
                '''                Old Tx status
                ''',
                'old_tx',
                'Cisco-IOS-XR-crypto-macsec-mka-oper', False, is_config=False),
            _MetaInfoClassMember('old-an', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                Old SAK AN
                ''',
                'old_an',
                'Cisco-IOS-XR-crypto-macsec-mka-oper', False, is_config=False),
            _MetaInfoClassMember('old-ki', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Old SAK KI
                ''',
                'old_ki',
                'Cisco-IOS-XR-crypto-macsec-mka-oper', False, is_config=False),
            _MetaInfoClassMember('old-kn', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                Old SAK KN
                ''',
                'old_kn',
                'Cisco-IOS-XR-crypto-macsec-mka-oper', False, is_config=False),
            _MetaInfoClassMember('wait-time', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                SAK Transmit Wait Time
                ''',
                'wait_time',
                'Cisco-IOS-XR-crypto-macsec-mka-oper', False, is_config=False),
            _MetaInfoClassMember('retire-time', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                SAK Retire time
                ''',
                'retire_time',
                'Cisco-IOS-XR-crypto-macsec-mka-oper', False, is_config=False),
            _MetaInfoClassMember('macsec-cipher-suite', REFERENCE_ENUM_CLASS, 'MacsecCipherSuite', 'Macsec-cipher-suite',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_macsec_mka_oper', 'MacsecCipherSuite',
                [], [],
                '''                SAK Cipher Suite
                ''',
                'macsec_cipher_suite',
                'Cisco-IOS-XR-crypto-macsec-mka-oper', False, is_config=False),
            _MetaInfoClassMember('ssci', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                SSCI of the Local TxSC
                ''',
                'ssci',
                'Cisco-IOS-XR-crypto-macsec-mka-oper', False, is_config=False),
            _MetaInfoClassMember('time-to-sak-rekey', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Next SAK Rekey time in Sec
                ''',
                'time_to_sak_rekey',
                'Cisco-IOS-XR-crypto-macsec-mka-oper', False, is_config=False),
            _MetaInfoClassMember('fallback-keepalive', REFERENCE_LIST, 'FallbackKeepalive', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_macsec_mka_oper', 'Macsec.Mka.Interfaces.Interface.Session.Vp.FallbackKeepalive',
                [], [],
                '''                Fallback Keepalive
                ''',
                'fallback_keepalive',
                'Cisco-IOS-XR-crypto-macsec-mka-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-crypto-macsec-mka-oper',
            'vp',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-crypto-macsec-mka-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_macsec_mka_oper',
            is_config=False,
        ),
    },
    'Macsec.Mka.Interfaces.Interface.Session.Ca.PeersStatus.Peer.PeerData' : {
        'meta_info' : _MetaInfoClass('Macsec.Mka.Interfaces.Interface.Session.Ca.PeersStatus.Peer.PeerData', REFERENCE_CLASS,
            '''Peer Status Data''',
            False, 
            [
            _MetaInfoClassMember('mi', ATTRIBUTE, 'str', 'string',
                None, None,
                [(0, 25)], [],
                '''                Member ID
                ''',
                'mi',
                'Cisco-IOS-XR-crypto-macsec-mka-oper', False, is_config=False),
            _MetaInfoClassMember('icv-status', ATTRIBUTE, 'str', 'string',
                None, None,
                [(0, 10)], [],
                '''                ICV Status
                ''',
                'icv_status',
                'Cisco-IOS-XR-crypto-macsec-mka-oper', False, is_config=False),
            _MetaInfoClassMember('icv-check-timestamp', ATTRIBUTE, 'str', 'string',
                None, None,
                [(0, 128)], [],
                '''                ICV Check Timestamp
                ''',
                'icv_check_timestamp',
                'Cisco-IOS-XR-crypto-macsec-mka-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-crypto-macsec-mka-oper',
            'peer-data',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-crypto-macsec-mka-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_macsec_mka_oper',
            is_config=False,
        ),
    },
    'Macsec.Mka.Interfaces.Interface.Session.Ca.PeersStatus.Peer' : {
        'meta_info' : _MetaInfoClass('Macsec.Mka.Interfaces.Interface.Session.Ca.PeersStatus.Peer', REFERENCE_LIST,
            '''Peer List''',
            False, 
            [
            _MetaInfoClassMember('peer-data', REFERENCE_CLASS, 'PeerData', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_macsec_mka_oper', 'Macsec.Mka.Interfaces.Interface.Session.Ca.PeersStatus.Peer.PeerData',
                [], [],
                '''                Peer Status Data
                ''',
                'peer_data',
                'Cisco-IOS-XR-crypto-macsec-mka-oper', False, is_config=False),
            _MetaInfoClassMember('sci', ATTRIBUTE, 'str', 'string',
                None, None,
                [(0, 17)], [],
                '''                Rx SCI
                ''',
                'sci',
                'Cisco-IOS-XR-crypto-macsec-mka-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-crypto-macsec-mka-oper',
            'peer',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-crypto-macsec-mka-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_macsec_mka_oper',
            is_config=False,
        ),
    },
    'Macsec.Mka.Interfaces.Interface.Session.Ca.PeersStatus' : {
        'meta_info' : _MetaInfoClass('Macsec.Mka.Interfaces.Interface.Session.Ca.PeersStatus', REFERENCE_CLASS,
            '''Peers Status''',
            False, 
            [
            _MetaInfoClassMember('tx-mkpdu-timestamp', ATTRIBUTE, 'str', 'string',
                None, None,
                [(0, 128)], [],
                '''                Tx MKPDU Timestamp
                ''',
                'tx_mkpdu_timestamp',
                'Cisco-IOS-XR-crypto-macsec-mka-oper', False, is_config=False),
            _MetaInfoClassMember('peer-count', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                Peer Count
                ''',
                'peer_count',
                'Cisco-IOS-XR-crypto-macsec-mka-oper', False, is_config=False),
            _MetaInfoClassMember('peer', REFERENCE_LIST, 'Peer', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_macsec_mka_oper', 'Macsec.Mka.Interfaces.Interface.Session.Ca.PeersStatus.Peer',
                [], [],
                '''                Peer List
                ''',
                'peer',
                'Cisco-IOS-XR-crypto-macsec-mka-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-crypto-macsec-mka-oper',
            'peers-status',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-crypto-macsec-mka-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_macsec_mka_oper',
            is_config=False,
        ),
    },
    'Macsec.Mka.Interfaces.Interface.Session.Ca.LivePeer' : {
        'meta_info' : _MetaInfoClass('Macsec.Mka.Interfaces.Interface.Session.Ca.LivePeer', REFERENCE_LIST,
            '''Live Peer List''',
            False, 
            [
            _MetaInfoClassMember('mi', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Member ID
                ''',
                'mi',
                'Cisco-IOS-XR-crypto-macsec-mka-oper', False, is_config=False),
            _MetaInfoClassMember('sci', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Rx SCI
                ''',
                'sci',
                'Cisco-IOS-XR-crypto-macsec-mka-oper', False, is_config=False),
            _MetaInfoClassMember('mn', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                Message Number
                ''',
                'mn',
                'Cisco-IOS-XR-crypto-macsec-mka-oper', False, is_config=False),
            _MetaInfoClassMember('priority', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                KS Priority
                ''',
                'priority',
                'Cisco-IOS-XR-crypto-macsec-mka-oper', False, is_config=False),
            _MetaInfoClassMember('ssci', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                Peer SSCI
                ''',
                'ssci',
                'Cisco-IOS-XR-crypto-macsec-mka-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-crypto-macsec-mka-oper',
            'live-peer',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-crypto-macsec-mka-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_macsec_mka_oper',
            is_config=False,
        ),
    },
    'Macsec.Mka.Interfaces.Interface.Session.Ca.PotentialPeer' : {
        'meta_info' : _MetaInfoClass('Macsec.Mka.Interfaces.Interface.Session.Ca.PotentialPeer', REFERENCE_LIST,
            '''Potential Peer List''',
            False, 
            [
            _MetaInfoClassMember('mi', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Member ID
                ''',
                'mi',
                'Cisco-IOS-XR-crypto-macsec-mka-oper', False, is_config=False),
            _MetaInfoClassMember('sci', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Rx SCI
                ''',
                'sci',
                'Cisco-IOS-XR-crypto-macsec-mka-oper', False, is_config=False),
            _MetaInfoClassMember('mn', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                Message Number
                ''',
                'mn',
                'Cisco-IOS-XR-crypto-macsec-mka-oper', False, is_config=False),
            _MetaInfoClassMember('priority', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                KS Priority
                ''',
                'priority',
                'Cisco-IOS-XR-crypto-macsec-mka-oper', False, is_config=False),
            _MetaInfoClassMember('ssci', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                Peer SSCI
                ''',
                'ssci',
                'Cisco-IOS-XR-crypto-macsec-mka-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-crypto-macsec-mka-oper',
            'potential-peer',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-crypto-macsec-mka-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_macsec_mka_oper',
            is_config=False,
        ),
    },
    'Macsec.Mka.Interfaces.Interface.Session.Ca.DormantPeer' : {
        'meta_info' : _MetaInfoClass('Macsec.Mka.Interfaces.Interface.Session.Ca.DormantPeer', REFERENCE_LIST,
            '''Dormant Peer List''',
            False, 
            [
            _MetaInfoClassMember('mi', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Member ID
                ''',
                'mi',
                'Cisco-IOS-XR-crypto-macsec-mka-oper', False, is_config=False),
            _MetaInfoClassMember('sci', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Rx SCI
                ''',
                'sci',
                'Cisco-IOS-XR-crypto-macsec-mka-oper', False, is_config=False),
            _MetaInfoClassMember('mn', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                Message Number
                ''',
                'mn',
                'Cisco-IOS-XR-crypto-macsec-mka-oper', False, is_config=False),
            _MetaInfoClassMember('priority', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                KS Priority
                ''',
                'priority',
                'Cisco-IOS-XR-crypto-macsec-mka-oper', False, is_config=False),
            _MetaInfoClassMember('ssci', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                Peer SSCI
                ''',
                'ssci',
                'Cisco-IOS-XR-crypto-macsec-mka-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-crypto-macsec-mka-oper',
            'dormant-peer',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-crypto-macsec-mka-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_macsec_mka_oper',
            is_config=False,
        ),
    },
    'Macsec.Mka.Interfaces.Interface.Session.Ca' : {
        'meta_info' : _MetaInfoClass('Macsec.Mka.Interfaces.Interface.Session.Ca', REFERENCE_LIST,
            '''CA List for a Session''',
            False, 
            [
            _MetaInfoClassMember('peers-status', REFERENCE_CLASS, 'PeersStatus', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_macsec_mka_oper', 'Macsec.Mka.Interfaces.Interface.Session.Ca.PeersStatus',
                [], [],
                '''                Peers Status
                ''',
                'peers_status',
                'Cisco-IOS-XR-crypto-macsec-mka-oper', False, is_config=False),
            _MetaInfoClassMember('is-key-server', ATTRIBUTE, 'bool', 'boolean',
                None, None,
                [], [],
                '''                Is Key Server
                ''',
                'is_key_server',
                'Cisco-IOS-XR-crypto-macsec-mka-oper', False, is_config=False),
            _MetaInfoClassMember('status', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Session Status [Secured/Not Secured]
                ''',
                'status',
                'Cisco-IOS-XR-crypto-macsec-mka-oper', False, is_config=False),
            _MetaInfoClassMember('num-live-peers', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                Number of Live Peers
                ''',
                'num_live_peers',
                'Cisco-IOS-XR-crypto-macsec-mka-oper', False, is_config=False),
            _MetaInfoClassMember('first-ca', ATTRIBUTE, 'bool', 'boolean',
                None, None,
                [], [],
                '''                Is First CA
                ''',
                'first_ca',
                'Cisco-IOS-XR-crypto-macsec-mka-oper', False, is_config=False),
            _MetaInfoClassMember('peer-sci', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Peer SCI(MAC)
                ''',
                'peer_sci',
                'Cisco-IOS-XR-crypto-macsec-mka-oper', False, is_config=False),
            _MetaInfoClassMember('num-live-peers-responded', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                Number of Live Peers responded
                ''',
                'num_live_peers_responded',
                'Cisco-IOS-XR-crypto-macsec-mka-oper', False, is_config=False),
            _MetaInfoClassMember('ckn', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                CKN
                ''',
                'ckn',
                'Cisco-IOS-XR-crypto-macsec-mka-oper', False, is_config=False),
            _MetaInfoClassMember('my-mi', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Member Identifier
                ''',
                'my_mi',
                'Cisco-IOS-XR-crypto-macsec-mka-oper', False, is_config=False),
            _MetaInfoClassMember('my-mn', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                Message Number
                ''',
                'my_mn',
                'Cisco-IOS-XR-crypto-macsec-mka-oper', False, is_config=False),
            _MetaInfoClassMember('authenticator', ATTRIBUTE, 'bool', 'boolean',
                None, None,
                [], [],
                '''                authenticator
                ''',
                'authenticator',
                'Cisco-IOS-XR-crypto-macsec-mka-oper', False, is_config=False),
            _MetaInfoClassMember('status-description', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Status Description
                ''',
                'status_description',
                'Cisco-IOS-XR-crypto-macsec-mka-oper', False, is_config=False),
            _MetaInfoClassMember('authentication-mode', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                CA Authentication Mode
                :PRIMARY-PSK/FALLBACK-PSK/EAP
                ''',
                'authentication_mode',
                'Cisco-IOS-XR-crypto-macsec-mka-oper', False, is_config=False),
            _MetaInfoClassMember('key-chain', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Key Chain name
                ''',
                'key_chain',
                'Cisco-IOS-XR-crypto-macsec-mka-oper', False, is_config=False),
            _MetaInfoClassMember('live-peer', REFERENCE_LIST, 'LivePeer', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_macsec_mka_oper', 'Macsec.Mka.Interfaces.Interface.Session.Ca.LivePeer',
                [], [],
                '''                Live Peer List
                ''',
                'live_peer',
                'Cisco-IOS-XR-crypto-macsec-mka-oper', False, is_config=False),
            _MetaInfoClassMember('potential-peer', REFERENCE_LIST, 'PotentialPeer', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_macsec_mka_oper', 'Macsec.Mka.Interfaces.Interface.Session.Ca.PotentialPeer',
                [], [],
                '''                Potential Peer List
                ''',
                'potential_peer',
                'Cisco-IOS-XR-crypto-macsec-mka-oper', False, is_config=False),
            _MetaInfoClassMember('dormant-peer', REFERENCE_LIST, 'DormantPeer', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_macsec_mka_oper', 'Macsec.Mka.Interfaces.Interface.Session.Ca.DormantPeer',
                [], [],
                '''                Dormant Peer List
                ''',
                'dormant_peer',
                'Cisco-IOS-XR-crypto-macsec-mka-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-crypto-macsec-mka-oper',
            'ca',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-crypto-macsec-mka-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_macsec_mka_oper',
            is_config=False,
        ),
    },
    'Macsec.Mka.Interfaces.Interface.Session' : {
        'meta_info' : _MetaInfoClass('Macsec.Mka.Interfaces.Interface.Session', REFERENCE_CLASS,
            '''MKA Session Data''',
            False, 
            [
            _MetaInfoClassMember('session-summary', REFERENCE_CLASS, 'SessionSummary', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_macsec_mka_oper', 'Macsec.Mka.Interfaces.Interface.Session.SessionSummary',
                [], [],
                '''                Session summary
                ''',
                'session_summary',
                'Cisco-IOS-XR-crypto-macsec-mka-oper', False, is_config=False),
            _MetaInfoClassMember('vp', REFERENCE_CLASS, 'Vp', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_macsec_mka_oper', 'Macsec.Mka.Interfaces.Interface.Session.Vp',
                [], [],
                '''                Virtual Pointer Info
                ''',
                'vp',
                'Cisco-IOS-XR-crypto-macsec-mka-oper', False, is_config=False),
            _MetaInfoClassMember('ca', REFERENCE_LIST, 'Ca', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_macsec_mka_oper', 'Macsec.Mka.Interfaces.Interface.Session.Ca',
                [], [],
                '''                CA List for a Session
                ''',
                'ca',
                'Cisco-IOS-XR-crypto-macsec-mka-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-crypto-macsec-mka-oper',
            'session',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-crypto-macsec-mka-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_macsec_mka_oper',
            is_config=False,
        ),
    },
    'Macsec.Mka.Interfaces.Interface.Info.InterfaceSummary' : {
        'meta_info' : _MetaInfoClass('Macsec.Mka.Interfaces.Interface.Info.InterfaceSummary', REFERENCE_CLASS,
            '''MKA Interface Summary''',
            False, 
            [
            _MetaInfoClassMember('interface-name', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                macsec configured interface
                ''',
                'interface_name',
                'Cisco-IOS-XR-crypto-macsec-mka-oper', False, is_config=False),
            _MetaInfoClassMember('short-name', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Short Name String
                ''',
                'short_name',
                'Cisco-IOS-XR-crypto-macsec-mka-oper', False, is_config=False),
            _MetaInfoClassMember('key-chain', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Name  of the Key chain
                ''',
                'key_chain',
                'Cisco-IOS-XR-crypto-macsec-mka-oper', False, is_config=False),
            _MetaInfoClassMember('policy', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Policy name
                ''',
                'policy',
                'Cisco-IOS-XR-crypto-macsec-mka-oper', False, is_config=False),
            _MetaInfoClassMember('macsec-svc-port', ATTRIBUTE, 'bool', 'boolean',
                None, None,
                [], [],
                '''                Is macsec-service port or not
                ''',
                'macsec_svc_port',
                'Cisco-IOS-XR-crypto-macsec-mka-oper', False, is_config=False),
            _MetaInfoClassMember('macsec-svc-port-type', REFERENCE_ENUM_CLASS, 'MacsecServicePort', 'Macsec-service-port',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_macsec_mka_oper', 'MacsecServicePort',
                [], [],
                '''                Macsec-service Encryption / Decryption port
                ''',
                'macsec_svc_port_type',
                'Cisco-IOS-XR-crypto-macsec-mka-oper', False, is_config=False),
            _MetaInfoClassMember('svcport-short-name', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Macsec Service paired port Short Name String
                ''',
                'svcport_short_name',
                'Cisco-IOS-XR-crypto-macsec-mka-oper', False, is_config=False),
            _MetaInfoClassMember('mka-mode', REFERENCE_ENUM_CLASS, 'MkaAuthenticationMode', 'Mka-authentication-mode',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_macsec_mka_oper', 'MkaAuthenticationMode',
                [], [],
                '''                MKA authentication mode
                ''',
                'mka_mode',
                'Cisco-IOS-XR-crypto-macsec-mka-oper', False, is_config=False),
            _MetaInfoClassMember('fallback-keychain', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                fallback Keychain name
                ''',
                'fallback_keychain',
                'Cisco-IOS-XR-crypto-macsec-mka-oper', False, is_config=False),
            _MetaInfoClassMember('macsec-shutdown', ATTRIBUTE, 'bool', 'boolean',
                None, None,
                [], [],
                '''                MacsecShutdown
                ''',
                'macsec_shutdown',
                'Cisco-IOS-XR-crypto-macsec-mka-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-crypto-macsec-mka-oper',
            'interface-summary',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-crypto-macsec-mka-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_macsec_mka_oper',
            is_config=False,
        ),
    },
    'Macsec.Mka.Interfaces.Interface.Info' : {
        'meta_info' : _MetaInfoClass('Macsec.Mka.Interfaces.Interface.Info', REFERENCE_CLASS,
            '''MKA Interface Summary Data''',
            False, 
            [
            _MetaInfoClassMember('interface-summary', REFERENCE_CLASS, 'InterfaceSummary', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_macsec_mka_oper', 'Macsec.Mka.Interfaces.Interface.Info.InterfaceSummary',
                [], [],
                '''                MKA Interface Summary
                ''',
                'interface_summary',
                'Cisco-IOS-XR-crypto-macsec-mka-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-crypto-macsec-mka-oper',
            'info',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-crypto-macsec-mka-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_macsec_mka_oper',
            is_config=False,
        ),
    },
    'Macsec.Mka.Interfaces.Interface' : {
        'meta_info' : _MetaInfoClass('Macsec.Mka.Interfaces.Interface', REFERENCE_LIST,
            '''MKA Data for the Interface''',
            False, 
            [
            _MetaInfoClassMember('name', ATTRIBUTE, 'str', 'xr:Interface-name',
                None, None,
                [], [b'[a-zA-Z0-9._/-]+'],
                '''                Interface Name
                ''',
                'name',
                'Cisco-IOS-XR-crypto-macsec-mka-oper', True, is_config=False),
            _MetaInfoClassMember('session', REFERENCE_CLASS, 'Session', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_macsec_mka_oper', 'Macsec.Mka.Interfaces.Interface.Session',
                [], [],
                '''                MKA Session Data
                ''',
                'session',
                'Cisco-IOS-XR-crypto-macsec-mka-oper', False, is_config=False),
            _MetaInfoClassMember('info', REFERENCE_CLASS, 'Info', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_macsec_mka_oper', 'Macsec.Mka.Interfaces.Interface.Info',
                [], [],
                '''                MKA Interface Summary Data
                ''',
                'info',
                'Cisco-IOS-XR-crypto-macsec-mka-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-crypto-macsec-mka-oper',
            'interface',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-crypto-macsec-mka-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_macsec_mka_oper',
            is_config=False,
        ),
    },
    'Macsec.Mka.Interfaces' : {
        'meta_info' : _MetaInfoClass('Macsec.Mka.Interfaces', REFERENCE_CLASS,
            '''MKA Data''',
            False, 
            [
            _MetaInfoClassMember('interface', REFERENCE_LIST, 'Interface', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_macsec_mka_oper', 'Macsec.Mka.Interfaces.Interface',
                [], [],
                '''                MKA Data for the Interface
                ''',
                'interface',
                'Cisco-IOS-XR-crypto-macsec-mka-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-crypto-macsec-mka-oper',
            'interfaces',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-crypto-macsec-mka-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_macsec_mka_oper',
            is_config=False,
        ),
    },
    'Macsec.Mka' : {
        'meta_info' : _MetaInfoClass('Macsec.Mka', REFERENCE_CLASS,
            '''MKA Data''',
            False, 
            [
            _MetaInfoClassMember('interfaces', REFERENCE_CLASS, 'Interfaces', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_macsec_mka_oper', 'Macsec.Mka.Interfaces',
                [], [],
                '''                MKA Data
                ''',
                'interfaces',
                'Cisco-IOS-XR-crypto-macsec-mka-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-crypto-macsec-mka-oper',
            'mka',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-crypto-macsec-mka-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_macsec_mka_oper',
            is_config=False,
        ),
    },
    'Macsec' : {
        'meta_info' : _MetaInfoClass('Macsec', REFERENCE_CLASS,
            '''Macsec operational data''',
            False, 
            [
            _MetaInfoClassMember('mka', REFERENCE_CLASS, 'Mka', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_macsec_mka_oper', 'Macsec.Mka',
                [], [],
                '''                MKA Data
                ''',
                'mka',
                'Cisco-IOS-XR-crypto-macsec-mka-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-crypto-macsec-mka-oper',
            'macsec',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-crypto-macsec-mka-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_macsec_mka_oper',
            is_config=False,
        ),
    },
}
_meta_table['Macsec.Mka.Interfaces.Interface.Session.SessionSummary.OuterTag']['meta_info'].parent =_meta_table['Macsec.Mka.Interfaces.Interface.Session.SessionSummary']['meta_info']
_meta_table['Macsec.Mka.Interfaces.Interface.Session.SessionSummary.InnerTag']['meta_info'].parent =_meta_table['Macsec.Mka.Interfaces.Interface.Session.SessionSummary']['meta_info']
_meta_table['Macsec.Mka.Interfaces.Interface.Session.Vp.FallbackKeepalive.PeersStatus.Peer.PeerData']['meta_info'].parent =_meta_table['Macsec.Mka.Interfaces.Interface.Session.Vp.FallbackKeepalive.PeersStatus.Peer']['meta_info']
_meta_table['Macsec.Mka.Interfaces.Interface.Session.Vp.FallbackKeepalive.PeersStatus.Peer']['meta_info'].parent =_meta_table['Macsec.Mka.Interfaces.Interface.Session.Vp.FallbackKeepalive.PeersStatus']['meta_info']
_meta_table['Macsec.Mka.Interfaces.Interface.Session.Vp.FallbackKeepalive.PeersStatus']['meta_info'].parent =_meta_table['Macsec.Mka.Interfaces.Interface.Session.Vp.FallbackKeepalive']['meta_info']
_meta_table['Macsec.Mka.Interfaces.Interface.Session.Vp.FallbackKeepalive']['meta_info'].parent =_meta_table['Macsec.Mka.Interfaces.Interface.Session.Vp']['meta_info']
_meta_table['Macsec.Mka.Interfaces.Interface.Session.Ca.PeersStatus.Peer.PeerData']['meta_info'].parent =_meta_table['Macsec.Mka.Interfaces.Interface.Session.Ca.PeersStatus.Peer']['meta_info']
_meta_table['Macsec.Mka.Interfaces.Interface.Session.Ca.PeersStatus.Peer']['meta_info'].parent =_meta_table['Macsec.Mka.Interfaces.Interface.Session.Ca.PeersStatus']['meta_info']
_meta_table['Macsec.Mka.Interfaces.Interface.Session.Ca.PeersStatus']['meta_info'].parent =_meta_table['Macsec.Mka.Interfaces.Interface.Session.Ca']['meta_info']
_meta_table['Macsec.Mka.Interfaces.Interface.Session.Ca.LivePeer']['meta_info'].parent =_meta_table['Macsec.Mka.Interfaces.Interface.Session.Ca']['meta_info']
_meta_table['Macsec.Mka.Interfaces.Interface.Session.Ca.PotentialPeer']['meta_info'].parent =_meta_table['Macsec.Mka.Interfaces.Interface.Session.Ca']['meta_info']
_meta_table['Macsec.Mka.Interfaces.Interface.Session.Ca.DormantPeer']['meta_info'].parent =_meta_table['Macsec.Mka.Interfaces.Interface.Session.Ca']['meta_info']
_meta_table['Macsec.Mka.Interfaces.Interface.Session.SessionSummary']['meta_info'].parent =_meta_table['Macsec.Mka.Interfaces.Interface.Session']['meta_info']
_meta_table['Macsec.Mka.Interfaces.Interface.Session.Vp']['meta_info'].parent =_meta_table['Macsec.Mka.Interfaces.Interface.Session']['meta_info']
_meta_table['Macsec.Mka.Interfaces.Interface.Session.Ca']['meta_info'].parent =_meta_table['Macsec.Mka.Interfaces.Interface.Session']['meta_info']
_meta_table['Macsec.Mka.Interfaces.Interface.Info.InterfaceSummary']['meta_info'].parent =_meta_table['Macsec.Mka.Interfaces.Interface.Info']['meta_info']
_meta_table['Macsec.Mka.Interfaces.Interface.Session']['meta_info'].parent =_meta_table['Macsec.Mka.Interfaces.Interface']['meta_info']
_meta_table['Macsec.Mka.Interfaces.Interface.Info']['meta_info'].parent =_meta_table['Macsec.Mka.Interfaces.Interface']['meta_info']
_meta_table['Macsec.Mka.Interfaces.Interface']['meta_info'].parent =_meta_table['Macsec.Mka.Interfaces']['meta_info']
_meta_table['Macsec.Mka.Interfaces']['meta_info'].parent =_meta_table['Macsec.Mka']['meta_info']
_meta_table['Macsec.Mka']['meta_info'].parent =_meta_table['Macsec']['meta_info']
