
'''
This is auto-generated file,
which includes metadata for module Cisco_IOS_XR_prm_server_oper
'''

from ydk._core._dm_meta_info import _MetaInfoClassMember, _MetaInfoClass, _MetaInfoEnum
from ydk._core._dm_meta_info import ATTRIBUTE, REFERENCE_LIST, REFERENCE_LEAFLIST, REFERENCE_BITS, REFERENCE_UNION
from ydk._core._dm_meta_info import REFERENCE_CLASS, REFERENCE_IDENTITY_CLASS, REFERENCE_ENUM_CLASS, ANYXML_CLASS
from ydk._core._importer import _yang_ns

_meta_table = {
    'HardwareModule.Nodes.Node.Np.Cpu.Indexes.Index' : {
        'meta_info' : _MetaInfoClass('HardwareModule.Nodes.Node.Np.Cpu.Indexes.Index', REFERENCE_LIST,
            '''Queue Stats''',
            False, 
            [
            _MetaInfoClassMember('index', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                Index value
                ''',
                'index',
                'Cisco-IOS-XR-prm-server-oper', True, is_config=False),
            _MetaInfoClassMember('cos-q-name', ATTRIBUTE, 'str', 'string',
                None, None,
                [(0, 1024)], [],
                '''                CosQ Name
                ''',
                'cos_q_name',
                'Cisco-IOS-XR-prm-server-oper', False, is_config=False),
            _MetaInfoClassMember('cos-q', ATTRIBUTE, 'int', 'uint8',
                None, None,
                [('0', '255')], [],
                '''                CosQ No
                ''',
                'cos_q',
                'Cisco-IOS-XR-prm-server-oper', False, is_config=False),
            _MetaInfoClassMember('rx-channel', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                Rx DMA Channel
                ''',
                'rx_channel',
                'Cisco-IOS-XR-prm-server-oper', False, is_config=False),
            _MetaInfoClassMember('flow-rate', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                Flow Rate
                ''',
                'flow_rate',
                'Cisco-IOS-XR-prm-server-oper', False, is_config=False),
            _MetaInfoClassMember('burst', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                Burst
                ''',
                'burst',
                'Cisco-IOS-XR-prm-server-oper', False, is_config=False),
            _MetaInfoClassMember('accepted', ATTRIBUTE, 'int', 'uint64',
                None, None,
                [('0', '18446744073709551615')], [],
                '''                Accepted
                ''',
                'accepted',
                'Cisco-IOS-XR-prm-server-oper', False, is_config=False),
            _MetaInfoClassMember('dropped', ATTRIBUTE, 'int', 'uint64',
                None, None,
                [('0', '18446744073709551615')], [],
                '''                Dropped
                ''',
                'dropped',
                'Cisco-IOS-XR-prm-server-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-prm-server-oper',
            'index',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-prm-server-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_prm_server_oper',
            is_config=False,
        ),
    },
    'HardwareModule.Nodes.Node.Np.Cpu.Indexes' : {
        'meta_info' : _MetaInfoClass('HardwareModule.Nodes.Node.Np.Cpu.Indexes', REFERENCE_CLASS,
            '''Data for software resource''',
            False, 
            [
            _MetaInfoClassMember('index', REFERENCE_LIST, 'Index', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_prm_server_oper', 'HardwareModule.Nodes.Node.Np.Cpu.Indexes.Index',
                [], [],
                '''                Queue Stats
                ''',
                'index',
                'Cisco-IOS-XR-prm-server-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-prm-server-oper',
            'indexes',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-prm-server-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_prm_server_oper',
            is_config=False,
        ),
    },
    'HardwareModule.Nodes.Node.Np.Cpu' : {
        'meta_info' : _MetaInfoClass('HardwareModule.Nodes.Node.Np.Cpu', REFERENCE_CLASS,
            '''Resource specific''',
            False, 
            [
            _MetaInfoClassMember('indexes', REFERENCE_CLASS, 'Indexes', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_prm_server_oper', 'HardwareModule.Nodes.Node.Np.Cpu.Indexes',
                [], [],
                '''                Data for software resource
                ''',
                'indexes',
                'Cisco-IOS-XR-prm-server-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-prm-server-oper',
            'cpu',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-prm-server-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_prm_server_oper',
            is_config=False,
        ),
    },
    'HardwareModule.Nodes.Node.Np.PlatformDrop.Indxes.Indx' : {
        'meta_info' : _MetaInfoClass('HardwareModule.Nodes.Node.Np.PlatformDrop.Indxes.Indx', REFERENCE_LIST,
            '''Captured packets''',
            False, 
            [
            _MetaInfoClassMember('index', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                Index value
                ''',
                'index',
                'Cisco-IOS-XR-prm-server-oper', True, is_config=False),
            _MetaInfoClassMember('total-captured', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                Total packets Captured
                ''',
                'total_captured',
                'Cisco-IOS-XR-prm-server-oper', False, is_config=False),
            _MetaInfoClassMember('captured-pak', ATTRIBUTE, 'str', 'string',
                None, None,
                [(0, 1024)], [],
                '''                Captured Packet
                ''',
                'captured_pak',
                'Cisco-IOS-XR-prm-server-oper', False, is_config=False),
            _MetaInfoClassMember('pkt-index', ATTRIBUTE, 'int', 'uint8',
                None, None,
                [('0', '255')], [],
                '''                Packet Index
                ''',
                'pkt_index',
                'Cisco-IOS-XR-prm-server-oper', False, is_config=False),
            _MetaInfoClassMember('ifhandle', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                If Handle
                ''',
                'ifhandle',
                'Cisco-IOS-XR-prm-server-oper', False, is_config=False),
            _MetaInfoClassMember('buffer-len', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                Buffer Length
                ''',
                'buffer_len',
                'Cisco-IOS-XR-prm-server-oper', False, is_config=False),
            _MetaInfoClassMember('reason-hi', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                Reason Hi
                ''',
                'reason_hi',
                'Cisco-IOS-XR-prm-server-oper', False, is_config=False),
            _MetaInfoClassMember('reason', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                Reason
                ''',
                'reason',
                'Cisco-IOS-XR-prm-server-oper', False, is_config=False),
            _MetaInfoClassMember('years', ATTRIBUTE, 'int', 'uint64',
                None, None,
                [('0', '18446744073709551615')], [],
                '''                Year
                ''',
                'years',
                'Cisco-IOS-XR-prm-server-oper', False, is_config=False),
            _MetaInfoClassMember('hours', ATTRIBUTE, 'int', 'uint64',
                None, None,
                [('0', '18446744073709551615')], [],
                '''                Hours
                ''',
                'hours',
                'Cisco-IOS-XR-prm-server-oper', False, is_config=False),
            _MetaInfoClassMember('days', ATTRIBUTE, 'int', 'uint64',
                None, None,
                [('0', '18446744073709551615')], [],
                '''                Days
                ''',
                'days',
                'Cisco-IOS-XR-prm-server-oper', False, is_config=False),
            _MetaInfoClassMember('mins', ATTRIBUTE, 'int', 'uint64',
                None, None,
                [('0', '18446744073709551615')], [],
                '''                Minutes
                ''',
                'mins',
                'Cisco-IOS-XR-prm-server-oper', False, is_config=False),
            _MetaInfoClassMember('secs', ATTRIBUTE, 'int', 'uint64',
                None, None,
                [('0', '18446744073709551615')], [],
                '''                Seconds
                ''',
                'secs',
                'Cisco-IOS-XR-prm-server-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-prm-server-oper',
            'indx',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-prm-server-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_prm_server_oper',
            is_config=False,
        ),
    },
    'HardwareModule.Nodes.Node.Np.PlatformDrop.Indxes' : {
        'meta_info' : _MetaInfoClass('HardwareModule.Nodes.Node.Np.PlatformDrop.Indxes', REFERENCE_CLASS,
            '''Captured Packets''',
            False, 
            [
            _MetaInfoClassMember('indx', REFERENCE_LIST, 'Indx', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_prm_server_oper', 'HardwareModule.Nodes.Node.Np.PlatformDrop.Indxes.Indx',
                [], [],
                '''                Captured packets
                ''',
                'indx',
                'Cisco-IOS-XR-prm-server-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-prm-server-oper',
            'indxes',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-prm-server-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_prm_server_oper',
            is_config=False,
        ),
    },
    'HardwareModule.Nodes.Node.Np.PlatformDrop.Idxes.Idx' : {
        'meta_info' : _MetaInfoClass('HardwareModule.Nodes.Node.Np.PlatformDrop.Idxes.Idx', REFERENCE_LIST,
            '''Drop Stats''',
            False, 
            [
            _MetaInfoClassMember('index', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                Index value
                ''',
                'index',
                'Cisco-IOS-XR-prm-server-oper', True, is_config=False),
            _MetaInfoClassMember('drop-reason', ATTRIBUTE, 'str', 'string',
                None, None,
                [(0, 1024)], [],
                '''                Drop Reason
                ''',
                'drop_reason',
                'Cisco-IOS-XR-prm-server-oper', False, is_config=False),
            _MetaInfoClassMember('counters', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                Counter
                ''',
                'counters',
                'Cisco-IOS-XR-prm-server-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-prm-server-oper',
            'idx',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-prm-server-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_prm_server_oper',
            is_config=False,
        ),
    },
    'HardwareModule.Nodes.Node.Np.PlatformDrop.Idxes' : {
        'meta_info' : _MetaInfoClass('HardwareModule.Nodes.Node.Np.PlatformDrop.Idxes', REFERENCE_CLASS,
            '''Stats for Drop packets''',
            False, 
            [
            _MetaInfoClassMember('idx', REFERENCE_LIST, 'Idx', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_prm_server_oper', 'HardwareModule.Nodes.Node.Np.PlatformDrop.Idxes.Idx',
                [], [],
                '''                Drop Stats
                ''',
                'idx',
                'Cisco-IOS-XR-prm-server-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-prm-server-oper',
            'idxes',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-prm-server-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_prm_server_oper',
            is_config=False,
        ),
    },
    'HardwareModule.Nodes.Node.Np.PlatformDrop' : {
        'meta_info' : _MetaInfoClass('HardwareModule.Nodes.Node.Np.PlatformDrop', REFERENCE_CLASS,
            '''Platform drops''',
            False, 
            [
            _MetaInfoClassMember('indxes', REFERENCE_CLASS, 'Indxes', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_prm_server_oper', 'HardwareModule.Nodes.Node.Np.PlatformDrop.Indxes',
                [], [],
                '''                Captured Packets
                ''',
                'indxes',
                'Cisco-IOS-XR-prm-server-oper', False, is_config=False),
            _MetaInfoClassMember('idxes', REFERENCE_CLASS, 'Idxes', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_prm_server_oper', 'HardwareModule.Nodes.Node.Np.PlatformDrop.Idxes',
                [], [],
                '''                Stats for Drop packets
                ''',
                'idxes',
                'Cisco-IOS-XR-prm-server-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-prm-server-oper',
            'platform-drop',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-prm-server-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_prm_server_oper',
            is_config=False,
        ),
    },
    'HardwareModule.Nodes.Node.Np' : {
        'meta_info' : _MetaInfoClass('HardwareModule.Nodes.Node.Np', REFERENCE_CLASS,
            '''Server specific''',
            False, 
            [
            _MetaInfoClassMember('cpu', REFERENCE_CLASS, 'Cpu', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_prm_server_oper', 'HardwareModule.Nodes.Node.Np.Cpu',
                [], [],
                '''                Resource specific
                ''',
                'cpu',
                'Cisco-IOS-XR-prm-server-oper', False, is_config=False),
            _MetaInfoClassMember('platform-drop', REFERENCE_CLASS, 'PlatformDrop', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_prm_server_oper', 'HardwareModule.Nodes.Node.Np.PlatformDrop',
                [], [],
                '''                Platform drops
                ''',
                'platform_drop',
                'Cisco-IOS-XR-prm-server-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-prm-server-oper',
            'np',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-prm-server-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_prm_server_oper',
            is_config=False,
        ),
    },
    'HardwareModule.Nodes.Node' : {
        'meta_info' : _MetaInfoClass('HardwareModule.Nodes.Node', REFERENCE_LIST,
            '''Node Information''',
            False, 
            [
            _MetaInfoClassMember('node-name', ATTRIBUTE, 'str', 'xr:Node-id',
                None, None,
                [], [b'([a-zA-Z0-9_]*\\d+/){1,2}([a-zA-Z0-9_]*\\d+)'],
                '''                The node name
                ''',
                'node_name',
                'Cisco-IOS-XR-prm-server-oper', True, is_config=False),
            _MetaInfoClassMember('np', REFERENCE_CLASS, 'Np', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_prm_server_oper', 'HardwareModule.Nodes.Node.Np',
                [], [],
                '''                Server specific
                ''',
                'np',
                'Cisco-IOS-XR-prm-server-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-prm-server-oper',
            'node',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-prm-server-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_prm_server_oper',
            is_config=False,
        ),
    },
    'HardwareModule.Nodes' : {
        'meta_info' : _MetaInfoClass('HardwareModule.Nodes', REFERENCE_CLASS,
            '''List of PRM Nodes''',
            False, 
            [
            _MetaInfoClassMember('node', REFERENCE_LIST, 'Node', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_prm_server_oper', 'HardwareModule.Nodes.Node',
                [], [],
                '''                Node Information
                ''',
                'node',
                'Cisco-IOS-XR-prm-server-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-prm-server-oper',
            'nodes',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-prm-server-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_prm_server_oper',
            is_config=False,
        ),
    },
    'HardwareModule' : {
        'meta_info' : _MetaInfoClass('HardwareModule', REFERENCE_CLASS,
            '''PRM data''',
            False, 
            [
            _MetaInfoClassMember('nodes', REFERENCE_CLASS, 'Nodes', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_prm_server_oper', 'HardwareModule.Nodes',
                [], [],
                '''                List of PRM Nodes
                ''',
                'nodes',
                'Cisco-IOS-XR-prm-server-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-prm-server-oper',
            'hardware-module',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-prm-server-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_prm_server_oper',
            is_config=False,
        ),
    },
    'Prm.Nodes.Node.Server.Resource.Indexes.Index' : {
        'meta_info' : _MetaInfoClass('Prm.Nodes.Node.Server.Resource.Indexes.Index', REFERENCE_LIST,
            '''Data for software resource''',
            False, 
            [
            _MetaInfoClassMember('index', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                Index value
                ''',
                'index',
                'Cisco-IOS-XR-prm-server-oper', True, is_config=False),
            _MetaInfoClassMember('resource-name', ATTRIBUTE, 'str', 'string',
                None, None,
                [(0, 1024)], [],
                '''                Resource Name
                ''',
                'resource_name',
                'Cisco-IOS-XR-prm-server-oper', False, is_config=False),
            _MetaInfoClassMember('resource-type', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                Resource Type
                ''',
                'resource_type',
                'Cisco-IOS-XR-prm-server-oper', False, is_config=False),
            _MetaInfoClassMember('total-num', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                Total Resource Count
                ''',
                'total_num',
                'Cisco-IOS-XR-prm-server-oper', False, is_config=False),
            _MetaInfoClassMember('free-num', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                Free Resource Count
                ''',
                'free_num',
                'Cisco-IOS-XR-prm-server-oper', False, is_config=False),
            _MetaInfoClassMember('first-available-index', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                Next Free Index
                ''',
                'first_available_index',
                'Cisco-IOS-XR-prm-server-oper', False, is_config=False),
            _MetaInfoClassMember('start-index', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                Start Index
                ''',
                'start_index',
                'Cisco-IOS-XR-prm-server-oper', False, is_config=False),
            _MetaInfoClassMember('availability-status', ATTRIBUTE, 'bool', 'boolean',
                None, None,
                [], [],
                '''                Availability Status
                ''',
                'availability_status',
                'Cisco-IOS-XR-prm-server-oper', False, is_config=False),
            _MetaInfoClassMember('flags', ATTRIBUTE, 'int', 'uint8',
                None, None,
                [('0', '255')], [],
                '''                Resource Flags
                ''',
                'flags',
                'Cisco-IOS-XR-prm-server-oper', False, is_config=False),
            _MetaInfoClassMember('inconsistent', ATTRIBUTE, 'bool', 'boolean',
                None, None,
                [], [],
                '''                Inconsistice Flags
                ''',
                'inconsistent',
                'Cisco-IOS-XR-prm-server-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-prm-server-oper',
            'index',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-prm-server-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_prm_server_oper',
            is_config=False,
        ),
    },
    'Prm.Nodes.Node.Server.Resource.Indexes' : {
        'meta_info' : _MetaInfoClass('Prm.Nodes.Node.Server.Resource.Indexes', REFERENCE_CLASS,
            '''Data for software resource''',
            False, 
            [
            _MetaInfoClassMember('index', REFERENCE_LIST, 'Index', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_prm_server_oper', 'Prm.Nodes.Node.Server.Resource.Indexes.Index',
                [], [],
                '''                Data for software resource
                ''',
                'index',
                'Cisco-IOS-XR-prm-server-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-prm-server-oper',
            'indexes',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-prm-server-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_prm_server_oper',
            is_config=False,
        ),
    },
    'Prm.Nodes.Node.Server.Resource' : {
        'meta_info' : _MetaInfoClass('Prm.Nodes.Node.Server.Resource', REFERENCE_CLASS,
            '''Resource specific''',
            False, 
            [
            _MetaInfoClassMember('indexes', REFERENCE_CLASS, 'Indexes', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_prm_server_oper', 'Prm.Nodes.Node.Server.Resource.Indexes',
                [], [],
                '''                Data for software resource
                ''',
                'indexes',
                'Cisco-IOS-XR-prm-server-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-prm-server-oper',
            'resource',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-prm-server-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_prm_server_oper',
            is_config=False,
        ),
    },
    'Prm.Nodes.Node.Server' : {
        'meta_info' : _MetaInfoClass('Prm.Nodes.Node.Server', REFERENCE_CLASS,
            '''Server specific''',
            False, 
            [
            _MetaInfoClassMember('resource', REFERENCE_CLASS, 'Resource', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_prm_server_oper', 'Prm.Nodes.Node.Server.Resource',
                [], [],
                '''                Resource specific
                ''',
                'resource',
                'Cisco-IOS-XR-prm-server-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-prm-server-oper',
            'server',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-prm-server-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_prm_server_oper',
            is_config=False,
        ),
    },
    'Prm.Nodes.Node' : {
        'meta_info' : _MetaInfoClass('Prm.Nodes.Node', REFERENCE_LIST,
            '''Node Information''',
            False, 
            [
            _MetaInfoClassMember('node-name', ATTRIBUTE, 'str', 'xr:Node-id',
                None, None,
                [], [b'([a-zA-Z0-9_]*\\d+/){1,2}([a-zA-Z0-9_]*\\d+)'],
                '''                The node name
                ''',
                'node_name',
                'Cisco-IOS-XR-prm-server-oper', True, is_config=False),
            _MetaInfoClassMember('server', REFERENCE_CLASS, 'Server', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_prm_server_oper', 'Prm.Nodes.Node.Server',
                [], [],
                '''                Server specific
                ''',
                'server',
                'Cisco-IOS-XR-prm-server-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-prm-server-oper',
            'node',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-prm-server-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_prm_server_oper',
            is_config=False,
        ),
    },
    'Prm.Nodes' : {
        'meta_info' : _MetaInfoClass('Prm.Nodes', REFERENCE_CLASS,
            '''List of PRM Nodes''',
            False, 
            [
            _MetaInfoClassMember('node', REFERENCE_LIST, 'Node', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_prm_server_oper', 'Prm.Nodes.Node',
                [], [],
                '''                Node Information
                ''',
                'node',
                'Cisco-IOS-XR-prm-server-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-prm-server-oper',
            'nodes',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-prm-server-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_prm_server_oper',
            is_config=False,
        ),
    },
    'Prm' : {
        'meta_info' : _MetaInfoClass('Prm', REFERENCE_CLASS,
            '''prm''',
            False, 
            [
            _MetaInfoClassMember('nodes', REFERENCE_CLASS, 'Nodes', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_prm_server_oper', 'Prm.Nodes',
                [], [],
                '''                List of PRM Nodes
                ''',
                'nodes',
                'Cisco-IOS-XR-prm-server-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-prm-server-oper',
            'prm',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-prm-server-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_prm_server_oper',
            is_config=False,
        ),
    },
}
_meta_table['HardwareModule.Nodes.Node.Np.Cpu.Indexes.Index']['meta_info'].parent =_meta_table['HardwareModule.Nodes.Node.Np.Cpu.Indexes']['meta_info']
_meta_table['HardwareModule.Nodes.Node.Np.Cpu.Indexes']['meta_info'].parent =_meta_table['HardwareModule.Nodes.Node.Np.Cpu']['meta_info']
_meta_table['HardwareModule.Nodes.Node.Np.PlatformDrop.Indxes.Indx']['meta_info'].parent =_meta_table['HardwareModule.Nodes.Node.Np.PlatformDrop.Indxes']['meta_info']
_meta_table['HardwareModule.Nodes.Node.Np.PlatformDrop.Idxes.Idx']['meta_info'].parent =_meta_table['HardwareModule.Nodes.Node.Np.PlatformDrop.Idxes']['meta_info']
_meta_table['HardwareModule.Nodes.Node.Np.PlatformDrop.Indxes']['meta_info'].parent =_meta_table['HardwareModule.Nodes.Node.Np.PlatformDrop']['meta_info']
_meta_table['HardwareModule.Nodes.Node.Np.PlatformDrop.Idxes']['meta_info'].parent =_meta_table['HardwareModule.Nodes.Node.Np.PlatformDrop']['meta_info']
_meta_table['HardwareModule.Nodes.Node.Np.Cpu']['meta_info'].parent =_meta_table['HardwareModule.Nodes.Node.Np']['meta_info']
_meta_table['HardwareModule.Nodes.Node.Np.PlatformDrop']['meta_info'].parent =_meta_table['HardwareModule.Nodes.Node.Np']['meta_info']
_meta_table['HardwareModule.Nodes.Node.Np']['meta_info'].parent =_meta_table['HardwareModule.Nodes.Node']['meta_info']
_meta_table['HardwareModule.Nodes.Node']['meta_info'].parent =_meta_table['HardwareModule.Nodes']['meta_info']
_meta_table['HardwareModule.Nodes']['meta_info'].parent =_meta_table['HardwareModule']['meta_info']
_meta_table['Prm.Nodes.Node.Server.Resource.Indexes.Index']['meta_info'].parent =_meta_table['Prm.Nodes.Node.Server.Resource.Indexes']['meta_info']
_meta_table['Prm.Nodes.Node.Server.Resource.Indexes']['meta_info'].parent =_meta_table['Prm.Nodes.Node.Server.Resource']['meta_info']
_meta_table['Prm.Nodes.Node.Server.Resource']['meta_info'].parent =_meta_table['Prm.Nodes.Node.Server']['meta_info']
_meta_table['Prm.Nodes.Node.Server']['meta_info'].parent =_meta_table['Prm.Nodes.Node']['meta_info']
_meta_table['Prm.Nodes.Node']['meta_info'].parent =_meta_table['Prm.Nodes']['meta_info']
_meta_table['Prm.Nodes']['meta_info'].parent =_meta_table['Prm']['meta_info']
