
'''
This is auto-generated file,
which includes metadata for module Cisco_IOS_XR_traceroute_act
'''

from ydk._core._dm_meta_info import _MetaInfoClassMember, _MetaInfoClass, _MetaInfoEnum
from ydk._core._dm_meta_info import ATTRIBUTE, REFERENCE_LIST, REFERENCE_LEAFLIST, REFERENCE_BITS, REFERENCE_UNION
from ydk._core._dm_meta_info import REFERENCE_CLASS, REFERENCE_IDENTITY_CLASS, REFERENCE_ENUM_CLASS, ANYXML_CLASS
from ydk._core._importer import _yang_ns

_meta_table = {
    'Traceroute.Input.Destination' : {
        'meta_info' : _MetaInfoClass('Traceroute.Input.Destination', REFERENCE_CLASS,
            ''' ''',
            False, 
            [
            _MetaInfoClassMember('destination', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Destination address or hostname
                ''',
                'destination',
                'Cisco-IOS-XR-traceroute-act', False, is_mandatory=True),
            _MetaInfoClassMember('source', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Source address or interface
                ''',
                'source',
                'Cisco-IOS-XR-traceroute-act', False),
            _MetaInfoClassMember('timeout', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '36')], [],
                '''                Timeout in seconds
                ''',
                'timeout',
                'Cisco-IOS-XR-traceroute-act', False, default_value="3"),
            _MetaInfoClassMember('probe', ATTRIBUTE, 'int', 'uint16',
                None, None,
                [('1', '64')], [],
                '''                Probe count
                ''',
                'probe',
                'Cisco-IOS-XR-traceroute-act', False, default_value="3"),
            _MetaInfoClassMember('numeric', ATTRIBUTE, 'bool', 'boolean',
                None, None,
                [], [],
                '''                Numeric display only
                ''',
                'numeric',
                'Cisco-IOS-XR-traceroute-act', False),
            _MetaInfoClassMember('vrf-name', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                VRF name
                ''',
                'vrf_name',
                'Cisco-IOS-XR-traceroute-act', False),
            _MetaInfoClassMember('min-ttl', ATTRIBUTE, 'int', 'uint16',
                None, None,
                [('0', '255')], [],
                '''                minimum time to live
                ''',
                'min_ttl',
                'Cisco-IOS-XR-traceroute-act', False, default_value="1"),
            _MetaInfoClassMember('max-ttl', ATTRIBUTE, 'int', 'uint16',
                None, None,
                [('0', '255')], [],
                '''                maximum time to live
                ''',
                'max_ttl',
                'Cisco-IOS-XR-traceroute-act', False, default_value="30"),
            _MetaInfoClassMember('port', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '65535')], [],
                '''                Port numbe
                ''',
                'port',
                'Cisco-IOS-XR-traceroute-act', False),
            _MetaInfoClassMember('verbose', ATTRIBUTE, 'bool', 'boolean',
                None, None,
                [], [],
                '''                verbose output
                ''',
                'verbose',
                'Cisco-IOS-XR-traceroute-act', False),
            _MetaInfoClassMember('srv6-header', ATTRIBUTE, 'Empty', 'empty',
                None, None,
                [], [],
                '''                srv6 header
                ''',
                'srv6_header',
                'Cisco-IOS-XR-traceroute-act', False),
            _MetaInfoClassMember('priority', ATTRIBUTE, 'int', 'uint16',
                None, None,
                [('0', '15')], [],
                '''                Priority of hte packet
                ''',
                'priority',
                'Cisco-IOS-XR-traceroute-act', False),
            _MetaInfoClassMember('outgoing-interface', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Outgoing interface, needed in case of traceroute to link local address
                ''',
                'outgoing_interface',
                'Cisco-IOS-XR-traceroute-act', False),
            ],
            'Cisco-IOS-XR-traceroute-act',
            'destination',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-traceroute-act'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_traceroute_act',
            is_presence=True,
        ),
    },
    'Traceroute.Input.Ipv4' : {
        'meta_info' : _MetaInfoClass('Traceroute.Input.Ipv4', REFERENCE_CLASS,
            ''' ''',
            False, 
            [
            _MetaInfoClassMember('destination', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Destination address or hostname
                ''',
                'destination',
                'Cisco-IOS-XR-traceroute-act', False, is_mandatory=True),
            _MetaInfoClassMember('source', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Source address or interface
                ''',
                'source',
                'Cisco-IOS-XR-traceroute-act', False),
            _MetaInfoClassMember('timeout', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '36')], [],
                '''                Timeout in seconds
                ''',
                'timeout',
                'Cisco-IOS-XR-traceroute-act', False, default_value="3"),
            _MetaInfoClassMember('probe', ATTRIBUTE, 'int', 'uint16',
                None, None,
                [('1', '64')], [],
                '''                Probe count
                ''',
                'probe',
                'Cisco-IOS-XR-traceroute-act', False, default_value="3"),
            _MetaInfoClassMember('numeric', ATTRIBUTE, 'bool', 'boolean',
                None, None,
                [], [],
                '''                Numeric display only
                ''',
                'numeric',
                'Cisco-IOS-XR-traceroute-act', False),
            _MetaInfoClassMember('vrf-name', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                VRF name
                ''',
                'vrf_name',
                'Cisco-IOS-XR-traceroute-act', False),
            _MetaInfoClassMember('min-ttl', ATTRIBUTE, 'int', 'uint16',
                None, None,
                [('0', '255')], [],
                '''                minimum time to live
                ''',
                'min_ttl',
                'Cisco-IOS-XR-traceroute-act', False, default_value="1"),
            _MetaInfoClassMember('max-ttl', ATTRIBUTE, 'int', 'uint16',
                None, None,
                [('0', '255')], [],
                '''                maximum time to live
                ''',
                'max_ttl',
                'Cisco-IOS-XR-traceroute-act', False, default_value="30"),
            _MetaInfoClassMember('port', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '65535')], [],
                '''                Port numbe
                ''',
                'port',
                'Cisco-IOS-XR-traceroute-act', False),
            _MetaInfoClassMember('verbose', ATTRIBUTE, 'bool', 'boolean',
                None, None,
                [], [],
                '''                verbose output
                ''',
                'verbose',
                'Cisco-IOS-XR-traceroute-act', False),
            _MetaInfoClassMember('srv6-header', ATTRIBUTE, 'Empty', 'empty',
                None, None,
                [], [],
                '''                srv6 header
                ''',
                'srv6_header',
                'Cisco-IOS-XR-traceroute-act', False),
            ],
            'Cisco-IOS-XR-traceroute-act',
            'ipv4',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-traceroute-act'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_traceroute_act',
            is_presence=True,
        ),
    },
    'Traceroute.Input.Ipv6' : {
        'meta_info' : _MetaInfoClass('Traceroute.Input.Ipv6', REFERENCE_CLASS,
            ''' ''',
            False, 
            [
            _MetaInfoClassMember('destination', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Destination address or hostname
                ''',
                'destination',
                'Cisco-IOS-XR-traceroute-act', False, is_mandatory=True),
            _MetaInfoClassMember('source', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Source address or interface
                ''',
                'source',
                'Cisco-IOS-XR-traceroute-act', False),
            _MetaInfoClassMember('timeout', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '36')], [],
                '''                Timeout in seconds
                ''',
                'timeout',
                'Cisco-IOS-XR-traceroute-act', False, default_value="3"),
            _MetaInfoClassMember('probe', ATTRIBUTE, 'int', 'uint16',
                None, None,
                [('1', '64')], [],
                '''                Probe count
                ''',
                'probe',
                'Cisco-IOS-XR-traceroute-act', False, default_value="3"),
            _MetaInfoClassMember('numeric', ATTRIBUTE, 'bool', 'boolean',
                None, None,
                [], [],
                '''                Numeric display only
                ''',
                'numeric',
                'Cisco-IOS-XR-traceroute-act', False),
            _MetaInfoClassMember('vrf-name', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                VRF name
                ''',
                'vrf_name',
                'Cisco-IOS-XR-traceroute-act', False),
            _MetaInfoClassMember('min-ttl', ATTRIBUTE, 'int', 'uint16',
                None, None,
                [('0', '255')], [],
                '''                minimum time to live
                ''',
                'min_ttl',
                'Cisco-IOS-XR-traceroute-act', False, default_value="1"),
            _MetaInfoClassMember('max-ttl', ATTRIBUTE, 'int', 'uint16',
                None, None,
                [('0', '255')], [],
                '''                maximum time to live
                ''',
                'max_ttl',
                'Cisco-IOS-XR-traceroute-act', False, default_value="30"),
            _MetaInfoClassMember('port', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '65535')], [],
                '''                Port numbe
                ''',
                'port',
                'Cisco-IOS-XR-traceroute-act', False),
            _MetaInfoClassMember('verbose', ATTRIBUTE, 'bool', 'boolean',
                None, None,
                [], [],
                '''                verbose output
                ''',
                'verbose',
                'Cisco-IOS-XR-traceroute-act', False),
            _MetaInfoClassMember('srv6-header', ATTRIBUTE, 'Empty', 'empty',
                None, None,
                [], [],
                '''                srv6 header
                ''',
                'srv6_header',
                'Cisco-IOS-XR-traceroute-act', False),
            _MetaInfoClassMember('priority', ATTRIBUTE, 'int', 'uint16',
                None, None,
                [('0', '15')], [],
                '''                Priority of hte packet
                ''',
                'priority',
                'Cisco-IOS-XR-traceroute-act', False),
            _MetaInfoClassMember('outgoing-interface', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Outgoing interface, needed in case of traceroute to link local address
                ''',
                'outgoing_interface',
                'Cisco-IOS-XR-traceroute-act', False),
            ],
            'Cisco-IOS-XR-traceroute-act',
            'ipv6',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-traceroute-act'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_traceroute_act',
            is_presence=True,
        ),
    },
    'Traceroute.Input' : {
        'meta_info' : _MetaInfoClass('Traceroute.Input', REFERENCE_CLASS,
            ''' ''',
            False, 
            [
            _MetaInfoClassMember('destination', REFERENCE_CLASS, 'Destination', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_traceroute_act', 'Traceroute.Input.Destination',
                [], [],
                '''                ''',
                'destination',
                'Cisco-IOS-XR-traceroute-act', False, is_presence=True),
            _MetaInfoClassMember('ipv4', REFERENCE_CLASS, 'Ipv4', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_traceroute_act', 'Traceroute.Input.Ipv4',
                [], [],
                '''                ''',
                'ipv4',
                'Cisco-IOS-XR-traceroute-act', False, is_presence=True),
            _MetaInfoClassMember('ipv6', REFERENCE_CLASS, 'Ipv6', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_traceroute_act', 'Traceroute.Input.Ipv6',
                [], [],
                '''                ''',
                'ipv6',
                'Cisco-IOS-XR-traceroute-act', False, is_presence=True),
            ],
            'Cisco-IOS-XR-traceroute-act',
            'input',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-traceroute-act'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_traceroute_act',
        ),
    },
    'Traceroute.Output.TracerouteResponse.Ipv4.Hops.Hop.Probes.Probe.Srv6Header.Segments' : {
        'meta_info' : _MetaInfoClass('Traceroute.Output.TracerouteResponse.Ipv4.Hops.Hop.Probes.Probe.Srv6Header.Segments', REFERENCE_CLASS,
            ''' ''',
            False, 
            [
            _MetaInfoClassMember('segment', REFERENCE_LEAFLIST, 'str', 'string',
                None, None,
                [], [],
                '''                sid in sidlist
                ''',
                'segment',
                'Cisco-IOS-XR-traceroute-act', False),
            ],
            'Cisco-IOS-XR-traceroute-act',
            'segments',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-traceroute-act'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_traceroute_act',
        ),
    },
    'Traceroute.Output.TracerouteResponse.Ipv4.Hops.Hop.Probes.Probe.Srv6Header' : {
        'meta_info' : _MetaInfoClass('Traceroute.Output.TracerouteResponse.Ipv4.Hops.Hop.Probes.Probe.Srv6Header', REFERENCE_CLASS,
            ''' ''',
            False, 
            [
            _MetaInfoClassMember('destination-address', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                Destination address for srv6 header
                ''',
                'destination_address',
                'Cisco-IOS-XR-traceroute-act', False),
            _MetaInfoClassMember('segments-left', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                Number of segments left
                ''',
                'segments_left',
                'Cisco-IOS-XR-traceroute-act', False),
            _MetaInfoClassMember('segments', REFERENCE_CLASS, 'Segments', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_traceroute_act', 'Traceroute.Output.TracerouteResponse.Ipv4.Hops.Hop.Probes.Probe.Srv6Header.Segments',
                [], [],
                '''                ''',
                'segments',
                'Cisco-IOS-XR-traceroute-act', False),
            ],
            'Cisco-IOS-XR-traceroute-act',
            'srv6-header',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-traceroute-act'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_traceroute_act',
        ),
    },
    'Traceroute.Output.TracerouteResponse.Ipv4.Hops.Hop.Probes.Probe' : {
        'meta_info' : _MetaInfoClass('Traceroute.Output.TracerouteResponse.Ipv4.Hops.Hop.Probes.Probe', REFERENCE_LIST,
            ''' ''',
            False, 
            [
            _MetaInfoClassMember('probe-index', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                Index of the probe
                ''',
                'probe_index',
                'Cisco-IOS-XR-traceroute-act', True),
            _MetaInfoClassMember('result', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Response for each probe
                ''',
                'result',
                'Cisco-IOS-XR-traceroute-act', False),
            _MetaInfoClassMember('delta-time', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                Delta time in seconds
                ''',
                'delta_time',
                'Cisco-IOS-XR-traceroute-act', False),
            _MetaInfoClassMember('hop-address', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Address of the hop
                ''',
                'hop_address',
                'Cisco-IOS-XR-traceroute-act', False),
            _MetaInfoClassMember('hop-hostname', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Hostname of the hop
                ''',
                'hop_hostname',
                'Cisco-IOS-XR-traceroute-act', False),
            _MetaInfoClassMember('srv6-header', REFERENCE_CLASS, 'Srv6Header', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_traceroute_act', 'Traceroute.Output.TracerouteResponse.Ipv4.Hops.Hop.Probes.Probe.Srv6Header',
                [], [],
                '''                ''',
                'srv6_header',
                'Cisco-IOS-XR-traceroute-act', False),
            ],
            'Cisco-IOS-XR-traceroute-act',
            'probe',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-traceroute-act'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_traceroute_act',
        ),
    },
    'Traceroute.Output.TracerouteResponse.Ipv4.Hops.Hop.Probes' : {
        'meta_info' : _MetaInfoClass('Traceroute.Output.TracerouteResponse.Ipv4.Hops.Hop.Probes', REFERENCE_CLASS,
            ''' ''',
            False, 
            [
            _MetaInfoClassMember('probe', REFERENCE_LIST, 'Probe', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_traceroute_act', 'Traceroute.Output.TracerouteResponse.Ipv4.Hops.Hop.Probes.Probe',
                [], [],
                '''                ''',
                'probe',
                'Cisco-IOS-XR-traceroute-act', False),
            ],
            'Cisco-IOS-XR-traceroute-act',
            'probes',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-traceroute-act'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_traceroute_act',
        ),
    },
    'Traceroute.Output.TracerouteResponse.Ipv4.Hops.Hop' : {
        'meta_info' : _MetaInfoClass('Traceroute.Output.TracerouteResponse.Ipv4.Hops.Hop', REFERENCE_LIST,
            ''' ''',
            False, 
            [
            _MetaInfoClassMember('hop-index', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                Index of the hop
                ''',
                'hop_index',
                'Cisco-IOS-XR-traceroute-act', True),
            _MetaInfoClassMember('hop-address', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Address of the hop
                ''',
                'hop_address',
                'Cisco-IOS-XR-traceroute-act', False),
            _MetaInfoClassMember('hop-hostname', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Hostname of the hop
                ''',
                'hop_hostname',
                'Cisco-IOS-XR-traceroute-act', False),
            _MetaInfoClassMember('probes', REFERENCE_CLASS, 'Probes', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_traceroute_act', 'Traceroute.Output.TracerouteResponse.Ipv4.Hops.Hop.Probes',
                [], [],
                '''                ''',
                'probes',
                'Cisco-IOS-XR-traceroute-act', False),
            ],
            'Cisco-IOS-XR-traceroute-act',
            'hop',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-traceroute-act'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_traceroute_act',
        ),
    },
    'Traceroute.Output.TracerouteResponse.Ipv4.Hops' : {
        'meta_info' : _MetaInfoClass('Traceroute.Output.TracerouteResponse.Ipv4.Hops', REFERENCE_CLASS,
            ''' ''',
            False, 
            [
            _MetaInfoClassMember('hop', REFERENCE_LIST, 'Hop', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_traceroute_act', 'Traceroute.Output.TracerouteResponse.Ipv4.Hops.Hop',
                [], [],
                '''                ''',
                'hop',
                'Cisco-IOS-XR-traceroute-act', False),
            ],
            'Cisco-IOS-XR-traceroute-act',
            'hops',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-traceroute-act'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_traceroute_act',
        ),
    },
    'Traceroute.Output.TracerouteResponse.Ipv4' : {
        'meta_info' : _MetaInfoClass('Traceroute.Output.TracerouteResponse.Ipv4', REFERENCE_CLASS,
            ''' ''',
            False, 
            [
            _MetaInfoClassMember('destination', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Destination address or hostname
                ''',
                'destination',
                'Cisco-IOS-XR-traceroute-act', False),
            _MetaInfoClassMember('hops', REFERENCE_CLASS, 'Hops', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_traceroute_act', 'Traceroute.Output.TracerouteResponse.Ipv4.Hops',
                [], [],
                '''                ''',
                'hops',
                'Cisco-IOS-XR-traceroute-act', False),
            _MetaInfoClassMember('verbose-output', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Verbose output
                ''',
                'verbose_output',
                'Cisco-IOS-XR-traceroute-act', False),
            ],
            'Cisco-IOS-XR-traceroute-act',
            'ipv4',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-traceroute-act'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_traceroute_act',
            is_presence=True,
        ),
    },
    'Traceroute.Output.TracerouteResponse.Ipv6.Hops.Hop.Probes.Probe.Srv6Header.Segments' : {
        'meta_info' : _MetaInfoClass('Traceroute.Output.TracerouteResponse.Ipv6.Hops.Hop.Probes.Probe.Srv6Header.Segments', REFERENCE_CLASS,
            ''' ''',
            False, 
            [
            _MetaInfoClassMember('segment', REFERENCE_LEAFLIST, 'str', 'string',
                None, None,
                [], [],
                '''                sid in sidlist
                ''',
                'segment',
                'Cisco-IOS-XR-traceroute-act', False),
            ],
            'Cisco-IOS-XR-traceroute-act',
            'segments',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-traceroute-act'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_traceroute_act',
        ),
    },
    'Traceroute.Output.TracerouteResponse.Ipv6.Hops.Hop.Probes.Probe.Srv6Header' : {
        'meta_info' : _MetaInfoClass('Traceroute.Output.TracerouteResponse.Ipv6.Hops.Hop.Probes.Probe.Srv6Header', REFERENCE_CLASS,
            ''' ''',
            False, 
            [
            _MetaInfoClassMember('destination-address', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                Destination address for srv6 header
                ''',
                'destination_address',
                'Cisco-IOS-XR-traceroute-act', False),
            _MetaInfoClassMember('segments-left', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                Number of segments left
                ''',
                'segments_left',
                'Cisco-IOS-XR-traceroute-act', False),
            _MetaInfoClassMember('segments', REFERENCE_CLASS, 'Segments', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_traceroute_act', 'Traceroute.Output.TracerouteResponse.Ipv6.Hops.Hop.Probes.Probe.Srv6Header.Segments',
                [], [],
                '''                ''',
                'segments',
                'Cisco-IOS-XR-traceroute-act', False),
            ],
            'Cisco-IOS-XR-traceroute-act',
            'srv6-header',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-traceroute-act'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_traceroute_act',
        ),
    },
    'Traceroute.Output.TracerouteResponse.Ipv6.Hops.Hop.Probes.Probe' : {
        'meta_info' : _MetaInfoClass('Traceroute.Output.TracerouteResponse.Ipv6.Hops.Hop.Probes.Probe', REFERENCE_LIST,
            ''' ''',
            False, 
            [
            _MetaInfoClassMember('probe-index', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                Index of the probe
                ''',
                'probe_index',
                'Cisco-IOS-XR-traceroute-act', True),
            _MetaInfoClassMember('result', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Response for each probe
                ''',
                'result',
                'Cisco-IOS-XR-traceroute-act', False),
            _MetaInfoClassMember('delta-time', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                Delta time in seconds
                ''',
                'delta_time',
                'Cisco-IOS-XR-traceroute-act', False),
            _MetaInfoClassMember('hop-address', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Address of the hop
                ''',
                'hop_address',
                'Cisco-IOS-XR-traceroute-act', False),
            _MetaInfoClassMember('hop-hostname', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Hostname of the hop
                ''',
                'hop_hostname',
                'Cisco-IOS-XR-traceroute-act', False),
            _MetaInfoClassMember('srv6-header', REFERENCE_CLASS, 'Srv6Header', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_traceroute_act', 'Traceroute.Output.TracerouteResponse.Ipv6.Hops.Hop.Probes.Probe.Srv6Header',
                [], [],
                '''                ''',
                'srv6_header',
                'Cisco-IOS-XR-traceroute-act', False),
            ],
            'Cisco-IOS-XR-traceroute-act',
            'probe',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-traceroute-act'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_traceroute_act',
        ),
    },
    'Traceroute.Output.TracerouteResponse.Ipv6.Hops.Hop.Probes' : {
        'meta_info' : _MetaInfoClass('Traceroute.Output.TracerouteResponse.Ipv6.Hops.Hop.Probes', REFERENCE_CLASS,
            ''' ''',
            False, 
            [
            _MetaInfoClassMember('probe', REFERENCE_LIST, 'Probe', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_traceroute_act', 'Traceroute.Output.TracerouteResponse.Ipv6.Hops.Hop.Probes.Probe',
                [], [],
                '''                ''',
                'probe',
                'Cisco-IOS-XR-traceroute-act', False),
            ],
            'Cisco-IOS-XR-traceroute-act',
            'probes',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-traceroute-act'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_traceroute_act',
        ),
    },
    'Traceroute.Output.TracerouteResponse.Ipv6.Hops.Hop' : {
        'meta_info' : _MetaInfoClass('Traceroute.Output.TracerouteResponse.Ipv6.Hops.Hop', REFERENCE_LIST,
            ''' ''',
            False, 
            [
            _MetaInfoClassMember('hop-index', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                Index of the hop
                ''',
                'hop_index',
                'Cisco-IOS-XR-traceroute-act', True),
            _MetaInfoClassMember('hop-address', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Address of the hop
                ''',
                'hop_address',
                'Cisco-IOS-XR-traceroute-act', False),
            _MetaInfoClassMember('hop-hostname', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Hostname of the hop
                ''',
                'hop_hostname',
                'Cisco-IOS-XR-traceroute-act', False),
            _MetaInfoClassMember('probes', REFERENCE_CLASS, 'Probes', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_traceroute_act', 'Traceroute.Output.TracerouteResponse.Ipv6.Hops.Hop.Probes',
                [], [],
                '''                ''',
                'probes',
                'Cisco-IOS-XR-traceroute-act', False),
            ],
            'Cisco-IOS-XR-traceroute-act',
            'hop',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-traceroute-act'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_traceroute_act',
        ),
    },
    'Traceroute.Output.TracerouteResponse.Ipv6.Hops' : {
        'meta_info' : _MetaInfoClass('Traceroute.Output.TracerouteResponse.Ipv6.Hops', REFERENCE_CLASS,
            ''' ''',
            False, 
            [
            _MetaInfoClassMember('hop', REFERENCE_LIST, 'Hop', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_traceroute_act', 'Traceroute.Output.TracerouteResponse.Ipv6.Hops.Hop',
                [], [],
                '''                ''',
                'hop',
                'Cisco-IOS-XR-traceroute-act', False),
            ],
            'Cisco-IOS-XR-traceroute-act',
            'hops',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-traceroute-act'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_traceroute_act',
        ),
    },
    'Traceroute.Output.TracerouteResponse.Ipv6' : {
        'meta_info' : _MetaInfoClass('Traceroute.Output.TracerouteResponse.Ipv6', REFERENCE_CLASS,
            ''' ''',
            False, 
            [
            _MetaInfoClassMember('destination', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Destination address or hostname
                ''',
                'destination',
                'Cisco-IOS-XR-traceroute-act', False),
            _MetaInfoClassMember('hops', REFERENCE_CLASS, 'Hops', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_traceroute_act', 'Traceroute.Output.TracerouteResponse.Ipv6.Hops',
                [], [],
                '''                ''',
                'hops',
                'Cisco-IOS-XR-traceroute-act', False),
            _MetaInfoClassMember('verbose-output', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Verbose output
                ''',
                'verbose_output',
                'Cisco-IOS-XR-traceroute-act', False),
            ],
            'Cisco-IOS-XR-traceroute-act',
            'ipv6',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-traceroute-act'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_traceroute_act',
            is_presence=True,
        ),
    },
    'Traceroute.Output.TracerouteResponse' : {
        'meta_info' : _MetaInfoClass('Traceroute.Output.TracerouteResponse', REFERENCE_CLASS,
            ''' ''',
            False, 
            [
            _MetaInfoClassMember('ipv4', REFERENCE_CLASS, 'Ipv4', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_traceroute_act', 'Traceroute.Output.TracerouteResponse.Ipv4',
                [], [],
                '''                ''',
                'ipv4',
                'Cisco-IOS-XR-traceroute-act', False, is_presence=True),
            _MetaInfoClassMember('ipv6', REFERENCE_CLASS, 'Ipv6', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_traceroute_act', 'Traceroute.Output.TracerouteResponse.Ipv6',
                [], [],
                '''                ''',
                'ipv6',
                'Cisco-IOS-XR-traceroute-act', False, is_presence=True),
            ],
            'Cisco-IOS-XR-traceroute-act',
            'traceroute-response',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-traceroute-act'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_traceroute_act',
        ),
    },
    'Traceroute.Output' : {
        'meta_info' : _MetaInfoClass('Traceroute.Output', REFERENCE_CLASS,
            ''' ''',
            False, 
            [
            _MetaInfoClassMember('traceroute-response', REFERENCE_CLASS, 'TracerouteResponse', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_traceroute_act', 'Traceroute.Output.TracerouteResponse',
                [], [],
                '''                ''',
                'traceroute_response',
                'Cisco-IOS-XR-traceroute-act', False),
            ],
            'Cisco-IOS-XR-traceroute-act',
            'output',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-traceroute-act'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_traceroute_act',
        ),
    },
    'Traceroute' : {
        'meta_info' : _MetaInfoClass('Traceroute', REFERENCE_CLASS,
            '''Trace route to destination''',
            False, 
            [
            _MetaInfoClassMember('input', REFERENCE_CLASS, 'Input', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_traceroute_act', 'Traceroute.Input',
                [], [],
                '''                ''',
                'input',
                'Cisco-IOS-XR-traceroute-act', False),
            _MetaInfoClassMember('output', REFERENCE_CLASS, 'Output', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_traceroute_act', 'Traceroute.Output',
                [], [],
                '''                ''',
                'output',
                'Cisco-IOS-XR-traceroute-act', False),
            ],
            'Cisco-IOS-XR-traceroute-act',
            'traceroute',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-traceroute-act'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_traceroute_act',
        ),
    },
}
_meta_table['Traceroute.Input.Destination']['meta_info'].parent =_meta_table['Traceroute.Input']['meta_info']
_meta_table['Traceroute.Input.Ipv4']['meta_info'].parent =_meta_table['Traceroute.Input']['meta_info']
_meta_table['Traceroute.Input.Ipv6']['meta_info'].parent =_meta_table['Traceroute.Input']['meta_info']
_meta_table['Traceroute.Output.TracerouteResponse.Ipv4.Hops.Hop.Probes.Probe.Srv6Header.Segments']['meta_info'].parent =_meta_table['Traceroute.Output.TracerouteResponse.Ipv4.Hops.Hop.Probes.Probe.Srv6Header']['meta_info']
_meta_table['Traceroute.Output.TracerouteResponse.Ipv4.Hops.Hop.Probes.Probe.Srv6Header']['meta_info'].parent =_meta_table['Traceroute.Output.TracerouteResponse.Ipv4.Hops.Hop.Probes.Probe']['meta_info']
_meta_table['Traceroute.Output.TracerouteResponse.Ipv4.Hops.Hop.Probes.Probe']['meta_info'].parent =_meta_table['Traceroute.Output.TracerouteResponse.Ipv4.Hops.Hop.Probes']['meta_info']
_meta_table['Traceroute.Output.TracerouteResponse.Ipv4.Hops.Hop.Probes']['meta_info'].parent =_meta_table['Traceroute.Output.TracerouteResponse.Ipv4.Hops.Hop']['meta_info']
_meta_table['Traceroute.Output.TracerouteResponse.Ipv4.Hops.Hop']['meta_info'].parent =_meta_table['Traceroute.Output.TracerouteResponse.Ipv4.Hops']['meta_info']
_meta_table['Traceroute.Output.TracerouteResponse.Ipv4.Hops']['meta_info'].parent =_meta_table['Traceroute.Output.TracerouteResponse.Ipv4']['meta_info']
_meta_table['Traceroute.Output.TracerouteResponse.Ipv6.Hops.Hop.Probes.Probe.Srv6Header.Segments']['meta_info'].parent =_meta_table['Traceroute.Output.TracerouteResponse.Ipv6.Hops.Hop.Probes.Probe.Srv6Header']['meta_info']
_meta_table['Traceroute.Output.TracerouteResponse.Ipv6.Hops.Hop.Probes.Probe.Srv6Header']['meta_info'].parent =_meta_table['Traceroute.Output.TracerouteResponse.Ipv6.Hops.Hop.Probes.Probe']['meta_info']
_meta_table['Traceroute.Output.TracerouteResponse.Ipv6.Hops.Hop.Probes.Probe']['meta_info'].parent =_meta_table['Traceroute.Output.TracerouteResponse.Ipv6.Hops.Hop.Probes']['meta_info']
_meta_table['Traceroute.Output.TracerouteResponse.Ipv6.Hops.Hop.Probes']['meta_info'].parent =_meta_table['Traceroute.Output.TracerouteResponse.Ipv6.Hops.Hop']['meta_info']
_meta_table['Traceroute.Output.TracerouteResponse.Ipv6.Hops.Hop']['meta_info'].parent =_meta_table['Traceroute.Output.TracerouteResponse.Ipv6.Hops']['meta_info']
_meta_table['Traceroute.Output.TracerouteResponse.Ipv6.Hops']['meta_info'].parent =_meta_table['Traceroute.Output.TracerouteResponse.Ipv6']['meta_info']
_meta_table['Traceroute.Output.TracerouteResponse.Ipv4']['meta_info'].parent =_meta_table['Traceroute.Output.TracerouteResponse']['meta_info']
_meta_table['Traceroute.Output.TracerouteResponse.Ipv6']['meta_info'].parent =_meta_table['Traceroute.Output.TracerouteResponse']['meta_info']
_meta_table['Traceroute.Output.TracerouteResponse']['meta_info'].parent =_meta_table['Traceroute.Output']['meta_info']
_meta_table['Traceroute.Input']['meta_info'].parent =_meta_table['Traceroute']['meta_info']
_meta_table['Traceroute.Output']['meta_info'].parent =_meta_table['Traceroute']['meta_info']
