
'''
This is auto-generated file,
which includes metadata for module Cisco_IOS_XR_lib_keychain_cfg
'''

from ydk._core._dm_meta_info import _MetaInfoClassMember, _MetaInfoClass, _MetaInfoEnum
from ydk._core._dm_meta_info import ATTRIBUTE, REFERENCE_LIST, REFERENCE_LEAFLIST, REFERENCE_BITS, REFERENCE_UNION
from ydk._core._dm_meta_info import REFERENCE_CLASS, REFERENCE_IDENTITY_CLASS, REFERENCE_ENUM_CLASS, ANYXML_CLASS
from ydk._core._importer import _yang_ns

_meta_table = {
    'MacsecEncryption' : _MetaInfoEnum('MacsecEncryption',
        'ydk.models.cisco_ios_xr.Cisco_IOS_XR_lib_keychain_cfg', 'MacsecEncryption',
        '''Macsec encryption''',
        {
            'type7':'type7',
            'type6':'type6',
        }, 'Cisco-IOS-XR-lib-keychain-cfg', _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-lib-keychain-cfg']),
    'CryptoAlg' : _MetaInfoEnum('CryptoAlg',
        'ydk.models.cisco_ios_xr.Cisco_IOS_XR_lib_keychain_cfg', 'CryptoAlg',
        '''Crypto alg''',
        {
            'alg-aes-128-cmac-96':'alg_aes_128_cmac_96',
            'alg-hmac-sha1-12':'alg_hmac_sha1_12',
            'alg-md5-16':'alg_md5_16',
            'alg-sha1-20':'alg_sha1_20',
            'alg-hmac-md5-16':'alg_hmac_md5_16',
            'alg-hmac-sha1-20':'alg_hmac_sha1_20',
            'alg-hmac-sha1-96':'alg_hmac_sha1_96',
            'alg-hmac-sha-256':'alg_hmac_sha_256',
        }, 'Cisco-IOS-XR-lib-keychain-cfg', _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-lib-keychain-cfg']),
    'MacsecCryptoAlg' : _MetaInfoEnum('MacsecCryptoAlg',
        'ydk.models.cisco_ios_xr.Cisco_IOS_XR_lib_keychain_cfg', 'MacsecCryptoAlg',
        '''Macsec crypto alg''',
        {
            'aes-128-cmac':'aes_128_cmac',
            'aes-256-cmac':'aes_256_cmac',
        }, 'Cisco-IOS-XR-lib-keychain-cfg', _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-lib-keychain-cfg']),
    'KeyChainMonth' : _MetaInfoEnum('KeyChainMonth',
        'ydk.models.cisco_ios_xr.Cisco_IOS_XR_lib_keychain_cfg', 'KeyChainMonth',
        '''Key chain month''',
        {
            'jan':'jan',
            'feb':'feb',
            'mar':'mar',
            'apr':'apr',
            'may':'may',
            'jun':'jun',
            'jul':'jul',
            'aug':'aug',
            'sep':'sep',
            'oct':'oct',
            'nov':'nov',
            'dec':'dec',
        }, 'Cisco-IOS-XR-lib-keychain-cfg', _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-lib-keychain-cfg']),
    'Keychains.Keychain.AcceptTolerance' : {
        'meta_info' : _MetaInfoClass('Keychains.Keychain.AcceptTolerance', REFERENCE_CLASS,
            '''Accept Tolerance in seconds or infinite''',
            False, 
            [
            _MetaInfoClassMember('value', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('1', '8640000')], [],
                '''                Value in seconds
                ''',
                'value',
                'Cisco-IOS-XR-lib-keychain-cfg', False, has_must=True),
            _MetaInfoClassMember('infinite', ATTRIBUTE, 'bool', 'boolean',
                None, None,
                [], [],
                '''                Infinite tolerance
                ''',
                'infinite',
                'Cisco-IOS-XR-lib-keychain-cfg', False, has_must=True),
            ],
            'Cisco-IOS-XR-lib-keychain-cfg',
            'accept-tolerance',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-lib-keychain-cfg'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_lib_keychain_cfg',
        ),
    },
    'Keychains.Keychain.MacsecKeychain.MacsecKeys.MacsecKey.MacsecLifetime' : {
        'meta_info' : _MetaInfoClass('Keychains.Keychain.MacsecKeychain.MacsecKeys.MacsecKey.MacsecLifetime', REFERENCE_CLASS,
            '''Configure a key Lifetime''',
            False, 
            [
            _MetaInfoClassMember('start-hour', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '23')], [],
                '''                Start Hour
                ''',
                'start_hour',
                'Cisco-IOS-XR-lib-keychain-cfg', False, is_mandatory=True),
            _MetaInfoClassMember('start-minutes', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '59')], [],
                '''                Start Minutes
                ''',
                'start_minutes',
                'Cisco-IOS-XR-lib-keychain-cfg', False, is_mandatory=True),
            _MetaInfoClassMember('start-seconds', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '59')], [],
                '''                Start Seconds
                ''',
                'start_seconds',
                'Cisco-IOS-XR-lib-keychain-cfg', False, is_mandatory=True),
            _MetaInfoClassMember('start-date', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('1', '31')], [],
                '''                Start Date
                ''',
                'start_date',
                'Cisco-IOS-XR-lib-keychain-cfg', False, is_mandatory=True),
            _MetaInfoClassMember('start-month', REFERENCE_ENUM_CLASS, 'KeyChainMonth', 'Key-chain-month',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_lib_keychain_cfg', 'KeyChainMonth',
                [], [],
                '''                Start Month
                ''',
                'start_month',
                'Cisco-IOS-XR-lib-keychain-cfg', False, is_mandatory=True),
            _MetaInfoClassMember('start-year', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('1993', '2035')], [],
                '''                Start Year
                ''',
                'start_year',
                'Cisco-IOS-XR-lib-keychain-cfg', False, is_mandatory=True),
            _MetaInfoClassMember('life-time', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('1', '2147483647')], [],
                '''                Lifetime duration in seconds
                ''',
                'life_time',
                'Cisco-IOS-XR-lib-keychain-cfg', False),
            _MetaInfoClassMember('infinite-flag', ATTRIBUTE, 'bool', 'boolean',
                None, None,
                [], [],
                '''                Infinite Lifetime flag
                ''',
                'infinite_flag',
                'Cisco-IOS-XR-lib-keychain-cfg', False),
            _MetaInfoClassMember('end-hour', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '23')], [],
                '''                End Hour
                ''',
                'end_hour',
                'Cisco-IOS-XR-lib-keychain-cfg', False),
            _MetaInfoClassMember('end-minutes', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '59')], [],
                '''                End Minutes
                ''',
                'end_minutes',
                'Cisco-IOS-XR-lib-keychain-cfg', False),
            _MetaInfoClassMember('end-seconds', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '59')], [],
                '''                End Seconds
                ''',
                'end_seconds',
                'Cisco-IOS-XR-lib-keychain-cfg', False),
            _MetaInfoClassMember('end-date', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('1', '31')], [],
                '''                End Date
                ''',
                'end_date',
                'Cisco-IOS-XR-lib-keychain-cfg', False),
            _MetaInfoClassMember('end-month', REFERENCE_ENUM_CLASS, 'KeyChainMonth', 'Key-chain-month',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_lib_keychain_cfg', 'KeyChainMonth',
                [], [],
                '''                End Month
                ''',
                'end_month',
                'Cisco-IOS-XR-lib-keychain-cfg', False),
            _MetaInfoClassMember('end-year', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('1993', '2035')], [],
                '''                End Year
                ''',
                'end_year',
                'Cisco-IOS-XR-lib-keychain-cfg', False),
            ],
            'Cisco-IOS-XR-lib-keychain-cfg',
            'macsec-lifetime',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-lib-keychain-cfg'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_lib_keychain_cfg',
            is_presence=True,
        ),
    },
    'Keychains.Keychain.MacsecKeychain.MacsecKeys.MacsecKey.MacsecKeyString' : {
        'meta_info' : _MetaInfoClass('Keychains.Keychain.MacsecKeychain.MacsecKeys.MacsecKey.MacsecKeyString', REFERENCE_CLASS,
            '''Configure a clear text/encrypted Key string
along with cryptographic algorithm''',
            False, 
            [
            _MetaInfoClassMember('string', ATTRIBUTE, 'str', 'xr:Proprietary-password',
                None, None,
                [], [b'(!.+)|([^!].+)'],
                '''                Key String
                ''',
                'string',
                'Cisco-IOS-XR-lib-keychain-cfg', False, is_mandatory=True),
            _MetaInfoClassMember('cryptographic-algorithm', REFERENCE_ENUM_CLASS, 'MacsecCryptoAlg', 'Macsec-crypto-alg',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_lib_keychain_cfg', 'MacsecCryptoAlg',
                [], [],
                '''                Cryptographic Algorithm
                ''',
                'cryptographic_algorithm',
                'Cisco-IOS-XR-lib-keychain-cfg', False, is_mandatory=True),
            _MetaInfoClassMember('encryption-type', REFERENCE_ENUM_CLASS, 'MacsecEncryption', 'Macsec-encryption',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_lib_keychain_cfg', 'MacsecEncryption',
                [], [],
                '''                encryption type used to store key
                ''',
                'encryption_type',
                'Cisco-IOS-XR-lib-keychain-cfg', False, default_value='Cisco_IOS_XR_lib_keychain_cfg.MacsecEncryption.type7'),
            ],
            'Cisco-IOS-XR-lib-keychain-cfg',
            'macsec-key-string',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-lib-keychain-cfg'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_lib_keychain_cfg',
            is_presence=True,
        ),
    },
    'Keychains.Keychain.MacsecKeychain.MacsecKeys.MacsecKey' : {
        'meta_info' : _MetaInfoClass('Keychains.Keychain.MacsecKeychain.MacsecKeys.MacsecKey', REFERENCE_LIST,
            '''Key Identifier''',
            False, 
            [
            _MetaInfoClassMember('key-id', ATTRIBUTE, 'str', 'xr:Cisco-ios-xr-string',
                None, None,
                [(2, 64)], [],
                '''                Enter CKN as non-zero hex string of even
                length, length range: <02-64>, i.e 32 bytes
                of MACsec CKN
                ''',
                'key_id',
                'Cisco-IOS-XR-lib-keychain-cfg', True),
            _MetaInfoClassMember('macsec-lifetime', REFERENCE_CLASS, 'MacsecLifetime', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_lib_keychain_cfg', 'Keychains.Keychain.MacsecKeychain.MacsecKeys.MacsecKey.MacsecLifetime',
                [], [],
                '''                Configure a key Lifetime
                ''',
                'macsec_lifetime',
                'Cisco-IOS-XR-lib-keychain-cfg', False, is_presence=True),
            _MetaInfoClassMember('macsec-key-string', REFERENCE_CLASS, 'MacsecKeyString', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_lib_keychain_cfg', 'Keychains.Keychain.MacsecKeychain.MacsecKeys.MacsecKey.MacsecKeyString',
                [], [],
                '''                Configure a clear text/encrypted Key string
                along with cryptographic algorithm
                ''',
                'macsec_key_string',
                'Cisco-IOS-XR-lib-keychain-cfg', False, is_presence=True),
            ],
            'Cisco-IOS-XR-lib-keychain-cfg',
            'macsec-key',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-lib-keychain-cfg'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_lib_keychain_cfg',
        ),
    },
    'Keychains.Keychain.MacsecKeychain.MacsecKeys' : {
        'meta_info' : _MetaInfoClass('Keychains.Keychain.MacsecKeychain.MacsecKeys', REFERENCE_CLASS,
            '''Configure a Key''',
            False, 
            [
            _MetaInfoClassMember('macsec-key', REFERENCE_LIST, 'MacsecKey', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_lib_keychain_cfg', 'Keychains.Keychain.MacsecKeychain.MacsecKeys.MacsecKey',
                [], [],
                '''                Key Identifier
                ''',
                'macsec_key',
                'Cisco-IOS-XR-lib-keychain-cfg', False),
            ],
            'Cisco-IOS-XR-lib-keychain-cfg',
            'macsec-keys',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-lib-keychain-cfg'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_lib_keychain_cfg',
        ),
    },
    'Keychains.Keychain.MacsecKeychain' : {
        'meta_info' : _MetaInfoClass('Keychains.Keychain.MacsecKeychain', REFERENCE_CLASS,
            '''Name of the key chain for MACSec''',
            False, 
            [
            _MetaInfoClassMember('macsec-keys', REFERENCE_CLASS, 'MacsecKeys', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_lib_keychain_cfg', 'Keychains.Keychain.MacsecKeychain.MacsecKeys',
                [], [],
                '''                Configure a Key
                ''',
                'macsec_keys',
                'Cisco-IOS-XR-lib-keychain-cfg', False),
            ],
            'Cisco-IOS-XR-lib-keychain-cfg',
            'macsec-keychain',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-lib-keychain-cfg'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_lib_keychain_cfg',
        ),
    },
    'Keychains.Keychain.Keys.Key.AcceptLifetime' : {
        'meta_info' : _MetaInfoClass('Keychains.Keychain.Keys.Key.AcceptLifetime', REFERENCE_CLASS,
            '''Configure a key Acceptance Lifetime''',
            False, 
            [
            _MetaInfoClassMember('start-hour', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '23')], [],
                '''                Start Hour
                ''',
                'start_hour',
                'Cisco-IOS-XR-lib-keychain-cfg', False, is_mandatory=True),
            _MetaInfoClassMember('start-minutes', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '59')], [],
                '''                Start Minutes
                ''',
                'start_minutes',
                'Cisco-IOS-XR-lib-keychain-cfg', False, is_mandatory=True),
            _MetaInfoClassMember('start-seconds', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '59')], [],
                '''                Start Seconds
                ''',
                'start_seconds',
                'Cisco-IOS-XR-lib-keychain-cfg', False, is_mandatory=True),
            _MetaInfoClassMember('start-date', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('1', '31')], [],
                '''                Start Date
                ''',
                'start_date',
                'Cisco-IOS-XR-lib-keychain-cfg', False, is_mandatory=True),
            _MetaInfoClassMember('start-month', REFERENCE_ENUM_CLASS, 'KeyChainMonth', 'Key-chain-month',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_lib_keychain_cfg', 'KeyChainMonth',
                [], [],
                '''                Start Month
                ''',
                'start_month',
                'Cisco-IOS-XR-lib-keychain-cfg', False, is_mandatory=True),
            _MetaInfoClassMember('start-year', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('1993', '2035')], [],
                '''                Start Year
                ''',
                'start_year',
                'Cisco-IOS-XR-lib-keychain-cfg', False, is_mandatory=True),
            _MetaInfoClassMember('life-time', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('1', '2147483647')], [],
                '''                Lifetime duration in seconds
                ''',
                'life_time',
                'Cisco-IOS-XR-lib-keychain-cfg', False),
            _MetaInfoClassMember('infinite-flag', ATTRIBUTE, 'bool', 'boolean',
                None, None,
                [], [],
                '''                Infinite Lifetime flag
                ''',
                'infinite_flag',
                'Cisco-IOS-XR-lib-keychain-cfg', False),
            _MetaInfoClassMember('end-hour', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '23')], [],
                '''                End Hour
                ''',
                'end_hour',
                'Cisco-IOS-XR-lib-keychain-cfg', False),
            _MetaInfoClassMember('end-minutes', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '59')], [],
                '''                End Minutes
                ''',
                'end_minutes',
                'Cisco-IOS-XR-lib-keychain-cfg', False),
            _MetaInfoClassMember('end-seconds', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '59')], [],
                '''                End Seconds
                ''',
                'end_seconds',
                'Cisco-IOS-XR-lib-keychain-cfg', False),
            _MetaInfoClassMember('end-date', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('1', '31')], [],
                '''                End Date
                ''',
                'end_date',
                'Cisco-IOS-XR-lib-keychain-cfg', False),
            _MetaInfoClassMember('end-month', REFERENCE_ENUM_CLASS, 'KeyChainMonth', 'Key-chain-month',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_lib_keychain_cfg', 'KeyChainMonth',
                [], [],
                '''                End Month
                ''',
                'end_month',
                'Cisco-IOS-XR-lib-keychain-cfg', False),
            _MetaInfoClassMember('end-year', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('1993', '2035')], [],
                '''                End Year
                ''',
                'end_year',
                'Cisco-IOS-XR-lib-keychain-cfg', False),
            ],
            'Cisco-IOS-XR-lib-keychain-cfg',
            'accept-lifetime',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-lib-keychain-cfg'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_lib_keychain_cfg',
            is_presence=True,
        ),
    },
    'Keychains.Keychain.Keys.Key.SendLifetime' : {
        'meta_info' : _MetaInfoClass('Keychains.Keychain.Keys.Key.SendLifetime', REFERENCE_CLASS,
            '''Configure a Send Lifetime''',
            False, 
            [
            _MetaInfoClassMember('start-hour', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '23')], [],
                '''                Start Hour
                ''',
                'start_hour',
                'Cisco-IOS-XR-lib-keychain-cfg', False, is_mandatory=True),
            _MetaInfoClassMember('start-minutes', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '59')], [],
                '''                Start Minutes
                ''',
                'start_minutes',
                'Cisco-IOS-XR-lib-keychain-cfg', False, is_mandatory=True),
            _MetaInfoClassMember('start-seconds', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '59')], [],
                '''                Start Seconds
                ''',
                'start_seconds',
                'Cisco-IOS-XR-lib-keychain-cfg', False, is_mandatory=True),
            _MetaInfoClassMember('start-date', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('1', '31')], [],
                '''                Start Date
                ''',
                'start_date',
                'Cisco-IOS-XR-lib-keychain-cfg', False, is_mandatory=True),
            _MetaInfoClassMember('start-month', REFERENCE_ENUM_CLASS, 'KeyChainMonth', 'Key-chain-month',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_lib_keychain_cfg', 'KeyChainMonth',
                [], [],
                '''                Start Month
                ''',
                'start_month',
                'Cisco-IOS-XR-lib-keychain-cfg', False, is_mandatory=True),
            _MetaInfoClassMember('start-year', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('1993', '2035')], [],
                '''                Start Year
                ''',
                'start_year',
                'Cisco-IOS-XR-lib-keychain-cfg', False, is_mandatory=True),
            _MetaInfoClassMember('life-time', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('1', '2147483647')], [],
                '''                Lifetime duration in seconds
                ''',
                'life_time',
                'Cisco-IOS-XR-lib-keychain-cfg', False),
            _MetaInfoClassMember('infinite-flag', ATTRIBUTE, 'bool', 'boolean',
                None, None,
                [], [],
                '''                Infinite Lifetime flag
                ''',
                'infinite_flag',
                'Cisco-IOS-XR-lib-keychain-cfg', False),
            _MetaInfoClassMember('end-hour', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '23')], [],
                '''                End Hour
                ''',
                'end_hour',
                'Cisco-IOS-XR-lib-keychain-cfg', False),
            _MetaInfoClassMember('end-minutes', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '59')], [],
                '''                End Minutes
                ''',
                'end_minutes',
                'Cisco-IOS-XR-lib-keychain-cfg', False),
            _MetaInfoClassMember('end-seconds', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '59')], [],
                '''                End Seconds
                ''',
                'end_seconds',
                'Cisco-IOS-XR-lib-keychain-cfg', False),
            _MetaInfoClassMember('end-date', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('1', '31')], [],
                '''                End Date
                ''',
                'end_date',
                'Cisco-IOS-XR-lib-keychain-cfg', False),
            _MetaInfoClassMember('end-month', REFERENCE_ENUM_CLASS, 'KeyChainMonth', 'Key-chain-month',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_lib_keychain_cfg', 'KeyChainMonth',
                [], [],
                '''                End Month
                ''',
                'end_month',
                'Cisco-IOS-XR-lib-keychain-cfg', False),
            _MetaInfoClassMember('end-year', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('1993', '2035')], [],
                '''                End Year
                ''',
                'end_year',
                'Cisco-IOS-XR-lib-keychain-cfg', False),
            ],
            'Cisco-IOS-XR-lib-keychain-cfg',
            'send-lifetime',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-lib-keychain-cfg'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_lib_keychain_cfg',
            is_presence=True,
        ),
    },
    'Keychains.Keychain.Keys.Key' : {
        'meta_info' : _MetaInfoClass('Keychains.Keychain.Keys.Key', REFERENCE_LIST,
            '''Key Identifier''',
            False, 
            [
            _MetaInfoClassMember('key-id', ATTRIBUTE, 'str', 'xr:Cisco-ios-xr-string',
                None, None,
                [], [b'[\\w\\-\\.:,_@#%$\\+=\\|;]+'],
                '''                48-bit Key identifier
                ''',
                'key_id',
                'Cisco-IOS-XR-lib-keychain-cfg', True),
            _MetaInfoClassMember('accept-lifetime', REFERENCE_CLASS, 'AcceptLifetime', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_lib_keychain_cfg', 'Keychains.Keychain.Keys.Key.AcceptLifetime',
                [], [],
                '''                Configure a key Acceptance Lifetime
                ''',
                'accept_lifetime',
                'Cisco-IOS-XR-lib-keychain-cfg', False, is_presence=True),
            _MetaInfoClassMember('send-lifetime', REFERENCE_CLASS, 'SendLifetime', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_lib_keychain_cfg', 'Keychains.Keychain.Keys.Key.SendLifetime',
                [], [],
                '''                Configure a Send Lifetime
                ''',
                'send_lifetime',
                'Cisco-IOS-XR-lib-keychain-cfg', False, is_presence=True),
            _MetaInfoClassMember('key-string', ATTRIBUTE, 'str', 'xr:Proprietary-password',
                None, None,
                [], [b'(!.+)|([^!].+)'],
                '''                Configure a clear text/encrypted Key string 
                ''',
                'key_string',
                'Cisco-IOS-XR-lib-keychain-cfg', False),
            _MetaInfoClassMember('cryptographic-algorithm', REFERENCE_ENUM_CLASS, 'CryptoAlg', 'Crypto-alg',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_lib_keychain_cfg', 'CryptoAlg',
                [], [],
                '''                Configure the cryptographic algorithm
                ''',
                'cryptographic_algorithm',
                'Cisco-IOS-XR-lib-keychain-cfg', False),
            ],
            'Cisco-IOS-XR-lib-keychain-cfg',
            'key',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-lib-keychain-cfg'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_lib_keychain_cfg',
        ),
    },
    'Keychains.Keychain.Keys' : {
        'meta_info' : _MetaInfoClass('Keychains.Keychain.Keys', REFERENCE_CLASS,
            '''Configure a Key''',
            False, 
            [
            _MetaInfoClassMember('key', REFERENCE_LIST, 'Key', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_lib_keychain_cfg', 'Keychains.Keychain.Keys.Key',
                [], [],
                '''                Key Identifier
                ''',
                'key',
                'Cisco-IOS-XR-lib-keychain-cfg', False),
            ],
            'Cisco-IOS-XR-lib-keychain-cfg',
            'keys',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-lib-keychain-cfg'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_lib_keychain_cfg',
        ),
    },
    'Keychains.Keychain' : {
        'meta_info' : _MetaInfoClass('Keychains.Keychain', REFERENCE_LIST,
            '''Name of the key chain''',
            False, 
            [
            _MetaInfoClassMember('chain-name', ATTRIBUTE, 'str', 'xr:Cisco-ios-xr-string',
                None, None,
                [(1, 32)], [],
                '''                Name of the key chain
                ''',
                'chain_name',
                'Cisco-IOS-XR-lib-keychain-cfg', True),
            _MetaInfoClassMember('accept-tolerance', REFERENCE_CLASS, 'AcceptTolerance', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_lib_keychain_cfg', 'Keychains.Keychain.AcceptTolerance',
                [], [],
                '''                Accept Tolerance in seconds or infinite
                ''',
                'accept_tolerance',
                'Cisco-IOS-XR-lib-keychain-cfg', False),
            _MetaInfoClassMember('macsec-keychain', REFERENCE_CLASS, 'MacsecKeychain', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_lib_keychain_cfg', 'Keychains.Keychain.MacsecKeychain',
                [], [],
                '''                Name of the key chain for MACSec
                ''',
                'macsec_keychain',
                'Cisco-IOS-XR-lib-keychain-cfg', False),
            _MetaInfoClassMember('keys', REFERENCE_CLASS, 'Keys', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_lib_keychain_cfg', 'Keychains.Keychain.Keys',
                [], [],
                '''                Configure a Key
                ''',
                'keys',
                'Cisco-IOS-XR-lib-keychain-cfg', False),
            ],
            'Cisco-IOS-XR-lib-keychain-cfg',
            'keychain',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-lib-keychain-cfg'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_lib_keychain_cfg',
        ),
    },
    'Keychains' : {
        'meta_info' : _MetaInfoClass('Keychains', REFERENCE_CLASS,
            '''Configure a Key Chain''',
            False, 
            [
            _MetaInfoClassMember('keychain', REFERENCE_LIST, 'Keychain', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_lib_keychain_cfg', 'Keychains.Keychain',
                [], [],
                '''                Name of the key chain
                ''',
                'keychain',
                'Cisco-IOS-XR-lib-keychain-cfg', False),
            ],
            'Cisco-IOS-XR-lib-keychain-cfg',
            'keychains',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-lib-keychain-cfg'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_lib_keychain_cfg',
        ),
    },
}
_meta_table['Keychains.Keychain.MacsecKeychain.MacsecKeys.MacsecKey.MacsecLifetime']['meta_info'].parent =_meta_table['Keychains.Keychain.MacsecKeychain.MacsecKeys.MacsecKey']['meta_info']
_meta_table['Keychains.Keychain.MacsecKeychain.MacsecKeys.MacsecKey.MacsecKeyString']['meta_info'].parent =_meta_table['Keychains.Keychain.MacsecKeychain.MacsecKeys.MacsecKey']['meta_info']
_meta_table['Keychains.Keychain.MacsecKeychain.MacsecKeys.MacsecKey']['meta_info'].parent =_meta_table['Keychains.Keychain.MacsecKeychain.MacsecKeys']['meta_info']
_meta_table['Keychains.Keychain.MacsecKeychain.MacsecKeys']['meta_info'].parent =_meta_table['Keychains.Keychain.MacsecKeychain']['meta_info']
_meta_table['Keychains.Keychain.Keys.Key.AcceptLifetime']['meta_info'].parent =_meta_table['Keychains.Keychain.Keys.Key']['meta_info']
_meta_table['Keychains.Keychain.Keys.Key.SendLifetime']['meta_info'].parent =_meta_table['Keychains.Keychain.Keys.Key']['meta_info']
_meta_table['Keychains.Keychain.Keys.Key']['meta_info'].parent =_meta_table['Keychains.Keychain.Keys']['meta_info']
_meta_table['Keychains.Keychain.AcceptTolerance']['meta_info'].parent =_meta_table['Keychains.Keychain']['meta_info']
_meta_table['Keychains.Keychain.MacsecKeychain']['meta_info'].parent =_meta_table['Keychains.Keychain']['meta_info']
_meta_table['Keychains.Keychain.Keys']['meta_info'].parent =_meta_table['Keychains.Keychain']['meta_info']
_meta_table['Keychains.Keychain']['meta_info'].parent =_meta_table['Keychains']['meta_info']
