
'''
This is auto-generated file,
which includes metadata for module Cisco_IOS_XR_crypto_ssh_oper
'''

from ydk._core._dm_meta_info import _MetaInfoClassMember, _MetaInfoClass, _MetaInfoEnum
from ydk._core._dm_meta_info import ATTRIBUTE, REFERENCE_LIST, REFERENCE_LEAFLIST, REFERENCE_BITS, REFERENCE_UNION
from ydk._core._dm_meta_info import REFERENCE_CLASS, REFERENCE_IDENTITY_CLASS, REFERENCE_ENUM_CLASS, ANYXML_CLASS
from ydk._core._importer import _yang_ns

_meta_table = {
    'Connection' : _MetaInfoEnum('Connection',
        'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_ssh_oper', 'Connection',
        '''SSH channel connection types''',
        {
            'undefined':'undefined',
            'shell':'shell',
            'exec':'exec_',
            'scp':'scp',
            'sftp-subsystem':'sftp_subsystem',
            'netconf-subsystem':'netconf_subsystem',
            'tl1-subsystem':'tl1_subsystem',
            'netconf-xml-subsystem':'netconf_xml_subsystem',
        }, 'Cisco-IOS-XR-crypto-ssh-oper', _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-crypto-ssh-oper']),
    'Authen' : _MetaInfoEnum('Authen',
        'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_ssh_oper', 'Authen',
        '''SSH session authentication types''',
        {
            'password':'password',
            'rsa-public-key':'rsa_public_key',
            'keyboard-interactive':'keyboard_interactive',
        }, 'Cisco-IOS-XR-crypto-ssh-oper', _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-crypto-ssh-oper']),
    'Version' : _MetaInfoEnum('Version',
        'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_ssh_oper', 'Version',
        '''SSH state versions''',
        {
            'v2':'v2',
            'v1':'v1',
        }, 'Cisco-IOS-XR-crypto-ssh-oper', _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-crypto-ssh-oper']),
    'States' : _MetaInfoEnum('States',
        'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_ssh_oper', 'States',
        '''SSH session states''',
        {
            'open':'open',
            'version-ok':'version_ok',
            'key-exchange-initialize':'key_exchange_initialize',
            'key-exchange-dh':'key_exchange_dh',
            'new-keys':'new_keys',
            'authenticate-information':'authenticate_information',
            'authenticated':'authenticated',
            'channel-open':'channel_open',
            'pty-open':'pty_open',
            'session-open':'session_open',
            'rekey':'rekey',
            'suspended':'suspended',
            'session-closed':'session_closed',
        }, 'Cisco-IOS-XR-crypto-ssh-oper', _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-crypto-ssh-oper']),
    'Mac' : _MetaInfoEnum('Mac',
        'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_ssh_oper', 'Mac',
        '''Different Message Authentication Code(MAC)
functions''',
        {
            'mac-not-applicable':'mac_not_applicable',
            'hmac-md5':'hmac_md5',
            'hmac-sha1':'hmac_sha1',
            'hmac-sha2-256':'hmac_sha2_256',
            'hmac-sha2-512':'hmac_sha2_512',
            'aes-gcm':'aes_gcm',
        }, 'Cisco-IOS-XR-crypto-ssh-oper', _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-crypto-ssh-oper']),
    'Cipher' : _MetaInfoEnum('Cipher',
        'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_ssh_oper', 'Cipher',
        '''SSH session in and out cipher standards''',
        {
            'cipher-not-applicable':'cipher_not_applicable',
            'aes128-cbc':'aes128_cbc',
            'aes192-cbc':'aes192_cbc',
            'aes256-cbc':'aes256_cbc',
            'triple-des-cbc':'triple_des_cbc',
            'aes128-ctr':'aes128_ctr',
            'aes192-ctr':'aes192_ctr',
            'aes256-ctr':'aes256_ctr',
            'aes128-gcm':'aes128_gcm',
            'aes256-gcm':'aes256_gcm',
        }, 'Cisco-IOS-XR-crypto-ssh-oper', _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-crypto-ssh-oper']),
    'Hostkey' : _MetaInfoEnum('Hostkey',
        'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_ssh_oper', 'Hostkey',
        '''SSH session authentication types''',
        {
            'host-key-not-applicable':'host_key_not_applicable',
            'ssh-dss':'ssh_dss',
            'ssh-rsa':'ssh_rsa',
            'ecdsa-sha2-nistp521':'ecdsa_sha2_nistp521',
            'ecdsa-sha2-nistp384':'ecdsa_sha2_nistp384',
            'ecdsa-sha2-nistp256':'ecdsa_sha2_nistp256',
        }, 'Cisco-IOS-XR-crypto-ssh-oper', _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-crypto-ssh-oper']),
    'KexName' : _MetaInfoEnum('KexName',
        'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_ssh_oper', 'KexName',
        '''Different key-exchange(kex) algorithms''',
        {
            'kex-not-applicable':'kex_not_applicable',
            'diffie-hellman-group1':'diffie_hellman_group1',
            'diffie-hellman-group14':'diffie_hellman_group14',
            'diffie-hellman-group15':'diffie_hellman_group15',
            'diffie-hellman-group16':'diffie_hellman_group16',
            'diffie-hellman-group17':'diffie_hellman_group17',
            'diffie-hellman-group18':'diffie_hellman_group18',
            'ecdh-nistp256':'ecdh_nistp256',
            'ecdh-nistp384':'ecdh_nistp384',
            'ecdh-nistp521':'ecdh_nistp521',
            'password-authenticated':'password_authenticated',
        }, 'Cisco-IOS-XR-crypto-ssh-oper', _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-crypto-ssh-oper']),
    'Ssh1.Kex.Nodes.Node.IncomingSessions.SessionDetailInfo.NextSession' : {
        'meta_info' : _MetaInfoClass('Ssh1.Kex.Nodes.Node.IncomingSessions.SessionDetailInfo.NextSession', REFERENCE_CLASS,
            '''next session''',
            False, 
            [
            ],
            'Cisco-IOS-XR-crypto-ssh-oper',
            'next-session',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-crypto-ssh-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_ssh_oper',
            is_config=False,
        ),
    },
    'Ssh1.Kex.Nodes.Node.IncomingSessions.SessionDetailInfo' : {
        'meta_info' : _MetaInfoClass('Ssh1.Kex.Nodes.Node.IncomingSessions.SessionDetailInfo', REFERENCE_LIST,
            '''session detail info''',
            False, 
            [
            _MetaInfoClassMember('next-session', REFERENCE_CLASS, 'NextSession', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_ssh_oper', 'Ssh1.Kex.Nodes.Node.IncomingSessions.SessionDetailInfo.NextSession',
                [], [],
                '''                next session
                ''',
                'next_session',
                'Cisco-IOS-XR-crypto-ssh-oper', False, is_config=False),
            _MetaInfoClassMember('session-id', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                Session ID
                ''',
                'session_id',
                'Cisco-IOS-XR-crypto-ssh-oper', False, is_config=False),
            _MetaInfoClassMember('key-exchange', REFERENCE_ENUM_CLASS, 'KexName', 'Kex-name',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_ssh_oper', 'KexName',
                [], [],
                '''                Key exchange name
                ''',
                'key_exchange',
                'Cisco-IOS-XR-crypto-ssh-oper', False, is_config=False),
            _MetaInfoClassMember('public-key', REFERENCE_ENUM_CLASS, 'Hostkey', 'Hostkey',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_ssh_oper', 'Hostkey',
                [], [],
                '''                Host key algorithm
                ''',
                'public_key',
                'Cisco-IOS-XR-crypto-ssh-oper', False, is_config=False),
            _MetaInfoClassMember('in-cipher', REFERENCE_ENUM_CLASS, 'Cipher', 'Cipher',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_ssh_oper', 'Cipher',
                [], [],
                '''                In cipher algorithm
                ''',
                'in_cipher',
                'Cisco-IOS-XR-crypto-ssh-oper', False, is_config=False),
            _MetaInfoClassMember('out-cipher', REFERENCE_ENUM_CLASS, 'Cipher', 'Cipher',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_ssh_oper', 'Cipher',
                [], [],
                '''                Out cipher algorithm
                ''',
                'out_cipher',
                'Cisco-IOS-XR-crypto-ssh-oper', False, is_config=False),
            _MetaInfoClassMember('in-mac', REFERENCE_ENUM_CLASS, 'Mac', 'Mac',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_ssh_oper', 'Mac',
                [], [],
                '''                In MAC
                ''',
                'in_mac',
                'Cisco-IOS-XR-crypto-ssh-oper', False, is_config=False),
            _MetaInfoClassMember('out-mac', REFERENCE_ENUM_CLASS, 'Mac', 'Mac',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_ssh_oper', 'Mac',
                [], [],
                '''                Out MAC
                ''',
                'out_mac',
                'Cisco-IOS-XR-crypto-ssh-oper', False, is_config=False),
            _MetaInfoClassMember('start-time', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                session start time
                ''',
                'start_time',
                'Cisco-IOS-XR-crypto-ssh-oper', False, is_config=False),
            _MetaInfoClassMember('end-time', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                session end time
                ''',
                'end_time',
                'Cisco-IOS-XR-crypto-ssh-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-crypto-ssh-oper',
            'session-detail-info',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-crypto-ssh-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_ssh_oper',
            is_config=False,
        ),
    },
    'Ssh1.Kex.Nodes.Node.IncomingSessions' : {
        'meta_info' : _MetaInfoClass('Ssh1.Kex.Nodes.Node.IncomingSessions', REFERENCE_CLASS,
            '''List of incoming sessions''',
            False, 
            [
            _MetaInfoClassMember('session-detail-info', REFERENCE_LIST, 'SessionDetailInfo', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_ssh_oper', 'Ssh1.Kex.Nodes.Node.IncomingSessions.SessionDetailInfo',
                [], [],
                '''                session detail info
                ''',
                'session_detail_info',
                'Cisco-IOS-XR-crypto-ssh-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-crypto-ssh-oper',
            'incoming-sessions',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-crypto-ssh-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_ssh_oper',
            is_config=False,
        ),
    },
    'Ssh1.Kex.Nodes.Node.OutgoingConnections.SessionDetailInfo.NextSession' : {
        'meta_info' : _MetaInfoClass('Ssh1.Kex.Nodes.Node.OutgoingConnections.SessionDetailInfo.NextSession', REFERENCE_CLASS,
            '''next session''',
            False, 
            [
            ],
            'Cisco-IOS-XR-crypto-ssh-oper',
            'next-session',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-crypto-ssh-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_ssh_oper',
            is_config=False,
        ),
    },
    'Ssh1.Kex.Nodes.Node.OutgoingConnections.SessionDetailInfo' : {
        'meta_info' : _MetaInfoClass('Ssh1.Kex.Nodes.Node.OutgoingConnections.SessionDetailInfo', REFERENCE_LIST,
            '''session detail info''',
            False, 
            [
            _MetaInfoClassMember('next-session', REFERENCE_CLASS, 'NextSession', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_ssh_oper', 'Ssh1.Kex.Nodes.Node.OutgoingConnections.SessionDetailInfo.NextSession',
                [], [],
                '''                next session
                ''',
                'next_session',
                'Cisco-IOS-XR-crypto-ssh-oper', False, is_config=False),
            _MetaInfoClassMember('session-id', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                Session ID
                ''',
                'session_id',
                'Cisco-IOS-XR-crypto-ssh-oper', False, is_config=False),
            _MetaInfoClassMember('key-exchange', REFERENCE_ENUM_CLASS, 'KexName', 'Kex-name',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_ssh_oper', 'KexName',
                [], [],
                '''                Key exchange name
                ''',
                'key_exchange',
                'Cisco-IOS-XR-crypto-ssh-oper', False, is_config=False),
            _MetaInfoClassMember('public-key', REFERENCE_ENUM_CLASS, 'Hostkey', 'Hostkey',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_ssh_oper', 'Hostkey',
                [], [],
                '''                Host key algorithm
                ''',
                'public_key',
                'Cisco-IOS-XR-crypto-ssh-oper', False, is_config=False),
            _MetaInfoClassMember('in-cipher', REFERENCE_ENUM_CLASS, 'Cipher', 'Cipher',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_ssh_oper', 'Cipher',
                [], [],
                '''                In cipher algorithm
                ''',
                'in_cipher',
                'Cisco-IOS-XR-crypto-ssh-oper', False, is_config=False),
            _MetaInfoClassMember('out-cipher', REFERENCE_ENUM_CLASS, 'Cipher', 'Cipher',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_ssh_oper', 'Cipher',
                [], [],
                '''                Out cipher algorithm
                ''',
                'out_cipher',
                'Cisco-IOS-XR-crypto-ssh-oper', False, is_config=False),
            _MetaInfoClassMember('in-mac', REFERENCE_ENUM_CLASS, 'Mac', 'Mac',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_ssh_oper', 'Mac',
                [], [],
                '''                In MAC
                ''',
                'in_mac',
                'Cisco-IOS-XR-crypto-ssh-oper', False, is_config=False),
            _MetaInfoClassMember('out-mac', REFERENCE_ENUM_CLASS, 'Mac', 'Mac',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_ssh_oper', 'Mac',
                [], [],
                '''                Out MAC
                ''',
                'out_mac',
                'Cisco-IOS-XR-crypto-ssh-oper', False, is_config=False),
            _MetaInfoClassMember('start-time', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                session start time
                ''',
                'start_time',
                'Cisco-IOS-XR-crypto-ssh-oper', False, is_config=False),
            _MetaInfoClassMember('end-time', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                session end time
                ''',
                'end_time',
                'Cisco-IOS-XR-crypto-ssh-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-crypto-ssh-oper',
            'session-detail-info',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-crypto-ssh-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_ssh_oper',
            is_config=False,
        ),
    },
    'Ssh1.Kex.Nodes.Node.OutgoingConnections' : {
        'meta_info' : _MetaInfoClass('Ssh1.Kex.Nodes.Node.OutgoingConnections', REFERENCE_CLASS,
            '''List of outgoing connections''',
            False, 
            [
            _MetaInfoClassMember('session-detail-info', REFERENCE_LIST, 'SessionDetailInfo', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_ssh_oper', 'Ssh1.Kex.Nodes.Node.OutgoingConnections.SessionDetailInfo',
                [], [],
                '''                session detail info
                ''',
                'session_detail_info',
                'Cisco-IOS-XR-crypto-ssh-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-crypto-ssh-oper',
            'outgoing-connections',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-crypto-ssh-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_ssh_oper',
            is_config=False,
        ),
    },
    'Ssh1.Kex.Nodes.Node' : {
        'meta_info' : _MetaInfoClass('Ssh1.Kex.Nodes.Node', REFERENCE_LIST,
            '''SSH session details for a particular node''',
            False, 
            [
            _MetaInfoClassMember('node-name', ATTRIBUTE, 'str', 'xr:Node-id',
                None, None,
                [], [b'([a-zA-Z0-9_]*\\d+/){1,2}([a-zA-Z0-9_]*\\d+)'],
                '''                Node name
                ''',
                'node_name',
                'Cisco-IOS-XR-crypto-ssh-oper', True, is_config=False),
            _MetaInfoClassMember('incoming-sessions', REFERENCE_CLASS, 'IncomingSessions', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_ssh_oper', 'Ssh1.Kex.Nodes.Node.IncomingSessions',
                [], [],
                '''                List of incoming sessions
                ''',
                'incoming_sessions',
                'Cisco-IOS-XR-crypto-ssh-oper', False, is_config=False),
            _MetaInfoClassMember('outgoing-connections', REFERENCE_CLASS, 'OutgoingConnections', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_ssh_oper', 'Ssh1.Kex.Nodes.Node.OutgoingConnections',
                [], [],
                '''                List of outgoing connections
                ''',
                'outgoing_connections',
                'Cisco-IOS-XR-crypto-ssh-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-crypto-ssh-oper',
            'node',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-crypto-ssh-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_ssh_oper',
            is_config=False,
        ),
    },
    'Ssh1.Kex.Nodes' : {
        'meta_info' : _MetaInfoClass('Ssh1.Kex.Nodes', REFERENCE_CLASS,
            '''Node-specific ssh session details''',
            False, 
            [
            _MetaInfoClassMember('node', REFERENCE_LIST, 'Node', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_ssh_oper', 'Ssh1.Kex.Nodes.Node',
                [], [],
                '''                SSH session details for a particular node
                ''',
                'node',
                'Cisco-IOS-XR-crypto-ssh-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-crypto-ssh-oper',
            'nodes',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-crypto-ssh-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_ssh_oper',
            is_config=False,
        ),
    },
    'Ssh1.Kex' : {
        'meta_info' : _MetaInfoClass('Ssh1.Kex', REFERENCE_CLASS,
            '''key exchange method data''',
            False, 
            [
            _MetaInfoClassMember('nodes', REFERENCE_CLASS, 'Nodes', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_ssh_oper', 'Ssh1.Kex.Nodes',
                [], [],
                '''                Node-specific ssh session details
                ''',
                'nodes',
                'Cisco-IOS-XR-crypto-ssh-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-crypto-ssh-oper',
            'kex',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-crypto-ssh-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_ssh_oper',
            is_config=False,
        ),
    },
    'Ssh1' : {
        'meta_info' : _MetaInfoClass('Ssh1', REFERENCE_CLASS,
            '''Crypto Secure Shell(SSH) data''',
            False, 
            [
            _MetaInfoClassMember('kex', REFERENCE_CLASS, 'Kex', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_ssh_oper', 'Ssh1.Kex',
                [], [],
                '''                key exchange method data
                ''',
                'kex',
                'Cisco-IOS-XR-crypto-ssh-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-crypto-ssh-oper',
            'ssh1',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-crypto-ssh-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_ssh_oper',
            is_config=False,
        ),
    },
    'Ssh.Session.Rekey.IncomingSessions.SessionRekeyInfo.NextSession' : {
        'meta_info' : _MetaInfoClass('Ssh.Session.Rekey.IncomingSessions.SessionRekeyInfo.NextSession', REFERENCE_CLASS,
            '''next session''',
            False, 
            [
            ],
            'Cisco-IOS-XR-crypto-ssh-oper',
            'next-session',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-crypto-ssh-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_ssh_oper',
            is_config=False,
        ),
    },
    'Ssh.Session.Rekey.IncomingSessions.SessionRekeyInfo' : {
        'meta_info' : _MetaInfoClass('Ssh.Session.Rekey.IncomingSessions.SessionRekeyInfo', REFERENCE_LIST,
            '''session rekey info''',
            False, 
            [
            _MetaInfoClassMember('next-session', REFERENCE_CLASS, 'NextSession', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_ssh_oper', 'Ssh.Session.Rekey.IncomingSessions.SessionRekeyInfo.NextSession',
                [], [],
                '''                next session
                ''',
                'next_session',
                'Cisco-IOS-XR-crypto-ssh-oper', False, is_config=False),
            _MetaInfoClassMember('session-id', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                Session ID
                ''',
                'session_id',
                'Cisco-IOS-XR-crypto-ssh-oper', False, is_config=False),
            _MetaInfoClassMember('session-rekey-count', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                Session Rekey Count
                ''',
                'session_rekey_count',
                'Cisco-IOS-XR-crypto-ssh-oper', False, is_config=False),
            _MetaInfoClassMember('time-to-rekey', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Time To Rekey
                ''',
                'time_to_rekey',
                'Cisco-IOS-XR-crypto-ssh-oper', False, is_config=False),
            _MetaInfoClassMember('volume-to-rekey', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Volume To Rekey
                ''',
                'volume_to_rekey',
                'Cisco-IOS-XR-crypto-ssh-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-crypto-ssh-oper',
            'session-rekey-info',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-crypto-ssh-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_ssh_oper',
            is_config=False,
        ),
    },
    'Ssh.Session.Rekey.IncomingSessions' : {
        'meta_info' : _MetaInfoClass('Ssh.Session.Rekey.IncomingSessions', REFERENCE_CLASS,
            '''List of incoming sessions''',
            False, 
            [
            _MetaInfoClassMember('session-rekey-info', REFERENCE_LIST, 'SessionRekeyInfo', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_ssh_oper', 'Ssh.Session.Rekey.IncomingSessions.SessionRekeyInfo',
                [], [],
                '''                session rekey info
                ''',
                'session_rekey_info',
                'Cisco-IOS-XR-crypto-ssh-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-crypto-ssh-oper',
            'incoming-sessions',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-crypto-ssh-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_ssh_oper',
            is_config=False,
        ),
    },
    'Ssh.Session.Rekey.OutgoingConnections.SessionRekeyInfo.NextSession' : {
        'meta_info' : _MetaInfoClass('Ssh.Session.Rekey.OutgoingConnections.SessionRekeyInfo.NextSession', REFERENCE_CLASS,
            '''next session''',
            False, 
            [
            ],
            'Cisco-IOS-XR-crypto-ssh-oper',
            'next-session',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-crypto-ssh-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_ssh_oper',
            is_config=False,
        ),
    },
    'Ssh.Session.Rekey.OutgoingConnections.SessionRekeyInfo' : {
        'meta_info' : _MetaInfoClass('Ssh.Session.Rekey.OutgoingConnections.SessionRekeyInfo', REFERENCE_LIST,
            '''session rekey info''',
            False, 
            [
            _MetaInfoClassMember('next-session', REFERENCE_CLASS, 'NextSession', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_ssh_oper', 'Ssh.Session.Rekey.OutgoingConnections.SessionRekeyInfo.NextSession',
                [], [],
                '''                next session
                ''',
                'next_session',
                'Cisco-IOS-XR-crypto-ssh-oper', False, is_config=False),
            _MetaInfoClassMember('session-id', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                Session ID
                ''',
                'session_id',
                'Cisco-IOS-XR-crypto-ssh-oper', False, is_config=False),
            _MetaInfoClassMember('session-rekey-count', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                Session Rekey Count
                ''',
                'session_rekey_count',
                'Cisco-IOS-XR-crypto-ssh-oper', False, is_config=False),
            _MetaInfoClassMember('time-to-rekey', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Time To Rekey
                ''',
                'time_to_rekey',
                'Cisco-IOS-XR-crypto-ssh-oper', False, is_config=False),
            _MetaInfoClassMember('volume-to-rekey', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Volume To Rekey
                ''',
                'volume_to_rekey',
                'Cisco-IOS-XR-crypto-ssh-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-crypto-ssh-oper',
            'session-rekey-info',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-crypto-ssh-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_ssh_oper',
            is_config=False,
        ),
    },
    'Ssh.Session.Rekey.OutgoingConnections' : {
        'meta_info' : _MetaInfoClass('Ssh.Session.Rekey.OutgoingConnections', REFERENCE_CLASS,
            '''List of outgoing connections''',
            False, 
            [
            _MetaInfoClassMember('session-rekey-info', REFERENCE_LIST, 'SessionRekeyInfo', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_ssh_oper', 'Ssh.Session.Rekey.OutgoingConnections.SessionRekeyInfo',
                [], [],
                '''                session rekey info
                ''',
                'session_rekey_info',
                'Cisco-IOS-XR-crypto-ssh-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-crypto-ssh-oper',
            'outgoing-connections',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-crypto-ssh-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_ssh_oper',
            is_config=False,
        ),
    },
    'Ssh.Session.Rekey' : {
        'meta_info' : _MetaInfoClass('Ssh.Session.Rekey', REFERENCE_CLASS,
            '''SSH session rekey information''',
            False, 
            [
            _MetaInfoClassMember('incoming-sessions', REFERENCE_CLASS, 'IncomingSessions', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_ssh_oper', 'Ssh.Session.Rekey.IncomingSessions',
                [], [],
                '''                List of incoming sessions
                ''',
                'incoming_sessions',
                'Cisco-IOS-XR-crypto-ssh-oper', False, is_config=False),
            _MetaInfoClassMember('outgoing-connections', REFERENCE_CLASS, 'OutgoingConnections', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_ssh_oper', 'Ssh.Session.Rekey.OutgoingConnections',
                [], [],
                '''                List of outgoing connections
                ''',
                'outgoing_connections',
                'Cisco-IOS-XR-crypto-ssh-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-crypto-ssh-oper',
            'rekey',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-crypto-ssh-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_ssh_oper',
            is_config=False,
        ),
    },
    'Ssh.Session.HistoryDetail.IncomingSessions.SessionDetailInfo.NextSession' : {
        'meta_info' : _MetaInfoClass('Ssh.Session.HistoryDetail.IncomingSessions.SessionDetailInfo.NextSession', REFERENCE_CLASS,
            '''next session''',
            False, 
            [
            ],
            'Cisco-IOS-XR-crypto-ssh-oper',
            'next-session',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-crypto-ssh-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_ssh_oper',
            is_config=False,
        ),
    },
    'Ssh.Session.HistoryDetail.IncomingSessions.SessionDetailInfo' : {
        'meta_info' : _MetaInfoClass('Ssh.Session.HistoryDetail.IncomingSessions.SessionDetailInfo', REFERENCE_LIST,
            '''session detail info''',
            False, 
            [
            _MetaInfoClassMember('next-session', REFERENCE_CLASS, 'NextSession', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_ssh_oper', 'Ssh.Session.HistoryDetail.IncomingSessions.SessionDetailInfo.NextSession',
                [], [],
                '''                next session
                ''',
                'next_session',
                'Cisco-IOS-XR-crypto-ssh-oper', False, is_config=False),
            _MetaInfoClassMember('session-id', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                Session ID
                ''',
                'session_id',
                'Cisco-IOS-XR-crypto-ssh-oper', False, is_config=False),
            _MetaInfoClassMember('key-exchange', REFERENCE_ENUM_CLASS, 'KexName', 'Kex-name',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_ssh_oper', 'KexName',
                [], [],
                '''                Key exchange name
                ''',
                'key_exchange',
                'Cisco-IOS-XR-crypto-ssh-oper', False, is_config=False),
            _MetaInfoClassMember('public-key', REFERENCE_ENUM_CLASS, 'Hostkey', 'Hostkey',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_ssh_oper', 'Hostkey',
                [], [],
                '''                Host key algorithm
                ''',
                'public_key',
                'Cisco-IOS-XR-crypto-ssh-oper', False, is_config=False),
            _MetaInfoClassMember('in-cipher', REFERENCE_ENUM_CLASS, 'Cipher', 'Cipher',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_ssh_oper', 'Cipher',
                [], [],
                '''                In cipher algorithm
                ''',
                'in_cipher',
                'Cisco-IOS-XR-crypto-ssh-oper', False, is_config=False),
            _MetaInfoClassMember('out-cipher', REFERENCE_ENUM_CLASS, 'Cipher', 'Cipher',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_ssh_oper', 'Cipher',
                [], [],
                '''                Out cipher algorithm
                ''',
                'out_cipher',
                'Cisco-IOS-XR-crypto-ssh-oper', False, is_config=False),
            _MetaInfoClassMember('in-mac', REFERENCE_ENUM_CLASS, 'Mac', 'Mac',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_ssh_oper', 'Mac',
                [], [],
                '''                In MAC
                ''',
                'in_mac',
                'Cisco-IOS-XR-crypto-ssh-oper', False, is_config=False),
            _MetaInfoClassMember('out-mac', REFERENCE_ENUM_CLASS, 'Mac', 'Mac',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_ssh_oper', 'Mac',
                [], [],
                '''                Out MAC
                ''',
                'out_mac',
                'Cisco-IOS-XR-crypto-ssh-oper', False, is_config=False),
            _MetaInfoClassMember('start-time', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                session start time
                ''',
                'start_time',
                'Cisco-IOS-XR-crypto-ssh-oper', False, is_config=False),
            _MetaInfoClassMember('end-time', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                session end time
                ''',
                'end_time',
                'Cisco-IOS-XR-crypto-ssh-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-crypto-ssh-oper',
            'session-detail-info',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-crypto-ssh-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_ssh_oper',
            is_config=False,
        ),
    },
    'Ssh.Session.HistoryDetail.IncomingSessions' : {
        'meta_info' : _MetaInfoClass('Ssh.Session.HistoryDetail.IncomingSessions', REFERENCE_CLASS,
            '''List of incoming sessions''',
            False, 
            [
            _MetaInfoClassMember('session-detail-info', REFERENCE_LIST, 'SessionDetailInfo', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_ssh_oper', 'Ssh.Session.HistoryDetail.IncomingSessions.SessionDetailInfo',
                [], [],
                '''                session detail info
                ''',
                'session_detail_info',
                'Cisco-IOS-XR-crypto-ssh-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-crypto-ssh-oper',
            'incoming-sessions',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-crypto-ssh-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_ssh_oper',
            is_config=False,
        ),
    },
    'Ssh.Session.HistoryDetail.OutgoingConnections.SessionDetailInfo.NextSession' : {
        'meta_info' : _MetaInfoClass('Ssh.Session.HistoryDetail.OutgoingConnections.SessionDetailInfo.NextSession', REFERENCE_CLASS,
            '''next session''',
            False, 
            [
            ],
            'Cisco-IOS-XR-crypto-ssh-oper',
            'next-session',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-crypto-ssh-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_ssh_oper',
            is_config=False,
        ),
    },
    'Ssh.Session.HistoryDetail.OutgoingConnections.SessionDetailInfo' : {
        'meta_info' : _MetaInfoClass('Ssh.Session.HistoryDetail.OutgoingConnections.SessionDetailInfo', REFERENCE_LIST,
            '''session detail info''',
            False, 
            [
            _MetaInfoClassMember('next-session', REFERENCE_CLASS, 'NextSession', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_ssh_oper', 'Ssh.Session.HistoryDetail.OutgoingConnections.SessionDetailInfo.NextSession',
                [], [],
                '''                next session
                ''',
                'next_session',
                'Cisco-IOS-XR-crypto-ssh-oper', False, is_config=False),
            _MetaInfoClassMember('session-id', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                Session ID
                ''',
                'session_id',
                'Cisco-IOS-XR-crypto-ssh-oper', False, is_config=False),
            _MetaInfoClassMember('key-exchange', REFERENCE_ENUM_CLASS, 'KexName', 'Kex-name',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_ssh_oper', 'KexName',
                [], [],
                '''                Key exchange name
                ''',
                'key_exchange',
                'Cisco-IOS-XR-crypto-ssh-oper', False, is_config=False),
            _MetaInfoClassMember('public-key', REFERENCE_ENUM_CLASS, 'Hostkey', 'Hostkey',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_ssh_oper', 'Hostkey',
                [], [],
                '''                Host key algorithm
                ''',
                'public_key',
                'Cisco-IOS-XR-crypto-ssh-oper', False, is_config=False),
            _MetaInfoClassMember('in-cipher', REFERENCE_ENUM_CLASS, 'Cipher', 'Cipher',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_ssh_oper', 'Cipher',
                [], [],
                '''                In cipher algorithm
                ''',
                'in_cipher',
                'Cisco-IOS-XR-crypto-ssh-oper', False, is_config=False),
            _MetaInfoClassMember('out-cipher', REFERENCE_ENUM_CLASS, 'Cipher', 'Cipher',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_ssh_oper', 'Cipher',
                [], [],
                '''                Out cipher algorithm
                ''',
                'out_cipher',
                'Cisco-IOS-XR-crypto-ssh-oper', False, is_config=False),
            _MetaInfoClassMember('in-mac', REFERENCE_ENUM_CLASS, 'Mac', 'Mac',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_ssh_oper', 'Mac',
                [], [],
                '''                In MAC
                ''',
                'in_mac',
                'Cisco-IOS-XR-crypto-ssh-oper', False, is_config=False),
            _MetaInfoClassMember('out-mac', REFERENCE_ENUM_CLASS, 'Mac', 'Mac',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_ssh_oper', 'Mac',
                [], [],
                '''                Out MAC
                ''',
                'out_mac',
                'Cisco-IOS-XR-crypto-ssh-oper', False, is_config=False),
            _MetaInfoClassMember('start-time', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                session start time
                ''',
                'start_time',
                'Cisco-IOS-XR-crypto-ssh-oper', False, is_config=False),
            _MetaInfoClassMember('end-time', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                session end time
                ''',
                'end_time',
                'Cisco-IOS-XR-crypto-ssh-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-crypto-ssh-oper',
            'session-detail-info',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-crypto-ssh-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_ssh_oper',
            is_config=False,
        ),
    },
    'Ssh.Session.HistoryDetail.OutgoingConnections' : {
        'meta_info' : _MetaInfoClass('Ssh.Session.HistoryDetail.OutgoingConnections', REFERENCE_CLASS,
            '''List of outgoing connections''',
            False, 
            [
            _MetaInfoClassMember('session-detail-info', REFERENCE_LIST, 'SessionDetailInfo', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_ssh_oper', 'Ssh.Session.HistoryDetail.OutgoingConnections.SessionDetailInfo',
                [], [],
                '''                session detail info
                ''',
                'session_detail_info',
                'Cisco-IOS-XR-crypto-ssh-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-crypto-ssh-oper',
            'outgoing-connections',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-crypto-ssh-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_ssh_oper',
            is_config=False,
        ),
    },
    'Ssh.Session.HistoryDetail' : {
        'meta_info' : _MetaInfoClass('Ssh.Session.HistoryDetail', REFERENCE_CLASS,
            '''SSH session history detail information''',
            False, 
            [
            _MetaInfoClassMember('incoming-sessions', REFERENCE_CLASS, 'IncomingSessions', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_ssh_oper', 'Ssh.Session.HistoryDetail.IncomingSessions',
                [], [],
                '''                List of incoming sessions
                ''',
                'incoming_sessions',
                'Cisco-IOS-XR-crypto-ssh-oper', False, is_config=False),
            _MetaInfoClassMember('outgoing-connections', REFERENCE_CLASS, 'OutgoingConnections', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_ssh_oper', 'Ssh.Session.HistoryDetail.OutgoingConnections',
                [], [],
                '''                List of outgoing connections
                ''',
                'outgoing_connections',
                'Cisco-IOS-XR-crypto-ssh-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-crypto-ssh-oper',
            'history-detail',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-crypto-ssh-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_ssh_oper',
            is_config=False,
        ),
    },
    'Ssh.Session.Brief.IncomingSessions.SessionBriefInfo.NextSession' : {
        'meta_info' : _MetaInfoClass('Ssh.Session.Brief.IncomingSessions.SessionBriefInfo.NextSession', REFERENCE_CLASS,
            '''next session''',
            False, 
            [
            ],
            'Cisco-IOS-XR-crypto-ssh-oper',
            'next-session',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-crypto-ssh-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_ssh_oper',
            is_config=False,
        ),
    },
    'Ssh.Session.Brief.IncomingSessions.SessionBriefInfo.McInfo' : {
        'meta_info' : _MetaInfoClass('Ssh.Session.Brief.IncomingSessions.SessionBriefInfo.McInfo', REFERENCE_LIST,
            '''List of channel info''',
            False, 
            [
            _MetaInfoClassMember('channel-id', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                Channel ID
                ''',
                'channel_id',
                'Cisco-IOS-XR-crypto-ssh-oper', False, is_config=False),
            _MetaInfoClassMember('connection-type', REFERENCE_ENUM_CLASS, 'Connection', 'Connection',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_ssh_oper', 'Connection',
                [], [],
                '''                Channel Connection Type
                ''',
                'connection_type',
                'Cisco-IOS-XR-crypto-ssh-oper', False, is_config=False),
            _MetaInfoClassMember('vty-line-number', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                VTY line number
                ''',
                'vty_line_number',
                'Cisco-IOS-XR-crypto-ssh-oper', False, is_config=False),
            _MetaInfoClassMember('vty-assigned', ATTRIBUTE, 'bool', 'boolean',
                None, None,
                [], [],
                '''                Boolean indicating whether line VTY line number
                is valid
                ''',
                'vty_assigned',
                'Cisco-IOS-XR-crypto-ssh-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-crypto-ssh-oper',
            'mc-info',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-crypto-ssh-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_ssh_oper',
            is_config=False,
        ),
    },
    'Ssh.Session.Brief.IncomingSessions.SessionBriefInfo' : {
        'meta_info' : _MetaInfoClass('Ssh.Session.Brief.IncomingSessions.SessionBriefInfo', REFERENCE_LIST,
            '''session brief info''',
            False, 
            [
            _MetaInfoClassMember('next-session', REFERENCE_CLASS, 'NextSession', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_ssh_oper', 'Ssh.Session.Brief.IncomingSessions.SessionBriefInfo.NextSession',
                [], [],
                '''                next session
                ''',
                'next_session',
                'Cisco-IOS-XR-crypto-ssh-oper', False, is_config=False),
            _MetaInfoClassMember('session-id', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                Session ID
                ''',
                'session_id',
                'Cisco-IOS-XR-crypto-ssh-oper', False, is_config=False),
            _MetaInfoClassMember('node-name', ATTRIBUTE, 'str', 'xr:Node-id',
                None, None,
                [], [b'([a-zA-Z0-9_]*\\d+/){1,2}([a-zA-Z0-9_]*\\d+)'],
                '''                Node name
                ''',
                'node_name',
                'Cisco-IOS-XR-crypto-ssh-oper', False, is_config=False),
            _MetaInfoClassMember('session-state', REFERENCE_ENUM_CLASS, 'States', 'States',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_ssh_oper', 'States',
                [], [],
                '''                SSH session state
                ''',
                'session_state',
                'Cisco-IOS-XR-crypto-ssh-oper', False, is_config=False),
            _MetaInfoClassMember('user-id', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                User ID
                ''',
                'user_id',
                'Cisco-IOS-XR-crypto-ssh-oper', False, is_config=False),
            _MetaInfoClassMember('host-address', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Host address
                ''',
                'host_address',
                'Cisco-IOS-XR-crypto-ssh-oper', False, is_config=False),
            _MetaInfoClassMember('version', REFERENCE_ENUM_CLASS, 'Version', 'Version',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_ssh_oper', 'Version',
                [], [],
                '''                SSH state version
                ''',
                'version',
                'Cisco-IOS-XR-crypto-ssh-oper', False, is_config=False),
            _MetaInfoClassMember('authentication-type', REFERENCE_ENUM_CLASS, 'Authen', 'Authen',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_ssh_oper', 'Authen',
                [], [],
                '''                Authentication method
                ''',
                'authentication_type',
                'Cisco-IOS-XR-crypto-ssh-oper', False, is_config=False),
            _MetaInfoClassMember('mc-info', REFERENCE_LIST, 'McInfo', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_ssh_oper', 'Ssh.Session.Brief.IncomingSessions.SessionBriefInfo.McInfo',
                [], [],
                '''                List of channel info
                ''',
                'mc_info',
                'Cisco-IOS-XR-crypto-ssh-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-crypto-ssh-oper',
            'session-brief-info',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-crypto-ssh-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_ssh_oper',
            is_config=False,
        ),
    },
    'Ssh.Session.Brief.IncomingSessions' : {
        'meta_info' : _MetaInfoClass('Ssh.Session.Brief.IncomingSessions', REFERENCE_CLASS,
            '''List of incoming sessions''',
            False, 
            [
            _MetaInfoClassMember('session-brief-info', REFERENCE_LIST, 'SessionBriefInfo', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_ssh_oper', 'Ssh.Session.Brief.IncomingSessions.SessionBriefInfo',
                [], [],
                '''                session brief info
                ''',
                'session_brief_info',
                'Cisco-IOS-XR-crypto-ssh-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-crypto-ssh-oper',
            'incoming-sessions',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-crypto-ssh-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_ssh_oper',
            is_config=False,
        ),
    },
    'Ssh.Session.Brief.OutgoingSessions.SessionBriefInfo.NextSession' : {
        'meta_info' : _MetaInfoClass('Ssh.Session.Brief.OutgoingSessions.SessionBriefInfo.NextSession', REFERENCE_CLASS,
            '''next session''',
            False, 
            [
            ],
            'Cisco-IOS-XR-crypto-ssh-oper',
            'next-session',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-crypto-ssh-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_ssh_oper',
            is_config=False,
        ),
    },
    'Ssh.Session.Brief.OutgoingSessions.SessionBriefInfo.McInfo' : {
        'meta_info' : _MetaInfoClass('Ssh.Session.Brief.OutgoingSessions.SessionBriefInfo.McInfo', REFERENCE_LIST,
            '''List of channel info''',
            False, 
            [
            _MetaInfoClassMember('channel-id', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                Channel ID
                ''',
                'channel_id',
                'Cisco-IOS-XR-crypto-ssh-oper', False, is_config=False),
            _MetaInfoClassMember('connection-type', REFERENCE_ENUM_CLASS, 'Connection', 'Connection',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_ssh_oper', 'Connection',
                [], [],
                '''                Channel Connection Type
                ''',
                'connection_type',
                'Cisco-IOS-XR-crypto-ssh-oper', False, is_config=False),
            _MetaInfoClassMember('vty-line-number', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                VTY line number
                ''',
                'vty_line_number',
                'Cisco-IOS-XR-crypto-ssh-oper', False, is_config=False),
            _MetaInfoClassMember('vty-assigned', ATTRIBUTE, 'bool', 'boolean',
                None, None,
                [], [],
                '''                Boolean indicating whether line VTY line number
                is valid
                ''',
                'vty_assigned',
                'Cisco-IOS-XR-crypto-ssh-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-crypto-ssh-oper',
            'mc-info',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-crypto-ssh-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_ssh_oper',
            is_config=False,
        ),
    },
    'Ssh.Session.Brief.OutgoingSessions.SessionBriefInfo' : {
        'meta_info' : _MetaInfoClass('Ssh.Session.Brief.OutgoingSessions.SessionBriefInfo', REFERENCE_LIST,
            '''session brief info''',
            False, 
            [
            _MetaInfoClassMember('next-session', REFERENCE_CLASS, 'NextSession', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_ssh_oper', 'Ssh.Session.Brief.OutgoingSessions.SessionBriefInfo.NextSession',
                [], [],
                '''                next session
                ''',
                'next_session',
                'Cisco-IOS-XR-crypto-ssh-oper', False, is_config=False),
            _MetaInfoClassMember('session-id', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                Session ID
                ''',
                'session_id',
                'Cisco-IOS-XR-crypto-ssh-oper', False, is_config=False),
            _MetaInfoClassMember('node-name', ATTRIBUTE, 'str', 'xr:Node-id',
                None, None,
                [], [b'([a-zA-Z0-9_]*\\d+/){1,2}([a-zA-Z0-9_]*\\d+)'],
                '''                Node name
                ''',
                'node_name',
                'Cisco-IOS-XR-crypto-ssh-oper', False, is_config=False),
            _MetaInfoClassMember('session-state', REFERENCE_ENUM_CLASS, 'States', 'States',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_ssh_oper', 'States',
                [], [],
                '''                SSH session state
                ''',
                'session_state',
                'Cisco-IOS-XR-crypto-ssh-oper', False, is_config=False),
            _MetaInfoClassMember('user-id', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                User ID
                ''',
                'user_id',
                'Cisco-IOS-XR-crypto-ssh-oper', False, is_config=False),
            _MetaInfoClassMember('host-address', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Host address
                ''',
                'host_address',
                'Cisco-IOS-XR-crypto-ssh-oper', False, is_config=False),
            _MetaInfoClassMember('version', REFERENCE_ENUM_CLASS, 'Version', 'Version',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_ssh_oper', 'Version',
                [], [],
                '''                SSH state version
                ''',
                'version',
                'Cisco-IOS-XR-crypto-ssh-oper', False, is_config=False),
            _MetaInfoClassMember('authentication-type', REFERENCE_ENUM_CLASS, 'Authen', 'Authen',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_ssh_oper', 'Authen',
                [], [],
                '''                Authentication method
                ''',
                'authentication_type',
                'Cisco-IOS-XR-crypto-ssh-oper', False, is_config=False),
            _MetaInfoClassMember('mc-info', REFERENCE_LIST, 'McInfo', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_ssh_oper', 'Ssh.Session.Brief.OutgoingSessions.SessionBriefInfo.McInfo',
                [], [],
                '''                List of channel info
                ''',
                'mc_info',
                'Cisco-IOS-XR-crypto-ssh-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-crypto-ssh-oper',
            'session-brief-info',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-crypto-ssh-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_ssh_oper',
            is_config=False,
        ),
    },
    'Ssh.Session.Brief.OutgoingSessions' : {
        'meta_info' : _MetaInfoClass('Ssh.Session.Brief.OutgoingSessions', REFERENCE_CLASS,
            '''List of outgoing sessions''',
            False, 
            [
            _MetaInfoClassMember('session-brief-info', REFERENCE_LIST, 'SessionBriefInfo', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_ssh_oper', 'Ssh.Session.Brief.OutgoingSessions.SessionBriefInfo',
                [], [],
                '''                session brief info
                ''',
                'session_brief_info',
                'Cisco-IOS-XR-crypto-ssh-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-crypto-ssh-oper',
            'outgoing-sessions',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-crypto-ssh-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_ssh_oper',
            is_config=False,
        ),
    },
    'Ssh.Session.Brief' : {
        'meta_info' : _MetaInfoClass('Ssh.Session.Brief', REFERENCE_CLASS,
            '''SSH session brief information''',
            False, 
            [
            _MetaInfoClassMember('incoming-sessions', REFERENCE_CLASS, 'IncomingSessions', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_ssh_oper', 'Ssh.Session.Brief.IncomingSessions',
                [], [],
                '''                List of incoming sessions
                ''',
                'incoming_sessions',
                'Cisco-IOS-XR-crypto-ssh-oper', False, is_config=False),
            _MetaInfoClassMember('outgoing-sessions', REFERENCE_CLASS, 'OutgoingSessions', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_ssh_oper', 'Ssh.Session.Brief.OutgoingSessions',
                [], [],
                '''                List of outgoing sessions
                ''',
                'outgoing_sessions',
                'Cisco-IOS-XR-crypto-ssh-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-crypto-ssh-oper',
            'brief',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-crypto-ssh-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_ssh_oper',
            is_config=False,
        ),
    },
    'Ssh.Session.History.IncomingSessions.SessionHistoryInfo.NextSession' : {
        'meta_info' : _MetaInfoClass('Ssh.Session.History.IncomingSessions.SessionHistoryInfo.NextSession', REFERENCE_CLASS,
            '''next session''',
            False, 
            [
            ],
            'Cisco-IOS-XR-crypto-ssh-oper',
            'next-session',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-crypto-ssh-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_ssh_oper',
            is_config=False,
        ),
    },
    'Ssh.Session.History.IncomingSessions.SessionHistoryInfo.McInfo' : {
        'meta_info' : _MetaInfoClass('Ssh.Session.History.IncomingSessions.SessionHistoryInfo.McInfo', REFERENCE_LIST,
            '''List of channel info''',
            False, 
            [
            _MetaInfoClassMember('channel-id', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                Channel ID
                ''',
                'channel_id',
                'Cisco-IOS-XR-crypto-ssh-oper', False, is_config=False),
            _MetaInfoClassMember('connection-type', REFERENCE_ENUM_CLASS, 'Connection', 'Connection',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_ssh_oper', 'Connection',
                [], [],
                '''                Channel Connection Type
                ''',
                'connection_type',
                'Cisco-IOS-XR-crypto-ssh-oper', False, is_config=False),
            _MetaInfoClassMember('vty-line-number', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                VTY line number
                ''',
                'vty_line_number',
                'Cisco-IOS-XR-crypto-ssh-oper', False, is_config=False),
            _MetaInfoClassMember('vty-assigned', ATTRIBUTE, 'bool', 'boolean',
                None, None,
                [], [],
                '''                Boolean indicating whether line VTY line number
                is valid
                ''',
                'vty_assigned',
                'Cisco-IOS-XR-crypto-ssh-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-crypto-ssh-oper',
            'mc-info',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-crypto-ssh-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_ssh_oper',
            is_config=False,
        ),
    },
    'Ssh.Session.History.IncomingSessions.SessionHistoryInfo' : {
        'meta_info' : _MetaInfoClass('Ssh.Session.History.IncomingSessions.SessionHistoryInfo', REFERENCE_LIST,
            '''session history info''',
            False, 
            [
            _MetaInfoClassMember('next-session', REFERENCE_CLASS, 'NextSession', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_ssh_oper', 'Ssh.Session.History.IncomingSessions.SessionHistoryInfo.NextSession',
                [], [],
                '''                next session
                ''',
                'next_session',
                'Cisco-IOS-XR-crypto-ssh-oper', False, is_config=False),
            _MetaInfoClassMember('session-id', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                Session ID
                ''',
                'session_id',
                'Cisco-IOS-XR-crypto-ssh-oper', False, is_config=False),
            _MetaInfoClassMember('node-name', ATTRIBUTE, 'str', 'xr:Node-id',
                None, None,
                [], [b'([a-zA-Z0-9_]*\\d+/){1,2}([a-zA-Z0-9_]*\\d+)'],
                '''                Node name
                ''',
                'node_name',
                'Cisco-IOS-XR-crypto-ssh-oper', False, is_config=False),
            _MetaInfoClassMember('user-id', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                User ID
                ''',
                'user_id',
                'Cisco-IOS-XR-crypto-ssh-oper', False, is_config=False),
            _MetaInfoClassMember('host-address', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Host address
                ''',
                'host_address',
                'Cisco-IOS-XR-crypto-ssh-oper', False, is_config=False),
            _MetaInfoClassMember('version', REFERENCE_ENUM_CLASS, 'Version', 'Version',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_ssh_oper', 'Version',
                [], [],
                '''                SSH state version
                ''',
                'version',
                'Cisco-IOS-XR-crypto-ssh-oper', False, is_config=False),
            _MetaInfoClassMember('authentication-type', REFERENCE_ENUM_CLASS, 'Authen', 'Authen',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_ssh_oper', 'Authen',
                [], [],
                '''                Authentication method
                ''',
                'authentication_type',
                'Cisco-IOS-XR-crypto-ssh-oper', False, is_config=False),
            _MetaInfoClassMember('mc-info', REFERENCE_LIST, 'McInfo', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_ssh_oper', 'Ssh.Session.History.IncomingSessions.SessionHistoryInfo.McInfo',
                [], [],
                '''                List of channel info
                ''',
                'mc_info',
                'Cisco-IOS-XR-crypto-ssh-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-crypto-ssh-oper',
            'session-history-info',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-crypto-ssh-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_ssh_oper',
            is_config=False,
        ),
    },
    'Ssh.Session.History.IncomingSessions' : {
        'meta_info' : _MetaInfoClass('Ssh.Session.History.IncomingSessions', REFERENCE_CLASS,
            '''List of incoming sessions''',
            False, 
            [
            _MetaInfoClassMember('session-history-info', REFERENCE_LIST, 'SessionHistoryInfo', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_ssh_oper', 'Ssh.Session.History.IncomingSessions.SessionHistoryInfo',
                [], [],
                '''                session history info
                ''',
                'session_history_info',
                'Cisco-IOS-XR-crypto-ssh-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-crypto-ssh-oper',
            'incoming-sessions',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-crypto-ssh-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_ssh_oper',
            is_config=False,
        ),
    },
    'Ssh.Session.History' : {
        'meta_info' : _MetaInfoClass('Ssh.Session.History', REFERENCE_CLASS,
            '''SSH session history information''',
            False, 
            [
            _MetaInfoClassMember('incoming-sessions', REFERENCE_CLASS, 'IncomingSessions', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_ssh_oper', 'Ssh.Session.History.IncomingSessions',
                [], [],
                '''                List of incoming sessions
                ''',
                'incoming_sessions',
                'Cisco-IOS-XR-crypto-ssh-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-crypto-ssh-oper',
            'history',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-crypto-ssh-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_ssh_oper',
            is_config=False,
        ),
    },
    'Ssh.Session.Detail.IncomingSessions.SessionDetailInfo.NextSession' : {
        'meta_info' : _MetaInfoClass('Ssh.Session.Detail.IncomingSessions.SessionDetailInfo.NextSession', REFERENCE_CLASS,
            '''next session''',
            False, 
            [
            ],
            'Cisco-IOS-XR-crypto-ssh-oper',
            'next-session',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-crypto-ssh-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_ssh_oper',
            is_config=False,
        ),
    },
    'Ssh.Session.Detail.IncomingSessions.SessionDetailInfo' : {
        'meta_info' : _MetaInfoClass('Ssh.Session.Detail.IncomingSessions.SessionDetailInfo', REFERENCE_LIST,
            '''session detail info''',
            False, 
            [
            _MetaInfoClassMember('next-session', REFERENCE_CLASS, 'NextSession', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_ssh_oper', 'Ssh.Session.Detail.IncomingSessions.SessionDetailInfo.NextSession',
                [], [],
                '''                next session
                ''',
                'next_session',
                'Cisco-IOS-XR-crypto-ssh-oper', False, is_config=False),
            _MetaInfoClassMember('session-id', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                Session ID
                ''',
                'session_id',
                'Cisco-IOS-XR-crypto-ssh-oper', False, is_config=False),
            _MetaInfoClassMember('key-exchange', REFERENCE_ENUM_CLASS, 'KexName', 'Kex-name',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_ssh_oper', 'KexName',
                [], [],
                '''                Key exchange name
                ''',
                'key_exchange',
                'Cisco-IOS-XR-crypto-ssh-oper', False, is_config=False),
            _MetaInfoClassMember('public-key', REFERENCE_ENUM_CLASS, 'Hostkey', 'Hostkey',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_ssh_oper', 'Hostkey',
                [], [],
                '''                Host key algorithm
                ''',
                'public_key',
                'Cisco-IOS-XR-crypto-ssh-oper', False, is_config=False),
            _MetaInfoClassMember('in-cipher', REFERENCE_ENUM_CLASS, 'Cipher', 'Cipher',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_ssh_oper', 'Cipher',
                [], [],
                '''                In cipher algorithm
                ''',
                'in_cipher',
                'Cisco-IOS-XR-crypto-ssh-oper', False, is_config=False),
            _MetaInfoClassMember('out-cipher', REFERENCE_ENUM_CLASS, 'Cipher', 'Cipher',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_ssh_oper', 'Cipher',
                [], [],
                '''                Out cipher algorithm
                ''',
                'out_cipher',
                'Cisco-IOS-XR-crypto-ssh-oper', False, is_config=False),
            _MetaInfoClassMember('in-mac', REFERENCE_ENUM_CLASS, 'Mac', 'Mac',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_ssh_oper', 'Mac',
                [], [],
                '''                In MAC
                ''',
                'in_mac',
                'Cisco-IOS-XR-crypto-ssh-oper', False, is_config=False),
            _MetaInfoClassMember('out-mac', REFERENCE_ENUM_CLASS, 'Mac', 'Mac',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_ssh_oper', 'Mac',
                [], [],
                '''                Out MAC
                ''',
                'out_mac',
                'Cisco-IOS-XR-crypto-ssh-oper', False, is_config=False),
            _MetaInfoClassMember('start-time', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                session start time
                ''',
                'start_time',
                'Cisco-IOS-XR-crypto-ssh-oper', False, is_config=False),
            _MetaInfoClassMember('end-time', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                session end time
                ''',
                'end_time',
                'Cisco-IOS-XR-crypto-ssh-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-crypto-ssh-oper',
            'session-detail-info',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-crypto-ssh-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_ssh_oper',
            is_config=False,
        ),
    },
    'Ssh.Session.Detail.IncomingSessions' : {
        'meta_info' : _MetaInfoClass('Ssh.Session.Detail.IncomingSessions', REFERENCE_CLASS,
            '''List of incoming sessions''',
            False, 
            [
            _MetaInfoClassMember('session-detail-info', REFERENCE_LIST, 'SessionDetailInfo', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_ssh_oper', 'Ssh.Session.Detail.IncomingSessions.SessionDetailInfo',
                [], [],
                '''                session detail info
                ''',
                'session_detail_info',
                'Cisco-IOS-XR-crypto-ssh-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-crypto-ssh-oper',
            'incoming-sessions',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-crypto-ssh-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_ssh_oper',
            is_config=False,
        ),
    },
    'Ssh.Session.Detail.OutgoingConnections.SessionDetailInfo.NextSession' : {
        'meta_info' : _MetaInfoClass('Ssh.Session.Detail.OutgoingConnections.SessionDetailInfo.NextSession', REFERENCE_CLASS,
            '''next session''',
            False, 
            [
            ],
            'Cisco-IOS-XR-crypto-ssh-oper',
            'next-session',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-crypto-ssh-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_ssh_oper',
            is_config=False,
        ),
    },
    'Ssh.Session.Detail.OutgoingConnections.SessionDetailInfo' : {
        'meta_info' : _MetaInfoClass('Ssh.Session.Detail.OutgoingConnections.SessionDetailInfo', REFERENCE_LIST,
            '''session detail info''',
            False, 
            [
            _MetaInfoClassMember('next-session', REFERENCE_CLASS, 'NextSession', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_ssh_oper', 'Ssh.Session.Detail.OutgoingConnections.SessionDetailInfo.NextSession',
                [], [],
                '''                next session
                ''',
                'next_session',
                'Cisco-IOS-XR-crypto-ssh-oper', False, is_config=False),
            _MetaInfoClassMember('session-id', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                Session ID
                ''',
                'session_id',
                'Cisco-IOS-XR-crypto-ssh-oper', False, is_config=False),
            _MetaInfoClassMember('key-exchange', REFERENCE_ENUM_CLASS, 'KexName', 'Kex-name',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_ssh_oper', 'KexName',
                [], [],
                '''                Key exchange name
                ''',
                'key_exchange',
                'Cisco-IOS-XR-crypto-ssh-oper', False, is_config=False),
            _MetaInfoClassMember('public-key', REFERENCE_ENUM_CLASS, 'Hostkey', 'Hostkey',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_ssh_oper', 'Hostkey',
                [], [],
                '''                Host key algorithm
                ''',
                'public_key',
                'Cisco-IOS-XR-crypto-ssh-oper', False, is_config=False),
            _MetaInfoClassMember('in-cipher', REFERENCE_ENUM_CLASS, 'Cipher', 'Cipher',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_ssh_oper', 'Cipher',
                [], [],
                '''                In cipher algorithm
                ''',
                'in_cipher',
                'Cisco-IOS-XR-crypto-ssh-oper', False, is_config=False),
            _MetaInfoClassMember('out-cipher', REFERENCE_ENUM_CLASS, 'Cipher', 'Cipher',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_ssh_oper', 'Cipher',
                [], [],
                '''                Out cipher algorithm
                ''',
                'out_cipher',
                'Cisco-IOS-XR-crypto-ssh-oper', False, is_config=False),
            _MetaInfoClassMember('in-mac', REFERENCE_ENUM_CLASS, 'Mac', 'Mac',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_ssh_oper', 'Mac',
                [], [],
                '''                In MAC
                ''',
                'in_mac',
                'Cisco-IOS-XR-crypto-ssh-oper', False, is_config=False),
            _MetaInfoClassMember('out-mac', REFERENCE_ENUM_CLASS, 'Mac', 'Mac',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_ssh_oper', 'Mac',
                [], [],
                '''                Out MAC
                ''',
                'out_mac',
                'Cisco-IOS-XR-crypto-ssh-oper', False, is_config=False),
            _MetaInfoClassMember('start-time', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                session start time
                ''',
                'start_time',
                'Cisco-IOS-XR-crypto-ssh-oper', False, is_config=False),
            _MetaInfoClassMember('end-time', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                session end time
                ''',
                'end_time',
                'Cisco-IOS-XR-crypto-ssh-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-crypto-ssh-oper',
            'session-detail-info',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-crypto-ssh-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_ssh_oper',
            is_config=False,
        ),
    },
    'Ssh.Session.Detail.OutgoingConnections' : {
        'meta_info' : _MetaInfoClass('Ssh.Session.Detail.OutgoingConnections', REFERENCE_CLASS,
            '''List of outgoing connections''',
            False, 
            [
            _MetaInfoClassMember('session-detail-info', REFERENCE_LIST, 'SessionDetailInfo', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_ssh_oper', 'Ssh.Session.Detail.OutgoingConnections.SessionDetailInfo',
                [], [],
                '''                session detail info
                ''',
                'session_detail_info',
                'Cisco-IOS-XR-crypto-ssh-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-crypto-ssh-oper',
            'outgoing-connections',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-crypto-ssh-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_ssh_oper',
            is_config=False,
        ),
    },
    'Ssh.Session.Detail' : {
        'meta_info' : _MetaInfoClass('Ssh.Session.Detail', REFERENCE_CLASS,
            '''SSH session detail information''',
            False, 
            [
            _MetaInfoClassMember('incoming-sessions', REFERENCE_CLASS, 'IncomingSessions', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_ssh_oper', 'Ssh.Session.Detail.IncomingSessions',
                [], [],
                '''                List of incoming sessions
                ''',
                'incoming_sessions',
                'Cisco-IOS-XR-crypto-ssh-oper', False, is_config=False),
            _MetaInfoClassMember('outgoing-connections', REFERENCE_CLASS, 'OutgoingConnections', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_ssh_oper', 'Ssh.Session.Detail.OutgoingConnections',
                [], [],
                '''                List of outgoing connections
                ''',
                'outgoing_connections',
                'Cisco-IOS-XR-crypto-ssh-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-crypto-ssh-oper',
            'detail',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-crypto-ssh-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_ssh_oper',
            is_config=False,
        ),
    },
    'Ssh.Session' : {
        'meta_info' : _MetaInfoClass('Ssh.Session', REFERENCE_CLASS,
            '''Crypto SSH session''',
            False, 
            [
            _MetaInfoClassMember('rekey', REFERENCE_CLASS, 'Rekey', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_ssh_oper', 'Ssh.Session.Rekey',
                [], [],
                '''                SSH session rekey information
                ''',
                'rekey',
                'Cisco-IOS-XR-crypto-ssh-oper', False, is_config=False),
            _MetaInfoClassMember('history-detail', REFERENCE_CLASS, 'HistoryDetail', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_ssh_oper', 'Ssh.Session.HistoryDetail',
                [], [],
                '''                SSH session history detail information
                ''',
                'history_detail',
                'Cisco-IOS-XR-crypto-ssh-oper', False, is_config=False),
            _MetaInfoClassMember('brief', REFERENCE_CLASS, 'Brief', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_ssh_oper', 'Ssh.Session.Brief',
                [], [],
                '''                SSH session brief information
                ''',
                'brief',
                'Cisco-IOS-XR-crypto-ssh-oper', False, is_config=False),
            _MetaInfoClassMember('history', REFERENCE_CLASS, 'History', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_ssh_oper', 'Ssh.Session.History',
                [], [],
                '''                SSH session history information
                ''',
                'history',
                'Cisco-IOS-XR-crypto-ssh-oper', False, is_config=False),
            _MetaInfoClassMember('detail', REFERENCE_CLASS, 'Detail', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_ssh_oper', 'Ssh.Session.Detail',
                [], [],
                '''                SSH session detail information
                ''',
                'detail',
                'Cisco-IOS-XR-crypto-ssh-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-crypto-ssh-oper',
            'session',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-crypto-ssh-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_ssh_oper',
            is_config=False,
        ),
    },
    'Ssh.Server' : {
        'meta_info' : _MetaInfoClass('Ssh.Server', REFERENCE_CLASS,
            '''SSH server parameters''',
            False, 
            [
            _MetaInfoClassMember('version', ATTRIBUTE, 'str', 'string',
                None, None,
                [(0, 10)], [],
                '''                Version
                ''',
                'version',
                'Cisco-IOS-XR-crypto-ssh-oper', False, is_config=False),
            _MetaInfoClassMember('port', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                SSH Port
                ''',
                'port',
                'Cisco-IOS-XR-crypto-ssh-oper', False, is_config=False),
            _MetaInfoClassMember('vrf', ATTRIBUTE, 'str', 'string',
                None, None,
                [(0, 500)], [],
                '''                Vrfs and acls
                ''',
                'vrf',
                'Cisco-IOS-XR-crypto-ssh-oper', False, is_config=False),
            _MetaInfoClassMember('netconfport', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                Netconf Port
                ''',
                'netconfport',
                'Cisco-IOS-XR-crypto-ssh-oper', False, is_config=False),
            _MetaInfoClassMember('netconfvrf', ATTRIBUTE, 'str', 'string',
                None, None,
                [(0, 500)], [],
                '''                Netconf vrfs and acls
                ''',
                'netconfvrf',
                'Cisco-IOS-XR-crypto-ssh-oper', False, is_config=False),
            _MetaInfoClassMember('netconfver', ATTRIBUTE, 'str', 'string',
                None, None,
                [(0, 10)], [],
                '''                Netconf Version
                ''',
                'netconfver',
                'Cisco-IOS-XR-crypto-ssh-oper', False, is_config=False),
            _MetaInfoClassMember('hostkeyalgo', ATTRIBUTE, 'str', 'string',
                None, None,
                [(0, 200)], [],
                '''                Hostkey algorithms
                ''',
                'hostkeyalgo',
                'Cisco-IOS-XR-crypto-ssh-oper', False, is_config=False),
            _MetaInfoClassMember('kexalgo', ATTRIBUTE, 'str', 'string',
                None, None,
                [(0, 200)], [],
                '''                Key exchange algorithms
                ''',
                'kexalgo',
                'Cisco-IOS-XR-crypto-ssh-oper', False, is_config=False),
            _MetaInfoClassMember('cipheralgo', ATTRIBUTE, 'str', 'string',
                None, None,
                [(0, 200)], [],
                '''                Encryption algorithms
                ''',
                'cipheralgo',
                'Cisco-IOS-XR-crypto-ssh-oper', False, is_config=False),
            _MetaInfoClassMember('macalgo', ATTRIBUTE, 'str', 'string',
                None, None,
                [(0, 200)], [],
                '''                Mac algorithms
                ''',
                'macalgo',
                'Cisco-IOS-XR-crypto-ssh-oper', False, is_config=False),
            _MetaInfoClassMember('backupserver', ATTRIBUTE, 'str', 'string',
                None, None,
                [(0, 100)], [],
                '''                Backup SSH server
                ''',
                'backupserver',
                'Cisco-IOS-XR-crypto-ssh-oper', False, is_config=False),
            _MetaInfoClassMember('dscp', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                Dscp
                ''',
                'dscp',
                'Cisco-IOS-XR-crypto-ssh-oper', False, is_config=False),
            _MetaInfoClassMember('ratelimit', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                ratelimit
                ''',
                'ratelimit',
                'Cisco-IOS-XR-crypto-ssh-oper', False, is_config=False),
            _MetaInfoClassMember('sessionlimit', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                session limit
                ''',
                'sessionlimit',
                'Cisco-IOS-XR-crypto-ssh-oper', False, is_config=False),
            _MetaInfoClassMember('rekeytime', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                Rekey Time
                ''',
                'rekeytime',
                'Cisco-IOS-XR-crypto-ssh-oper', False, is_config=False),
            _MetaInfoClassMember('rekeyvolume', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                Rekey Volume
                ''',
                'rekeyvolume',
                'Cisco-IOS-XR-crypto-ssh-oper', False, is_config=False),
            _MetaInfoClassMember('windowscalefactor', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                Window scale factor
                ''',
                'windowscalefactor',
                'Cisco-IOS-XR-crypto-ssh-oper', False, is_config=False),
            _MetaInfoClassMember('passwordauthen', ATTRIBUTE, 'bool', 'boolean',
                None, None,
                [], [],
                '''                Password Authentication support
                ''',
                'passwordauthen',
                'Cisco-IOS-XR-crypto-ssh-oper', False, is_config=False),
            _MetaInfoClassMember('keyboardinteractiveauthen', ATTRIBUTE, 'bool', 'boolean',
                None, None,
                [], [],
                '''                Pubkey Authentication support
                ''',
                'keyboardinteractiveauthen',
                'Cisco-IOS-XR-crypto-ssh-oper', False, is_config=False),
            _MetaInfoClassMember('pubkeyauthen', ATTRIBUTE, 'bool', 'boolean',
                None, None,
                [], [],
                '''                Pubkey Authentication support
                ''',
                'pubkeyauthen',
                'Cisco-IOS-XR-crypto-ssh-oper', False, is_config=False),
            _MetaInfoClassMember('certificateauthen', ATTRIBUTE, 'bool', 'boolean',
                None, None,
                [], [],
                '''                Certificate based Authentication support
                ''',
                'certificateauthen',
                'Cisco-IOS-XR-crypto-ssh-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-crypto-ssh-oper',
            'server',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-crypto-ssh-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_ssh_oper',
            is_config=False,
        ),
    },
    'Ssh' : {
        'meta_info' : _MetaInfoClass('Ssh', REFERENCE_CLASS,
            '''ssh''',
            False, 
            [
            _MetaInfoClassMember('session', REFERENCE_CLASS, 'Session', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_ssh_oper', 'Ssh.Session',
                [], [],
                '''                Crypto SSH session
                ''',
                'session',
                'Cisco-IOS-XR-crypto-ssh-oper', False, is_config=False),
            _MetaInfoClassMember('server', REFERENCE_CLASS, 'Server', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_ssh_oper', 'Ssh.Server',
                [], [],
                '''                SSH server parameters
                ''',
                'server',
                'Cisco-IOS-XR-crypto-ssh-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-crypto-ssh-oper',
            'ssh',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-crypto-ssh-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_crypto_ssh_oper',
            is_config=False,
        ),
    },
}
_meta_table['Ssh1.Kex.Nodes.Node.IncomingSessions.SessionDetailInfo.NextSession']['meta_info'].parent =_meta_table['Ssh1.Kex.Nodes.Node.IncomingSessions.SessionDetailInfo']['meta_info']
_meta_table['Ssh1.Kex.Nodes.Node.IncomingSessions.SessionDetailInfo']['meta_info'].parent =_meta_table['Ssh1.Kex.Nodes.Node.IncomingSessions']['meta_info']
_meta_table['Ssh1.Kex.Nodes.Node.OutgoingConnections.SessionDetailInfo.NextSession']['meta_info'].parent =_meta_table['Ssh1.Kex.Nodes.Node.OutgoingConnections.SessionDetailInfo']['meta_info']
_meta_table['Ssh1.Kex.Nodes.Node.OutgoingConnections.SessionDetailInfo']['meta_info'].parent =_meta_table['Ssh1.Kex.Nodes.Node.OutgoingConnections']['meta_info']
_meta_table['Ssh1.Kex.Nodes.Node.IncomingSessions']['meta_info'].parent =_meta_table['Ssh1.Kex.Nodes.Node']['meta_info']
_meta_table['Ssh1.Kex.Nodes.Node.OutgoingConnections']['meta_info'].parent =_meta_table['Ssh1.Kex.Nodes.Node']['meta_info']
_meta_table['Ssh1.Kex.Nodes.Node']['meta_info'].parent =_meta_table['Ssh1.Kex.Nodes']['meta_info']
_meta_table['Ssh1.Kex.Nodes']['meta_info'].parent =_meta_table['Ssh1.Kex']['meta_info']
_meta_table['Ssh1.Kex']['meta_info'].parent =_meta_table['Ssh1']['meta_info']
_meta_table['Ssh.Session.Rekey.IncomingSessions.SessionRekeyInfo.NextSession']['meta_info'].parent =_meta_table['Ssh.Session.Rekey.IncomingSessions.SessionRekeyInfo']['meta_info']
_meta_table['Ssh.Session.Rekey.IncomingSessions.SessionRekeyInfo']['meta_info'].parent =_meta_table['Ssh.Session.Rekey.IncomingSessions']['meta_info']
_meta_table['Ssh.Session.Rekey.OutgoingConnections.SessionRekeyInfo.NextSession']['meta_info'].parent =_meta_table['Ssh.Session.Rekey.OutgoingConnections.SessionRekeyInfo']['meta_info']
_meta_table['Ssh.Session.Rekey.OutgoingConnections.SessionRekeyInfo']['meta_info'].parent =_meta_table['Ssh.Session.Rekey.OutgoingConnections']['meta_info']
_meta_table['Ssh.Session.Rekey.IncomingSessions']['meta_info'].parent =_meta_table['Ssh.Session.Rekey']['meta_info']
_meta_table['Ssh.Session.Rekey.OutgoingConnections']['meta_info'].parent =_meta_table['Ssh.Session.Rekey']['meta_info']
_meta_table['Ssh.Session.HistoryDetail.IncomingSessions.SessionDetailInfo.NextSession']['meta_info'].parent =_meta_table['Ssh.Session.HistoryDetail.IncomingSessions.SessionDetailInfo']['meta_info']
_meta_table['Ssh.Session.HistoryDetail.IncomingSessions.SessionDetailInfo']['meta_info'].parent =_meta_table['Ssh.Session.HistoryDetail.IncomingSessions']['meta_info']
_meta_table['Ssh.Session.HistoryDetail.OutgoingConnections.SessionDetailInfo.NextSession']['meta_info'].parent =_meta_table['Ssh.Session.HistoryDetail.OutgoingConnections.SessionDetailInfo']['meta_info']
_meta_table['Ssh.Session.HistoryDetail.OutgoingConnections.SessionDetailInfo']['meta_info'].parent =_meta_table['Ssh.Session.HistoryDetail.OutgoingConnections']['meta_info']
_meta_table['Ssh.Session.HistoryDetail.IncomingSessions']['meta_info'].parent =_meta_table['Ssh.Session.HistoryDetail']['meta_info']
_meta_table['Ssh.Session.HistoryDetail.OutgoingConnections']['meta_info'].parent =_meta_table['Ssh.Session.HistoryDetail']['meta_info']
_meta_table['Ssh.Session.Brief.IncomingSessions.SessionBriefInfo.NextSession']['meta_info'].parent =_meta_table['Ssh.Session.Brief.IncomingSessions.SessionBriefInfo']['meta_info']
_meta_table['Ssh.Session.Brief.IncomingSessions.SessionBriefInfo.McInfo']['meta_info'].parent =_meta_table['Ssh.Session.Brief.IncomingSessions.SessionBriefInfo']['meta_info']
_meta_table['Ssh.Session.Brief.IncomingSessions.SessionBriefInfo']['meta_info'].parent =_meta_table['Ssh.Session.Brief.IncomingSessions']['meta_info']
_meta_table['Ssh.Session.Brief.OutgoingSessions.SessionBriefInfo.NextSession']['meta_info'].parent =_meta_table['Ssh.Session.Brief.OutgoingSessions.SessionBriefInfo']['meta_info']
_meta_table['Ssh.Session.Brief.OutgoingSessions.SessionBriefInfo.McInfo']['meta_info'].parent =_meta_table['Ssh.Session.Brief.OutgoingSessions.SessionBriefInfo']['meta_info']
_meta_table['Ssh.Session.Brief.OutgoingSessions.SessionBriefInfo']['meta_info'].parent =_meta_table['Ssh.Session.Brief.OutgoingSessions']['meta_info']
_meta_table['Ssh.Session.Brief.IncomingSessions']['meta_info'].parent =_meta_table['Ssh.Session.Brief']['meta_info']
_meta_table['Ssh.Session.Brief.OutgoingSessions']['meta_info'].parent =_meta_table['Ssh.Session.Brief']['meta_info']
_meta_table['Ssh.Session.History.IncomingSessions.SessionHistoryInfo.NextSession']['meta_info'].parent =_meta_table['Ssh.Session.History.IncomingSessions.SessionHistoryInfo']['meta_info']
_meta_table['Ssh.Session.History.IncomingSessions.SessionHistoryInfo.McInfo']['meta_info'].parent =_meta_table['Ssh.Session.History.IncomingSessions.SessionHistoryInfo']['meta_info']
_meta_table['Ssh.Session.History.IncomingSessions.SessionHistoryInfo']['meta_info'].parent =_meta_table['Ssh.Session.History.IncomingSessions']['meta_info']
_meta_table['Ssh.Session.History.IncomingSessions']['meta_info'].parent =_meta_table['Ssh.Session.History']['meta_info']
_meta_table['Ssh.Session.Detail.IncomingSessions.SessionDetailInfo.NextSession']['meta_info'].parent =_meta_table['Ssh.Session.Detail.IncomingSessions.SessionDetailInfo']['meta_info']
_meta_table['Ssh.Session.Detail.IncomingSessions.SessionDetailInfo']['meta_info'].parent =_meta_table['Ssh.Session.Detail.IncomingSessions']['meta_info']
_meta_table['Ssh.Session.Detail.OutgoingConnections.SessionDetailInfo.NextSession']['meta_info'].parent =_meta_table['Ssh.Session.Detail.OutgoingConnections.SessionDetailInfo']['meta_info']
_meta_table['Ssh.Session.Detail.OutgoingConnections.SessionDetailInfo']['meta_info'].parent =_meta_table['Ssh.Session.Detail.OutgoingConnections']['meta_info']
_meta_table['Ssh.Session.Detail.IncomingSessions']['meta_info'].parent =_meta_table['Ssh.Session.Detail']['meta_info']
_meta_table['Ssh.Session.Detail.OutgoingConnections']['meta_info'].parent =_meta_table['Ssh.Session.Detail']['meta_info']
_meta_table['Ssh.Session.Rekey']['meta_info'].parent =_meta_table['Ssh.Session']['meta_info']
_meta_table['Ssh.Session.HistoryDetail']['meta_info'].parent =_meta_table['Ssh.Session']['meta_info']
_meta_table['Ssh.Session.Brief']['meta_info'].parent =_meta_table['Ssh.Session']['meta_info']
_meta_table['Ssh.Session.History']['meta_info'].parent =_meta_table['Ssh.Session']['meta_info']
_meta_table['Ssh.Session.Detail']['meta_info'].parent =_meta_table['Ssh.Session']['meta_info']
_meta_table['Ssh.Session']['meta_info'].parent =_meta_table['Ssh']['meta_info']
_meta_table['Ssh.Server']['meta_info'].parent =_meta_table['Ssh']['meta_info']
