
'''
This is auto-generated file,
which includes metadata for module Cisco_IOS_XR_sysadmin_ethsw_esdma_types
'''

from ydk._core._dm_meta_info import _MetaInfoClassMember, _MetaInfoClass, _MetaInfoEnum
from ydk._core._dm_meta_info import ATTRIBUTE, REFERENCE_LIST, REFERENCE_LEAFLIST, REFERENCE_BITS, REFERENCE_UNION
from ydk._core._dm_meta_info import REFERENCE_CLASS, REFERENCE_IDENTITY_CLASS, REFERENCE_ENUM_CLASS, ANYXML_CLASS
from ydk._core._importer import _yang_ns

_meta_table = {
    'EsdmaRackTypeEnum' : _MetaInfoEnum('EsdmaRackTypeEnum',
        'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_ethsw_esdma_types', 'EsdmaRackTypeEnum',
        '''The valid chassis types supported supported in Sysadmin.''',
        {
            'Unknown':'Unknown',
            'FCC':'FCC',
            'LCC':'LCC',
            'BSC':'BSC',
            'COMPUTE':'COMPUTE',
        }, 'Cisco-IOS-XR-sysadmin-ethsw-esdma-types', _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-sysadmin-ethsw-esdma-types']),
    'EsdmaRackNumEnum' : _MetaInfoEnum('EsdmaRackNumEnum',
        'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_ethsw_esdma_types', 'EsdmaRackNumEnum',
        '''The valid rack numbers supported in Sysadmin.''',
        {
            '0':'Y_0',
            '1':'Y_1',
            '2':'Y_2',
            '3':'Y_3',
            '4':'Y_4',
            '5':'Y_5',
            '6':'Y_6',
            '7':'Y_7',
            '8':'Y_8',
            '9':'Y_9',
            '10':'Y_10',
            '11':'Y_11',
            '12':'Y_12',
            '13':'Y_13',
            '14':'Y_14',
            '15':'Y_15',
            'F0':'F0',
            'F1':'F1',
            'F2':'F2',
            'F3':'F3',
            'B0':'B0',
            'B1':'B1',
        }, 'Cisco-IOS-XR-sysadmin-ethsw-esdma-types', _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-sysadmin-ethsw-esdma-types']),
    'EsdmaCpu' : _MetaInfoEnum('EsdmaCpu',
        'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_ethsw_esdma_types', 'EsdmaCpu',
        '''The set of CPU enumerations that have control plane Ethernet switches or run the MLAP protocol.''',
        {
            'Unknown':'Unknown',
            'RP0':'RP0',
            'RP1':'RP1',
            'SC0':'SC0',
            'SC1':'SC1',
            'LC0':'LC0',
            'LC1':'LC1',
            'LC2':'LC2',
            'LC3':'LC3',
            'LC4':'LC4',
            'LC5':'LC5',
            'LC6':'LC6',
            'LC7':'LC7',
            'LC8':'LC8',
            'LC9':'LC9',
            'LC10':'LC10',
            'LC11':'LC11',
            'LC12':'LC12',
            'LC13':'LC13',
            'LC14':'LC14',
            'LC15':'LC15',
            'LC16':'LC16',
            'LC17':'LC17',
            'LC18':'LC18',
            'LC19':'LC19',
            'FC0':'FC0',
            'FC1':'FC1',
            'FC2':'FC2',
            'FC3':'FC3',
            'FC4':'FC4',
            'FC5':'FC5',
            'CB0':'CB0',
        }, 'Cisco-IOS-XR-sysadmin-ethsw-esdma-types', _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-sysadmin-ethsw-esdma-types']),
    'EsdmaSwitchTypeEnum' : _MetaInfoEnum('EsdmaSwitchTypeEnum',
        'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_ethsw_esdma_types', 'EsdmaSwitchTypeEnum',
        '''The list of Ethernet switch types''',
        {
            'RP-SW':'RP_SW',
            'SC-SW':'SC_SW',
            'LC-SW':'LC_SW',
            'F-SW0':'F_SW0',
            'F-SW1':'F_SW1',
            'FC-SW':'FC_SW',
            'EOBC-SW':'EOBC_SW',
            'EPC-SW':'EPC_SW',
            'CB-SW':'CB_SW',
            'Unknown':'Unknown',
            'RP-SW1':'RP_SW1',
        }, 'Cisco-IOS-XR-sysadmin-ethsw-esdma-types', _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-sysadmin-ethsw-esdma-types']),
    'EsdmaSwitchYesNoEnum' : _MetaInfoEnum('EsdmaSwitchYesNoEnum',
        'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_ethsw_esdma_types', 'EsdmaSwitchYesNoEnum',
        ''' ''',
        {
            'Yes':'Yes',
            'No':'No',
        }, 'Cisco-IOS-XR-sysadmin-ethsw-esdma-types', _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-sysadmin-ethsw-esdma-types']),
    'EsdmaSwitchSfpInsertedEnum' : _MetaInfoEnum('EsdmaSwitchSfpInsertedEnum',
        'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_ethsw_esdma_types', 'EsdmaSwitchSfpInsertedEnum',
        ''' ''',
        {
            'Unknown':'Unknown',
            'Yes':'Yes',
            'No':'No',
            'Failed':'Failed',
        }, 'Cisco-IOS-XR-sysadmin-ethsw-esdma-types', _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-sysadmin-ethsw-esdma-types']),
    'EsdmaSwitchSfpControllerEnum' : _MetaInfoEnum('EsdmaSwitchSfpControllerEnum',
        'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_ethsw_esdma_types', 'EsdmaSwitchSfpControllerEnum',
        ''' ''',
        {
            'Unknown':'Unknown',
            'Switch':'Switch',
            'PHY':'PHY',
        }, 'Cisco-IOS-XR-sysadmin-ethsw-esdma-types', _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-sysadmin-ethsw-esdma-types']),
    'EsdmaSwitchSfpTranceiverTypeEnum' : _MetaInfoEnum('EsdmaSwitchSfpTranceiverTypeEnum',
        'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_ethsw_esdma_types', 'EsdmaSwitchSfpTranceiverTypeEnum',
        ''' ''',
        {
            'Unspecified':'Unspecified',
            'SFP':'SFP',
            'QSFP':'QSFP',
            'Unknown':'Unknown',
        }, 'Cisco-IOS-XR-sysadmin-ethsw-esdma-types', _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-sysadmin-ethsw-esdma-types']),
    'EsdmaSfpEncodingEnum' : _MetaInfoEnum('EsdmaSfpEncodingEnum',
        'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_ethsw_esdma_types', 'EsdmaSfpEncodingEnum',
        ''' ''',
        {
            'Unspecified':'Unspecified',
            '8B/10B':'Y_8B__FWD_SLASH__10B',
            '4B/5B':'Y_4B__FWD_SLASH__5B',
            'NRZ':'NRZ',
            'Manchester':'Manchester',
            'SONET Scrambled':'SONET_Scrambled',
            '64B/66B':'Y_64B__FWD_SLASH__66B',
            'Unknown':'Unknown',
        }, 'Cisco-IOS-XR-sysadmin-ethsw-esdma-types', _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-sysadmin-ethsw-esdma-types']),
    'EsdmaQsfpTransceiverEnum' : _MetaInfoEnum('EsdmaQsfpTransceiverEnum',
        'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_ethsw_esdma_types', 'EsdmaQsfpTransceiverEnum',
        ''' ''',
        {
            'QSFP-40G-LR4':'QSFP_40G_LR4',
            'QSFP-40G-SR4':'QSFP_40G_SR4',
            'QSFP-40G-CR4-Active':'QSFP_40G_CR4_Active',
            'QSFP-40G-CR4-Passive':'QSFP_40G_CR4_Passive',
            'Unknown':'Unknown',
        }, 'Cisco-IOS-XR-sysadmin-ethsw-esdma-types', _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-sysadmin-ethsw-esdma-types']),
    'EsdmaSwitchSfpTypeEnum' : _MetaInfoEnum('EsdmaSwitchSfpTypeEnum',
        'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_ethsw_esdma_types', 'EsdmaSwitchSfpTypeEnum',
        ''' ''',
        {
            'None':'None_',
            'SFP-10G-SR':'SFP_10G_SR',
            'SFP-10G-LR':'SFP_10G_LR',
            'SFP-10G-LRM':'SFP_10G_LRM',
            'SFP-1G-SX':'SFP_1G_SX',
            'SFP-1G-LX':'SFP_1G_LX',
            'SFP-1000Base-T':'SFP_1000Base_T',
            'SFP-40G-SR4':'SFP_40G_SR4',
            'SFP-40G-LR4':'SFP_40G_LR4',
            'Unsupported':'Unsupported',
        }, 'Cisco-IOS-XR-sysadmin-ethsw-esdma-types', _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-sysadmin-ethsw-esdma-types']),
    'EsdmaSwitchPortState' : _MetaInfoEnum('EsdmaSwitchPortState',
        'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_ethsw_esdma_types', 'EsdmaSwitchPortState',
        '''The switch port up and down states''',
        {
            'Unknown':'Unknown',
            'Test':'Test',
            'Down':'Down',
            'Up':'Up',
        }, 'Cisco-IOS-XR-sysadmin-ethsw-esdma-types', _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-sysadmin-ethsw-esdma-types']),
    'SwitchForwardingState' : _MetaInfoEnum('SwitchForwardingState',
        'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_ethsw_esdma_types', 'SwitchForwardingState',
        '''The set of switch port forwarding states''',
        {
            'Unknown':'Unknown',
            '-':'Y_',
            'Disabled':'Disabled',
            'Blocking':'Blocking',
            'Learning':'Learning',
            'Forwarding':'Forwarding',
        }, 'Cisco-IOS-XR-sysadmin-ethsw-esdma-types', _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-sysadmin-ethsw-esdma-types']),
    'EsdCirEirType' : _MetaInfoEnum('EsdCirEirType',
        'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_ethsw_esdma_types', 'EsdCirEirType',
        ''' ''',
        {
            'CIR':'CIR',
            'PIR':'PIR',
        }, 'Cisco-IOS-XR-sysadmin-ethsw-esdma-types', _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-sysadmin-ethsw-esdma-types']),
    'MlapEpType' : _MetaInfoEnum('MlapEpType',
        'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_ethsw_esdma_types', 'MlapEpType',
        ''' ''',
        {
            'Unknown':'Unknown',
            'RP':'RP',
            'SC':'SC',
            'FC':'FC',
            'LC':'LC',
            'F-SW':'F_SW',
            'CB':'CB',
        }, 'Cisco-IOS-XR-sysadmin-ethsw-esdma-types', _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-sysadmin-ethsw-esdma-types']),
    'MlapStateEnum' : _MetaInfoEnum('MlapStateEnum',
        'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_ethsw_esdma_types', 'MlapStateEnum',
        '''The set of enumerated values that MLAP uses to manage a port's protocol state''',
        {
            '-':'Y_',
            'Down':'Down',
            'Up':'Up',
            'Admin Down':'Admin_Down',
            'Do Not Use':'Do_Not_Use',
            'Invalid':'Invalid',
            'Active':'Active',
            'Standby':'Standby',
            'Rem Managed':'Rem_Managed',
        }, 'Cisco-IOS-XR-sysadmin-ethsw-esdma-types', _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-sysadmin-ethsw-esdma-types']),
    'MlapProtocolEnum' : _MetaInfoEnum('MlapProtocolEnum',
        'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_ethsw_esdma_types', 'MlapProtocolEnum',
        '''The types of MLAP protocol''',
        {
            'Internal':'Internal',
            'External':'External',
        }, 'Cisco-IOS-XR-sysadmin-ethsw-esdma-types', _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-sysadmin-ethsw-esdma-types']),
    'MlapTraceVerbosity' : _MetaInfoEnum('MlapTraceVerbosity',
        'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_ethsw_esdma_types', 'MlapTraceVerbosity',
        ''' ''',
        {
            'Off':'Off',
            'Low':'Low',
            'Medium':'Medium',
            'High':'High',
        }, 'Cisco-IOS-XR-sysadmin-ethsw-esdma-types', _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-sysadmin-ethsw-esdma-types']),
    'SwitchDataDirectionEnum' : _MetaInfoEnum('SwitchDataDirectionEnum',
        'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_ethsw_esdma_types', 'SwitchDataDirectionEnum',
        '''Switch data direction''',
        {
            '-':'Y_',
            'Both':'Both',
            'Rx':'Rx',
            'Tx':'Tx',
            'Unknown':'Unknown',
            'Invalid':'Invalid',
        }, 'Cisco-IOS-XR-sysadmin-ethsw-esdma-types', _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-sysadmin-ethsw-esdma-types']),
    'SwitchTableTypeEnum' : _MetaInfoEnum('SwitchTableTypeEnum',
        'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_ethsw_esdma_types', 'SwitchTableTypeEnum',
        ''' ''',
        {
            '-':'Y_',
            'Port':'Port',
            'VLAN':'VLAN',
            'TCAM':'TCAM',
            'Unknown':'Unknown',
        }, 'Cisco-IOS-XR-sysadmin-ethsw-esdma-types', _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-sysadmin-ethsw-esdma-types']),
    'SwitchMatchTypeEnum' : _MetaInfoEnum('SwitchMatchTypeEnum',
        'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_ethsw_esdma_types', 'SwitchMatchTypeEnum',
        ''' ''',
        {
            '-':'Y_',
            'Any':'Any',
            'Tagged':'Tagged',
            'Untagged':'Untagged',
            'Unknown':'Unknown',
        }, 'Cisco-IOS-XR-sysadmin-ethsw-esdma-types', _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-sysadmin-ethsw-esdma-types']),
    'SwitchActionTypeEnum' : _MetaInfoEnum('SwitchActionTypeEnum',
        'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_ethsw_esdma_types', 'SwitchActionTypeEnum',
        ''' ''',
        {
            '-':'Y_',
            'Translate':'Translate',
            'Remove Outer':'Remove_Outer',
            'Add Outer':'Add_Outer',
            'Drop':'Drop',
            'Forward':'Forward',
            'Unknown':'Unknown',
        }, 'Cisco-IOS-XR-sysadmin-ethsw-esdma-types', _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-sysadmin-ethsw-esdma-types']),
    'EsdmaSdrTrafficType' : _MetaInfoEnum('EsdmaSdrTrafficType',
        'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_ethsw_esdma_types', 'EsdmaSdrTrafficType',
        ''' ''',
        {
            'Unknown':'Unknown',
            'IPC':'IPC',
            'MgmtEth':'MgmtEth',
            'All':'All',
            'Invalid':'Invalid',
        }, 'Cisco-IOS-XR-sysadmin-ethsw-esdma-types', _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-sysadmin-ethsw-esdma-types']),
    'EsdmaTrunkMemberStatus' : _MetaInfoEnum('EsdmaTrunkMemberStatus',
        'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_ethsw_esdma_types', 'EsdmaTrunkMemberStatus',
        ''' ''',
        {
            'Disabled':'Disabled',
            'Enabled':'Enabled',
            '-':'Y_',
        }, 'Cisco-IOS-XR-sysadmin-ethsw-esdma-types', _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-sysadmin-ethsw-esdma-types']),
}
