
'''
This is auto-generated file,
which includes metadata for module Cisco_IOS_XR_infra_fti_oper
'''

from ydk._core._dm_meta_info import _MetaInfoClassMember, _MetaInfoClass, _MetaInfoEnum
from ydk._core._dm_meta_info import ATTRIBUTE, REFERENCE_LIST, REFERENCE_LEAFLIST, REFERENCE_BITS, REFERENCE_UNION
from ydk._core._dm_meta_info import REFERENCE_CLASS, REFERENCE_IDENTITY_CLASS, REFERENCE_ENUM_CLASS, ANYXML_CLASS
from ydk._core._importer import _yang_ns

_meta_table = {
    'FtiBagFabricPeerState' : _MetaInfoEnum('FtiBagFabricPeerState',
        'ydk.models.cisco_ios_xr.Cisco_IOS_XR_infra_fti_oper', 'FtiBagFabricPeerState',
        '''FTI Fabric Peer States''',
        {
            'fti-bag-fabric-peer-status-disconnected':'fti_bag_fabric_peer_status_disconnected',
            'fti-bag-fabric-peer-status-connecting':'fti_bag_fabric_peer_status_connecting',
            'fti-bag-fabric-peer-status-connected':'fti_bag_fabric_peer_status_connected',
            'fti-bag-fabric-peer-status-ready':'fti_bag_fabric_peer_status_ready',
            'fti-bag-fabric-peer-status-closing':'fti_bag_fabric_peer_status_closing',
        }, 'Cisco-IOS-XR-infra-fti-oper', _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-infra-fti-oper']),
    'FtiBagFabricState' : _MetaInfoEnum('FtiBagFabricState',
        'ydk.models.cisco_ios_xr.Cisco_IOS_XR_infra_fti_oper', 'FtiBagFabricState',
        '''FTI Fabric States''',
        {
            'fti-bag-fabric-state-active-down':'fti_bag_fabric_state_active_down',
            'fti-bag-fabric-state-active-degraded':'fti_bag_fabric_state_active_degraded',
            'fti-bag-fabric-state-active-healthy':'fti_bag_fabric_state_active_healthy',
            'fti-bag-fabric-state-inactive':'fti_bag_fabric_state_inactive',
        }, 'Cisco-IOS-XR-infra-fti-oper', _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-infra-fti-oper']),
    'FtiBagFabricConfigState' : _MetaInfoEnum('FtiBagFabricConfigState',
        'ydk.models.cisco_ios_xr.Cisco_IOS_XR_infra_fti_oper', 'FtiBagFabricConfigState',
        '''FTI Fabric Config States''',
        {
            'fti-bag-config-complete':'fti_bag_config_complete',
            'fti-bag-config-incomplete':'fti_bag_config_incomplete',
        }, 'Cisco-IOS-XR-infra-fti-oper', _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-infra-fti-oper']),
    'DciFabricInterconnect.OpflexSessionInfos.OpflexSessionInfo.PeerInfo' : {
        'meta_info' : _MetaInfoClass('DciFabricInterconnect.OpflexSessionInfos.OpflexSessionInfo.PeerInfo', REFERENCE_LIST,
            '''Fabric Per Peer Info''',
            False, 
            [
            _MetaInfoClassMember('peer-ip', ATTRIBUTE, 'str', 'inet:ipv4-address',
                None, None,
                [], [b'(([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])(%[\\p{N}\\p{L}]+)?'],
                '''                Peer IP
                ''',
                'peer_ip',
                'Cisco-IOS-XR-infra-fti-oper', False, is_config=False),
            _MetaInfoClassMember('peer-port', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                Peer Port
                ''',
                'peer_port',
                'Cisco-IOS-XR-infra-fti-oper', False, is_config=False),
            _MetaInfoClassMember('peer-state', REFERENCE_ENUM_CLASS, 'FtiBagFabricPeerState', 'Fti-bag-fabric-peer-state',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_infra_fti_oper', 'FtiBagFabricPeerState',
                [], [],
                '''                Peer State
                ''',
                'peer_state',
                'Cisco-IOS-XR-infra-fti-oper', False, is_config=False),
            _MetaInfoClassMember('last-upd-ts-peer-status', ATTRIBUTE, 'int', 'uint64',
                None, None,
                [('0', '18446744073709551615')], [],
                '''                Peer Status Last Update Timestamp
                ''',
                'last_upd_ts_peer_status',
                'Cisco-IOS-XR-infra-fti-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-infra-fti-oper',
            'peer-info',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-infra-fti-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_infra_fti_oper',
            is_config=False,
        ),
    },
    'DciFabricInterconnect.OpflexSessionInfos.OpflexSessionInfo' : {
        'meta_info' : _MetaInfoClass('DciFabricInterconnect.OpflexSessionInfos.OpflexSessionInfo', REFERENCE_LIST,
            '''FTI Opflex Session Info for a particular fabric''',
            False, 
            [
            _MetaInfoClassMember('id1', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('1000', '9999')], [],
                '''                fabric identifier
                ''',
                'id1',
                'Cisco-IOS-XR-infra-fti-oper', True, is_config=False),
            _MetaInfoClassMember('fabric-id', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                Fabric Id
                ''',
                'fabric_id',
                'Cisco-IOS-XR-infra-fti-oper', False, is_config=False),
            _MetaInfoClassMember('config-state', REFERENCE_ENUM_CLASS, 'FtiBagFabricConfigState', 'Fti-bag-fabric-config-state',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_infra_fti_oper', 'FtiBagFabricConfigState',
                [], [],
                '''                Config State
                ''',
                'config_state',
                'Cisco-IOS-XR-infra-fti-oper', False, is_config=False),
            _MetaInfoClassMember('last-upd-ts-config', ATTRIBUTE, 'int', 'uint64',
                None, None,
                [('0', '18446744073709551615')], [],
                '''                Config Last Update Timestamp
                ''',
                'last_upd_ts_config',
                'Cisco-IOS-XR-infra-fti-oper', False, is_config=False),
            _MetaInfoClassMember('fabric-state', REFERENCE_ENUM_CLASS, 'FtiBagFabricState', 'Fti-bag-fabric-state',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_infra_fti_oper', 'FtiBagFabricState',
                [], [],
                '''                Fabric State
                ''',
                'fabric_state',
                'Cisco-IOS-XR-infra-fti-oper', False, is_config=False),
            _MetaInfoClassMember('last-upd-ts-fabric', ATTRIBUTE, 'int', 'uint64',
                None, None,
                [('0', '18446744073709551615')], [],
                '''                Fabric Last Update Timestamp
                ''',
                'last_upd_ts_fabric',
                'Cisco-IOS-XR-infra-fti-oper', False, is_config=False),
            _MetaInfoClassMember('peer-info', REFERENCE_LIST, 'PeerInfo', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_infra_fti_oper', 'DciFabricInterconnect.OpflexSessionInfos.OpflexSessionInfo.PeerInfo',
                [], [],
                '''                Fabric Per Peer Info
                ''',
                'peer_info',
                'Cisco-IOS-XR-infra-fti-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-infra-fti-oper',
            'opflex-session-info',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-infra-fti-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_infra_fti_oper',
            is_config=False,
        ),
    },
    'DciFabricInterconnect.OpflexSessionInfos' : {
        'meta_info' : _MetaInfoClass('DciFabricInterconnect.OpflexSessionInfos', REFERENCE_CLASS,
            '''FTI Opflex Session Info for all fabrics''',
            False, 
            [
            _MetaInfoClassMember('opflex-session-info', REFERENCE_LIST, 'OpflexSessionInfo', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_infra_fti_oper', 'DciFabricInterconnect.OpflexSessionInfos.OpflexSessionInfo',
                [], [],
                '''                FTI Opflex Session Info for a particular fabric
                ''',
                'opflex_session_info',
                'Cisco-IOS-XR-infra-fti-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-infra-fti-oper',
            'opflex-session-infos',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-infra-fti-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_infra_fti_oper',
            is_config=False,
        ),
    },
    'DciFabricInterconnect.FabricVrfDbs.FabricVrfDb.FabricVrf.V4ImportRt' : {
        'meta_info' : _MetaInfoClass('DciFabricInterconnect.FabricVrfDbs.FabricVrfDb.FabricVrf.V4ImportRt', REFERENCE_LIST,
            '''V4 Import Route Targets''',
            False, 
            [
            _MetaInfoClassMember('rt-value', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                RT Value
                ''',
                'rt_value',
                'Cisco-IOS-XR-infra-fti-oper', False, is_config=False),
            _MetaInfoClassMember('rt-flags', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                RT Flags
                ''',
                'rt_flags',
                'Cisco-IOS-XR-infra-fti-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-infra-fti-oper',
            'v4-import-rt',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-infra-fti-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_infra_fti_oper',
            is_config=False,
        ),
    },
    'DciFabricInterconnect.FabricVrfDbs.FabricVrfDb.FabricVrf.V4ExportRt' : {
        'meta_info' : _MetaInfoClass('DciFabricInterconnect.FabricVrfDbs.FabricVrfDb.FabricVrf.V4ExportRt', REFERENCE_LIST,
            '''V4 Export Route Targets''',
            False, 
            [
            _MetaInfoClassMember('rt-value', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                RT Value
                ''',
                'rt_value',
                'Cisco-IOS-XR-infra-fti-oper', False, is_config=False),
            _MetaInfoClassMember('rt-flags', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                RT Flags
                ''',
                'rt_flags',
                'Cisco-IOS-XR-infra-fti-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-infra-fti-oper',
            'v4-export-rt',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-infra-fti-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_infra_fti_oper',
            is_config=False,
        ),
    },
    'DciFabricInterconnect.FabricVrfDbs.FabricVrfDb.FabricVrf.V6ImportRt' : {
        'meta_info' : _MetaInfoClass('DciFabricInterconnect.FabricVrfDbs.FabricVrfDb.FabricVrf.V6ImportRt', REFERENCE_LIST,
            '''V6 Import Route Targets''',
            False, 
            [
            _MetaInfoClassMember('rt-value', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                RT Value
                ''',
                'rt_value',
                'Cisco-IOS-XR-infra-fti-oper', False, is_config=False),
            _MetaInfoClassMember('rt-flags', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                RT Flags
                ''',
                'rt_flags',
                'Cisco-IOS-XR-infra-fti-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-infra-fti-oper',
            'v6-import-rt',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-infra-fti-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_infra_fti_oper',
            is_config=False,
        ),
    },
    'DciFabricInterconnect.FabricVrfDbs.FabricVrfDb.FabricVrf.V6ExportRt' : {
        'meta_info' : _MetaInfoClass('DciFabricInterconnect.FabricVrfDbs.FabricVrfDb.FabricVrf.V6ExportRt', REFERENCE_LIST,
            '''V6 Export Route Targets''',
            False, 
            [
            _MetaInfoClassMember('rt-value', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                RT Value
                ''',
                'rt_value',
                'Cisco-IOS-XR-infra-fti-oper', False, is_config=False),
            _MetaInfoClassMember('rt-flags', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                RT Flags
                ''',
                'rt_flags',
                'Cisco-IOS-XR-infra-fti-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-infra-fti-oper',
            'v6-export-rt',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-infra-fti-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_infra_fti_oper',
            is_config=False,
        ),
    },
    'DciFabricInterconnect.FabricVrfDbs.FabricVrfDb.FabricVrf' : {
        'meta_info' : _MetaInfoClass('DciFabricInterconnect.FabricVrfDbs.FabricVrfDb.FabricVrf', REFERENCE_LIST,
            '''Fabric VRFs''',
            False, 
            [
            _MetaInfoClassMember('fabric-vrf', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Fabric VRF
                ''',
                'fabric_vrf',
                'Cisco-IOS-XR-infra-fti-oper', False, is_config=False),
            _MetaInfoClassMember('dci-vrf', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Dci VRF
                ''',
                'dci_vrf',
                'Cisco-IOS-XR-infra-fti-oper', False, is_config=False),
            _MetaInfoClassMember('fabric-vrf-flags', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Fabric VRF Flags
                ''',
                'fabric_vrf_flags',
                'Cisco-IOS-XR-infra-fti-oper', False, is_config=False),
            _MetaInfoClassMember('v4-import-rt', REFERENCE_LIST, 'V4ImportRt', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_infra_fti_oper', 'DciFabricInterconnect.FabricVrfDbs.FabricVrfDb.FabricVrf.V4ImportRt',
                [], [],
                '''                V4 Import Route Targets
                ''',
                'v4_import_rt',
                'Cisco-IOS-XR-infra-fti-oper', False, is_config=False),
            _MetaInfoClassMember('v4-export-rt', REFERENCE_LIST, 'V4ExportRt', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_infra_fti_oper', 'DciFabricInterconnect.FabricVrfDbs.FabricVrfDb.FabricVrf.V4ExportRt',
                [], [],
                '''                V4 Export Route Targets
                ''',
                'v4_export_rt',
                'Cisco-IOS-XR-infra-fti-oper', False, is_config=False),
            _MetaInfoClassMember('v6-import-rt', REFERENCE_LIST, 'V6ImportRt', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_infra_fti_oper', 'DciFabricInterconnect.FabricVrfDbs.FabricVrfDb.FabricVrf.V6ImportRt',
                [], [],
                '''                V6 Import Route Targets
                ''',
                'v6_import_rt',
                'Cisco-IOS-XR-infra-fti-oper', False, is_config=False),
            _MetaInfoClassMember('v6-export-rt', REFERENCE_LIST, 'V6ExportRt', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_infra_fti_oper', 'DciFabricInterconnect.FabricVrfDbs.FabricVrfDb.FabricVrf.V6ExportRt',
                [], [],
                '''                V6 Export Route Targets
                ''',
                'v6_export_rt',
                'Cisco-IOS-XR-infra-fti-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-infra-fti-oper',
            'fabric-vrf',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-infra-fti-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_infra_fti_oper',
            is_config=False,
        ),
    },
    'DciFabricInterconnect.FabricVrfDbs.FabricVrfDb' : {
        'meta_info' : _MetaInfoClass('DciFabricInterconnect.FabricVrfDbs.FabricVrfDb', REFERENCE_LIST,
            '''FTI Fabric-VRF DB for a particular fabric''',
            False, 
            [
            _MetaInfoClassMember('id1', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('1000', '9999')], [],
                '''                fabric identifier
                ''',
                'id1',
                'Cisco-IOS-XR-infra-fti-oper', True, is_config=False),
            _MetaInfoClassMember('fabric-id', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                Fabric Id
                ''',
                'fabric_id',
                'Cisco-IOS-XR-infra-fti-oper', False, is_config=False),
            _MetaInfoClassMember('fabric-vrf', REFERENCE_LIST, 'FabricVrf', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_infra_fti_oper', 'DciFabricInterconnect.FabricVrfDbs.FabricVrfDb.FabricVrf',
                [], [],
                '''                Fabric VRFs
                ''',
                'fabric_vrf',
                'Cisco-IOS-XR-infra-fti-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-infra-fti-oper',
            'fabric-vrf-db',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-infra-fti-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_infra_fti_oper',
            is_config=False,
        ),
    },
    'DciFabricInterconnect.FabricVrfDbs' : {
        'meta_info' : _MetaInfoClass('DciFabricInterconnect.FabricVrfDbs', REFERENCE_CLASS,
            '''FTI Fabric-VRF DB for all fabrics''',
            False, 
            [
            _MetaInfoClassMember('fabric-vrf-db', REFERENCE_LIST, 'FabricVrfDb', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_infra_fti_oper', 'DciFabricInterconnect.FabricVrfDbs.FabricVrfDb',
                [], [],
                '''                FTI Fabric-VRF DB for a particular fabric
                ''',
                'fabric_vrf_db',
                'Cisco-IOS-XR-infra-fti-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-infra-fti-oper',
            'fabric-vrf-dbs',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-infra-fti-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_infra_fti_oper',
            is_config=False,
        ),
    },
    'DciFabricInterconnect.DciVrfs.DciVrf.V4ImportRt' : {
        'meta_info' : _MetaInfoClass('DciFabricInterconnect.DciVrfs.DciVrf.V4ImportRt', REFERENCE_LIST,
            '''V4 Import Route Targets''',
            False, 
            [
            _MetaInfoClassMember('rt-value', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                RT Value
                ''',
                'rt_value',
                'Cisco-IOS-XR-infra-fti-oper', False, is_config=False),
            _MetaInfoClassMember('rt-flags', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                RT Flags
                ''',
                'rt_flags',
                'Cisco-IOS-XR-infra-fti-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-infra-fti-oper',
            'v4-import-rt',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-infra-fti-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_infra_fti_oper',
            is_config=False,
        ),
    },
    'DciFabricInterconnect.DciVrfs.DciVrf.V4ExportRt' : {
        'meta_info' : _MetaInfoClass('DciFabricInterconnect.DciVrfs.DciVrf.V4ExportRt', REFERENCE_LIST,
            '''V4 Export Route Targets''',
            False, 
            [
            _MetaInfoClassMember('rt-value', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                RT Value
                ''',
                'rt_value',
                'Cisco-IOS-XR-infra-fti-oper', False, is_config=False),
            _MetaInfoClassMember('rt-flags', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                RT Flags
                ''',
                'rt_flags',
                'Cisco-IOS-XR-infra-fti-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-infra-fti-oper',
            'v4-export-rt',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-infra-fti-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_infra_fti_oper',
            is_config=False,
        ),
    },
    'DciFabricInterconnect.DciVrfs.DciVrf.V6ImportRt' : {
        'meta_info' : _MetaInfoClass('DciFabricInterconnect.DciVrfs.DciVrf.V6ImportRt', REFERENCE_LIST,
            '''V6 Import Route Targets''',
            False, 
            [
            _MetaInfoClassMember('rt-value', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                RT Value
                ''',
                'rt_value',
                'Cisco-IOS-XR-infra-fti-oper', False, is_config=False),
            _MetaInfoClassMember('rt-flags', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                RT Flags
                ''',
                'rt_flags',
                'Cisco-IOS-XR-infra-fti-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-infra-fti-oper',
            'v6-import-rt',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-infra-fti-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_infra_fti_oper',
            is_config=False,
        ),
    },
    'DciFabricInterconnect.DciVrfs.DciVrf.V6ExportRt' : {
        'meta_info' : _MetaInfoClass('DciFabricInterconnect.DciVrfs.DciVrf.V6ExportRt', REFERENCE_LIST,
            '''V6 Export Route Targets''',
            False, 
            [
            _MetaInfoClassMember('rt-value', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                RT Value
                ''',
                'rt_value',
                'Cisco-IOS-XR-infra-fti-oper', False, is_config=False),
            _MetaInfoClassMember('rt-flags', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                RT Flags
                ''',
                'rt_flags',
                'Cisco-IOS-XR-infra-fti-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-infra-fti-oper',
            'v6-export-rt',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-infra-fti-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_infra_fti_oper',
            is_config=False,
        ),
    },
    'DciFabricInterconnect.DciVrfs.DciVrf' : {
        'meta_info' : _MetaInfoClass('DciFabricInterconnect.DciVrfs.DciVrf', REFERENCE_LIST,
            '''FTI DCI-VRF Info for a particular VRF''',
            False, 
            [
            _MetaInfoClassMember('vrf1', ATTRIBUTE, 'str', 'xr:Cisco-ios-xr-string',
                None, None,
                [], [b'[\\w\\-\\.:,_@#%$\\+=\\|;]+'],
                '''                vrf name
                ''',
                'vrf1',
                'Cisco-IOS-XR-infra-fti-oper', True, is_config=False),
            _MetaInfoClassMember('dci-vrf', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                DCI VRF
                ''',
                'dci_vrf',
                'Cisco-IOS-XR-infra-fti-oper', False, is_config=False),
            _MetaInfoClassMember('num-fabric-vrf', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                Number of Fabric VRFs
                ''',
                'num_fabric_vrf',
                'Cisco-IOS-XR-infra-fti-oper', False, is_config=False),
            _MetaInfoClassMember('faric-vrfs-id-name', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Associated Fabric Vrfs Info
                ''',
                'faric_vrfs_id_name',
                'Cisco-IOS-XR-infra-fti-oper', False, is_config=False),
            _MetaInfoClassMember('vni-id', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                VNI Id
                ''',
                'vni_id',
                'Cisco-IOS-XR-infra-fti-oper', False, is_config=False),
            _MetaInfoClassMember('bd-name', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                BD Name
                ''',
                'bd_name',
                'Cisco-IOS-XR-infra-fti-oper', False, is_config=False),
            _MetaInfoClassMember('bvi-id', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                BVI Id
                ''',
                'bvi_id',
                'Cisco-IOS-XR-infra-fti-oper', False, is_config=False),
            _MetaInfoClassMember('bvi-ip', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                BVI Override IP
                ''',
                'bvi_ip',
                'Cisco-IOS-XR-infra-fti-oper', False, is_config=False),
            _MetaInfoClassMember('bvi-ip-v6', ATTRIBUTE, 'bool', 'boolean',
                None, None,
                [], [],
                '''                BVI IPV6. False is disabled, True is enabled
                ''',
                'bvi_ip_v6',
                'Cisco-IOS-XR-infra-fti-oper', False, is_config=False),
            _MetaInfoClassMember('dci-vrf-flags', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                DCI VRF Flags
                ''',
                'dci_vrf_flags',
                'Cisco-IOS-XR-infra-fti-oper', False, is_config=False),
            _MetaInfoClassMember('v4-import-rt', REFERENCE_LIST, 'V4ImportRt', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_infra_fti_oper', 'DciFabricInterconnect.DciVrfs.DciVrf.V4ImportRt',
                [], [],
                '''                V4 Import Route Targets
                ''',
                'v4_import_rt',
                'Cisco-IOS-XR-infra-fti-oper', False, is_config=False),
            _MetaInfoClassMember('v4-export-rt', REFERENCE_LIST, 'V4ExportRt', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_infra_fti_oper', 'DciFabricInterconnect.DciVrfs.DciVrf.V4ExportRt',
                [], [],
                '''                V4 Export Route Targets
                ''',
                'v4_export_rt',
                'Cisco-IOS-XR-infra-fti-oper', False, is_config=False),
            _MetaInfoClassMember('v6-import-rt', REFERENCE_LIST, 'V6ImportRt', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_infra_fti_oper', 'DciFabricInterconnect.DciVrfs.DciVrf.V6ImportRt',
                [], [],
                '''                V6 Import Route Targets
                ''',
                'v6_import_rt',
                'Cisco-IOS-XR-infra-fti-oper', False, is_config=False),
            _MetaInfoClassMember('v6-export-rt', REFERENCE_LIST, 'V6ExportRt', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_infra_fti_oper', 'DciFabricInterconnect.DciVrfs.DciVrf.V6ExportRt',
                [], [],
                '''                V6 Export Route Targets
                ''',
                'v6_export_rt',
                'Cisco-IOS-XR-infra-fti-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-infra-fti-oper',
            'dci-vrf',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-infra-fti-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_infra_fti_oper',
            is_config=False,
        ),
    },
    'DciFabricInterconnect.DciVrfs' : {
        'meta_info' : _MetaInfoClass('DciFabricInterconnect.DciVrfs', REFERENCE_CLASS,
            '''FTI DCI-VRF DB for all VRFs''',
            False, 
            [
            _MetaInfoClassMember('dci-vrf', REFERENCE_LIST, 'DciVrf', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_infra_fti_oper', 'DciFabricInterconnect.DciVrfs.DciVrf',
                [], [],
                '''                FTI DCI-VRF Info for a particular VRF
                ''',
                'dci_vrf',
                'Cisco-IOS-XR-infra-fti-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-infra-fti-oper',
            'dci-vrfs',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-infra-fti-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_infra_fti_oper',
            is_config=False,
        ),
    },
    'DciFabricInterconnect.Acp' : {
        'meta_info' : _MetaInfoClass('DciFabricInterconnect.Acp', REFERENCE_CLASS,
            '''Auto Config Pool Info''',
            False, 
            [
            _MetaInfoClassMember('vni-min', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                VNI MIN VALUE
                ''',
                'vni_min',
                'Cisco-IOS-XR-infra-fti-oper', False, is_config=False),
            _MetaInfoClassMember('vni-max', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                VNI MAX VALUE
                ''',
                'vni_max',
                'Cisco-IOS-XR-infra-fti-oper', False, is_config=False),
            _MetaInfoClassMember('vni-bits', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                Num of VNI used bits
                ''',
                'vni_bits',
                'Cisco-IOS-XR-infra-fti-oper', False, is_config=False),
            _MetaInfoClassMember('bvi-min', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                BVI MIN VALUE
                ''',
                'bvi_min',
                'Cisco-IOS-XR-infra-fti-oper', False, is_config=False),
            _MetaInfoClassMember('bvi-max', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                BVI MAX VALUE
                ''',
                'bvi_max',
                'Cisco-IOS-XR-infra-fti-oper', False, is_config=False),
            _MetaInfoClassMember('bvi-bits', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                Num of BVI used bits
                ''',
                'bvi_bits',
                'Cisco-IOS-XR-infra-fti-oper', False, is_config=False),
            _MetaInfoClassMember('bd-min', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                BD MIN VALUE
                ''',
                'bd_min',
                'Cisco-IOS-XR-infra-fti-oper', False, is_config=False),
            _MetaInfoClassMember('bd-max', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                BD MAX VALUE
                ''',
                'bd_max',
                'Cisco-IOS-XR-infra-fti-oper', False, is_config=False),
            _MetaInfoClassMember('bd-bits', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                Num of BD used bits
                ''',
                'bd_bits',
                'Cisco-IOS-XR-infra-fti-oper', False, is_config=False),
            _MetaInfoClassMember('vniused-range', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Used VNI Range
                ''',
                'vniused_range',
                'Cisco-IOS-XR-infra-fti-oper', False, is_config=False),
            _MetaInfoClassMember('bviused-range', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Used BVI Range
                ''',
                'bviused_range',
                'Cisco-IOS-XR-infra-fti-oper', False, is_config=False),
            _MetaInfoClassMember('bdused-range', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Used BD Range
                ''',
                'bdused_range',
                'Cisco-IOS-XR-infra-fti-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-infra-fti-oper',
            'acp',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-infra-fti-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_infra_fti_oper',
            is_config=False,
        ),
    },
    'DciFabricInterconnect' : {
        'meta_info' : _MetaInfoClass('DciFabricInterconnect', REFERENCE_CLASS,
            '''Display FTI operational data''',
            False, 
            [
            _MetaInfoClassMember('opflex-session-infos', REFERENCE_CLASS, 'OpflexSessionInfos', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_infra_fti_oper', 'DciFabricInterconnect.OpflexSessionInfos',
                [], [],
                '''                FTI Opflex Session Info for all fabrics
                ''',
                'opflex_session_infos',
                'Cisco-IOS-XR-infra-fti-oper', False, is_config=False),
            _MetaInfoClassMember('fabric-vrf-dbs', REFERENCE_CLASS, 'FabricVrfDbs', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_infra_fti_oper', 'DciFabricInterconnect.FabricVrfDbs',
                [], [],
                '''                FTI Fabric-VRF DB for all fabrics
                ''',
                'fabric_vrf_dbs',
                'Cisco-IOS-XR-infra-fti-oper', False, is_config=False),
            _MetaInfoClassMember('dci-vrfs', REFERENCE_CLASS, 'DciVrfs', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_infra_fti_oper', 'DciFabricInterconnect.DciVrfs',
                [], [],
                '''                FTI DCI-VRF DB for all VRFs
                ''',
                'dci_vrfs',
                'Cisco-IOS-XR-infra-fti-oper', False, is_config=False),
            _MetaInfoClassMember('acp', REFERENCE_CLASS, 'Acp', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_infra_fti_oper', 'DciFabricInterconnect.Acp',
                [], [],
                '''                Auto Config Pool Info
                ''',
                'acp',
                'Cisco-IOS-XR-infra-fti-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-infra-fti-oper',
            'dci-fabric-interconnect',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-infra-fti-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_infra_fti_oper',
            is_config=False,
        ),
    },
}
_meta_table['DciFabricInterconnect.OpflexSessionInfos.OpflexSessionInfo.PeerInfo']['meta_info'].parent =_meta_table['DciFabricInterconnect.OpflexSessionInfos.OpflexSessionInfo']['meta_info']
_meta_table['DciFabricInterconnect.OpflexSessionInfos.OpflexSessionInfo']['meta_info'].parent =_meta_table['DciFabricInterconnect.OpflexSessionInfos']['meta_info']
_meta_table['DciFabricInterconnect.FabricVrfDbs.FabricVrfDb.FabricVrf.V4ImportRt']['meta_info'].parent =_meta_table['DciFabricInterconnect.FabricVrfDbs.FabricVrfDb.FabricVrf']['meta_info']
_meta_table['DciFabricInterconnect.FabricVrfDbs.FabricVrfDb.FabricVrf.V4ExportRt']['meta_info'].parent =_meta_table['DciFabricInterconnect.FabricVrfDbs.FabricVrfDb.FabricVrf']['meta_info']
_meta_table['DciFabricInterconnect.FabricVrfDbs.FabricVrfDb.FabricVrf.V6ImportRt']['meta_info'].parent =_meta_table['DciFabricInterconnect.FabricVrfDbs.FabricVrfDb.FabricVrf']['meta_info']
_meta_table['DciFabricInterconnect.FabricVrfDbs.FabricVrfDb.FabricVrf.V6ExportRt']['meta_info'].parent =_meta_table['DciFabricInterconnect.FabricVrfDbs.FabricVrfDb.FabricVrf']['meta_info']
_meta_table['DciFabricInterconnect.FabricVrfDbs.FabricVrfDb.FabricVrf']['meta_info'].parent =_meta_table['DciFabricInterconnect.FabricVrfDbs.FabricVrfDb']['meta_info']
_meta_table['DciFabricInterconnect.FabricVrfDbs.FabricVrfDb']['meta_info'].parent =_meta_table['DciFabricInterconnect.FabricVrfDbs']['meta_info']
_meta_table['DciFabricInterconnect.DciVrfs.DciVrf.V4ImportRt']['meta_info'].parent =_meta_table['DciFabricInterconnect.DciVrfs.DciVrf']['meta_info']
_meta_table['DciFabricInterconnect.DciVrfs.DciVrf.V4ExportRt']['meta_info'].parent =_meta_table['DciFabricInterconnect.DciVrfs.DciVrf']['meta_info']
_meta_table['DciFabricInterconnect.DciVrfs.DciVrf.V6ImportRt']['meta_info'].parent =_meta_table['DciFabricInterconnect.DciVrfs.DciVrf']['meta_info']
_meta_table['DciFabricInterconnect.DciVrfs.DciVrf.V6ExportRt']['meta_info'].parent =_meta_table['DciFabricInterconnect.DciVrfs.DciVrf']['meta_info']
_meta_table['DciFabricInterconnect.DciVrfs.DciVrf']['meta_info'].parent =_meta_table['DciFabricInterconnect.DciVrfs']['meta_info']
_meta_table['DciFabricInterconnect.OpflexSessionInfos']['meta_info'].parent =_meta_table['DciFabricInterconnect']['meta_info']
_meta_table['DciFabricInterconnect.FabricVrfDbs']['meta_info'].parent =_meta_table['DciFabricInterconnect']['meta_info']
_meta_table['DciFabricInterconnect.DciVrfs']['meta_info'].parent =_meta_table['DciFabricInterconnect']['meta_info']
_meta_table['DciFabricInterconnect.Acp']['meta_info'].parent =_meta_table['DciFabricInterconnect']['meta_info']
