
'''
This is auto-generated file,
which includes metadata for module Cisco_IOS_XR_ipv4_bgp_datatypes
'''

from ydk._core._dm_meta_info import _MetaInfoClassMember, _MetaInfoClass, _MetaInfoEnum
from ydk._core._dm_meta_info import ATTRIBUTE, REFERENCE_LIST, REFERENCE_LEAFLIST, REFERENCE_BITS, REFERENCE_UNION
from ydk._core._dm_meta_info import REFERENCE_CLASS, REFERENCE_IDENTITY_CLASS, REFERENCE_ENUM_CLASS, ANYXML_CLASS
from ydk._core._importer import _yang_ns

_meta_table = {
    'BgpOfficialAddressFamily' : _MetaInfoEnum('BgpOfficialAddressFamily',
        'ydk.models.cisco_ios_xr.Cisco_IOS_XR_ipv4_bgp_datatypes', 'BgpOfficialAddressFamily',
        '''Bgp official address family''',
        {
            'ipv4':'ipv4',
            'ipv6':'ipv6',
            'l2vpn':'l2vpn',
            'ls':'ls',
            'all':'all',
        }, 'Cisco-IOS-XR-ipv4-bgp-datatypes', _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-ipv4-bgp-datatypes']),
    'BgpNbrCapAdditionalPathsCfg' : _MetaInfoEnum('BgpNbrCapAdditionalPathsCfg',
        'ydk.models.cisco_ios_xr.Cisco_IOS_XR_ipv4_bgp_datatypes', 'BgpNbrCapAdditionalPathsCfg',
        '''Bgp nbr cap additional paths cfg''',
        {
            'enable':'enable',
            'disable':'disable',
        }, 'Cisco-IOS-XR-ipv4-bgp-datatypes', _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-ipv4-bgp-datatypes']),
    'BgpAdvertiseLocalLabeledRouteCfg' : _MetaInfoEnum('BgpAdvertiseLocalLabeledRouteCfg',
        'ydk.models.cisco_ios_xr.Cisco_IOS_XR_ipv4_bgp_datatypes', 'BgpAdvertiseLocalLabeledRouteCfg',
        '''Bgp advertise local labeled route cfg''',
        {
            'enable':'enable',
            'disable':'disable',
        }, 'Cisco-IOS-XR-ipv4-bgp-datatypes', _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-ipv4-bgp-datatypes']),
    'BgpTos' : _MetaInfoEnum('BgpTos',
        'ydk.models.cisco_ios_xr.Cisco_IOS_XR_ipv4_bgp_datatypes', 'BgpTos',
        '''Bgp tos''',
        {
            'precedence':'precedence',
            'dscp':'dscp',
        }, 'Cisco-IOS-XR-ipv4-bgp-datatypes', _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-ipv4-bgp-datatypes']),
    'BgpAddressFamily' : _MetaInfoEnum('BgpAddressFamily',
        'ydk.models.cisco_ios_xr.Cisco_IOS_XR_ipv4_bgp_datatypes', 'BgpAddressFamily',
        '''Bgp address family''',
        {
            'ipv4-unicast':'ipv4_unicast',
            'ipv4-multicast':'ipv4_multicast',
            'ipv4-labeled-unicast':'ipv4_labeled_unicast',
            'ipv4-tunnel':'ipv4_tunnel',
            'vpnv4-unicast':'vpnv4_unicast',
            'ipv6-unicast':'ipv6_unicast',
            'ipv6-multicast':'ipv6_multicast',
            'ipv6-labeled-unicast':'ipv6_labeled_unicast',
            'vpnv6-unicast':'vpnv6_unicast',
            'ipv4-mdt':'ipv4_mdt',
            'l2vpn-vpls':'l2vpn_vpls',
            'ipv4rt-constraint':'ipv4rt_constraint',
            'ipv4-mvpn':'ipv4_mvpn',
            'ipv6-mvpn':'ipv6_mvpn',
            'l2vpn-evpn':'l2vpn_evpn',
            'lsls':'lsls',
            'vpnv4-multicast':'vpnv4_multicast',
            'vpnv6-multicast':'vpnv6_multicast',
            'ipv4-flowspec':'ipv4_flowspec',
            'ipv6-flowspec':'ipv6_flowspec',
            'vpnv4-flowspec':'vpnv4_flowspec',
            'vpnv6-flowspec':'vpnv6_flowspec',
            'l2vpn-mspw':'l2vpn_mspw',
            'ipv4-sr-policy':'ipv4_sr_policy',
            'ipv6-sr-policy':'ipv6_sr_policy',
            'all-address-family':'all_address_family',
        }, 'Cisco-IOS-XR-ipv4-bgp-datatypes', _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-ipv4-bgp-datatypes']),
    'BgpUpdateFilterAction' : _MetaInfoEnum('BgpUpdateFilterAction',
        'ydk.models.cisco_ios_xr.Cisco_IOS_XR_ipv4_bgp_datatypes', 'BgpUpdateFilterAction',
        '''Bgp update filter action''',
        {
            'treat-as-withdraw':'treat_as_withdraw',
            'discard-attibute':'discard_attibute',
        }, 'Cisco-IOS-XR-ipv4-bgp-datatypes', _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-ipv4-bgp-datatypes']),
    'BgpPrecedenceDscp' : _MetaInfoEnum('BgpPrecedenceDscp',
        'ydk.models.cisco_ios_xr.Cisco_IOS_XR_ipv4_bgp_datatypes', 'BgpPrecedenceDscp',
        ''' ''',
        {
            'af11':'af11',
            'af12':'af12',
            'af13':'af13',
            'af21':'af21',
            'af22':'af22',
            'af23':'af23',
            'af31':'af31',
            'af32':'af32',
            'af33':'af33',
            'af41':'af41',
            'af42':'af42',
            'af43':'af43',
            'cs1':'cs1',
            'cs2':'cs2',
            'cs3':'cs3',
            'cs4':'cs4',
            'cs5':'cs5',
            'cs6':'cs6',
            'cs7':'cs7',
            'ef':'ef',
            'critical':'critical',
            'flash':'flash',
            'flash-override':'flash_override',
            'immediate':'immediate',
            'internet':'internet',
            'network':'network',
            'priority':'priority',
            'default-or-routine':'default_or_routine',
        }, 'Cisco-IOS-XR-ipv4-bgp-datatypes', _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-ipv4-bgp-datatypes']),
    'BgpAfAdditionalPathsCfg' : _MetaInfoEnum('BgpAfAdditionalPathsCfg',
        'ydk.models.cisco_ios_xr.Cisco_IOS_XR_ipv4_bgp_datatypes', 'BgpAfAdditionalPathsCfg',
        '''Bgp af additional paths cfg''',
        {
            'enable':'enable',
            'disable':'disable',
        }, 'Cisco-IOS-XR-ipv4-bgp-datatypes', _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-ipv4-bgp-datatypes']),
    'BgpSubsequentAddressFamily' : _MetaInfoEnum('BgpSubsequentAddressFamily',
        'ydk.models.cisco_ios_xr.Cisco_IOS_XR_ipv4_bgp_datatypes', 'BgpSubsequentAddressFamily',
        '''Bgp subsequent address family''',
        {
            'unicast':'unicast',
            'multicast':'multicast',
            'labeled-unicast':'labeled_unicast',
            'mvpn':'mvpn',
            'mspw':'mspw',
            'tunnel':'tunnel',
            'vpls':'vpls',
            'mdt':'mdt',
            'vpws':'vpws',
            'evpn':'evpn',
            'ls':'ls',
            'sr-policy':'sr_policy',
            'vpn':'vpn',
            'vpn-mcast':'vpn_mcast',
            'rt-filter':'rt_filter',
            'flowspec':'flowspec',
            'vpn-flowspec':'vpn_flowspec',
            'all':'all',
        }, 'Cisco-IOS-XR-ipv4-bgp-datatypes', _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-ipv4-bgp-datatypes']),
}
