
'''
This is auto-generated file,
which includes metadata for module Cisco_IOS_XR_ip_sbfd_oper
'''

from ydk._core._dm_meta_info import _MetaInfoClassMember, _MetaInfoClass, _MetaInfoEnum
from ydk._core._dm_meta_info import ATTRIBUTE, REFERENCE_LIST, REFERENCE_LEAFLIST, REFERENCE_BITS, REFERENCE_UNION
from ydk._core._dm_meta_info import REFERENCE_CLASS, REFERENCE_IDENTITY_CLASS, REFERENCE_ENUM_CLASS, ANYXML_CLASS
from ydk._core._importer import _yang_ns

_meta_table = {
    'BfdAfId' : _MetaInfoEnum('BfdAfId',
        'ydk.models.cisco_ios_xr.Cisco_IOS_XR_ip_sbfd_oper', 'BfdAfId',
        '''Bfd af id''',
        {
            'bfd-af-id-none':'bfd_af_id_none',
            'bfd-af-id-ipv4':'bfd_af_id_ipv4',
            'bfd-af-id-ipv6':'bfd_af_id_ipv6',
        }, 'Cisco-IOS-XR-ip-sbfd-oper', _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-ip-sbfd-oper']),
    'SbfdAddressFamily' : _MetaInfoEnum('SbfdAddressFamily',
        'ydk.models.cisco_ios_xr.Cisco_IOS_XR_ip_sbfd_oper', 'SbfdAddressFamily',
        '''Sbfd address family''',
        {
            'ipv4':'ipv4',
            'ipv6':'ipv6',
        }, 'Cisco-IOS-XR-ip-sbfd-oper', _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-ip-sbfd-oper']),
    'Sbfd.TargetIdentifier.RemoteVrfs.RemoteVrf.RemoteDiscriminator.IpAddress' : {
        'meta_info' : _MetaInfoClass('Sbfd.TargetIdentifier.RemoteVrfs.RemoteVrf.RemoteDiscriminator.IpAddress', REFERENCE_CLASS,
            '''IP address''',
            False, 
            [
            _MetaInfoClassMember('afi', REFERENCE_ENUM_CLASS, 'BfdAfId', 'Bfd-af-id',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_ip_sbfd_oper', 'BfdAfId',
                [], [],
                '''                AFI
                ''',
                'afi',
                'Cisco-IOS-XR-ip-sbfd-oper', False, is_config=False),
            _MetaInfoClassMember('dummy', ATTRIBUTE, 'int', 'uint8',
                None, None,
                [('0', '255')], [],
                '''                No Address
                ''',
                'dummy',
                'Cisco-IOS-XR-ip-sbfd-oper', False, is_config=False, has_when=True),
            _MetaInfoClassMember('ipv4', ATTRIBUTE, 'str', 'Bfd-in-addr',
                None, None,
                [], [b'(([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])(%[\\p{N}\\p{L}]+)?'],
                '''                IPv4 address type
                ''',
                'ipv4',
                'Cisco-IOS-XR-ip-sbfd-oper', False, is_config=False, has_when=True),
            _MetaInfoClassMember('ipv6', ATTRIBUTE, 'str', 'Bfd-in6-addr',
                None, None,
                [], [b'((:|[0-9a-fA-F]{0,4}):)([0-9a-fA-F]{0,4}:){0,5}((([0-9a-fA-F]{0,4}:)?(:|[0-9a-fA-F]{0,4}))|(((25[0-5]|2[0-4][0-9]|[01]?[0-9]?[0-9])\\.){3}(25[0-5]|2[0-4][0-9]|[01]?[0-9]?[0-9])))(%[\\p{N}\\p{L}]+)?'],
                '''                IPv6 address type
                ''',
                'ipv6',
                'Cisco-IOS-XR-ip-sbfd-oper', False, is_config=False, has_when=True),
            ],
            'Cisco-IOS-XR-ip-sbfd-oper',
            'ip-address',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-ip-sbfd-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_ip_sbfd_oper',
            is_config=False,
        ),
    },
    'Sbfd.TargetIdentifier.RemoteVrfs.RemoteVrf.RemoteDiscriminator' : {
        'meta_info' : _MetaInfoClass('Sbfd.TargetIdentifier.RemoteVrfs.RemoteVrf.RemoteDiscriminator', REFERENCE_LIST,
            '''SBFD remote discriminator ''',
            False, 
            [
            _MetaInfoClassMember('vrf-name', ATTRIBUTE, 'str', 'xr:Cisco-ios-xr-string',
                None, None,
                [], [b'[\\w\\-\\.:,_@#%$\\+=\\|;]+'],
                '''                VRF Name 
                ''',
                'vrf_name',
                'Cisco-IOS-XR-ip-sbfd-oper', False, is_config=False),
            _MetaInfoClassMember('remote-discriminator', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                Remote Discriminator
                ''',
                'remote_discriminator',
                'Cisco-IOS-XR-ip-sbfd-oper', False, is_config=False),
            _MetaInfoClassMember('address', REFERENCE_UNION, 'str', 'inet:ip-address-no-zone',
                None, None,
                [], [],
                '''                Address
                ''',
                'address',
                'Cisco-IOS-XR-ip-sbfd-oper', False, [
                    _MetaInfoClassMember('address', ATTRIBUTE, 'str', 'inet:ipv4-address-no-zone',
                        None, None,
                        [], [b'(([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])(%[\\p{N}\\p{L}]+)?'],
                        '''                        Address
                        ''',
                        'address',
                        'Cisco-IOS-XR-ip-sbfd-oper', False, is_config=False),
                    _MetaInfoClassMember('address', ATTRIBUTE, 'str', 'inet:ipv6-address-no-zone',
                        None, None,
                        [], [b'((:|[0-9a-fA-F]{0,4}):)([0-9a-fA-F]{0,4}:){0,5}((([0-9a-fA-F]{0,4}:)?(:|[0-9a-fA-F]{0,4}))|(((25[0-5]|2[0-4][0-9]|[01]?[0-9]?[0-9])\\.){3}(25[0-5]|2[0-4][0-9]|[01]?[0-9]?[0-9])))(%[\\p{N}\\p{L}]+)?'],
                        '''                        Address
                        ''',
                        'address',
                        'Cisco-IOS-XR-ip-sbfd-oper', False, is_config=False),
                ], is_config=False),
            _MetaInfoClassMember('ip-address', REFERENCE_CLASS, 'IpAddress', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_ip_sbfd_oper', 'Sbfd.TargetIdentifier.RemoteVrfs.RemoteVrf.RemoteDiscriminator.IpAddress',
                [], [],
                '''                IP address
                ''',
                'ip_address',
                'Cisco-IOS-XR-ip-sbfd-oper', False, is_config=False),
            _MetaInfoClassMember('tid-type', REFERENCE_ENUM_CLASS, 'SbfdAddressFamily', 'Sbfd-address-family',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_ip_sbfd_oper', 'SbfdAddressFamily',
                [], [],
                '''                Target identifier for sbfd
                ''',
                'tid_type',
                'Cisco-IOS-XR-ip-sbfd-oper', False, is_config=False),
            _MetaInfoClassMember('discr', ATTRIBUTE, 'int', 'Bfd-discr',
                None, None,
                [('0', '4294967295')], [],
                '''                Remote discriminator
                ''',
                'discr',
                'Cisco-IOS-XR-ip-sbfd-oper', False, is_config=False),
            _MetaInfoClassMember('vrf-name-xr', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                VRF Name
                ''',
                'vrf_name_xr',
                'Cisco-IOS-XR-ip-sbfd-oper', False, is_config=False),
            _MetaInfoClassMember('status', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Status
                ''',
                'status',
                'Cisco-IOS-XR-ip-sbfd-oper', False, is_config=False),
            _MetaInfoClassMember('discr-src', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Discriminator source name
                ''',
                'discr_src',
                'Cisco-IOS-XR-ip-sbfd-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-ip-sbfd-oper',
            'remote-discriminator',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-ip-sbfd-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_ip_sbfd_oper',
            is_config=False,
        ),
    },
    'Sbfd.TargetIdentifier.RemoteVrfs.RemoteVrf' : {
        'meta_info' : _MetaInfoClass('Sbfd.TargetIdentifier.RemoteVrfs.RemoteVrf', REFERENCE_LIST,
            '''Table of remote discriminator data per VRF''',
            False, 
            [
            _MetaInfoClassMember('vrf-name', ATTRIBUTE, 'str', 'xr:Cisco-ios-xr-string',
                None, None,
                [], [b'[\\w\\-\\.:,_@#%$\\+=\\|;]+'],
                '''                VRF name
                ''',
                'vrf_name',
                'Cisco-IOS-XR-ip-sbfd-oper', True, is_config=False),
            _MetaInfoClassMember('remote-discriminator', REFERENCE_LIST, 'RemoteDiscriminator', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_ip_sbfd_oper', 'Sbfd.TargetIdentifier.RemoteVrfs.RemoteVrf.RemoteDiscriminator',
                [], [],
                '''                SBFD remote discriminator 
                ''',
                'remote_discriminator',
                'Cisco-IOS-XR-ip-sbfd-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-ip-sbfd-oper',
            'remote-vrf',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-ip-sbfd-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_ip_sbfd_oper',
            is_config=False,
        ),
    },
    'Sbfd.TargetIdentifier.RemoteVrfs' : {
        'meta_info' : _MetaInfoClass('Sbfd.TargetIdentifier.RemoteVrfs', REFERENCE_CLASS,
            '''SBFD remote discriminator data''',
            False, 
            [
            _MetaInfoClassMember('remote-vrf', REFERENCE_LIST, 'RemoteVrf', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_ip_sbfd_oper', 'Sbfd.TargetIdentifier.RemoteVrfs.RemoteVrf',
                [], [],
                '''                Table of remote discriminator data per VRF
                ''',
                'remote_vrf',
                'Cisco-IOS-XR-ip-sbfd-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-ip-sbfd-oper',
            'remote-vrfs',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-ip-sbfd-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_ip_sbfd_oper',
            is_config=False,
        ),
    },
    'Sbfd.TargetIdentifier.LocalVrfs.LocalVrf.LocalDiscriminator' : {
        'meta_info' : _MetaInfoClass('Sbfd.TargetIdentifier.LocalVrfs.LocalVrf.LocalDiscriminator', REFERENCE_LIST,
            '''SBFD local discriminator ''',
            False, 
            [
            _MetaInfoClassMember('local-discriminator', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                Local discriminator
                ''',
                'local_discriminator',
                'Cisco-IOS-XR-ip-sbfd-oper', False, is_config=False),
            _MetaInfoClassMember('vrf-name', ATTRIBUTE, 'str', 'xr:Cisco-ios-xr-string',
                None, None,
                [], [b'[\\w\\-\\.:,_@#%$\\+=\\|;]+'],
                '''                VRF Name 
                ''',
                'vrf_name',
                'Cisco-IOS-XR-ip-sbfd-oper', False, is_config=False),
            _MetaInfoClassMember('discr', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                Local discriminator
                ''',
                'discr',
                'Cisco-IOS-XR-ip-sbfd-oper', False, is_config=False),
            _MetaInfoClassMember('vrf-name-xr', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                VRF Name
                ''',
                'vrf_name_xr',
                'Cisco-IOS-XR-ip-sbfd-oper', False, is_config=False),
            _MetaInfoClassMember('flags', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                MODE name
                ''',
                'flags',
                'Cisco-IOS-XR-ip-sbfd-oper', False, is_config=False),
            _MetaInfoClassMember('status', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Status
                ''',
                'status',
                'Cisco-IOS-XR-ip-sbfd-oper', False, is_config=False),
            _MetaInfoClassMember('discr-src', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Discriminator source name
                ''',
                'discr_src',
                'Cisco-IOS-XR-ip-sbfd-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-ip-sbfd-oper',
            'local-discriminator',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-ip-sbfd-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_ip_sbfd_oper',
            is_config=False,
        ),
    },
    'Sbfd.TargetIdentifier.LocalVrfs.LocalVrf' : {
        'meta_info' : _MetaInfoClass('Sbfd.TargetIdentifier.LocalVrfs.LocalVrf', REFERENCE_LIST,
            '''Table of local discriminator data per VRF''',
            False, 
            [
            _MetaInfoClassMember('vrf-name', ATTRIBUTE, 'str', 'xr:Cisco-ios-xr-string',
                None, None,
                [], [b'[\\w\\-\\.:,_@#%$\\+=\\|;]+'],
                '''                VRF name
                ''',
                'vrf_name',
                'Cisco-IOS-XR-ip-sbfd-oper', True, is_config=False),
            _MetaInfoClassMember('local-discriminator', REFERENCE_LIST, 'LocalDiscriminator', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_ip_sbfd_oper', 'Sbfd.TargetIdentifier.LocalVrfs.LocalVrf.LocalDiscriminator',
                [], [],
                '''                SBFD local discriminator 
                ''',
                'local_discriminator',
                'Cisco-IOS-XR-ip-sbfd-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-ip-sbfd-oper',
            'local-vrf',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-ip-sbfd-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_ip_sbfd_oper',
            is_config=False,
        ),
    },
    'Sbfd.TargetIdentifier.LocalVrfs' : {
        'meta_info' : _MetaInfoClass('Sbfd.TargetIdentifier.LocalVrfs', REFERENCE_CLASS,
            '''SBFD local discriminator  data''',
            False, 
            [
            _MetaInfoClassMember('local-vrf', REFERENCE_LIST, 'LocalVrf', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_ip_sbfd_oper', 'Sbfd.TargetIdentifier.LocalVrfs.LocalVrf',
                [], [],
                '''                Table of local discriminator data per VRF
                ''',
                'local_vrf',
                'Cisco-IOS-XR-ip-sbfd-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-ip-sbfd-oper',
            'local-vrfs',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-ip-sbfd-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_ip_sbfd_oper',
            is_config=False,
        ),
    },
    'Sbfd.TargetIdentifier' : {
        'meta_info' : _MetaInfoClass('Sbfd.TargetIdentifier', REFERENCE_CLASS,
            '''Target-identifier information''',
            False, 
            [
            _MetaInfoClassMember('remote-vrfs', REFERENCE_CLASS, 'RemoteVrfs', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_ip_sbfd_oper', 'Sbfd.TargetIdentifier.RemoteVrfs',
                [], [],
                '''                SBFD remote discriminator data
                ''',
                'remote_vrfs',
                'Cisco-IOS-XR-ip-sbfd-oper', False, is_config=False),
            _MetaInfoClassMember('local-vrfs', REFERENCE_CLASS, 'LocalVrfs', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_ip_sbfd_oper', 'Sbfd.TargetIdentifier.LocalVrfs',
                [], [],
                '''                SBFD local discriminator  data
                ''',
                'local_vrfs',
                'Cisco-IOS-XR-ip-sbfd-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-ip-sbfd-oper',
            'target-identifier',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-ip-sbfd-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_ip_sbfd_oper',
            is_config=False,
        ),
    },
    'Sbfd' : {
        'meta_info' : _MetaInfoClass('Sbfd', REFERENCE_CLASS,
            '''Seamless BFD (S-BFD) operational data''',
            False, 
            [
            _MetaInfoClassMember('target-identifier', REFERENCE_CLASS, 'TargetIdentifier', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_ip_sbfd_oper', 'Sbfd.TargetIdentifier',
                [], [],
                '''                Target-identifier information
                ''',
                'target_identifier',
                'Cisco-IOS-XR-ip-sbfd-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-ip-sbfd-oper',
            'sbfd',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-ip-sbfd-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_ip_sbfd_oper',
            is_config=False,
        ),
    },
}
_meta_table['Sbfd.TargetIdentifier.RemoteVrfs.RemoteVrf.RemoteDiscriminator.IpAddress']['meta_info'].parent =_meta_table['Sbfd.TargetIdentifier.RemoteVrfs.RemoteVrf.RemoteDiscriminator']['meta_info']
_meta_table['Sbfd.TargetIdentifier.RemoteVrfs.RemoteVrf.RemoteDiscriminator']['meta_info'].parent =_meta_table['Sbfd.TargetIdentifier.RemoteVrfs.RemoteVrf']['meta_info']
_meta_table['Sbfd.TargetIdentifier.RemoteVrfs.RemoteVrf']['meta_info'].parent =_meta_table['Sbfd.TargetIdentifier.RemoteVrfs']['meta_info']
_meta_table['Sbfd.TargetIdentifier.LocalVrfs.LocalVrf.LocalDiscriminator']['meta_info'].parent =_meta_table['Sbfd.TargetIdentifier.LocalVrfs.LocalVrf']['meta_info']
_meta_table['Sbfd.TargetIdentifier.LocalVrfs.LocalVrf']['meta_info'].parent =_meta_table['Sbfd.TargetIdentifier.LocalVrfs']['meta_info']
_meta_table['Sbfd.TargetIdentifier.RemoteVrfs']['meta_info'].parent =_meta_table['Sbfd.TargetIdentifier']['meta_info']
_meta_table['Sbfd.TargetIdentifier.LocalVrfs']['meta_info'].parent =_meta_table['Sbfd.TargetIdentifier']['meta_info']
_meta_table['Sbfd.TargetIdentifier']['meta_info'].parent =_meta_table['Sbfd']['meta_info']
