
'''
This is auto-generated file,
which includes metadata for module Cisco_IOS_XR_sysadmin_pm
'''

from ydk._core._dm_meta_info import _MetaInfoClassMember, _MetaInfoClass, _MetaInfoEnum
from ydk._core._dm_meta_info import ATTRIBUTE, REFERENCE_LIST, REFERENCE_LEAFLIST, REFERENCE_BITS, REFERENCE_UNION
from ydk._core._dm_meta_info import REFERENCE_CLASS, REFERENCE_IDENTITY_CLASS, REFERENCE_ENUM_CLASS, ANYXML_CLASS
from ydk._core._importer import _yang_ns

_meta_table = {
    'StartupMode' : _MetaInfoEnum('StartupMode',
        'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_pm', 'StartupMode',
        ''' ''',
        {
            'ON-BOOTUP':'ON_BOOTUP',
            'ON-SELECTION':'ON_SELECTION',
            'ON-DEMAND':'ON_DEMAND',
        }, 'Cisco-IOS-XR-sysadmin-pm', _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-sysadmin-pm']),
    'ProcessState' : _MetaInfoEnum('ProcessState',
        'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_pm', 'ProcessState',
        ''' ''',
        {
            'IDLE':'IDLE',
            'RUNNING':'RUNNING',
            'STOPPING':'STOPPING',
            'STOPPED':'STOPPED',
            'DESELECTING':'DESELECTING',
            'DESELECTED':'DESELECTED',
        }, 'Cisco-IOS-XR-sysadmin-pm', _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-sysadmin-pm']),
    'ServiceScope' : _MetaInfoEnum('ServiceScope',
        'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_pm', 'ServiceScope',
        ''' ''',
        {
            'SYSTEM':'SYSTEM',
            'RACK':'RACK',
        }, 'Cisco-IOS-XR-sysadmin-pm', _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-sysadmin-pm']),
    'ServiceState' : _MetaInfoEnum('ServiceState',
        'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_pm', 'ServiceState',
        ''' ''',
        {
            'SS_IDLE':'SS_IDLE',
            'SS_RUNNING':'SS_RUNNING',
            'SS_ACK_PENDING':'SS_ACK_PENDING',
        }, 'Cisco-IOS-XR-sysadmin-pm', _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-sysadmin-pm']),
    'ServiceRole' : _MetaInfoEnum('ServiceRole',
        'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_pm', 'ServiceRole',
        ''' ''',
        {
            'NONE':'NONE',
            'ACTIVE':'ACTIVE',
            'STANDBY':'STANDBY',
        }, 'Cisco-IOS-XR-sysadmin-pm', _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-sysadmin-pm']),
    'Processes.AllLocations.Name.Services' : {
        'meta_info' : _MetaInfoClass('Processes.AllLocations.Name.Services', REFERENCE_LIST,
            ''' ''',
            False, 
            [
            _MetaInfoClassMember('service-name', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Name of the service
                ''',
                'service_name',
                'Cisco-IOS-XR-sysadmin-pm', True, is_config=False),
            _MetaInfoClassMember('scope', REFERENCE_ENUM_CLASS, 'ServiceScope', 'serviceScope',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_pm', 'ServiceScope',
                [], [],
                '''                Scope of the service
                ''',
                'scope',
                'Cisco-IOS-XR-sysadmin-pm', False, is_config=False),
            _MetaInfoClassMember('redundancy', ATTRIBUTE, 'bool', 'boolean',
                None, None,
                [], [],
                '''                Service redundancy support
                ''',
                'redundancy',
                'Cisco-IOS-XR-sysadmin-pm', False, is_config=False),
            _MetaInfoClassMember('ha-ready', ATTRIBUTE, 'bool', 'boolean',
                None, None,
                [], [],
                '''                Standby ready for HA
                ''',
                'ha_ready',
                'Cisco-IOS-XR-sysadmin-pm', False, is_config=False),
            _MetaInfoClassMember('service-state', REFERENCE_ENUM_CLASS, 'ServiceState', 'serviceState',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_pm', 'ServiceState',
                [], [],
                '''                State of the service
                ''',
                'service_state',
                'Cisco-IOS-XR-sysadmin-pm', False, is_config=False),
            _MetaInfoClassMember('ha-role', REFERENCE_ENUM_CLASS, 'ServiceRole', 'serviceRole',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_pm', 'ServiceRole',
                [], [],
                '''                Service role
                ''',
                'ha_role',
                'Cisco-IOS-XR-sysadmin-pm', False, is_config=False),
            _MetaInfoClassMember('new-ha-role', REFERENCE_ENUM_CLASS, 'ServiceRole', 'serviceRole',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_pm', 'ServiceRole',
                [], [],
                '''                New service role, different if PM in process of assigning
                ''',
                'new_ha_role',
                'Cisco-IOS-XR-sysadmin-pm', False, is_config=False),
            _MetaInfoClassMember('selected', ATTRIBUTE, 'bool', 'boolean',
                None, None,
                [], [],
                '''                Service seleted to run on the node
                ''',
                'selected',
                'Cisco-IOS-XR-sysadmin-pm', False, is_config=False),
            _MetaInfoClassMember('ip1', REFERENCE_UNION, 'str', 'inet:ip-address',
                None, None,
                [], [],
                '''                First IP address in the selection
                ''',
                'ip1',
                'Cisco-IOS-XR-sysadmin-pm', False, [
                    _MetaInfoClassMember('ip1', ATTRIBUTE, 'str', 'inet:ipv4-address',
                        None, None,
                        [], [b'(([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])(%[\\p{N}\\p{L}]+)?'],
                        '''                        First IP address in the selection
                        ''',
                        'ip1',
                        'Cisco-IOS-XR-sysadmin-pm', False, is_config=False),
                    _MetaInfoClassMember('ip1', ATTRIBUTE, 'str', 'inet:ipv6-address',
                        None, None,
                        [], [b'((:|[0-9a-fA-F]{0,4}):)([0-9a-fA-F]{0,4}:){0,5}((([0-9a-fA-F]{0,4}:)?(:|[0-9a-fA-F]{0,4}))|(((25[0-5]|2[0-4][0-9]|[01]?[0-9]?[0-9])\\.){3}(25[0-5]|2[0-4][0-9]|[01]?[0-9]?[0-9])))(%[\\p{N}\\p{L}]+)?'],
                        '''                        First IP address in the selection
                        ''',
                        'ip1',
                        'Cisco-IOS-XR-sysadmin-pm', False, is_config=False),
                ], is_config=False),
            _MetaInfoClassMember('ip2', REFERENCE_UNION, 'str', 'inet:ip-address',
                None, None,
                [], [],
                '''                Second IP address in the selection
                ''',
                'ip2',
                'Cisco-IOS-XR-sysadmin-pm', False, [
                    _MetaInfoClassMember('ip2', ATTRIBUTE, 'str', 'inet:ipv4-address',
                        None, None,
                        [], [b'(([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])(%[\\p{N}\\p{L}]+)?'],
                        '''                        Second IP address in the selection
                        ''',
                        'ip2',
                        'Cisco-IOS-XR-sysadmin-pm', False, is_config=False),
                    _MetaInfoClassMember('ip2', ATTRIBUTE, 'str', 'inet:ipv6-address',
                        None, None,
                        [], [b'((:|[0-9a-fA-F]{0,4}):)([0-9a-fA-F]{0,4}:){0,5}((([0-9a-fA-F]{0,4}:)?(:|[0-9a-fA-F]{0,4}))|(((25[0-5]|2[0-4][0-9]|[01]?[0-9]?[0-9])\\.){3}(25[0-5]|2[0-4][0-9]|[01]?[0-9]?[0-9])))(%[\\p{N}\\p{L}]+)?'],
                        '''                        Second IP address in the selection
                        ''',
                        'ip2',
                        'Cisco-IOS-XR-sysadmin-pm', False, is_config=False),
                ], is_config=False),
            _MetaInfoClassMember('svc-start-time', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Last start date and time
                ''',
                'svc_start_time',
                'Cisco-IOS-XR-sysadmin-pm', False, is_config=False),
            _MetaInfoClassMember('svc-ready-time', ATTRIBUTE, 'str', 'xs:double',
                None, None,
                [], [],
                '''                Time it took to get ready since start time
                ''',
                'svc_ready_time',
                'Cisco-IOS-XR-sysadmin-pm', False, is_config=False),
            _MetaInfoClassMember('svc-haready-time', ATTRIBUTE, 'str', 'xs:double',
                None, None,
                [], [],
                '''                Time it took to get HA-ready since start time
                ''',
                'svc_haready_time',
                'Cisco-IOS-XR-sysadmin-pm', False, is_config=False),
            ],
            'Cisco-IOS-XR-sysadmin-pm',
            'services',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-sysadmin-pm'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_pm',
            is_config=False,
        ),
    },
    'Processes.AllLocations.Name' : {
        'meta_info' : _MetaInfoClass('Processes.AllLocations.Name', REFERENCE_LIST,
            ''' ''',
            False, 
            [
            _MetaInfoClassMember('proc-name', ATTRIBUTE, 'str', 'proc-name-type',
                None, None,
                [], [],
                '''                Name of the process
                ''',
                'proc_name',
                'Cisco-IOS-XR-sysadmin-pm', True, is_config=False),
            _MetaInfoClassMember('instance-id', ATTRIBUTE, 'int', 'instance-id-type',
                None, None,
                [('0', '4294967295')], [],
                '''                Instance identifier
                ''',
                'instance_id',
                'Cisco-IOS-XR-sysadmin-pm', True, is_config=False),
            _MetaInfoClassMember('path', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Process path
                ''',
                'path',
                'Cisco-IOS-XR-sysadmin-pm', False, is_config=False),
            _MetaInfoClassMember('startup-file', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Process startup file
                ''',
                'startup_file',
                'Cisco-IOS-XR-sysadmin-pm', False, is_config=False),
            _MetaInfoClassMember('startup-mode', REFERENCE_ENUM_CLASS, 'StartupMode', 'startupMode',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_pm', 'StartupMode',
                [], [],
                '''                When is a process started
                ''',
                'startup_mode',
                'Cisco-IOS-XR-sysadmin-pm', False, is_config=False),
            _MetaInfoClassMember('heart-beat-timeout', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                Heart beat timeout in sec
                ''',
                'heart_beat_timeout',
                'Cisco-IOS-XR-sysadmin-pm', False, is_config=False),
            _MetaInfoClassMember('last-heart-beat-time', ATTRIBUTE, 'str', 'xs:double',
                None, None,
                [], [],
                '''                How long ago last heart beat was detected
                ''',
                'last_heart_beat_time',
                'Cisco-IOS-XR-sysadmin-pm', False, is_config=False),
            _MetaInfoClassMember('max-restarts', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                Maximum num of restarts
                ''',
                'max_restarts',
                'Cisco-IOS-XR-sysadmin-pm', False, is_config=False),
            _MetaInfoClassMember('respawn-reset-timer', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                Respawn reset timer in min
                ''',
                'respawn_reset_timer',
                'Cisco-IOS-XR-sysadmin-pm', False, is_config=False),
            _MetaInfoClassMember('mandatory', ATTRIBUTE, 'bool', 'boolean',
                None, None,
                [], [],
                '''                Mandatory process
                ''',
                'mandatory',
                'Cisco-IOS-XR-sysadmin-pm', False, is_config=False),
            _MetaInfoClassMember('maint-mode', ATTRIBUTE, 'bool', 'boolean',
                None, None,
                [], [],
                '''                Should run during maintenance mode
                ''',
                'maint_mode',
                'Cisco-IOS-XR-sysadmin-pm', False, is_config=False),
            _MetaInfoClassMember('args', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Process arguments
                ''',
                'args',
                'Cisco-IOS-XR-sysadmin-pm', False, is_config=False),
            _MetaInfoClassMember('proc-state', REFERENCE_ENUM_CLASS, 'ProcessState', 'processState',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_pm', 'ProcessState',
                [], [],
                '''                State of the process
                ''',
                'proc_state',
                'Cisco-IOS-XR-sysadmin-pm', False, is_config=False),
            _MetaInfoClassMember('pid', ATTRIBUTE, 'int', 'int32',
                None, None,
                [('-2147483648', '2147483647')], [],
                '''                Process ID
                ''',
                'pid',
                'Cisco-IOS-XR-sysadmin-pm', False, is_config=False),
            _MetaInfoClassMember('proc-aborted', ATTRIBUTE, 'bool', 'boolean',
                None, None,
                [], [],
                '''                Whether the processes ever aborted
                ''',
                'proc_aborted',
                'Cisco-IOS-XR-sysadmin-pm', False, is_config=False),
            _MetaInfoClassMember('exit-status', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Last exit status/info of the process
                ''',
                'exit_status',
                'Cisco-IOS-XR-sysadmin-pm', False, is_config=False),
            _MetaInfoClassMember('respawns', ATTRIBUTE, 'int', 'int32',
                None, None,
                [('-2147483648', '2147483647')], [],
                '''                Total number of respawns of the process
                ''',
                'respawns',
                'Cisco-IOS-XR-sysadmin-pm', False, is_config=False),
            _MetaInfoClassMember('start-time', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Last start date and time
                ''',
                'start_time',
                'Cisco-IOS-XR-sysadmin-pm', False, is_config=False),
            _MetaInfoClassMember('ready-time', ATTRIBUTE, 'str', 'xs:double',
                None, None,
                [], [],
                '''                Time for ready from start-time
                ''',
                'ready_time',
                'Cisco-IOS-XR-sysadmin-pm', False, is_config=False),
            _MetaInfoClassMember('last-exit-time', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Last exit date and time
                ''',
                'last_exit_time',
                'Cisco-IOS-XR-sysadmin-pm', False, is_config=False),
            _MetaInfoClassMember('services', REFERENCE_LIST, 'Services', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_pm', 'Processes.AllLocations.Name.Services',
                [], [],
                '''                ''',
                'services',
                'Cisco-IOS-XR-sysadmin-pm', False, is_config=False),
            ],
            'Cisco-IOS-XR-sysadmin-pm',
            'name',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-sysadmin-pm'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_pm',
            is_config=False,
        ),
    },
    'Processes.AllLocations' : {
        'meta_info' : _MetaInfoClass('Processes.AllLocations', REFERENCE_LIST,
            ''' ''',
            False, 
            [
            _MetaInfoClassMember('location', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                ''',
                'location',
                'Cisco-IOS-XR-sysadmin-pm', True, is_config=False),
            _MetaInfoClassMember('ip-addr', REFERENCE_UNION, 'str', 'inet:ip-address',
                None, None,
                [], [],
                '''                IP address of the location
                ''',
                'ip_addr',
                'Cisco-IOS-XR-sysadmin-pm', False, [
                    _MetaInfoClassMember('ip-addr', ATTRIBUTE, 'str', 'inet:ipv4-address',
                        None, None,
                        [], [b'(([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])(%[\\p{N}\\p{L}]+)?'],
                        '''                        IP address of the location
                        ''',
                        'ip_addr',
                        'Cisco-IOS-XR-sysadmin-pm', False, is_config=False),
                    _MetaInfoClassMember('ip-addr', ATTRIBUTE, 'str', 'inet:ipv6-address',
                        None, None,
                        [], [b'((:|[0-9a-fA-F]{0,4}):)([0-9a-fA-F]{0,4}:){0,5}((([0-9a-fA-F]{0,4}:)?(:|[0-9a-fA-F]{0,4}))|(((25[0-5]|2[0-4][0-9]|[01]?[0-9]?[0-9])\\.){3}(25[0-5]|2[0-4][0-9]|[01]?[0-9]?[0-9])))(%[\\p{N}\\p{L}]+)?'],
                        '''                        IP address of the location
                        ''',
                        'ip_addr',
                        'Cisco-IOS-XR-sysadmin-pm', False, is_config=False),
                ], is_config=False),
            _MetaInfoClassMember('pcbs', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                Total number of process control blocks
                ''',
                'pcbs',
                'Cisco-IOS-XR-sysadmin-pm', False, is_config=False),
            _MetaInfoClassMember('name', REFERENCE_LIST, 'Name', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_pm', 'Processes.AllLocations.Name',
                [], [],
                '''                ''',
                'name',
                'Cisco-IOS-XR-sysadmin-pm', False, is_config=False),
            ],
            'Cisco-IOS-XR-sysadmin-pm',
            'all-locations',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-sysadmin-pm'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_pm',
            is_config=False,
        ),
    },
    'Processes' : {
        'meta_info' : _MetaInfoClass('Processes', REFERENCE_CLASS,
            '''Process Info''',
            False, 
            [
            _MetaInfoClassMember('all-locations', REFERENCE_LIST, 'AllLocations', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_pm', 'Processes.AllLocations',
                [], [],
                '''                ''',
                'all_locations',
                'Cisco-IOS-XR-sysadmin-pm', False, is_config=False),
            ],
            'Cisco-IOS-XR-sysadmin-pm',
            'processes',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-sysadmin-pm'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_pm',
            is_config=False,
        ),
    },
    'ProcessManager.AllLocationsInfo' : {
        'meta_info' : _MetaInfoClass('ProcessManager.AllLocationsInfo', REFERENCE_LIST,
            ''' ''',
            False, 
            [
            _MetaInfoClassMember('location-info', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                ''',
                'location_info',
                'Cisco-IOS-XR-sysadmin-pm', True, is_config=False),
            _MetaInfoClassMember('ip-addr-info', REFERENCE_UNION, 'str', 'inet:ip-address',
                None, None,
                [], [],
                '''                IP address of the location
                ''',
                'ip_addr_info',
                'Cisco-IOS-XR-sysadmin-pm', False, [
                    _MetaInfoClassMember('ip-addr-info', ATTRIBUTE, 'str', 'inet:ipv4-address',
                        None, None,
                        [], [b'(([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])(%[\\p{N}\\p{L}]+)?'],
                        '''                        IP address of the location
                        ''',
                        'ip_addr_info',
                        'Cisco-IOS-XR-sysadmin-pm', False, is_config=False),
                    _MetaInfoClassMember('ip-addr-info', ATTRIBUTE, 'str', 'inet:ipv6-address',
                        None, None,
                        [], [b'((:|[0-9a-fA-F]{0,4}):)([0-9a-fA-F]{0,4}:){0,5}((([0-9a-fA-F]{0,4}:)?(:|[0-9a-fA-F]{0,4}))|(((25[0-5]|2[0-4][0-9]|[01]?[0-9]?[0-9])\\.){3}(25[0-5]|2[0-4][0-9]|[01]?[0-9]?[0-9])))(%[\\p{N}\\p{L}]+)?'],
                        '''                        IP address of the location
                        ''',
                        'ip_addr_info',
                        'Cisco-IOS-XR-sysadmin-pm', False, is_config=False),
                ], is_config=False),
            _MetaInfoClassMember('pm-start-time', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Last start date and time for PM
                ''',
                'pm_start_time',
                'Cisco-IOS-XR-sysadmin-pm', False, is_config=False),
            _MetaInfoClassMember('mand-proc-down', ATTRIBUTE, 'bool', 'boolean',
                None, None,
                [], [],
                '''                PM in mandatory process down state
                ''',
                'mand_proc_down',
                'Cisco-IOS-XR-sysadmin-pm', False, is_config=False),
            _MetaInfoClassMember('vmm-capi-up', ATTRIBUTE, 'bool', 'boolean',
                None, None,
                [], [],
                '''                Status of CAPI with vm-manager
                ''',
                'vmm_capi_up',
                'Cisco-IOS-XR-sysadmin-pm', False, is_config=False),
            _MetaInfoClassMember('wdmon-capi-up', ATTRIBUTE, 'bool', 'boolean',
                None, None,
                [], [],
                '''                Status of CAPI with wdmon
                ''',
                'wdmon_capi_up',
                'Cisco-IOS-XR-sysadmin-pm', False, is_config=False),
            _MetaInfoClassMember('wdmon-capi-timestamp', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Date and time of last wdmon CAPI connection establish
                ''',
                'wdmon_capi_timestamp',
                'Cisco-IOS-XR-sysadmin-pm', False, is_config=False),
            _MetaInfoClassMember('wdmon-num-capi-connects', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                Number of times wdmon CAPI connection extablished
                ''',
                'wdmon_num_capi_connects',
                'Cisco-IOS-XR-sysadmin-pm', False, is_config=False),
            ],
            'Cisco-IOS-XR-sysadmin-pm',
            'all-locations-info',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-sysadmin-pm'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_pm',
            is_config=False,
        ),
    },
    'ProcessManager' : {
        'meta_info' : _MetaInfoClass('ProcessManager', REFERENCE_CLASS,
            '''Process Manager Info''',
            False, 
            [
            _MetaInfoClassMember('all-locations-info', REFERENCE_LIST, 'AllLocationsInfo', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_pm', 'ProcessManager.AllLocationsInfo',
                [], [],
                '''                ''',
                'all_locations_info',
                'Cisco-IOS-XR-sysadmin-pm', False, is_config=False),
            ],
            'Cisco-IOS-XR-sysadmin-pm',
            'process-manager',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-sysadmin-pm'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_pm',
            is_config=False,
        ),
    },
    'Pm.Pm_.Trace.Location.AllOptions.TraceBlocks' : {
        'meta_info' : _MetaInfoClass('Pm.Pm_.Trace.Location.AllOptions.TraceBlocks', REFERENCE_LIST,
            ''' ''',
            False, 
            [
            _MetaInfoClassMember('data', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Trace output block
                ''',
                'data',
                'Cisco-IOS-XR-sysadmin-pm', False, is_config=False),
            ],
            'Cisco-IOS-XR-sysadmin-pm',
            'trace-blocks',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-sysadmin-pm'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_pm',
            is_config=False,
        ),
    },
    'Pm.Pm_.Trace.Location.AllOptions' : {
        'meta_info' : _MetaInfoClass('Pm.Pm_.Trace.Location.AllOptions', REFERENCE_LIST,
            ''' ''',
            False, 
            [
            _MetaInfoClassMember('option', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                ''',
                'option',
                'Cisco-IOS-XR-sysadmin-pm', True, is_config=False),
            _MetaInfoClassMember('trace-blocks', REFERENCE_LIST, 'TraceBlocks', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_pm', 'Pm.Pm_.Trace.Location.AllOptions.TraceBlocks',
                [], [],
                '''                ''',
                'trace_blocks',
                'Cisco-IOS-XR-sysadmin-pm', False, is_config=False),
            ],
            'Cisco-IOS-XR-sysadmin-pm',
            'all-options',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-sysadmin-pm'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_pm',
            is_config=False,
        ),
    },
    'Pm.Pm_.Trace.Location' : {
        'meta_info' : _MetaInfoClass('Pm.Pm_.Trace.Location', REFERENCE_LIST,
            ''' ''',
            False, 
            [
            _MetaInfoClassMember('location_name', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                ''',
                'location_name',
                'Cisco-IOS-XR-sysadmin-pm', True, is_config=False),
            _MetaInfoClassMember('all-options', REFERENCE_LIST, 'AllOptions', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_pm', 'Pm.Pm_.Trace.Location.AllOptions',
                [], [],
                '''                ''',
                'all_options',
                'Cisco-IOS-XR-sysadmin-pm', False, is_config=False),
            ],
            'Cisco-IOS-XR-sysadmin-pm',
            'location',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-sysadmin-pm'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_pm',
            is_config=False,
        ),
    },
    'Pm.Pm_.Trace' : {
        'meta_info' : _MetaInfoClass('Pm.Pm_.Trace', REFERENCE_LIST,
            '''show traceable processes''',
            False, 
            [
            _MetaInfoClassMember('buffer', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                ''',
                'buffer',
                'Cisco-IOS-XR-sysadmin-pm', True, is_config=False),
            _MetaInfoClassMember('location', REFERENCE_LIST, 'Location', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_pm', 'Pm.Pm_.Trace.Location',
                [], [],
                '''                ''',
                'location',
                'Cisco-IOS-XR-sysadmin-pm', False, is_config=False),
            ],
            'Cisco-IOS-XR-sysadmin-pm',
            'trace',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-sysadmin-pm'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_pm',
            is_config=False,
        ),
    },
    'Pm.Pm_' : {
        'meta_info' : _MetaInfoClass('Pm.Pm_', REFERENCE_CLASS,
            ''' ''',
            False, 
            [
            _MetaInfoClassMember('trace', REFERENCE_LIST, 'Trace', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_pm', 'Pm.Pm_.Trace',
                [], [],
                '''                show traceable processes
                ''',
                'trace',
                'Cisco-IOS-XR-sysadmin-pm', False, is_config=False),
            ],
            'Cisco-IOS-XR-sysadmin-pm',
            'pm',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-sysadmin-pm'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_pm',
            is_config=False,
        ),
    },
    'Pm' : {
        'meta_info' : _MetaInfoClass('Pm', REFERENCE_CLASS,
            ''' ''',
            False, 
            [
            _MetaInfoClassMember('pm', REFERENCE_CLASS, 'Pm_', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_pm', 'Pm.Pm_',
                [], [],
                '''                ''',
                'pm',
                'Cisco-IOS-XR-sysadmin-pm', False, is_config=False),
            ],
            'Cisco-IOS-XR-sysadmin-pm',
            'pm',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-sysadmin-pm'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_pm',
            is_config=False,
        ),
    },
}
_meta_table['Processes.AllLocations.Name.Services']['meta_info'].parent =_meta_table['Processes.AllLocations.Name']['meta_info']
_meta_table['Processes.AllLocations.Name']['meta_info'].parent =_meta_table['Processes.AllLocations']['meta_info']
_meta_table['Processes.AllLocations']['meta_info'].parent =_meta_table['Processes']['meta_info']
_meta_table['ProcessManager.AllLocationsInfo']['meta_info'].parent =_meta_table['ProcessManager']['meta_info']
_meta_table['Pm.Pm_.Trace.Location.AllOptions.TraceBlocks']['meta_info'].parent =_meta_table['Pm.Pm_.Trace.Location.AllOptions']['meta_info']
_meta_table['Pm.Pm_.Trace.Location.AllOptions']['meta_info'].parent =_meta_table['Pm.Pm_.Trace.Location']['meta_info']
_meta_table['Pm.Pm_.Trace.Location']['meta_info'].parent =_meta_table['Pm.Pm_.Trace']['meta_info']
_meta_table['Pm.Pm_.Trace']['meta_info'].parent =_meta_table['Pm.Pm_']['meta_info']
_meta_table['Pm.Pm_']['meta_info'].parent =_meta_table['Pm']['meta_info']
