
'''
This is auto-generated file,
which includes metadata for module Cisco_IOS_XR_sysadmin_show_trace_cm
'''

from ydk._core._dm_meta_info import _MetaInfoClassMember, _MetaInfoClass, _MetaInfoEnum
from ydk._core._dm_meta_info import ATTRIBUTE, REFERENCE_LIST, REFERENCE_LEAFLIST, REFERENCE_BITS, REFERENCE_UNION
from ydk._core._dm_meta_info import REFERENCE_CLASS, REFERENCE_IDENTITY_CLASS, REFERENCE_ENUM_CLASS, ANYXML_CLASS
from ydk._core._importer import _yang_ns

_meta_table = {
    'Cm.Trace.Location.AllOptions.TraceBlocks' : {
        'meta_info' : _MetaInfoClass('Cm.Trace.Location.AllOptions.TraceBlocks', REFERENCE_LIST,
            ''' ''',
            False, 
            [
            _MetaInfoClassMember('data', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Trace output block
                ''',
                'data',
                'Cisco-IOS-XR-sysadmin-show-trace-cm', False, is_config=False),
            ],
            'Cisco-IOS-XR-sysadmin-show-trace-cm',
            'trace-blocks',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-sysadmin-show-trace-cm'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_show_trace_cm',
            is_config=False,
        ),
    },
    'Cm.Trace.Location.AllOptions' : {
        'meta_info' : _MetaInfoClass('Cm.Trace.Location.AllOptions', REFERENCE_LIST,
            ''' ''',
            False, 
            [
            _MetaInfoClassMember('option', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                ''',
                'option',
                'Cisco-IOS-XR-sysadmin-show-trace-cm', True, is_config=False),
            _MetaInfoClassMember('trace-blocks', REFERENCE_LIST, 'TraceBlocks', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_show_trace_cm', 'Cm.Trace.Location.AllOptions.TraceBlocks',
                [], [],
                '''                ''',
                'trace_blocks',
                'Cisco-IOS-XR-sysadmin-show-trace-cm', False, is_config=False),
            ],
            'Cisco-IOS-XR-sysadmin-show-trace-cm',
            'all-options',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-sysadmin-show-trace-cm'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_show_trace_cm',
            is_config=False,
        ),
    },
    'Cm.Trace.Location' : {
        'meta_info' : _MetaInfoClass('Cm.Trace.Location', REFERENCE_LIST,
            ''' ''',
            False, 
            [
            _MetaInfoClassMember('location_name', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                ''',
                'location_name',
                'Cisco-IOS-XR-sysadmin-show-trace-cm', True, is_config=False),
            _MetaInfoClassMember('all-options', REFERENCE_LIST, 'AllOptions', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_show_trace_cm', 'Cm.Trace.Location.AllOptions',
                [], [],
                '''                ''',
                'all_options',
                'Cisco-IOS-XR-sysadmin-show-trace-cm', False, is_config=False),
            ],
            'Cisco-IOS-XR-sysadmin-show-trace-cm',
            'location',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-sysadmin-show-trace-cm'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_show_trace_cm',
            is_config=False,
        ),
    },
    'Cm.Trace' : {
        'meta_info' : _MetaInfoClass('Cm.Trace', REFERENCE_LIST,
            '''show traceable processes''',
            False, 
            [
            _MetaInfoClassMember('buffer', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                ''',
                'buffer',
                'Cisco-IOS-XR-sysadmin-show-trace-cm', True, is_config=False),
            _MetaInfoClassMember('location', REFERENCE_LIST, 'Location', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_show_trace_cm', 'Cm.Trace.Location',
                [], [],
                '''                ''',
                'location',
                'Cisco-IOS-XR-sysadmin-show-trace-cm', False, is_config=False),
            ],
            'Cisco-IOS-XR-sysadmin-show-trace-cm',
            'trace',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-sysadmin-show-trace-cm'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_show_trace_cm',
            is_config=False,
        ),
    },
    'Cm.Lsp.LspdbLocations.Lspdbi' : {
        'meta_info' : _MetaInfoClass('Cm.Lsp.LspdbLocations.Lspdbi', REFERENCE_LIST,
            ''' ''',
            False, 
            [
            _MetaInfoClassMember('lsp_id', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                LSP System ID
                ''',
                'lsp_id',
                'Cisco-IOS-XR-sysadmin-cm', True, is_config=False),
            _MetaInfoClassMember('lsp_area_type', REFERENCE_ENUM_CLASS, 'AreaType', 'area_type',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_cm', 'AreaType',
                [], [],
                '''                LSP Area Type
                ''',
                'lsp_area_type',
                'Cisco-IOS-XR-sysadmin-cm', True, is_config=False),
            _MetaInfoClassMember('lsp_sequence', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                LSP sequence number
                ''',
                'lsp_sequence',
                'Cisco-IOS-XR-sysadmin-cm', False, is_config=False),
            _MetaInfoClassMember('lsp_core', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                LSP core data bits
                ''',
                'lsp_core',
                'Cisco-IOS-XR-sysadmin-cm', False, is_config=False),
            _MetaInfoClassMember('lsp_tlvs', REFERENCE_LEAFLIST, 'str', 'string',
                None, None,
                [], [],
                '''                LSP TLV data
                ''',
                'lsp_tlvs',
                'Cisco-IOS-XR-sysadmin-cm', False, is_config=False),
            ],
            'Cisco-IOS-XR-sysadmin-cm',
            'lspdbi',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-sysadmin-cm'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_show_trace_cm',
            is_config=False,
        ),
    },
    'Cm.Lsp.LspdbLocations' : {
        'meta_info' : _MetaInfoClass('Cm.Lsp.LspdbLocations', REFERENCE_LIST,
            ''' ''',
            False, 
            [
            _MetaInfoClassMember('lspdb_location', ATTRIBUTE, 'str', 'calvados:location-id',
                None, None,
                [], [b'((([bB][0-9])/(([a-zA-Z]){2}\\d{1,2}))|(([fF][0-7])/(([a-zA-Z]){2}\\d{1,2}))|((0?[0-9]|1[0-5])/((([a-zA-Z]){2,3})?\\d{1,2})))(/[cC][pP][uU]0)?'],
                '''                ''',
                'lspdb_location',
                'Cisco-IOS-XR-sysadmin-cm', True, is_config=False),
            _MetaInfoClassMember('lspdbi', REFERENCE_LIST, 'Lspdbi', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_show_trace_cm', 'Cm.Lsp.LspdbLocations.Lspdbi',
                [], [],
                '''                ''',
                'lspdbi',
                'Cisco-IOS-XR-sysadmin-cm', False, is_config=False),
            ],
            'Cisco-IOS-XR-sysadmin-cm',
            'lspdb_locations',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-sysadmin-cm'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_show_trace_cm',
            is_config=False,
        ),
    },
    'Cm.Lsp' : {
        'meta_info' : _MetaInfoClass('Cm.Lsp', REFERENCE_CLASS,
            '''System Admin Manager lspdb of a location''',
            False, 
            [
            _MetaInfoClassMember('lspdb_locations', REFERENCE_LIST, 'LspdbLocations', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_show_trace_cm', 'Cm.Lsp.LspdbLocations',
                [], [],
                '''                ''',
                'lspdb_locations',
                'Cisco-IOS-XR-sysadmin-cm', False, is_config=False),
            ],
            'Cisco-IOS-XR-sysadmin-cm',
            'lsp',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-sysadmin-cm'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_show_trace_cm',
            is_config=False,
        ),
    },
    'Cm' : {
        'meta_info' : _MetaInfoClass('Cm', REFERENCE_CLASS,
            ''' ''',
            False, 
            [
            _MetaInfoClassMember('trace', REFERENCE_LIST, 'Trace', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_show_trace_cm', 'Cm.Trace',
                [], [],
                '''                show traceable processes
                ''',
                'trace',
                'Cisco-IOS-XR-sysadmin-show-trace-cm', False, is_config=False),
            _MetaInfoClassMember('lsp', REFERENCE_CLASS, 'Lsp', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_show_trace_cm', 'Cm.Lsp',
                [], [],
                '''                System Admin Manager lspdb of a location
                ''',
                'lsp',
                'Cisco-IOS-XR-sysadmin-cm', False, is_config=False),
            ],
            'Cisco-IOS-XR-sysadmin-show-trace-cm',
            'cm',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-sysadmin-show-trace-cm'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_show_trace_cm',
            is_config=False,
        ),
    },
}
_meta_table['Cm.Trace.Location.AllOptions.TraceBlocks']['meta_info'].parent =_meta_table['Cm.Trace.Location.AllOptions']['meta_info']
_meta_table['Cm.Trace.Location.AllOptions']['meta_info'].parent =_meta_table['Cm.Trace.Location']['meta_info']
_meta_table['Cm.Trace.Location']['meta_info'].parent =_meta_table['Cm.Trace']['meta_info']
_meta_table['Cm.Lsp.LspdbLocations.Lspdbi']['meta_info'].parent =_meta_table['Cm.Lsp.LspdbLocations']['meta_info']
_meta_table['Cm.Lsp.LspdbLocations']['meta_info'].parent =_meta_table['Cm.Lsp']['meta_info']
_meta_table['Cm.Trace']['meta_info'].parent =_meta_table['Cm']['meta_info']
_meta_table['Cm.Lsp']['meta_info'].parent =_meta_table['Cm']['meta_info']
