
'''
This is auto-generated file,
which includes metadata for module Cisco_IOS_XR_sysadmin_show_inv
'''

from ydk._core._dm_meta_info import _MetaInfoClassMember, _MetaInfoClass, _MetaInfoEnum
from ydk._core._dm_meta_info import ATTRIBUTE, REFERENCE_LIST, REFERENCE_LEAFLIST, REFERENCE_BITS, REFERENCE_UNION
from ydk._core._dm_meta_info import REFERENCE_CLASS, REFERENCE_IDENTITY_CLASS, REFERENCE_ENUM_CLASS, ANYXML_CLASS
from ydk._core._importer import _yang_ns

_meta_table = {
    'Inventory.Location' : {
        'meta_info' : _MetaInfoClass('Inventory.Location', REFERENCE_LIST,
            ''' ''',
            False, 
            [
            _MetaInfoClassMember('loc', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Node id of the entity
                ''',
                'loc',
                'Cisco-IOS-XR-sysadmin-show-inv', True, is_config=False),
            _MetaInfoClassMember('name', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Name of the entity
                ''',
                'name',
                'Cisco-IOS-XR-sysadmin-show-inv', False, is_config=False),
            _MetaInfoClassMember('Description', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Description of the entity
                ''',
                'description',
                'Cisco-IOS-XR-sysadmin-show-inv', False, is_config=False),
            _MetaInfoClassMember('PID', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Product ID of the entity
                ''',
                'pid',
                'Cisco-IOS-XR-sysadmin-show-inv', False, is_config=False),
            _MetaInfoClassMember('VID', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Version ID of the entity
                ''',
                'vid',
                'Cisco-IOS-XR-sysadmin-show-inv', False, is_config=False),
            _MetaInfoClassMember('SN', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Serial Numbe of the entity
                ''',
                'sn',
                'Cisco-IOS-XR-sysadmin-show-inv', False, is_config=False),
            _MetaInfoClassMember('index', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                Index for the entity
                ''',
                'index',
                'Cisco-IOS-XR-sysadmin-show-inv', False, is_config=False),
            ],
            'Cisco-IOS-XR-sysadmin-show-inv',
            'location',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-sysadmin-show-inv'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_show_inv',
            is_config=False,
        ),
    },
    'Inventory.All' : {
        'meta_info' : _MetaInfoClass('Inventory.All', REFERENCE_LIST,
            ''' ''',
            False, 
            [
            _MetaInfoClassMember('index', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                Index for the entity
                ''',
                'index',
                'Cisco-IOS-XR-sysadmin-show-inv', True, is_config=False),
            _MetaInfoClassMember('name', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Name of the entity
                ''',
                'name',
                'Cisco-IOS-XR-sysadmin-show-inv', False, is_config=False),
            _MetaInfoClassMember('Description', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Description of the entity
                ''',
                'description',
                'Cisco-IOS-XR-sysadmin-show-inv', False, is_config=False),
            _MetaInfoClassMember('PID', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Product ID of the entity
                ''',
                'pid',
                'Cisco-IOS-XR-sysadmin-show-inv', False, is_config=False),
            _MetaInfoClassMember('VID', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Version ID of the entity
                ''',
                'vid',
                'Cisco-IOS-XR-sysadmin-show-inv', False, is_config=False),
            _MetaInfoClassMember('SN', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Serial Numbe of the entity
                ''',
                'sn',
                'Cisco-IOS-XR-sysadmin-show-inv', False, is_config=False),
            _MetaInfoClassMember('loc', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Node id of the entity
                ''',
                'loc',
                'Cisco-IOS-XR-sysadmin-show-inv', False, is_config=False),
            ],
            'Cisco-IOS-XR-sysadmin-show-inv',
            'all',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-sysadmin-show-inv'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_show_inv',
            is_config=False,
        ),
    },
    'Inventory.Chassis' : {
        'meta_info' : _MetaInfoClass('Inventory.Chassis', REFERENCE_LIST,
            ''' ''',
            False, 
            [
            _MetaInfoClassMember('index', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                Index for the entity
                ''',
                'index',
                'Cisco-IOS-XR-sysadmin-show-inv', True, is_config=False),
            _MetaInfoClassMember('name', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Name of the entity
                ''',
                'name',
                'Cisco-IOS-XR-sysadmin-show-inv', False, is_config=False),
            _MetaInfoClassMember('Description', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Description of the entity
                ''',
                'description',
                'Cisco-IOS-XR-sysadmin-show-inv', False, is_config=False),
            _MetaInfoClassMember('PID', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Product ID of the entity
                ''',
                'pid',
                'Cisco-IOS-XR-sysadmin-show-inv', False, is_config=False),
            _MetaInfoClassMember('VID', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Version ID of the entity
                ''',
                'vid',
                'Cisco-IOS-XR-sysadmin-show-inv', False, is_config=False),
            _MetaInfoClassMember('SN', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Serial Numbe of the entity
                ''',
                'sn',
                'Cisco-IOS-XR-sysadmin-show-inv', False, is_config=False),
            _MetaInfoClassMember('loc', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Node id of the entity
                ''',
                'loc',
                'Cisco-IOS-XR-sysadmin-show-inv', False, is_config=False),
            ],
            'Cisco-IOS-XR-sysadmin-show-inv',
            'chassis',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-sysadmin-show-inv'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_show_inv',
            is_config=False,
        ),
    },
    'Inventory.Power' : {
        'meta_info' : _MetaInfoClass('Inventory.Power', REFERENCE_LIST,
            ''' ''',
            False, 
            [
            _MetaInfoClassMember('index', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                Index for the entity
                ''',
                'index',
                'Cisco-IOS-XR-sysadmin-show-inv', True, is_config=False),
            _MetaInfoClassMember('name', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Name of the entity
                ''',
                'name',
                'Cisco-IOS-XR-sysadmin-show-inv', False, is_config=False),
            _MetaInfoClassMember('Description', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Description of the entity
                ''',
                'description',
                'Cisco-IOS-XR-sysadmin-show-inv', False, is_config=False),
            _MetaInfoClassMember('PID', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Product ID of the entity
                ''',
                'pid',
                'Cisco-IOS-XR-sysadmin-show-inv', False, is_config=False),
            _MetaInfoClassMember('VID', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Version ID of the entity
                ''',
                'vid',
                'Cisco-IOS-XR-sysadmin-show-inv', False, is_config=False),
            _MetaInfoClassMember('SN', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Serial Numbe of the entity
                ''',
                'sn',
                'Cisco-IOS-XR-sysadmin-show-inv', False, is_config=False),
            _MetaInfoClassMember('loc', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Node id of the entity
                ''',
                'loc',
                'Cisco-IOS-XR-sysadmin-show-inv', False, is_config=False),
            ],
            'Cisco-IOS-XR-sysadmin-show-inv',
            'power',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-sysadmin-show-inv'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_show_inv',
            is_config=False,
        ),
    },
    'Inventory.Fan' : {
        'meta_info' : _MetaInfoClass('Inventory.Fan', REFERENCE_LIST,
            ''' ''',
            False, 
            [
            _MetaInfoClassMember('index', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                Index for the entity
                ''',
                'index',
                'Cisco-IOS-XR-sysadmin-show-inv', True, is_config=False),
            _MetaInfoClassMember('name', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Name of the entity
                ''',
                'name',
                'Cisco-IOS-XR-sysadmin-show-inv', False, is_config=False),
            _MetaInfoClassMember('Description', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Description of the entity
                ''',
                'description',
                'Cisco-IOS-XR-sysadmin-show-inv', False, is_config=False),
            _MetaInfoClassMember('PID', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Product ID of the entity
                ''',
                'pid',
                'Cisco-IOS-XR-sysadmin-show-inv', False, is_config=False),
            _MetaInfoClassMember('VID', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Version ID of the entity
                ''',
                'vid',
                'Cisco-IOS-XR-sysadmin-show-inv', False, is_config=False),
            _MetaInfoClassMember('SN', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Serial Numbe of the entity
                ''',
                'sn',
                'Cisco-IOS-XR-sysadmin-show-inv', False, is_config=False),
            _MetaInfoClassMember('loc', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Node id of the entity
                ''',
                'loc',
                'Cisco-IOS-XR-sysadmin-show-inv', False, is_config=False),
            ],
            'Cisco-IOS-XR-sysadmin-show-inv',
            'fan',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-sysadmin-show-inv'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_show_inv',
            is_config=False,
        ),
    },
    'Inventory.Raw' : {
        'meta_info' : _MetaInfoClass('Inventory.Raw', REFERENCE_LIST,
            ''' ''',
            False, 
            [
            _MetaInfoClassMember('index', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                Index for the entity
                ''',
                'index',
                'Cisco-IOS-XR-sysadmin-show-inv', True, is_config=False),
            _MetaInfoClassMember('name', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Name of the entity
                ''',
                'name',
                'Cisco-IOS-XR-sysadmin-show-inv', False, is_config=False),
            _MetaInfoClassMember('Description', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Description of the entity
                ''',
                'description',
                'Cisco-IOS-XR-sysadmin-show-inv', False, is_config=False),
            _MetaInfoClassMember('PID', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Product ID of the entity
                ''',
                'pid',
                'Cisco-IOS-XR-sysadmin-show-inv', False, is_config=False),
            _MetaInfoClassMember('VID', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Version ID of the entity
                ''',
                'vid',
                'Cisco-IOS-XR-sysadmin-show-inv', False, is_config=False),
            _MetaInfoClassMember('SN', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Serial Numbe of the entity
                ''',
                'sn',
                'Cisco-IOS-XR-sysadmin-show-inv', False, is_config=False),
            _MetaInfoClassMember('loc', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Node id of the entity
                ''',
                'loc',
                'Cisco-IOS-XR-sysadmin-show-inv', False, is_config=False),
            ],
            'Cisco-IOS-XR-sysadmin-show-inv',
            'raw',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-sysadmin-show-inv'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_show_inv',
            is_config=False,
        ),
    },
    'Inventory' : {
        'meta_info' : _MetaInfoClass('Inventory', REFERENCE_CLASS,
            '''show inventory''',
            False, 
            [
            _MetaInfoClassMember('location', REFERENCE_LIST, 'Location', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_show_inv', 'Inventory.Location',
                [], [],
                '''                ''',
                'location',
                'Cisco-IOS-XR-sysadmin-show-inv', False, is_config=False),
            _MetaInfoClassMember('all', REFERENCE_LIST, 'All', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_show_inv', 'Inventory.All',
                [], [],
                '''                ''',
                'all',
                'Cisco-IOS-XR-sysadmin-show-inv', False, is_config=False),
            _MetaInfoClassMember('chassis', REFERENCE_LIST, 'Chassis', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_show_inv', 'Inventory.Chassis',
                [], [],
                '''                ''',
                'chassis',
                'Cisco-IOS-XR-sysadmin-show-inv', False, is_config=False),
            _MetaInfoClassMember('power', REFERENCE_LIST, 'Power', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_show_inv', 'Inventory.Power',
                [], [],
                '''                ''',
                'power',
                'Cisco-IOS-XR-sysadmin-show-inv', False, is_config=False),
            _MetaInfoClassMember('fan', REFERENCE_LIST, 'Fan', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_show_inv', 'Inventory.Fan',
                [], [],
                '''                ''',
                'fan',
                'Cisco-IOS-XR-sysadmin-show-inv', False, is_config=False),
            _MetaInfoClassMember('raw', REFERENCE_LIST, 'Raw', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_show_inv', 'Inventory.Raw',
                [], [],
                '''                ''',
                'raw',
                'Cisco-IOS-XR-sysadmin-show-inv', False, is_config=False),
            ],
            'Cisco-IOS-XR-sysadmin-show-inv',
            'inventory',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-sysadmin-show-inv'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_show_inv',
            is_config=False,
        ),
    },
}
_meta_table['Inventory.Location']['meta_info'].parent =_meta_table['Inventory']['meta_info']
_meta_table['Inventory.All']['meta_info'].parent =_meta_table['Inventory']['meta_info']
_meta_table['Inventory.Chassis']['meta_info'].parent =_meta_table['Inventory']['meta_info']
_meta_table['Inventory.Power']['meta_info'].parent =_meta_table['Inventory']['meta_info']
_meta_table['Inventory.Fan']['meta_info'].parent =_meta_table['Inventory']['meta_info']
_meta_table['Inventory.Raw']['meta_info'].parent =_meta_table['Inventory']['meta_info']
