
'''
This is auto-generated file,
which includes metadata for module Cisco_IOS_XR_mpls_vpn_oper
'''

from ydk._core._dm_meta_info import _MetaInfoClassMember, _MetaInfoClass, _MetaInfoEnum
from ydk._core._dm_meta_info import ATTRIBUTE, REFERENCE_LIST, REFERENCE_LEAFLIST, REFERENCE_BITS, REFERENCE_UNION
from ydk._core._dm_meta_info import REFERENCE_CLASS, REFERENCE_IDENTITY_CLASS, REFERENCE_ENUM_CLASS, ANYXML_CLASS
from ydk._core._importer import _yang_ns

_meta_table = {
    'MplsVpnRt' : _MetaInfoEnum('MplsVpnRt',
        'ydk.models.cisco_ios_xr.Cisco_IOS_XR_mpls_vpn_oper', 'MplsVpnRt',
        '''Layer 3 VPN Route Target Type''',
        {
            'import':'import_',
            'export':'export',
            'both':'both',
        }, 'Cisco-IOS-XR-mpls-vpn-oper', _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-mpls-vpn-oper']),
    'MplsVpnSafi' : _MetaInfoEnum('MplsVpnSafi',
        'ydk.models.cisco_ios_xr.Cisco_IOS_XR_mpls_vpn_oper', 'MplsVpnSafi',
        '''Layer 3 VPN Sub-Address Family Type''',
        {
            'unicast':'unicast',
            'multicast':'multicast',
            'flowspec':'flowspec',
        }, 'Cisco-IOS-XR-mpls-vpn-oper', _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-mpls-vpn-oper']),
    'MplsVpnAfi' : _MetaInfoEnum('MplsVpnAfi',
        'ydk.models.cisco_ios_xr.Cisco_IOS_XR_mpls_vpn_oper', 'MplsVpnAfi',
        '''Layer 3 VPN Address Family Type''',
        {
            'ipv4':'ipv4',
            'ipv6':'ipv6',
        }, 'Cisco-IOS-XR-mpls-vpn-oper', _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-mpls-vpn-oper']),
    'L3vpn.InvalidVrfs.InvalidVrf.Interface' : {
        'meta_info' : _MetaInfoClass('L3vpn.InvalidVrfs.InvalidVrf.Interface', REFERENCE_LIST,
            '''Interfaces in VRF''',
            False, 
            [
            _MetaInfoClassMember('interface-name', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Interface Name
                ''',
                'interface_name',
                'Cisco-IOS-XR-mpls-vpn-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-mpls-vpn-oper',
            'interface',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-mpls-vpn-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_mpls_vpn_oper',
            is_config=False,
        ),
    },
    'L3vpn.InvalidVrfs.InvalidVrf.Af.RouteTarget' : {
        'meta_info' : _MetaInfoClass('L3vpn.InvalidVrfs.InvalidVrf.Af.RouteTarget', REFERENCE_LIST,
            '''Route Targets''',
            False, 
            [
            _MetaInfoClassMember('route-target-type', REFERENCE_ENUM_CLASS, 'MplsVpnRt', 'Mpls-vpn-rt',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_mpls_vpn_oper', 'MplsVpnRt',
                [], [],
                '''                Route Target Type
                ''',
                'route_target_type',
                'Cisco-IOS-XR-mpls-vpn-oper', False, is_config=False),
            _MetaInfoClassMember('route-target-value', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Route Target Value
                ''',
                'route_target_value',
                'Cisco-IOS-XR-mpls-vpn-oper', False, is_config=False),
            _MetaInfoClassMember('af-name', REFERENCE_ENUM_CLASS, 'MplsVpnAfi', 'Mpls-vpn-afi',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_mpls_vpn_oper', 'MplsVpnAfi',
                [], [],
                '''                AF name
                ''',
                'af_name',
                'Cisco-IOS-XR-mpls-vpn-oper', False, is_config=False),
            _MetaInfoClassMember('saf-name', REFERENCE_ENUM_CLASS, 'MplsVpnSafi', 'Mpls-vpn-safi',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_mpls_vpn_oper', 'MplsVpnSafi',
                [], [],
                '''                SAF name
                ''',
                'saf_name',
                'Cisco-IOS-XR-mpls-vpn-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-mpls-vpn-oper',
            'route-target',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-mpls-vpn-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_mpls_vpn_oper',
            is_config=False,
        ),
    },
    'L3vpn.InvalidVrfs.InvalidVrf.Af' : {
        'meta_info' : _MetaInfoClass('L3vpn.InvalidVrfs.InvalidVrf.Af', REFERENCE_LIST,
            '''AF/SAF information''',
            False, 
            [
            _MetaInfoClassMember('af-name', REFERENCE_ENUM_CLASS, 'MplsVpnAfi', 'Mpls-vpn-afi',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_mpls_vpn_oper', 'MplsVpnAfi',
                [], [],
                '''                AF name
                ''',
                'af_name',
                'Cisco-IOS-XR-mpls-vpn-oper', False, is_config=False),
            _MetaInfoClassMember('saf-name', REFERENCE_ENUM_CLASS, 'MplsVpnSafi', 'Mpls-vpn-safi',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_mpls_vpn_oper', 'MplsVpnSafi',
                [], [],
                '''                SAF name
                ''',
                'saf_name',
                'Cisco-IOS-XR-mpls-vpn-oper', False, is_config=False),
            _MetaInfoClassMember('import-route-policy', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Import Route Policy
                ''',
                'import_route_policy',
                'Cisco-IOS-XR-mpls-vpn-oper', False, is_config=False),
            _MetaInfoClassMember('export-route-policy', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Export Route Policy
                ''',
                'export_route_policy',
                'Cisco-IOS-XR-mpls-vpn-oper', False, is_config=False),
            _MetaInfoClassMember('route-target', REFERENCE_LIST, 'RouteTarget', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_mpls_vpn_oper', 'L3vpn.InvalidVrfs.InvalidVrf.Af.RouteTarget',
                [], [],
                '''                Route Targets
                ''',
                'route_target',
                'Cisco-IOS-XR-mpls-vpn-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-mpls-vpn-oper',
            'af',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-mpls-vpn-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_mpls_vpn_oper',
            is_config=False,
        ),
    },
    'L3vpn.InvalidVrfs.InvalidVrf' : {
        'meta_info' : _MetaInfoClass('L3vpn.InvalidVrfs.InvalidVrf', REFERENCE_LIST,
            '''Invalid VRF (VRF that is forward referenced)''',
            False, 
            [
            _MetaInfoClassMember('vrf-name', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                The Name for an invalid VRF
                ''',
                'vrf_name',
                'Cisco-IOS-XR-mpls-vpn-oper', True, is_config=False),
            _MetaInfoClassMember('vrf-name-xr', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                VRF Name
                ''',
                'vrf_name_xr',
                'Cisco-IOS-XR-mpls-vpn-oper', False, is_config=False),
            _MetaInfoClassMember('vrf-description', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                VRF Description
                ''',
                'vrf_description',
                'Cisco-IOS-XR-mpls-vpn-oper', False, is_config=False),
            _MetaInfoClassMember('route-distinguisher', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Route Distinguisher
                ''',
                'route_distinguisher',
                'Cisco-IOS-XR-mpls-vpn-oper', False, is_config=False),
            _MetaInfoClassMember('is-big-vrf', ATTRIBUTE, 'bool', 'boolean',
                None, None,
                [], [],
                '''                VRF mode information
                ''',
                'is_big_vrf',
                'Cisco-IOS-XR-mpls-vpn-oper', False, is_config=False),
            _MetaInfoClassMember('interface', REFERENCE_LIST, 'Interface', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_mpls_vpn_oper', 'L3vpn.InvalidVrfs.InvalidVrf.Interface',
                [], [],
                '''                Interfaces in VRF
                ''',
                'interface',
                'Cisco-IOS-XR-mpls-vpn-oper', False, is_config=False),
            _MetaInfoClassMember('af', REFERENCE_LIST, 'Af', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_mpls_vpn_oper', 'L3vpn.InvalidVrfs.InvalidVrf.Af',
                [], [],
                '''                AF/SAF information
                ''',
                'af',
                'Cisco-IOS-XR-mpls-vpn-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-mpls-vpn-oper',
            'invalid-vrf',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-mpls-vpn-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_mpls_vpn_oper',
            is_config=False,
        ),
    },
    'L3vpn.InvalidVrfs' : {
        'meta_info' : _MetaInfoClass('L3vpn.InvalidVrfs', REFERENCE_CLASS,
            '''Invalid VRF Table (VRFs that are forward
referenced)''',
            False, 
            [
            _MetaInfoClassMember('invalid-vrf', REFERENCE_LIST, 'InvalidVrf', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_mpls_vpn_oper', 'L3vpn.InvalidVrfs.InvalidVrf',
                [], [],
                '''                Invalid VRF (VRF that is forward referenced)
                ''',
                'invalid_vrf',
                'Cisco-IOS-XR-mpls-vpn-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-mpls-vpn-oper',
            'invalid-vrfs',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-mpls-vpn-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_mpls_vpn_oper',
            is_config=False,
        ),
    },
    'L3vpn.Vrfs.Vrf.Interface' : {
        'meta_info' : _MetaInfoClass('L3vpn.Vrfs.Vrf.Interface', REFERENCE_LIST,
            '''Interfaces in VRF''',
            False, 
            [
            _MetaInfoClassMember('interface-name', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Interface Name
                ''',
                'interface_name',
                'Cisco-IOS-XR-mpls-vpn-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-mpls-vpn-oper',
            'interface',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-mpls-vpn-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_mpls_vpn_oper',
            is_config=False,
        ),
    },
    'L3vpn.Vrfs.Vrf.Af.RouteTarget' : {
        'meta_info' : _MetaInfoClass('L3vpn.Vrfs.Vrf.Af.RouteTarget', REFERENCE_LIST,
            '''Route Targets''',
            False, 
            [
            _MetaInfoClassMember('route-target-type', REFERENCE_ENUM_CLASS, 'MplsVpnRt', 'Mpls-vpn-rt',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_mpls_vpn_oper', 'MplsVpnRt',
                [], [],
                '''                Route Target Type
                ''',
                'route_target_type',
                'Cisco-IOS-XR-mpls-vpn-oper', False, is_config=False),
            _MetaInfoClassMember('route-target-value', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Route Target Value
                ''',
                'route_target_value',
                'Cisco-IOS-XR-mpls-vpn-oper', False, is_config=False),
            _MetaInfoClassMember('af-name', REFERENCE_ENUM_CLASS, 'MplsVpnAfi', 'Mpls-vpn-afi',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_mpls_vpn_oper', 'MplsVpnAfi',
                [], [],
                '''                AF name
                ''',
                'af_name',
                'Cisco-IOS-XR-mpls-vpn-oper', False, is_config=False),
            _MetaInfoClassMember('saf-name', REFERENCE_ENUM_CLASS, 'MplsVpnSafi', 'Mpls-vpn-safi',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_mpls_vpn_oper', 'MplsVpnSafi',
                [], [],
                '''                SAF name
                ''',
                'saf_name',
                'Cisco-IOS-XR-mpls-vpn-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-mpls-vpn-oper',
            'route-target',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-mpls-vpn-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_mpls_vpn_oper',
            is_config=False,
        ),
    },
    'L3vpn.Vrfs.Vrf.Af' : {
        'meta_info' : _MetaInfoClass('L3vpn.Vrfs.Vrf.Af', REFERENCE_LIST,
            '''AF/SAF information''',
            False, 
            [
            _MetaInfoClassMember('af-name', REFERENCE_ENUM_CLASS, 'MplsVpnAfi', 'Mpls-vpn-afi',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_mpls_vpn_oper', 'MplsVpnAfi',
                [], [],
                '''                AF name
                ''',
                'af_name',
                'Cisco-IOS-XR-mpls-vpn-oper', False, is_config=False),
            _MetaInfoClassMember('saf-name', REFERENCE_ENUM_CLASS, 'MplsVpnSafi', 'Mpls-vpn-safi',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_mpls_vpn_oper', 'MplsVpnSafi',
                [], [],
                '''                SAF name
                ''',
                'saf_name',
                'Cisco-IOS-XR-mpls-vpn-oper', False, is_config=False),
            _MetaInfoClassMember('import-route-policy', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Import Route Policy
                ''',
                'import_route_policy',
                'Cisco-IOS-XR-mpls-vpn-oper', False, is_config=False),
            _MetaInfoClassMember('export-route-policy', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Export Route Policy
                ''',
                'export_route_policy',
                'Cisco-IOS-XR-mpls-vpn-oper', False, is_config=False),
            _MetaInfoClassMember('route-target', REFERENCE_LIST, 'RouteTarget', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_mpls_vpn_oper', 'L3vpn.Vrfs.Vrf.Af.RouteTarget',
                [], [],
                '''                Route Targets
                ''',
                'route_target',
                'Cisco-IOS-XR-mpls-vpn-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-mpls-vpn-oper',
            'af',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-mpls-vpn-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_mpls_vpn_oper',
            is_config=False,
        ),
    },
    'L3vpn.Vrfs.Vrf' : {
        'meta_info' : _MetaInfoClass('L3vpn.Vrfs.Vrf', REFERENCE_LIST,
            '''VRF''',
            False, 
            [
            _MetaInfoClassMember('vrf-name', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                The Name for a VRF
                ''',
                'vrf_name',
                'Cisco-IOS-XR-mpls-vpn-oper', True, is_config=False),
            _MetaInfoClassMember('vrf-name-xr', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                VRF Name
                ''',
                'vrf_name_xr',
                'Cisco-IOS-XR-mpls-vpn-oper', False, is_config=False),
            _MetaInfoClassMember('vrf-description', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                VRF Description
                ''',
                'vrf_description',
                'Cisco-IOS-XR-mpls-vpn-oper', False, is_config=False),
            _MetaInfoClassMember('route-distinguisher', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Route Distinguisher
                ''',
                'route_distinguisher',
                'Cisco-IOS-XR-mpls-vpn-oper', False, is_config=False),
            _MetaInfoClassMember('is-big-vrf', ATTRIBUTE, 'bool', 'boolean',
                None, None,
                [], [],
                '''                VRF mode information
                ''',
                'is_big_vrf',
                'Cisco-IOS-XR-mpls-vpn-oper', False, is_config=False),
            _MetaInfoClassMember('interface', REFERENCE_LIST, 'Interface', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_mpls_vpn_oper', 'L3vpn.Vrfs.Vrf.Interface',
                [], [],
                '''                Interfaces in VRF
                ''',
                'interface',
                'Cisco-IOS-XR-mpls-vpn-oper', False, is_config=False),
            _MetaInfoClassMember('af', REFERENCE_LIST, 'Af', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_mpls_vpn_oper', 'L3vpn.Vrfs.Vrf.Af',
                [], [],
                '''                AF/SAF information
                ''',
                'af',
                'Cisco-IOS-XR-mpls-vpn-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-mpls-vpn-oper',
            'vrf',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-mpls-vpn-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_mpls_vpn_oper',
            is_config=False,
        ),
    },
    'L3vpn.Vrfs' : {
        'meta_info' : _MetaInfoClass('L3vpn.Vrfs', REFERENCE_CLASS,
            '''VRF Table''',
            False, 
            [
            _MetaInfoClassMember('vrf', REFERENCE_LIST, 'Vrf', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_mpls_vpn_oper', 'L3vpn.Vrfs.Vrf',
                [], [],
                '''                VRF
                ''',
                'vrf',
                'Cisco-IOS-XR-mpls-vpn-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-mpls-vpn-oper',
            'vrfs',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-mpls-vpn-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_mpls_vpn_oper',
            is_config=False,
        ),
    },
    'L3vpn' : {
        'meta_info' : _MetaInfoClass('L3vpn', REFERENCE_CLASS,
            '''L3VPN operational data''',
            False, 
            [
            _MetaInfoClassMember('invalid-vrfs', REFERENCE_CLASS, 'InvalidVrfs', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_mpls_vpn_oper', 'L3vpn.InvalidVrfs',
                [], [],
                '''                Invalid VRF Table (VRFs that are forward
                referenced)
                ''',
                'invalid_vrfs',
                'Cisco-IOS-XR-mpls-vpn-oper', False, is_config=False),
            _MetaInfoClassMember('vrfs', REFERENCE_CLASS, 'Vrfs', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_mpls_vpn_oper', 'L3vpn.Vrfs',
                [], [],
                '''                VRF Table
                ''',
                'vrfs',
                'Cisco-IOS-XR-mpls-vpn-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-mpls-vpn-oper',
            'l3vpn',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-mpls-vpn-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_mpls_vpn_oper',
            is_config=False,
        ),
    },
}
_meta_table['L3vpn.InvalidVrfs.InvalidVrf.Af.RouteTarget']['meta_info'].parent =_meta_table['L3vpn.InvalidVrfs.InvalidVrf.Af']['meta_info']
_meta_table['L3vpn.InvalidVrfs.InvalidVrf.Interface']['meta_info'].parent =_meta_table['L3vpn.InvalidVrfs.InvalidVrf']['meta_info']
_meta_table['L3vpn.InvalidVrfs.InvalidVrf.Af']['meta_info'].parent =_meta_table['L3vpn.InvalidVrfs.InvalidVrf']['meta_info']
_meta_table['L3vpn.InvalidVrfs.InvalidVrf']['meta_info'].parent =_meta_table['L3vpn.InvalidVrfs']['meta_info']
_meta_table['L3vpn.Vrfs.Vrf.Af.RouteTarget']['meta_info'].parent =_meta_table['L3vpn.Vrfs.Vrf.Af']['meta_info']
_meta_table['L3vpn.Vrfs.Vrf.Interface']['meta_info'].parent =_meta_table['L3vpn.Vrfs.Vrf']['meta_info']
_meta_table['L3vpn.Vrfs.Vrf.Af']['meta_info'].parent =_meta_table['L3vpn.Vrfs.Vrf']['meta_info']
_meta_table['L3vpn.Vrfs.Vrf']['meta_info'].parent =_meta_table['L3vpn.Vrfs']['meta_info']
_meta_table['L3vpn.InvalidVrfs']['meta_info'].parent =_meta_table['L3vpn']['meta_info']
_meta_table['L3vpn.Vrfs']['meta_info'].parent =_meta_table['L3vpn']['meta_info']
