
'''
This is auto-generated file,
which includes metadata for module Cisco_IOS_XR_lpts_ifib_oper
'''

from ydk._core._dm_meta_info import _MetaInfoClassMember, _MetaInfoClass, _MetaInfoEnum
from ydk._core._dm_meta_info import ATTRIBUTE, REFERENCE_LIST, REFERENCE_LEAFLIST, REFERENCE_BITS, REFERENCE_UNION
from ydk._core._dm_meta_info import REFERENCE_CLASS, REFERENCE_IDENTITY_CLASS, REFERENCE_ENUM_CLASS, ANYXML_CLASS
from ydk._core._importer import _yang_ns

_meta_table = {
    'LptsIfib.Nodes.Node.SliceIds.SliceId.Entry' : {
        'meta_info' : _MetaInfoClass('LptsIfib.Nodes.Node.SliceIds.SliceId.Entry', REFERENCE_LIST,
            '''Data for single pre-ifib entry''',
            False, 
            [
            _MetaInfoClassMember('entry', ATTRIBUTE, 'str', 'xr:Hex-integer',
                None, None,
                [], [b'[0-9a-fA-F]{1,8}'],
                '''                Single Pre-ifib entry
                ''',
                'entry',
                'Cisco-IOS-XR-lpts-ifib-oper', True, is_config=False),
            _MetaInfoClassMember('destination-type', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Destination Key Type
                ''',
                'destination_type',
                'Cisco-IOS-XR-lpts-ifib-oper', False, is_config=False),
            _MetaInfoClassMember('destination-value', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Destination Port/ICMP Type/IGMP Type
                ''',
                'destination_value',
                'Cisco-IOS-XR-lpts-ifib-oper', False, is_config=False),
            _MetaInfoClassMember('source-port', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Source port
                ''',
                'source_port',
                'Cisco-IOS-XR-lpts-ifib-oper', False, is_config=False),
            _MetaInfoClassMember('destination-addr', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Destination IP Address
                ''',
                'destination_addr',
                'Cisco-IOS-XR-lpts-ifib-oper', False, is_config=False),
            _MetaInfoClassMember('source-addr', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Source IP Address
                ''',
                'source_addr',
                'Cisco-IOS-XR-lpts-ifib-oper', False, is_config=False),
            _MetaInfoClassMember('vrf-name', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                VRF Name
                ''',
                'vrf_name',
                'Cisco-IOS-XR-lpts-ifib-oper', False, is_config=False),
            _MetaInfoClassMember('vid', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                VRF ID
                ''',
                'vid',
                'Cisco-IOS-XR-lpts-ifib-oper', False, is_config=False),
            _MetaInfoClassMember('l3protocol', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                Layer 3 Protocol
                ''',
                'l3protocol',
                'Cisco-IOS-XR-lpts-ifib-oper', False, is_config=False),
            _MetaInfoClassMember('l4protocol', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                Layer 4 Protocol
                ''',
                'l4protocol',
                'Cisco-IOS-XR-lpts-ifib-oper', False, is_config=False),
            _MetaInfoClassMember('intf-name', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Interface Name
                ''',
                'intf_name',
                'Cisco-IOS-XR-lpts-ifib-oper', False, is_config=False),
            _MetaInfoClassMember('intf-handle', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                Interface Handle
                ''',
                'intf_handle',
                'Cisco-IOS-XR-lpts-ifib-oper', False, is_config=False),
            _MetaInfoClassMember('is-syn', ATTRIBUTE, 'int', 'uint8',
                None, None,
                [('0', '255')], [],
                '''                Is SYN
                ''',
                'is_syn',
                'Cisco-IOS-XR-lpts-ifib-oper', False, is_config=False),
            _MetaInfoClassMember('opcode', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Opcode
                ''',
                'opcode',
                'Cisco-IOS-XR-lpts-ifib-oper', False, is_config=False),
            _MetaInfoClassMember('accepts', ATTRIBUTE, 'int', 'uint64',
                None, None,
                [('0', '18446744073709551615')], [],
                '''                Packets matched to accept
                ''',
                'accepts',
                'Cisco-IOS-XR-lpts-ifib-oper', False, is_config=False),
            _MetaInfoClassMember('drops', ATTRIBUTE, 'int', 'uint64',
                None, None,
                [('0', '18446744073709551615')], [],
                '''                Packets matched to drop
                ''',
                'drops',
                'Cisco-IOS-XR-lpts-ifib-oper', False, is_config=False),
            _MetaInfoClassMember('flow-type', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Flow type
                ''',
                'flow_type',
                'Cisco-IOS-XR-lpts-ifib-oper', False, is_config=False),
            _MetaInfoClassMember('listener-tag', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Listener Tag
                ''',
                'listener_tag',
                'Cisco-IOS-XR-lpts-ifib-oper', False, is_config=False),
            _MetaInfoClassMember('local-flag', ATTRIBUTE, 'int', 'uint8',
                None, None,
                [('0', '255')], [],
                '''                Local Flag
                ''',
                'local_flag',
                'Cisco-IOS-XR-lpts-ifib-oper', False, is_config=False),
            _MetaInfoClassMember('is-fgid', ATTRIBUTE, 'int', 'uint8',
                None, None,
                [('0', '255')], [],
                '''                Is FGID or not
                ''',
                'is_fgid',
                'Cisco-IOS-XR-lpts-ifib-oper', False, is_config=False),
            _MetaInfoClassMember('deliver-list-short', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Deliver List Short Format
                ''',
                'deliver_list_short',
                'Cisco-IOS-XR-lpts-ifib-oper', False, is_config=False),
            _MetaInfoClassMember('deliver-list-long', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Deliver List Long Format
                ''',
                'deliver_list_long',
                'Cisco-IOS-XR-lpts-ifib-oper', False, is_config=False),
            _MetaInfoClassMember('min-ttl', ATTRIBUTE, 'int', 'uint8',
                None, None,
                [('0', '255')], [],
                '''                Minimum TTL
                ''',
                'min_ttl',
                'Cisco-IOS-XR-lpts-ifib-oper', False, is_config=False),
            _MetaInfoClassMember('pending-ifibq-delay', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                pending ifib queue delay
                ''',
                'pending_ifibq_delay',
                'Cisco-IOS-XR-lpts-ifib-oper', False, is_config=False),
            _MetaInfoClassMember('sl-ifibq-delay', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                sl_ifibq delay
                ''',
                'sl_ifibq_delay',
                'Cisco-IOS-XR-lpts-ifib-oper', False, is_config=False),
            _MetaInfoClassMember('ifib-program-time', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                ifib program time in netio
                ''',
                'ifib_program_time',
                'Cisco-IOS-XR-lpts-ifib-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-lpts-ifib-oper',
            'entry',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-lpts-ifib-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_lpts_ifib_oper',
            is_config=False,
        ),
    },
    'LptsIfib.Nodes.Node.SliceIds.SliceId' : {
        'meta_info' : _MetaInfoClass('LptsIfib.Nodes.Node.SliceIds.SliceId', REFERENCE_LIST,
            '''slice types''',
            False, 
            [
            _MetaInfoClassMember('slice-name', ATTRIBUTE, 'str', 'xr:Cisco-ios-xr-string',
                None, None,
                [], [b'[\\w\\-\\.:,_@#%$\\+=\\|;]+'],
                '''                Type value
                ''',
                'slice_name',
                'Cisco-IOS-XR-lpts-ifib-oper', True, is_config=False),
            _MetaInfoClassMember('entry', REFERENCE_LIST, 'Entry', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_lpts_ifib_oper', 'LptsIfib.Nodes.Node.SliceIds.SliceId.Entry',
                [], [],
                '''                Data for single pre-ifib entry
                ''',
                'entry',
                'Cisco-IOS-XR-lpts-ifib-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-lpts-ifib-oper',
            'slice-id',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-lpts-ifib-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_lpts_ifib_oper',
            is_config=False,
        ),
    },
    'LptsIfib.Nodes.Node.SliceIds' : {
        'meta_info' : _MetaInfoClass('LptsIfib.Nodes.Node.SliceIds', REFERENCE_CLASS,
            '''Slice specific''',
            False, 
            [
            _MetaInfoClassMember('slice-id', REFERENCE_LIST, 'SliceId', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_lpts_ifib_oper', 'LptsIfib.Nodes.Node.SliceIds.SliceId',
                [], [],
                '''                slice types
                ''',
                'slice_id',
                'Cisco-IOS-XR-lpts-ifib-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-lpts-ifib-oper',
            'slice-ids',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-lpts-ifib-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_lpts_ifib_oper',
            is_config=False,
        ),
    },
    'LptsIfib.Nodes.Node' : {
        'meta_info' : _MetaInfoClass('LptsIfib.Nodes.Node', REFERENCE_LIST,
            '''Per node slice ''',
            False, 
            [
            _MetaInfoClassMember('node-name', ATTRIBUTE, 'str', 'xr:Node-id',
                None, None,
                [], [b'([a-zA-Z0-9_]*\\d+/){1,2}([a-zA-Z0-9_]*\\d+)'],
                '''                The node name
                ''',
                'node_name',
                'Cisco-IOS-XR-lpts-ifib-oper', True, is_config=False),
            _MetaInfoClassMember('slice-ids', REFERENCE_CLASS, 'SliceIds', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_lpts_ifib_oper', 'LptsIfib.Nodes.Node.SliceIds',
                [], [],
                '''                Slice specific
                ''',
                'slice_ids',
                'Cisco-IOS-XR-lpts-ifib-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-lpts-ifib-oper',
            'node',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-lpts-ifib-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_lpts_ifib_oper',
            is_config=False,
        ),
    },
    'LptsIfib.Nodes' : {
        'meta_info' : _MetaInfoClass('LptsIfib.Nodes', REFERENCE_CLASS,
            '''Node ifib database''',
            False, 
            [
            _MetaInfoClassMember('node', REFERENCE_LIST, 'Node', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_lpts_ifib_oper', 'LptsIfib.Nodes.Node',
                [], [],
                '''                Per node slice 
                ''',
                'node',
                'Cisco-IOS-XR-lpts-ifib-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-lpts-ifib-oper',
            'nodes',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-lpts-ifib-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_lpts_ifib_oper',
            is_config=False,
        ),
    },
    'LptsIfib' : {
        'meta_info' : _MetaInfoClass('LptsIfib', REFERENCE_CLASS,
            '''lpts ifib database''',
            False, 
            [
            _MetaInfoClassMember('nodes', REFERENCE_CLASS, 'Nodes', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_lpts_ifib_oper', 'LptsIfib.Nodes',
                [], [],
                '''                Node ifib database
                ''',
                'nodes',
                'Cisco-IOS-XR-lpts-ifib-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-lpts-ifib-oper',
            'lpts-ifib',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-lpts-ifib-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_lpts_ifib_oper',
            is_config=False,
        ),
    },
}
_meta_table['LptsIfib.Nodes.Node.SliceIds.SliceId.Entry']['meta_info'].parent =_meta_table['LptsIfib.Nodes.Node.SliceIds.SliceId']['meta_info']
_meta_table['LptsIfib.Nodes.Node.SliceIds.SliceId']['meta_info'].parent =_meta_table['LptsIfib.Nodes.Node.SliceIds']['meta_info']
_meta_table['LptsIfib.Nodes.Node.SliceIds']['meta_info'].parent =_meta_table['LptsIfib.Nodes.Node']['meta_info']
_meta_table['LptsIfib.Nodes.Node']['meta_info'].parent =_meta_table['LptsIfib.Nodes']['meta_info']
_meta_table['LptsIfib.Nodes']['meta_info'].parent =_meta_table['LptsIfib']['meta_info']
