
'''
This is auto-generated file,
which includes metadata for module Cisco_IOS_XR_sysadmin_entity_sensor_mib
'''

from ydk._core._dm_meta_info import _MetaInfoClassMember, _MetaInfoClass, _MetaInfoEnum
from ydk._core._dm_meta_info import ATTRIBUTE, REFERENCE_LIST, REFERENCE_LEAFLIST, REFERENCE_BITS, REFERENCE_UNION
from ydk._core._dm_meta_info import REFERENCE_CLASS, REFERENCE_IDENTITY_CLASS, REFERENCE_ENUM_CLASS, ANYXML_CLASS
from ydk._core._importer import _yang_ns

_meta_table = {
    'SensorDataType' : _MetaInfoEnum('SensorDataType',
        'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_entity_sensor_mib', 'SensorDataType',
        ''' ''',
        {
            'other':'other',
            'unknown':'unknown',
            'voltsAC':'voltsAC',
            'voltsDC':'voltsDC',
            'amperes':'amperes',
            'watts':'watts',
            'hertz':'hertz',
            'celsius':'celsius',
            'percentRH':'percentRH',
            'rpm':'rpm',
            'cmm':'cmm',
            'truthvalue':'truthvalue',
            'specialEnum':'specialEnum',
        }, 'Cisco-IOS-XR-sysadmin-entity-sensor-mib', _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-sysadmin-entity-sensor-mib']),
    'SensorDataScale' : _MetaInfoEnum('SensorDataScale',
        'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_entity_sensor_mib', 'SensorDataScale',
        ''' ''',
        {
            'yocto':'yocto',
            'zepto':'zepto',
            'atto':'atto',
            'femto':'femto',
            'pico':'pico',
            'nano':'nano',
            'micro':'micro',
            'milli':'milli',
            'units':'units',
            'kilo':'kilo',
            'mega':'mega',
            'giga':'giga',
            'tera':'tera',
            'exa':'exa',
            'peta':'peta',
            'zetta':'zetta',
            'yotta':'yotta',
        }, 'Cisco-IOS-XR-sysadmin-entity-sensor-mib', _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-sysadmin-entity-sensor-mib']),
    'SensorStatus' : _MetaInfoEnum('SensorStatus',
        'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_entity_sensor_mib', 'SensorStatus',
        ''' ''',
        {
            'ok':'ok',
            'unavailable':'unavailable',
            'nonoperational':'nonoperational',
        }, 'Cisco-IOS-XR-sysadmin-entity-sensor-mib', _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-sysadmin-entity-sensor-mib']),
    'SensorThresholdSeverity' : _MetaInfoEnum('SensorThresholdSeverity',
        'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_entity_sensor_mib', 'SensorThresholdSeverity',
        ''' ''',
        {
            'other':'other',
            'minor':'minor',
            'major':'major',
            'critical':'critical',
        }, 'Cisco-IOS-XR-sysadmin-entity-sensor-mib', _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-sysadmin-entity-sensor-mib']),
    'SensorThresholdRelation' : _MetaInfoEnum('SensorThresholdRelation',
        'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_entity_sensor_mib', 'SensorThresholdRelation',
        ''' ''',
        {
            'lessThan':'lessThan',
            'lessOrEqual':'lessOrEqual',
            'greaterThan':'greaterThan',
            'greaterOrEqual':'greaterOrEqual',
            'equalTo':'equalTo',
            'notEqualTo':'notEqualTo',
        }, 'Cisco-IOS-XR-sysadmin-entity-sensor-mib', _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-sysadmin-entity-sensor-mib']),
    'CISCOENTITYSENSORMIB.EntSensorValueTable.EntSensorValueEntry' : {
        'meta_info' : _MetaInfoClass('CISCOENTITYSENSORMIB.EntSensorValueTable.EntSensorValueEntry', REFERENCE_LIST,
            ''' ''',
            False, 
            [
            _MetaInfoClassMember('entPhysicalIndex', ATTRIBUTE, 'int', 'ENTITY-MIB:PhysicalIndex',
                None, None,
                [('1', '2147483647')], [],
                '''                ''',
                'entphysicalindex',
                'Cisco-IOS-XR-sysadmin-entity-sensor-mib', True, is_config=False),
            _MetaInfoClassMember('entSensorType', REFERENCE_ENUM_CLASS, 'SensorDataType', 'SensorDataType',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_entity_sensor_mib', 'SensorDataType',
                [], [],
                '''                ''',
                'entsensortype',
                'Cisco-IOS-XR-sysadmin-entity-sensor-mib', False, is_config=False),
            _MetaInfoClassMember('entSensorScale', REFERENCE_ENUM_CLASS, 'SensorDataScale', 'SensorDataScale',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_entity_sensor_mib', 'SensorDataScale',
                [], [],
                '''                ''',
                'entsensorscale',
                'Cisco-IOS-XR-sysadmin-entity-sensor-mib', False, is_config=False),
            _MetaInfoClassMember('entSensorPrecision', ATTRIBUTE, 'int', 'SensorPrecision',
                None, None,
                [('-8', '9')], [],
                '''                ''',
                'entsensorprecision',
                'Cisco-IOS-XR-sysadmin-entity-sensor-mib', False, is_config=False),
            _MetaInfoClassMember('entSensorValue', ATTRIBUTE, 'int', 'SensorValue',
                None, None,
                [('-1000000000', '1000000000')], [],
                '''                ''',
                'entsensorvalue',
                'Cisco-IOS-XR-sysadmin-entity-sensor-mib', False, is_config=False),
            _MetaInfoClassMember('entSensorStatus', REFERENCE_ENUM_CLASS, 'SensorStatus', 'SensorStatus',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_entity_sensor_mib', 'SensorStatus',
                [], [],
                '''                ''',
                'entsensorstatus',
                'Cisco-IOS-XR-sysadmin-entity-sensor-mib', False, is_config=False),
            _MetaInfoClassMember('entSensorValueTimeStamp', ATTRIBUTE, 'int', 'yang:timestamp',
                None, None,
                [('0', '4294967295')], [],
                '''                ''',
                'entsensorvaluetimestamp',
                'Cisco-IOS-XR-sysadmin-entity-sensor-mib', False, is_config=False),
            _MetaInfoClassMember('entSensorValueUpdateRate', ATTRIBUTE, 'int', 'SensorValueUpdateRate',
                None, None,
                [('0', '999999999')], [],
                '''                ''',
                'entsensorvalueupdaterate',
                'Cisco-IOS-XR-sysadmin-entity-sensor-mib', False, is_config=False),
            _MetaInfoClassMember('entSensorMeasuredEntity', ATTRIBUTE, 'int', 'entSensorMeasuredEntityType',
                None, None,
                [('0', '2147483647')], [],
                '''                ''',
                'entsensormeasuredentity',
                'Cisco-IOS-XR-sysadmin-entity-sensor-mib', False, is_config=False),
            ],
            'Cisco-IOS-XR-sysadmin-entity-sensor-mib',
            'entSensorValueEntry',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-sysadmin-entity-sensor-mib'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_entity_sensor_mib',
            is_config=False,
        ),
    },
    'CISCOENTITYSENSORMIB.EntSensorValueTable' : {
        'meta_info' : _MetaInfoClass('CISCOENTITYSENSORMIB.EntSensorValueTable', REFERENCE_CLASS,
            ''' ''',
            False, 
            [
            _MetaInfoClassMember('entSensorValueEntry', REFERENCE_LIST, 'EntSensorValueEntry', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_entity_sensor_mib', 'CISCOENTITYSENSORMIB.EntSensorValueTable.EntSensorValueEntry',
                [], [],
                '''                ''',
                'entsensorvalueentry',
                'Cisco-IOS-XR-sysadmin-entity-sensor-mib', False, is_config=False),
            ],
            'Cisco-IOS-XR-sysadmin-entity-sensor-mib',
            'entSensorValueTable',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-sysadmin-entity-sensor-mib'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_entity_sensor_mib',
            is_config=False,
        ),
    },
    'CISCOENTITYSENSORMIB.EntSensorThresholdTable.EntSensorThresholdEntry' : {
        'meta_info' : _MetaInfoClass('CISCOENTITYSENSORMIB.EntSensorThresholdTable.EntSensorThresholdEntry', REFERENCE_LIST,
            ''' ''',
            False, 
            [
            _MetaInfoClassMember('entPhysicalIndex', ATTRIBUTE, 'int', 'ENTITY-MIB:PhysicalIndex',
                None, None,
                [('1', '2147483647')], [],
                '''                ''',
                'entphysicalindex',
                'Cisco-IOS-XR-sysadmin-entity-sensor-mib', True, is_config=False),
            _MetaInfoClassMember('entSensorThresholdIndex', ATTRIBUTE, 'int', 'entSensorThresholdIndexType',
                None, None,
                [('1', '99999999')], [],
                '''                ''',
                'entsensorthresholdindex',
                'Cisco-IOS-XR-sysadmin-entity-sensor-mib', True, is_config=False),
            _MetaInfoClassMember('entSensorThresholdSeverity', REFERENCE_ENUM_CLASS, 'SensorThresholdSeverity', 'SensorThresholdSeverity',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_entity_sensor_mib', 'SensorThresholdSeverity',
                [], [],
                '''                ''',
                'entsensorthresholdseverity',
                'Cisco-IOS-XR-sysadmin-entity-sensor-mib', False, is_config=False),
            _MetaInfoClassMember('entSensorThresholdRelation', REFERENCE_ENUM_CLASS, 'SensorThresholdRelation', 'SensorThresholdRelation',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_entity_sensor_mib', 'SensorThresholdRelation',
                [], [],
                '''                ''',
                'entsensorthresholdrelation',
                'Cisco-IOS-XR-sysadmin-entity-sensor-mib', False, is_config=False),
            _MetaInfoClassMember('entSensorThresholdValue', ATTRIBUTE, 'int', 'SensorValue',
                None, None,
                [('-1000000000', '1000000000')], [],
                '''                ''',
                'entsensorthresholdvalue',
                'Cisco-IOS-XR-sysadmin-entity-sensor-mib', False, is_config=False),
            _MetaInfoClassMember('entSensorThresholdEvaluation', REFERENCE_ENUM_CLASS, 'TruthValue', 'SNMPv2-TC:TruthValue',
                'ydk.models.cisco_ios_xr.SNMPv2_TC', 'TruthValue',
                [], [],
                '''                ''',
                'entsensorthresholdevaluation',
                'Cisco-IOS-XR-sysadmin-entity-sensor-mib', False, is_config=False),
            _MetaInfoClassMember('entSensorThresholdNotificationEnable', REFERENCE_ENUM_CLASS, 'TruthValue', 'SNMPv2-TC:TruthValue',
                'ydk.models.cisco_ios_xr.SNMPv2_TC', 'TruthValue',
                [], [],
                '''                ''',
                'entsensorthresholdnotificationenable',
                'Cisco-IOS-XR-sysadmin-entity-sensor-mib', False, is_config=False),
            ],
            'Cisco-IOS-XR-sysadmin-entity-sensor-mib',
            'entSensorThresholdEntry',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-sysadmin-entity-sensor-mib'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_entity_sensor_mib',
            is_config=False,
        ),
    },
    'CISCOENTITYSENSORMIB.EntSensorThresholdTable' : {
        'meta_info' : _MetaInfoClass('CISCOENTITYSENSORMIB.EntSensorThresholdTable', REFERENCE_CLASS,
            ''' ''',
            False, 
            [
            _MetaInfoClassMember('entSensorThresholdEntry', REFERENCE_LIST, 'EntSensorThresholdEntry', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_entity_sensor_mib', 'CISCOENTITYSENSORMIB.EntSensorThresholdTable.EntSensorThresholdEntry',
                [], [],
                '''                ''',
                'entsensorthresholdentry',
                'Cisco-IOS-XR-sysadmin-entity-sensor-mib', False, is_config=False),
            ],
            'Cisco-IOS-XR-sysadmin-entity-sensor-mib',
            'entSensorThresholdTable',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-sysadmin-entity-sensor-mib'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_entity_sensor_mib',
            is_config=False,
        ),
    },
    'CISCOENTITYSENSORMIB' : {
        'meta_info' : _MetaInfoClass('CISCOENTITYSENSORMIB', REFERENCE_CLASS,
            ''' ''',
            False, 
            [
            _MetaInfoClassMember('entSensorValueTable', REFERENCE_CLASS, 'EntSensorValueTable', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_entity_sensor_mib', 'CISCOENTITYSENSORMIB.EntSensorValueTable',
                [], [],
                '''                ''',
                'entsensorvaluetable',
                'Cisco-IOS-XR-sysadmin-entity-sensor-mib', False, is_config=False),
            _MetaInfoClassMember('entSensorThresholdTable', REFERENCE_CLASS, 'EntSensorThresholdTable', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_entity_sensor_mib', 'CISCOENTITYSENSORMIB.EntSensorThresholdTable',
                [], [],
                '''                ''',
                'entsensorthresholdtable',
                'Cisco-IOS-XR-sysadmin-entity-sensor-mib', False, is_config=False),
            ],
            'Cisco-IOS-XR-sysadmin-entity-sensor-mib',
            'CISCO-ENTITY-SENSOR-MIB',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-sysadmin-entity-sensor-mib'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_entity_sensor_mib',
        ),
    },
}
_meta_table['CISCOENTITYSENSORMIB.EntSensorValueTable.EntSensorValueEntry']['meta_info'].parent =_meta_table['CISCOENTITYSENSORMIB.EntSensorValueTable']['meta_info']
_meta_table['CISCOENTITYSENSORMIB.EntSensorThresholdTable.EntSensorThresholdEntry']['meta_info'].parent =_meta_table['CISCOENTITYSENSORMIB.EntSensorThresholdTable']['meta_info']
_meta_table['CISCOENTITYSENSORMIB.EntSensorValueTable']['meta_info'].parent =_meta_table['CISCOENTITYSENSORMIB']['meta_info']
_meta_table['CISCOENTITYSENSORMIB.EntSensorThresholdTable']['meta_info'].parent =_meta_table['CISCOENTITYSENSORMIB']['meta_info']
