
'''
This is auto-generated file,
which includes metadata for module Cisco_IOS_XR_isis_act
'''

from ydk._core._dm_meta_info import _MetaInfoClassMember, _MetaInfoClass, _MetaInfoEnum
from ydk._core._dm_meta_info import ATTRIBUTE, REFERENCE_LIST, REFERENCE_LEAFLIST, REFERENCE_BITS, REFERENCE_UNION
from ydk._core._dm_meta_info import REFERENCE_CLASS, REFERENCE_IDENTITY_CLASS, REFERENCE_ENUM_CLASS, ANYXML_CLASS
from ydk._core._importer import _yang_ns

_meta_table = {
    'ClearIsisProcess.Input.Instance' : {
        'meta_info' : _MetaInfoClass('ClearIsisProcess.Input.Instance', REFERENCE_CLASS,
            '''Clear data from single IS-IS instance''',
            False, 
            [
            _MetaInfoClassMember('instance-identifier', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                IS-IS process instance identifier
                ''',
                'instance_identifier',
                'Cisco-IOS-XR-isis-act', False),
            ],
            'Cisco-IOS-XR-isis-act',
            'instance',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-isis-act'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_isis_act',
        ),
    },
    'ClearIsisProcess.Input' : {
        'meta_info' : _MetaInfoClass('ClearIsisProcess.Input', REFERENCE_CLASS,
            ''' ''',
            False, 
            [
            _MetaInfoClassMember('instance', REFERENCE_CLASS, 'Instance', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_isis_act', 'ClearIsisProcess.Input.Instance',
                [], [],
                '''                Clear data from single IS-IS instance
                ''',
                'instance',
                'Cisco-IOS-XR-isis-act', False),
            _MetaInfoClassMember('process', ATTRIBUTE, 'Empty', 'empty',
                None, None,
                [], [],
                '''                Clear all IS-IS data structures
                ''',
                'process',
                'Cisco-IOS-XR-isis-act', False),
            ],
            'Cisco-IOS-XR-isis-act',
            'input',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-isis-act'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_isis_act',
        ),
    },
    'ClearIsisProcess' : {
        'meta_info' : _MetaInfoClass('ClearIsisProcess', REFERENCE_CLASS,
            '''Clear all IS-IS data structures''',
            False, 
            [
            _MetaInfoClassMember('input', REFERENCE_CLASS, 'Input', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_isis_act', 'ClearIsisProcess.Input',
                [], [],
                '''                ''',
                'input',
                'Cisco-IOS-XR-isis-act', False),
            ],
            'Cisco-IOS-XR-isis-act',
            'clear-isis-process',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-isis-act'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_isis_act',
        ),
    },
    'ClearIsisRoute.Input.Instance' : {
        'meta_info' : _MetaInfoClass('ClearIsisRoute.Input.Instance', REFERENCE_CLASS,
            '''Clear data from single IS-IS instance''',
            False, 
            [
            _MetaInfoClassMember('instance-identifier', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                IS-IS process instance identifier
                ''',
                'instance_identifier',
                'Cisco-IOS-XR-isis-act', False),
            ],
            'Cisco-IOS-XR-isis-act',
            'instance',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-isis-act'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_isis_act',
        ),
    },
    'ClearIsisRoute.Input' : {
        'meta_info' : _MetaInfoClass('ClearIsisRoute.Input', REFERENCE_CLASS,
            ''' ''',
            False, 
            [
            _MetaInfoClassMember('instance', REFERENCE_CLASS, 'Instance', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_isis_act', 'ClearIsisRoute.Input.Instance',
                [], [],
                '''                Clear data from single IS-IS instance
                ''',
                'instance',
                'Cisco-IOS-XR-isis-act', False),
            _MetaInfoClassMember('route', ATTRIBUTE, 'Empty', 'empty',
                None, None,
                [], [],
                '''                Clear IS-IS routes
                ''',
                'route',
                'Cisco-IOS-XR-isis-act', False),
            ],
            'Cisco-IOS-XR-isis-act',
            'input',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-isis-act'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_isis_act',
        ),
    },
    'ClearIsisRoute' : {
        'meta_info' : _MetaInfoClass('ClearIsisRoute', REFERENCE_CLASS,
            '''Clear IS-IS routes''',
            False, 
            [
            _MetaInfoClassMember('input', REFERENCE_CLASS, 'Input', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_isis_act', 'ClearIsisRoute.Input',
                [], [],
                '''                ''',
                'input',
                'Cisco-IOS-XR-isis-act', False),
            ],
            'Cisco-IOS-XR-isis-act',
            'clear-isis-route',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-isis-act'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_isis_act',
        ),
    },
    'ClearIsisStat.Input.Instance' : {
        'meta_info' : _MetaInfoClass('ClearIsisStat.Input.Instance', REFERENCE_CLASS,
            '''Clear data from single IS-IS instance''',
            False, 
            [
            _MetaInfoClassMember('instance-identifier', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                IS-IS process instance identifier
                ''',
                'instance_identifier',
                'Cisco-IOS-XR-isis-act', False),
            ],
            'Cisco-IOS-XR-isis-act',
            'instance',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-isis-act'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_isis_act',
        ),
    },
    'ClearIsisStat.Input.Statistics' : {
        'meta_info' : _MetaInfoClass('ClearIsisStat.Input.Statistics', REFERENCE_CLASS,
            '''Clear IS-IS protocol statistics''',
            False, 
            [
            _MetaInfoClassMember('interface-name', ATTRIBUTE, 'str', 'xr:Interface-name',
                None, None,
                [], [b'[a-zA-Z0-9._/-]+'],
                '''                Interface name
                ''',
                'interface_name',
                'Cisco-IOS-XR-isis-act', False, is_mandatory=True),
            ],
            'Cisco-IOS-XR-isis-act',
            'statistics',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-isis-act'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_isis_act',
        ),
    },
    'ClearIsisStat.Input' : {
        'meta_info' : _MetaInfoClass('ClearIsisStat.Input', REFERENCE_CLASS,
            ''' ''',
            False, 
            [
            _MetaInfoClassMember('instance', REFERENCE_CLASS, 'Instance', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_isis_act', 'ClearIsisStat.Input.Instance',
                [], [],
                '''                Clear data from single IS-IS instance
                ''',
                'instance',
                'Cisco-IOS-XR-isis-act', False),
            _MetaInfoClassMember('statistics', REFERENCE_CLASS, 'Statistics', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_isis_act', 'ClearIsisStat.Input.Statistics',
                [], [],
                '''                Clear IS-IS protocol statistics
                ''',
                'statistics',
                'Cisco-IOS-XR-isis-act', False),
            ],
            'Cisco-IOS-XR-isis-act',
            'input',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-isis-act'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_isis_act',
        ),
    },
    'ClearIsisStat' : {
        'meta_info' : _MetaInfoClass('ClearIsisStat', REFERENCE_CLASS,
            '''Clear IS-IS protocol statistics''',
            False, 
            [
            _MetaInfoClassMember('input', REFERENCE_CLASS, 'Input', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_isis_act', 'ClearIsisStat.Input',
                [], [],
                '''                ''',
                'input',
                'Cisco-IOS-XR-isis-act', False),
            ],
            'Cisco-IOS-XR-isis-act',
            'clear-isis-stat',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-isis-act'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_isis_act',
        ),
    },
    'ClearIsisDist.Input.Instance' : {
        'meta_info' : _MetaInfoClass('ClearIsisDist.Input.Instance', REFERENCE_CLASS,
            '''Reset BGP-LS topology from single IS-IS instance''',
            False, 
            [
            _MetaInfoClassMember('instance-identifier', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                IS-IS process instance identifier
                ''',
                'instance_identifier',
                'Cisco-IOS-XR-isis-act', False),
            ],
            'Cisco-IOS-XR-isis-act',
            'instance',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-isis-act'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_isis_act',
        ),
    },
    'ClearIsisDist.Input' : {
        'meta_info' : _MetaInfoClass('ClearIsisDist.Input', REFERENCE_CLASS,
            ''' ''',
            False, 
            [
            _MetaInfoClassMember('instance', REFERENCE_CLASS, 'Instance', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_isis_act', 'ClearIsisDist.Input.Instance',
                [], [],
                '''                Reset BGP-LS topology from single IS-IS instance
                ''',
                'instance',
                'Cisco-IOS-XR-isis-act', False),
            _MetaInfoClassMember('distribution', ATTRIBUTE, 'Empty', 'empty',
                None, None,
                [], [],
                '''                Reset BGP-LS topology distribution
                ''',
                'distribution',
                'Cisco-IOS-XR-isis-act', False),
            ],
            'Cisco-IOS-XR-isis-act',
            'input',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-isis-act'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_isis_act',
        ),
    },
    'ClearIsisDist' : {
        'meta_info' : _MetaInfoClass('ClearIsisDist', REFERENCE_CLASS,
            '''Reset BGP-LS topology distribution''',
            False, 
            [
            _MetaInfoClassMember('input', REFERENCE_CLASS, 'Input', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_isis_act', 'ClearIsisDist.Input',
                [], [],
                '''                ''',
                'input',
                'Cisco-IOS-XR-isis-act', False),
            ],
            'Cisco-IOS-XR-isis-act',
            'clear-isis-dist',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-isis-act'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_isis_act',
        ),
    },
    'ClearIsisLocalLsp.Input.Instance' : {
        'meta_info' : _MetaInfoClass('ClearIsisLocalLsp.Input.Instance', REFERENCE_CLASS,
            '''Clean and regenerate local LSPs from single IS-IS instance''',
            False, 
            [
            _MetaInfoClassMember('instance-identifier', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                IS-IS process instance identifier
                ''',
                'instance_identifier',
                'Cisco-IOS-XR-isis-act', False),
            ],
            'Cisco-IOS-XR-isis-act',
            'instance',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-isis-act'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_isis_act',
        ),
    },
    'ClearIsisLocalLsp.Input' : {
        'meta_info' : _MetaInfoClass('ClearIsisLocalLsp.Input', REFERENCE_CLASS,
            ''' ''',
            False, 
            [
            _MetaInfoClassMember('instance', REFERENCE_CLASS, 'Instance', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_isis_act', 'ClearIsisLocalLsp.Input.Instance',
                [], [],
                '''                Clean and regenerate local LSPs from single IS-IS instance
                ''',
                'instance',
                'Cisco-IOS-XR-isis-act', False),
            _MetaInfoClassMember('local-lsp', ATTRIBUTE, 'Empty', 'empty',
                None, None,
                [], [],
                '''                Clean and regenerate local LSPs
                ''',
                'local_lsp',
                'Cisco-IOS-XR-isis-act', False),
            ],
            'Cisco-IOS-XR-isis-act',
            'input',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-isis-act'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_isis_act',
        ),
    },
    'ClearIsisLocalLsp' : {
        'meta_info' : _MetaInfoClass('ClearIsisLocalLsp', REFERENCE_CLASS,
            '''Clean and regenerate local LSPs''',
            False, 
            [
            _MetaInfoClassMember('input', REFERENCE_CLASS, 'Input', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_isis_act', 'ClearIsisLocalLsp.Input',
                [], [],
                '''                ''',
                'input',
                'Cisco-IOS-XR-isis-act', False),
            ],
            'Cisco-IOS-XR-isis-act',
            'clear-isis-local-lsp',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-isis-act'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_isis_act',
        ),
    },
    'ClearIsis.Input.Instance' : {
        'meta_info' : _MetaInfoClass('ClearIsis.Input.Instance', REFERENCE_CLASS,
            '''Clear data from single IS-IS instance''',
            False, 
            [
            _MetaInfoClassMember('instance-identifier', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                IS-IS process instance identifier
                ''',
                'instance_identifier',
                'Cisco-IOS-XR-isis-act', False),
            ],
            'Cisco-IOS-XR-isis-act',
            'instance',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-isis-act'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_isis_act',
        ),
    },
    'ClearIsis.Input.RtType' : _MetaInfoEnum('RtType',
        'ydk.models.cisco_ios_xr.Cisco_IOS_XR_isis_act', 'ClearIsis.Input.RtType',
        '''Clear data for these route types''',
        {
            'AFI-ALL-MULTICAST':'AFI_ALL_MULTICAST',
            'AFI-ALL-SAFI-ALL':'AFI_ALL_SAFI_ALL',
            'AFI-ALL-UNICAST':'AFI_ALL_UNICAST',
            'IPv4-MULTICAST':'IPv4_MULTICAST',
            'IPv4-SAFI-ALL':'IPv4_SAFI_ALL',
            'IPv4-UNICAST':'IPv4_UNICAST',
            'IPv6-MULTICAST':'IPv6_MULTICAST',
            'IPv6-SAFI-ALL':'IPv6_SAFI_ALL',
            'IPv6-UNICAST':'IPv6_UNICAST',
        }, 'Cisco-IOS-XR-isis-act', _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-isis-act']),
    'ClearIsis.Input' : {
        'meta_info' : _MetaInfoClass('ClearIsis.Input', REFERENCE_CLASS,
            ''' ''',
            False, 
            [
            _MetaInfoClassMember('instance', REFERENCE_CLASS, 'Instance', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_isis_act', 'ClearIsis.Input.Instance',
                [], [],
                '''                Clear data from single IS-IS instance
                ''',
                'instance',
                'Cisco-IOS-XR-isis-act', False),
            _MetaInfoClassMember('rt-type', REFERENCE_ENUM_CLASS, 'RtType', 'enumeration',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_isis_act', 'ClearIsis.Input.RtType',
                [], [],
                '''                Clear data for these route types
                ''',
                'rt_type',
                'Cisco-IOS-XR-isis-act', False),
            _MetaInfoClassMember('route', ATTRIBUTE, 'Empty', 'empty',
                None, None,
                [], [],
                '''                Clear IS-IS routes
                ''',
                'route',
                'Cisco-IOS-XR-isis-act', False),
            _MetaInfoClassMember('topology', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Topology table information
                ''',
                'topology',
                'Cisco-IOS-XR-isis-act', False),
            ],
            'Cisco-IOS-XR-isis-act',
            'input',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-isis-act'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_isis_act',
        ),
    },
    'ClearIsis' : {
        'meta_info' : _MetaInfoClass('ClearIsis', REFERENCE_CLASS,
            '''Clear IS-IS data structures''',
            False, 
            [
            _MetaInfoClassMember('input', REFERENCE_CLASS, 'Input', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_isis_act', 'ClearIsis.Input',
                [], [],
                '''                ''',
                'input',
                'Cisco-IOS-XR-isis-act', False),
            ],
            'Cisco-IOS-XR-isis-act',
            'clear-isis',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-isis-act'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_isis_act',
        ),
    },
}
_meta_table['ClearIsisProcess.Input.Instance']['meta_info'].parent =_meta_table['ClearIsisProcess.Input']['meta_info']
_meta_table['ClearIsisProcess.Input']['meta_info'].parent =_meta_table['ClearIsisProcess']['meta_info']
_meta_table['ClearIsisRoute.Input.Instance']['meta_info'].parent =_meta_table['ClearIsisRoute.Input']['meta_info']
_meta_table['ClearIsisRoute.Input']['meta_info'].parent =_meta_table['ClearIsisRoute']['meta_info']
_meta_table['ClearIsisStat.Input.Instance']['meta_info'].parent =_meta_table['ClearIsisStat.Input']['meta_info']
_meta_table['ClearIsisStat.Input.Statistics']['meta_info'].parent =_meta_table['ClearIsisStat.Input']['meta_info']
_meta_table['ClearIsisStat.Input']['meta_info'].parent =_meta_table['ClearIsisStat']['meta_info']
_meta_table['ClearIsisDist.Input.Instance']['meta_info'].parent =_meta_table['ClearIsisDist.Input']['meta_info']
_meta_table['ClearIsisDist.Input']['meta_info'].parent =_meta_table['ClearIsisDist']['meta_info']
_meta_table['ClearIsisLocalLsp.Input.Instance']['meta_info'].parent =_meta_table['ClearIsisLocalLsp.Input']['meta_info']
_meta_table['ClearIsisLocalLsp.Input']['meta_info'].parent =_meta_table['ClearIsisLocalLsp']['meta_info']
_meta_table['ClearIsis.Input.Instance']['meta_info'].parent =_meta_table['ClearIsis.Input']['meta_info']
_meta_table['ClearIsis.Input']['meta_info'].parent =_meta_table['ClearIsis']['meta_info']
