
'''
This is auto-generated file,
which includes metadata for module Cisco_IOS_XR_cfgmgr_rollback_act
'''

from ydk._core._dm_meta_info import _MetaInfoClassMember, _MetaInfoClass, _MetaInfoEnum
from ydk._core._dm_meta_info import ATTRIBUTE, REFERENCE_LIST, REFERENCE_LEAFLIST, REFERENCE_BITS, REFERENCE_UNION
from ydk._core._dm_meta_info import REFERENCE_CLASS, REFERENCE_IDENTITY_CLASS, REFERENCE_ENUM_CLASS, ANYXML_CLASS
from ydk._core._importer import _yang_ns

_meta_table = {
    'RollBackConfigurationLast.Input' : {
        'meta_info' : _MetaInfoClass('RollBackConfigurationLast.Input', REFERENCE_CLASS,
            ''' ''',
            False, 
            [
            _MetaInfoClassMember('count', ATTRIBUTE, 'int', 'int32',
                None, None,
                [('1', '100')], [],
                '''                Number of commits to rollback
                ''',
                'count',
                'Cisco-IOS-XR-cfgmgr-rollback-act', False, is_mandatory=True),
            _MetaInfoClassMember('force', ATTRIBUTE, 'bool', 'boolean',
                None, None,
                [], [],
                '''                Override commit blocks
                ''',
                'force',
                'Cisco-IOS-XR-cfgmgr-rollback-act', False, default_value='False', has_when=True),
            _MetaInfoClassMember('best-effort', ATTRIBUTE, 'bool', 'boolean',
                None, None,
                [], [],
                '''                Rollback via best-effort operation
                ''',
                'best_effort',
                'Cisco-IOS-XR-cfgmgr-rollback-act', False, default_value='False', has_when=True),
            _MetaInfoClassMember('label', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Assign a label to this rollback
                ''',
                'label',
                'Cisco-IOS-XR-cfgmgr-rollback-act', False),
            _MetaInfoClassMember('comment', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Assign a comment to this rollback
                ''',
                'comment',
                'Cisco-IOS-XR-cfgmgr-rollback-act', False),
            ],
            'Cisco-IOS-XR-cfgmgr-rollback-act',
            'input',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-cfgmgr-rollback-act'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_cfgmgr_rollback_act',
        ),
    },
    'RollBackConfigurationLast' : {
        'meta_info' : _MetaInfoClass('RollBackConfigurationLast', REFERENCE_CLASS,
            '''Rollback last <n> commits made''',
            False, 
            [
            _MetaInfoClassMember('input', REFERENCE_CLASS, 'Input', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_cfgmgr_rollback_act', 'RollBackConfigurationLast.Input',
                [], [],
                '''                ''',
                'input',
                'Cisco-IOS-XR-cfgmgr-rollback-act', False),
            ],
            'Cisco-IOS-XR-cfgmgr-rollback-act',
            'roll-back-configuration-last',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-cfgmgr-rollback-act'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_cfgmgr_rollback_act',
        ),
    },
    'RollBackConfigurationTo.Input' : {
        'meta_info' : _MetaInfoClass('RollBackConfigurationTo.Input', REFERENCE_CLASS,
            ''' ''',
            False, 
            [
            _MetaInfoClassMember('commit-id', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Commit ID
                ''',
                'commit_id',
                'Cisco-IOS-XR-cfgmgr-rollback-act', False, is_mandatory=True),
            _MetaInfoClassMember('force', ATTRIBUTE, 'bool', 'boolean',
                None, None,
                [], [],
                '''                Override commit blocks
                ''',
                'force',
                'Cisco-IOS-XR-cfgmgr-rollback-act', False, default_value='False', has_when=True),
            _MetaInfoClassMember('best-effort', ATTRIBUTE, 'bool', 'boolean',
                None, None,
                [], [],
                '''                Rollback via best-effort operation
                ''',
                'best_effort',
                'Cisco-IOS-XR-cfgmgr-rollback-act', False, default_value='False', has_when=True),
            _MetaInfoClassMember('label', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Assign a label to this rollback
                ''',
                'label',
                'Cisco-IOS-XR-cfgmgr-rollback-act', False),
            _MetaInfoClassMember('comment', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Assign a comment to this rollback
                ''',
                'comment',
                'Cisco-IOS-XR-cfgmgr-rollback-act', False),
            ],
            'Cisco-IOS-XR-cfgmgr-rollback-act',
            'input',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-cfgmgr-rollback-act'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_cfgmgr_rollback_act',
        ),
    },
    'RollBackConfigurationTo' : {
        'meta_info' : _MetaInfoClass('RollBackConfigurationTo', REFERENCE_CLASS,
            '''Rollback up to (and including) a specific commit''',
            False, 
            [
            _MetaInfoClassMember('input', REFERENCE_CLASS, 'Input', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_cfgmgr_rollback_act', 'RollBackConfigurationTo.Input',
                [], [],
                '''                ''',
                'input',
                'Cisco-IOS-XR-cfgmgr-rollback-act', False),
            ],
            'Cisco-IOS-XR-cfgmgr-rollback-act',
            'roll-back-configuration-to',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-cfgmgr-rollback-act'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_cfgmgr_rollback_act',
        ),
    },
    'RollBackConfigurationToExclude.Input' : {
        'meta_info' : _MetaInfoClass('RollBackConfigurationToExclude.Input', REFERENCE_CLASS,
            ''' ''',
            False, 
            [
            _MetaInfoClassMember('commit-id', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Commit ID
                ''',
                'commit_id',
                'Cisco-IOS-XR-cfgmgr-rollback-act', False, is_mandatory=True),
            _MetaInfoClassMember('force', ATTRIBUTE, 'bool', 'boolean',
                None, None,
                [], [],
                '''                Override commit blocks
                ''',
                'force',
                'Cisco-IOS-XR-cfgmgr-rollback-act', False, default_value='False', has_when=True),
            _MetaInfoClassMember('best-effort', ATTRIBUTE, 'bool', 'boolean',
                None, None,
                [], [],
                '''                Rollback via best-effort operation
                ''',
                'best_effort',
                'Cisco-IOS-XR-cfgmgr-rollback-act', False, default_value='False', has_when=True),
            _MetaInfoClassMember('label', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Assign a label to this rollback
                ''',
                'label',
                'Cisco-IOS-XR-cfgmgr-rollback-act', False),
            _MetaInfoClassMember('comment', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Assign a comment to this rollback
                ''',
                'comment',
                'Cisco-IOS-XR-cfgmgr-rollback-act', False),
            ],
            'Cisco-IOS-XR-cfgmgr-rollback-act',
            'input',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-cfgmgr-rollback-act'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_cfgmgr_rollback_act',
        ),
    },
    'RollBackConfigurationToExclude' : {
        'meta_info' : _MetaInfoClass('RollBackConfigurationToExclude', REFERENCE_CLASS,
            '''Rollback up to (and excluding) a specific commit''',
            False, 
            [
            _MetaInfoClassMember('input', REFERENCE_CLASS, 'Input', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_cfgmgr_rollback_act', 'RollBackConfigurationToExclude.Input',
                [], [],
                '''                ''',
                'input',
                'Cisco-IOS-XR-cfgmgr-rollback-act', False),
            ],
            'Cisco-IOS-XR-cfgmgr-rollback-act',
            'roll-back-configuration-to-exclude',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-cfgmgr-rollback-act'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_cfgmgr_rollback_act',
        ),
    },
    'RollBackConfiguration.Input' : {
        'meta_info' : _MetaInfoClass('RollBackConfiguration.Input', REFERENCE_CLASS,
            ''' ''',
            False, 
            [
            _MetaInfoClassMember('commit-id', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Commit ID
                ''',
                'commit_id',
                'Cisco-IOS-XR-cfgmgr-rollback-act', False, is_mandatory=True),
            _MetaInfoClassMember('force', ATTRIBUTE, 'bool', 'boolean',
                None, None,
                [], [],
                '''                Override commit blocks
                ''',
                'force',
                'Cisco-IOS-XR-cfgmgr-rollback-act', False, default_value='False', has_when=True),
            _MetaInfoClassMember('best-effort', ATTRIBUTE, 'bool', 'boolean',
                None, None,
                [], [],
                '''                Rollback via best-effort operation
                ''',
                'best_effort',
                'Cisco-IOS-XR-cfgmgr-rollback-act', False, default_value='False', has_when=True),
            _MetaInfoClassMember('label', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Assign a label to this rollback
                ''',
                'label',
                'Cisco-IOS-XR-cfgmgr-rollback-act', False),
            _MetaInfoClassMember('comment', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Assign a comment to this rollback
                ''',
                'comment',
                'Cisco-IOS-XR-cfgmgr-rollback-act', False),
            ],
            'Cisco-IOS-XR-cfgmgr-rollback-act',
            'input',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-cfgmgr-rollback-act'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_cfgmgr_rollback_act',
        ),
    },
    'RollBackConfiguration' : {
        'meta_info' : _MetaInfoClass('RollBackConfiguration', REFERENCE_CLASS,
            '''Rollback a specific commit''',
            False, 
            [
            _MetaInfoClassMember('input', REFERENCE_CLASS, 'Input', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_cfgmgr_rollback_act', 'RollBackConfiguration.Input',
                [], [],
                '''                ''',
                'input',
                'Cisco-IOS-XR-cfgmgr-rollback-act', False),
            ],
            'Cisco-IOS-XR-cfgmgr-rollback-act',
            'roll-back-configuration',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-cfgmgr-rollback-act'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_cfgmgr_rollback_act',
        ),
    },
}
_meta_table['RollBackConfigurationLast.Input']['meta_info'].parent =_meta_table['RollBackConfigurationLast']['meta_info']
_meta_table['RollBackConfigurationTo.Input']['meta_info'].parent =_meta_table['RollBackConfigurationTo']['meta_info']
_meta_table['RollBackConfigurationToExclude.Input']['meta_info'].parent =_meta_table['RollBackConfigurationToExclude']['meta_info']
_meta_table['RollBackConfiguration.Input']['meta_info'].parent =_meta_table['RollBackConfiguration']['meta_info']
