
'''
This is auto-generated file,
which includes metadata for module Cisco_IOS_XR_call_home_cfg
'''

from ydk._core._dm_meta_info import _MetaInfoClassMember, _MetaInfoClass, _MetaInfoEnum
from ydk._core._dm_meta_info import ATTRIBUTE, REFERENCE_LIST, REFERENCE_LEAFLIST, REFERENCE_BITS, REFERENCE_UNION
from ydk._core._dm_meta_info import REFERENCE_CLASS, REFERENCE_IDENTITY_CLASS, REFERENCE_ENUM_CLASS, ANYXML_CLASS
from ydk._core._importer import _yang_ns

_meta_table = {
    'CallHomeMailSendInterval' : _MetaInfoEnum('CallHomeMailSendInterval',
        'ydk.models.cisco_ios_xr.Cisco_IOS_XR_call_home_cfg', 'CallHomeMailSendInterval',
        '''Call home mail send interval''',
        {
            'daily':'daily',
            'weekly':'weekly',
            'monthly':'monthly',
        }, 'Cisco-IOS-XR-call-home-cfg', _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-call-home-cfg']),
    'CallHomeDayOfWeek' : _MetaInfoEnum('CallHomeDayOfWeek',
        'ydk.models.cisco_ios_xr.Cisco_IOS_XR_call_home_cfg', 'CallHomeDayOfWeek',
        '''Call home day of week''',
        {
            'sunday':'sunday',
            'monday':'monday',
            'tuesday':'tuesday',
            'wednesday':'wednesday',
            'thursday':'thursday',
            'friday':'friday',
            'saturday':'saturday',
        }, 'Cisco-IOS-XR-call-home-cfg', _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-call-home-cfg']),
    'CallHomeEventSeverity' : _MetaInfoEnum('CallHomeEventSeverity',
        'ydk.models.cisco_ios_xr.Cisco_IOS_XR_call_home_cfg', 'CallHomeEventSeverity',
        '''Call home event severity''',
        {
            'debugging':'debugging',
            'normal':'normal',
            'notification':'notification',
            'warning':'warning',
            'minor':'minor',
            'major':'major',
            'critical':'critical',
            'fatal':'fatal',
            'disaster':'disaster',
            'catastrophic':'catastrophic',
        }, 'Cisco-IOS-XR-call-home-cfg', _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-call-home-cfg']),
    'SnapshotInterval' : _MetaInfoEnum('SnapshotInterval',
        'ydk.models.cisco_ios_xr.Cisco_IOS_XR_call_home_cfg', 'SnapshotInterval',
        '''Snapshot interval''',
        {
            'daily':'daily',
            'weekly':'weekly',
            'monthly':'monthly',
        }, 'Cisco-IOS-XR-call-home-cfg', _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-call-home-cfg']),
    'CallHomeTransMethod' : _MetaInfoEnum('CallHomeTransMethod',
        'ydk.models.cisco_ios_xr.Cisco_IOS_XR_call_home_cfg', 'CallHomeTransMethod',
        '''Call home trans method''',
        {
            'email':'email',
            'http':'http',
        }, 'Cisco-IOS-XR-call-home-cfg', _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-call-home-cfg']),
    'DataPrivacyLevel' : _MetaInfoEnum('DataPrivacyLevel',
        'ydk.models.cisco_ios_xr.Cisco_IOS_XR_call_home_cfg', 'DataPrivacyLevel',
        '''Data privacy level''',
        {
            'normal':'normal',
            'high':'high',
            'host-name':'host_name',
        }, 'Cisco-IOS-XR-call-home-cfg', _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-call-home-cfg']),
    'CallHome.MailServers.MailServer' : {
        'meta_info' : _MetaInfoClass('CallHome.MailServers.MailServer', REFERENCE_LIST,
            '''Email server''',
            False, 
            [
            _MetaInfoClassMember('mail-serv-address', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Email server
                ''',
                'mail_serv_address',
                'Cisco-IOS-XR-call-home-cfg', True),
            _MetaInfoClassMember('priority', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('1', '100')], [],
                '''                Mail server with lower # will be used first
                ''',
                'priority',
                'Cisco-IOS-XR-call-home-cfg', False),
            ],
            'Cisco-IOS-XR-call-home-cfg',
            'mail-server',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-call-home-cfg'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_call_home_cfg',
        ),
    },
    'CallHome.MailServers' : {
        'meta_info' : _MetaInfoClass('CallHome.MailServers', REFERENCE_CLASS,
            '''List of call-home mail_server''',
            False, 
            [
            _MetaInfoClassMember('mail-server', REFERENCE_LIST, 'MailServer', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_call_home_cfg', 'CallHome.MailServers.MailServer',
                [], [],
                '''                Email server
                ''',
                'mail_server',
                'Cisco-IOS-XR-call-home-cfg', False),
            ],
            'Cisco-IOS-XR-call-home-cfg',
            'mail-servers',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-call-home-cfg'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_call_home_cfg',
        ),
    },
    'CallHome.SyslogThrottling' : {
        'meta_info' : _MetaInfoClass('CallHome.SyslogThrottling', REFERENCE_CLASS,
            '''Enable or disable call-home syslog message
throttling''',
            False, 
            [
            _MetaInfoClassMember('active', ATTRIBUTE, 'bool', 'boolean',
                None, None,
                [], [],
                '''                Active syslog throttling
                ''',
                'active',
                'Cisco-IOS-XR-call-home-cfg', False),
            ],
            'Cisco-IOS-XR-call-home-cfg',
            'syslog-throttling',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-call-home-cfg'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_call_home_cfg',
        ),
    },
    'CallHome.HttpProxy' : {
        'meta_info' : _MetaInfoClass('CallHome.HttpProxy', REFERENCE_CLASS,
            '''http proxy server address and port''',
            False, 
            [
            _MetaInfoClassMember('server-address', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                http proxy server address
                ''',
                'server_address',
                'Cisco-IOS-XR-call-home-cfg', False),
            _MetaInfoClassMember('port', ATTRIBUTE, 'int', 'xr:Cisco-ios-xr-port-number',
                None, None,
                [('1', '65535')], [],
                '''                http proxy server's port
                ''',
                'port',
                'Cisco-IOS-XR-call-home-cfg', False),
            ],
            'Cisco-IOS-XR-call-home-cfg',
            'http-proxy',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-call-home-cfg'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_call_home_cfg',
        ),
    },
    'CallHome.Profiles.Profile.ReportType.ReportingCallhomeData' : {
        'meta_info' : _MetaInfoClass('CallHome.Profiles.Profile.ReportType.ReportingCallhomeData', REFERENCE_CLASS,
            '''Report smart call-home data''',
            False, 
            [
            _MetaInfoClassMember('enable', ATTRIBUTE, 'bool', 'boolean',
                None, None,
                [], [],
                '''                Enable report smart call-home data
                ''',
                'enable',
                'Cisco-IOS-XR-call-home-cfg', False),
            ],
            'Cisco-IOS-XR-call-home-cfg',
            'reporting-callhome-data',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-call-home-cfg'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_call_home_cfg',
        ),
    },
    'CallHome.Profiles.Profile.ReportType.ReportingLicensingData' : {
        'meta_info' : _MetaInfoClass('CallHome.Profiles.Profile.ReportType.ReportingLicensingData', REFERENCE_CLASS,
            '''Report smart licensing data''',
            False, 
            [
            _MetaInfoClassMember('enable', ATTRIBUTE, 'bool', 'boolean',
                None, None,
                [], [],
                '''                Enable report smart licensing data
                ''',
                'enable',
                'Cisco-IOS-XR-call-home-cfg', False),
            ],
            'Cisco-IOS-XR-call-home-cfg',
            'reporting-licensing-data',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-call-home-cfg'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_call_home_cfg',
        ),
    },
    'CallHome.Profiles.Profile.ReportType' : {
        'meta_info' : _MetaInfoClass('CallHome.Profiles.Profile.ReportType', REFERENCE_CLASS,
            '''Choose what data to report''',
            False, 
            [
            _MetaInfoClassMember('reporting-callhome-data', REFERENCE_CLASS, 'ReportingCallhomeData', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_call_home_cfg', 'CallHome.Profiles.Profile.ReportType.ReportingCallhomeData',
                [], [],
                '''                Report smart call-home data
                ''',
                'reporting_callhome_data',
                'Cisco-IOS-XR-call-home-cfg', False),
            _MetaInfoClassMember('reporting-licensing-data', REFERENCE_CLASS, 'ReportingLicensingData', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_call_home_cfg', 'CallHome.Profiles.Profile.ReportType.ReportingLicensingData',
                [], [],
                '''                Report smart licensing data
                ''',
                'reporting_licensing_data',
                'Cisco-IOS-XR-call-home-cfg', False),
            ],
            'Cisco-IOS-XR-call-home-cfg',
            'report-type',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-call-home-cfg'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_call_home_cfg',
        ),
    },
    'CallHome.Profiles.Profile.Methods.Method' : {
        'meta_info' : _MetaInfoClass('CallHome.Profiles.Profile.Methods.Method', REFERENCE_LIST,
            '''Transport method''',
            False, 
            [
            _MetaInfoClassMember('method', REFERENCE_ENUM_CLASS, 'CallHomeTransMethod', 'Call-home-trans-method',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_call_home_cfg', 'CallHomeTransMethod',
                [], [],
                '''                Transport Method
                ''',
                'method',
                'Cisco-IOS-XR-call-home-cfg', True),
            _MetaInfoClassMember('enable', ATTRIBUTE, 'bool', 'boolean',
                None, None,
                [], [],
                '''                Enable this transport method
                ''',
                'enable',
                'Cisco-IOS-XR-call-home-cfg', False),
            ],
            'Cisco-IOS-XR-call-home-cfg',
            'method',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-call-home-cfg'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_call_home_cfg',
        ),
    },
    'CallHome.Profiles.Profile.Methods' : {
        'meta_info' : _MetaInfoClass('CallHome.Profiles.Profile.Methods', REFERENCE_CLASS,
            '''Transport method (http or email)''',
            False, 
            [
            _MetaInfoClassMember('method', REFERENCE_LIST, 'Method', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_call_home_cfg', 'CallHome.Profiles.Profile.Methods.Method',
                [], [],
                '''                Transport method
                ''',
                'method',
                'Cisco-IOS-XR-call-home-cfg', False),
            ],
            'Cisco-IOS-XR-call-home-cfg',
            'methods',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-call-home-cfg'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_call_home_cfg',
        ),
    },
    'CallHome.Profiles.Profile.Addresses.Address' : {
        'meta_info' : _MetaInfoClass('CallHome.Profiles.Profile.Addresses.Address', REFERENCE_LIST,
            '''A specific address''',
            False, 
            [
            _MetaInfoClassMember('method', REFERENCE_ENUM_CLASS, 'CallHomeTransMethod', 'Call-home-trans-method',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_call_home_cfg', 'CallHomeTransMethod',
                [], [],
                '''                Transpotation Method
                ''',
                'method',
                'Cisco-IOS-XR-call-home-cfg', True),
            _MetaInfoClassMember('destination-addr', ATTRIBUTE, 'str', 'string',
                None, None,
                [(1, 200)], [],
                '''                Destination address (1-200) characters
                ''',
                'destination_addr',
                'Cisco-IOS-XR-call-home-cfg', True),
            _MetaInfoClassMember('enable', ATTRIBUTE, 'bool', 'boolean',
                None, None,
                [], [],
                '''                Set the address
                ''',
                'enable',
                'Cisco-IOS-XR-call-home-cfg', False),
            ],
            'Cisco-IOS-XR-call-home-cfg',
            'address',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-call-home-cfg'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_call_home_cfg',
        ),
    },
    'CallHome.Profiles.Profile.Addresses' : {
        'meta_info' : _MetaInfoClass('CallHome.Profiles.Profile.Addresses', REFERENCE_CLASS,
            '''List of destination address''',
            False, 
            [
            _MetaInfoClassMember('address', REFERENCE_LIST, 'Address', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_call_home_cfg', 'CallHome.Profiles.Profile.Addresses.Address',
                [], [],
                '''                A specific address
                ''',
                'address',
                'Cisco-IOS-XR-call-home-cfg', False),
            ],
            'Cisco-IOS-XR-call-home-cfg',
            'addresses',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-call-home-cfg'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_call_home_cfg',
        ),
    },
    'CallHome.Profiles.Profile.SubscribeAlertGroup.Environment' : {
        'meta_info' : _MetaInfoClass('CallHome.Profiles.Profile.SubscribeAlertGroup.Environment', REFERENCE_CLASS,
            '''environmental info''',
            False, 
            [
            _MetaInfoClassMember('severity', REFERENCE_ENUM_CLASS, 'CallHomeEventSeverity', 'Call-home-event-severity',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_call_home_cfg', 'CallHomeEventSeverity',
                [], [],
                '''                Severity
                ''',
                'severity',
                'Cisco-IOS-XR-call-home-cfg', False),
            ],
            'Cisco-IOS-XR-call-home-cfg',
            'environment',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-call-home-cfg'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_call_home_cfg',
        ),
    },
    'CallHome.Profiles.Profile.SubscribeAlertGroup.Configuration.Periodic' : {
        'meta_info' : _MetaInfoClass('CallHome.Profiles.Profile.SubscribeAlertGroup.Configuration.Periodic', REFERENCE_CLASS,
            '''Periodic call-home message''',
            False, 
            [
            _MetaInfoClassMember('interval', REFERENCE_ENUM_CLASS, 'CallHomeMailSendInterval', 'Call-home-mail-send-interval',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_call_home_cfg', 'CallHomeMailSendInterval',
                [], [],
                '''                none
                ''',
                'interval',
                'Cisco-IOS-XR-call-home-cfg', False),
            _MetaInfoClassMember('day', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '31')], [],
                '''                Day
                ''',
                'day',
                'Cisco-IOS-XR-call-home-cfg', False),
            _MetaInfoClassMember('weekday', REFERENCE_ENUM_CLASS, 'CallHomeDayOfWeek', 'Call-home-day-of-week',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_call_home_cfg', 'CallHomeDayOfWeek',
                [], [],
                '''                Day of week
                ''',
                'weekday',
                'Cisco-IOS-XR-call-home-cfg', False),
            _MetaInfoClassMember('hour', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '23')], [],
                '''                Hour
                ''',
                'hour',
                'Cisco-IOS-XR-call-home-cfg', False),
            _MetaInfoClassMember('minute', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '59')], [],
                '''                Minute
                ''',
                'minute',
                'Cisco-IOS-XR-call-home-cfg', False),
            ],
            'Cisco-IOS-XR-call-home-cfg',
            'periodic',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-call-home-cfg'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_call_home_cfg',
        ),
    },
    'CallHome.Profiles.Profile.SubscribeAlertGroup.Configuration' : {
        'meta_info' : _MetaInfoClass('CallHome.Profiles.Profile.SubscribeAlertGroup.Configuration', REFERENCE_CLASS,
            '''configuration info''',
            False, 
            [
            _MetaInfoClassMember('periodic', REFERENCE_CLASS, 'Periodic', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_call_home_cfg', 'CallHome.Profiles.Profile.SubscribeAlertGroup.Configuration.Periodic',
                [], [],
                '''                Periodic call-home message
                ''',
                'periodic',
                'Cisco-IOS-XR-call-home-cfg', False),
            _MetaInfoClassMember('subscribe', ATTRIBUTE, 'Empty', 'empty',
                None, None,
                [], [],
                '''                Subscribe the alert-group
                ''',
                'subscribe',
                'Cisco-IOS-XR-call-home-cfg', False),
            ],
            'Cisco-IOS-XR-call-home-cfg',
            'configuration',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-call-home-cfg'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_call_home_cfg',
        ),
    },
    'CallHome.Profiles.Profile.SubscribeAlertGroup.Snapshot.Periodic' : {
        'meta_info' : _MetaInfoClass('CallHome.Profiles.Profile.SubscribeAlertGroup.Snapshot.Periodic', REFERENCE_CLASS,
            '''Periodic call-home message''',
            False, 
            [
            _MetaInfoClassMember('interval', REFERENCE_ENUM_CLASS, 'SnapshotInterval', 'Snapshot-interval',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_call_home_cfg', 'SnapshotInterval',
                [], [],
                '''                none
                ''',
                'interval',
                'Cisco-IOS-XR-call-home-cfg', False),
            _MetaInfoClassMember('day', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '31')], [],
                '''                Day of month
                ''',
                'day',
                'Cisco-IOS-XR-call-home-cfg', False),
            _MetaInfoClassMember('weekday', REFERENCE_ENUM_CLASS, 'CallHomeDayOfWeek', 'Call-home-day-of-week',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_call_home_cfg', 'CallHomeDayOfWeek',
                [], [],
                '''                Day of week
                ''',
                'weekday',
                'Cisco-IOS-XR-call-home-cfg', False),
            _MetaInfoClassMember('hour', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '23')], [],
                '''                Hour
                ''',
                'hour',
                'Cisco-IOS-XR-call-home-cfg', False),
            _MetaInfoClassMember('minute', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '59')], [],
                '''                Minute
                ''',
                'minute',
                'Cisco-IOS-XR-call-home-cfg', False),
            ],
            'Cisco-IOS-XR-call-home-cfg',
            'periodic',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-call-home-cfg'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_call_home_cfg',
        ),
    },
    'CallHome.Profiles.Profile.SubscribeAlertGroup.Snapshot' : {
        'meta_info' : _MetaInfoClass('CallHome.Profiles.Profile.SubscribeAlertGroup.Snapshot', REFERENCE_CLASS,
            '''snapshot info''',
            False, 
            [
            _MetaInfoClassMember('periodic', REFERENCE_CLASS, 'Periodic', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_call_home_cfg', 'CallHome.Profiles.Profile.SubscribeAlertGroup.Snapshot.Periodic',
                [], [],
                '''                Periodic call-home message
                ''',
                'periodic',
                'Cisco-IOS-XR-call-home-cfg', False),
            ],
            'Cisco-IOS-XR-call-home-cfg',
            'snapshot',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-call-home-cfg'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_call_home_cfg',
        ),
    },
    'CallHome.Profiles.Profile.SubscribeAlertGroup.Inventory.Periodic' : {
        'meta_info' : _MetaInfoClass('CallHome.Profiles.Profile.SubscribeAlertGroup.Inventory.Periodic', REFERENCE_CLASS,
            '''Periodic call-home message''',
            False, 
            [
            _MetaInfoClassMember('interval', REFERENCE_ENUM_CLASS, 'CallHomeMailSendInterval', 'Call-home-mail-send-interval',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_call_home_cfg', 'CallHomeMailSendInterval',
                [], [],
                '''                none
                ''',
                'interval',
                'Cisco-IOS-XR-call-home-cfg', False),
            _MetaInfoClassMember('day', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '31')], [],
                '''                Day of month
                ''',
                'day',
                'Cisco-IOS-XR-call-home-cfg', False),
            _MetaInfoClassMember('weekday', REFERENCE_ENUM_CLASS, 'CallHomeDayOfWeek', 'Call-home-day-of-week',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_call_home_cfg', 'CallHomeDayOfWeek',
                [], [],
                '''                Day of week
                ''',
                'weekday',
                'Cisco-IOS-XR-call-home-cfg', False),
            _MetaInfoClassMember('hour', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '23')], [],
                '''                Hour
                ''',
                'hour',
                'Cisco-IOS-XR-call-home-cfg', False),
            _MetaInfoClassMember('minute', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '59')], [],
                '''                Minute
                ''',
                'minute',
                'Cisco-IOS-XR-call-home-cfg', False),
            ],
            'Cisco-IOS-XR-call-home-cfg',
            'periodic',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-call-home-cfg'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_call_home_cfg',
        ),
    },
    'CallHome.Profiles.Profile.SubscribeAlertGroup.Inventory' : {
        'meta_info' : _MetaInfoClass('CallHome.Profiles.Profile.SubscribeAlertGroup.Inventory', REFERENCE_CLASS,
            '''inventory info''',
            False, 
            [
            _MetaInfoClassMember('periodic', REFERENCE_CLASS, 'Periodic', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_call_home_cfg', 'CallHome.Profiles.Profile.SubscribeAlertGroup.Inventory.Periodic',
                [], [],
                '''                Periodic call-home message
                ''',
                'periodic',
                'Cisco-IOS-XR-call-home-cfg', False),
            _MetaInfoClassMember('subscribe', ATTRIBUTE, 'Empty', 'empty',
                None, None,
                [], [],
                '''                Subscribe the alert-group
                ''',
                'subscribe',
                'Cisco-IOS-XR-call-home-cfg', False),
            ],
            'Cisco-IOS-XR-call-home-cfg',
            'inventory',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-call-home-cfg'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_call_home_cfg',
        ),
    },
    'CallHome.Profiles.Profile.SubscribeAlertGroup.Crash' : {
        'meta_info' : _MetaInfoClass('CallHome.Profiles.Profile.SubscribeAlertGroup.Crash', REFERENCE_CLASS,
            '''Crash info''',
            False, 
            [
            _MetaInfoClassMember('subscribe', ATTRIBUTE, 'Empty', 'empty',
                None, None,
                [], [],
                '''                Subscribe crash group
                ''',
                'subscribe',
                'Cisco-IOS-XR-call-home-cfg', False),
            ],
            'Cisco-IOS-XR-call-home-cfg',
            'crash',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-call-home-cfg'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_call_home_cfg',
        ),
    },
    'CallHome.Profiles.Profile.SubscribeAlertGroup.Syslogs.Syslog' : {
        'meta_info' : _MetaInfoClass('CallHome.Profiles.Profile.SubscribeAlertGroup.Syslogs.Syslog', REFERENCE_LIST,
            '''Syslog message pattern to be matched''',
            False, 
            [
            _MetaInfoClassMember('syslog-pattern', ATTRIBUTE, 'str', 'string',
                None, None,
                [(1, 80)], [],
                '''                Syslog message pattern to be matched
                ''',
                'syslog_pattern',
                'Cisco-IOS-XR-call-home-cfg', True),
            _MetaInfoClassMember('severity', REFERENCE_ENUM_CLASS, 'CallHomeEventSeverity', 'Call-home-event-severity',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_call_home_cfg', 'CallHomeEventSeverity',
                [], [],
                '''                Severity
                ''',
                'severity',
                'Cisco-IOS-XR-call-home-cfg', False),
            ],
            'Cisco-IOS-XR-call-home-cfg',
            'syslog',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-call-home-cfg'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_call_home_cfg',
        ),
    },
    'CallHome.Profiles.Profile.SubscribeAlertGroup.Syslogs' : {
        'meta_info' : _MetaInfoClass('CallHome.Profiles.Profile.SubscribeAlertGroup.Syslogs', REFERENCE_CLASS,
            '''syslog info''',
            False, 
            [
            _MetaInfoClassMember('syslog', REFERENCE_LIST, 'Syslog', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_call_home_cfg', 'CallHome.Profiles.Profile.SubscribeAlertGroup.Syslogs.Syslog',
                [], [],
                '''                Syslog message pattern to be matched
                ''',
                'syslog',
                'Cisco-IOS-XR-call-home-cfg', False),
            ],
            'Cisco-IOS-XR-call-home-cfg',
            'syslogs',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-call-home-cfg'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_call_home_cfg',
        ),
    },
    'CallHome.Profiles.Profile.SubscribeAlertGroup' : {
        'meta_info' : _MetaInfoClass('CallHome.Profiles.Profile.SubscribeAlertGroup', REFERENCE_CLASS,
            '''Subscribe to alert-group''',
            False, 
            [
            _MetaInfoClassMember('environment', REFERENCE_CLASS, 'Environment', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_call_home_cfg', 'CallHome.Profiles.Profile.SubscribeAlertGroup.Environment',
                [], [],
                '''                environmental info
                ''',
                'environment',
                'Cisco-IOS-XR-call-home-cfg', False),
            _MetaInfoClassMember('configuration', REFERENCE_CLASS, 'Configuration', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_call_home_cfg', 'CallHome.Profiles.Profile.SubscribeAlertGroup.Configuration',
                [], [],
                '''                configuration info
                ''',
                'configuration',
                'Cisco-IOS-XR-call-home-cfg', False),
            _MetaInfoClassMember('snapshot', REFERENCE_CLASS, 'Snapshot', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_call_home_cfg', 'CallHome.Profiles.Profile.SubscribeAlertGroup.Snapshot',
                [], [],
                '''                snapshot info
                ''',
                'snapshot',
                'Cisco-IOS-XR-call-home-cfg', False),
            _MetaInfoClassMember('inventory', REFERENCE_CLASS, 'Inventory', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_call_home_cfg', 'CallHome.Profiles.Profile.SubscribeAlertGroup.Inventory',
                [], [],
                '''                inventory info
                ''',
                'inventory',
                'Cisco-IOS-XR-call-home-cfg', False),
            _MetaInfoClassMember('crash', REFERENCE_CLASS, 'Crash', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_call_home_cfg', 'CallHome.Profiles.Profile.SubscribeAlertGroup.Crash',
                [], [],
                '''                Crash info
                ''',
                'crash',
                'Cisco-IOS-XR-call-home-cfg', False),
            _MetaInfoClassMember('syslogs', REFERENCE_CLASS, 'Syslogs', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_call_home_cfg', 'CallHome.Profiles.Profile.SubscribeAlertGroup.Syslogs',
                [], [],
                '''                syslog info
                ''',
                'syslogs',
                'Cisco-IOS-XR-call-home-cfg', False),
            ],
            'Cisco-IOS-XR-call-home-cfg',
            'subscribe-alert-group',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-call-home-cfg'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_call_home_cfg',
        ),
    },
    'CallHome.Profiles.Profile' : {
        'meta_info' : _MetaInfoClass('CallHome.Profiles.Profile', REFERENCE_LIST,
            '''A specific profile''',
            False, 
            [
            _MetaInfoClassMember('profile-name', ATTRIBUTE, 'str', 'xr:Cisco-ios-xr-string',
                None, None,
                [], [b'[\\w\\-\\.:,_@#%$\\+=\\|;]+'],
                '''                Profile name
                ''',
                'profile_name',
                'Cisco-IOS-XR-call-home-cfg', True),
            _MetaInfoClassMember('report-type', REFERENCE_CLASS, 'ReportType', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_call_home_cfg', 'CallHome.Profiles.Profile.ReportType',
                [], [],
                '''                Choose what data to report
                ''',
                'report_type',
                'Cisco-IOS-XR-call-home-cfg', False),
            _MetaInfoClassMember('methods', REFERENCE_CLASS, 'Methods', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_call_home_cfg', 'CallHome.Profiles.Profile.Methods',
                [], [],
                '''                Transport method (http or email)
                ''',
                'methods',
                'Cisco-IOS-XR-call-home-cfg', False),
            _MetaInfoClassMember('addresses', REFERENCE_CLASS, 'Addresses', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_call_home_cfg', 'CallHome.Profiles.Profile.Addresses',
                [], [],
                '''                List of destination address
                ''',
                'addresses',
                'Cisco-IOS-XR-call-home-cfg', False),
            _MetaInfoClassMember('subscribe-alert-group', REFERENCE_CLASS, 'SubscribeAlertGroup', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_call_home_cfg', 'CallHome.Profiles.Profile.SubscribeAlertGroup',
                [], [],
                '''                Subscribe to alert-group
                ''',
                'subscribe_alert_group',
                'Cisco-IOS-XR-call-home-cfg', False),
            _MetaInfoClassMember('message-format', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                none
                ''',
                'message_format',
                'Cisco-IOS-XR-call-home-cfg', False),
            _MetaInfoClassMember('anonymous', ATTRIBUTE, 'bool', 'boolean',
                None, None,
                [], [],
                '''                Enable call-home anonymous reporting only
                ''',
                'anonymous',
                'Cisco-IOS-XR-call-home-cfg', False),
            _MetaInfoClassMember('message-size-limit', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('50', '3145728')], [],
                '''                To specify message size limit for this profile
                ''',
                'message_size_limit',
                'Cisco-IOS-XR-call-home-cfg', False),
            _MetaInfoClassMember('active', ATTRIBUTE, 'Empty', 'empty',
                None, None,
                [], [],
                '''                Activate the current profile
                ''',
                'active',
                'Cisco-IOS-XR-call-home-cfg', False),
            ],
            'Cisco-IOS-XR-call-home-cfg',
            'profile',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-call-home-cfg'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_call_home_cfg',
        ),
    },
    'CallHome.Profiles' : {
        'meta_info' : _MetaInfoClass('CallHome.Profiles', REFERENCE_CLASS,
            '''List of profiles''',
            False, 
            [
            _MetaInfoClassMember('profile', REFERENCE_LIST, 'Profile', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_call_home_cfg', 'CallHome.Profiles.Profile',
                [], [],
                '''                A specific profile
                ''',
                'profile',
                'Cisco-IOS-XR-call-home-cfg', False),
            ],
            'Cisco-IOS-XR-call-home-cfg',
            'profiles',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-call-home-cfg'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_call_home_cfg',
        ),
    },
    'CallHome.AlertGroups.AlertGroup' : {
        'meta_info' : _MetaInfoClass('CallHome.AlertGroups.AlertGroup', REFERENCE_LIST,
            '''A specific alert-group''',
            False, 
            [
            _MetaInfoClassMember('alert-group-name', ATTRIBUTE, 'str', 'xr:Cisco-ios-xr-string',
                None, None,
                [], [b'[\\w\\-\\.:,_@#%$\\+=\\|;]+'],
                '''                none
                ''',
                'alert_group_name',
                'Cisco-IOS-XR-call-home-cfg', True),
            _MetaInfoClassMember('enable', ATTRIBUTE, 'bool', 'boolean',
                None, None,
                [], [],
                '''                Enable the alert-group
                ''',
                'enable',
                'Cisco-IOS-XR-call-home-cfg', False),
            _MetaInfoClassMember('disable', ATTRIBUTE, 'bool', 'boolean',
                None, None,
                [], [],
                '''                Disable the alert-group
                ''',
                'disable',
                'Cisco-IOS-XR-call-home-cfg', False),
            ],
            'Cisco-IOS-XR-call-home-cfg',
            'alert-group',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-call-home-cfg'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_call_home_cfg',
        ),
    },
    'CallHome.AlertGroups' : {
        'meta_info' : _MetaInfoClass('CallHome.AlertGroups', REFERENCE_CLASS,
            '''List of alert-group''',
            False, 
            [
            _MetaInfoClassMember('alert-group', REFERENCE_LIST, 'AlertGroup', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_call_home_cfg', 'CallHome.AlertGroups.AlertGroup',
                [], [],
                '''                A specific alert-group
                ''',
                'alert_group',
                'Cisco-IOS-XR-call-home-cfg', False),
            ],
            'Cisco-IOS-XR-call-home-cfg',
            'alert-groups',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-call-home-cfg'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_call_home_cfg',
        ),
    },
    'CallHome.DataPrivacies.DataPrivacy' : {
        'meta_info' : _MetaInfoClass('CallHome.DataPrivacies.DataPrivacy', REFERENCE_LIST,
            '''level hostname''',
            False, 
            [
            _MetaInfoClassMember('host-name', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Data privacy type (hostname or level)
                ''',
                'host_name',
                'Cisco-IOS-XR-call-home-cfg', True),
            _MetaInfoClassMember('level', REFERENCE_ENUM_CLASS, 'DataPrivacyLevel', 'Data-privacy-level',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_call_home_cfg', 'DataPrivacyLevel',
                [], [],
                '''                Set call-home data-privacy level
                ''',
                'level',
                'Cisco-IOS-XR-call-home-cfg', False),
            ],
            'Cisco-IOS-XR-call-home-cfg',
            'data-privacy',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-call-home-cfg'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_call_home_cfg',
        ),
    },
    'CallHome.DataPrivacies' : {
        'meta_info' : _MetaInfoClass('CallHome.DataPrivacies', REFERENCE_CLASS,
            '''Set call-home data-privacy''',
            False, 
            [
            _MetaInfoClassMember('data-privacy', REFERENCE_LIST, 'DataPrivacy', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_call_home_cfg', 'CallHome.DataPrivacies.DataPrivacy',
                [], [],
                '''                level hostname
                ''',
                'data_privacy',
                'Cisco-IOS-XR-call-home-cfg', False),
            ],
            'Cisco-IOS-XR-call-home-cfg',
            'data-privacies',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-call-home-cfg'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_call_home_cfg',
        ),
    },
    'CallHome.AlertGroupConfig.SnapshotCommands.SnapshotCommand' : {
        'meta_info' : _MetaInfoClass('CallHome.AlertGroupConfig.SnapshotCommands.SnapshotCommand', REFERENCE_LIST,
            '''A specific CLI cmd for snapshot''',
            False, 
            [
            _MetaInfoClassMember('command', ATTRIBUTE, 'str', 'string',
                None, None,
                [(1, 127)], [],
                '''                new added command
                ''',
                'command',
                'Cisco-IOS-XR-call-home-cfg', True),
            _MetaInfoClassMember('active', ATTRIBUTE, 'Empty', 'empty',
                None, None,
                [], [],
                '''                enable snapshot cmd
                ''',
                'active',
                'Cisco-IOS-XR-call-home-cfg', False),
            ],
            'Cisco-IOS-XR-call-home-cfg',
            'snapshot-command',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-call-home-cfg'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_call_home_cfg',
        ),
    },
    'CallHome.AlertGroupConfig.SnapshotCommands' : {
        'meta_info' : _MetaInfoClass('CallHome.AlertGroupConfig.SnapshotCommands', REFERENCE_CLASS,
            '''snapshot for adding CLI command''',
            False, 
            [
            _MetaInfoClassMember('snapshot-command', REFERENCE_LIST, 'SnapshotCommand', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_call_home_cfg', 'CallHome.AlertGroupConfig.SnapshotCommands.SnapshotCommand',
                [], [],
                '''                A specific CLI cmd for snapshot
                ''',
                'snapshot_command',
                'Cisco-IOS-XR-call-home-cfg', False),
            ],
            'Cisco-IOS-XR-call-home-cfg',
            'snapshot-commands',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-call-home-cfg'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_call_home_cfg',
        ),
    },
    'CallHome.AlertGroupConfig' : {
        'meta_info' : _MetaInfoClass('CallHome.AlertGroupConfig', REFERENCE_CLASS,
            '''alert-group config''',
            False, 
            [
            _MetaInfoClassMember('snapshot-commands', REFERENCE_CLASS, 'SnapshotCommands', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_call_home_cfg', 'CallHome.AlertGroupConfig.SnapshotCommands',
                [], [],
                '''                snapshot for adding CLI command
                ''',
                'snapshot_commands',
                'Cisco-IOS-XR-call-home-cfg', False),
            ],
            'Cisco-IOS-XR-call-home-cfg',
            'alert-group-config',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-call-home-cfg'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_call_home_cfg',
        ),
    },
    'CallHome.Authorization' : {
        'meta_info' : _MetaInfoClass('CallHome.Authorization', REFERENCE_CLASS,
            '''Config aaa authorization, default username is
callhome''',
            False, 
            [
            _MetaInfoClassMember('username', ATTRIBUTE, 'str', 'xr:Cisco-ios-xr-string',
                None, None,
                [(1, 64)], [],
                '''                Username for authorization. default is callhome
                ''',
                'username',
                'Cisco-IOS-XR-call-home-cfg', False),
            _MetaInfoClassMember('active', ATTRIBUTE, 'Empty', 'empty',
                None, None,
                [], [],
                '''                Enable call-home aaa-authorization
                ''',
                'active',
                'Cisco-IOS-XR-call-home-cfg', False),
            ],
            'Cisco-IOS-XR-call-home-cfg',
            'authorization',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-call-home-cfg'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_call_home_cfg',
        ),
    },
    'CallHome' : {
        'meta_info' : _MetaInfoClass('CallHome', REFERENCE_CLASS,
            '''Set CallHome parameters''',
            False, 
            [
            _MetaInfoClassMember('mail-servers', REFERENCE_CLASS, 'MailServers', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_call_home_cfg', 'CallHome.MailServers',
                [], [],
                '''                List of call-home mail_server
                ''',
                'mail_servers',
                'Cisco-IOS-XR-call-home-cfg', False),
            _MetaInfoClassMember('syslog-throttling', REFERENCE_CLASS, 'SyslogThrottling', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_call_home_cfg', 'CallHome.SyslogThrottling',
                [], [],
                '''                Enable or disable call-home syslog message
                throttling
                ''',
                'syslog_throttling',
                'Cisco-IOS-XR-call-home-cfg', False),
            _MetaInfoClassMember('http-proxy', REFERENCE_CLASS, 'HttpProxy', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_call_home_cfg', 'CallHome.HttpProxy',
                [], [],
                '''                http proxy server address and port
                ''',
                'http_proxy',
                'Cisco-IOS-XR-call-home-cfg', False),
            _MetaInfoClassMember('profiles', REFERENCE_CLASS, 'Profiles', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_call_home_cfg', 'CallHome.Profiles',
                [], [],
                '''                List of profiles
                ''',
                'profiles',
                'Cisco-IOS-XR-call-home-cfg', False),
            _MetaInfoClassMember('alert-groups', REFERENCE_CLASS, 'AlertGroups', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_call_home_cfg', 'CallHome.AlertGroups',
                [], [],
                '''                List of alert-group
                ''',
                'alert_groups',
                'Cisco-IOS-XR-call-home-cfg', False),
            _MetaInfoClassMember('data-privacies', REFERENCE_CLASS, 'DataPrivacies', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_call_home_cfg', 'CallHome.DataPrivacies',
                [], [],
                '''                Set call-home data-privacy
                ''',
                'data_privacies',
                'Cisco-IOS-XR-call-home-cfg', False),
            _MetaInfoClassMember('alert-group-config', REFERENCE_CLASS, 'AlertGroupConfig', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_call_home_cfg', 'CallHome.AlertGroupConfig',
                [], [],
                '''                alert-group config
                ''',
                'alert_group_config',
                'Cisco-IOS-XR-call-home-cfg', False),
            _MetaInfoClassMember('authorization', REFERENCE_CLASS, 'Authorization', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_call_home_cfg', 'CallHome.Authorization',
                [], [],
                '''                Config aaa authorization, default username is
                callhome
                ''',
                'authorization',
                'Cisco-IOS-XR-call-home-cfg', False),
            _MetaInfoClassMember('customer-id', ATTRIBUTE, 'str', 'string',
                None, None,
                [(1, 64)], [],
                '''                Customer identification for Cisco Smart Call
                Home
                ''',
                'customer_id',
                'Cisco-IOS-XR-call-home-cfg', False),
            _MetaInfoClassMember('phone-number', ATTRIBUTE, 'str', 'string',
                None, None,
                [(1, 17)], [],
                '''                Phone number of the contact person.
                ''',
                'phone_number',
                'Cisco-IOS-XR-call-home-cfg', False),
            _MetaInfoClassMember('contact-smart-licensing', ATTRIBUTE, 'bool', 'boolean',
                None, None,
                [], [],
                '''                System Contact is Smart Licensing
                ''',
                'contact_smart_licensing',
                'Cisco-IOS-XR-call-home-cfg', False),
            _MetaInfoClassMember('contact-email-address', ATTRIBUTE, 'str', 'string',
                None, None,
                [(1, 194)], [],
                '''                Contact person's email address
                ''',
                'contact_email_address',
                'Cisco-IOS-XR-call-home-cfg', False),
            _MetaInfoClassMember('rate-limit', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('1', '5')], [],
                '''                Call-home event trigger rate-limit threshold per
                minute.
                ''',
                'rate_limit',
                'Cisco-IOS-XR-call-home-cfg', False),
            _MetaInfoClassMember('site-id', ATTRIBUTE, 'str', 'string',
                None, None,
                [(1, 200)], [],
                '''                Site identification for Cisco Smart Call Home
                ''',
                'site_id',
                'Cisco-IOS-XR-call-home-cfg', False),
            _MetaInfoClassMember('vrf', ATTRIBUTE, 'str', 'xr:Cisco-ios-xr-string',
                None, None,
                [(1, 32)], [],
                '''                Vrf routing/forwarding instance name
                ''',
                'vrf',
                'Cisco-IOS-XR-call-home-cfg', False),
            _MetaInfoClassMember('street-address', ATTRIBUTE, 'str', 'string',
                None, None,
                [(1, 200)], [],
                '''                Street address, city, state, and zip code.
                ''',
                'street_address',
                'Cisco-IOS-XR-call-home-cfg', False),
            _MetaInfoClassMember('source-interface', ATTRIBUTE, 'str', 'xr:Interface-name',
                None, None,
                [], [b'[a-zA-Z0-9._/-]+'],
                '''                Source interface name to send call-home messages
                ''',
                'source_interface',
                'Cisco-IOS-XR-call-home-cfg', False),
            _MetaInfoClassMember('contract-id', ATTRIBUTE, 'str', 'string',
                None, None,
                [(1, 64)], [],
                '''                Contract identification for Cisco Smart Call
                Home
                ''',
                'contract_id',
                'Cisco-IOS-XR-call-home-cfg', False),
            _MetaInfoClassMember('reply-to', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Call home msg's reply-to email address
                ''',
                'reply_to',
                'Cisco-IOS-XR-call-home-cfg', False),
            _MetaInfoClassMember('from', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Call home msg's from email address
                ''',
                'from_',
                'Cisco-IOS-XR-call-home-cfg', False),
            _MetaInfoClassMember('active', ATTRIBUTE, 'Empty', 'empty',
                None, None,
                [], [],
                '''                Enable call-home service
                ''',
                'active',
                'Cisco-IOS-XR-call-home-cfg', False),
            ],
            'Cisco-IOS-XR-call-home-cfg',
            'call-home',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-call-home-cfg'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_call_home_cfg',
        ),
    },
}
_meta_table['CallHome.MailServers.MailServer']['meta_info'].parent =_meta_table['CallHome.MailServers']['meta_info']
_meta_table['CallHome.Profiles.Profile.ReportType.ReportingCallhomeData']['meta_info'].parent =_meta_table['CallHome.Profiles.Profile.ReportType']['meta_info']
_meta_table['CallHome.Profiles.Profile.ReportType.ReportingLicensingData']['meta_info'].parent =_meta_table['CallHome.Profiles.Profile.ReportType']['meta_info']
_meta_table['CallHome.Profiles.Profile.Methods.Method']['meta_info'].parent =_meta_table['CallHome.Profiles.Profile.Methods']['meta_info']
_meta_table['CallHome.Profiles.Profile.Addresses.Address']['meta_info'].parent =_meta_table['CallHome.Profiles.Profile.Addresses']['meta_info']
_meta_table['CallHome.Profiles.Profile.SubscribeAlertGroup.Configuration.Periodic']['meta_info'].parent =_meta_table['CallHome.Profiles.Profile.SubscribeAlertGroup.Configuration']['meta_info']
_meta_table['CallHome.Profiles.Profile.SubscribeAlertGroup.Snapshot.Periodic']['meta_info'].parent =_meta_table['CallHome.Profiles.Profile.SubscribeAlertGroup.Snapshot']['meta_info']
_meta_table['CallHome.Profiles.Profile.SubscribeAlertGroup.Inventory.Periodic']['meta_info'].parent =_meta_table['CallHome.Profiles.Profile.SubscribeAlertGroup.Inventory']['meta_info']
_meta_table['CallHome.Profiles.Profile.SubscribeAlertGroup.Syslogs.Syslog']['meta_info'].parent =_meta_table['CallHome.Profiles.Profile.SubscribeAlertGroup.Syslogs']['meta_info']
_meta_table['CallHome.Profiles.Profile.SubscribeAlertGroup.Environment']['meta_info'].parent =_meta_table['CallHome.Profiles.Profile.SubscribeAlertGroup']['meta_info']
_meta_table['CallHome.Profiles.Profile.SubscribeAlertGroup.Configuration']['meta_info'].parent =_meta_table['CallHome.Profiles.Profile.SubscribeAlertGroup']['meta_info']
_meta_table['CallHome.Profiles.Profile.SubscribeAlertGroup.Snapshot']['meta_info'].parent =_meta_table['CallHome.Profiles.Profile.SubscribeAlertGroup']['meta_info']
_meta_table['CallHome.Profiles.Profile.SubscribeAlertGroup.Inventory']['meta_info'].parent =_meta_table['CallHome.Profiles.Profile.SubscribeAlertGroup']['meta_info']
_meta_table['CallHome.Profiles.Profile.SubscribeAlertGroup.Crash']['meta_info'].parent =_meta_table['CallHome.Profiles.Profile.SubscribeAlertGroup']['meta_info']
_meta_table['CallHome.Profiles.Profile.SubscribeAlertGroup.Syslogs']['meta_info'].parent =_meta_table['CallHome.Profiles.Profile.SubscribeAlertGroup']['meta_info']
_meta_table['CallHome.Profiles.Profile.ReportType']['meta_info'].parent =_meta_table['CallHome.Profiles.Profile']['meta_info']
_meta_table['CallHome.Profiles.Profile.Methods']['meta_info'].parent =_meta_table['CallHome.Profiles.Profile']['meta_info']
_meta_table['CallHome.Profiles.Profile.Addresses']['meta_info'].parent =_meta_table['CallHome.Profiles.Profile']['meta_info']
_meta_table['CallHome.Profiles.Profile.SubscribeAlertGroup']['meta_info'].parent =_meta_table['CallHome.Profiles.Profile']['meta_info']
_meta_table['CallHome.Profiles.Profile']['meta_info'].parent =_meta_table['CallHome.Profiles']['meta_info']
_meta_table['CallHome.AlertGroups.AlertGroup']['meta_info'].parent =_meta_table['CallHome.AlertGroups']['meta_info']
_meta_table['CallHome.DataPrivacies.DataPrivacy']['meta_info'].parent =_meta_table['CallHome.DataPrivacies']['meta_info']
_meta_table['CallHome.AlertGroupConfig.SnapshotCommands.SnapshotCommand']['meta_info'].parent =_meta_table['CallHome.AlertGroupConfig.SnapshotCommands']['meta_info']
_meta_table['CallHome.AlertGroupConfig.SnapshotCommands']['meta_info'].parent =_meta_table['CallHome.AlertGroupConfig']['meta_info']
_meta_table['CallHome.MailServers']['meta_info'].parent =_meta_table['CallHome']['meta_info']
_meta_table['CallHome.SyslogThrottling']['meta_info'].parent =_meta_table['CallHome']['meta_info']
_meta_table['CallHome.HttpProxy']['meta_info'].parent =_meta_table['CallHome']['meta_info']
_meta_table['CallHome.Profiles']['meta_info'].parent =_meta_table['CallHome']['meta_info']
_meta_table['CallHome.AlertGroups']['meta_info'].parent =_meta_table['CallHome']['meta_info']
_meta_table['CallHome.DataPrivacies']['meta_info'].parent =_meta_table['CallHome']['meta_info']
_meta_table['CallHome.AlertGroupConfig']['meta_info'].parent =_meta_table['CallHome']['meta_info']
_meta_table['CallHome.Authorization']['meta_info'].parent =_meta_table['CallHome']['meta_info']
