
'''
This is auto-generated file,
which includes metadata for module Cisco_IOS_XR_aaa_nacm_oper
'''

from ydk._core._dm_meta_info import _MetaInfoClassMember, _MetaInfoClass, _MetaInfoEnum
from ydk._core._dm_meta_info import ATTRIBUTE, REFERENCE_LIST, REFERENCE_LEAFLIST, REFERENCE_BITS, REFERENCE_UNION
from ydk._core._dm_meta_info import REFERENCE_CLASS, REFERENCE_IDENTITY_CLASS, REFERENCE_ENUM_CLASS, ANYXML_CLASS
from ydk._core._importer import _yang_ns

_meta_table = {
    'AaaNacm.Counters' : {
        'meta_info' : _MetaInfoClass('AaaNacm.Counters', REFERENCE_CLASS,
            '''AAA NACM summary''',
            False, 
            [
            _MetaInfoClassMember('denied-operations', ATTRIBUTE, 'int', 'int32',
                None, None,
                [('-2147483648', '2147483647')], [],
                '''                Denied Operations
                ''',
                'denied_operations',
                'Cisco-IOS-XR-aaa-nacm-oper', False, is_config=False),
            _MetaInfoClassMember('denied-data-writes', ATTRIBUTE, 'int', 'int32',
                None, None,
                [('-2147483648', '2147483647')], [],
                '''                Denied Data Writes
                ''',
                'denied_data_writes',
                'Cisco-IOS-XR-aaa-nacm-oper', False, is_config=False),
            _MetaInfoClassMember('denied-notifications', ATTRIBUTE, 'int', 'int32',
                None, None,
                [('-2147483648', '2147483647')], [],
                '''                Denied Notifications
                ''',
                'denied_notifications',
                'Cisco-IOS-XR-aaa-nacm-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-aaa-nacm-oper',
            'counters',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-aaa-nacm-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_aaa_nacm_oper',
            is_config=False,
        ),
    },
    'AaaNacm.Users.User.GroupName' : {
        'meta_info' : _MetaInfoClass('AaaNacm.Users.User.GroupName', REFERENCE_LIST,
            '''Group Name List''',
            False, 
            [
            _MetaInfoClassMember('name', ATTRIBUTE, 'str', 'string',
                None, None,
                [(0, 256)], [],
                '''                Name
                ''',
                'name',
                'Cisco-IOS-XR-aaa-nacm-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-aaa-nacm-oper',
            'group-name',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-aaa-nacm-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_aaa_nacm_oper',
            is_config=False,
        ),
    },
    'AaaNacm.Users.User' : {
        'meta_info' : _MetaInfoClass('AaaNacm.Users.User', REFERENCE_LIST,
            '''AAA NACM User detail''',
            False, 
            [
            _MetaInfoClassMember('user', ATTRIBUTE, 'str', 'xr:Cisco-ios-xr-string',
                None, None,
                [(1, 256)], [],
                '''                User
                ''',
                'user',
                'Cisco-IOS-XR-aaa-nacm-oper', True, is_config=False),
            _MetaInfoClassMember('user-name', ATTRIBUTE, 'str', 'string',
                None, None,
                [(0, 256)], [],
                '''                User Name
                ''',
                'user_name',
                'Cisco-IOS-XR-aaa-nacm-oper', False, is_config=False),
            _MetaInfoClassMember('group-name', REFERENCE_LIST, 'GroupName', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_aaa_nacm_oper', 'AaaNacm.Users.User.GroupName',
                [], [],
                '''                Group Name List
                ''',
                'group_name',
                'Cisco-IOS-XR-aaa-nacm-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-aaa-nacm-oper',
            'user',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-aaa-nacm-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_aaa_nacm_oper',
            is_config=False,
        ),
    },
    'AaaNacm.Users' : {
        'meta_info' : _MetaInfoClass('AaaNacm.Users', REFERENCE_CLASS,
            '''AAA NACM User summary''',
            False, 
            [
            _MetaInfoClassMember('user', REFERENCE_LIST, 'User', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_aaa_nacm_oper', 'AaaNacm.Users.User',
                [], [],
                '''                AAA NACM User detail
                ''',
                'user',
                'Cisco-IOS-XR-aaa-nacm-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-aaa-nacm-oper',
            'users',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-aaa-nacm-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_aaa_nacm_oper',
            is_config=False,
        ),
    },
    'AaaNacm.Summary' : {
        'meta_info' : _MetaInfoClass('AaaNacm.Summary', REFERENCE_CLASS,
            '''AAA NACM summary''',
            False, 
            [
            _MetaInfoClassMember('groups', ATTRIBUTE, 'int', 'int32',
                None, None,
                [('-2147483648', '2147483647')], [],
                '''                Groups
                ''',
                'groups',
                'Cisco-IOS-XR-aaa-nacm-oper', False, is_config=False),
            _MetaInfoClassMember('users', ATTRIBUTE, 'int', 'int32',
                None, None,
                [('-2147483648', '2147483647')], [],
                '''                Users
                ''',
                'users',
                'Cisco-IOS-XR-aaa-nacm-oper', False, is_config=False),
            _MetaInfoClassMember('rulelist', ATTRIBUTE, 'int', 'int32',
                None, None,
                [('-2147483648', '2147483647')], [],
                '''                Rulelist
                ''',
                'rulelist',
                'Cisco-IOS-XR-aaa-nacm-oper', False, is_config=False),
            _MetaInfoClassMember('rules', ATTRIBUTE, 'int', 'int32',
                None, None,
                [('-2147483648', '2147483647')], [],
                '''                Rules
                ''',
                'rules',
                'Cisco-IOS-XR-aaa-nacm-oper', False, is_config=False),
            _MetaInfoClassMember('read-default', ATTRIBUTE, 'str', 'string',
                None, None,
                [(0, 16)], [],
                '''                Read Default
                ''',
                'read_default',
                'Cisco-IOS-XR-aaa-nacm-oper', False, is_config=False),
            _MetaInfoClassMember('write-default', ATTRIBUTE, 'str', 'string',
                None, None,
                [(0, 16)], [],
                '''                Write Default
                ''',
                'write_default',
                'Cisco-IOS-XR-aaa-nacm-oper', False, is_config=False),
            _MetaInfoClassMember('exec-default', ATTRIBUTE, 'str', 'string',
                None, None,
                [(0, 16)], [],
                '''                Exec Default
                ''',
                'exec_default',
                'Cisco-IOS-XR-aaa-nacm-oper', False, is_config=False),
            _MetaInfoClassMember('enable-nacm', ATTRIBUTE, 'str', 'string',
                None, None,
                [(0, 16)], [],
                '''                Enable Nacm
                ''',
                'enable_nacm',
                'Cisco-IOS-XR-aaa-nacm-oper', False, is_config=False),
            _MetaInfoClassMember('enable-external-groups', ATTRIBUTE, 'str', 'string',
                None, None,
                [(0, 16)], [],
                '''                Enable External Groups
                ''',
                'enable_external_groups',
                'Cisco-IOS-XR-aaa-nacm-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-aaa-nacm-oper',
            'summary',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-aaa-nacm-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_aaa_nacm_oper',
            is_config=False,
        ),
    },
    'AaaNacm.Rules.Rule.RulelistRules.RulelistRule' : {
        'meta_info' : _MetaInfoClass('AaaNacm.Rules.Rule.RulelistRules.RulelistRule', REFERENCE_LIST,
            '''AAA NACM Rulelist detail''',
            False, 
            [
            _MetaInfoClassMember('rule', ATTRIBUTE, 'str', 'xr:Cisco-ios-xr-string',
                None, None,
                [(1, 256)], [],
                '''                Rule
                ''',
                'rule',
                'Cisco-IOS-XR-aaa-nacm-oper', True, is_config=False),
            _MetaInfoClassMember('rule-name', ATTRIBUTE, 'str', 'string',
                None, None,
                [(0, 512)], [],
                '''                Rule Name
                ''',
                'rule_name',
                'Cisco-IOS-XR-aaa-nacm-oper', False, is_config=False),
            _MetaInfoClassMember('rule-index', ATTRIBUTE, 'str', 'string',
                None, None,
                [(0, 16)], [],
                '''                Rule Index
                ''',
                'rule_index',
                'Cisco-IOS-XR-aaa-nacm-oper', False, is_config=False),
            _MetaInfoClassMember('rulelist-index', ATTRIBUTE, 'str', 'string',
                None, None,
                [(0, 16)], [],
                '''                Rulelist Index
                ''',
                'rulelist_index',
                'Cisco-IOS-XR-aaa-nacm-oper', False, is_config=False),
            _MetaInfoClassMember('module-name', ATTRIBUTE, 'str', 'string',
                None, None,
                [(0, 512)], [],
                '''                Module Name
                ''',
                'module_name',
                'Cisco-IOS-XR-aaa-nacm-oper', False, is_config=False),
            _MetaInfoClassMember('action', ATTRIBUTE, 'str', 'string',
                None, None,
                [(0, 256)], [],
                '''                Action
                ''',
                'action',
                'Cisco-IOS-XR-aaa-nacm-oper', False, is_config=False),
            _MetaInfoClassMember('rule-type', ATTRIBUTE, 'str', 'string',
                None, None,
                [(0, 256)], [],
                '''                Rule Type
                ''',
                'rule_type',
                'Cisco-IOS-XR-aaa-nacm-oper', False, is_config=False),
            _MetaInfoClassMember('comment', ATTRIBUTE, 'str', 'string',
                None, None,
                [(0, 256)], [],
                '''                Comment
                ''',
                'comment',
                'Cisco-IOS-XR-aaa-nacm-oper', False, is_config=False),
            _MetaInfoClassMember('access-operations', ATTRIBUTE, 'str', 'string',
                None, None,
                [(0, 256)], [],
                '''                Access Operations
                ''',
                'access_operations',
                'Cisco-IOS-XR-aaa-nacm-oper', False, is_config=False),
            _MetaInfoClassMember('rule-value', ATTRIBUTE, 'str', 'string',
                None, None,
                [(0, 512)], [],
                '''                Rule Value
                ''',
                'rule_value',
                'Cisco-IOS-XR-aaa-nacm-oper', False, is_config=False),
            _MetaInfoClassMember('hit-count', ATTRIBUTE, 'int', 'int32',
                None, None,
                [('-2147483648', '2147483647')], [],
                '''                Hit Count
                ''',
                'hit_count',
                'Cisco-IOS-XR-aaa-nacm-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-aaa-nacm-oper',
            'rulelist-rule',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-aaa-nacm-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_aaa_nacm_oper',
            is_config=False,
        ),
    },
    'AaaNacm.Rules.Rule.RulelistRules' : {
        'meta_info' : _MetaInfoClass('AaaNacm.Rules.Rule.RulelistRules', REFERENCE_CLASS,
            '''AAA NACM Rulelist detail''',
            False, 
            [
            _MetaInfoClassMember('rulelist-rule', REFERENCE_LIST, 'RulelistRule', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_aaa_nacm_oper', 'AaaNacm.Rules.Rule.RulelistRules.RulelistRule',
                [], [],
                '''                AAA NACM Rulelist detail
                ''',
                'rulelist_rule',
                'Cisco-IOS-XR-aaa-nacm-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-aaa-nacm-oper',
            'rulelist-rules',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-aaa-nacm-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_aaa_nacm_oper',
            is_config=False,
        ),
    },
    'AaaNacm.Rules.Rule' : {
        'meta_info' : _MetaInfoClass('AaaNacm.Rules.Rule', REFERENCE_LIST,
            '''AAA NACM Rulelist detail''',
            False, 
            [
            _MetaInfoClassMember('rulelist-rules', REFERENCE_CLASS, 'RulelistRules', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_aaa_nacm_oper', 'AaaNacm.Rules.Rule.RulelistRules',
                [], [],
                '''                AAA NACM Rulelist detail
                ''',
                'rulelist_rules',
                'Cisco-IOS-XR-aaa-nacm-oper', False, is_config=False),
            _MetaInfoClassMember('ordering-index', ATTRIBUTE, 'str', 'xr:Cisco-ios-xr-string',
                None, None,
                [(1, 256)], [],
                '''                Rulelist Ordering Index
                ''',
                'ordering_index',
                'Cisco-IOS-XR-aaa-nacm-oper', False, is_config=False),
            _MetaInfoClassMember('rulelist-name', ATTRIBUTE, 'str', 'xr:Cisco-ios-xr-string',
                None, None,
                [(1, 256)], [],
                '''                Rulelist Name
                ''',
                'rulelist_name',
                'Cisco-IOS-XR-aaa-nacm-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-aaa-nacm-oper',
            'rule',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-aaa-nacm-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_aaa_nacm_oper',
            is_config=False,
        ),
    },
    'AaaNacm.Rules' : {
        'meta_info' : _MetaInfoClass('AaaNacm.Rules', REFERENCE_CLASS,
            '''AAA NACM Rulelist summary''',
            False, 
            [
            _MetaInfoClassMember('rule', REFERENCE_LIST, 'Rule', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_aaa_nacm_oper', 'AaaNacm.Rules.Rule',
                [], [],
                '''                AAA NACM Rulelist detail
                ''',
                'rule',
                'Cisco-IOS-XR-aaa-nacm-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-aaa-nacm-oper',
            'rules',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-aaa-nacm-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_aaa_nacm_oper',
            is_config=False,
        ),
    },
    'AaaNacm.Groups.Group.UserName' : {
        'meta_info' : _MetaInfoClass('AaaNacm.Groups.Group.UserName', REFERENCE_LIST,
            '''Users Name List''',
            False, 
            [
            _MetaInfoClassMember('name', ATTRIBUTE, 'str', 'string',
                None, None,
                [(0, 256)], [],
                '''                Name
                ''',
                'name',
                'Cisco-IOS-XR-aaa-nacm-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-aaa-nacm-oper',
            'user-name',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-aaa-nacm-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_aaa_nacm_oper',
            is_config=False,
        ),
    },
    'AaaNacm.Groups.Group.RuleName' : {
        'meta_info' : _MetaInfoClass('AaaNacm.Groups.Group.RuleName', REFERENCE_LIST,
            '''Rules Name List''',
            False, 
            [
            _MetaInfoClassMember('name', ATTRIBUTE, 'str', 'string',
                None, None,
                [(0, 256)], [],
                '''                Name
                ''',
                'name',
                'Cisco-IOS-XR-aaa-nacm-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-aaa-nacm-oper',
            'rule-name',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-aaa-nacm-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_aaa_nacm_oper',
            is_config=False,
        ),
    },
    'AaaNacm.Groups.Group' : {
        'meta_info' : _MetaInfoClass('AaaNacm.Groups.Group', REFERENCE_LIST,
            '''AAA NACM Group detail''',
            False, 
            [
            _MetaInfoClassMember('group', ATTRIBUTE, 'str', 'xr:Cisco-ios-xr-string',
                None, None,
                [(1, 256)], [],
                '''                Group
                ''',
                'group',
                'Cisco-IOS-XR-aaa-nacm-oper', True, is_config=False),
            _MetaInfoClassMember('group-name', ATTRIBUTE, 'str', 'string',
                None, None,
                [(0, 256)], [],
                '''                Group Name
                ''',
                'group_name',
                'Cisco-IOS-XR-aaa-nacm-oper', False, is_config=False),
            _MetaInfoClassMember('user-name', REFERENCE_LIST, 'UserName', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_aaa_nacm_oper', 'AaaNacm.Groups.Group.UserName',
                [], [],
                '''                Users Name List
                ''',
                'user_name',
                'Cisco-IOS-XR-aaa-nacm-oper', False, is_config=False),
            _MetaInfoClassMember('rule-name', REFERENCE_LIST, 'RuleName', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_aaa_nacm_oper', 'AaaNacm.Groups.Group.RuleName',
                [], [],
                '''                Rules Name List
                ''',
                'rule_name',
                'Cisco-IOS-XR-aaa-nacm-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-aaa-nacm-oper',
            'group',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-aaa-nacm-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_aaa_nacm_oper',
            is_config=False,
        ),
    },
    'AaaNacm.Groups' : {
        'meta_info' : _MetaInfoClass('AaaNacm.Groups', REFERENCE_CLASS,
            '''AAA NACM Group summary''',
            False, 
            [
            _MetaInfoClassMember('group', REFERENCE_LIST, 'Group', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_aaa_nacm_oper', 'AaaNacm.Groups.Group',
                [], [],
                '''                AAA NACM Group detail
                ''',
                'group',
                'Cisco-IOS-XR-aaa-nacm-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-aaa-nacm-oper',
            'groups',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-aaa-nacm-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_aaa_nacm_oper',
            is_config=False,
        ),
    },
    'AaaNacm' : {
        'meta_info' : _MetaInfoClass('AaaNacm', REFERENCE_CLASS,
            '''AAA Nacm Information''',
            False, 
            [
            _MetaInfoClassMember('counters', REFERENCE_CLASS, 'Counters', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_aaa_nacm_oper', 'AaaNacm.Counters',
                [], [],
                '''                AAA NACM summary
                ''',
                'counters',
                'Cisco-IOS-XR-aaa-nacm-oper', False, is_config=False),
            _MetaInfoClassMember('users', REFERENCE_CLASS, 'Users', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_aaa_nacm_oper', 'AaaNacm.Users',
                [], [],
                '''                AAA NACM User summary
                ''',
                'users',
                'Cisco-IOS-XR-aaa-nacm-oper', False, is_config=False),
            _MetaInfoClassMember('summary', REFERENCE_CLASS, 'Summary', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_aaa_nacm_oper', 'AaaNacm.Summary',
                [], [],
                '''                AAA NACM summary
                ''',
                'summary',
                'Cisco-IOS-XR-aaa-nacm-oper', False, is_config=False),
            _MetaInfoClassMember('rules', REFERENCE_CLASS, 'Rules', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_aaa_nacm_oper', 'AaaNacm.Rules',
                [], [],
                '''                AAA NACM Rulelist summary
                ''',
                'rules',
                'Cisco-IOS-XR-aaa-nacm-oper', False, is_config=False),
            _MetaInfoClassMember('groups', REFERENCE_CLASS, 'Groups', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_aaa_nacm_oper', 'AaaNacm.Groups',
                [], [],
                '''                AAA NACM Group summary
                ''',
                'groups',
                'Cisco-IOS-XR-aaa-nacm-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-aaa-nacm-oper',
            'aaa-nacm',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-aaa-nacm-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_aaa_nacm_oper',
            is_config=False,
        ),
    },
}
_meta_table['AaaNacm.Users.User.GroupName']['meta_info'].parent =_meta_table['AaaNacm.Users.User']['meta_info']
_meta_table['AaaNacm.Users.User']['meta_info'].parent =_meta_table['AaaNacm.Users']['meta_info']
_meta_table['AaaNacm.Rules.Rule.RulelistRules.RulelistRule']['meta_info'].parent =_meta_table['AaaNacm.Rules.Rule.RulelistRules']['meta_info']
_meta_table['AaaNacm.Rules.Rule.RulelistRules']['meta_info'].parent =_meta_table['AaaNacm.Rules.Rule']['meta_info']
_meta_table['AaaNacm.Rules.Rule']['meta_info'].parent =_meta_table['AaaNacm.Rules']['meta_info']
_meta_table['AaaNacm.Groups.Group.UserName']['meta_info'].parent =_meta_table['AaaNacm.Groups.Group']['meta_info']
_meta_table['AaaNacm.Groups.Group.RuleName']['meta_info'].parent =_meta_table['AaaNacm.Groups.Group']['meta_info']
_meta_table['AaaNacm.Groups.Group']['meta_info'].parent =_meta_table['AaaNacm.Groups']['meta_info']
_meta_table['AaaNacm.Counters']['meta_info'].parent =_meta_table['AaaNacm']['meta_info']
_meta_table['AaaNacm.Users']['meta_info'].parent =_meta_table['AaaNacm']['meta_info']
_meta_table['AaaNacm.Summary']['meta_info'].parent =_meta_table['AaaNacm']['meta_info']
_meta_table['AaaNacm.Rules']['meta_info'].parent =_meta_table['AaaNacm']['meta_info']
_meta_table['AaaNacm.Groups']['meta_info'].parent =_meta_table['AaaNacm']['meta_info']
