
'''
This is auto-generated file,
which includes metadata for module Cisco_IOS_XR_spirit_install_instmgr_oper
'''

from ydk._core._dm_meta_info import _MetaInfoClassMember, _MetaInfoClass, _MetaInfoEnum
from ydk._core._dm_meta_info import ATTRIBUTE, REFERENCE_LIST, REFERENCE_LEAFLIST, REFERENCE_BITS, REFERENCE_UNION
from ydk._core._dm_meta_info import REFERENCE_CLASS, REFERENCE_IDENTITY_CLASS, REFERENCE_ENUM_CLASS, ANYXML_CLASS
from ydk._core._importer import _yang_ns

_meta_table = {
    'NodeRoleEt' : _MetaInfoEnum('NodeRoleEt',
        'ydk.models.cisco_ios_xr.Cisco_IOS_XR_spirit_install_instmgr_oper', 'NodeRoleEt',
        '''node role''',
        {
            'node-unknown':'node_unknown',
            'node-active':'node_active',
            'node-standby':'node_standby',
            'node-unusable':'node_unusable',
        }, 'Cisco-IOS-XR-spirit-install-instmgr-oper', _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-spirit-install-instmgr-oper']),
    'IssudirNodeStatusEt' : _MetaInfoEnum('IssudirNodeStatusEt',
        'ydk.models.cisco_ios_xr.Cisco_IOS_XR_spirit_install_instmgr_oper', 'IssudirNodeStatusEt',
        '''ISSU node status''',
        {
            'not-issu-ready':'not_issu_ready',
            'issu-ready':'issu_ready',
            'isus-go':'isus_go',
            'node-fail':'node_fail',
        }, 'Cisco-IOS-XR-spirit-install-instmgr-oper', _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-spirit-install-instmgr-oper']),
    'IssuNodeRoleEt' : _MetaInfoEnum('IssuNodeRoleEt',
        'ydk.models.cisco_ios_xr.Cisco_IOS_XR_spirit_install_instmgr_oper', 'IssuNodeRoleEt',
        '''ISSU role''',
        {
            'unknown-role':'unknown_role',
            'primary-role':'primary_role',
            'secondary-role':'secondary_role',
            'tertiary-role':'tertiary_role',
        }, 'Cisco-IOS-XR-spirit-install-instmgr-oper', _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-spirit-install-instmgr-oper']),
    'CardTypeEt' : _MetaInfoEnum('CardTypeEt',
        'ydk.models.cisco_ios_xr.Cisco_IOS_XR_spirit_install_instmgr_oper', 'CardTypeEt',
        '''card type''',
        {
            'card-rp':'card_rp',
            'card-drp':'card_drp',
            'card-lc':'card_lc',
            'card-sc':'card_sc',
            'card-sp':'card_sp',
            'card-other':'card_other',
        }, 'Cisco-IOS-XR-spirit-install-instmgr-oper', _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-spirit-install-instmgr-oper']),
    'IsdErrorEt' : _MetaInfoEnum('IsdErrorEt',
        'ydk.models.cisco_ios_xr.Cisco_IOS_XR_spirit_install_instmgr_oper', 'IsdErrorEt',
        '''isd error''',
        {
            'none':'none',
            'not-compatible':'not_compatible',
            'not-enough-resource':'not_enough_resource',
            'not-nsr-ready':'not_nsr_ready',
            'not-conn-sdrsm':'not_conn_sdrsm',
            'cmd-invalid':'cmd_invalid',
            'load-prep-fail':'load_prep_fail',
            'error-timeout':'error_timeout',
            'err-node-down':'err_node_down',
            'node-not-ready':'node_not_ready',
            'err-node-new':'err_node_new',
            'err-card-oir':'err_card_oir',
            'invalid-evt':'invalid_evt',
            'disconn-from-calv':'disconn_from_calv',
            'gsp-down':'gsp_down',
            'abort-by-ism':'abort_by_ism',
            'rpfo':'rpfo',
            'pkg-null':'pkg_null',
            'error-general':'error_general',
            'fsa-error':'fsa_error',
            'err-post-issu':'err_post_issu',
            'err-issu-dir-restart':'err_issu_dir_restart',
        }, 'Cisco-IOS-XR-spirit-install-instmgr-oper', _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-spirit-install-instmgr-oper']),
    'IsdIssuStatusEt' : _MetaInfoEnum('IsdIssuStatusEt',
        'ydk.models.cisco_ios_xr.Cisco_IOS_XR_spirit_install_instmgr_oper', 'IsdIssuStatusEt',
        '''isd status''',
        {
            'ok':'ok',
            'prep-done':'prep_done',
            'big-bang':'big_bang',
            'done':'done',
            'abort':'abort',
            'cmd-reject':'cmd_reject',
            'unknown':'unknown',
            'abort-cleanup':'abort_cleanup',
            'abort-cmd-reject':'abort_cmd_reject',
        }, 'Cisco-IOS-XR-spirit-install-instmgr-oper', _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-spirit-install-instmgr-oper']),
    'IsdStateEt' : _MetaInfoEnum('IsdStateEt',
        'ydk.models.cisco_ios_xr.Cisco_IOS_XR_spirit_install_instmgr_oper', 'IsdStateEt',
        '''isd state''',
        {
            'none':'none',
            'idle':'idle',
            'init':'init',
            'init-done':'init_done',
            'load-prep':'load_prep',
            'load-exec':'load_exec',
            'load-issu-go':'load_issu_go',
            'load-done':'load_done',
            'run-prep-isd':'run_prep_isd',
            'run-prep-ism':'run_prep_ism',
            'big-bang':'big_bang',
            'run-done':'run_done',
            'cleanup':'cleanup',
            'cleanup-done':'cleanup_done',
            'abort':'abort',
            'abort-done':'abort_done',
            'abort-cleanup':'abort_cleanup',
            'unknown-state':'unknown_state',
        }, 'Cisco-IOS-XR-spirit-install-instmgr-oper', _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-spirit-install-instmgr-oper']),
    'SoftwareInstall.Superseded.SupersededPackageInfo' : {
        'meta_info' : _MetaInfoClass('SoftwareInstall.Superseded.SupersededPackageInfo', REFERENCE_LIST,
            '''superseded package info''',
            False, 
            [
            _MetaInfoClassMember('error-message', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                ErrorMessage
                ''',
                'error_message',
                'Cisco-IOS-XR-spirit-install-instmgr-oper', False, is_config=False),
            _MetaInfoClassMember('location', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Location
                ''',
                'location',
                'Cisco-IOS-XR-spirit-install-instmgr-oper', False, is_config=False),
            _MetaInfoClassMember('node-type', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                NodeType
                ''',
                'node_type',
                'Cisco-IOS-XR-spirit-install-instmgr-oper', False, is_config=False),
            _MetaInfoClassMember('boot-partition-name', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                BootPartitionName
                ''',
                'boot_partition_name',
                'Cisco-IOS-XR-spirit-install-instmgr-oper', False, is_config=False),
            _MetaInfoClassMember('superseded-packages', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                SupersededPackages
                ''',
                'superseded_packages',
                'Cisco-IOS-XR-spirit-install-instmgr-oper', False, is_config=False),
            _MetaInfoClassMember('number-of-packages', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                NumberOfPackages
                ''',
                'number_of_packages',
                'Cisco-IOS-XR-spirit-install-instmgr-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-spirit-install-instmgr-oper',
            'superseded-package-info',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-spirit-install-instmgr-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_spirit_install_instmgr_oper',
            is_config=False,
        ),
    },
    'SoftwareInstall.Superseded' : {
        'meta_info' : _MetaInfoClass('SoftwareInstall.Superseded', REFERENCE_CLASS,
            '''Show superseded packages''',
            False, 
            [
            _MetaInfoClassMember('superseded-package-info', REFERENCE_LIST, 'SupersededPackageInfo', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_spirit_install_instmgr_oper', 'SoftwareInstall.Superseded.SupersededPackageInfo',
                [], [],
                '''                superseded package info
                ''',
                'superseded_package_info',
                'Cisco-IOS-XR-spirit-install-instmgr-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-spirit-install-instmgr-oper',
            'superseded',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-spirit-install-instmgr-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_spirit_install_instmgr_oper',
            is_config=False,
        ),
    },
    'SoftwareInstall.CommittedSummary.CommittedPackageInfo' : {
        'meta_info' : _MetaInfoClass('SoftwareInstall.CommittedSummary.CommittedPackageInfo', REFERENCE_LIST,
            '''committed package info''',
            False, 
            [
            _MetaInfoClassMember('error-message', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                ErrorMessage
                ''',
                'error_message',
                'Cisco-IOS-XR-spirit-install-instmgr-oper', False, is_config=False),
            _MetaInfoClassMember('location', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Location
                ''',
                'location',
                'Cisco-IOS-XR-spirit-install-instmgr-oper', False, is_config=False),
            _MetaInfoClassMember('node-type', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                NodeType
                ''',
                'node_type',
                'Cisco-IOS-XR-spirit-install-instmgr-oper', False, is_config=False),
            _MetaInfoClassMember('boot-partition-name', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                BootPartitionName
                ''',
                'boot_partition_name',
                'Cisco-IOS-XR-spirit-install-instmgr-oper', False, is_config=False),
            _MetaInfoClassMember('number-of-committed-packages', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                NumberOfCommittedPackages
                ''',
                'number_of_committed_packages',
                'Cisco-IOS-XR-spirit-install-instmgr-oper', False, is_config=False),
            _MetaInfoClassMember('committed-packages', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                CommittedPackages
                ''',
                'committed_packages',
                'Cisco-IOS-XR-spirit-install-instmgr-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-spirit-install-instmgr-oper',
            'committed-package-info',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-spirit-install-instmgr-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_spirit_install_instmgr_oper',
            is_config=False,
        ),
    },
    'SoftwareInstall.CommittedSummary' : {
        'meta_info' : _MetaInfoClass('SoftwareInstall.CommittedSummary', REFERENCE_CLASS,
            '''Show Committed packages installed''',
            False, 
            [
            _MetaInfoClassMember('committed-package-info', REFERENCE_LIST, 'CommittedPackageInfo', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_spirit_install_instmgr_oper', 'SoftwareInstall.CommittedSummary.CommittedPackageInfo',
                [], [],
                '''                committed package info
                ''',
                'committed_package_info',
                'Cisco-IOS-XR-spirit-install-instmgr-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-spirit-install-instmgr-oper',
            'committed-summary',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-spirit-install-instmgr-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_spirit_install_instmgr_oper',
            is_config=False,
        ),
    },
    'SoftwareInstall.ActiveSummary.ActivePackageInfo' : {
        'meta_info' : _MetaInfoClass('SoftwareInstall.ActiveSummary.ActivePackageInfo', REFERENCE_LIST,
            '''active package info''',
            False, 
            [
            _MetaInfoClassMember('error-message', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                ErrorMessage
                ''',
                'error_message',
                'Cisco-IOS-XR-spirit-install-instmgr-oper', False, is_config=False),
            _MetaInfoClassMember('location', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Location
                ''',
                'location',
                'Cisco-IOS-XR-spirit-install-instmgr-oper', False, is_config=False),
            _MetaInfoClassMember('node-type', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                NodeType
                ''',
                'node_type',
                'Cisco-IOS-XR-spirit-install-instmgr-oper', False, is_config=False),
            _MetaInfoClassMember('boot-partition-name', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                BootPartitionName
                ''',
                'boot_partition_name',
                'Cisco-IOS-XR-spirit-install-instmgr-oper', False, is_config=False),
            _MetaInfoClassMember('number-of-active-packages', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                NumberOfActivePackages
                ''',
                'number_of_active_packages',
                'Cisco-IOS-XR-spirit-install-instmgr-oper', False, is_config=False),
            _MetaInfoClassMember('active-packages', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                ActivePackages
                ''',
                'active_packages',
                'Cisco-IOS-XR-spirit-install-instmgr-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-spirit-install-instmgr-oper',
            'active-package-info',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-spirit-install-instmgr-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_spirit_install_instmgr_oper',
            is_config=False,
        ),
    },
    'SoftwareInstall.ActiveSummary' : {
        'meta_info' : _MetaInfoClass('SoftwareInstall.ActiveSummary', REFERENCE_CLASS,
            '''Show active packages installed''',
            False, 
            [
            _MetaInfoClassMember('active-package-info', REFERENCE_LIST, 'ActivePackageInfo', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_spirit_install_instmgr_oper', 'SoftwareInstall.ActiveSummary.ActivePackageInfo',
                [], [],
                '''                active package info
                ''',
                'active_package_info',
                'Cisco-IOS-XR-spirit-install-instmgr-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-spirit-install-instmgr-oper',
            'active-summary',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-spirit-install-instmgr-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_spirit_install_instmgr_oper',
            is_config=False,
        ),
    },
    'SoftwareInstall.InactiveSummary' : {
        'meta_info' : _MetaInfoClass('SoftwareInstall.InactiveSummary', REFERENCE_CLASS,
            '''Show XR inactive packages''',
            False, 
            [
            _MetaInfoClassMember('log', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                log
                ''',
                'log',
                'Cisco-IOS-XR-spirit-install-instmgr-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-spirit-install-instmgr-oper',
            'inactive-summary',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-spirit-install-instmgr-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_spirit_install_instmgr_oper',
            is_config=False,
        ),
    },
    'SoftwareInstall.Prepare.Rpm' : {
        'meta_info' : _MetaInfoClass('SoftwareInstall.Prepare.Rpm', REFERENCE_LIST,
            '''rpm''',
            False, 
            [
            _MetaInfoClassMember('package', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                package
                ''',
                'package',
                'Cisco-IOS-XR-spirit-install-instmgr-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-spirit-install-instmgr-oper',
            'rpm',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-spirit-install-instmgr-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_spirit_install_instmgr_oper',
            is_config=False,
        ),
    },
    'SoftwareInstall.Prepare.Package' : {
        'meta_info' : _MetaInfoClass('SoftwareInstall.Prepare.Package', REFERENCE_LIST,
            '''package''',
            False, 
            [
            _MetaInfoClassMember('package', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                package
                ''',
                'package',
                'Cisco-IOS-XR-spirit-install-instmgr-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-spirit-install-instmgr-oper',
            'package',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-spirit-install-instmgr-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_spirit_install_instmgr_oper',
            is_config=False,
        ),
    },
    'SoftwareInstall.Prepare' : {
        'meta_info' : _MetaInfoClass('SoftwareInstall.Prepare', REFERENCE_CLASS,
            '''Show prepared packages ready for activation''',
            False, 
            [
            _MetaInfoClassMember('no-prepare-done', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                NoPrepareDone
                ''',
                'no_prepare_done',
                'Cisco-IOS-XR-spirit-install-instmgr-oper', False, is_config=False),
            _MetaInfoClassMember('prepared-boot-image', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                PreparedBootImage
                ''',
                'prepared_boot_image',
                'Cisco-IOS-XR-spirit-install-instmgr-oper', False, is_config=False),
            _MetaInfoClassMember('prepared-boot-partition', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                PreparedBootPartition
                ''',
                'prepared_boot_partition',
                'Cisco-IOS-XR-spirit-install-instmgr-oper', False, is_config=False),
            _MetaInfoClassMember('restart-type', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                RestartType
                ''',
                'restart_type',
                'Cisco-IOS-XR-spirit-install-instmgr-oper', False, is_config=False),
            _MetaInfoClassMember('activate-message', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                ActivateMessage
                ''',
                'activate_message',
                'Cisco-IOS-XR-spirit-install-instmgr-oper', False, is_config=False),
            _MetaInfoClassMember('prepare-clean-message', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                PrepareCleanMessage
                ''',
                'prepare_clean_message',
                'Cisco-IOS-XR-spirit-install-instmgr-oper', False, is_config=False),
            _MetaInfoClassMember('error-message', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                ErrorMessage
                ''',
                'error_message',
                'Cisco-IOS-XR-spirit-install-instmgr-oper', False, is_config=False),
            _MetaInfoClassMember('rpm', REFERENCE_LIST, 'Rpm', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_spirit_install_instmgr_oper', 'SoftwareInstall.Prepare.Rpm',
                [], [],
                '''                rpm
                ''',
                'rpm',
                'Cisco-IOS-XR-spirit-install-instmgr-oper', False, is_config=False),
            _MetaInfoClassMember('package', REFERENCE_LIST, 'Package', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_spirit_install_instmgr_oper', 'SoftwareInstall.Prepare.Package',
                [], [],
                '''                package
                ''',
                'package',
                'Cisco-IOS-XR-spirit-install-instmgr-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-spirit-install-instmgr-oper',
            'prepare',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-spirit-install-instmgr-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_spirit_install_instmgr_oper',
            is_config=False,
        ),
    },
    'SoftwareInstall.Active.ActivePackageInfo' : {
        'meta_info' : _MetaInfoClass('SoftwareInstall.Active.ActivePackageInfo', REFERENCE_LIST,
            '''active package info''',
            False, 
            [
            _MetaInfoClassMember('error-message', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                ErrorMessage
                ''',
                'error_message',
                'Cisco-IOS-XR-spirit-install-instmgr-oper', False, is_config=False),
            _MetaInfoClassMember('location', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Location
                ''',
                'location',
                'Cisco-IOS-XR-spirit-install-instmgr-oper', False, is_config=False),
            _MetaInfoClassMember('node-type', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                NodeType
                ''',
                'node_type',
                'Cisco-IOS-XR-spirit-install-instmgr-oper', False, is_config=False),
            _MetaInfoClassMember('boot-partition-name', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                BootPartitionName
                ''',
                'boot_partition_name',
                'Cisco-IOS-XR-spirit-install-instmgr-oper', False, is_config=False),
            _MetaInfoClassMember('number-of-active-packages', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                NumberOfActivePackages
                ''',
                'number_of_active_packages',
                'Cisco-IOS-XR-spirit-install-instmgr-oper', False, is_config=False),
            _MetaInfoClassMember('active-packages', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                ActivePackages
                ''',
                'active_packages',
                'Cisco-IOS-XR-spirit-install-instmgr-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-spirit-install-instmgr-oper',
            'active-package-info',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-spirit-install-instmgr-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_spirit_install_instmgr_oper',
            is_config=False,
        ),
    },
    'SoftwareInstall.Active' : {
        'meta_info' : _MetaInfoClass('SoftwareInstall.Active', REFERENCE_CLASS,
            '''Show active packages installed''',
            False, 
            [
            _MetaInfoClassMember('active-package-info', REFERENCE_LIST, 'ActivePackageInfo', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_spirit_install_instmgr_oper', 'SoftwareInstall.Active.ActivePackageInfo',
                [], [],
                '''                active package info
                ''',
                'active_package_info',
                'Cisco-IOS-XR-spirit-install-instmgr-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-spirit-install-instmgr-oper',
            'active',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-spirit-install-instmgr-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_spirit_install_instmgr_oper',
            is_config=False,
        ),
    },
    'SoftwareInstall.Version.Package' : {
        'meta_info' : _MetaInfoClass('SoftwareInstall.Version.Package', REFERENCE_LIST,
            '''package''',
            False, 
            [
            _MetaInfoClassMember('name', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Name
                ''',
                'name',
                'Cisco-IOS-XR-spirit-install-instmgr-oper', False, is_config=False),
            _MetaInfoClassMember('version', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Running version
                ''',
                'version',
                'Cisco-IOS-XR-spirit-install-instmgr-oper', False, is_config=False),
            _MetaInfoClassMember('built-by', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                User built by
                ''',
                'built_by',
                'Cisco-IOS-XR-spirit-install-instmgr-oper', False, is_config=False),
            _MetaInfoClassMember('built-on', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Time built
                ''',
                'built_on',
                'Cisco-IOS-XR-spirit-install-instmgr-oper', False, is_config=False),
            _MetaInfoClassMember('build-host', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Build host
                ''',
                'build_host',
                'Cisco-IOS-XR-spirit-install-instmgr-oper', False, is_config=False),
            _MetaInfoClassMember('workspace', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Workspace built in
                ''',
                'workspace',
                'Cisco-IOS-XR-spirit-install-instmgr-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-spirit-install-instmgr-oper',
            'package',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-spirit-install-instmgr-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_spirit_install_instmgr_oper',
            is_config=False,
        ),
    },
    'SoftwareInstall.Version' : {
        'meta_info' : _MetaInfoClass('SoftwareInstall.Version', REFERENCE_CLASS,
            '''Show install version''',
            False, 
            [
            _MetaInfoClassMember('location', ATTRIBUTE, 'str', 'Install-bag-optional-string',
                None, None,
                [], [],
                '''                Path where all cisco packages are installed
                ''',
                'location',
                'Cisco-IOS-XR-spirit-install-instmgr-oper', False, is_config=False),
            _MetaInfoClassMember('label', ATTRIBUTE, 'str', 'Install-bag-optional-string',
                None, None,
                [], [],
                '''                label name
                ''',
                'label',
                'Cisco-IOS-XR-spirit-install-instmgr-oper', False, is_config=False),
            _MetaInfoClassMember('copyright-info', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                copyright info
                ''',
                'copyright_info',
                'Cisco-IOS-XR-spirit-install-instmgr-oper', False, is_config=False),
            _MetaInfoClassMember('hardware-info', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                hardware info of the router
                ''',
                'hardware_info',
                'Cisco-IOS-XR-spirit-install-instmgr-oper', False, is_config=False),
            _MetaInfoClassMember('system-uptime', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                duration since when system is up
                ''',
                'system_uptime',
                'Cisco-IOS-XR-spirit-install-instmgr-oper', False, is_config=False),
            _MetaInfoClassMember('img-info', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                this tag is deprecated
                ''',
                'img_info',
                'Cisco-IOS-XR-spirit-install-instmgr-oper', False, is_config=False),
            _MetaInfoClassMember('package', REFERENCE_LIST, 'Package', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_spirit_install_instmgr_oper', 'SoftwareInstall.Version.Package',
                [], [],
                '''                package
                ''',
                'package',
                'Cisco-IOS-XR-spirit-install-instmgr-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-spirit-install-instmgr-oper',
            'version',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-spirit-install-instmgr-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_spirit_install_instmgr_oper',
            is_config=False,
        ),
    },
    'SoftwareInstall.Inactive' : {
        'meta_info' : _MetaInfoClass('SoftwareInstall.Inactive', REFERENCE_CLASS,
            '''Show XR inactive packages''',
            False, 
            [
            _MetaInfoClassMember('log', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                log
                ''',
                'log',
                'Cisco-IOS-XR-spirit-install-instmgr-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-spirit-install-instmgr-oper',
            'inactive',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-spirit-install-instmgr-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_spirit_install_instmgr_oper',
            is_config=False,
        ),
    },
    'SoftwareInstall.Request' : {
        'meta_info' : _MetaInfoClass('SoftwareInstall.Request', REFERENCE_CLASS,
            '''Show current request''',
            False, 
            [
            _MetaInfoClassMember('curr-inst-oper', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                CurrInstOper
                ''',
                'curr_inst_oper',
                'Cisco-IOS-XR-spirit-install-instmgr-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-spirit-install-instmgr-oper',
            'request',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-spirit-install-instmgr-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_spirit_install_instmgr_oper',
            is_config=False,
        ),
    },
    'SoftwareInstall.SupersededSummary' : {
        'meta_info' : _MetaInfoClass('SoftwareInstall.SupersededSummary', REFERENCE_CLASS,
            '''Show superseded packages''',
            False, 
            [
            _MetaInfoClassMember('log', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                log
                ''',
                'log',
                'Cisco-IOS-XR-spirit-install-instmgr-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-spirit-install-instmgr-oper',
            'superseded-summary',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-spirit-install-instmgr-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_spirit_install_instmgr_oper',
            is_config=False,
        ),
    },
    'SoftwareInstall.Issu.Stage' : {
        'meta_info' : _MetaInfoClass('SoftwareInstall.Issu.Stage', REFERENCE_CLASS,
            '''Show XR install issu stage''',
            False, 
            [
            _MetaInfoClassMember('state', REFERENCE_ENUM_CLASS, 'IsdStateEt', 'Isd-state-et',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_spirit_install_instmgr_oper', 'IsdStateEt',
                [], [],
                '''                State
                ''',
                'state',
                'Cisco-IOS-XR-spirit-install-instmgr-oper', False, is_config=False),
            _MetaInfoClassMember('issu-node-cnt', ATTRIBUTE, 'int', 'int32',
                None, None,
                [('-2147483648', '2147483647')], [],
                '''                ISSU Node Count
                ''',
                'issu_node_cnt',
                'Cisco-IOS-XR-spirit-install-instmgr-oper', False, is_config=False),
            _MetaInfoClassMember('issu-ready-node-cnt', ATTRIBUTE, 'int', 'int32',
                None, None,
                [('-2147483648', '2147483647')], [],
                '''                ISSU Ready Node Count
                ''',
                'issu_ready_node_cnt',
                'Cisco-IOS-XR-spirit-install-instmgr-oper', False, is_config=False),
            _MetaInfoClassMember('percentage', ATTRIBUTE, 'int', 'int32',
                None, None,
                [('-2147483648', '2147483647')], [],
                '''                Percentage
                ''',
                'percentage',
                'Cisco-IOS-XR-spirit-install-instmgr-oper', False, is_config=False),
            _MetaInfoClassMember('issu-status', REFERENCE_ENUM_CLASS, 'IsdIssuStatusEt', 'Isd-issu-status-et',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_spirit_install_instmgr_oper', 'IsdIssuStatusEt',
                [], [],
                '''                Abort Status
                ''',
                'issu_status',
                'Cisco-IOS-XR-spirit-install-instmgr-oper', False, is_config=False),
            _MetaInfoClassMember('issu-error', REFERENCE_ENUM_CLASS, 'IsdErrorEt', 'Isd-error-et',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_spirit_install_instmgr_oper', 'IsdErrorEt',
                [], [],
                '''                ISSU Error
                ''',
                'issu_error',
                'Cisco-IOS-XR-spirit-install-instmgr-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-spirit-install-instmgr-oper',
            'stage',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-spirit-install-instmgr-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_spirit_install_instmgr_oper',
            is_config=False,
        ),
    },
    'SoftwareInstall.Issu.Inventory.Invinfo' : {
        'meta_info' : _MetaInfoClass('SoftwareInstall.Issu.Inventory.Invinfo', REFERENCE_LIST,
            '''invinfo''',
            False, 
            [
            _MetaInfoClassMember('node-id', ATTRIBUTE, 'int', 'int32',
                None, None,
                [('-2147483648', '2147483647')], [],
                '''                Node ID
                ''',
                'node_id',
                'Cisco-IOS-XR-spirit-install-instmgr-oper', False, is_config=False),
            _MetaInfoClassMember('node-type', REFERENCE_ENUM_CLASS, 'CardTypeEt', 'Card-type-et',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_spirit_install_instmgr_oper', 'CardTypeEt',
                [], [],
                '''                Node Type
                ''',
                'node_type',
                'Cisco-IOS-XR-spirit-install-instmgr-oper', False, is_config=False),
            _MetaInfoClassMember('issu-node-role', REFERENCE_ENUM_CLASS, 'IssuNodeRoleEt', 'Issu-node-role-et',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_spirit_install_instmgr_oper', 'IssuNodeRoleEt',
                [], [],
                '''                ISSU Node Role
                ''',
                'issu_node_role',
                'Cisco-IOS-XR-spirit-install-instmgr-oper', False, is_config=False),
            _MetaInfoClassMember('node-state', REFERENCE_ENUM_CLASS, 'IssudirNodeStatusEt', 'Issudir-node-status-et',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_spirit_install_instmgr_oper', 'IssudirNodeStatusEt',
                [], [],
                '''                Node State
                ''',
                'node_state',
                'Cisco-IOS-XR-spirit-install-instmgr-oper', False, is_config=False),
            _MetaInfoClassMember('node-role', REFERENCE_ENUM_CLASS, 'NodeRoleEt', 'Node-role-et',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_spirit_install_instmgr_oper', 'NodeRoleEt',
                [], [],
                '''                Node role
                ''',
                'node_role',
                'Cisco-IOS-XR-spirit-install-instmgr-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-spirit-install-instmgr-oper',
            'invinfo',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-spirit-install-instmgr-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_spirit_install_instmgr_oper',
            is_config=False,
        ),
    },
    'SoftwareInstall.Issu.Inventory' : {
        'meta_info' : _MetaInfoClass('SoftwareInstall.Issu.Inventory', REFERENCE_CLASS,
            '''Show XR install issu inventory''',
            False, 
            [
            _MetaInfoClassMember('invinfo', REFERENCE_LIST, 'Invinfo', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_spirit_install_instmgr_oper', 'SoftwareInstall.Issu.Inventory.Invinfo',
                [], [],
                '''                invinfo
                ''',
                'invinfo',
                'Cisco-IOS-XR-spirit-install-instmgr-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-spirit-install-instmgr-oper',
            'inventory',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-spirit-install-instmgr-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_spirit_install_instmgr_oper',
            is_config=False,
        ),
    },
    'SoftwareInstall.Issu' : {
        'meta_info' : _MetaInfoClass('SoftwareInstall.Issu', REFERENCE_CLASS,
            '''ISSU operation''',
            False, 
            [
            _MetaInfoClassMember('stage', REFERENCE_CLASS, 'Stage', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_spirit_install_instmgr_oper', 'SoftwareInstall.Issu.Stage',
                [], [],
                '''                Show XR install issu stage
                ''',
                'stage',
                'Cisco-IOS-XR-spirit-install-instmgr-oper', False, is_config=False),
            _MetaInfoClassMember('inventory', REFERENCE_CLASS, 'Inventory', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_spirit_install_instmgr_oper', 'SoftwareInstall.Issu.Inventory',
                [], [],
                '''                Show XR install issu inventory
                ''',
                'inventory',
                'Cisco-IOS-XR-spirit-install-instmgr-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-spirit-install-instmgr-oper',
            'issu',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-spirit-install-instmgr-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_spirit_install_instmgr_oper',
            is_config=False,
        ),
    },
    'SoftwareInstall.Committed.CommittedPackageInfo' : {
        'meta_info' : _MetaInfoClass('SoftwareInstall.Committed.CommittedPackageInfo', REFERENCE_LIST,
            '''committed package info''',
            False, 
            [
            _MetaInfoClassMember('error-message', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                ErrorMessage
                ''',
                'error_message',
                'Cisco-IOS-XR-spirit-install-instmgr-oper', False, is_config=False),
            _MetaInfoClassMember('location', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Location
                ''',
                'location',
                'Cisco-IOS-XR-spirit-install-instmgr-oper', False, is_config=False),
            _MetaInfoClassMember('node-type', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                NodeType
                ''',
                'node_type',
                'Cisco-IOS-XR-spirit-install-instmgr-oper', False, is_config=False),
            _MetaInfoClassMember('boot-partition-name', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                BootPartitionName
                ''',
                'boot_partition_name',
                'Cisco-IOS-XR-spirit-install-instmgr-oper', False, is_config=False),
            _MetaInfoClassMember('number-of-committed-packages', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                NumberOfCommittedPackages
                ''',
                'number_of_committed_packages',
                'Cisco-IOS-XR-spirit-install-instmgr-oper', False, is_config=False),
            _MetaInfoClassMember('committed-packages', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                CommittedPackages
                ''',
                'committed_packages',
                'Cisco-IOS-XR-spirit-install-instmgr-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-spirit-install-instmgr-oper',
            'committed-package-info',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-spirit-install-instmgr-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_spirit_install_instmgr_oper',
            is_config=False,
        ),
    },
    'SoftwareInstall.Committed' : {
        'meta_info' : _MetaInfoClass('SoftwareInstall.Committed', REFERENCE_CLASS,
            '''Show Committed packages installed''',
            False, 
            [
            _MetaInfoClassMember('committed-package-info', REFERENCE_LIST, 'CommittedPackageInfo', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_spirit_install_instmgr_oper', 'SoftwareInstall.Committed.CommittedPackageInfo',
                [], [],
                '''                committed package info
                ''',
                'committed_package_info',
                'Cisco-IOS-XR-spirit-install-instmgr-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-spirit-install-instmgr-oper',
            'committed',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-spirit-install-instmgr-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_spirit_install_instmgr_oper',
            is_config=False,
        ),
    },
    'SoftwareInstall.AllOperationsLog.ReverseDetail' : {
        'meta_info' : _MetaInfoClass('SoftwareInstall.AllOperationsLog.ReverseDetail', REFERENCE_CLASS,
            '''Show detailed log file for all operations -
reverse''',
            False, 
            [
            _MetaInfoClassMember('log', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                log
                ''',
                'log',
                'Cisco-IOS-XR-spirit-install-instmgr-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-spirit-install-instmgr-oper',
            'reverse-detail',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-spirit-install-instmgr-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_spirit_install_instmgr_oper',
            is_config=False,
        ),
    },
    'SoftwareInstall.AllOperationsLog.Reverse' : {
        'meta_info' : _MetaInfoClass('SoftwareInstall.AllOperationsLog.Reverse', REFERENCE_CLASS,
            '''Show log file for all operations - reverse''',
            False, 
            [
            _MetaInfoClassMember('log', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                log
                ''',
                'log',
                'Cisco-IOS-XR-spirit-install-instmgr-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-spirit-install-instmgr-oper',
            'reverse',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-spirit-install-instmgr-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_spirit_install_instmgr_oper',
            is_config=False,
        ),
    },
    'SoftwareInstall.AllOperationsLog.Summary' : {
        'meta_info' : _MetaInfoClass('SoftwareInstall.AllOperationsLog.Summary', REFERENCE_CLASS,
            '''Show summary log file for all operations''',
            False, 
            [
            _MetaInfoClassMember('log', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                log
                ''',
                'log',
                'Cisco-IOS-XR-spirit-install-instmgr-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-spirit-install-instmgr-oper',
            'summary',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-spirit-install-instmgr-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_spirit_install_instmgr_oper',
            is_config=False,
        ),
    },
    'SoftwareInstall.AllOperationsLog.Detail' : {
        'meta_info' : _MetaInfoClass('SoftwareInstall.AllOperationsLog.Detail', REFERENCE_CLASS,
            '''Show detailed log file for all operations''',
            False, 
            [
            _MetaInfoClassMember('log', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                log
                ''',
                'log',
                'Cisco-IOS-XR-spirit-install-instmgr-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-spirit-install-instmgr-oper',
            'detail',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-spirit-install-instmgr-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_spirit_install_instmgr_oper',
            is_config=False,
        ),
    },
    'SoftwareInstall.AllOperationsLog' : {
        'meta_info' : _MetaInfoClass('SoftwareInstall.AllOperationsLog', REFERENCE_CLASS,
            '''Show log file for all operations''',
            False, 
            [
            _MetaInfoClassMember('reverse-detail', REFERENCE_CLASS, 'ReverseDetail', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_spirit_install_instmgr_oper', 'SoftwareInstall.AllOperationsLog.ReverseDetail',
                [], [],
                '''                Show detailed log file for all operations -
                reverse
                ''',
                'reverse_detail',
                'Cisco-IOS-XR-spirit-install-instmgr-oper', False, is_config=False),
            _MetaInfoClassMember('reverse', REFERENCE_CLASS, 'Reverse', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_spirit_install_instmgr_oper', 'SoftwareInstall.AllOperationsLog.Reverse',
                [], [],
                '''                Show log file for all operations - reverse
                ''',
                'reverse',
                'Cisco-IOS-XR-spirit-install-instmgr-oper', False, is_config=False),
            _MetaInfoClassMember('summary', REFERENCE_CLASS, 'Summary', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_spirit_install_instmgr_oper', 'SoftwareInstall.AllOperationsLog.Summary',
                [], [],
                '''                Show summary log file for all operations
                ''',
                'summary',
                'Cisco-IOS-XR-spirit-install-instmgr-oper', False, is_config=False),
            _MetaInfoClassMember('detail', REFERENCE_CLASS, 'Detail', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_spirit_install_instmgr_oper', 'SoftwareInstall.AllOperationsLog.Detail',
                [], [],
                '''                Show detailed log file for all operations
                ''',
                'detail',
                'Cisco-IOS-XR-spirit-install-instmgr-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-spirit-install-instmgr-oper',
            'all-operations-log',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-spirit-install-instmgr-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_spirit_install_instmgr_oper',
            is_config=False,
        ),
    },
    'SoftwareInstall.Packages.Package.Verbose' : {
        'meta_info' : _MetaInfoClass('SoftwareInstall.Packages.Package.Verbose', REFERENCE_CLASS,
            '''Show the verbose info for a installed package''',
            False, 
            [
            _MetaInfoClassMember('log', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                log
                ''',
                'log',
                'Cisco-IOS-XR-spirit-install-instmgr-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-spirit-install-instmgr-oper',
            'verbose',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-spirit-install-instmgr-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_spirit_install_instmgr_oper',
            is_config=False,
        ),
    },
    'SoftwareInstall.Packages.Package.Brief' : {
        'meta_info' : _MetaInfoClass('SoftwareInstall.Packages.Package.Brief', REFERENCE_CLASS,
            '''Show the info for a installed package''',
            False, 
            [
            _MetaInfoClassMember('log', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                log
                ''',
                'log',
                'Cisco-IOS-XR-spirit-install-instmgr-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-spirit-install-instmgr-oper',
            'brief',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-spirit-install-instmgr-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_spirit_install_instmgr_oper',
            is_config=False,
        ),
    },
    'SoftwareInstall.Packages.Package.Detail' : {
        'meta_info' : _MetaInfoClass('SoftwareInstall.Packages.Package.Detail', REFERENCE_CLASS,
            '''Show the deatil info for a installed package''',
            False, 
            [
            _MetaInfoClassMember('log', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                log
                ''',
                'log',
                'Cisco-IOS-XR-spirit-install-instmgr-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-spirit-install-instmgr-oper',
            'detail',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-spirit-install-instmgr-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_spirit_install_instmgr_oper',
            is_config=False,
        ),
    },
    'SoftwareInstall.Packages.Package' : {
        'meta_info' : _MetaInfoClass('SoftwareInstall.Packages.Package', REFERENCE_LIST,
            '''Show the info for a installed package''',
            False, 
            [
            _MetaInfoClassMember('package-name', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Package name
                ''',
                'package_name',
                'Cisco-IOS-XR-spirit-install-instmgr-oper', True, is_config=False),
            _MetaInfoClassMember('verbose', REFERENCE_CLASS, 'Verbose', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_spirit_install_instmgr_oper', 'SoftwareInstall.Packages.Package.Verbose',
                [], [],
                '''                Show the verbose info for a installed package
                ''',
                'verbose',
                'Cisco-IOS-XR-spirit-install-instmgr-oper', False, is_config=False),
            _MetaInfoClassMember('brief', REFERENCE_CLASS, 'Brief', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_spirit_install_instmgr_oper', 'SoftwareInstall.Packages.Package.Brief',
                [], [],
                '''                Show the info for a installed package
                ''',
                'brief',
                'Cisco-IOS-XR-spirit-install-instmgr-oper', False, is_config=False),
            _MetaInfoClassMember('detail', REFERENCE_CLASS, 'Detail', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_spirit_install_instmgr_oper', 'SoftwareInstall.Packages.Package.Detail',
                [], [],
                '''                Show the deatil info for a installed package
                ''',
                'detail',
                'Cisco-IOS-XR-spirit-install-instmgr-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-spirit-install-instmgr-oper',
            'package',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-spirit-install-instmgr-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_spirit_install_instmgr_oper',
            is_config=False,
        ),
    },
    'SoftwareInstall.Packages' : {
        'meta_info' : _MetaInfoClass('SoftwareInstall.Packages', REFERENCE_CLASS,
            '''Show the list of installed packages''',
            False, 
            [
            _MetaInfoClassMember('package', REFERENCE_LIST, 'Package', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_spirit_install_instmgr_oper', 'SoftwareInstall.Packages.Package',
                [], [],
                '''                Show the info for a installed package
                ''',
                'package',
                'Cisco-IOS-XR-spirit-install-instmgr-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-spirit-install-instmgr-oper',
            'packages',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-spirit-install-instmgr-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_spirit_install_instmgr_oper',
            is_config=False,
        ),
    },
    'SoftwareInstall.OperationLogs.OperationLog.Summary' : {
        'meta_info' : _MetaInfoClass('SoftwareInstall.OperationLogs.OperationLog.Summary', REFERENCE_CLASS,
            '''Show summary log file for the specified
install ID''',
            False, 
            [
            _MetaInfoClassMember('log', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                log
                ''',
                'log',
                'Cisco-IOS-XR-spirit-install-instmgr-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-spirit-install-instmgr-oper',
            'summary',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-spirit-install-instmgr-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_spirit_install_instmgr_oper',
            is_config=False,
        ),
    },
    'SoftwareInstall.OperationLogs.OperationLog.Detail' : {
        'meta_info' : _MetaInfoClass('SoftwareInstall.OperationLogs.OperationLog.Detail', REFERENCE_CLASS,
            '''Show detailed log file for the specified
install ID''',
            False, 
            [
            _MetaInfoClassMember('log', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                log
                ''',
                'log',
                'Cisco-IOS-XR-spirit-install-instmgr-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-spirit-install-instmgr-oper',
            'detail',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-spirit-install-instmgr-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_spirit_install_instmgr_oper',
            is_config=False,
        ),
    },
    'SoftwareInstall.OperationLogs.OperationLog' : {
        'meta_info' : _MetaInfoClass('SoftwareInstall.OperationLogs.OperationLog', REFERENCE_LIST,
            '''Show log file for the specified install ID''',
            False, 
            [
            _MetaInfoClassMember('log-id', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                Log ID number
                ''',
                'log_id',
                'Cisco-IOS-XR-spirit-install-instmgr-oper', True, is_config=False),
            _MetaInfoClassMember('summary', REFERENCE_CLASS, 'Summary', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_spirit_install_instmgr_oper', 'SoftwareInstall.OperationLogs.OperationLog.Summary',
                [], [],
                '''                Show summary log file for the specified
                install ID
                ''',
                'summary',
                'Cisco-IOS-XR-spirit-install-instmgr-oper', False, is_config=False),
            _MetaInfoClassMember('detail', REFERENCE_CLASS, 'Detail', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_spirit_install_instmgr_oper', 'SoftwareInstall.OperationLogs.OperationLog.Detail',
                [], [],
                '''                Show detailed log file for the specified
                install ID
                ''',
                'detail',
                'Cisco-IOS-XR-spirit-install-instmgr-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-spirit-install-instmgr-oper',
            'operation-log',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-spirit-install-instmgr-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_spirit_install_instmgr_oper',
            is_config=False,
        ),
    },
    'SoftwareInstall.OperationLogs' : {
        'meta_info' : _MetaInfoClass('SoftwareInstall.OperationLogs', REFERENCE_CLASS,
            '''Show log file''',
            False, 
            [
            _MetaInfoClassMember('operation-log', REFERENCE_LIST, 'OperationLog', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_spirit_install_instmgr_oper', 'SoftwareInstall.OperationLogs.OperationLog',
                [], [],
                '''                Show log file for the specified install ID
                ''',
                'operation_log',
                'Cisco-IOS-XR-spirit-install-instmgr-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-spirit-install-instmgr-oper',
            'operation-logs',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-spirit-install-instmgr-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_spirit_install_instmgr_oper',
            is_config=False,
        ),
    },
    'SoftwareInstall.Repository.Xr' : {
        'meta_info' : _MetaInfoClass('SoftwareInstall.Repository.Xr', REFERENCE_CLASS,
            '''Show install software repository for XR''',
            False, 
            [
            _MetaInfoClassMember('log', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                log
                ''',
                'log',
                'Cisco-IOS-XR-spirit-install-instmgr-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-spirit-install-instmgr-oper',
            'xr',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-spirit-install-instmgr-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_spirit_install_instmgr_oper',
            is_config=False,
        ),
    },
    'SoftwareInstall.Repository.All' : {
        'meta_info' : _MetaInfoClass('SoftwareInstall.Repository.All', REFERENCE_CLASS,
            '''Show contents of all install software
repositories''',
            False, 
            [
            _MetaInfoClassMember('log', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                log
                ''',
                'log',
                'Cisco-IOS-XR-spirit-install-instmgr-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-spirit-install-instmgr-oper',
            'all',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-spirit-install-instmgr-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_spirit_install_instmgr_oper',
            is_config=False,
        ),
    },
    'SoftwareInstall.Repository' : {
        'meta_info' : _MetaInfoClass('SoftwareInstall.Repository', REFERENCE_CLASS,
            '''Show packages stored in install software
repositories''',
            False, 
            [
            _MetaInfoClassMember('xr', REFERENCE_CLASS, 'Xr', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_spirit_install_instmgr_oper', 'SoftwareInstall.Repository.Xr',
                [], [],
                '''                Show install software repository for XR
                ''',
                'xr',
                'Cisco-IOS-XR-spirit-install-instmgr-oper', False, is_config=False),
            _MetaInfoClassMember('all', REFERENCE_CLASS, 'All', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_spirit_install_instmgr_oper', 'SoftwareInstall.Repository.All',
                [], [],
                '''                Show contents of all install software
                repositories
                ''',
                'all',
                'Cisco-IOS-XR-spirit-install-instmgr-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-spirit-install-instmgr-oper',
            'repository',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-spirit-install-instmgr-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_spirit_install_instmgr_oper',
            is_config=False,
        ),
    },
    'SoftwareInstall' : {
        'meta_info' : _MetaInfoClass('SoftwareInstall', REFERENCE_CLASS,
            '''Install operations info''',
            False, 
            [
            _MetaInfoClassMember('superseded', REFERENCE_CLASS, 'Superseded', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_spirit_install_instmgr_oper', 'SoftwareInstall.Superseded',
                [], [],
                '''                Show superseded packages
                ''',
                'superseded',
                'Cisco-IOS-XR-spirit-install-instmgr-oper', False, is_config=False),
            _MetaInfoClassMember('committed-summary', REFERENCE_CLASS, 'CommittedSummary', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_spirit_install_instmgr_oper', 'SoftwareInstall.CommittedSummary',
                [], [],
                '''                Show Committed packages installed
                ''',
                'committed_summary',
                'Cisco-IOS-XR-spirit-install-instmgr-oper', False, is_config=False),
            _MetaInfoClassMember('active-summary', REFERENCE_CLASS, 'ActiveSummary', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_spirit_install_instmgr_oper', 'SoftwareInstall.ActiveSummary',
                [], [],
                '''                Show active packages installed
                ''',
                'active_summary',
                'Cisco-IOS-XR-spirit-install-instmgr-oper', False, is_config=False),
            _MetaInfoClassMember('inactive-summary', REFERENCE_CLASS, 'InactiveSummary', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_spirit_install_instmgr_oper', 'SoftwareInstall.InactiveSummary',
                [], [],
                '''                Show XR inactive packages
                ''',
                'inactive_summary',
                'Cisco-IOS-XR-spirit-install-instmgr-oper', False, is_config=False),
            _MetaInfoClassMember('prepare', REFERENCE_CLASS, 'Prepare', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_spirit_install_instmgr_oper', 'SoftwareInstall.Prepare',
                [], [],
                '''                Show prepared packages ready for activation
                ''',
                'prepare',
                'Cisco-IOS-XR-spirit-install-instmgr-oper', False, is_config=False),
            _MetaInfoClassMember('active', REFERENCE_CLASS, 'Active', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_spirit_install_instmgr_oper', 'SoftwareInstall.Active',
                [], [],
                '''                Show active packages installed
                ''',
                'active',
                'Cisco-IOS-XR-spirit-install-instmgr-oper', False, is_config=False),
            _MetaInfoClassMember('version', REFERENCE_CLASS, 'Version', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_spirit_install_instmgr_oper', 'SoftwareInstall.Version',
                [], [],
                '''                Show install version
                ''',
                'version',
                'Cisco-IOS-XR-spirit-install-instmgr-oper', False, is_config=False),
            _MetaInfoClassMember('inactive', REFERENCE_CLASS, 'Inactive', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_spirit_install_instmgr_oper', 'SoftwareInstall.Inactive',
                [], [],
                '''                Show XR inactive packages
                ''',
                'inactive',
                'Cisco-IOS-XR-spirit-install-instmgr-oper', False, is_config=False),
            _MetaInfoClassMember('request', REFERENCE_CLASS, 'Request', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_spirit_install_instmgr_oper', 'SoftwareInstall.Request',
                [], [],
                '''                Show current request
                ''',
                'request',
                'Cisco-IOS-XR-spirit-install-instmgr-oper', False, is_config=False),
            _MetaInfoClassMember('superseded-summary', REFERENCE_CLASS, 'SupersededSummary', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_spirit_install_instmgr_oper', 'SoftwareInstall.SupersededSummary',
                [], [],
                '''                Show superseded packages
                ''',
                'superseded_summary',
                'Cisco-IOS-XR-spirit-install-instmgr-oper', False, is_config=False),
            _MetaInfoClassMember('issu', REFERENCE_CLASS, 'Issu', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_spirit_install_instmgr_oper', 'SoftwareInstall.Issu',
                [], [],
                '''                ISSU operation
                ''',
                'issu',
                'Cisco-IOS-XR-spirit-install-instmgr-oper', False, is_config=False),
            _MetaInfoClassMember('committed', REFERENCE_CLASS, 'Committed', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_spirit_install_instmgr_oper', 'SoftwareInstall.Committed',
                [], [],
                '''                Show Committed packages installed
                ''',
                'committed',
                'Cisco-IOS-XR-spirit-install-instmgr-oper', False, is_config=False),
            _MetaInfoClassMember('all-operations-log', REFERENCE_CLASS, 'AllOperationsLog', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_spirit_install_instmgr_oper', 'SoftwareInstall.AllOperationsLog',
                [], [],
                '''                Show log file for all operations
                ''',
                'all_operations_log',
                'Cisco-IOS-XR-spirit-install-instmgr-oper', False, is_config=False),
            _MetaInfoClassMember('packages', REFERENCE_CLASS, 'Packages', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_spirit_install_instmgr_oper', 'SoftwareInstall.Packages',
                [], [],
                '''                Show the list of installed packages
                ''',
                'packages',
                'Cisco-IOS-XR-spirit-install-instmgr-oper', False, is_config=False),
            _MetaInfoClassMember('operation-logs', REFERENCE_CLASS, 'OperationLogs', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_spirit_install_instmgr_oper', 'SoftwareInstall.OperationLogs',
                [], [],
                '''                Show log file
                ''',
                'operation_logs',
                'Cisco-IOS-XR-spirit-install-instmgr-oper', False, is_config=False),
            _MetaInfoClassMember('repository', REFERENCE_CLASS, 'Repository', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_spirit_install_instmgr_oper', 'SoftwareInstall.Repository',
                [], [],
                '''                Show packages stored in install software
                repositories
                ''',
                'repository',
                'Cisco-IOS-XR-spirit-install-instmgr-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-spirit-install-instmgr-oper',
            'software-install',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-spirit-install-instmgr-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_spirit_install_instmgr_oper',
            is_config=False,
        ),
    },
}
_meta_table['SoftwareInstall.Superseded.SupersededPackageInfo']['meta_info'].parent =_meta_table['SoftwareInstall.Superseded']['meta_info']
_meta_table['SoftwareInstall.CommittedSummary.CommittedPackageInfo']['meta_info'].parent =_meta_table['SoftwareInstall.CommittedSummary']['meta_info']
_meta_table['SoftwareInstall.ActiveSummary.ActivePackageInfo']['meta_info'].parent =_meta_table['SoftwareInstall.ActiveSummary']['meta_info']
_meta_table['SoftwareInstall.Prepare.Rpm']['meta_info'].parent =_meta_table['SoftwareInstall.Prepare']['meta_info']
_meta_table['SoftwareInstall.Prepare.Package']['meta_info'].parent =_meta_table['SoftwareInstall.Prepare']['meta_info']
_meta_table['SoftwareInstall.Active.ActivePackageInfo']['meta_info'].parent =_meta_table['SoftwareInstall.Active']['meta_info']
_meta_table['SoftwareInstall.Version.Package']['meta_info'].parent =_meta_table['SoftwareInstall.Version']['meta_info']
_meta_table['SoftwareInstall.Issu.Inventory.Invinfo']['meta_info'].parent =_meta_table['SoftwareInstall.Issu.Inventory']['meta_info']
_meta_table['SoftwareInstall.Issu.Stage']['meta_info'].parent =_meta_table['SoftwareInstall.Issu']['meta_info']
_meta_table['SoftwareInstall.Issu.Inventory']['meta_info'].parent =_meta_table['SoftwareInstall.Issu']['meta_info']
_meta_table['SoftwareInstall.Committed.CommittedPackageInfo']['meta_info'].parent =_meta_table['SoftwareInstall.Committed']['meta_info']
_meta_table['SoftwareInstall.AllOperationsLog.ReverseDetail']['meta_info'].parent =_meta_table['SoftwareInstall.AllOperationsLog']['meta_info']
_meta_table['SoftwareInstall.AllOperationsLog.Reverse']['meta_info'].parent =_meta_table['SoftwareInstall.AllOperationsLog']['meta_info']
_meta_table['SoftwareInstall.AllOperationsLog.Summary']['meta_info'].parent =_meta_table['SoftwareInstall.AllOperationsLog']['meta_info']
_meta_table['SoftwareInstall.AllOperationsLog.Detail']['meta_info'].parent =_meta_table['SoftwareInstall.AllOperationsLog']['meta_info']
_meta_table['SoftwareInstall.Packages.Package.Verbose']['meta_info'].parent =_meta_table['SoftwareInstall.Packages.Package']['meta_info']
_meta_table['SoftwareInstall.Packages.Package.Brief']['meta_info'].parent =_meta_table['SoftwareInstall.Packages.Package']['meta_info']
_meta_table['SoftwareInstall.Packages.Package.Detail']['meta_info'].parent =_meta_table['SoftwareInstall.Packages.Package']['meta_info']
_meta_table['SoftwareInstall.Packages.Package']['meta_info'].parent =_meta_table['SoftwareInstall.Packages']['meta_info']
_meta_table['SoftwareInstall.OperationLogs.OperationLog.Summary']['meta_info'].parent =_meta_table['SoftwareInstall.OperationLogs.OperationLog']['meta_info']
_meta_table['SoftwareInstall.OperationLogs.OperationLog.Detail']['meta_info'].parent =_meta_table['SoftwareInstall.OperationLogs.OperationLog']['meta_info']
_meta_table['SoftwareInstall.OperationLogs.OperationLog']['meta_info'].parent =_meta_table['SoftwareInstall.OperationLogs']['meta_info']
_meta_table['SoftwareInstall.Repository.Xr']['meta_info'].parent =_meta_table['SoftwareInstall.Repository']['meta_info']
_meta_table['SoftwareInstall.Repository.All']['meta_info'].parent =_meta_table['SoftwareInstall.Repository']['meta_info']
_meta_table['SoftwareInstall.Superseded']['meta_info'].parent =_meta_table['SoftwareInstall']['meta_info']
_meta_table['SoftwareInstall.CommittedSummary']['meta_info'].parent =_meta_table['SoftwareInstall']['meta_info']
_meta_table['SoftwareInstall.ActiveSummary']['meta_info'].parent =_meta_table['SoftwareInstall']['meta_info']
_meta_table['SoftwareInstall.InactiveSummary']['meta_info'].parent =_meta_table['SoftwareInstall']['meta_info']
_meta_table['SoftwareInstall.Prepare']['meta_info'].parent =_meta_table['SoftwareInstall']['meta_info']
_meta_table['SoftwareInstall.Active']['meta_info'].parent =_meta_table['SoftwareInstall']['meta_info']
_meta_table['SoftwareInstall.Version']['meta_info'].parent =_meta_table['SoftwareInstall']['meta_info']
_meta_table['SoftwareInstall.Inactive']['meta_info'].parent =_meta_table['SoftwareInstall']['meta_info']
_meta_table['SoftwareInstall.Request']['meta_info'].parent =_meta_table['SoftwareInstall']['meta_info']
_meta_table['SoftwareInstall.SupersededSummary']['meta_info'].parent =_meta_table['SoftwareInstall']['meta_info']
_meta_table['SoftwareInstall.Issu']['meta_info'].parent =_meta_table['SoftwareInstall']['meta_info']
_meta_table['SoftwareInstall.Committed']['meta_info'].parent =_meta_table['SoftwareInstall']['meta_info']
_meta_table['SoftwareInstall.AllOperationsLog']['meta_info'].parent =_meta_table['SoftwareInstall']['meta_info']
_meta_table['SoftwareInstall.Packages']['meta_info'].parent =_meta_table['SoftwareInstall']['meta_info']
_meta_table['SoftwareInstall.OperationLogs']['meta_info'].parent =_meta_table['SoftwareInstall']['meta_info']
_meta_table['SoftwareInstall.Repository']['meta_info'].parent =_meta_table['SoftwareInstall']['meta_info']
