
'''
This is auto-generated file,
which includes metadata for module Cisco_IOS_XR_ip_ntp_oper
'''

from ydk._core._dm_meta_info import _MetaInfoClassMember, _MetaInfoClass, _MetaInfoEnum
from ydk._core._dm_meta_info import ATTRIBUTE, REFERENCE_LIST, REFERENCE_LEAFLIST, REFERENCE_BITS, REFERENCE_UNION
from ydk._core._dm_meta_info import REFERENCE_CLASS, REFERENCE_IDENTITY_CLASS, REFERENCE_ENUM_CLASS, ANYXML_CLASS
from ydk._core._importer import _yang_ns

_meta_table = {
    'ClockUpdateNode' : _MetaInfoEnum('ClockUpdateNode',
        'ydk.models.cisco_ios_xr.Cisco_IOS_XR_ip_ntp_oper', 'ClockUpdateNode',
        '''Mode of Clock Update''',
        {
            'clk-never-updated':'clk_never_updated',
            'clk-updated':'clk_updated',
            'clk-no-update-info':'clk_no_update_info',
        }, 'Cisco-IOS-XR-ip-ntp-oper', _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-ip-ntp-oper']),
    'NtpLoopFilterState' : _MetaInfoEnum('NtpLoopFilterState',
        'ydk.models.cisco_ios_xr.Cisco_IOS_XR_ip_ntp_oper', 'NtpLoopFilterState',
        '''Loop filter state''',
        {
            'ntp-loop-flt-n-set':'ntp_loop_flt_n_set',
            'ntp-loop-flt-f-set':'ntp_loop_flt_f_set',
            'ntp-loop-flt-spik':'ntp_loop_flt_spik',
            'ntp-loop-flt-freq':'ntp_loop_flt_freq',
            'ntp-loop-flt-sync':'ntp_loop_flt_sync',
            'ntp-loop-flt-unkn':'ntp_loop_flt_unkn',
        }, 'Cisco-IOS-XR-ip-ntp-oper', _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-ip-ntp-oper']),
    'NtpPeerStatus' : _MetaInfoEnum('NtpPeerStatus',
        'ydk.models.cisco_ios_xr.Cisco_IOS_XR_ip_ntp_oper', 'NtpPeerStatus',
        '''Type of peer status''',
        {
            'ntp-ctl-pst-sel-reject':'ntp_ctl_pst_sel_reject',
            'ntp-ctl-pst-sel-sane':'ntp_ctl_pst_sel_sane',
            'ntp-ctl-pst-sel-correct':'ntp_ctl_pst_sel_correct',
            'ntp-ctl-pst-sel-selcand':'ntp_ctl_pst_sel_selcand',
            'ntp-ctl-pst-sel-sync-cand':'ntp_ctl_pst_sel_sync_cand',
            'ntp-ctl-pst-sel-distsys-peer':'ntp_ctl_pst_sel_distsys_peer',
            'ntp-ctl-pst-sel-sys-peer':'ntp_ctl_pst_sel_sys_peer',
            'ntp-ctl-pst-sel-pps':'ntp_ctl_pst_sel_pps',
        }, 'Cisco-IOS-XR-ip-ntp-oper', _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-ip-ntp-oper']),
    'NtpMode' : _MetaInfoEnum('NtpMode',
        'ydk.models.cisco_ios_xr.Cisco_IOS_XR_ip_ntp_oper', 'NtpMode',
        '''Type of mode''',
        {
            'ntp-mode-unspec':'ntp_mode_unspec',
            'ntp-mode-symetric-active':'ntp_mode_symetric_active',
            'ntp-mode-symetric-passive':'ntp_mode_symetric_passive',
            'ntp-mode-client':'ntp_mode_client',
            'ntp-mode-server':'ntp_mode_server',
            'ntp-mode-xcast-server':'ntp_mode_xcast_server',
            'ntp-mode-control':'ntp_mode_control',
            'ntp-mode-private':'ntp_mode_private',
            'ntp-mode-xcast-client':'ntp_mode_xcast_client',
        }, 'Cisco-IOS-XR-ip-ntp-oper', _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-ip-ntp-oper']),
    'NtpLeap' : _MetaInfoEnum('NtpLeap',
        'ydk.models.cisco_ios_xr.Cisco_IOS_XR_ip_ntp_oper', 'NtpLeap',
        '''Type of leap''',
        {
            'ntp-leap-no-warning':'ntp_leap_no_warning',
            'ntp-leap-addse-cond':'ntp_leap_addse_cond',
            'ntp-leap-delse-cond':'ntp_leap_delse_cond',
            'ntp-leap-not-in-sync':'ntp_leap_not_in_sync',
        }, 'Cisco-IOS-XR-ip-ntp-oper', _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-ip-ntp-oper']),
    'Ntp.Nodes.Node.AssociationsDetail.PeerDetailInfo.PeerInfoCommon' : {
        'meta_info' : _MetaInfoClass('Ntp.Nodes.Node.AssociationsDetail.PeerDetailInfo.PeerInfoCommon', REFERENCE_CLASS,
            '''Common peer info''',
            False, 
            [
            _MetaInfoClassMember('host-mode', REFERENCE_ENUM_CLASS, 'NtpMode', 'Ntp-mode',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_ip_ntp_oper', 'NtpMode',
                [], [],
                '''                Association mode with this peer
                ''',
                'host_mode',
                'Cisco-IOS-XR-ip-ntp-oper', False, is_config=False),
            _MetaInfoClassMember('is-configured', ATTRIBUTE, 'bool', 'boolean',
                None, None,
                [], [],
                '''                Is configured
                ''',
                'is_configured',
                'Cisco-IOS-XR-ip-ntp-oper', False, is_config=False),
            _MetaInfoClassMember('address', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Peer Address
                ''',
                'address',
                'Cisco-IOS-XR-ip-ntp-oper', False, is_config=False),
            _MetaInfoClassMember('reference-id', ATTRIBUTE, 'str', 'inet:ipv4-address',
                None, None,
                [], [b'(([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])(%[\\p{N}\\p{L}]+)?'],
                '''                Peer reference ID
                ''',
                'reference_id',
                'Cisco-IOS-XR-ip-ntp-oper', False, is_config=False),
            _MetaInfoClassMember('host-poll', ATTRIBUTE, 'int', 'uint8',
                None, None,
                [('0', '255')], [],
                '''                Host poll
                ''',
                'host_poll',
                'Cisco-IOS-XR-ip-ntp-oper', False, is_config=False),
            _MetaInfoClassMember('reachability', ATTRIBUTE, 'int', 'uint8',
                None, None,
                [('0', '255')], [],
                '''                Reachability
                ''',
                'reachability',
                'Cisco-IOS-XR-ip-ntp-oper', False, is_config=False),
            _MetaInfoClassMember('stratum', ATTRIBUTE, 'int', 'uint8',
                None, None,
                [('0', '255')], [],
                '''                Peer stratum
                ''',
                'stratum',
                'Cisco-IOS-XR-ip-ntp-oper', False, is_config=False),
            _MetaInfoClassMember('status', REFERENCE_ENUM_CLASS, 'NtpPeerStatus', 'Ntp-peer-status',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_ip_ntp_oper', 'NtpPeerStatus',
                [], [],
                '''                Peer status
                ''',
                'status',
                'Cisco-IOS-XR-ip-ntp-oper', False, is_config=False),
            _MetaInfoClassMember('delay', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Peer delay
                ''',
                'delay',
                'Cisco-IOS-XR-ip-ntp-oper', False, is_config=False),
            _MetaInfoClassMember('offset', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Peer offset
                ''',
                'offset',
                'Cisco-IOS-XR-ip-ntp-oper', False, is_config=False),
            _MetaInfoClassMember('dispersion', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Peer dispersion
                ''',
                'dispersion',
                'Cisco-IOS-XR-ip-ntp-oper', False, is_config=False),
            _MetaInfoClassMember('is-sys-peer', ATTRIBUTE, 'bool', 'boolean',
                None, None,
                [], [],
                '''                Indicates whether this is syspeer
                ''',
                'is_sys_peer',
                'Cisco-IOS-XR-ip-ntp-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-ip-ntp-oper',
            'peer-info-common',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-ip-ntp-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_ip_ntp_oper',
            is_config=False,
        ),
    },
    'Ntp.Nodes.Node.AssociationsDetail.PeerDetailInfo.RefTime.Sec' : {
        'meta_info' : _MetaInfoClass('Ntp.Nodes.Node.AssociationsDetail.PeerDetailInfo.RefTime.Sec', REFERENCE_CLASS,
            '''Second part in 64-bit NTP timestamp''',
            False, 
            [
            _MetaInfoClassMember('int', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                Integer format in NTP reference code
                ''',
                'int',
                'Cisco-IOS-XR-ip-ntp-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-ip-ntp-oper',
            'sec',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-ip-ntp-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_ip_ntp_oper',
            is_config=False,
        ),
    },
    'Ntp.Nodes.Node.AssociationsDetail.PeerDetailInfo.RefTime.FracSecs' : {
        'meta_info' : _MetaInfoClass('Ntp.Nodes.Node.AssociationsDetail.PeerDetailInfo.RefTime.FracSecs', REFERENCE_CLASS,
            '''Fractional part in 64-bit NTP timestamp''',
            False, 
            [
            _MetaInfoClassMember('frac', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                Fractional format in NTP reference code
                ''',
                'frac',
                'Cisco-IOS-XR-ip-ntp-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-ip-ntp-oper',
            'frac-secs',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-ip-ntp-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_ip_ntp_oper',
            is_config=False,
        ),
    },
    'Ntp.Nodes.Node.AssociationsDetail.PeerDetailInfo.RefTime' : {
        'meta_info' : _MetaInfoClass('Ntp.Nodes.Node.AssociationsDetail.PeerDetailInfo.RefTime', REFERENCE_CLASS,
            '''Reference time''',
            False, 
            [
            _MetaInfoClassMember('sec', REFERENCE_CLASS, 'Sec', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_ip_ntp_oper', 'Ntp.Nodes.Node.AssociationsDetail.PeerDetailInfo.RefTime.Sec',
                [], [],
                '''                Second part in 64-bit NTP timestamp
                ''',
                'sec',
                'Cisco-IOS-XR-ip-ntp-oper', False, is_config=False),
            _MetaInfoClassMember('frac-secs', REFERENCE_CLASS, 'FracSecs', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_ip_ntp_oper', 'Ntp.Nodes.Node.AssociationsDetail.PeerDetailInfo.RefTime.FracSecs',
                [], [],
                '''                Fractional part in 64-bit NTP timestamp
                ''',
                'frac_secs',
                'Cisco-IOS-XR-ip-ntp-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-ip-ntp-oper',
            'ref-time',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-ip-ntp-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_ip_ntp_oper',
            is_config=False,
        ),
    },
    'Ntp.Nodes.Node.AssociationsDetail.PeerDetailInfo.OriginateTime.Sec' : {
        'meta_info' : _MetaInfoClass('Ntp.Nodes.Node.AssociationsDetail.PeerDetailInfo.OriginateTime.Sec', REFERENCE_CLASS,
            '''Second part in 64-bit NTP timestamp''',
            False, 
            [
            _MetaInfoClassMember('int', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                Integer format in NTP reference code
                ''',
                'int',
                'Cisco-IOS-XR-ip-ntp-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-ip-ntp-oper',
            'sec',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-ip-ntp-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_ip_ntp_oper',
            is_config=False,
        ),
    },
    'Ntp.Nodes.Node.AssociationsDetail.PeerDetailInfo.OriginateTime.FracSecs' : {
        'meta_info' : _MetaInfoClass('Ntp.Nodes.Node.AssociationsDetail.PeerDetailInfo.OriginateTime.FracSecs', REFERENCE_CLASS,
            '''Fractional part in 64-bit NTP timestamp''',
            False, 
            [
            _MetaInfoClassMember('frac', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                Fractional format in NTP reference code
                ''',
                'frac',
                'Cisco-IOS-XR-ip-ntp-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-ip-ntp-oper',
            'frac-secs',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-ip-ntp-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_ip_ntp_oper',
            is_config=False,
        ),
    },
    'Ntp.Nodes.Node.AssociationsDetail.PeerDetailInfo.OriginateTime' : {
        'meta_info' : _MetaInfoClass('Ntp.Nodes.Node.AssociationsDetail.PeerDetailInfo.OriginateTime', REFERENCE_CLASS,
            '''Originate timestamp''',
            False, 
            [
            _MetaInfoClassMember('sec', REFERENCE_CLASS, 'Sec', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_ip_ntp_oper', 'Ntp.Nodes.Node.AssociationsDetail.PeerDetailInfo.OriginateTime.Sec',
                [], [],
                '''                Second part in 64-bit NTP timestamp
                ''',
                'sec',
                'Cisco-IOS-XR-ip-ntp-oper', False, is_config=False),
            _MetaInfoClassMember('frac-secs', REFERENCE_CLASS, 'FracSecs', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_ip_ntp_oper', 'Ntp.Nodes.Node.AssociationsDetail.PeerDetailInfo.OriginateTime.FracSecs',
                [], [],
                '''                Fractional part in 64-bit NTP timestamp
                ''',
                'frac_secs',
                'Cisco-IOS-XR-ip-ntp-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-ip-ntp-oper',
            'originate-time',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-ip-ntp-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_ip_ntp_oper',
            is_config=False,
        ),
    },
    'Ntp.Nodes.Node.AssociationsDetail.PeerDetailInfo.ReceiveTime.Sec' : {
        'meta_info' : _MetaInfoClass('Ntp.Nodes.Node.AssociationsDetail.PeerDetailInfo.ReceiveTime.Sec', REFERENCE_CLASS,
            '''Second part in 64-bit NTP timestamp''',
            False, 
            [
            _MetaInfoClassMember('int', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                Integer format in NTP reference code
                ''',
                'int',
                'Cisco-IOS-XR-ip-ntp-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-ip-ntp-oper',
            'sec',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-ip-ntp-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_ip_ntp_oper',
            is_config=False,
        ),
    },
    'Ntp.Nodes.Node.AssociationsDetail.PeerDetailInfo.ReceiveTime.FracSecs' : {
        'meta_info' : _MetaInfoClass('Ntp.Nodes.Node.AssociationsDetail.PeerDetailInfo.ReceiveTime.FracSecs', REFERENCE_CLASS,
            '''Fractional part in 64-bit NTP timestamp''',
            False, 
            [
            _MetaInfoClassMember('frac', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                Fractional format in NTP reference code
                ''',
                'frac',
                'Cisco-IOS-XR-ip-ntp-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-ip-ntp-oper',
            'frac-secs',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-ip-ntp-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_ip_ntp_oper',
            is_config=False,
        ),
    },
    'Ntp.Nodes.Node.AssociationsDetail.PeerDetailInfo.ReceiveTime' : {
        'meta_info' : _MetaInfoClass('Ntp.Nodes.Node.AssociationsDetail.PeerDetailInfo.ReceiveTime', REFERENCE_CLASS,
            '''Receive timestamp''',
            False, 
            [
            _MetaInfoClassMember('sec', REFERENCE_CLASS, 'Sec', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_ip_ntp_oper', 'Ntp.Nodes.Node.AssociationsDetail.PeerDetailInfo.ReceiveTime.Sec',
                [], [],
                '''                Second part in 64-bit NTP timestamp
                ''',
                'sec',
                'Cisco-IOS-XR-ip-ntp-oper', False, is_config=False),
            _MetaInfoClassMember('frac-secs', REFERENCE_CLASS, 'FracSecs', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_ip_ntp_oper', 'Ntp.Nodes.Node.AssociationsDetail.PeerDetailInfo.ReceiveTime.FracSecs',
                [], [],
                '''                Fractional part in 64-bit NTP timestamp
                ''',
                'frac_secs',
                'Cisco-IOS-XR-ip-ntp-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-ip-ntp-oper',
            'receive-time',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-ip-ntp-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_ip_ntp_oper',
            is_config=False,
        ),
    },
    'Ntp.Nodes.Node.AssociationsDetail.PeerDetailInfo.TransmitTime.Sec' : {
        'meta_info' : _MetaInfoClass('Ntp.Nodes.Node.AssociationsDetail.PeerDetailInfo.TransmitTime.Sec', REFERENCE_CLASS,
            '''Second part in 64-bit NTP timestamp''',
            False, 
            [
            _MetaInfoClassMember('int', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                Integer format in NTP reference code
                ''',
                'int',
                'Cisco-IOS-XR-ip-ntp-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-ip-ntp-oper',
            'sec',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-ip-ntp-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_ip_ntp_oper',
            is_config=False,
        ),
    },
    'Ntp.Nodes.Node.AssociationsDetail.PeerDetailInfo.TransmitTime.FracSecs' : {
        'meta_info' : _MetaInfoClass('Ntp.Nodes.Node.AssociationsDetail.PeerDetailInfo.TransmitTime.FracSecs', REFERENCE_CLASS,
            '''Fractional part in 64-bit NTP timestamp''',
            False, 
            [
            _MetaInfoClassMember('frac', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                Fractional format in NTP reference code
                ''',
                'frac',
                'Cisco-IOS-XR-ip-ntp-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-ip-ntp-oper',
            'frac-secs',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-ip-ntp-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_ip_ntp_oper',
            is_config=False,
        ),
    },
    'Ntp.Nodes.Node.AssociationsDetail.PeerDetailInfo.TransmitTime' : {
        'meta_info' : _MetaInfoClass('Ntp.Nodes.Node.AssociationsDetail.PeerDetailInfo.TransmitTime', REFERENCE_CLASS,
            '''Transmit timestamp''',
            False, 
            [
            _MetaInfoClassMember('sec', REFERENCE_CLASS, 'Sec', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_ip_ntp_oper', 'Ntp.Nodes.Node.AssociationsDetail.PeerDetailInfo.TransmitTime.Sec',
                [], [],
                '''                Second part in 64-bit NTP timestamp
                ''',
                'sec',
                'Cisco-IOS-XR-ip-ntp-oper', False, is_config=False),
            _MetaInfoClassMember('frac-secs', REFERENCE_CLASS, 'FracSecs', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_ip_ntp_oper', 'Ntp.Nodes.Node.AssociationsDetail.PeerDetailInfo.TransmitTime.FracSecs',
                [], [],
                '''                Fractional part in 64-bit NTP timestamp
                ''',
                'frac_secs',
                'Cisco-IOS-XR-ip-ntp-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-ip-ntp-oper',
            'transmit-time',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-ip-ntp-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_ip_ntp_oper',
            is_config=False,
        ),
    },
    'Ntp.Nodes.Node.AssociationsDetail.PeerDetailInfo.FilterDetail' : {
        'meta_info' : _MetaInfoClass('Ntp.Nodes.Node.AssociationsDetail.PeerDetailInfo.FilterDetail', REFERENCE_LIST,
            '''Filter Details''',
            False, 
            [
            _MetaInfoClassMember('filter-delay', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                filter delay
                ''',
                'filter_delay',
                'Cisco-IOS-XR-ip-ntp-oper', False, is_config=False),
            _MetaInfoClassMember('filter-offset', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                filter offset
                ''',
                'filter_offset',
                'Cisco-IOS-XR-ip-ntp-oper', False, is_config=False),
            _MetaInfoClassMember('filter-disp', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                filter disp
                ''',
                'filter_disp',
                'Cisco-IOS-XR-ip-ntp-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-ip-ntp-oper',
            'filter-detail',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-ip-ntp-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_ip_ntp_oper',
            is_config=False,
        ),
    },
    'Ntp.Nodes.Node.AssociationsDetail.PeerDetailInfo' : {
        'meta_info' : _MetaInfoClass('Ntp.Nodes.Node.AssociationsDetail.PeerDetailInfo', REFERENCE_LIST,
            '''Peer info''',
            False, 
            [
            _MetaInfoClassMember('peer-info-common', REFERENCE_CLASS, 'PeerInfoCommon', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_ip_ntp_oper', 'Ntp.Nodes.Node.AssociationsDetail.PeerDetailInfo.PeerInfoCommon',
                [], [],
                '''                Common peer info
                ''',
                'peer_info_common',
                'Cisco-IOS-XR-ip-ntp-oper', False, is_config=False),
            _MetaInfoClassMember('ref-time', REFERENCE_CLASS, 'RefTime', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_ip_ntp_oper', 'Ntp.Nodes.Node.AssociationsDetail.PeerDetailInfo.RefTime',
                [], [],
                '''                Reference time
                ''',
                'ref_time',
                'Cisco-IOS-XR-ip-ntp-oper', False, is_config=False),
            _MetaInfoClassMember('originate-time', REFERENCE_CLASS, 'OriginateTime', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_ip_ntp_oper', 'Ntp.Nodes.Node.AssociationsDetail.PeerDetailInfo.OriginateTime',
                [], [],
                '''                Originate timestamp
                ''',
                'originate_time',
                'Cisco-IOS-XR-ip-ntp-oper', False, is_config=False),
            _MetaInfoClassMember('receive-time', REFERENCE_CLASS, 'ReceiveTime', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_ip_ntp_oper', 'Ntp.Nodes.Node.AssociationsDetail.PeerDetailInfo.ReceiveTime',
                [], [],
                '''                Receive timestamp
                ''',
                'receive_time',
                'Cisco-IOS-XR-ip-ntp-oper', False, is_config=False),
            _MetaInfoClassMember('transmit-time', REFERENCE_CLASS, 'TransmitTime', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_ip_ntp_oper', 'Ntp.Nodes.Node.AssociationsDetail.PeerDetailInfo.TransmitTime',
                [], [],
                '''                Transmit timestamp
                ''',
                'transmit_time',
                'Cisco-IOS-XR-ip-ntp-oper', False, is_config=False),
            _MetaInfoClassMember('leap', REFERENCE_ENUM_CLASS, 'NtpLeap', 'Ntp-leap',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_ip_ntp_oper', 'NtpLeap',
                [], [],
                '''                Leap
                ''',
                'leap',
                'Cisco-IOS-XR-ip-ntp-oper', False, is_config=False),
            _MetaInfoClassMember('peer-mode', REFERENCE_ENUM_CLASS, 'NtpMode', 'Ntp-mode',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_ip_ntp_oper', 'NtpMode',
                [], [],
                '''                Peer's association mode
                ''',
                'peer_mode',
                'Cisco-IOS-XR-ip-ntp-oper', False, is_config=False),
            _MetaInfoClassMember('poll-interval', ATTRIBUTE, 'int', 'uint8',
                None, None,
                [('0', '255')], [],
                '''                Peer poll interval
                ''',
                'poll_interval',
                'Cisco-IOS-XR-ip-ntp-oper', False, is_config=False),
            _MetaInfoClassMember('is-ref-clock', ATTRIBUTE, 'bool', 'boolean',
                None, None,
                [], [],
                '''                Is refclock
                ''',
                'is_ref_clock',
                'Cisco-IOS-XR-ip-ntp-oper', False, is_config=False),
            _MetaInfoClassMember('is-authenticated', ATTRIBUTE, 'bool', 'boolean',
                None, None,
                [], [],
                '''                Is authenticated
                ''',
                'is_authenticated',
                'Cisco-IOS-XR-ip-ntp-oper', False, is_config=False),
            _MetaInfoClassMember('root-delay', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Root delay
                ''',
                'root_delay',
                'Cisco-IOS-XR-ip-ntp-oper', False, is_config=False),
            _MetaInfoClassMember('root-dispersion', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Root dispersion
                ''',
                'root_dispersion',
                'Cisco-IOS-XR-ip-ntp-oper', False, is_config=False),
            _MetaInfoClassMember('synch-distance', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Synch distance
                ''',
                'synch_distance',
                'Cisco-IOS-XR-ip-ntp-oper', False, is_config=False),
            _MetaInfoClassMember('precision', ATTRIBUTE, 'int', 'int8',
                None, None,
                [('-128', '127')], [],
                '''                Precision
                ''',
                'precision',
                'Cisco-IOS-XR-ip-ntp-oper', False, is_config=False),
            _MetaInfoClassMember('version', ATTRIBUTE, 'int', 'uint8',
                None, None,
                [('0', '255')], [],
                '''                NTP version
                ''',
                'version',
                'Cisco-IOS-XR-ip-ntp-oper', False, is_config=False),
            _MetaInfoClassMember('filter-index', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                Index into filter shift register
                ''',
                'filter_index',
                'Cisco-IOS-XR-ip-ntp-oper', False, is_config=False),
            _MetaInfoClassMember('cast-flags', ATTRIBUTE, 'int', 'uint8',
                None, None,
                [('0', '255')], [],
                '''                Cast Flags
                ''',
                'cast_flags',
                'Cisco-IOS-XR-ip-ntp-oper', False, is_config=False),
            _MetaInfoClassMember('filter-detail', REFERENCE_LIST, 'FilterDetail', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_ip_ntp_oper', 'Ntp.Nodes.Node.AssociationsDetail.PeerDetailInfo.FilterDetail',
                [], [],
                '''                Filter Details
                ''',
                'filter_detail',
                'Cisco-IOS-XR-ip-ntp-oper', False, max_elements=8, is_config=False),
            ],
            'Cisco-IOS-XR-ip-ntp-oper',
            'peer-detail-info',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-ip-ntp-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_ip_ntp_oper',
            is_config=False,
        ),
    },
    'Ntp.Nodes.Node.AssociationsDetail' : {
        'meta_info' : _MetaInfoClass('Ntp.Nodes.Node.AssociationsDetail', REFERENCE_CLASS,
            '''NTP Associations Detail information''',
            False, 
            [
            _MetaInfoClassMember('is-ntp-enabled', ATTRIBUTE, 'bool', 'boolean',
                None, None,
                [], [],
                '''                Is NTP enabled
                ''',
                'is_ntp_enabled',
                'Cisco-IOS-XR-ip-ntp-oper', False, is_config=False),
            _MetaInfoClassMember('sys-leap', REFERENCE_ENUM_CLASS, 'NtpLeap', 'Ntp-leap',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_ip_ntp_oper', 'NtpLeap',
                [], [],
                '''                Leap
                ''',
                'sys_leap',
                'Cisco-IOS-XR-ip-ntp-oper', False, is_config=False),
            _MetaInfoClassMember('peer-detail-info', REFERENCE_LIST, 'PeerDetailInfo', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_ip_ntp_oper', 'Ntp.Nodes.Node.AssociationsDetail.PeerDetailInfo',
                [], [],
                '''                Peer info
                ''',
                'peer_detail_info',
                'Cisco-IOS-XR-ip-ntp-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-ip-ntp-oper',
            'associations-detail',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-ip-ntp-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_ip_ntp_oper',
            is_config=False,
        ),
    },
    'Ntp.Nodes.Node.Status.SysRefTime.Sec' : {
        'meta_info' : _MetaInfoClass('Ntp.Nodes.Node.Status.SysRefTime.Sec', REFERENCE_CLASS,
            '''Second part in 64-bit NTP timestamp''',
            False, 
            [
            _MetaInfoClassMember('int', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                Integer format in NTP reference code
                ''',
                'int',
                'Cisco-IOS-XR-ip-ntp-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-ip-ntp-oper',
            'sec',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-ip-ntp-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_ip_ntp_oper',
            is_config=False,
        ),
    },
    'Ntp.Nodes.Node.Status.SysRefTime.FracSecs' : {
        'meta_info' : _MetaInfoClass('Ntp.Nodes.Node.Status.SysRefTime.FracSecs', REFERENCE_CLASS,
            '''Fractional part in 64-bit NTP timestamp''',
            False, 
            [
            _MetaInfoClassMember('frac', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                Fractional format in NTP reference code
                ''',
                'frac',
                'Cisco-IOS-XR-ip-ntp-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-ip-ntp-oper',
            'frac-secs',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-ip-ntp-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_ip_ntp_oper',
            is_config=False,
        ),
    },
    'Ntp.Nodes.Node.Status.SysRefTime' : {
        'meta_info' : _MetaInfoClass('Ntp.Nodes.Node.Status.SysRefTime', REFERENCE_CLASS,
            '''Reference time''',
            False, 
            [
            _MetaInfoClassMember('sec', REFERENCE_CLASS, 'Sec', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_ip_ntp_oper', 'Ntp.Nodes.Node.Status.SysRefTime.Sec',
                [], [],
                '''                Second part in 64-bit NTP timestamp
                ''',
                'sec',
                'Cisco-IOS-XR-ip-ntp-oper', False, is_config=False),
            _MetaInfoClassMember('frac-secs', REFERENCE_CLASS, 'FracSecs', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_ip_ntp_oper', 'Ntp.Nodes.Node.Status.SysRefTime.FracSecs',
                [], [],
                '''                Fractional part in 64-bit NTP timestamp
                ''',
                'frac_secs',
                'Cisco-IOS-XR-ip-ntp-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-ip-ntp-oper',
            'sys-ref-time',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-ip-ntp-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_ip_ntp_oper',
            is_config=False,
        ),
    },
    'Ntp.Nodes.Node.Status.SysDrift.Sec' : {
        'meta_info' : _MetaInfoClass('Ntp.Nodes.Node.Status.SysDrift.Sec', REFERENCE_CLASS,
            '''Second part in 64-bit NTP timestamp''',
            False, 
            [
            _MetaInfoClassMember('int', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                Integer format in NTP reference code
                ''',
                'int',
                'Cisco-IOS-XR-ip-ntp-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-ip-ntp-oper',
            'sec',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-ip-ntp-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_ip_ntp_oper',
            is_config=False,
        ),
    },
    'Ntp.Nodes.Node.Status.SysDrift.FracSecs' : {
        'meta_info' : _MetaInfoClass('Ntp.Nodes.Node.Status.SysDrift.FracSecs', REFERENCE_CLASS,
            '''Fractional part in 64-bit NTP timestamp''',
            False, 
            [
            _MetaInfoClassMember('frac', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                Fractional format in NTP reference code
                ''',
                'frac',
                'Cisco-IOS-XR-ip-ntp-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-ip-ntp-oper',
            'frac-secs',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-ip-ntp-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_ip_ntp_oper',
            is_config=False,
        ),
    },
    'Ntp.Nodes.Node.Status.SysDrift' : {
        'meta_info' : _MetaInfoClass('Ntp.Nodes.Node.Status.SysDrift', REFERENCE_CLASS,
            '''System Drift''',
            False, 
            [
            _MetaInfoClassMember('sec', REFERENCE_CLASS, 'Sec', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_ip_ntp_oper', 'Ntp.Nodes.Node.Status.SysDrift.Sec',
                [], [],
                '''                Second part in 64-bit NTP timestamp
                ''',
                'sec',
                'Cisco-IOS-XR-ip-ntp-oper', False, is_config=False),
            _MetaInfoClassMember('frac-secs', REFERENCE_CLASS, 'FracSecs', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_ip_ntp_oper', 'Ntp.Nodes.Node.Status.SysDrift.FracSecs',
                [], [],
                '''                Fractional part in 64-bit NTP timestamp
                ''',
                'frac_secs',
                'Cisco-IOS-XR-ip-ntp-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-ip-ntp-oper',
            'sys-drift',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-ip-ntp-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_ip_ntp_oper',
            is_config=False,
        ),
    },
    'Ntp.Nodes.Node.Status' : {
        'meta_info' : _MetaInfoClass('Ntp.Nodes.Node.Status', REFERENCE_CLASS,
            '''Status of NTP peer(s)''',
            False, 
            [
            _MetaInfoClassMember('sys-ref-time', REFERENCE_CLASS, 'SysRefTime', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_ip_ntp_oper', 'Ntp.Nodes.Node.Status.SysRefTime',
                [], [],
                '''                Reference time
                ''',
                'sys_ref_time',
                'Cisco-IOS-XR-ip-ntp-oper', False, is_config=False),
            _MetaInfoClassMember('sys-drift', REFERENCE_CLASS, 'SysDrift', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_ip_ntp_oper', 'Ntp.Nodes.Node.Status.SysDrift',
                [], [],
                '''                System Drift
                ''',
                'sys_drift',
                'Cisco-IOS-XR-ip-ntp-oper', False, is_config=False),
            _MetaInfoClassMember('is-ntp-enabled', ATTRIBUTE, 'bool', 'boolean',
                None, None,
                [], [],
                '''                Is NTP enabled
                ''',
                'is_ntp_enabled',
                'Cisco-IOS-XR-ip-ntp-oper', False, is_config=False),
            _MetaInfoClassMember('sys-dispersion', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Peer dispersion
                ''',
                'sys_dispersion',
                'Cisco-IOS-XR-ip-ntp-oper', False, is_config=False),
            _MetaInfoClassMember('sys-offset', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Clock offset
                ''',
                'sys_offset',
                'Cisco-IOS-XR-ip-ntp-oper', False, is_config=False),
            _MetaInfoClassMember('clock-period', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                Clock period in nanosecs
                ''',
                'clock_period',
                'Cisco-IOS-XR-ip-ntp-oper', False, is_config=False),
            _MetaInfoClassMember('sys-leap', REFERENCE_ENUM_CLASS, 'NtpLeap', 'Ntp-leap',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_ip_ntp_oper', 'NtpLeap',
                [], [],
                '''                leap
                ''',
                'sys_leap',
                'Cisco-IOS-XR-ip-ntp-oper', False, is_config=False),
            _MetaInfoClassMember('sys-precision', ATTRIBUTE, 'int', 'int8',
                None, None,
                [('-128', '127')], [],
                '''                Precision
                ''',
                'sys_precision',
                'Cisco-IOS-XR-ip-ntp-oper', False, is_config=False),
            _MetaInfoClassMember('sys-stratum', ATTRIBUTE, 'int', 'uint8',
                None, None,
                [('0', '255')], [],
                '''                Stratum
                ''',
                'sys_stratum',
                'Cisco-IOS-XR-ip-ntp-oper', False, is_config=False),
            _MetaInfoClassMember('sys-ref-id', ATTRIBUTE, 'str', 'inet:ipv4-address',
                None, None,
                [], [b'(([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])(%[\\p{N}\\p{L}]+)?'],
                '''                Reference clock ID
                ''',
                'sys_ref_id',
                'Cisco-IOS-XR-ip-ntp-oper', False, is_config=False),
            _MetaInfoClassMember('sys-root-delay', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Root delay
                ''',
                'sys_root_delay',
                'Cisco-IOS-XR-ip-ntp-oper', False, is_config=False),
            _MetaInfoClassMember('sys-root-dispersion', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Root dispersion
                ''',
                'sys_root_dispersion',
                'Cisco-IOS-XR-ip-ntp-oper', False, is_config=False),
            _MetaInfoClassMember('loop-filter-state', REFERENCE_ENUM_CLASS, 'NtpLoopFilterState', 'Ntp-loop-filter-state',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_ip_ntp_oper', 'NtpLoopFilterState',
                [], [],
                '''                Loop Filter State
                ''',
                'loop_filter_state',
                'Cisco-IOS-XR-ip-ntp-oper', False, is_config=False),
            _MetaInfoClassMember('poll-interval', ATTRIBUTE, 'int', 'uint8',
                None, None,
                [('0', '255')], [],
                '''                Peer poll interval
                ''',
                'poll_interval',
                'Cisco-IOS-XR-ip-ntp-oper', False, is_config=False),
            _MetaInfoClassMember('is-updated', REFERENCE_ENUM_CLASS, 'ClockUpdateNode', 'Clock-update-node',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_ip_ntp_oper', 'ClockUpdateNode',
                [], [],
                '''                Is clock updated
                ''',
                'is_updated',
                'Cisco-IOS-XR-ip-ntp-oper', False, is_config=False),
            _MetaInfoClassMember('last-update', ATTRIBUTE, 'int', 'int32',
                None, None,
                [('-2147483648', '2147483647')], [],
                '''                Last Update
                ''',
                'last_update',
                'Cisco-IOS-XR-ip-ntp-oper', False, is_config=False),
            _MetaInfoClassMember('is-auth-enabled', ATTRIBUTE, 'bool', 'boolean',
                None, None,
                [], [],
                '''                Is NTP Authenticate enabled
                ''',
                'is_auth_enabled',
                'Cisco-IOS-XR-ip-ntp-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-ip-ntp-oper',
            'status',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-ip-ntp-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_ip_ntp_oper',
            is_config=False,
        ),
    },
    'Ntp.Nodes.Node.Associations.PeerSummaryInfo.PeerInfoCommon' : {
        'meta_info' : _MetaInfoClass('Ntp.Nodes.Node.Associations.PeerSummaryInfo.PeerInfoCommon', REFERENCE_CLASS,
            '''Common peer info''',
            False, 
            [
            _MetaInfoClassMember('host-mode', REFERENCE_ENUM_CLASS, 'NtpMode', 'Ntp-mode',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_ip_ntp_oper', 'NtpMode',
                [], [],
                '''                Association mode with this peer
                ''',
                'host_mode',
                'Cisco-IOS-XR-ip-ntp-oper', False, is_config=False),
            _MetaInfoClassMember('is-configured', ATTRIBUTE, 'bool', 'boolean',
                None, None,
                [], [],
                '''                Is configured
                ''',
                'is_configured',
                'Cisco-IOS-XR-ip-ntp-oper', False, is_config=False),
            _MetaInfoClassMember('address', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Peer Address
                ''',
                'address',
                'Cisco-IOS-XR-ip-ntp-oper', False, is_config=False),
            _MetaInfoClassMember('reference-id', ATTRIBUTE, 'str', 'inet:ipv4-address',
                None, None,
                [], [b'(([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])(%[\\p{N}\\p{L}]+)?'],
                '''                Peer reference ID
                ''',
                'reference_id',
                'Cisco-IOS-XR-ip-ntp-oper', False, is_config=False),
            _MetaInfoClassMember('host-poll', ATTRIBUTE, 'int', 'uint8',
                None, None,
                [('0', '255')], [],
                '''                Host poll
                ''',
                'host_poll',
                'Cisco-IOS-XR-ip-ntp-oper', False, is_config=False),
            _MetaInfoClassMember('reachability', ATTRIBUTE, 'int', 'uint8',
                None, None,
                [('0', '255')], [],
                '''                Reachability
                ''',
                'reachability',
                'Cisco-IOS-XR-ip-ntp-oper', False, is_config=False),
            _MetaInfoClassMember('stratum', ATTRIBUTE, 'int', 'uint8',
                None, None,
                [('0', '255')], [],
                '''                Peer stratum
                ''',
                'stratum',
                'Cisco-IOS-XR-ip-ntp-oper', False, is_config=False),
            _MetaInfoClassMember('status', REFERENCE_ENUM_CLASS, 'NtpPeerStatus', 'Ntp-peer-status',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_ip_ntp_oper', 'NtpPeerStatus',
                [], [],
                '''                Peer status
                ''',
                'status',
                'Cisco-IOS-XR-ip-ntp-oper', False, is_config=False),
            _MetaInfoClassMember('delay', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Peer delay
                ''',
                'delay',
                'Cisco-IOS-XR-ip-ntp-oper', False, is_config=False),
            _MetaInfoClassMember('offset', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Peer offset
                ''',
                'offset',
                'Cisco-IOS-XR-ip-ntp-oper', False, is_config=False),
            _MetaInfoClassMember('dispersion', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Peer dispersion
                ''',
                'dispersion',
                'Cisco-IOS-XR-ip-ntp-oper', False, is_config=False),
            _MetaInfoClassMember('is-sys-peer', ATTRIBUTE, 'bool', 'boolean',
                None, None,
                [], [],
                '''                Indicates whether this is syspeer
                ''',
                'is_sys_peer',
                'Cisco-IOS-XR-ip-ntp-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-ip-ntp-oper',
            'peer-info-common',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-ip-ntp-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_ip_ntp_oper',
            is_config=False,
        ),
    },
    'Ntp.Nodes.Node.Associations.PeerSummaryInfo' : {
        'meta_info' : _MetaInfoClass('Ntp.Nodes.Node.Associations.PeerSummaryInfo', REFERENCE_LIST,
            '''Peer info''',
            False, 
            [
            _MetaInfoClassMember('peer-info-common', REFERENCE_CLASS, 'PeerInfoCommon', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_ip_ntp_oper', 'Ntp.Nodes.Node.Associations.PeerSummaryInfo.PeerInfoCommon',
                [], [],
                '''                Common peer info
                ''',
                'peer_info_common',
                'Cisco-IOS-XR-ip-ntp-oper', False, is_config=False),
            _MetaInfoClassMember('time-since', ATTRIBUTE, 'int', 'int32',
                None, None,
                [('-2147483648', '2147483647')], [],
                '''                Time since last frame received (-1=none)
                ''',
                'time_since',
                'Cisco-IOS-XR-ip-ntp-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-ip-ntp-oper',
            'peer-summary-info',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-ip-ntp-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_ip_ntp_oper',
            is_config=False,
        ),
    },
    'Ntp.Nodes.Node.Associations' : {
        'meta_info' : _MetaInfoClass('Ntp.Nodes.Node.Associations', REFERENCE_CLASS,
            '''NTP Associations information''',
            False, 
            [
            _MetaInfoClassMember('is-ntp-enabled', ATTRIBUTE, 'bool', 'boolean',
                None, None,
                [], [],
                '''                Is NTP enabled
                ''',
                'is_ntp_enabled',
                'Cisco-IOS-XR-ip-ntp-oper', False, is_config=False),
            _MetaInfoClassMember('sys-leap', REFERENCE_ENUM_CLASS, 'NtpLeap', 'Ntp-leap',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_ip_ntp_oper', 'NtpLeap',
                [], [],
                '''                Leap
                ''',
                'sys_leap',
                'Cisco-IOS-XR-ip-ntp-oper', False, is_config=False),
            _MetaInfoClassMember('peer-summary-info', REFERENCE_LIST, 'PeerSummaryInfo', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_ip_ntp_oper', 'Ntp.Nodes.Node.Associations.PeerSummaryInfo',
                [], [],
                '''                Peer info
                ''',
                'peer_summary_info',
                'Cisco-IOS-XR-ip-ntp-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-ip-ntp-oper',
            'associations',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-ip-ntp-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_ip_ntp_oper',
            is_config=False,
        ),
    },
    'Ntp.Nodes.Node' : {
        'meta_info' : _MetaInfoClass('Ntp.Nodes.Node', REFERENCE_LIST,
            '''NTP operational data for a particular node''',
            False, 
            [
            _MetaInfoClassMember('node', ATTRIBUTE, 'str', 'xr:Node-id',
                None, None,
                [], [b'([a-zA-Z0-9_]*\\d+/){1,2}([a-zA-Z0-9_]*\\d+)'],
                '''                The node identifier
                ''',
                'node',
                'Cisco-IOS-XR-ip-ntp-oper', True, is_config=False),
            _MetaInfoClassMember('associations-detail', REFERENCE_CLASS, 'AssociationsDetail', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_ip_ntp_oper', 'Ntp.Nodes.Node.AssociationsDetail',
                [], [],
                '''                NTP Associations Detail information
                ''',
                'associations_detail',
                'Cisco-IOS-XR-ip-ntp-oper', False, is_config=False),
            _MetaInfoClassMember('status', REFERENCE_CLASS, 'Status', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_ip_ntp_oper', 'Ntp.Nodes.Node.Status',
                [], [],
                '''                Status of NTP peer(s)
                ''',
                'status',
                'Cisco-IOS-XR-ip-ntp-oper', False, is_config=False),
            _MetaInfoClassMember('associations', REFERENCE_CLASS, 'Associations', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_ip_ntp_oper', 'Ntp.Nodes.Node.Associations',
                [], [],
                '''                NTP Associations information
                ''',
                'associations',
                'Cisco-IOS-XR-ip-ntp-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-ip-ntp-oper',
            'node',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-ip-ntp-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_ip_ntp_oper',
            is_config=False,
        ),
    },
    'Ntp.Nodes' : {
        'meta_info' : _MetaInfoClass('Ntp.Nodes', REFERENCE_CLASS,
            '''Node-specific NTP operational data''',
            False, 
            [
            _MetaInfoClassMember('node', REFERENCE_LIST, 'Node', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_ip_ntp_oper', 'Ntp.Nodes.Node',
                [], [],
                '''                NTP operational data for a particular node
                ''',
                'node',
                'Cisco-IOS-XR-ip-ntp-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-ip-ntp-oper',
            'nodes',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-ip-ntp-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_ip_ntp_oper',
            is_config=False,
        ),
    },
    'Ntp' : {
        'meta_info' : _MetaInfoClass('Ntp', REFERENCE_CLASS,
            '''NTP operational data''',
            False, 
            [
            _MetaInfoClassMember('nodes', REFERENCE_CLASS, 'Nodes', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_ip_ntp_oper', 'Ntp.Nodes',
                [], [],
                '''                Node-specific NTP operational data
                ''',
                'nodes',
                'Cisco-IOS-XR-ip-ntp-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-ip-ntp-oper',
            'ntp',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-ip-ntp-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_ip_ntp_oper',
            is_config=False,
        ),
    },
}
_meta_table['Ntp.Nodes.Node.AssociationsDetail.PeerDetailInfo.RefTime.Sec']['meta_info'].parent =_meta_table['Ntp.Nodes.Node.AssociationsDetail.PeerDetailInfo.RefTime']['meta_info']
_meta_table['Ntp.Nodes.Node.AssociationsDetail.PeerDetailInfo.RefTime.FracSecs']['meta_info'].parent =_meta_table['Ntp.Nodes.Node.AssociationsDetail.PeerDetailInfo.RefTime']['meta_info']
_meta_table['Ntp.Nodes.Node.AssociationsDetail.PeerDetailInfo.OriginateTime.Sec']['meta_info'].parent =_meta_table['Ntp.Nodes.Node.AssociationsDetail.PeerDetailInfo.OriginateTime']['meta_info']
_meta_table['Ntp.Nodes.Node.AssociationsDetail.PeerDetailInfo.OriginateTime.FracSecs']['meta_info'].parent =_meta_table['Ntp.Nodes.Node.AssociationsDetail.PeerDetailInfo.OriginateTime']['meta_info']
_meta_table['Ntp.Nodes.Node.AssociationsDetail.PeerDetailInfo.ReceiveTime.Sec']['meta_info'].parent =_meta_table['Ntp.Nodes.Node.AssociationsDetail.PeerDetailInfo.ReceiveTime']['meta_info']
_meta_table['Ntp.Nodes.Node.AssociationsDetail.PeerDetailInfo.ReceiveTime.FracSecs']['meta_info'].parent =_meta_table['Ntp.Nodes.Node.AssociationsDetail.PeerDetailInfo.ReceiveTime']['meta_info']
_meta_table['Ntp.Nodes.Node.AssociationsDetail.PeerDetailInfo.TransmitTime.Sec']['meta_info'].parent =_meta_table['Ntp.Nodes.Node.AssociationsDetail.PeerDetailInfo.TransmitTime']['meta_info']
_meta_table['Ntp.Nodes.Node.AssociationsDetail.PeerDetailInfo.TransmitTime.FracSecs']['meta_info'].parent =_meta_table['Ntp.Nodes.Node.AssociationsDetail.PeerDetailInfo.TransmitTime']['meta_info']
_meta_table['Ntp.Nodes.Node.AssociationsDetail.PeerDetailInfo.PeerInfoCommon']['meta_info'].parent =_meta_table['Ntp.Nodes.Node.AssociationsDetail.PeerDetailInfo']['meta_info']
_meta_table['Ntp.Nodes.Node.AssociationsDetail.PeerDetailInfo.RefTime']['meta_info'].parent =_meta_table['Ntp.Nodes.Node.AssociationsDetail.PeerDetailInfo']['meta_info']
_meta_table['Ntp.Nodes.Node.AssociationsDetail.PeerDetailInfo.OriginateTime']['meta_info'].parent =_meta_table['Ntp.Nodes.Node.AssociationsDetail.PeerDetailInfo']['meta_info']
_meta_table['Ntp.Nodes.Node.AssociationsDetail.PeerDetailInfo.ReceiveTime']['meta_info'].parent =_meta_table['Ntp.Nodes.Node.AssociationsDetail.PeerDetailInfo']['meta_info']
_meta_table['Ntp.Nodes.Node.AssociationsDetail.PeerDetailInfo.TransmitTime']['meta_info'].parent =_meta_table['Ntp.Nodes.Node.AssociationsDetail.PeerDetailInfo']['meta_info']
_meta_table['Ntp.Nodes.Node.AssociationsDetail.PeerDetailInfo.FilterDetail']['meta_info'].parent =_meta_table['Ntp.Nodes.Node.AssociationsDetail.PeerDetailInfo']['meta_info']
_meta_table['Ntp.Nodes.Node.AssociationsDetail.PeerDetailInfo']['meta_info'].parent =_meta_table['Ntp.Nodes.Node.AssociationsDetail']['meta_info']
_meta_table['Ntp.Nodes.Node.Status.SysRefTime.Sec']['meta_info'].parent =_meta_table['Ntp.Nodes.Node.Status.SysRefTime']['meta_info']
_meta_table['Ntp.Nodes.Node.Status.SysRefTime.FracSecs']['meta_info'].parent =_meta_table['Ntp.Nodes.Node.Status.SysRefTime']['meta_info']
_meta_table['Ntp.Nodes.Node.Status.SysDrift.Sec']['meta_info'].parent =_meta_table['Ntp.Nodes.Node.Status.SysDrift']['meta_info']
_meta_table['Ntp.Nodes.Node.Status.SysDrift.FracSecs']['meta_info'].parent =_meta_table['Ntp.Nodes.Node.Status.SysDrift']['meta_info']
_meta_table['Ntp.Nodes.Node.Status.SysRefTime']['meta_info'].parent =_meta_table['Ntp.Nodes.Node.Status']['meta_info']
_meta_table['Ntp.Nodes.Node.Status.SysDrift']['meta_info'].parent =_meta_table['Ntp.Nodes.Node.Status']['meta_info']
_meta_table['Ntp.Nodes.Node.Associations.PeerSummaryInfo.PeerInfoCommon']['meta_info'].parent =_meta_table['Ntp.Nodes.Node.Associations.PeerSummaryInfo']['meta_info']
_meta_table['Ntp.Nodes.Node.Associations.PeerSummaryInfo']['meta_info'].parent =_meta_table['Ntp.Nodes.Node.Associations']['meta_info']
_meta_table['Ntp.Nodes.Node.AssociationsDetail']['meta_info'].parent =_meta_table['Ntp.Nodes.Node']['meta_info']
_meta_table['Ntp.Nodes.Node.Status']['meta_info'].parent =_meta_table['Ntp.Nodes.Node']['meta_info']
_meta_table['Ntp.Nodes.Node.Associations']['meta_info'].parent =_meta_table['Ntp.Nodes.Node']['meta_info']
_meta_table['Ntp.Nodes.Node']['meta_info'].parent =_meta_table['Ntp.Nodes']['meta_info']
_meta_table['Ntp.Nodes']['meta_info'].parent =_meta_table['Ntp']['meta_info']
