
'''
This is auto-generated file,
which includes metadata for module Cisco_IOS_XR_controller_odu_datatypes
'''

from ydk._core._dm_meta_info import _MetaInfoClassMember, _MetaInfoClass, _MetaInfoEnum
from ydk._core._dm_meta_info import ATTRIBUTE, REFERENCE_LIST, REFERENCE_LEAFLIST, REFERENCE_BITS, REFERENCE_UNION
from ydk._core._dm_meta_info import REFERENCE_CLASS, REFERENCE_IDENTITY_CLASS, REFERENCE_ENUM_CLASS, ANYXML_CLASS
from ydk._core._importer import _yang_ns

_meta_table = {
    'OtnChildControllerName' : _MetaInfoEnum('OtnChildControllerName',
        'ydk.models.cisco_ios_xr.Cisco_IOS_XR_controller_odu_datatypes', 'OtnChildControllerName',
        '''Otn child controller name''',
        {
            'odu1':'odu1',
            'odu2':'odu2',
            'odu3':'odu3',
            'odu0':'odu0',
            'odu2e':'odu2e',
            'odu1e':'odu1e',
            'odu2f':'odu2f',
            'odu3e1':'odu3e1',
            'odu3e2':'odu3e2',
        }, 'Cisco-IOS-XR-controller-odu-datatypes', _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-controller-odu-datatypes']),
    'OtnChildFlexControllerName' : _MetaInfoEnum('OtnChildFlexControllerName',
        'ydk.models.cisco_ios_xr.Cisco_IOS_XR_controller_odu_datatypes', 'OtnChildFlexControllerName',
        '''Otn child flex controller name''',
        {
            'odu-flex':'odu_flex',
        }, 'Cisco-IOS-XR-controller-odu-datatypes', _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-controller-odu-datatypes']),
    'OtnFlexMapping' : _MetaInfoEnum('OtnFlexMapping',
        'ydk.models.cisco_ios_xr.Cisco_IOS_XR_controller_odu_datatypes', 'OtnFlexMapping',
        '''Otn flex mapping''',
        {
            'gfp-f-fixed':'gfp_f_fixed',
            'gfp-resizable':'gfp_resizable',
            'cbr':'cbr',
        }, 'Cisco-IOS-XR-controller-odu-datatypes', _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-controller-odu-datatypes']),
    'OtntcmMode' : _MetaInfoEnum('OtntcmMode',
        'ydk.models.cisco_ios_xr.Cisco_IOS_XR_controller_odu_datatypes', 'OtntcmMode',
        '''Otntcm mode''',
        {
            'transparent':'transparent',
            'nim':'nim',
            'operational':'operational',
        }, 'Cisco-IOS-XR-controller-odu-datatypes', _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-controller-odu-datatypes']),
    'OtnPerMon' : _MetaInfoEnum('OtnPerMon',
        'ydk.models.cisco_ios_xr.Cisco_IOS_XR_controller_odu_datatypes', 'OtnPerMon',
        '''Otn per mon''',
        {
            'disable':'disable',
            'enable':'enable',
        }, 'Cisco-IOS-XR-controller-odu-datatypes', _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-controller-odu-datatypes']),
    'OduPrbsMode' : _MetaInfoEnum('OduPrbsMode',
        'ydk.models.cisco_ios_xr.Cisco_IOS_XR_controller_odu_datatypes', 'OduPrbsMode',
        '''Odu prbs mode''',
        {
            'mode-invalid':'mode_invalid',
            'mode-source':'mode_source',
            'mode-sink':'mode_sink',
            'mode-source-sink':'mode_source_sink',
        }, 'Cisco-IOS-XR-controller-odu-datatypes', _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-controller-odu-datatypes']),
    'OduTimeSlotGranularity' : _MetaInfoEnum('OduTimeSlotGranularity',
        'ydk.models.cisco_ios_xr.Cisco_IOS_XR_controller_odu_datatypes', 'OduTimeSlotGranularity',
        '''Odu time slot granularity''',
        {
            '1.25g':'Y_1__DOT__25g',
            '2.5g':'Y_2__DOT__5g',
        }, 'Cisco-IOS-XR-controller-odu-datatypes', _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-controller-odu-datatypes']),
    'OtnSendTtiTypeOs' : _MetaInfoEnum('OtnSendTtiTypeOs',
        'ydk.models.cisco_ios_xr.Cisco_IOS_XR_controller_odu_datatypes', 'OtnSendTtiTypeOs',
        '''Otn send tti type os''',
        {
            'send-tti-os-ascii/os-ascii':'send_tti_os_ascii__FWD_SLASH__os_ascii',
            'send-tti-os-hex/os-hex':'send_tti_os_hex__FWD_SLASH__os_hex',
        }, 'Cisco-IOS-XR-controller-odu-datatypes', _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-controller-odu-datatypes']),
    'OtnExpTtiTypeSapi' : _MetaInfoEnum('OtnExpTtiTypeSapi',
        'ydk.models.cisco_ios_xr.Cisco_IOS_XR_controller_odu_datatypes', 'OtnExpTtiTypeSapi',
        '''Otn exp tti type sapi''',
        {
            'exp-tti-sapi-ascii/sapi-ascii':'exp_tti_sapi_ascii__FWD_SLASH__sapi_ascii',
        }, 'Cisco-IOS-XR-controller-odu-datatypes', _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-controller-odu-datatypes']),
    'OtnTermination' : _MetaInfoEnum('OtnTermination',
        'ydk.models.cisco_ios_xr.Cisco_IOS_XR_controller_odu_datatypes', 'OtnTermination',
        '''Otn termination''',
        {
            'ether':'ether',
        }, 'Cisco-IOS-XR-controller-odu-datatypes', _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-controller-odu-datatypes']),
    'OtnSendTtiTypeSapi' : _MetaInfoEnum('OtnSendTtiTypeSapi',
        'ydk.models.cisco_ios_xr.Cisco_IOS_XR_controller_odu_datatypes', 'OtnSendTtiTypeSapi',
        '''Otn send tti type sapi''',
        {
            'send-tti-sapi-ascii/sapi-ascii':'send_tti_sapi_ascii__FWD_SLASH__sapi_ascii',
        }, 'Cisco-IOS-XR-controller-odu-datatypes', _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-controller-odu-datatypes']),
    'OtnSecAdminState' : _MetaInfoEnum('OtnSecAdminState',
        'ydk.models.cisco_ios_xr.Cisco_IOS_XR_controller_odu_datatypes', 'OtnSecAdminState',
        '''Otn sec admin state''',
        {
            'normal':'normal',
            'maintenance':'maintenance',
        }, 'Cisco-IOS-XR-controller-odu-datatypes', _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-controller-odu-datatypes']),
    'OtnMapping' : _MetaInfoEnum('OtnMapping',
        'ydk.models.cisco_ios_xr.Cisco_IOS_XR_controller_odu_datatypes', 'OtnMapping',
        '''Otn mapping''',
        {
            'gfp-f':'gfp_f',
            'bmp':'bmp',
            'gmp':'gmp',
            'gfp-f-ext':'gfp_f_ext',
        }, 'Cisco-IOS-XR-controller-odu-datatypes', _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-controller-odu-datatypes']),
    'OtnExpTtiTypeOs' : _MetaInfoEnum('OtnExpTtiTypeOs',
        'ydk.models.cisco_ios_xr.Cisco_IOS_XR_controller_odu_datatypes', 'OtnExpTtiTypeOs',
        '''Otn exp tti type os''',
        {
            'exp-tti-os-ascii/os-ascii':'exp_tti_os_ascii__FWD_SLASH__os_ascii',
            'exp-tti-os-hex/os-hex':'exp_tti_os_hex__FWD_SLASH__os_hex',
        }, 'Cisco-IOS-XR-controller-odu-datatypes', _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-controller-odu-datatypes']),
    'OduDelay' : _MetaInfoEnum('OduDelay',
        'ydk.models.cisco_ios_xr.Cisco_IOS_XR_controller_odu_datatypes', 'OduDelay',
        '''Odu delay''',
        {
            'disable':'disable',
            'enable':'enable',
        }, 'Cisco-IOS-XR-controller-odu-datatypes', _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-controller-odu-datatypes']),
    'OtnLoopback' : _MetaInfoEnum('OtnLoopback',
        'ydk.models.cisco_ios_xr.Cisco_IOS_XR_controller_odu_datatypes', 'OtnLoopback',
        '''Otn loopback''',
        {
            'line':'line',
            'internal':'internal',
        }, 'Cisco-IOS-XR-controller-odu-datatypes', _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-controller-odu-datatypes']),
    'OtnExpTtiTypeFull' : _MetaInfoEnum('OtnExpTtiTypeFull',
        'ydk.models.cisco_ios_xr.Cisco_IOS_XR_controller_odu_datatypes', 'OtnExpTtiTypeFull',
        '''Otn exp tti type full''',
        {
            'exp-tti-full-ascii/full-ascii':'exp_tti_full_ascii__FWD_SLASH__full_ascii',
            'exp-tti-hex/hex':'exp_tti_hex__FWD_SLASH__hex',
        }, 'Cisco-IOS-XR-controller-odu-datatypes', _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-controller-odu-datatypes']),
    'OtnSendTtiTypeFull' : _MetaInfoEnum('OtnSendTtiTypeFull',
        'ydk.models.cisco_ios_xr.Cisco_IOS_XR_controller_odu_datatypes', 'OtnSendTtiTypeFull',
        '''Otn send tti type full''',
        {
            'send-tti-full-ascii/full-ascii':'send_tti_full_ascii__FWD_SLASH__full_ascii',
            'send-tti-hex/hex':'send_tti_hex__FWD_SLASH__hex',
        }, 'Cisco-IOS-XR-controller-odu-datatypes', _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-controller-odu-datatypes']),
    'OtnExpTtiTypeDapi' : _MetaInfoEnum('OtnExpTtiTypeDapi',
        'ydk.models.cisco_ios_xr.Cisco_IOS_XR_controller_odu_datatypes', 'OtnExpTtiTypeDapi',
        '''Otn exp tti type dapi''',
        {
            'exp-tti-dapi-ascii/dapi-ascii':'exp_tti_dapi_ascii__FWD_SLASH__dapi_ascii',
        }, 'Cisco-IOS-XR-controller-odu-datatypes', _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-controller-odu-datatypes']),
    'OtnSendTtiTypeDapi' : _MetaInfoEnum('OtnSendTtiTypeDapi',
        'ydk.models.cisco_ios_xr.Cisco_IOS_XR_controller_odu_datatypes', 'OtnSendTtiTypeDapi',
        '''Otn send tti type dapi''',
        {
            'send-tti-dapi-ascii/dapi-ascii':'send_tti_dapi_ascii__FWD_SLASH__dapi_ascii',
        }, 'Cisco-IOS-XR-controller-odu-datatypes', _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-controller-odu-datatypes']),
    'Otntcmca' : _MetaInfoEnum('Otntcmca',
        'ydk.models.cisco_ios_xr.Cisco_IOS_XR_controller_odu_datatypes', 'Otntcmca',
        '''Otntcmca''',
        {
            'disable':'disable',
            'enable':'enable',
        }, 'Cisco-IOS-XR-controller-odu-datatypes', _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-controller-odu-datatypes']),
    'Pattern' : _MetaInfoEnum('Pattern',
        'ydk.models.cisco_ios_xr.Cisco_IOS_XR_controller_odu_datatypes', 'Pattern',
        '''Pattern''',
        {
            'pattern-none':'pattern_none',
            'pattern-pn31':'pattern_pn31',
            'pattern-pn23':'pattern_pn23',
            'pattern-pn11':'pattern_pn11',
            'pattern-inverted-pn31':'pattern_inverted_pn31',
            'pattern-inverted-pn11':'pattern_inverted_pn11',
        }, 'Cisco-IOS-XR-controller-odu-datatypes', _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-controller-odu-datatypes']),
    'Otnpmtimca' : _MetaInfoEnum('Otnpmtimca',
        'ydk.models.cisco_ios_xr.Cisco_IOS_XR_controller_odu_datatypes', 'Otnpmtimca',
        '''Otnpmtimca''',
        {
            'disable':'disable',
            'enable':'enable',
        }, 'Cisco-IOS-XR-controller-odu-datatypes', _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-controller-odu-datatypes']),
}
