
'''
This is auto-generated file,
which includes metadata for module Cisco_IOS_XR_man_ems_oper
'''

from ydk._core._dm_meta_info import _MetaInfoClassMember, _MetaInfoClass, _MetaInfoEnum
from ydk._core._dm_meta_info import ATTRIBUTE, REFERENCE_LIST, REFERENCE_LEAFLIST, REFERENCE_BITS, REFERENCE_UNION
from ydk._core._dm_meta_info import REFERENCE_CLASS, REFERENCE_IDENTITY_CLASS, REFERENCE_ENUM_CLASS, ANYXML_CLASS
from ydk._core._importer import _yang_ns

_meta_table = {
    'Grpc.Statistics' : {
        'meta_info' : _MetaInfoClass('Grpc.Statistics', REFERENCE_CLASS,
            '''Grpc Statistics''',
            False, 
            [
            _MetaInfoClassMember('ct-show-cmd-txt-req-recv', ATTRIBUTE, 'int', 'uint64',
                None, None,
                [('0', '18446744073709551615')], [],
                '''                CounterShowCmdTxtReqRecv
                ''',
                'ct_show_cmd_txt_req_recv',
                'Cisco-IOS-XR-man-ems-oper', False, is_config=False),
            _MetaInfoClassMember('ct-show-cmd-txt-res-sent', ATTRIBUTE, 'int', 'uint64',
                None, None,
                [('0', '18446744073709551615')], [],
                '''                CounterShowCmdTxtResSent
                ''',
                'ct_show_cmd_txt_res_sent',
                'Cisco-IOS-XR-man-ems-oper', False, is_config=False),
            _MetaInfoClassMember('ct-get-config-req-recv', ATTRIBUTE, 'int', 'uint64',
                None, None,
                [('0', '18446744073709551615')], [],
                '''                CounterGetConfigReqRecv
                ''',
                'ct_get_config_req_recv',
                'Cisco-IOS-XR-man-ems-oper', False, is_config=False),
            _MetaInfoClassMember('ct-get-config-res-sent', ATTRIBUTE, 'int', 'uint64',
                None, None,
                [('0', '18446744073709551615')], [],
                '''                CounterGetConfigResSent
                ''',
                'ct_get_config_res_sent',
                'Cisco-IOS-XR-man-ems-oper', False, is_config=False),
            _MetaInfoClassMember('ct-cli-config-req-recv', ATTRIBUTE, 'int', 'uint64',
                None, None,
                [('0', '18446744073709551615')], [],
                '''                CounterCliConfigReqRecv
                ''',
                'ct_cli_config_req_recv',
                'Cisco-IOS-XR-man-ems-oper', False, is_config=False),
            _MetaInfoClassMember('ct-cli-config-res-sent', ATTRIBUTE, 'int', 'uint64',
                None, None,
                [('0', '18446744073709551615')], [],
                '''                CounterCliConfigResSent
                ''',
                'ct_cli_config_res_sent',
                'Cisco-IOS-XR-man-ems-oper', False, is_config=False),
            _MetaInfoClassMember('ct-merge-config-req-recv', ATTRIBUTE, 'int', 'uint64',
                None, None,
                [('0', '18446744073709551615')], [],
                '''                CounterMergeConfigReq
                ''',
                'ct_merge_config_req_recv',
                'Cisco-IOS-XR-man-ems-oper', False, is_config=False),
            _MetaInfoClassMember('ct-merge-config-res-sent', ATTRIBUTE, 'int', 'uint64',
                None, None,
                [('0', '18446744073709551615')], [],
                '''                CounterMergeConfigRes
                ''',
                'ct_merge_config_res_sent',
                'Cisco-IOS-XR-man-ems-oper', False, is_config=False),
            _MetaInfoClassMember('ct-commit-replace-req-recv', ATTRIBUTE, 'int', 'uint64',
                None, None,
                [('0', '18446744073709551615')], [],
                '''                CounterCommitReplaceReq
                ''',
                'ct_commit_replace_req_recv',
                'Cisco-IOS-XR-man-ems-oper', False, is_config=False),
            _MetaInfoClassMember('ct-commit-replace-res-sent', ATTRIBUTE, 'int', 'uint64',
                None, None,
                [('0', '18446744073709551615')], [],
                '''                CounterCommitReplaceRes
                ''',
                'ct_commit_replace_res_sent',
                'Cisco-IOS-XR-man-ems-oper', False, is_config=False),
            _MetaInfoClassMember('ct-delete-config-req-recv', ATTRIBUTE, 'int', 'uint64',
                None, None,
                [('0', '18446744073709551615')], [],
                '''                CounterDeleteConfigReq
                ''',
                'ct_delete_config_req_recv',
                'Cisco-IOS-XR-man-ems-oper', False, is_config=False),
            _MetaInfoClassMember('ct-delete-config-res-sent', ATTRIBUTE, 'int', 'uint64',
                None, None,
                [('0', '18446744073709551615')], [],
                '''                CounterDeleteConfigRes
                ''',
                'ct_delete_config_res_sent',
                'Cisco-IOS-XR-man-ems-oper', False, is_config=False),
            _MetaInfoClassMember('ct-replace-config-req-recv', ATTRIBUTE, 'int', 'uint64',
                None, None,
                [('0', '18446744073709551615')], [],
                '''                CounterReplaceConfigReq
                ''',
                'ct_replace_config_req_recv',
                'Cisco-IOS-XR-man-ems-oper', False, is_config=False),
            _MetaInfoClassMember('ct-replace-config-res-sent', ATTRIBUTE, 'int', 'uint64',
                None, None,
                [('0', '18446744073709551615')], [],
                '''                CounterReplaceConfigSent
                ''',
                'ct_replace_config_res_sent',
                'Cisco-IOS-XR-man-ems-oper', False, is_config=False),
            _MetaInfoClassMember('ct-get-oper-req-recv', ATTRIBUTE, 'int', 'uint64',
                None, None,
                [('0', '18446744073709551615')], [],
                '''                CounterGetOperReqRecv
                ''',
                'ct_get_oper_req_recv',
                'Cisco-IOS-XR-man-ems-oper', False, is_config=False),
            _MetaInfoClassMember('ct-get-oper-res-sent', ATTRIBUTE, 'int', 'uint64',
                None, None,
                [('0', '18446744073709551615')], [],
                '''                CounterGetOperResSent
                ''',
                'ct_get_oper_res_sent',
                'Cisco-IOS-XR-man-ems-oper', False, is_config=False),
            _MetaInfoClassMember('ct-get-current-session', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                CounterGetCurrentSession
                ''',
                'ct_get_current_session',
                'Cisco-IOS-XR-man-ems-oper', False, is_config=False),
            _MetaInfoClassMember('ct-commit-config-req-recv', ATTRIBUTE, 'int', 'uint64',
                None, None,
                [('0', '18446744073709551615')], [],
                '''                CounterForHowManyCommitConfigRequests
                ''',
                'ct_commit_config_req_recv',
                'Cisco-IOS-XR-man-ems-oper', False, is_config=False),
            _MetaInfoClassMember('ct-commit-config-res-sent', ATTRIBUTE, 'int', 'uint64',
                None, None,
                [('0', '18446744073709551615')], [],
                '''                CounterForHowManyCommitConfigResponses
                ''',
                'ct_commit_config_res_sent',
                'Cisco-IOS-XR-man-ems-oper', False, is_config=False),
            _MetaInfoClassMember('ct-action-json-req-recv', ATTRIBUTE, 'int', 'uint64',
                None, None,
                [('0', '18446744073709551615')], [],
                '''                CounterForHowManyActionJsonRequests
                ''',
                'ct_action_json_req_recv',
                'Cisco-IOS-XR-man-ems-oper', False, is_config=False),
            _MetaInfoClassMember('ct-action-json-res-sent', ATTRIBUTE, 'int', 'uint64',
                None, None,
                [('0', '18446744073709551615')], [],
                '''                CounterForHowManyActionJsonResponses
                ''',
                'ct_action_json_res_sent',
                'Cisco-IOS-XR-man-ems-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-man-ems-oper',
            'statistics',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-man-ems-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_man_ems_oper',
            is_config=False,
        ),
    },
    'Grpc.Status' : {
        'meta_info' : _MetaInfoClass('Grpc.Status', REFERENCE_CLASS,
            '''Grpc Status''',
            False, 
            [
            _MetaInfoClassMember('transport', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                GRPCTransport
                ''',
                'transport',
                'Cisco-IOS-XR-man-ems-oper', False, is_config=False),
            _MetaInfoClassMember('address-family', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                AddressFamily
                ''',
                'address_family',
                'Cisco-IOS-XR-man-ems-oper', False, is_config=False),
            _MetaInfoClassMember('tls', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                GRPCTLS
                ''',
                'tls',
                'Cisco-IOS-XR-man-ems-oper', False, is_config=False),
            _MetaInfoClassMember('trustpoint', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                GRPCTrustpoint
                ''',
                'trustpoint',
                'Cisco-IOS-XR-man-ems-oper', False, is_config=False),
            _MetaInfoClassMember('listening-port', ATTRIBUTE, 'int', 'int32',
                None, None,
                [('-2147483648', '2147483647')], [],
                '''                ListeningPort
                ''',
                'listening_port',
                'Cisco-IOS-XR-man-ems-oper', False, is_config=False),
            _MetaInfoClassMember('vrf-socket-ns-path', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                VrfSocketNamespacePath
                ''',
                'vrf_socket_ns_path',
                'Cisco-IOS-XR-man-ems-oper', False, is_config=False),
            _MetaInfoClassMember('max-req-per-user', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                MaxReqPerUser
                ''',
                'max_req_per_user',
                'Cisco-IOS-XR-man-ems-oper', False, is_config=False),
            _MetaInfoClassMember('max-req-total', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                MaxReqTotal
                ''',
                'max_req_total',
                'Cisco-IOS-XR-man-ems-oper', False, is_config=False),
            _MetaInfoClassMember('max-streams', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                Maximum number of streaming gRPCs
                ''',
                'max_streams',
                'Cisco-IOS-XR-man-ems-oper', False, is_config=False),
            _MetaInfoClassMember('max-streams-per-user', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                Maximum number of streaming gRPCs per user
                ''',
                'max_streams_per_user',
                'Cisco-IOS-XR-man-ems-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-man-ems-oper',
            'status',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-man-ems-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_man_ems_oper',
            is_config=False,
        ),
    },
    'Grpc' : {
        'meta_info' : _MetaInfoClass('Grpc', REFERENCE_CLASS,
            '''grpc commands''',
            False, 
            [
            _MetaInfoClassMember('statistics', REFERENCE_CLASS, 'Statistics', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_man_ems_oper', 'Grpc.Statistics',
                [], [],
                '''                Grpc Statistics
                ''',
                'statistics',
                'Cisco-IOS-XR-man-ems-oper', False, is_config=False),
            _MetaInfoClassMember('status', REFERENCE_CLASS, 'Status', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_man_ems_oper', 'Grpc.Status',
                [], [],
                '''                Grpc Status
                ''',
                'status',
                'Cisco-IOS-XR-man-ems-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-man-ems-oper',
            'grpc',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-man-ems-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_man_ems_oper',
            is_config=False,
        ),
    },
}
_meta_table['Grpc.Statistics']['meta_info'].parent =_meta_table['Grpc']['meta_info']
_meta_table['Grpc.Status']['meta_info'].parent =_meta_table['Grpc']['meta_info']
