
'''
This is auto-generated file,
which includes metadata for module Cisco_IOS_XR_flowspec_oper
'''

from ydk._core._dm_meta_info import _MetaInfoClassMember, _MetaInfoClass, _MetaInfoEnum
from ydk._core._dm_meta_info import ATTRIBUTE, REFERENCE_LIST, REFERENCE_LEAFLIST, REFERENCE_BITS, REFERENCE_UNION
from ydk._core._dm_meta_info import REFERENCE_CLASS, REFERENCE_IDENTITY_CLASS, REFERENCE_ENUM_CLASS, ANYXML_CLASS
from ydk._core._importer import _yang_ns

_meta_table = {
    'FsClient' : _MetaInfoEnum('FsClient',
        'ydk.models.cisco_ios_xr.Cisco_IOS_XR_flowspec_oper', 'FsClient',
        '''Fs client''',
        {
            'bgp':'bgp',
            'one-pk':'one_pk',
            'policy':'policy',
            'ha':'ha',
            'test':'test',
        }, 'Cisco-IOS-XR-flowspec-oper', _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-flowspec-oper']),
    'FsMgrClientState' : _MetaInfoEnum('FsMgrClientState',
        'ydk.models.cisco_ios_xr.Cisco_IOS_XR_flowspec_oper', 'FsMgrClientState',
        '''FlowSpec manager client state''',
        {
            'dormant':'dormant',
            'connected':'connected',
            'replay':'replay',
            'unconfigured':'unconfigured',
        }, 'Cisco-IOS-XR-flowspec-oper', _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-flowspec-oper']),
    'FlowSpec.Clients.Client' : {
        'meta_info' : _MetaInfoClass('FlowSpec.Clients.Client', REFERENCE_LIST,
            '''FlowSpec client information''',
            False, 
            [
            _MetaInfoClassMember('client-type', REFERENCE_ENUM_CLASS, 'FsClient', 'Fs-client',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_flowspec_oper', 'FsClient',
                [], [],
                '''                FlowSpec Client Type
                ''',
                'client_type',
                'Cisco-IOS-XR-flowspec-oper', False, is_config=False),
            _MetaInfoClassMember('client-id', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                FlowSpec client ID
                ''',
                'client_id',
                'Cisco-IOS-XR-flowspec-oper', False, is_config=False),
            _MetaInfoClassMember('client-state', REFERENCE_ENUM_CLASS, 'FsMgrClientState', 'Fs-mgr-client-state',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_flowspec_oper', 'FsMgrClientState',
                [], [],
                '''                State of FS client
                ''',
                'client_state',
                'Cisco-IOS-XR-flowspec-oper', False, is_config=False),
            _MetaInfoClassMember('client-flows', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                Number of client flows
                ''',
                'client_flows',
                'Cisco-IOS-XR-flowspec-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-flowspec-oper',
            'client',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-flowspec-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_flowspec_oper',
            is_config=False,
        ),
    },
    'FlowSpec.Clients' : {
        'meta_info' : _MetaInfoClass('FlowSpec.Clients', REFERENCE_CLASS,
            '''Table of Client''',
            False, 
            [
            _MetaInfoClassMember('client', REFERENCE_LIST, 'Client', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_flowspec_oper', 'FlowSpec.Clients.Client',
                [], [],
                '''                FlowSpec client information
                ''',
                'client',
                'Cisco-IOS-XR-flowspec-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-flowspec-oper',
            'clients',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-flowspec-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_flowspec_oper',
            is_config=False,
        ),
    },
    'FlowSpec.Summary' : {
        'meta_info' : _MetaInfoClass('FlowSpec.Summary', REFERENCE_CLASS,
            '''FlowSpec summary''',
            False, 
            [
            _MetaInfoClassMember('vrfafi-tables', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                Total VRF+AFI tables
                ''',
                'vrfafi_tables',
                'Cisco-IOS-XR-flowspec-oper', False, is_config=False),
            _MetaInfoClassMember('flows', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                Total flows
                ''',
                'flows',
                'Cisco-IOS-XR-flowspec-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-flowspec-oper',
            'summary',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-flowspec-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_flowspec_oper',
            is_config=False,
        ),
    },
    'FlowSpec.Vrfs.Vrf.Afs.Af.TableSummary' : {
        'meta_info' : _MetaInfoClass('FlowSpec.Vrfs.Vrf.Afs.Af.TableSummary', REFERENCE_CLASS,
            '''FlowSpec summary for VRF+AFI tables''',
            False, 
            [
            _MetaInfoClassMember('total-flows', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                Total number of flows
                ''',
                'total_flows',
                'Cisco-IOS-XR-flowspec-oper', False, is_config=False),
            _MetaInfoClassMember('service-policies', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                Total number of attached service policies
                ''',
                'service_policies',
                'Cisco-IOS-XR-flowspec-oper', False, is_config=False),
            _MetaInfoClassMember('local-install-enabled', ATTRIBUTE, 'bool', 'boolean',
                None, None,
                [], [],
                '''                Local installation of flowspec rules
                ''',
                'local_install_enabled',
                'Cisco-IOS-XR-flowspec-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-flowspec-oper',
            'table-summary',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-flowspec-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_flowspec_oper',
            is_config=False,
        ),
    },
    'FlowSpec.Vrfs.Vrf.Afs.Af.Nlris.Nlri.FlowStatistics.Classified' : {
        'meta_info' : _MetaInfoClass('FlowSpec.Vrfs.Vrf.Afs.Af.Nlris.Nlri.FlowStatistics.Classified', REFERENCE_CLASS,
            '''Classified statistics''',
            False, 
            [
            _MetaInfoClassMember('packets', ATTRIBUTE, 'int', 'uint64',
                None, None,
                [('0', '18446744073709551615')], [],
                '''                Number of packets
                ''',
                'packets',
                'Cisco-IOS-XR-flowspec-oper', False, is_config=False),
            _MetaInfoClassMember('bytes', ATTRIBUTE, 'int', 'uint64',
                None, None,
                [('0', '18446744073709551615')], [],
                '''                Number of bytes
                ''',
                'bytes',
                'Cisco-IOS-XR-flowspec-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-flowspec-oper',
            'classified',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-flowspec-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_flowspec_oper',
            is_config=False,
        ),
    },
    'FlowSpec.Vrfs.Vrf.Afs.Af.Nlris.Nlri.FlowStatistics.Dropped' : {
        'meta_info' : _MetaInfoClass('FlowSpec.Vrfs.Vrf.Afs.Af.Nlris.Nlri.FlowStatistics.Dropped', REFERENCE_CLASS,
            '''Drop statistics''',
            False, 
            [
            _MetaInfoClassMember('packets', ATTRIBUTE, 'int', 'uint64',
                None, None,
                [('0', '18446744073709551615')], [],
                '''                Number of packets
                ''',
                'packets',
                'Cisco-IOS-XR-flowspec-oper', False, is_config=False),
            _MetaInfoClassMember('bytes', ATTRIBUTE, 'int', 'uint64',
                None, None,
                [('0', '18446744073709551615')], [],
                '''                Number of bytes
                ''',
                'bytes',
                'Cisco-IOS-XR-flowspec-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-flowspec-oper',
            'dropped',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-flowspec-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_flowspec_oper',
            is_config=False,
        ),
    },
    'FlowSpec.Vrfs.Vrf.Afs.Af.Nlris.Nlri.FlowStatistics' : {
        'meta_info' : _MetaInfoClass('FlowSpec.Vrfs.Vrf.Afs.Af.Nlris.Nlri.FlowStatistics', REFERENCE_CLASS,
            '''Flow statistics''',
            False, 
            [
            _MetaInfoClassMember('classified', REFERENCE_CLASS, 'Classified', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_flowspec_oper', 'FlowSpec.Vrfs.Vrf.Afs.Af.Nlris.Nlri.FlowStatistics.Classified',
                [], [],
                '''                Classified statistics
                ''',
                'classified',
                'Cisco-IOS-XR-flowspec-oper', False, is_config=False),
            _MetaInfoClassMember('dropped', REFERENCE_CLASS, 'Dropped', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_flowspec_oper', 'FlowSpec.Vrfs.Vrf.Afs.Af.Nlris.Nlri.FlowStatistics.Dropped',
                [], [],
                '''                Drop statistics
                ''',
                'dropped',
                'Cisco-IOS-XR-flowspec-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-flowspec-oper',
            'flow-statistics',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-flowspec-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_flowspec_oper',
            is_config=False,
        ),
    },
    'FlowSpec.Vrfs.Vrf.Afs.Af.Nlris.Nlri' : {
        'meta_info' : _MetaInfoClass('FlowSpec.Vrfs.Vrf.Afs.Af.Nlris.Nlri', REFERENCE_LIST,
            '''NLRI information (hexdump)''',
            False, 
            [
            _MetaInfoClassMember('nlri-bytes', ATTRIBUTE, 'str', 'xr:Cisco-ios-xr-string',
                None, None,
                [], [b'[\\w\\-\\.:,_@#%$\\+=\\|;]+'],
                '''                Enter NLRI hex string
                ''',
                'nlri_bytes',
                'Cisco-IOS-XR-flowspec-oper', True, is_config=False),
            _MetaInfoClassMember('flow-statistics', REFERENCE_CLASS, 'FlowStatistics', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_flowspec_oper', 'FlowSpec.Vrfs.Vrf.Afs.Af.Nlris.Nlri.FlowStatistics',
                [], [],
                '''                Flow statistics
                ''',
                'flow_statistics',
                'Cisco-IOS-XR-flowspec-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-flowspec-oper',
            'nlri',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-flowspec-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_flowspec_oper',
            is_config=False,
        ),
    },
    'FlowSpec.Vrfs.Vrf.Afs.Af.Nlris' : {
        'meta_info' : _MetaInfoClass('FlowSpec.Vrfs.Vrf.Afs.Af.Nlris', REFERENCE_CLASS,
            '''Table of NLRI''',
            False, 
            [
            _MetaInfoClassMember('nlri', REFERENCE_LIST, 'Nlri', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_flowspec_oper', 'FlowSpec.Vrfs.Vrf.Afs.Af.Nlris.Nlri',
                [], [],
                '''                NLRI information (hexdump)
                ''',
                'nlri',
                'Cisco-IOS-XR-flowspec-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-flowspec-oper',
            'nlris',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-flowspec-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_flowspec_oper',
            is_config=False,
        ),
    },
    'FlowSpec.Vrfs.Vrf.Afs.Af.Flows.Flow.FlowStatistics.Classified' : {
        'meta_info' : _MetaInfoClass('FlowSpec.Vrfs.Vrf.Afs.Af.Flows.Flow.FlowStatistics.Classified', REFERENCE_CLASS,
            '''Classified statistics''',
            False, 
            [
            _MetaInfoClassMember('packets', ATTRIBUTE, 'int', 'uint64',
                None, None,
                [('0', '18446744073709551615')], [],
                '''                Number of packets
                ''',
                'packets',
                'Cisco-IOS-XR-flowspec-oper', False, is_config=False),
            _MetaInfoClassMember('bytes', ATTRIBUTE, 'int', 'uint64',
                None, None,
                [('0', '18446744073709551615')], [],
                '''                Number of bytes
                ''',
                'bytes',
                'Cisco-IOS-XR-flowspec-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-flowspec-oper',
            'classified',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-flowspec-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_flowspec_oper',
            is_config=False,
        ),
    },
    'FlowSpec.Vrfs.Vrf.Afs.Af.Flows.Flow.FlowStatistics.Dropped' : {
        'meta_info' : _MetaInfoClass('FlowSpec.Vrfs.Vrf.Afs.Af.Flows.Flow.FlowStatistics.Dropped', REFERENCE_CLASS,
            '''Drop statistics''',
            False, 
            [
            _MetaInfoClassMember('packets', ATTRIBUTE, 'int', 'uint64',
                None, None,
                [('0', '18446744073709551615')], [],
                '''                Number of packets
                ''',
                'packets',
                'Cisco-IOS-XR-flowspec-oper', False, is_config=False),
            _MetaInfoClassMember('bytes', ATTRIBUTE, 'int', 'uint64',
                None, None,
                [('0', '18446744073709551615')], [],
                '''                Number of bytes
                ''',
                'bytes',
                'Cisco-IOS-XR-flowspec-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-flowspec-oper',
            'dropped',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-flowspec-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_flowspec_oper',
            is_config=False,
        ),
    },
    'FlowSpec.Vrfs.Vrf.Afs.Af.Flows.Flow.FlowStatistics' : {
        'meta_info' : _MetaInfoClass('FlowSpec.Vrfs.Vrf.Afs.Af.Flows.Flow.FlowStatistics', REFERENCE_CLASS,
            '''Flow statistics''',
            False, 
            [
            _MetaInfoClassMember('classified', REFERENCE_CLASS, 'Classified', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_flowspec_oper', 'FlowSpec.Vrfs.Vrf.Afs.Af.Flows.Flow.FlowStatistics.Classified',
                [], [],
                '''                Classified statistics
                ''',
                'classified',
                'Cisco-IOS-XR-flowspec-oper', False, is_config=False),
            _MetaInfoClassMember('dropped', REFERENCE_CLASS, 'Dropped', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_flowspec_oper', 'FlowSpec.Vrfs.Vrf.Afs.Af.Flows.Flow.FlowStatistics.Dropped',
                [], [],
                '''                Drop statistics
                ''',
                'dropped',
                'Cisco-IOS-XR-flowspec-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-flowspec-oper',
            'flow-statistics',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-flowspec-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_flowspec_oper',
            is_config=False,
        ),
    },
    'FlowSpec.Vrfs.Vrf.Afs.Af.Flows.Flow' : {
        'meta_info' : _MetaInfoClass('FlowSpec.Vrfs.Vrf.Afs.Af.Flows.Flow', REFERENCE_LIST,
            '''Flow notation string''',
            False, 
            [
            _MetaInfoClassMember('flow-notation', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Enter the Flow notation string
                ''',
                'flow_notation',
                'Cisco-IOS-XR-flowspec-oper', True, is_config=False),
            _MetaInfoClassMember('flow-statistics', REFERENCE_CLASS, 'FlowStatistics', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_flowspec_oper', 'FlowSpec.Vrfs.Vrf.Afs.Af.Flows.Flow.FlowStatistics',
                [], [],
                '''                Flow statistics
                ''',
                'flow_statistics',
                'Cisco-IOS-XR-flowspec-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-flowspec-oper',
            'flow',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-flowspec-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_flowspec_oper',
            is_config=False,
        ),
    },
    'FlowSpec.Vrfs.Vrf.Afs.Af.Flows' : {
        'meta_info' : _MetaInfoClass('FlowSpec.Vrfs.Vrf.Afs.Af.Flows', REFERENCE_CLASS,
            '''Table of Flow''',
            False, 
            [
            _MetaInfoClassMember('flow', REFERENCE_LIST, 'Flow', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_flowspec_oper', 'FlowSpec.Vrfs.Vrf.Afs.Af.Flows.Flow',
                [], [],
                '''                Flow notation string
                ''',
                'flow',
                'Cisco-IOS-XR-flowspec-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-flowspec-oper',
            'flows',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-flowspec-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_flowspec_oper',
            is_config=False,
        ),
    },
    'FlowSpec.Vrfs.Vrf.Afs.Af' : {
        'meta_info' : _MetaInfoClass('FlowSpec.Vrfs.Vrf.Afs.Af', REFERENCE_LIST,
            '''AFI Type (IPv4/IPv6)''',
            False, 
            [
            _MetaInfoClassMember('af-name', ATTRIBUTE, 'str', 'xr:Cisco-ios-xr-string',
                None, None,
                [], [b'[\\w\\-\\.:,_@#%$\\+=\\|;]+'],
                '''                Set string
                ''',
                'af_name',
                'Cisco-IOS-XR-flowspec-oper', True, is_config=False),
            _MetaInfoClassMember('table-summary', REFERENCE_CLASS, 'TableSummary', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_flowspec_oper', 'FlowSpec.Vrfs.Vrf.Afs.Af.TableSummary',
                [], [],
                '''                FlowSpec summary for VRF+AFI tables
                ''',
                'table_summary',
                'Cisco-IOS-XR-flowspec-oper', False, is_config=False),
            _MetaInfoClassMember('nlris', REFERENCE_CLASS, 'Nlris', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_flowspec_oper', 'FlowSpec.Vrfs.Vrf.Afs.Af.Nlris',
                [], [],
                '''                Table of NLRI
                ''',
                'nlris',
                'Cisco-IOS-XR-flowspec-oper', False, is_config=False),
            _MetaInfoClassMember('flows', REFERENCE_CLASS, 'Flows', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_flowspec_oper', 'FlowSpec.Vrfs.Vrf.Afs.Af.Flows',
                [], [],
                '''                Table of Flow
                ''',
                'flows',
                'Cisco-IOS-XR-flowspec-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-flowspec-oper',
            'af',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-flowspec-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_flowspec_oper',
            is_config=False,
        ),
    },
    'FlowSpec.Vrfs.Vrf.Afs' : {
        'meta_info' : _MetaInfoClass('FlowSpec.Vrfs.Vrf.Afs', REFERENCE_CLASS,
            '''Table of AF''',
            False, 
            [
            _MetaInfoClassMember('af', REFERENCE_LIST, 'Af', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_flowspec_oper', 'FlowSpec.Vrfs.Vrf.Afs.Af',
                [], [],
                '''                AFI Type (IPv4/IPv6)
                ''',
                'af',
                'Cisco-IOS-XR-flowspec-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-flowspec-oper',
            'afs',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-flowspec-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_flowspec_oper',
            is_config=False,
        ),
    },
    'FlowSpec.Vrfs.Vrf' : {
        'meta_info' : _MetaInfoClass('FlowSpec.Vrfs.Vrf', REFERENCE_LIST,
            '''VRF information''',
            False, 
            [
            _MetaInfoClassMember('vrf-name', ATTRIBUTE, 'str', 'xr:Cisco-ios-xr-string',
                None, None,
                [(1, 32)], [],
                '''                VRF Name
                ''',
                'vrf_name',
                'Cisco-IOS-XR-flowspec-oper', True, is_config=False),
            _MetaInfoClassMember('afs', REFERENCE_CLASS, 'Afs', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_flowspec_oper', 'FlowSpec.Vrfs.Vrf.Afs',
                [], [],
                '''                Table of AF
                ''',
                'afs',
                'Cisco-IOS-XR-flowspec-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-flowspec-oper',
            'vrf',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-flowspec-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_flowspec_oper',
            is_config=False,
        ),
    },
    'FlowSpec.Vrfs' : {
        'meta_info' : _MetaInfoClass('FlowSpec.Vrfs', REFERENCE_CLASS,
            '''Table of VRF''',
            False, 
            [
            _MetaInfoClassMember('vrf', REFERENCE_LIST, 'Vrf', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_flowspec_oper', 'FlowSpec.Vrfs.Vrf',
                [], [],
                '''                VRF information
                ''',
                'vrf',
                'Cisco-IOS-XR-flowspec-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-flowspec-oper',
            'vrfs',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-flowspec-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_flowspec_oper',
            is_config=False,
        ),
    },
    'FlowSpec' : {
        'meta_info' : _MetaInfoClass('FlowSpec', REFERENCE_CLASS,
            '''FlowSpec information''',
            False, 
            [
            _MetaInfoClassMember('clients', REFERENCE_CLASS, 'Clients', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_flowspec_oper', 'FlowSpec.Clients',
                [], [],
                '''                Table of Client
                ''',
                'clients',
                'Cisco-IOS-XR-flowspec-oper', False, is_config=False),
            _MetaInfoClassMember('summary', REFERENCE_CLASS, 'Summary', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_flowspec_oper', 'FlowSpec.Summary',
                [], [],
                '''                FlowSpec summary
                ''',
                'summary',
                'Cisco-IOS-XR-flowspec-oper', False, is_config=False),
            _MetaInfoClassMember('vrfs', REFERENCE_CLASS, 'Vrfs', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_flowspec_oper', 'FlowSpec.Vrfs',
                [], [],
                '''                Table of VRF
                ''',
                'vrfs',
                'Cisco-IOS-XR-flowspec-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-flowspec-oper',
            'flow-spec',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-flowspec-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_flowspec_oper',
            is_config=False,
        ),
    },
}
_meta_table['FlowSpec.Clients.Client']['meta_info'].parent =_meta_table['FlowSpec.Clients']['meta_info']
_meta_table['FlowSpec.Vrfs.Vrf.Afs.Af.Nlris.Nlri.FlowStatistics.Classified']['meta_info'].parent =_meta_table['FlowSpec.Vrfs.Vrf.Afs.Af.Nlris.Nlri.FlowStatistics']['meta_info']
_meta_table['FlowSpec.Vrfs.Vrf.Afs.Af.Nlris.Nlri.FlowStatistics.Dropped']['meta_info'].parent =_meta_table['FlowSpec.Vrfs.Vrf.Afs.Af.Nlris.Nlri.FlowStatistics']['meta_info']
_meta_table['FlowSpec.Vrfs.Vrf.Afs.Af.Nlris.Nlri.FlowStatistics']['meta_info'].parent =_meta_table['FlowSpec.Vrfs.Vrf.Afs.Af.Nlris.Nlri']['meta_info']
_meta_table['FlowSpec.Vrfs.Vrf.Afs.Af.Nlris.Nlri']['meta_info'].parent =_meta_table['FlowSpec.Vrfs.Vrf.Afs.Af.Nlris']['meta_info']
_meta_table['FlowSpec.Vrfs.Vrf.Afs.Af.Flows.Flow.FlowStatistics.Classified']['meta_info'].parent =_meta_table['FlowSpec.Vrfs.Vrf.Afs.Af.Flows.Flow.FlowStatistics']['meta_info']
_meta_table['FlowSpec.Vrfs.Vrf.Afs.Af.Flows.Flow.FlowStatistics.Dropped']['meta_info'].parent =_meta_table['FlowSpec.Vrfs.Vrf.Afs.Af.Flows.Flow.FlowStatistics']['meta_info']
_meta_table['FlowSpec.Vrfs.Vrf.Afs.Af.Flows.Flow.FlowStatistics']['meta_info'].parent =_meta_table['FlowSpec.Vrfs.Vrf.Afs.Af.Flows.Flow']['meta_info']
_meta_table['FlowSpec.Vrfs.Vrf.Afs.Af.Flows.Flow']['meta_info'].parent =_meta_table['FlowSpec.Vrfs.Vrf.Afs.Af.Flows']['meta_info']
_meta_table['FlowSpec.Vrfs.Vrf.Afs.Af.TableSummary']['meta_info'].parent =_meta_table['FlowSpec.Vrfs.Vrf.Afs.Af']['meta_info']
_meta_table['FlowSpec.Vrfs.Vrf.Afs.Af.Nlris']['meta_info'].parent =_meta_table['FlowSpec.Vrfs.Vrf.Afs.Af']['meta_info']
_meta_table['FlowSpec.Vrfs.Vrf.Afs.Af.Flows']['meta_info'].parent =_meta_table['FlowSpec.Vrfs.Vrf.Afs.Af']['meta_info']
_meta_table['FlowSpec.Vrfs.Vrf.Afs.Af']['meta_info'].parent =_meta_table['FlowSpec.Vrfs.Vrf.Afs']['meta_info']
_meta_table['FlowSpec.Vrfs.Vrf.Afs']['meta_info'].parent =_meta_table['FlowSpec.Vrfs.Vrf']['meta_info']
_meta_table['FlowSpec.Vrfs.Vrf']['meta_info'].parent =_meta_table['FlowSpec.Vrfs']['meta_info']
_meta_table['FlowSpec.Clients']['meta_info'].parent =_meta_table['FlowSpec']['meta_info']
_meta_table['FlowSpec.Summary']['meta_info'].parent =_meta_table['FlowSpec']['meta_info']
_meta_table['FlowSpec.Vrfs']['meta_info'].parent =_meta_table['FlowSpec']['meta_info']
