
'''
This is auto-generated file,
which includes metadata for module Cisco_IOS_XR_sysadmin_rvm_mgr
'''

from ydk._core._dm_meta_info import _MetaInfoClassMember, _MetaInfoClass, _MetaInfoEnum
from ydk._core._dm_meta_info import ATTRIBUTE, REFERENCE_LIST, REFERENCE_LEAFLIST, REFERENCE_BITS, REFERENCE_UNION
from ydk._core._dm_meta_info import REFERENCE_CLASS, REFERENCE_IDENTITY_CLASS, REFERENCE_ENUM_CLASS, ANYXML_CLASS
from ydk._core._importer import _yang_ns

_meta_table = {
    'NodetypeTd' : _MetaInfoEnum('NodetypeTd',
        'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_rvm_mgr', 'NodetypeTd',
        ''' ''',
        {
            'sysadmin':'sysadmin',
            'service':'service',
        }, 'Cisco-IOS-XR-sysadmin-rvm-mgr', _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-sysadmin-rvm-mgr']),
    'FlagtypeTd' : _MetaInfoEnum('FlagtypeTd',
        'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_rvm_mgr', 'FlagtypeTd',
        ''' ''',
        {
            'clear':'clear',
            'set':'set',
        }, 'Cisco-IOS-XR-sysadmin-rvm-mgr', _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-sysadmin-rvm-mgr']),
    'RVM.AllLocations.Objects.AllObjs' : {
        'meta_info' : _MetaInfoClass('RVM.AllLocations.Objects.AllObjs', REFERENCE_LIST,
            ''' ''',
            False, 
            [
            _MetaInfoClassMember('index', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                Index into obj_db array
                ''',
                'index',
                'Cisco-IOS-XR-sysadmin-rvm-mgr', True, is_config=False),
            _MetaInfoClassMember('num_allocated', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                Number of allocated nodes
                ''',
                'num_allocated',
                'Cisco-IOS-XR-sysadmin-rvm-mgr', False, is_config=False),
            _MetaInfoClassMember('num_freed', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                Number of freed nodes
                ''',
                'num_freed',
                'Cisco-IOS-XR-sysadmin-rvm-mgr', False, is_config=False),
            _MetaInfoClassMember('num_objects', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                Number of current object nodes
                ''',
                'num_objects',
                'Cisco-IOS-XR-sysadmin-rvm-mgr', False, is_config=False),
            ],
            'Cisco-IOS-XR-sysadmin-rvm-mgr',
            'all-objs',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-sysadmin-rvm-mgr'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_rvm_mgr',
            is_config=False,
        ),
    },
    'RVM.AllLocations.Objects' : {
        'meta_info' : _MetaInfoClass('RVM.AllLocations.Objects', REFERENCE_CLASS,
            '''RVM Manager Info''',
            False, 
            [
            _MetaInfoClassMember('all-objs', REFERENCE_LIST, 'AllObjs', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_rvm_mgr', 'RVM.AllLocations.Objects.AllObjs',
                [], [],
                '''                ''',
                'all_objs',
                'Cisco-IOS-XR-sysadmin-rvm-mgr', False, is_config=False),
            ],
            'Cisco-IOS-XR-sysadmin-rvm-mgr',
            'objects',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-sysadmin-rvm-mgr'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_rvm_mgr',
            is_config=False,
        ),
    },
    'RVM.AllLocations.Node.AllNodes' : {
        'meta_info' : _MetaInfoClass('RVM.AllLocations.Node.AllNodes', REFERENCE_LIST,
            ''' ''',
            False, 
            [
            _MetaInfoClassMember('ipv4_addr', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                IP address of the node
                ''',
                'ipv4_addr',
                'Cisco-IOS-XR-sysadmin-rvm-mgr', True, is_config=False),
            _MetaInfoClassMember('ipv4_addr_str', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                IP address of the node in string format
                ''',
                'ipv4_addr_str',
                'Cisco-IOS-XR-sysadmin-rvm-mgr', False, is_config=False),
            _MetaInfoClassMember('node_info', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Node type state and flag
                ''',
                'node_info',
                'Cisco-IOS-XR-sysadmin-rvm-mgr', False, is_config=False),
            _MetaInfoClassMember('node_hb_info', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Node heartbeat related info
                ''',
                'node_hb_info',
                'Cisco-IOS-XR-sysadmin-rvm-mgr', False, is_config=False),
            _MetaInfoClassMember('node_card_info', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Card info the node belongs to
                ''',
                'node_card_info',
                'Cisco-IOS-XR-sysadmin-rvm-mgr', False, is_config=False),
            ],
            'Cisco-IOS-XR-sysadmin-rvm-mgr',
            'all-nodes',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-sysadmin-rvm-mgr'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_rvm_mgr',
            is_config=False,
        ),
    },
    'RVM.AllLocations.Node' : {
        'meta_info' : _MetaInfoClass('RVM.AllLocations.Node', REFERENCE_CLASS,
            '''RVM Manager Node Info''',
            False, 
            [
            _MetaInfoClassMember('all-nodes', REFERENCE_LIST, 'AllNodes', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_rvm_mgr', 'RVM.AllLocations.Node.AllNodes',
                [], [],
                '''                ''',
                'all_nodes',
                'Cisco-IOS-XR-sysadmin-rvm-mgr', False, is_config=False),
            ],
            'Cisco-IOS-XR-sysadmin-rvm-mgr',
            'node',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-sysadmin-rvm-mgr'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_rvm_mgr',
            is_config=False,
        ),
    },
    'RVM.AllLocations.Card.AllCards' : {
        'meta_info' : _MetaInfoClass('RVM.AllLocations.Card.AllCards', REFERENCE_LIST,
            ''' ''',
            False, 
            [
            _MetaInfoClassMember('serial_num', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Serial number of the card
                ''',
                'serial_num',
                'Cisco-IOS-XR-sysadmin-rvm-mgr', True, is_config=False),
            _MetaInfoClassMember('card_flag', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Card flags
                ''',
                'card_flag',
                'Cisco-IOS-XR-sysadmin-rvm-mgr', False, is_config=False),
            _MetaInfoClassMember('card_info', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Card rack and slot num
                ''',
                'card_info',
                'Cisco-IOS-XR-sysadmin-rvm-mgr', False, is_config=False),
            _MetaInfoClassMember('sysadmin_nodes', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Sysadmin nodes on this card
                ''',
                'sysadmin_nodes',
                'Cisco-IOS-XR-sysadmin-rvm-mgr', False, is_config=False),
            _MetaInfoClassMember('xr_nodes', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                XR nodes on this card
                ''',
                'xr_nodes',
                'Cisco-IOS-XR-sysadmin-rvm-mgr', False, is_config=False),
            ],
            'Cisco-IOS-XR-sysadmin-rvm-mgr',
            'all-cards',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-sysadmin-rvm-mgr'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_rvm_mgr',
            is_config=False,
        ),
    },
    'RVM.AllLocations.Card' : {
        'meta_info' : _MetaInfoClass('RVM.AllLocations.Card', REFERENCE_CLASS,
            '''RVM Manager Card Info''',
            False, 
            [
            _MetaInfoClassMember('all-cards', REFERENCE_LIST, 'AllCards', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_rvm_mgr', 'RVM.AllLocations.Card.AllCards',
                [], [],
                '''                ''',
                'all_cards',
                'Cisco-IOS-XR-sysadmin-rvm-mgr', False, is_config=False),
            ],
            'Cisco-IOS-XR-sysadmin-rvm-mgr',
            'card',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-sysadmin-rvm-mgr'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_rvm_mgr',
            is_config=False,
        ),
    },
    'RVM.AllLocations' : {
        'meta_info' : _MetaInfoClass('RVM.AllLocations', REFERENCE_LIST,
            ''' ''',
            False, 
            [
            _MetaInfoClassMember('location', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                ''',
                'location',
                'Cisco-IOS-XR-sysadmin-rvm-mgr', True, is_config=False),
            _MetaInfoClassMember('objects', REFERENCE_CLASS, 'Objects', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_rvm_mgr', 'RVM.AllLocations.Objects',
                [], [],
                '''                RVM Manager Info
                ''',
                'objects',
                'Cisco-IOS-XR-sysadmin-rvm-mgr', False, is_config=False),
            _MetaInfoClassMember('node', REFERENCE_CLASS, 'Node', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_rvm_mgr', 'RVM.AllLocations.Node',
                [], [],
                '''                RVM Manager Node Info
                ''',
                'node',
                'Cisco-IOS-XR-sysadmin-rvm-mgr', False, is_config=False),
            _MetaInfoClassMember('card', REFERENCE_CLASS, 'Card', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_rvm_mgr', 'RVM.AllLocations.Card',
                [], [],
                '''                RVM Manager Card Info
                ''',
                'card',
                'Cisco-IOS-XR-sysadmin-rvm-mgr', False, is_config=False),
            ],
            'Cisco-IOS-XR-sysadmin-rvm-mgr',
            'all-locations',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-sysadmin-rvm-mgr'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_rvm_mgr',
            is_config=False,
        ),
    },
    'RVM' : {
        'meta_info' : _MetaInfoClass('RVM', REFERENCE_CLASS,
            '''RVM Manager Info''',
            False, 
            [
            _MetaInfoClassMember('all-locations', REFERENCE_LIST, 'AllLocations', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_rvm_mgr', 'RVM.AllLocations',
                [], [],
                '''                ''',
                'all_locations',
                'Cisco-IOS-XR-sysadmin-rvm-mgr', False, is_config=False),
            ],
            'Cisco-IOS-XR-sysadmin-rvm-mgr',
            'RVM',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-sysadmin-rvm-mgr'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_rvm_mgr',
            is_config=False,
        ),
    },
}
_meta_table['RVM.AllLocations.Objects.AllObjs']['meta_info'].parent =_meta_table['RVM.AllLocations.Objects']['meta_info']
_meta_table['RVM.AllLocations.Node.AllNodes']['meta_info'].parent =_meta_table['RVM.AllLocations.Node']['meta_info']
_meta_table['RVM.AllLocations.Card.AllCards']['meta_info'].parent =_meta_table['RVM.AllLocations.Card']['meta_info']
_meta_table['RVM.AllLocations.Objects']['meta_info'].parent =_meta_table['RVM.AllLocations']['meta_info']
_meta_table['RVM.AllLocations.Node']['meta_info'].parent =_meta_table['RVM.AllLocations']['meta_info']
_meta_table['RVM.AllLocations.Card']['meta_info'].parent =_meta_table['RVM.AllLocations']['meta_info']
_meta_table['RVM.AllLocations']['meta_info'].parent =_meta_table['RVM']['meta_info']
