
'''
This is auto-generated file,
which includes metadata for module Cisco_IOS_XR_dot1x_oper
'''

from ydk._core._dm_meta_info import _MetaInfoClassMember, _MetaInfoClass, _MetaInfoEnum
from ydk._core._dm_meta_info import ATTRIBUTE, REFERENCE_LIST, REFERENCE_LEAFLIST, REFERENCE_BITS, REFERENCE_UNION
from ydk._core._dm_meta_info import REFERENCE_CLASS, REFERENCE_IDENTITY_CLASS, REFERENCE_ENUM_CLASS, ANYXML_CLASS
from ydk._core._importer import _yang_ns

_meta_table = {
    'Dot1x.Statistics.InterfaceStatistics.InterfaceStatistic.Idb' : {
        'meta_info' : _MetaInfoClass('Dot1x.Statistics.InterfaceStatistics.InterfaceStatistic.Idb', REFERENCE_CLASS,
            '''Dot1x interface database Statistics''',
            False, 
            [
            _MetaInfoClassMember('rx-total', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                RxTotal
                ''',
                'rx_total',
                'Cisco-IOS-XR-dot1x-oper', False, is_config=False),
            _MetaInfoClassMember('tx-total', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                TxTotal
                ''',
                'tx_total',
                'Cisco-IOS-XR-dot1x-oper', False, is_config=False),
            _MetaInfoClassMember('no-rx-on-intf-down', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                NoRxOnIntfDown
                ''',
                'no_rx_on_intf_down',
                'Cisco-IOS-XR-dot1x-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-dot1x-oper',
            'idb',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-dot1x-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_dot1x_oper',
            is_config=False,
        ),
    },
    'Dot1x.Statistics.InterfaceStatistics.InterfaceStatistic.Auth.PortControl' : {
        'meta_info' : _MetaInfoClass('Dot1x.Statistics.InterfaceStatistics.InterfaceStatistic.Auth.PortControl', REFERENCE_CLASS,
            '''PortControl''',
            False, 
            [
            _MetaInfoClassMember('enable-succ', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                EnableSucc
                ''',
                'enable_succ',
                'Cisco-IOS-XR-dot1x-oper', False, is_config=False),
            _MetaInfoClassMember('enable-fail', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                EnableFail
                ''',
                'enable_fail',
                'Cisco-IOS-XR-dot1x-oper', False, is_config=False),
            _MetaInfoClassMember('add-client-succ', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                AddClientSucc
                ''',
                'add_client_succ',
                'Cisco-IOS-XR-dot1x-oper', False, is_config=False),
            _MetaInfoClassMember('add-client-fail', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                AddClientFail
                ''',
                'add_client_fail',
                'Cisco-IOS-XR-dot1x-oper', False, is_config=False),
            _MetaInfoClassMember('remove-client-succ', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                RemoveClientSucc
                ''',
                'remove_client_succ',
                'Cisco-IOS-XR-dot1x-oper', False, is_config=False),
            _MetaInfoClassMember('remove-client-fail', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                RemoveClientFail
                ''',
                'remove_client_fail',
                'Cisco-IOS-XR-dot1x-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-dot1x-oper',
            'port-control',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-dot1x-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_dot1x_oper',
            is_config=False,
        ),
    },
    'Dot1x.Statistics.InterfaceStatistics.InterfaceStatistic.Auth' : {
        'meta_info' : _MetaInfoClass('Dot1x.Statistics.InterfaceStatistics.InterfaceStatistic.Auth', REFERENCE_CLASS,
            '''Dot1x Authenticator Port Statistics''',
            False, 
            [
            _MetaInfoClassMember('port-control', REFERENCE_CLASS, 'PortControl', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_dot1x_oper', 'Dot1x.Statistics.InterfaceStatistics.InterfaceStatistic.Auth.PortControl',
                [], [],
                '''                PortControl
                ''',
                'port_control',
                'Cisco-IOS-XR-dot1x-oper', False, is_config=False),
            _MetaInfoClassMember('rx-start', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                RxStart
                ''',
                'rx_start',
                'Cisco-IOS-XR-dot1x-oper', False, is_config=False),
            _MetaInfoClassMember('rx-logoff', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                RxLogoff
                ''',
                'rx_logoff',
                'Cisco-IOS-XR-dot1x-oper', False, is_config=False),
            _MetaInfoClassMember('rx-resp', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                RxResp
                ''',
                'rx_resp',
                'Cisco-IOS-XR-dot1x-oper', False, is_config=False),
            _MetaInfoClassMember('rx-resp-id', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                RxRespID
                ''',
                'rx_resp_id',
                'Cisco-IOS-XR-dot1x-oper', False, is_config=False),
            _MetaInfoClassMember('rx-invalid', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                RxInvalid
                ''',
                'rx_invalid',
                'Cisco-IOS-XR-dot1x-oper', False, is_config=False),
            _MetaInfoClassMember('rx-len-err', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                RxLenErr
                ''',
                'rx_len_err',
                'Cisco-IOS-XR-dot1x-oper', False, is_config=False),
            _MetaInfoClassMember('rx-my-mac-err', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                RxMyMacErr
                ''',
                'rx_my_mac_err',
                'Cisco-IOS-XR-dot1x-oper', False, is_config=False),
            _MetaInfoClassMember('rx-total', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                RxTotal
                ''',
                'rx_total',
                'Cisco-IOS-XR-dot1x-oper', False, is_config=False),
            _MetaInfoClassMember('tx-req', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                TxReq
                ''',
                'tx_req',
                'Cisco-IOS-XR-dot1x-oper', False, is_config=False),
            _MetaInfoClassMember('tx-reqid', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                TxReqID
                ''',
                'tx_reqid',
                'Cisco-IOS-XR-dot1x-oper', False, is_config=False),
            _MetaInfoClassMember('tx-total', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                TxTotal
                ''',
                'tx_total',
                'Cisco-IOS-XR-dot1x-oper', False, is_config=False),
            _MetaInfoClassMember('packet-drop-no-config-received', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                PacketDrop
                ''',
                'packet_drop_no_config_received',
                'Cisco-IOS-XR-dot1x-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-dot1x-oper',
            'auth',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-dot1x-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_dot1x_oper',
            is_config=False,
        ),
    },
    'Dot1x.Statistics.InterfaceStatistics.InterfaceStatistic.Supp' : {
        'meta_info' : _MetaInfoClass('Dot1x.Statistics.InterfaceStatistics.InterfaceStatistic.Supp', REFERENCE_CLASS,
            '''Dot1x Supplicant Port Statistics''',
            False, 
            [
            _MetaInfoClassMember('rx-req', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                RxReq
                ''',
                'rx_req',
                'Cisco-IOS-XR-dot1x-oper', False, is_config=False),
            _MetaInfoClassMember('rx-invalid', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                RxInvalid
                ''',
                'rx_invalid',
                'Cisco-IOS-XR-dot1x-oper', False, is_config=False),
            _MetaInfoClassMember('rx-len-err', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                RxLenErr
                ''',
                'rx_len_err',
                'Cisco-IOS-XR-dot1x-oper', False, is_config=False),
            _MetaInfoClassMember('rx-my-mac-err', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                RxMyMacErr
                ''',
                'rx_my_mac_err',
                'Cisco-IOS-XR-dot1x-oper', False, is_config=False),
            _MetaInfoClassMember('rx-total', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                RxTotal
                ''',
                'rx_total',
                'Cisco-IOS-XR-dot1x-oper', False, is_config=False),
            _MetaInfoClassMember('tx-start', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                TxStart
                ''',
                'tx_start',
                'Cisco-IOS-XR-dot1x-oper', False, is_config=False),
            _MetaInfoClassMember('tx-logoff', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                TxLogoff
                ''',
                'tx_logoff',
                'Cisco-IOS-XR-dot1x-oper', False, is_config=False),
            _MetaInfoClassMember('tx-resp', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                TxResp
                ''',
                'tx_resp',
                'Cisco-IOS-XR-dot1x-oper', False, is_config=False),
            _MetaInfoClassMember('tx-total', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                TxTotal
                ''',
                'tx_total',
                'Cisco-IOS-XR-dot1x-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-dot1x-oper',
            'supp',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-dot1x-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_dot1x_oper',
            is_config=False,
        ),
    },
    'Dot1x.Statistics.InterfaceStatistics.InterfaceStatistic.LocalEap' : {
        'meta_info' : _MetaInfoClass('Dot1x.Statistics.InterfaceStatistics.InterfaceStatistic.LocalEap', REFERENCE_CLASS,
            '''Dot1x Local EAP Port Statistics''',
            False, 
            [
            _MetaInfoClassMember('requests', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                Requests
                ''',
                'requests',
                'Cisco-IOS-XR-dot1x-oper', False, is_config=False),
            _MetaInfoClassMember('replies', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                Replies
                ''',
                'replies',
                'Cisco-IOS-XR-dot1x-oper', False, is_config=False),
            _MetaInfoClassMember('timeout', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                Timeout
                ''',
                'timeout',
                'Cisco-IOS-XR-dot1x-oper', False, is_config=False),
            _MetaInfoClassMember('dropped-no-eap', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                DroppedNoEAP
                ''',
                'dropped_no_eap',
                'Cisco-IOS-XR-dot1x-oper', False, is_config=False),
            _MetaInfoClassMember('dropped', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                Dropped
                ''',
                'dropped',
                'Cisco-IOS-XR-dot1x-oper', False, is_config=False),
            _MetaInfoClassMember('success', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                Success
                ''',
                'success',
                'Cisco-IOS-XR-dot1x-oper', False, is_config=False),
            _MetaInfoClassMember('failed', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                Failed
                ''',
                'failed',
                'Cisco-IOS-XR-dot1x-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-dot1x-oper',
            'local-eap',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-dot1x-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_dot1x_oper',
            is_config=False,
        ),
    },
    'Dot1x.Statistics.InterfaceStatistics.InterfaceStatistic' : {
        'meta_info' : _MetaInfoClass('Dot1x.Statistics.InterfaceStatistics.InterfaceStatistic', REFERENCE_LIST,
            '''Dot1x Data for that Interface''',
            False, 
            [
            _MetaInfoClassMember('name', ATTRIBUTE, 'str', 'xr:Interface-name',
                None, None,
                [], [b'[a-zA-Z0-9._/-]+'],
                '''                Interface Name
                ''',
                'name',
                'Cisco-IOS-XR-dot1x-oper', True, is_config=False),
            _MetaInfoClassMember('idb', REFERENCE_CLASS, 'Idb', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_dot1x_oper', 'Dot1x.Statistics.InterfaceStatistics.InterfaceStatistic.Idb',
                [], [],
                '''                Dot1x interface database Statistics
                ''',
                'idb',
                'Cisco-IOS-XR-dot1x-oper', False, is_config=False),
            _MetaInfoClassMember('auth', REFERENCE_CLASS, 'Auth', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_dot1x_oper', 'Dot1x.Statistics.InterfaceStatistics.InterfaceStatistic.Auth',
                [], [],
                '''                Dot1x Authenticator Port Statistics
                ''',
                'auth',
                'Cisco-IOS-XR-dot1x-oper', False, is_config=False),
            _MetaInfoClassMember('supp', REFERENCE_CLASS, 'Supp', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_dot1x_oper', 'Dot1x.Statistics.InterfaceStatistics.InterfaceStatistic.Supp',
                [], [],
                '''                Dot1x Supplicant Port Statistics
                ''',
                'supp',
                'Cisco-IOS-XR-dot1x-oper', False, is_config=False),
            _MetaInfoClassMember('local-eap', REFERENCE_CLASS, 'LocalEap', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_dot1x_oper', 'Dot1x.Statistics.InterfaceStatistics.InterfaceStatistic.LocalEap',
                [], [],
                '''                Dot1x Local EAP Port Statistics
                ''',
                'local_eap',
                'Cisco-IOS-XR-dot1x-oper', False, is_config=False),
            _MetaInfoClassMember('interface-name', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Interface Display name 
                ''',
                'interface_name',
                'Cisco-IOS-XR-dot1x-oper', False, is_config=False),
            _MetaInfoClassMember('pae', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                PAE type on interface
                ''',
                'pae',
                'Cisco-IOS-XR-dot1x-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-dot1x-oper',
            'interface-statistic',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-dot1x-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_dot1x_oper',
            is_config=False,
        ),
    },
    'Dot1x.Statistics.InterfaceStatistics' : {
        'meta_info' : _MetaInfoClass('Dot1x.Statistics.InterfaceStatistics', REFERENCE_CLASS,
            '''Interfaces with Dot1x''',
            False, 
            [
            _MetaInfoClassMember('interface-statistic', REFERENCE_LIST, 'InterfaceStatistic', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_dot1x_oper', 'Dot1x.Statistics.InterfaceStatistics.InterfaceStatistic',
                [], [],
                '''                Dot1x Data for that Interface
                ''',
                'interface_statistic',
                'Cisco-IOS-XR-dot1x-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-dot1x-oper',
            'interface-statistics',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-dot1x-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_dot1x_oper',
            is_config=False,
        ),
    },
    'Dot1x.Statistics' : {
        'meta_info' : _MetaInfoClass('Dot1x.Statistics', REFERENCE_CLASS,
            '''Dot1x operational data''',
            False, 
            [
            _MetaInfoClassMember('interface-statistics', REFERENCE_CLASS, 'InterfaceStatistics', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_dot1x_oper', 'Dot1x.Statistics.InterfaceStatistics',
                [], [],
                '''                Interfaces with Dot1x
                ''',
                'interface_statistics',
                'Cisco-IOS-XR-dot1x-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-dot1x-oper',
            'statistics',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-dot1x-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_dot1x_oper',
            is_config=False,
        ),
    },
    'Dot1x.Nodes.Node.Dot1xDefaults.AuthTimers' : {
        'meta_info' : _MetaInfoClass('Dot1x.Nodes.Node.Dot1xDefaults.AuthTimers', REFERENCE_CLASS,
            '''Dot1x Authenticator default Timer values''',
            False, 
            [
            _MetaInfoClassMember('quiet-period', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                in Seconds, authenticator remains quiet (in the
                HELD state) following a failed authentication
                exchange before trying to reauthenticate the
                client
                ''',
                'quiet_period',
                'Cisco-IOS-XR-dot1x-oper', False, is_config=False),
            _MetaInfoClassMember('tx-period', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                in Seconds, Timeout for supplicant reply,
                authenticator-to-supplicant retransmission time
                for EAP-request-ID packets (assuming that no
                response is received) from the client
                ''',
                'tx_period',
                'Cisco-IOS-XR-dot1x-oper', False, is_config=False),
            _MetaInfoClassMember('max-reauth-req', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                Max No. of Reauthentication Attempts (or)
                retransmits an EAP-request-ID frame to the
                client before restarting the authentication
                process
                ''',
                'max_reauth_req',
                'Cisco-IOS-XR-dot1x-oper', False, is_config=False),
            _MetaInfoClassMember('supp-timeout', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                in Seconds, Timeout for supplicant reply,
                authenticator-to-supplicant retransmission time
                for all EAP messages except for EAP Request ID
                packets
                ''',
                'supp_timeout',
                'Cisco-IOS-XR-dot1x-oper', False, is_config=False),
            _MetaInfoClassMember('max-req', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                Max No. of EAP-Req (except for EAP-Request-ID)
                retransmits (authenticator-to-supplicant) before
                sending EAP-Failure
                ''',
                'max_req',
                'Cisco-IOS-XR-dot1x-oper', False, is_config=False),
            _MetaInfoClassMember('reauth-period', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                in Seconds,  after which an automatic
                reauthentication should be initiated
                ''',
                'reauth_period',
                'Cisco-IOS-XR-dot1x-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-dot1x-oper',
            'auth-timers',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-dot1x-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_dot1x_oper',
            is_config=False,
        ),
    },
    'Dot1x.Nodes.Node.Dot1xDefaults.SuppTimers' : {
        'meta_info' : _MetaInfoClass('Dot1x.Nodes.Node.Dot1xDefaults.SuppTimers', REFERENCE_CLASS,
            '''Dot1x Supllicant default Timer values''',
            False, 
            [
            _MetaInfoClassMember('auth-period', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                in Seconds, supplicant waits for a response from
                an authenticator except for EAPOL-START before
                timing out
                ''',
                'auth_period',
                'Cisco-IOS-XR-dot1x-oper', False, is_config=False),
            _MetaInfoClassMember('held-period', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                in Seconds, supplicant will stay in the HELD
                state (that is, the length of time it will wait
                before trying to send the credentials again
                after a failed attempt)
                ''',
                'held_period',
                'Cisco-IOS-XR-dot1x-oper', False, is_config=False),
            _MetaInfoClassMember('start-period', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                Configures the interval, in seconds, between two
                successive EAPOL-Start frames when they are
                being retransmitted
                ''',
                'start_period',
                'Cisco-IOS-XR-dot1x-oper', False, is_config=False),
            _MetaInfoClassMember('max-start', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                Max No. of EAPOL-Start frames supplicant can
                send to the authenticator
                ''',
                'max_start',
                'Cisco-IOS-XR-dot1x-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-dot1x-oper',
            'supp-timers',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-dot1x-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_dot1x_oper',
            is_config=False,
        ),
    },
    'Dot1x.Nodes.Node.Dot1xDefaults' : {
        'meta_info' : _MetaInfoClass('Dot1x.Nodes.Node.Dot1xDefaults', REFERENCE_CLASS,
            '''Dot1x Default Values''',
            False, 
            [
            _MetaInfoClassMember('auth-timers', REFERENCE_CLASS, 'AuthTimers', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_dot1x_oper', 'Dot1x.Nodes.Node.Dot1xDefaults.AuthTimers',
                [], [],
                '''                Dot1x Authenticator default Timer values
                ''',
                'auth_timers',
                'Cisco-IOS-XR-dot1x-oper', False, is_config=False),
            _MetaInfoClassMember('supp-timers', REFERENCE_CLASS, 'SuppTimers', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_dot1x_oper', 'Dot1x.Nodes.Node.Dot1xDefaults.SuppTimers',
                [], [],
                '''                Dot1x Supllicant default Timer values
                ''',
                'supp_timers',
                'Cisco-IOS-XR-dot1x-oper', False, is_config=False),
            _MetaInfoClassMember('version', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                Dot1x Protocol Version
                ''',
                'version',
                'Cisco-IOS-XR-dot1x-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-dot1x-oper',
            'dot1x-defaults',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-dot1x-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_dot1x_oper',
            is_config=False,
        ),
    },
    'Dot1x.Nodes.Node.Statistics.GlStats.PortControl' : {
        'meta_info' : _MetaInfoClass('Dot1x.Nodes.Node.Statistics.GlStats.PortControl', REFERENCE_CLASS,
            '''PortControl''',
            False, 
            [
            _MetaInfoClassMember('enable-succ', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                EnableSucc
                ''',
                'enable_succ',
                'Cisco-IOS-XR-dot1x-oper', False, is_config=False),
            _MetaInfoClassMember('enable-fail', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                EnableFail
                ''',
                'enable_fail',
                'Cisco-IOS-XR-dot1x-oper', False, is_config=False),
            _MetaInfoClassMember('disable-succ', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                DisableSucc
                ''',
                'disable_succ',
                'Cisco-IOS-XR-dot1x-oper', False, is_config=False),
            _MetaInfoClassMember('disable-fail', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                DisableFail
                ''',
                'disable_fail',
                'Cisco-IOS-XR-dot1x-oper', False, is_config=False),
            _MetaInfoClassMember('add-client-succ', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                AddClientSucc
                ''',
                'add_client_succ',
                'Cisco-IOS-XR-dot1x-oper', False, is_config=False),
            _MetaInfoClassMember('add-client-fail', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                AddClientFail
                ''',
                'add_client_fail',
                'Cisco-IOS-XR-dot1x-oper', False, is_config=False),
            _MetaInfoClassMember('remove-client-succ', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                RemoveClientSucc
                ''',
                'remove_client_succ',
                'Cisco-IOS-XR-dot1x-oper', False, is_config=False),
            _MetaInfoClassMember('remove-client-fail', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                RemoveClientFail
                ''',
                'remove_client_fail',
                'Cisco-IOS-XR-dot1x-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-dot1x-oper',
            'port-control',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-dot1x-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_dot1x_oper',
            is_config=False,
        ),
    },
    'Dot1x.Nodes.Node.Statistics.GlStats' : {
        'meta_info' : _MetaInfoClass('Dot1x.Nodes.Node.Statistics.GlStats', REFERENCE_CLASS,
            '''Global statistics''',
            False, 
            [
            _MetaInfoClassMember('port-control', REFERENCE_CLASS, 'PortControl', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_dot1x_oper', 'Dot1x.Nodes.Node.Statistics.GlStats.PortControl',
                [], [],
                '''                PortControl
                ''',
                'port_control',
                'Cisco-IOS-XR-dot1x-oper', False, is_config=False),
            _MetaInfoClassMember('tx-total', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                TxTotal
                ''',
                'tx_total',
                'Cisco-IOS-XR-dot1x-oper', False, is_config=False),
            _MetaInfoClassMember('rx-total', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                RxTotal
                ''',
                'rx_total',
                'Cisco-IOS-XR-dot1x-oper', False, is_config=False),
            _MetaInfoClassMember('rx-no-idb', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                RxNoIDB
                ''',
                'rx_no_idb',
                'Cisco-IOS-XR-dot1x-oper', False, is_config=False),
            _MetaInfoClassMember('packet-drop-no-config-received', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                PacketDrop
                ''',
                'packet_drop_no_config_received',
                'Cisco-IOS-XR-dot1x-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-dot1x-oper',
            'gl-stats',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-dot1x-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_dot1x_oper',
            is_config=False,
        ),
    },
    'Dot1x.Nodes.Node.Statistics.IfStats.Idb' : {
        'meta_info' : _MetaInfoClass('Dot1x.Nodes.Node.Statistics.IfStats.Idb', REFERENCE_CLASS,
            '''Dot1x interface database Statistics''',
            False, 
            [
            _MetaInfoClassMember('rx-total', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                RxTotal
                ''',
                'rx_total',
                'Cisco-IOS-XR-dot1x-oper', False, is_config=False),
            _MetaInfoClassMember('tx-total', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                TxTotal
                ''',
                'tx_total',
                'Cisco-IOS-XR-dot1x-oper', False, is_config=False),
            _MetaInfoClassMember('no-rx-on-intf-down', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                NoRxOnIntfDown
                ''',
                'no_rx_on_intf_down',
                'Cisco-IOS-XR-dot1x-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-dot1x-oper',
            'idb',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-dot1x-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_dot1x_oper',
            is_config=False,
        ),
    },
    'Dot1x.Nodes.Node.Statistics.IfStats.Auth.PortControl' : {
        'meta_info' : _MetaInfoClass('Dot1x.Nodes.Node.Statistics.IfStats.Auth.PortControl', REFERENCE_CLASS,
            '''PortControl''',
            False, 
            [
            _MetaInfoClassMember('enable-succ', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                EnableSucc
                ''',
                'enable_succ',
                'Cisco-IOS-XR-dot1x-oper', False, is_config=False),
            _MetaInfoClassMember('enable-fail', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                EnableFail
                ''',
                'enable_fail',
                'Cisco-IOS-XR-dot1x-oper', False, is_config=False),
            _MetaInfoClassMember('add-client-succ', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                AddClientSucc
                ''',
                'add_client_succ',
                'Cisco-IOS-XR-dot1x-oper', False, is_config=False),
            _MetaInfoClassMember('add-client-fail', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                AddClientFail
                ''',
                'add_client_fail',
                'Cisco-IOS-XR-dot1x-oper', False, is_config=False),
            _MetaInfoClassMember('remove-client-succ', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                RemoveClientSucc
                ''',
                'remove_client_succ',
                'Cisco-IOS-XR-dot1x-oper', False, is_config=False),
            _MetaInfoClassMember('remove-client-fail', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                RemoveClientFail
                ''',
                'remove_client_fail',
                'Cisco-IOS-XR-dot1x-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-dot1x-oper',
            'port-control',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-dot1x-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_dot1x_oper',
            is_config=False,
        ),
    },
    'Dot1x.Nodes.Node.Statistics.IfStats.Auth' : {
        'meta_info' : _MetaInfoClass('Dot1x.Nodes.Node.Statistics.IfStats.Auth', REFERENCE_CLASS,
            '''Dot1x Authenticator Port Statistics''',
            False, 
            [
            _MetaInfoClassMember('port-control', REFERENCE_CLASS, 'PortControl', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_dot1x_oper', 'Dot1x.Nodes.Node.Statistics.IfStats.Auth.PortControl',
                [], [],
                '''                PortControl
                ''',
                'port_control',
                'Cisco-IOS-XR-dot1x-oper', False, is_config=False),
            _MetaInfoClassMember('rx-start', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                RxStart
                ''',
                'rx_start',
                'Cisco-IOS-XR-dot1x-oper', False, is_config=False),
            _MetaInfoClassMember('rx-logoff', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                RxLogoff
                ''',
                'rx_logoff',
                'Cisco-IOS-XR-dot1x-oper', False, is_config=False),
            _MetaInfoClassMember('rx-resp', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                RxResp
                ''',
                'rx_resp',
                'Cisco-IOS-XR-dot1x-oper', False, is_config=False),
            _MetaInfoClassMember('rx-resp-id', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                RxRespID
                ''',
                'rx_resp_id',
                'Cisco-IOS-XR-dot1x-oper', False, is_config=False),
            _MetaInfoClassMember('rx-invalid', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                RxInvalid
                ''',
                'rx_invalid',
                'Cisco-IOS-XR-dot1x-oper', False, is_config=False),
            _MetaInfoClassMember('rx-len-err', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                RxLenErr
                ''',
                'rx_len_err',
                'Cisco-IOS-XR-dot1x-oper', False, is_config=False),
            _MetaInfoClassMember('rx-my-mac-err', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                RxMyMacErr
                ''',
                'rx_my_mac_err',
                'Cisco-IOS-XR-dot1x-oper', False, is_config=False),
            _MetaInfoClassMember('rx-total', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                RxTotal
                ''',
                'rx_total',
                'Cisco-IOS-XR-dot1x-oper', False, is_config=False),
            _MetaInfoClassMember('tx-req', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                TxReq
                ''',
                'tx_req',
                'Cisco-IOS-XR-dot1x-oper', False, is_config=False),
            _MetaInfoClassMember('tx-reqid', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                TxReqID
                ''',
                'tx_reqid',
                'Cisco-IOS-XR-dot1x-oper', False, is_config=False),
            _MetaInfoClassMember('tx-total', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                TxTotal
                ''',
                'tx_total',
                'Cisco-IOS-XR-dot1x-oper', False, is_config=False),
            _MetaInfoClassMember('packet-drop-no-config-received', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                PacketDrop
                ''',
                'packet_drop_no_config_received',
                'Cisco-IOS-XR-dot1x-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-dot1x-oper',
            'auth',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-dot1x-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_dot1x_oper',
            is_config=False,
        ),
    },
    'Dot1x.Nodes.Node.Statistics.IfStats.Supp' : {
        'meta_info' : _MetaInfoClass('Dot1x.Nodes.Node.Statistics.IfStats.Supp', REFERENCE_CLASS,
            '''Dot1x Supplicant Port Statistics''',
            False, 
            [
            _MetaInfoClassMember('rx-req', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                RxReq
                ''',
                'rx_req',
                'Cisco-IOS-XR-dot1x-oper', False, is_config=False),
            _MetaInfoClassMember('rx-invalid', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                RxInvalid
                ''',
                'rx_invalid',
                'Cisco-IOS-XR-dot1x-oper', False, is_config=False),
            _MetaInfoClassMember('rx-len-err', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                RxLenErr
                ''',
                'rx_len_err',
                'Cisco-IOS-XR-dot1x-oper', False, is_config=False),
            _MetaInfoClassMember('rx-my-mac-err', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                RxMyMacErr
                ''',
                'rx_my_mac_err',
                'Cisco-IOS-XR-dot1x-oper', False, is_config=False),
            _MetaInfoClassMember('rx-total', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                RxTotal
                ''',
                'rx_total',
                'Cisco-IOS-XR-dot1x-oper', False, is_config=False),
            _MetaInfoClassMember('tx-start', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                TxStart
                ''',
                'tx_start',
                'Cisco-IOS-XR-dot1x-oper', False, is_config=False),
            _MetaInfoClassMember('tx-logoff', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                TxLogoff
                ''',
                'tx_logoff',
                'Cisco-IOS-XR-dot1x-oper', False, is_config=False),
            _MetaInfoClassMember('tx-resp', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                TxResp
                ''',
                'tx_resp',
                'Cisco-IOS-XR-dot1x-oper', False, is_config=False),
            _MetaInfoClassMember('tx-total', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                TxTotal
                ''',
                'tx_total',
                'Cisco-IOS-XR-dot1x-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-dot1x-oper',
            'supp',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-dot1x-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_dot1x_oper',
            is_config=False,
        ),
    },
    'Dot1x.Nodes.Node.Statistics.IfStats.LocalEap' : {
        'meta_info' : _MetaInfoClass('Dot1x.Nodes.Node.Statistics.IfStats.LocalEap', REFERENCE_CLASS,
            '''Dot1x Local EAP Port Statistics''',
            False, 
            [
            _MetaInfoClassMember('requests', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                Requests
                ''',
                'requests',
                'Cisco-IOS-XR-dot1x-oper', False, is_config=False),
            _MetaInfoClassMember('replies', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                Replies
                ''',
                'replies',
                'Cisco-IOS-XR-dot1x-oper', False, is_config=False),
            _MetaInfoClassMember('timeout', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                Timeout
                ''',
                'timeout',
                'Cisco-IOS-XR-dot1x-oper', False, is_config=False),
            _MetaInfoClassMember('dropped-no-eap', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                DroppedNoEAP
                ''',
                'dropped_no_eap',
                'Cisco-IOS-XR-dot1x-oper', False, is_config=False),
            _MetaInfoClassMember('dropped', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                Dropped
                ''',
                'dropped',
                'Cisco-IOS-XR-dot1x-oper', False, is_config=False),
            _MetaInfoClassMember('success', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                Success
                ''',
                'success',
                'Cisco-IOS-XR-dot1x-oper', False, is_config=False),
            _MetaInfoClassMember('failed', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                Failed
                ''',
                'failed',
                'Cisco-IOS-XR-dot1x-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-dot1x-oper',
            'local-eap',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-dot1x-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_dot1x_oper',
            is_config=False,
        ),
    },
    'Dot1x.Nodes.Node.Statistics.IfStats' : {
        'meta_info' : _MetaInfoClass('Dot1x.Nodes.Node.Statistics.IfStats', REFERENCE_LIST,
            '''dot1x interface statistics list''',
            False, 
            [
            _MetaInfoClassMember('idb', REFERENCE_CLASS, 'Idb', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_dot1x_oper', 'Dot1x.Nodes.Node.Statistics.IfStats.Idb',
                [], [],
                '''                Dot1x interface database Statistics
                ''',
                'idb',
                'Cisco-IOS-XR-dot1x-oper', False, is_config=False),
            _MetaInfoClassMember('auth', REFERENCE_CLASS, 'Auth', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_dot1x_oper', 'Dot1x.Nodes.Node.Statistics.IfStats.Auth',
                [], [],
                '''                Dot1x Authenticator Port Statistics
                ''',
                'auth',
                'Cisco-IOS-XR-dot1x-oper', False, is_config=False),
            _MetaInfoClassMember('supp', REFERENCE_CLASS, 'Supp', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_dot1x_oper', 'Dot1x.Nodes.Node.Statistics.IfStats.Supp',
                [], [],
                '''                Dot1x Supplicant Port Statistics
                ''',
                'supp',
                'Cisco-IOS-XR-dot1x-oper', False, is_config=False),
            _MetaInfoClassMember('local-eap', REFERENCE_CLASS, 'LocalEap', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_dot1x_oper', 'Dot1x.Nodes.Node.Statistics.IfStats.LocalEap',
                [], [],
                '''                Dot1x Local EAP Port Statistics
                ''',
                'local_eap',
                'Cisco-IOS-XR-dot1x-oper', False, is_config=False),
            _MetaInfoClassMember('interface-name', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Interface Display name 
                ''',
                'interface_name',
                'Cisco-IOS-XR-dot1x-oper', False, is_config=False),
            _MetaInfoClassMember('pae', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                PAE type on interface
                ''',
                'pae',
                'Cisco-IOS-XR-dot1x-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-dot1x-oper',
            'if-stats',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-dot1x-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_dot1x_oper',
            is_config=False,
        ),
    },
    'Dot1x.Nodes.Node.Statistics' : {
        'meta_info' : _MetaInfoClass('Dot1x.Nodes.Node.Statistics', REFERENCE_CLASS,
            '''Dot1x Default Values''',
            False, 
            [
            _MetaInfoClassMember('gl-stats', REFERENCE_CLASS, 'GlStats', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_dot1x_oper', 'Dot1x.Nodes.Node.Statistics.GlStats',
                [], [],
                '''                Global statistics
                ''',
                'gl_stats',
                'Cisco-IOS-XR-dot1x-oper', False, is_config=False),
            _MetaInfoClassMember('if-stats', REFERENCE_LIST, 'IfStats', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_dot1x_oper', 'Dot1x.Nodes.Node.Statistics.IfStats',
                [], [],
                '''                dot1x interface statistics list
                ''',
                'if_stats',
                'Cisco-IOS-XR-dot1x-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-dot1x-oper',
            'statistics',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-dot1x-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_dot1x_oper',
            is_config=False,
        ),
    },
    'Dot1x.Nodes.Node' : {
        'meta_info' : _MetaInfoClass('Dot1x.Nodes.Node', REFERENCE_LIST,
            '''Dot1x operational data for a particular node''',
            False, 
            [
            _MetaInfoClassMember('node-name', ATTRIBUTE, 'str', 'xr:Node-id',
                None, None,
                [], [b'([a-zA-Z0-9_]*\\d+/){1,2}([a-zA-Z0-9_]*\\d+)'],
                '''                The node name
                ''',
                'node_name',
                'Cisco-IOS-XR-dot1x-oper', True, is_config=False),
            _MetaInfoClassMember('dot1x-defaults', REFERENCE_CLASS, 'Dot1xDefaults', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_dot1x_oper', 'Dot1x.Nodes.Node.Dot1xDefaults',
                [], [],
                '''                Dot1x Default Values
                ''',
                'dot1x_defaults',
                'Cisco-IOS-XR-dot1x-oper', False, is_config=False),
            _MetaInfoClassMember('statistics', REFERENCE_CLASS, 'Statistics', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_dot1x_oper', 'Dot1x.Nodes.Node.Statistics',
                [], [],
                '''                Dot1x Default Values
                ''',
                'statistics',
                'Cisco-IOS-XR-dot1x-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-dot1x-oper',
            'node',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-dot1x-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_dot1x_oper',
            is_config=False,
        ),
    },
    'Dot1x.Nodes' : {
        'meta_info' : _MetaInfoClass('Dot1x.Nodes', REFERENCE_CLASS,
            '''Node-specific Dot1x operational data''',
            False, 
            [
            _MetaInfoClassMember('node', REFERENCE_LIST, 'Node', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_dot1x_oper', 'Dot1x.Nodes.Node',
                [], [],
                '''                Dot1x operational data for a particular node
                ''',
                'node',
                'Cisco-IOS-XR-dot1x-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-dot1x-oper',
            'nodes',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-dot1x-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_dot1x_oper',
            is_config=False,
        ),
    },
    'Dot1x.Session.InterfaceSessions.InterfaceSession.IntfInfo.AuthInfo.Client' : {
        'meta_info' : _MetaInfoClass('Dot1x.Session.InterfaceSessions.InterfaceSession.IntfInfo.AuthInfo.Client', REFERENCE_LIST,
            '''Authenticator client list''',
            False, 
            [
            _MetaInfoClassMember('mac', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                formatted MAC Address
                ''',
                'mac',
                'Cisco-IOS-XR-dot1x-oper', False, is_config=False),
            _MetaInfoClassMember('auth-sm-state', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Auth SM State
                ''',
                'auth_sm_state',
                'Cisco-IOS-XR-dot1x-oper', False, is_config=False),
            _MetaInfoClassMember('auth-bend-sm-state', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Auth back end SM State
                ''',
                'auth_bend_sm_state',
                'Cisco-IOS-XR-dot1x-oper', False, is_config=False),
            _MetaInfoClassMember('time-to-next-reauth', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                remaining time for next reauthentication
                ''',
                'time_to_next_reauth',
                'Cisco-IOS-XR-dot1x-oper', False, is_config=False),
            _MetaInfoClassMember('last-auth-time', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Last Authenticated Timestamp (formatted)
                ''',
                'last_auth_time',
                'Cisco-IOS-XR-dot1x-oper', False, is_config=False),
            _MetaInfoClassMember('last-auth-server', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Last Authenticated Server
                ''',
                'last_auth_server',
                'Cisco-IOS-XR-dot1x-oper', False, is_config=False),
            _MetaInfoClassMember('port-control', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Auth Client Port Control Status
                ''',
                'port_control',
                'Cisco-IOS-XR-dot1x-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-dot1x-oper',
            'client',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-dot1x-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_dot1x_oper',
            is_config=False,
        ),
    },
    'Dot1x.Session.InterfaceSessions.InterfaceSession.IntfInfo.AuthInfo' : {
        'meta_info' : _MetaInfoClass('Dot1x.Session.InterfaceSessions.InterfaceSession.IntfInfo.AuthInfo', REFERENCE_CLASS,
            '''Dot1x Authenticator info''',
            False, 
            [
            _MetaInfoClassMember('port-control', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Port Control Feature
                ''',
                'port_control',
                'Cisco-IOS-XR-dot1x-oper', False, is_config=False),
            _MetaInfoClassMember('reauth', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Re-Authentication enabled status
                ''',
                'reauth',
                'Cisco-IOS-XR-dot1x-oper', False, is_config=False),
            _MetaInfoClassMember('config-dependency', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Configuration Dependency 
                ''',
                'config_dependency',
                'Cisco-IOS-XR-dot1x-oper', False, is_config=False),
            _MetaInfoClassMember('eap-profile', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                EAP profile
                ''',
                'eap_profile',
                'Cisco-IOS-XR-dot1x-oper', False, is_config=False),
            _MetaInfoClassMember('client', REFERENCE_LIST, 'Client', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_dot1x_oper', 'Dot1x.Session.InterfaceSessions.InterfaceSession.IntfInfo.AuthInfo.Client',
                [], [],
                '''                Authenticator client list
                ''',
                'client',
                'Cisco-IOS-XR-dot1x-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-dot1x-oper',
            'auth-info',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-dot1x-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_dot1x_oper',
            is_config=False,
        ),
    },
    'Dot1x.Session.InterfaceSessions.InterfaceSession.IntfInfo.SuppInfo.Client' : {
        'meta_info' : _MetaInfoClass('Dot1x.Session.InterfaceSessions.InterfaceSession.IntfInfo.SuppInfo.Client', REFERENCE_LIST,
            '''Supp Client info''',
            False, 
            [
            _MetaInfoClassMember('mac', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                formatted MAC Address
                ''',
                'mac',
                'Cisco-IOS-XR-dot1x-oper', False, is_config=False),
            _MetaInfoClassMember('eap-method', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                EAP Method
                ''',
                'eap_method',
                'Cisco-IOS-XR-dot1x-oper', False, is_config=False),
            _MetaInfoClassMember('last-auth-time', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Last Authenticated Timestamp (formatted)
                ''',
                'last_auth_time',
                'Cisco-IOS-XR-dot1x-oper', False, is_config=False),
            _MetaInfoClassMember('auth-sm-state', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                supp SM State
                ''',
                'auth_sm_state',
                'Cisco-IOS-XR-dot1x-oper', False, is_config=False),
            _MetaInfoClassMember('auth-bend-sm-state', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                supp back end SM State
                ''',
                'auth_bend_sm_state',
                'Cisco-IOS-XR-dot1x-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-dot1x-oper',
            'client',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-dot1x-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_dot1x_oper',
            is_config=False,
        ),
    },
    'Dot1x.Session.InterfaceSessions.InterfaceSession.IntfInfo.SuppInfo' : {
        'meta_info' : _MetaInfoClass('Dot1x.Session.InterfaceSessions.InterfaceSession.IntfInfo.SuppInfo', REFERENCE_CLASS,
            '''Dot1x Supplicant info''',
            False, 
            [
            _MetaInfoClassMember('eap-profile', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                EAP profile
                ''',
                'eap_profile',
                'Cisco-IOS-XR-dot1x-oper', False, is_config=False),
            _MetaInfoClassMember('config-dependency', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Configuration Dependency 
                ''',
                'config_dependency',
                'Cisco-IOS-XR-dot1x-oper', False, is_config=False),
            _MetaInfoClassMember('client', REFERENCE_LIST, 'Client', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_dot1x_oper', 'Dot1x.Session.InterfaceSessions.InterfaceSession.IntfInfo.SuppInfo.Client',
                [], [],
                '''                Supp Client info
                ''',
                'client',
                'Cisco-IOS-XR-dot1x-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-dot1x-oper',
            'supp-info',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-dot1x-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_dot1x_oper',
            is_config=False,
        ),
    },
    'Dot1x.Session.InterfaceSessions.InterfaceSession.IntfInfo' : {
        'meta_info' : _MetaInfoClass('Dot1x.Session.InterfaceSessions.InterfaceSession.IntfInfo', REFERENCE_CLASS,
            '''Dot1x interface Info''',
            False, 
            [
            _MetaInfoClassMember('auth-info', REFERENCE_CLASS, 'AuthInfo', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_dot1x_oper', 'Dot1x.Session.InterfaceSessions.InterfaceSession.IntfInfo.AuthInfo',
                [], [],
                '''                Dot1x Authenticator info
                ''',
                'auth_info',
                'Cisco-IOS-XR-dot1x-oper', False, is_config=False),
            _MetaInfoClassMember('supp-info', REFERENCE_CLASS, 'SuppInfo', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_dot1x_oper', 'Dot1x.Session.InterfaceSessions.InterfaceSession.IntfInfo.SuppInfo',
                [], [],
                '''                Dot1x Supplicant info
                ''',
                'supp_info',
                'Cisco-IOS-XR-dot1x-oper', False, is_config=False),
            _MetaInfoClassMember('pae', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                PAE type on interface
                ''',
                'pae',
                'Cisco-IOS-XR-dot1x-oper', False, is_config=False),
            _MetaInfoClassMember('port-status', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Dot1x Port Status
                ''',
                'port_status',
                'Cisco-IOS-XR-dot1x-oper', False, is_config=False),
            _MetaInfoClassMember('dot1x-profile', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Dot1x Profile
                ''',
                'dot1x_profile',
                'Cisco-IOS-XR-dot1x-oper', False, is_config=False),
            _MetaInfoClassMember('l2-transport', ATTRIBUTE, 'bool', 'boolean',
                None, None,
                [], [],
                '''                L2 Transport Info
                ''',
                'l2_transport',
                'Cisco-IOS-XR-dot1x-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-dot1x-oper',
            'intf-info',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-dot1x-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_dot1x_oper',
            is_config=False,
        ),
    },
    'Dot1x.Session.InterfaceSessions.InterfaceSession.MkaStatusInfo' : {
        'meta_info' : _MetaInfoClass('Dot1x.Session.InterfaceSessions.InterfaceSession.MkaStatusInfo', REFERENCE_CLASS,
            '''MKA session secure status''',
            False, 
            [
            _MetaInfoClassMember('tie-break-role', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Dot1x Tie breaker role chosen for mka when PAE
                type is BOTH
                ''',
                'tie_break_role',
                'Cisco-IOS-XR-dot1x-oper', False, is_config=False),
            _MetaInfoClassMember('eap-based-macsec', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                EAP Mode status for MKA
                ''',
                'eap_based_macsec',
                'Cisco-IOS-XR-dot1x-oper', False, is_config=False),
            _MetaInfoClassMember('mka-start-time', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Time stamp when Dot1x posting a message to  MKA
                to start session.
                ''',
                'mka_start_time',
                'Cisco-IOS-XR-dot1x-oper', False, is_config=False),
            _MetaInfoClassMember('mka-stop-time', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Time stamp when Dot1x posting a message to  MKA
                to stop session.
                ''',
                'mka_stop_time',
                'Cisco-IOS-XR-dot1x-oper', False, is_config=False),
            _MetaInfoClassMember('mka-response-time', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Time Stamp of MKA acknowledgement to Dot1x
                ''',
                'mka_response_time',
                'Cisco-IOS-XR-dot1x-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-dot1x-oper',
            'mka-status-info',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-dot1x-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_dot1x_oper',
            is_config=False,
        ),
    },
    'Dot1x.Session.InterfaceSessions.InterfaceSession' : {
        'meta_info' : _MetaInfoClass('Dot1x.Session.InterfaceSessions.InterfaceSession', REFERENCE_LIST,
            '''Dot1x Data for that Interface''',
            False, 
            [
            _MetaInfoClassMember('name', ATTRIBUTE, 'str', 'xr:Interface-name',
                None, None,
                [], [b'[a-zA-Z0-9._/-]+'],
                '''                Interface Name
                ''',
                'name',
                'Cisco-IOS-XR-dot1x-oper', True, is_config=False),
            _MetaInfoClassMember('intf-info', REFERENCE_CLASS, 'IntfInfo', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_dot1x_oper', 'Dot1x.Session.InterfaceSessions.InterfaceSession.IntfInfo',
                [], [],
                '''                Dot1x interface Info
                ''',
                'intf_info',
                'Cisco-IOS-XR-dot1x-oper', False, is_config=False),
            _MetaInfoClassMember('mka-status-info', REFERENCE_CLASS, 'MkaStatusInfo', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_dot1x_oper', 'Dot1x.Session.InterfaceSessions.InterfaceSession.MkaStatusInfo',
                [], [],
                '''                MKA session secure status
                ''',
                'mka_status_info',
                'Cisco-IOS-XR-dot1x-oper', False, is_config=False),
            _MetaInfoClassMember('interface-name', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Interface Display name 
                ''',
                'interface_name',
                'Cisco-IOS-XR-dot1x-oper', False, is_config=False),
            _MetaInfoClassMember('interface-sname', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Interface Display short_name 
                ''',
                'interface_sname',
                'Cisco-IOS-XR-dot1x-oper', False, is_config=False),
            _MetaInfoClassMember('if-handle', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Interface handle
                ''',
                'if_handle',
                'Cisco-IOS-XR-dot1x-oper', False, is_config=False),
            _MetaInfoClassMember('mac', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                formatted MAC Address
                ''',
                'mac',
                'Cisco-IOS-XR-dot1x-oper', False, is_config=False),
            _MetaInfoClassMember('ethertype', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                EAPOL Ethertype
                ''',
                'ethertype',
                'Cisco-IOS-XR-dot1x-oper', False, is_config=False),
            _MetaInfoClassMember('eapol-addr', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                EAPOL Destination Address
                ''',
                'eapol_addr',
                'Cisco-IOS-XR-dot1x-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-dot1x-oper',
            'interface-session',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-dot1x-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_dot1x_oper',
            is_config=False,
        ),
    },
    'Dot1x.Session.InterfaceSessions' : {
        'meta_info' : _MetaInfoClass('Dot1x.Session.InterfaceSessions', REFERENCE_CLASS,
            '''Interfaces with Dot1x''',
            False, 
            [
            _MetaInfoClassMember('interface-session', REFERENCE_LIST, 'InterfaceSession', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_dot1x_oper', 'Dot1x.Session.InterfaceSessions.InterfaceSession',
                [], [],
                '''                Dot1x Data for that Interface
                ''',
                'interface_session',
                'Cisco-IOS-XR-dot1x-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-dot1x-oper',
            'interface-sessions',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-dot1x-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_dot1x_oper',
            is_config=False,
        ),
    },
    'Dot1x.Session' : {
        'meta_info' : _MetaInfoClass('Dot1x.Session', REFERENCE_CLASS,
            '''Dot1x operational data''',
            False, 
            [
            _MetaInfoClassMember('interface-sessions', REFERENCE_CLASS, 'InterfaceSessions', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_dot1x_oper', 'Dot1x.Session.InterfaceSessions',
                [], [],
                '''                Interfaces with Dot1x
                ''',
                'interface_sessions',
                'Cisco-IOS-XR-dot1x-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-dot1x-oper',
            'session',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-dot1x-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_dot1x_oper',
            is_config=False,
        ),
    },
    'Dot1x' : {
        'meta_info' : _MetaInfoClass('Dot1x', REFERENCE_CLASS,
            '''Dot1x operational data''',
            False, 
            [
            _MetaInfoClassMember('statistics', REFERENCE_CLASS, 'Statistics', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_dot1x_oper', 'Dot1x.Statistics',
                [], [],
                '''                Dot1x operational data
                ''',
                'statistics',
                'Cisco-IOS-XR-dot1x-oper', False, is_config=False),
            _MetaInfoClassMember('nodes', REFERENCE_CLASS, 'Nodes', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_dot1x_oper', 'Dot1x.Nodes',
                [], [],
                '''                Node-specific Dot1x operational data
                ''',
                'nodes',
                'Cisco-IOS-XR-dot1x-oper', False, is_config=False),
            _MetaInfoClassMember('session', REFERENCE_CLASS, 'Session', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_dot1x_oper', 'Dot1x.Session',
                [], [],
                '''                Dot1x operational data
                ''',
                'session',
                'Cisco-IOS-XR-dot1x-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-dot1x-oper',
            'dot1x',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-dot1x-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_dot1x_oper',
            is_config=False,
        ),
    },
}
_meta_table['Dot1x.Statistics.InterfaceStatistics.InterfaceStatistic.Auth.PortControl']['meta_info'].parent =_meta_table['Dot1x.Statistics.InterfaceStatistics.InterfaceStatistic.Auth']['meta_info']
_meta_table['Dot1x.Statistics.InterfaceStatistics.InterfaceStatistic.Idb']['meta_info'].parent =_meta_table['Dot1x.Statistics.InterfaceStatistics.InterfaceStatistic']['meta_info']
_meta_table['Dot1x.Statistics.InterfaceStatistics.InterfaceStatistic.Auth']['meta_info'].parent =_meta_table['Dot1x.Statistics.InterfaceStatistics.InterfaceStatistic']['meta_info']
_meta_table['Dot1x.Statistics.InterfaceStatistics.InterfaceStatistic.Supp']['meta_info'].parent =_meta_table['Dot1x.Statistics.InterfaceStatistics.InterfaceStatistic']['meta_info']
_meta_table['Dot1x.Statistics.InterfaceStatistics.InterfaceStatistic.LocalEap']['meta_info'].parent =_meta_table['Dot1x.Statistics.InterfaceStatistics.InterfaceStatistic']['meta_info']
_meta_table['Dot1x.Statistics.InterfaceStatistics.InterfaceStatistic']['meta_info'].parent =_meta_table['Dot1x.Statistics.InterfaceStatistics']['meta_info']
_meta_table['Dot1x.Statistics.InterfaceStatistics']['meta_info'].parent =_meta_table['Dot1x.Statistics']['meta_info']
_meta_table['Dot1x.Nodes.Node.Dot1xDefaults.AuthTimers']['meta_info'].parent =_meta_table['Dot1x.Nodes.Node.Dot1xDefaults']['meta_info']
_meta_table['Dot1x.Nodes.Node.Dot1xDefaults.SuppTimers']['meta_info'].parent =_meta_table['Dot1x.Nodes.Node.Dot1xDefaults']['meta_info']
_meta_table['Dot1x.Nodes.Node.Statistics.GlStats.PortControl']['meta_info'].parent =_meta_table['Dot1x.Nodes.Node.Statistics.GlStats']['meta_info']
_meta_table['Dot1x.Nodes.Node.Statistics.IfStats.Auth.PortControl']['meta_info'].parent =_meta_table['Dot1x.Nodes.Node.Statistics.IfStats.Auth']['meta_info']
_meta_table['Dot1x.Nodes.Node.Statistics.IfStats.Idb']['meta_info'].parent =_meta_table['Dot1x.Nodes.Node.Statistics.IfStats']['meta_info']
_meta_table['Dot1x.Nodes.Node.Statistics.IfStats.Auth']['meta_info'].parent =_meta_table['Dot1x.Nodes.Node.Statistics.IfStats']['meta_info']
_meta_table['Dot1x.Nodes.Node.Statistics.IfStats.Supp']['meta_info'].parent =_meta_table['Dot1x.Nodes.Node.Statistics.IfStats']['meta_info']
_meta_table['Dot1x.Nodes.Node.Statistics.IfStats.LocalEap']['meta_info'].parent =_meta_table['Dot1x.Nodes.Node.Statistics.IfStats']['meta_info']
_meta_table['Dot1x.Nodes.Node.Statistics.GlStats']['meta_info'].parent =_meta_table['Dot1x.Nodes.Node.Statistics']['meta_info']
_meta_table['Dot1x.Nodes.Node.Statistics.IfStats']['meta_info'].parent =_meta_table['Dot1x.Nodes.Node.Statistics']['meta_info']
_meta_table['Dot1x.Nodes.Node.Dot1xDefaults']['meta_info'].parent =_meta_table['Dot1x.Nodes.Node']['meta_info']
_meta_table['Dot1x.Nodes.Node.Statistics']['meta_info'].parent =_meta_table['Dot1x.Nodes.Node']['meta_info']
_meta_table['Dot1x.Nodes.Node']['meta_info'].parent =_meta_table['Dot1x.Nodes']['meta_info']
_meta_table['Dot1x.Session.InterfaceSessions.InterfaceSession.IntfInfo.AuthInfo.Client']['meta_info'].parent =_meta_table['Dot1x.Session.InterfaceSessions.InterfaceSession.IntfInfo.AuthInfo']['meta_info']
_meta_table['Dot1x.Session.InterfaceSessions.InterfaceSession.IntfInfo.SuppInfo.Client']['meta_info'].parent =_meta_table['Dot1x.Session.InterfaceSessions.InterfaceSession.IntfInfo.SuppInfo']['meta_info']
_meta_table['Dot1x.Session.InterfaceSessions.InterfaceSession.IntfInfo.AuthInfo']['meta_info'].parent =_meta_table['Dot1x.Session.InterfaceSessions.InterfaceSession.IntfInfo']['meta_info']
_meta_table['Dot1x.Session.InterfaceSessions.InterfaceSession.IntfInfo.SuppInfo']['meta_info'].parent =_meta_table['Dot1x.Session.InterfaceSessions.InterfaceSession.IntfInfo']['meta_info']
_meta_table['Dot1x.Session.InterfaceSessions.InterfaceSession.IntfInfo']['meta_info'].parent =_meta_table['Dot1x.Session.InterfaceSessions.InterfaceSession']['meta_info']
_meta_table['Dot1x.Session.InterfaceSessions.InterfaceSession.MkaStatusInfo']['meta_info'].parent =_meta_table['Dot1x.Session.InterfaceSessions.InterfaceSession']['meta_info']
_meta_table['Dot1x.Session.InterfaceSessions.InterfaceSession']['meta_info'].parent =_meta_table['Dot1x.Session.InterfaceSessions']['meta_info']
_meta_table['Dot1x.Session.InterfaceSessions']['meta_info'].parent =_meta_table['Dot1x.Session']['meta_info']
_meta_table['Dot1x.Statistics']['meta_info'].parent =_meta_table['Dot1x']['meta_info']
_meta_table['Dot1x.Nodes']['meta_info'].parent =_meta_table['Dot1x']['meta_info']
_meta_table['Dot1x.Session']['meta_info'].parent =_meta_table['Dot1x']['meta_info']
