
'''
This is auto-generated file,
which includes metadata for module Cisco_IOS_XR_sysadmin_cm
'''

from ydk._core._dm_meta_info import _MetaInfoClassMember, _MetaInfoClass, _MetaInfoEnum
from ydk._core._dm_meta_info import ATTRIBUTE, REFERENCE_LIST, REFERENCE_LEAFLIST, REFERENCE_BITS, REFERENCE_UNION
from ydk._core._dm_meta_info import REFERENCE_CLASS, REFERENCE_IDENTITY_CLASS, REFERENCE_ENUM_CLASS, ANYXML_CLASS
from ydk._core._importer import _yang_ns

_meta_table = {
    'AreaType' : _MetaInfoEnum('AreaType',
        'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_cm', 'AreaType',
        ''' ''',
        {
            'SYSTEM':'SYSTEM',
            'RACK':'RACK',
            'UNKNOWN':'UNKNOWN',
        }, 'Cisco-IOS-XR-sysadmin-cm', _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-sysadmin-cm']),
    'NodeInventory.Summary.NodeLocations.Nodei' : {
        'meta_info' : _MetaInfoClass('NodeInventory.Summary.NodeLocations.Nodei', REFERENCE_LIST,
            ''' ''',
            False, 
            [
            _MetaInfoClassMember('ip_address', REFERENCE_UNION, 'str', 'inet:ip-address',
                None, None,
                [], [],
                '''                IP address of the node
                ''',
                'ip_address',
                'Cisco-IOS-XR-sysadmin-cm', True, [
                    _MetaInfoClassMember('ip_address', ATTRIBUTE, 'str', 'inet:ipv4-address',
                        None, None,
                        [], [b'(([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])(%[\\p{N}\\p{L}]+)?'],
                        '''                        IP address of the node
                        ''',
                        'ip_address',
                        'Cisco-IOS-XR-sysadmin-cm', True, is_config=False),
                    _MetaInfoClassMember('ip_address', ATTRIBUTE, 'str', 'inet:ipv6-address',
                        None, None,
                        [], [b'((:|[0-9a-fA-F]{0,4}):)([0-9a-fA-F]{0,4}:){0,5}((([0-9a-fA-F]{0,4}:)?(:|[0-9a-fA-F]{0,4}))|(((25[0-5]|2[0-4][0-9]|[01]?[0-9]?[0-9])\\.){3}(25[0-5]|2[0-4][0-9]|[01]?[0-9]?[0-9])))(%[\\p{N}\\p{L}]+)?'],
                        '''                        IP address of the node
                        ''',
                        'ip_address',
                        'Cisco-IOS-XR-sysadmin-cm', True, is_config=False),
                ], is_config=False),
            _MetaInfoClassMember('type', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Node Type
                ''',
                'type',
                'Cisco-IOS-XR-sysadmin-cm', False, is_config=False),
            _MetaInfoClassMember('mac_address', ATTRIBUTE, 'str', 'yang:mac-address',
                None, None,
                [], [b'[0-9a-fA-F]{2}(:[0-9a-fA-F]{2}){5}'],
                '''                Node MAC
                ''',
                'mac_address',
                'Cisco-IOS-XR-sysadmin-cm', False, is_config=False),
            _MetaInfoClassMember('card_serial', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Card serial# the node belongs to
                ''',
                'card_serial',
                'Cisco-IOS-XR-sysadmin-cm', False, is_config=False),
            _MetaInfoClassMember('nti', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                Node NTI
                ''',
                'nti',
                'Cisco-IOS-XR-sysadmin-cm', False, is_config=False),
            ],
            'Cisco-IOS-XR-sysadmin-cm',
            'nodei',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-sysadmin-cm'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_cm',
            is_config=False,
        ),
    },
    'NodeInventory.Summary.NodeLocations' : {
        'meta_info' : _MetaInfoClass('NodeInventory.Summary.NodeLocations', REFERENCE_LIST,
            ''' ''',
            False, 
            [
            _MetaInfoClassMember('node_location', ATTRIBUTE, 'str', 'calvados:location-id',
                None, None,
                [], [b'((([bB][0-9])/(([a-zA-Z]){2}\\d{1,2}))|(([fF][0-7])/(([a-zA-Z]){2}\\d{1,2}))|((0?[0-9]|1[0-5])/((([a-zA-Z]){2,3})?\\d{1,2})))(/[cC][pP][uU]0)?'],
                '''                ''',
                'node_location',
                'Cisco-IOS-XR-sysadmin-cm', True, is_config=False),
            _MetaInfoClassMember('nodei', REFERENCE_LIST, 'Nodei', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_cm', 'NodeInventory.Summary.NodeLocations.Nodei',
                [], [],
                '''                ''',
                'nodei',
                'Cisco-IOS-XR-sysadmin-cm', False, is_config=False),
            ],
            'Cisco-IOS-XR-sysadmin-cm',
            'node_locations',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-sysadmin-cm'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_cm',
            is_config=False,
        ),
    },
    'NodeInventory.Summary' : {
        'meta_info' : _MetaInfoClass('NodeInventory.Summary', REFERENCE_CLASS,
            '''System Admin Manager Node Inventory. All accesses are
read-only. CLI show command looks like show node-inventory
location <location>''',
            False, 
            [
            _MetaInfoClassMember('node_locations', REFERENCE_LIST, 'NodeLocations', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_cm', 'NodeInventory.Summary.NodeLocations',
                [], [],
                '''                ''',
                'node_locations',
                'Cisco-IOS-XR-sysadmin-cm', False, is_config=False),
            ],
            'Cisco-IOS-XR-sysadmin-cm',
            'summary',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-sysadmin-cm'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_cm',
            is_config=False,
        ),
    },
    'NodeInventory.Detail.NodeLocations.Nodei' : {
        'meta_info' : _MetaInfoClass('NodeInventory.Detail.NodeLocations.Nodei', REFERENCE_LIST,
            ''' ''',
            False, 
            [
            _MetaInfoClassMember('ip_address', REFERENCE_UNION, 'str', 'inet:ip-address',
                None, None,
                [], [],
                '''                IP address of the node
                ''',
                'ip_address',
                'Cisco-IOS-XR-sysadmin-cm', True, [
                    _MetaInfoClassMember('ip_address', ATTRIBUTE, 'str', 'inet:ipv4-address',
                        None, None,
                        [], [b'(([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])(%[\\p{N}\\p{L}]+)?'],
                        '''                        IP address of the node
                        ''',
                        'ip_address',
                        'Cisco-IOS-XR-sysadmin-cm', True, is_config=False),
                    _MetaInfoClassMember('ip_address', ATTRIBUTE, 'str', 'inet:ipv6-address',
                        None, None,
                        [], [b'((:|[0-9a-fA-F]{0,4}):)([0-9a-fA-F]{0,4}:){0,5}((([0-9a-fA-F]{0,4}:)?(:|[0-9a-fA-F]{0,4}))|(((25[0-5]|2[0-4][0-9]|[01]?[0-9]?[0-9])\\.){3}(25[0-5]|2[0-4][0-9]|[01]?[0-9]?[0-9])))(%[\\p{N}\\p{L}]+)?'],
                        '''                        IP address of the node
                        ''',
                        'ip_address',
                        'Cisco-IOS-XR-sysadmin-cm', True, is_config=False),
                ], is_config=False),
            _MetaInfoClassMember('type', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Node Type
                ''',
                'type',
                'Cisco-IOS-XR-sysadmin-cm', False, is_config=False),
            _MetaInfoClassMember('mac_address', ATTRIBUTE, 'str', 'yang:mac-address',
                None, None,
                [], [b'[0-9a-fA-F]{2}(:[0-9a-fA-F]{2}){5}'],
                '''                Node MAC
                ''',
                'mac_address',
                'Cisco-IOS-XR-sysadmin-cm', False, is_config=False),
            _MetaInfoClassMember('card_serial', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Card serial# the node belongs to
                ''',
                'card_serial',
                'Cisco-IOS-XR-sysadmin-cm', False, is_config=False),
            _MetaInfoClassMember('nti', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                Node NTI
                ''',
                'nti',
                'Cisco-IOS-XR-sysadmin-cm', False, is_config=False),
            _MetaInfoClassMember('restart', ATTRIBUTE, 'bool', 'boolean',
                None, None,
                [], [],
                '''                Node in Restart
                ''',
                'restart',
                'Cisco-IOS-XR-sysadmin-cm', False, is_config=False),
            _MetaInfoClassMember('data', ATTRIBUTE, 'str', 'hex8ValueType',
                None, None,
                [], [],
                '''                Node Data
                ''',
                'data',
                'Cisco-IOS-XR-sysadmin-cm', False, is_config=False),
            _MetaInfoClassMember('sdr', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                SDR Name the node belongs to
                ''',
                'sdr',
                'Cisco-IOS-XR-sysadmin-cm', False, is_config=False),
            ],
            'Cisco-IOS-XR-sysadmin-cm',
            'nodei',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-sysadmin-cm'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_cm',
            is_config=False,
        ),
    },
    'NodeInventory.Detail.NodeLocations' : {
        'meta_info' : _MetaInfoClass('NodeInventory.Detail.NodeLocations', REFERENCE_LIST,
            ''' ''',
            False, 
            [
            _MetaInfoClassMember('node_location', ATTRIBUTE, 'str', 'calvados:location-id',
                None, None,
                [], [b'((([bB][0-9])/(([a-zA-Z]){2}\\d{1,2}))|(([fF][0-7])/(([a-zA-Z]){2}\\d{1,2}))|((0?[0-9]|1[0-5])/((([a-zA-Z]){2,3})?\\d{1,2})))(/[cC][pP][uU]0)?'],
                '''                ''',
                'node_location',
                'Cisco-IOS-XR-sysadmin-cm', True, is_config=False),
            _MetaInfoClassMember('nodei', REFERENCE_LIST, 'Nodei', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_cm', 'NodeInventory.Detail.NodeLocations.Nodei',
                [], [],
                '''                ''',
                'nodei',
                'Cisco-IOS-XR-sysadmin-cm', False, is_config=False),
            ],
            'Cisco-IOS-XR-sysadmin-cm',
            'node_locations',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-sysadmin-cm'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_cm',
            is_config=False,
        ),
    },
    'NodeInventory.Detail' : {
        'meta_info' : _MetaInfoClass('NodeInventory.Detail', REFERENCE_CLASS,
            '''System Admin Manager Node Inventory. All accesses are
read-only. CLI show command looks like show node-inventory
location <location>''',
            False, 
            [
            _MetaInfoClassMember('node_locations', REFERENCE_LIST, 'NodeLocations', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_cm', 'NodeInventory.Detail.NodeLocations',
                [], [],
                '''                ''',
                'node_locations',
                'Cisco-IOS-XR-sysadmin-cm', False, is_config=False),
            ],
            'Cisco-IOS-XR-sysadmin-cm',
            'detail',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-sysadmin-cm'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_cm',
            is_config=False,
        ),
    },
    'NodeInventory' : {
        'meta_info' : _MetaInfoClass('NodeInventory', REFERENCE_CLASS,
            '''System Admin Manager Node Inventory. All accesses are
read-only. CLI show command looks like show node-inventory
location <location>''',
            False, 
            [
            _MetaInfoClassMember('summary', REFERENCE_CLASS, 'Summary', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_cm', 'NodeInventory.Summary',
                [], [],
                '''                System Admin Manager Node Inventory. All accesses are
                read-only. CLI show command looks like show node-inventory
                location <location>
                ''',
                'summary',
                'Cisco-IOS-XR-sysadmin-cm', False, is_config=False),
            _MetaInfoClassMember('detail', REFERENCE_CLASS, 'Detail', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_cm', 'NodeInventory.Detail',
                [], [],
                '''                System Admin Manager Node Inventory. All accesses are
                read-only. CLI show command looks like show node-inventory
                location <location>
                ''',
                'detail',
                'Cisco-IOS-XR-sysadmin-cm', False, is_config=False),
            ],
            'Cisco-IOS-XR-sysadmin-cm',
            'node-inventory',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-sysadmin-cm'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_cm',
            is_config=False,
        ),
    },
    'CardInventory.CardLocations.Cardi' : {
        'meta_info' : _MetaInfoClass('CardInventory.CardLocations.Cardi', REFERENCE_LIST,
            ''' ''',
            False, 
            [
            _MetaInfoClassMember('card_serial', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Serial Number of the Card
                ''',
                'card_serial',
                'Cisco-IOS-XR-sysadmin-cm', True, is_config=False),
            _MetaInfoClassMember('node_id', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Node name
                ''',
                'node_id',
                'Cisco-IOS-XR-sysadmin-cm', False, is_config=False),
            _MetaInfoClassMember('card_type', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Card Type
                ''',
                'card_type',
                'Cisco-IOS-XR-sysadmin-cm', False, is_config=False),
            _MetaInfoClassMember('hw_state', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Card State
                ''',
                'hw_state',
                'Cisco-IOS-XR-sysadmin-cm', False, is_config=False),
            _MetaInfoClassMember('sw_state', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Card Software State
                ''',
                'sw_state',
                'Cisco-IOS-XR-sysadmin-cm', False, is_config=False),
            _MetaInfoClassMember('slot', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                Card Slot Number
                ''',
                'slot',
                'Cisco-IOS-XR-sysadmin-cm', False, is_config=False),
            _MetaInfoClassMember('cti', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                Card CTI
                ''',
                'cti',
                'Cisco-IOS-XR-sysadmin-cm', False, is_config=False),
            ],
            'Cisco-IOS-XR-sysadmin-cm',
            'cardi',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-sysadmin-cm'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_cm',
            is_config=False,
        ),
    },
    'CardInventory.CardLocations' : {
        'meta_info' : _MetaInfoClass('CardInventory.CardLocations', REFERENCE_LIST,
            ''' ''',
            False, 
            [
            _MetaInfoClassMember('card_location', ATTRIBUTE, 'str', 'calvados:location-id',
                None, None,
                [], [b'((([bB][0-9])/(([a-zA-Z]){2}\\d{1,2}))|(([fF][0-7])/(([a-zA-Z]){2}\\d{1,2}))|((0?[0-9]|1[0-5])/((([a-zA-Z]){2,3})?\\d{1,2})))(/[cC][pP][uU]0)?'],
                '''                ''',
                'card_location',
                'Cisco-IOS-XR-sysadmin-cm', True, is_config=False),
            _MetaInfoClassMember('cardi', REFERENCE_LIST, 'Cardi', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_cm', 'CardInventory.CardLocations.Cardi',
                [], [],
                '''                ''',
                'cardi',
                'Cisco-IOS-XR-sysadmin-cm', False, is_config=False),
            ],
            'Cisco-IOS-XR-sysadmin-cm',
            'card_locations',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-sysadmin-cm'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_cm',
            is_config=False,
        ),
    },
    'CardInventory' : {
        'meta_info' : _MetaInfoClass('CardInventory', REFERENCE_CLASS,
            '''System Admin Manager Card Inventory. All accesses are
read-only. CLI show command looks like show card-inventory
location <location>''',
            False, 
            [
            _MetaInfoClassMember('card_locations', REFERENCE_LIST, 'CardLocations', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_cm', 'CardInventory.CardLocations',
                [], [],
                '''                ''',
                'card_locations',
                'Cisco-IOS-XR-sysadmin-cm', False, is_config=False),
            ],
            'Cisco-IOS-XR-sysadmin-cm',
            'card-inventory',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-sysadmin-cm'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_cm',
            is_config=False,
        ),
    },
    'RackInventory.RackLocations.Racki' : {
        'meta_info' : _MetaInfoClass('RackInventory.RackLocations.Racki', REFERENCE_LIST,
            ''' ''',
            False, 
            [
            _MetaInfoClassMember('rack_serial', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Serial Number of the Rack
                ''',
                'rack_serial',
                'Cisco-IOS-XR-sysadmin-cm', True, is_config=False),
            _MetaInfoClassMember('rack_number', ATTRIBUTE, 'int', 'int32',
                None, None,
                [('-2147483648', '2147483647')], [],
                '''                Rack Number
                ''',
                'rack_number',
                'Cisco-IOS-XR-sysadmin-cm', False, is_config=False),
            _MetaInfoClassMember('rack_state', ATTRIBUTE, 'int', 'int32',
                None, None,
                [('-2147483648', '2147483647')], [],
                '''                Rack State
                ''',
                'rack_state',
                'Cisco-IOS-XR-sysadmin-cm', False, is_config=False),
            ],
            'Cisco-IOS-XR-sysadmin-cm',
            'racki',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-sysadmin-cm'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_cm',
            is_config=False,
        ),
    },
    'RackInventory.RackLocations' : {
        'meta_info' : _MetaInfoClass('RackInventory.RackLocations', REFERENCE_LIST,
            ''' ''',
            False, 
            [
            _MetaInfoClassMember('rack_location', ATTRIBUTE, 'str', 'calvados:location-id',
                None, None,
                [], [b'((([bB][0-9])/(([a-zA-Z]){2}\\d{1,2}))|(([fF][0-7])/(([a-zA-Z]){2}\\d{1,2}))|((0?[0-9]|1[0-5])/((([a-zA-Z]){2,3})?\\d{1,2})))(/[cC][pP][uU]0)?'],
                '''                ''',
                'rack_location',
                'Cisco-IOS-XR-sysadmin-cm', True, is_config=False),
            _MetaInfoClassMember('racki', REFERENCE_LIST, 'Racki', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_cm', 'RackInventory.RackLocations.Racki',
                [], [],
                '''                ''',
                'racki',
                'Cisco-IOS-XR-sysadmin-cm', False, is_config=False),
            ],
            'Cisco-IOS-XR-sysadmin-cm',
            'rack_locations',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-sysadmin-cm'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_cm',
            is_config=False,
        ),
    },
    'RackInventory' : {
        'meta_info' : _MetaInfoClass('RackInventory', REFERENCE_CLASS,
            '''System Admin Manager Rack Inventory''',
            False, 
            [
            _MetaInfoClassMember('rack_locations', REFERENCE_LIST, 'RackLocations', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_cm', 'RackInventory.RackLocations',
                [], [],
                '''                ''',
                'rack_locations',
                'Cisco-IOS-XR-sysadmin-cm', False, is_config=False),
            ],
            'Cisco-IOS-XR-sysadmin-cm',
            'rack-inventory',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-sysadmin-cm'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_cm',
            is_config=False,
        ),
    },
    'SystemServiceInventory.SsvcLocations.Ssvci' : {
        'meta_info' : _MetaInfoClass('SystemServiceInventory.SsvcLocations.Ssvci', REFERENCE_LIST,
            ''' ''',
            False, 
            [
            _MetaInfoClassMember('svc_name', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Service Name
                ''',
                'svc_name',
                'Cisco-IOS-XR-sysadmin-cm', True, is_config=False),
            _MetaInfoClassMember('placement_first', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Serial Number of the first card selected
                ''',
                'placement_first',
                'Cisco-IOS-XR-sysadmin-cm', False, is_config=False),
            _MetaInfoClassMember('nodeid_first', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Node id of the first card selected
                ''',
                'nodeid_first',
                'Cisco-IOS-XR-sysadmin-cm', False, is_config=False),
            _MetaInfoClassMember('placement_second', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Serial Number of the second card selected
                ''',
                'placement_second',
                'Cisco-IOS-XR-sysadmin-cm', False, is_config=False),
            _MetaInfoClassMember('nodeid_second', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Node id of the second card selected
                ''',
                'nodeid_second',
                'Cisco-IOS-XR-sysadmin-cm', False, is_config=False),
            _MetaInfoClassMember('svc_load', ATTRIBUTE, 'int', 'uint8',
                None, None,
                [('0', '255')], [],
                '''                Service Load
                ''',
                'svc_load',
                'Cisco-IOS-XR-sysadmin-cm', False, is_config=False),
            ],
            'Cisco-IOS-XR-sysadmin-cm',
            'ssvci',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-sysadmin-cm'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_cm',
            is_config=False,
        ),
    },
    'SystemServiceInventory.SsvcLocations' : {
        'meta_info' : _MetaInfoClass('SystemServiceInventory.SsvcLocations', REFERENCE_LIST,
            ''' ''',
            False, 
            [
            _MetaInfoClassMember('ssvc_location', ATTRIBUTE, 'str', 'calvados:location-id',
                None, None,
                [], [b'((([bB][0-9])/(([a-zA-Z]){2}\\d{1,2}))|(([fF][0-7])/(([a-zA-Z]){2}\\d{1,2}))|((0?[0-9]|1[0-5])/((([a-zA-Z]){2,3})?\\d{1,2})))(/[cC][pP][uU]0)?'],
                '''                ''',
                'ssvc_location',
                'Cisco-IOS-XR-sysadmin-cm', True, is_config=False),
            _MetaInfoClassMember('ssvci', REFERENCE_LIST, 'Ssvci', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_cm', 'SystemServiceInventory.SsvcLocations.Ssvci',
                [], [],
                '''                ''',
                'ssvci',
                'Cisco-IOS-XR-sysadmin-cm', False, is_config=False),
            ],
            'Cisco-IOS-XR-sysadmin-cm',
            'ssvc_locations',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-sysadmin-cm'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_cm',
            is_config=False,
        ),
    },
    'SystemServiceInventory' : {
        'meta_info' : _MetaInfoClass('SystemServiceInventory', REFERENCE_CLASS,
            '''System Admin Manager System Services Inventory''',
            False, 
            [
            _MetaInfoClassMember('ssvc_locations', REFERENCE_LIST, 'SsvcLocations', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_cm', 'SystemServiceInventory.SsvcLocations',
                [], [],
                '''                ''',
                'ssvc_locations',
                'Cisco-IOS-XR-sysadmin-cm', False, is_config=False),
            ],
            'Cisco-IOS-XR-sysadmin-cm',
            'system-service-inventory',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-sysadmin-cm'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_cm',
            is_config=False,
        ),
    },
    'RackServiceInventory.RsvcLocations.Rsvci' : {
        'meta_info' : _MetaInfoClass('RackServiceInventory.RsvcLocations.Rsvci', REFERENCE_LIST,
            ''' ''',
            False, 
            [
            _MetaInfoClassMember('svc_name', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Service Name
                ''',
                'svc_name',
                'Cisco-IOS-XR-sysadmin-cm', True, is_config=False),
            _MetaInfoClassMember('placement_first', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Serial Number of the first card selected
                ''',
                'placement_first',
                'Cisco-IOS-XR-sysadmin-cm', False, is_config=False),
            _MetaInfoClassMember('nodeid_first', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Node id of the first card selected
                ''',
                'nodeid_first',
                'Cisco-IOS-XR-sysadmin-cm', False, is_config=False),
            _MetaInfoClassMember('placement_second', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Serial Number of the second card selected
                ''',
                'placement_second',
                'Cisco-IOS-XR-sysadmin-cm', False, is_config=False),
            _MetaInfoClassMember('nodeid_second', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Node id of the second card selected
                ''',
                'nodeid_second',
                'Cisco-IOS-XR-sysadmin-cm', False, is_config=False),
            _MetaInfoClassMember('svc_load', ATTRIBUTE, 'int', 'uint8',
                None, None,
                [('0', '255')], [],
                '''                Service Load
                ''',
                'svc_load',
                'Cisco-IOS-XR-sysadmin-cm', False, is_config=False),
            ],
            'Cisco-IOS-XR-sysadmin-cm',
            'rsvci',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-sysadmin-cm'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_cm',
            is_config=False,
        ),
    },
    'RackServiceInventory.RsvcLocations' : {
        'meta_info' : _MetaInfoClass('RackServiceInventory.RsvcLocations', REFERENCE_LIST,
            ''' ''',
            False, 
            [
            _MetaInfoClassMember('rsvc_location', ATTRIBUTE, 'str', 'calvados:location-id',
                None, None,
                [], [b'((([bB][0-9])/(([a-zA-Z]){2}\\d{1,2}))|(([fF][0-7])/(([a-zA-Z]){2}\\d{1,2}))|((0?[0-9]|1[0-5])/((([a-zA-Z]){2,3})?\\d{1,2})))(/[cC][pP][uU]0)?'],
                '''                ''',
                'rsvc_location',
                'Cisco-IOS-XR-sysadmin-cm', True, is_config=False),
            _MetaInfoClassMember('rsvci', REFERENCE_LIST, 'Rsvci', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_cm', 'RackServiceInventory.RsvcLocations.Rsvci',
                [], [],
                '''                ''',
                'rsvci',
                'Cisco-IOS-XR-sysadmin-cm', False, is_config=False),
            ],
            'Cisco-IOS-XR-sysadmin-cm',
            'rsvc_locations',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-sysadmin-cm'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_cm',
            is_config=False,
        ),
    },
    'RackServiceInventory' : {
        'meta_info' : _MetaInfoClass('RackServiceInventory', REFERENCE_CLASS,
            '''System Admin Manager Rack Services Inventory''',
            False, 
            [
            _MetaInfoClassMember('rsvc_locations', REFERENCE_LIST, 'RsvcLocations', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_cm', 'RackServiceInventory.RsvcLocations',
                [], [],
                '''                ''',
                'rsvc_locations',
                'Cisco-IOS-XR-sysadmin-cm', False, is_config=False),
            ],
            'Cisco-IOS-XR-sysadmin-cm',
            'rack-service-inventory',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-sysadmin-cm'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_cm',
            is_config=False,
        ),
    },
    'SdrInventory.SdrLocations.Sdri' : {
        'meta_info' : _MetaInfoClass('SdrInventory.SdrLocations.Sdri', REFERENCE_LIST,
            ''' ''',
            False, 
            [
            _MetaInfoClassMember('sdr_name', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                SDR NAME
                ''',
                'sdr_name',
                'Cisco-IOS-XR-sysadmin-cm', True, is_config=False),
            _MetaInfoClassMember('sdr_id', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                SDR ID
                ''',
                'sdr_id',
                'Cisco-IOS-XR-sysadmin-cm', False, is_config=False),
            _MetaInfoClassMember('sdr_vlan_baseid', ATTRIBUTE, 'int', 'uint8',
                None, None,
                [('0', '255')], [],
                '''                SDR VLAN ID
                ''',
                'sdr_vlan_baseid',
                'Cisco-IOS-XR-sysadmin-cm', False, is_config=False),
            _MetaInfoClassMember('sdr_version', ATTRIBUTE, 'int', 'uint64',
                None, None,
                [('0', '18446744073709551615')], [],
                '''                SDR Image Version
                ''',
                'sdr_version',
                'Cisco-IOS-XR-sysadmin-cm', False, is_config=False),
            ],
            'Cisco-IOS-XR-sysadmin-cm',
            'sdri',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-sysadmin-cm'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_cm',
            is_config=False,
        ),
    },
    'SdrInventory.SdrLocations' : {
        'meta_info' : _MetaInfoClass('SdrInventory.SdrLocations', REFERENCE_LIST,
            ''' ''',
            False, 
            [
            _MetaInfoClassMember('sdr_location', ATTRIBUTE, 'str', 'calvados:location-id',
                None, None,
                [], [b'((([bB][0-9])/(([a-zA-Z]){2}\\d{1,2}))|(([fF][0-7])/(([a-zA-Z]){2}\\d{1,2}))|((0?[0-9]|1[0-5])/((([a-zA-Z]){2,3})?\\d{1,2})))(/[cC][pP][uU]0)?'],
                '''                ''',
                'sdr_location',
                'Cisco-IOS-XR-sysadmin-cm', True, is_config=False),
            _MetaInfoClassMember('sdri', REFERENCE_LIST, 'Sdri', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_cm', 'SdrInventory.SdrLocations.Sdri',
                [], [],
                '''                ''',
                'sdri',
                'Cisco-IOS-XR-sysadmin-cm', False, is_config=False),
            ],
            'Cisco-IOS-XR-sysadmin-cm',
            'sdr_locations',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-sysadmin-cm'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_cm',
            is_config=False,
        ),
    },
    'SdrInventory' : {
        'meta_info' : _MetaInfoClass('SdrInventory', REFERENCE_CLASS,
            '''System Admin Manager SDR Inventory''',
            False, 
            [
            _MetaInfoClassMember('sdr_locations', REFERENCE_LIST, 'SdrLocations', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_cm', 'SdrInventory.SdrLocations',
                [], [],
                '''                ''',
                'sdr_locations',
                'Cisco-IOS-XR-sysadmin-cm', False, is_config=False),
            ],
            'Cisco-IOS-XR-sysadmin-cm',
            'sdr-inventory',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-sysadmin-cm'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_cm',
            is_config=False,
        ),
    },
    'LeaderStatistics.LdrLocations' : {
        'meta_info' : _MetaInfoClass('LeaderStatistics.LdrLocations', REFERENCE_LIST,
            ''' ''',
            False, 
            [
            _MetaInfoClassMember('ldr_location', ATTRIBUTE, 'str', 'calvados:location-id',
                None, None,
                [], [b'((([bB][0-9])/(([a-zA-Z]){2}\\d{1,2}))|(([fF][0-7])/(([a-zA-Z]){2}\\d{1,2}))|((0?[0-9]|1[0-5])/((([a-zA-Z]){2,3})?\\d{1,2})))(/[cC][pP][uU]0)?'],
                '''                ''',
                'ldr_location',
                'Cisco-IOS-XR-sysadmin-cm', True, is_config=False),
            _MetaInfoClassMember('syslead', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Primary System Leader
                ''',
                'syslead',
                'Cisco-IOS-XR-sysadmin-cm', False, is_config=False),
            _MetaInfoClassMember('bkup_syslead', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Backup System Leader
                ''',
                'bkup_syslead',
                'Cisco-IOS-XR-sysadmin-cm', False, is_config=False),
            _MetaInfoClassMember('racklead', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Primary Rack Leader
                ''',
                'racklead',
                'Cisco-IOS-XR-sysadmin-cm', False, is_config=False),
            _MetaInfoClassMember('bkup_racklead', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Backup Rack Leader
                ''',
                'bkup_racklead',
                'Cisco-IOS-XR-sysadmin-cm', False, is_config=False),
            _MetaInfoClassMember('l1_dis', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                L1 DIS
                ''',
                'l1_dis',
                'Cisco-IOS-XR-sysadmin-cm', False, is_config=False),
            _MetaInfoClassMember('l2_dis', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                L2 DIS
                ''',
                'l2_dis',
                'Cisco-IOS-XR-sysadmin-cm', False, is_config=False),
            ],
            'Cisco-IOS-XR-sysadmin-cm',
            'ldr_locations',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-sysadmin-cm'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_cm',
            is_config=False,
        ),
    },
    'LeaderStatistics' : {
        'meta_info' : _MetaInfoClass('LeaderStatistics', REFERENCE_CLASS,
            '''System Admin Manager Leader Statistics''',
            False, 
            [
            _MetaInfoClassMember('ldr_locations', REFERENCE_LIST, 'LdrLocations', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_cm', 'LeaderStatistics.LdrLocations',
                [], [],
                '''                ''',
                'ldr_locations',
                'Cisco-IOS-XR-sysadmin-cm', False, is_config=False),
            ],
            'Cisco-IOS-XR-sysadmin-cm',
            'leader-statistics',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-sysadmin-cm'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_cm',
            is_config=False,
        ),
    },
    'TopologyNeighbors.NbrLocations.Nbri' : {
        'meta_info' : _MetaInfoClass('TopologyNeighbors.NbrLocations.Nbri', REFERENCE_LIST,
            ''' ''',
            False, 
            [
            _MetaInfoClassMember('nbr_system_id', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Neighbor System ID
                ''',
                'nbr_system_id',
                'Cisco-IOS-XR-sysadmin-cm', True, is_config=False),
            _MetaInfoClassMember('nbr_area_type', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Neighbor Area Type
                ''',
                'nbr_area_type',
                'Cisco-IOS-XR-sysadmin-cm', True, is_config=False),
            _MetaInfoClassMember('nbr_interface', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Adjacency Interface
                ''',
                'nbr_interface',
                'Cisco-IOS-XR-sysadmin-cm', False, is_config=False),
            _MetaInfoClassMember('nbr_state', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Neighbor State
                ''',
                'nbr_state',
                'Cisco-IOS-XR-sysadmin-cm', False, is_config=False),
            _MetaInfoClassMember('nbr_holdtime', ATTRIBUTE, 'int', 'uint64',
                None, None,
                [('0', '18446744073709551615')], [],
                '''                Neighbor Hold Time
                ''',
                'nbr_holdtime',
                'Cisco-IOS-XR-sysadmin-cm', False, is_config=False),
            _MetaInfoClassMember('nbr_uptime', ATTRIBUTE, 'str', 'xs:duration',
                None, None,
                [], [],
                '''                Neighbor Up Time
                ''',
                'nbr_uptime',
                'Cisco-IOS-XR-sysadmin-cm', False, is_config=False),
            ],
            'Cisco-IOS-XR-sysadmin-cm',
            'nbri',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-sysadmin-cm'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_cm',
            is_config=False,
        ),
    },
    'TopologyNeighbors.NbrLocations' : {
        'meta_info' : _MetaInfoClass('TopologyNeighbors.NbrLocations', REFERENCE_LIST,
            ''' ''',
            False, 
            [
            _MetaInfoClassMember('nbr_location', ATTRIBUTE, 'str', 'calvados:location-id',
                None, None,
                [], [b'((([bB][0-9])/(([a-zA-Z]){2}\\d{1,2}))|(([fF][0-7])/(([a-zA-Z]){2}\\d{1,2}))|((0?[0-9]|1[0-5])/((([a-zA-Z]){2,3})?\\d{1,2})))(/[cC][pP][uU]0)?'],
                '''                ''',
                'nbr_location',
                'Cisco-IOS-XR-sysadmin-cm', True, is_config=False),
            _MetaInfoClassMember('nbri', REFERENCE_LIST, 'Nbri', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_cm', 'TopologyNeighbors.NbrLocations.Nbri',
                [], [],
                '''                ''',
                'nbri',
                'Cisco-IOS-XR-sysadmin-cm', False, is_config=False),
            ],
            'Cisco-IOS-XR-sysadmin-cm',
            'nbr_locations',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-sysadmin-cm'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_cm',
            is_config=False,
        ),
    },
    'TopologyNeighbors' : {
        'meta_info' : _MetaInfoClass('TopologyNeighbors', REFERENCE_CLASS,
            '''System Admin Manager Neighbors of a location''',
            False, 
            [
            _MetaInfoClassMember('nbr_locations', REFERENCE_LIST, 'NbrLocations', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_cm', 'TopologyNeighbors.NbrLocations',
                [], [],
                '''                ''',
                'nbr_locations',
                'Cisco-IOS-XR-sysadmin-cm', False, is_config=False),
            ],
            'Cisco-IOS-XR-sysadmin-cm',
            'topology-neighbors',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-sysadmin-cm'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_cm',
            is_config=False,
        ),
    },
    'Placement' : {
        'meta_info' : _MetaInfoClass('Placement', REFERENCE_CLASS,
            ''' ''',
            False, 
            [
            ],
            'Cisco-IOS-XR-sysadmin-cm',
            'placement',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-sysadmin-cm'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_cm',
        ),
    },
}
_meta_table['NodeInventory.Summary.NodeLocations.Nodei']['meta_info'].parent =_meta_table['NodeInventory.Summary.NodeLocations']['meta_info']
_meta_table['NodeInventory.Summary.NodeLocations']['meta_info'].parent =_meta_table['NodeInventory.Summary']['meta_info']
_meta_table['NodeInventory.Detail.NodeLocations.Nodei']['meta_info'].parent =_meta_table['NodeInventory.Detail.NodeLocations']['meta_info']
_meta_table['NodeInventory.Detail.NodeLocations']['meta_info'].parent =_meta_table['NodeInventory.Detail']['meta_info']
_meta_table['NodeInventory.Summary']['meta_info'].parent =_meta_table['NodeInventory']['meta_info']
_meta_table['NodeInventory.Detail']['meta_info'].parent =_meta_table['NodeInventory']['meta_info']
_meta_table['CardInventory.CardLocations.Cardi']['meta_info'].parent =_meta_table['CardInventory.CardLocations']['meta_info']
_meta_table['CardInventory.CardLocations']['meta_info'].parent =_meta_table['CardInventory']['meta_info']
_meta_table['RackInventory.RackLocations.Racki']['meta_info'].parent =_meta_table['RackInventory.RackLocations']['meta_info']
_meta_table['RackInventory.RackLocations']['meta_info'].parent =_meta_table['RackInventory']['meta_info']
_meta_table['SystemServiceInventory.SsvcLocations.Ssvci']['meta_info'].parent =_meta_table['SystemServiceInventory.SsvcLocations']['meta_info']
_meta_table['SystemServiceInventory.SsvcLocations']['meta_info'].parent =_meta_table['SystemServiceInventory']['meta_info']
_meta_table['RackServiceInventory.RsvcLocations.Rsvci']['meta_info'].parent =_meta_table['RackServiceInventory.RsvcLocations']['meta_info']
_meta_table['RackServiceInventory.RsvcLocations']['meta_info'].parent =_meta_table['RackServiceInventory']['meta_info']
_meta_table['SdrInventory.SdrLocations.Sdri']['meta_info'].parent =_meta_table['SdrInventory.SdrLocations']['meta_info']
_meta_table['SdrInventory.SdrLocations']['meta_info'].parent =_meta_table['SdrInventory']['meta_info']
_meta_table['LeaderStatistics.LdrLocations']['meta_info'].parent =_meta_table['LeaderStatistics']['meta_info']
_meta_table['TopologyNeighbors.NbrLocations.Nbri']['meta_info'].parent =_meta_table['TopologyNeighbors.NbrLocations']['meta_info']
_meta_table['TopologyNeighbors.NbrLocations']['meta_info'].parent =_meta_table['TopologyNeighbors']['meta_info']
