
'''
This is auto-generated file,
which includes metadata for module Cisco_IOS_XR_nto_misc_oper
'''

from ydk._core._dm_meta_info import _MetaInfoClassMember, _MetaInfoClass, _MetaInfoEnum
from ydk._core._dm_meta_info import ATTRIBUTE, REFERENCE_LIST, REFERENCE_LEAFLIST, REFERENCE_BITS, REFERENCE_UNION
from ydk._core._dm_meta_info import REFERENCE_CLASS, REFERENCE_IDENTITY_CLASS, REFERENCE_ENUM_CLASS, ANYXML_CLASS
from ydk._core._importer import _yang_ns

_meta_table = {
    'MemorySummary.Nodes.Node.Summary' : {
        'meta_info' : _MetaInfoClass('MemorySummary.Nodes.Node.Summary', REFERENCE_CLASS,
            '''Memory summary information for a specific node''',
            False, 
            [
            _MetaInfoClassMember('page-size', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                Page size in bytes
                ''',
                'page_size',
                'Cisco-IOS-XR-nto-misc-oper', False, is_config=False),
            _MetaInfoClassMember('ram-memory', ATTRIBUTE, 'int', 'uint64',
                None, None,
                [('0', '18446744073709551615')], [],
                '''                Physical memory size in bytes
                ''',
                'ram_memory',
                'Cisco-IOS-XR-nto-misc-oper', False, is_config=False),
            _MetaInfoClassMember('free-physical-memory', ATTRIBUTE, 'int', 'uint64',
                None, None,
                [('0', '18446744073709551615')], [],
                '''                Physical memory available in bytes
                ''',
                'free_physical_memory',
                'Cisco-IOS-XR-nto-misc-oper', False, is_config=False),
            _MetaInfoClassMember('system-ram-memory', ATTRIBUTE, 'int', 'uint64',
                None, None,
                [('0', '18446744073709551615')], [],
                '''                Application memory size in bytes
                ''',
                'system_ram_memory',
                'Cisco-IOS-XR-nto-misc-oper', False, is_config=False),
            _MetaInfoClassMember('free-application-memory', ATTRIBUTE, 'int', 'uint64',
                None, None,
                [('0', '18446744073709551615')], [],
                '''                Application memory available in bytes
                ''',
                'free_application_memory',
                'Cisco-IOS-XR-nto-misc-oper', False, is_config=False),
            _MetaInfoClassMember('image-memory', ATTRIBUTE, 'int', 'uint64',
                None, None,
                [('0', '18446744073709551615')], [],
                '''                Image memory size in bytes
                ''',
                'image_memory',
                'Cisco-IOS-XR-nto-misc-oper', False, is_config=False),
            _MetaInfoClassMember('boot-ram-size', ATTRIBUTE, 'int', 'uint64',
                None, None,
                [('0', '18446744073709551615')], [],
                '''                Boot RAM size in bytes
                ''',
                'boot_ram_size',
                'Cisco-IOS-XR-nto-misc-oper', False, is_config=False),
            _MetaInfoClassMember('reserved-memory', ATTRIBUTE, 'int', 'uint64',
                None, None,
                [('0', '18446744073709551615')], [],
                '''                Reserved memory size in bytes
                ''',
                'reserved_memory',
                'Cisco-IOS-XR-nto-misc-oper', False, is_config=False),
            _MetaInfoClassMember('io-memory', ATTRIBUTE, 'int', 'uint64',
                None, None,
                [('0', '18446744073709551615')], [],
                '''                IO memory size in bytes
                ''',
                'io_memory',
                'Cisco-IOS-XR-nto-misc-oper', False, is_config=False),
            _MetaInfoClassMember('flash-system', ATTRIBUTE, 'int', 'uint64',
                None, None,
                [('0', '18446744073709551615')], [],
                '''                Flash System size in bytes
                ''',
                'flash_system',
                'Cisco-IOS-XR-nto-misc-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-nto-misc-oper',
            'summary',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-nto-misc-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_nto_misc_oper',
            is_config=False,
        ),
    },
    'MemorySummary.Nodes.Node.Detail.SharedWindow' : {
        'meta_info' : _MetaInfoClass('MemorySummary.Nodes.Node.Detail.SharedWindow', REFERENCE_LIST,
            '''Available Shared windows''',
            False, 
            [
            _MetaInfoClassMember('shared-window', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Name of shared window
                ''',
                'shared_window',
                'Cisco-IOS-XR-nto-misc-oper', False, is_config=False),
            _MetaInfoClassMember('window-size', ATTRIBUTE, 'int', 'uint64',
                None, None,
                [('0', '18446744073709551615')], [],
                '''                Size of shared window
                ''',
                'window_size',
                'Cisco-IOS-XR-nto-misc-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-nto-misc-oper',
            'shared-window',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-nto-misc-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_nto_misc_oper',
            is_config=False,
        ),
    },
    'MemorySummary.Nodes.Node.Detail' : {
        'meta_info' : _MetaInfoClass('MemorySummary.Nodes.Node.Detail', REFERENCE_CLASS,
            '''Detail Memory summary information for a
specific node''',
            False, 
            [
            _MetaInfoClassMember('page-size', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                Page size in bytes
                ''',
                'page_size',
                'Cisco-IOS-XR-nto-misc-oper', False, is_config=False),
            _MetaInfoClassMember('ram-memory', ATTRIBUTE, 'int', 'uint64',
                None, None,
                [('0', '18446744073709551615')], [],
                '''                Physical memory size in bytes
                ''',
                'ram_memory',
                'Cisco-IOS-XR-nto-misc-oper', False, is_config=False),
            _MetaInfoClassMember('free-physical-memory', ATTRIBUTE, 'int', 'uint64',
                None, None,
                [('0', '18446744073709551615')], [],
                '''                Physical memory available in bytes
                ''',
                'free_physical_memory',
                'Cisco-IOS-XR-nto-misc-oper', False, is_config=False),
            _MetaInfoClassMember('private-physical-memory', ATTRIBUTE, 'int', 'uint64',
                None, None,
                [('0', '18446744073709551615')], [],
                '''                Private Physical memory in bytes
                ''',
                'private_physical_memory',
                'Cisco-IOS-XR-nto-misc-oper', False, is_config=False),
            _MetaInfoClassMember('system-ram-memory', ATTRIBUTE, 'int', 'uint64',
                None, None,
                [('0', '18446744073709551615')], [],
                '''                Application memory size in bytes
                ''',
                'system_ram_memory',
                'Cisco-IOS-XR-nto-misc-oper', False, is_config=False),
            _MetaInfoClassMember('free-application-memory', ATTRIBUTE, 'int', 'uint64',
                None, None,
                [('0', '18446744073709551615')], [],
                '''                Application memory available in bytes
                ''',
                'free_application_memory',
                'Cisco-IOS-XR-nto-misc-oper', False, is_config=False),
            _MetaInfoClassMember('image-memory', ATTRIBUTE, 'int', 'uint64',
                None, None,
                [('0', '18446744073709551615')], [],
                '''                Image memory size in bytes
                ''',
                'image_memory',
                'Cisco-IOS-XR-nto-misc-oper', False, is_config=False),
            _MetaInfoClassMember('boot-ram-size', ATTRIBUTE, 'int', 'uint64',
                None, None,
                [('0', '18446744073709551615')], [],
                '''                Boot RAM size in bytes
                ''',
                'boot_ram_size',
                'Cisco-IOS-XR-nto-misc-oper', False, is_config=False),
            _MetaInfoClassMember('reserved-memory', ATTRIBUTE, 'int', 'uint64',
                None, None,
                [('0', '18446744073709551615')], [],
                '''                Reserved memory size in bytes
                ''',
                'reserved_memory',
                'Cisco-IOS-XR-nto-misc-oper', False, is_config=False),
            _MetaInfoClassMember('io-memory', ATTRIBUTE, 'int', 'uint64',
                None, None,
                [('0', '18446744073709551615')], [],
                '''                IO memory size in bytes
                ''',
                'io_memory',
                'Cisco-IOS-XR-nto-misc-oper', False, is_config=False),
            _MetaInfoClassMember('flash-system', ATTRIBUTE, 'int', 'uint64',
                None, None,
                [('0', '18446744073709551615')], [],
                '''                Flash System size in bytes
                ''',
                'flash_system',
                'Cisco-IOS-XR-nto-misc-oper', False, is_config=False),
            _MetaInfoClassMember('total-shared-window', ATTRIBUTE, 'int', 'uint64',
                None, None,
                [('0', '18446744073709551615')], [],
                '''                Total Shared window
                ''',
                'total_shared_window',
                'Cisco-IOS-XR-nto-misc-oper', False, is_config=False),
            _MetaInfoClassMember('allocated-memory', ATTRIBUTE, 'int', 'uint64',
                None, None,
                [('0', '18446744073709551615')], [],
                '''                Allocated Memory Size
                ''',
                'allocated_memory',
                'Cisco-IOS-XR-nto-misc-oper', False, is_config=False),
            _MetaInfoClassMember('program-text', ATTRIBUTE, 'int', 'uint64',
                None, None,
                [('0', '18446744073709551615')], [],
                '''                Program Text Size
                ''',
                'program_text',
                'Cisco-IOS-XR-nto-misc-oper', False, is_config=False),
            _MetaInfoClassMember('program-data', ATTRIBUTE, 'int', 'uint64',
                None, None,
                [('0', '18446744073709551615')], [],
                '''                Program Data Size
                ''',
                'program_data',
                'Cisco-IOS-XR-nto-misc-oper', False, is_config=False),
            _MetaInfoClassMember('program-stack', ATTRIBUTE, 'int', 'uint64',
                None, None,
                [('0', '18446744073709551615')], [],
                '''                Program Stack Size
                ''',
                'program_stack',
                'Cisco-IOS-XR-nto-misc-oper', False, is_config=False),
            _MetaInfoClassMember('total-used', ATTRIBUTE, 'int', 'uint64',
                None, None,
                [('0', '18446744073709551615')], [],
                '''                Total Used
                ''',
                'total_used',
                'Cisco-IOS-XR-nto-misc-oper', False, is_config=False),
            _MetaInfoClassMember('shared-window', REFERENCE_LIST, 'SharedWindow', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_nto_misc_oper', 'MemorySummary.Nodes.Node.Detail.SharedWindow',
                [], [],
                '''                Available Shared windows
                ''',
                'shared_window',
                'Cisco-IOS-XR-nto-misc-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-nto-misc-oper',
            'detail',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-nto-misc-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_nto_misc_oper',
            is_config=False,
        ),
    },
    'MemorySummary.Nodes.Node' : {
        'meta_info' : _MetaInfoClass('MemorySummary.Nodes.Node', REFERENCE_LIST,
            '''Name of nodes''',
            False, 
            [
            _MetaInfoClassMember('node-name', ATTRIBUTE, 'str', 'xr:Node-id',
                None, None,
                [], [b'([a-zA-Z0-9_]*\\d+/){1,2}([a-zA-Z0-9_]*\\d+)'],
                '''                Node name
                ''',
                'node_name',
                'Cisco-IOS-XR-nto-misc-oper', True, is_config=False),
            _MetaInfoClassMember('summary', REFERENCE_CLASS, 'Summary', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_nto_misc_oper', 'MemorySummary.Nodes.Node.Summary',
                [], [],
                '''                Memory summary information for a specific node
                ''',
                'summary',
                'Cisco-IOS-XR-nto-misc-oper', False, is_config=False),
            _MetaInfoClassMember('detail', REFERENCE_CLASS, 'Detail', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_nto_misc_oper', 'MemorySummary.Nodes.Node.Detail',
                [], [],
                '''                Detail Memory summary information for a
                specific node
                ''',
                'detail',
                'Cisco-IOS-XR-nto-misc-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-nto-misc-oper',
            'node',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-nto-misc-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_nto_misc_oper',
            is_config=False,
        ),
    },
    'MemorySummary.Nodes' : {
        'meta_info' : _MetaInfoClass('MemorySummary.Nodes', REFERENCE_CLASS,
            '''List of nodes''',
            False, 
            [
            _MetaInfoClassMember('node', REFERENCE_LIST, 'Node', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_nto_misc_oper', 'MemorySummary.Nodes.Node',
                [], [],
                '''                Name of nodes
                ''',
                'node',
                'Cisco-IOS-XR-nto-misc-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-nto-misc-oper',
            'nodes',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-nto-misc-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_nto_misc_oper',
            is_config=False,
        ),
    },
    'MemorySummary' : {
        'meta_info' : _MetaInfoClass('MemorySummary', REFERENCE_CLASS,
            '''Memory summary information''',
            False, 
            [
            _MetaInfoClassMember('nodes', REFERENCE_CLASS, 'Nodes', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_nto_misc_oper', 'MemorySummary.Nodes',
                [], [],
                '''                List of nodes
                ''',
                'nodes',
                'Cisco-IOS-XR-nto-misc-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-nto-misc-oper',
            'memory-summary',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-nto-misc-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_nto_misc_oper',
            is_config=False,
        ),
    },
}
_meta_table['MemorySummary.Nodes.Node.Detail.SharedWindow']['meta_info'].parent =_meta_table['MemorySummary.Nodes.Node.Detail']['meta_info']
_meta_table['MemorySummary.Nodes.Node.Summary']['meta_info'].parent =_meta_table['MemorySummary.Nodes.Node']['meta_info']
_meta_table['MemorySummary.Nodes.Node.Detail']['meta_info'].parent =_meta_table['MemorySummary.Nodes.Node']['meta_info']
_meta_table['MemorySummary.Nodes.Node']['meta_info'].parent =_meta_table['MemorySummary.Nodes']['meta_info']
_meta_table['MemorySummary.Nodes']['meta_info'].parent =_meta_table['MemorySummary']['meta_info']
