
'''
This is auto-generated file,
which includes metadata for module Cisco_IOS_XR_sysadmin_fm
'''

from ydk._core._dm_meta_info import _MetaInfoClassMember, _MetaInfoClass, _MetaInfoEnum
from ydk._core._dm_meta_info import ATTRIBUTE, REFERENCE_LIST, REFERENCE_LEAFLIST, REFERENCE_BITS, REFERENCE_UNION
from ydk._core._dm_meta_info import REFERENCE_CLASS, REFERENCE_IDENTITY_CLASS, REFERENCE_ENUM_CLASS, ANYXML_CLASS
from ydk._core._importer import _yang_ns

_meta_table = {
    'FmFaultStateT' : _MetaInfoEnum('FmFaultStateT',
        'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_fm', 'FmFaultStateT',
        '''The status value for a given fault condition.''',
        {
            'SET':'SET',
            'CLEAR':'CLEAR',
            'INFO':'INFO',
            'INVALID':'INVALID',
            'PARTIALLY_QUALIFIED':'PARTIALLY_QUALIFIED',
            'SOAKING_BEFORE_SET':'SOAKING_BEFORE_SET',
            'SOAKING_BEFORE_CLEAR':'SOAKING_BEFORE_CLEAR',
            'SUPPRESSED':'SUPPRESSED',
            'UPDATE':'UPDATE',
        }, 'Cisco-IOS-XR-sysadmin-fm', _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-sysadmin-fm']),
    'FmFaultSeverityT' : _MetaInfoEnum('FmFaultSeverityT',
        'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_fm', 'FmFaultSeverityT',
        ''' ''',
        {
            'CRITICAL':'CRITICAL',
            'MAJOR':'MAJOR',
            'MINOR':'MINOR',
            'NR':'NR',
        }, 'Cisco-IOS-XR-sysadmin-fm', _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-sysadmin-fm']),
    'FmActionT' : _MetaInfoEnum('FmActionT',
        'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_fm', 'FmActionT',
        '''The List of supported Action Types''',
        {
            'ISOLATION':'ISOLATION',
            'MITIGATION':'MITIGATION',
            'RECOVERY':'RECOVERY',
            'CORRELATION':'CORRELATION',
            'ALARM':'ALARM',
            'REPORT':'REPORT',
        }, 'Cisco-IOS-XR-sysadmin-fm', _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-sysadmin-fm']),
    'FmActionResultT' : _MetaInfoEnum('FmActionResultT',
        'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_fm', 'FmActionResultT',
        '''The result of a certain fm action''',
        {
            'SUCCESS':'SUCCESS',
            'FAILURE':'FAILURE',
            'NO-OP':'NO_OP',
        }, 'Cisco-IOS-XR-sysadmin-fm', _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-sysadmin-fm']),
    'FmRuleEvalResultT' : _MetaInfoEnum('FmRuleEvalResultT',
        'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_fm', 'FmRuleEvalResultT',
        '''The result status of the evaluation of a FM rule.''',
        {
            'SUCCESS':'SUCCESS',
            'FAILURE':'FAILURE',
        }, 'Cisco-IOS-XR-sysadmin-fm', _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-sysadmin-fm']),
    'GenericHaRole' : _MetaInfoEnum('GenericHaRole',
        'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_fm', 'GenericHaRole',
        ''' ''',
        {
            'no-ha-role':'no_ha_role',
            'Active':'Active',
            'Standby':'Standby',
        }, 'Cisco-IOS-XR-sysadmin-types', _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-sysadmin-types']),
    'FmCorrelationObjQualifierT' : _MetaInfoEnum('FmCorrelationObjQualifierT',
        'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_fm', 'FmCorrelationObjQualifierT',
        ''' ''',
        {
            'QUALIFIER_IGNORED':'QUALIFIER_IGNORED',
            'QUALIFIER_RACK':'QUALIFIER_RACK',
            'QUALIFIER_SLOT':'QUALIFIER_SLOT',
            'QUALIFIER_OBJECT':'QUALIFIER_OBJECT',
        }, 'Cisco-IOS-XR-sysadmin-fm', _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-sysadmin-fm']),
    'FmHistoryStateT' : _MetaInfoEnum('FmHistoryStateT',
        'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_fm', 'FmHistoryStateT',
        '''The fm history entry state.''',
        {
            'FM_HISTORY_STATE_ACTIVE':'FM_HISTORY_STATE_ACTIVE',
            'FM_HISTORY_STATE_CLEARED':'FM_HISTORY_STATE_CLEARED',
            'FM_HISTORY_STATE_INVALID':'FM_HISTORY_STATE_INVALID',
        }, 'Cisco-IOS-XR-sysadmin-fm', _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-sysadmin-fm']),
    'FmServiceScopeT' : _MetaInfoEnum('FmServiceScopeT',
        'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_fm', 'FmServiceScopeT',
        '''The fm service scope definting type.''',
        {
            'FM_SERVICE_NODE_SCOPE':'FM_SERVICE_NODE_SCOPE',
            'FM_SERVICE_RACK_SCOPE':'FM_SERVICE_RACK_SCOPE',
            'FM_SERVICE_SYSTEM_SCOPE':'FM_SERVICE_SYSTEM_SCOPE',
        }, 'Cisco-IOS-XR-sysadmin-fm', _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-sysadmin-fm']),
    'Fm.Agents.FmInitials' : {
        'meta_info' : _MetaInfoClass('Fm.Agents.FmInitials', REFERENCE_CLASS,
            ''' ''',
            False, 
            [
            _MetaInfoClassMember('levm', ATTRIBUTE, 'int', 'uint64',
                None, None,
                [('0', '18446744073709551615')], [],
                '''                The levm pointer supplied to fm infra.
                ''',
                'levm',
                'Cisco-IOS-XR-sysadmin-fm', False, is_config=False),
            _MetaInfoClassMember('comp_id', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                The owner component Id
                ''',
                'comp_id',
                'Cisco-IOS-XR-sysadmin-fm', False, is_config=False),
            _MetaInfoClassMember('process', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                The name of the process in which this fm instance is active.
                ''',
                'process',
                'Cisco-IOS-XR-sysadmin-fm', False, is_config=False),
            _MetaInfoClassMember('default_rule_cb', ATTRIBUTE, 'int', 'uint64',
                None, None,
                [('0', '18446744073709551615')], [],
                '''                Default rule callback pointer.
                ''',
                'default_rule_cb',
                'Cisco-IOS-XR-sysadmin-fm', False, is_config=False),
            _MetaInfoClassMember('default_action_cb', ATTRIBUTE, 'int', 'uint64',
                None, None,
                [('0', '18446744073709551615')], [],
                '''                Default action callback pointer.
                ''',
                'default_action_cb',
                'Cisco-IOS-XR-sysadmin-fm', False, is_config=False),
            _MetaInfoClassMember('default_notif_cb', ATTRIBUTE, 'int', 'uint64',
                None, None,
                [('0', '18446744073709551615')], [],
                '''                Default notification callback pointer.
                ''',
                'default_notif_cb',
                'Cisco-IOS-XR-sysadmin-fm', False, is_config=False),
            _MetaInfoClassMember('default_error_cb', ATTRIBUTE, 'int', 'uint64',
                None, None,
                [('0', '18446744073709551615')], [],
                '''                Default error callback pointer.
                ''',
                'default_error_cb',
                'Cisco-IOS-XR-sysadmin-fm', False, is_config=False),
            _MetaInfoClassMember('replica_cb', ATTRIBUTE, 'int', 'uint64',
                None, None,
                [('0', '18446744073709551615')], [],
                '''                Data Replica callback pointer.
                ''',
                'replica_cb',
                'Cisco-IOS-XR-sysadmin-fm', False, is_config=False),
            ],
            'Cisco-IOS-XR-sysadmin-fm',
            'fm_initials',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-sysadmin-fm'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_fm',
            is_config=False,
        ),
    },
    'Fm.Agents.FmTable.Brief' : {
        'meta_info' : _MetaInfoClass('Fm.Agents.FmTable.Brief', REFERENCE_LIST,
            ''' ''',
            False, 
            [
            _MetaInfoClassMember('fm_subsystem_id', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Fault sub-system identifier
                ''',
                'fm_subsystem_id',
                'Cisco-IOS-XR-sysadmin-fm', True, is_config=False),
            _MetaInfoClassMember('fm_fault_type', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Fault type identifier
                ''',
                'fm_fault_type',
                'Cisco-IOS-XR-sysadmin-fm', True, is_config=False),
            _MetaInfoClassMember('fm_fault_tag', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Fault tag identifier
                ''',
                'fm_fault_tag',
                'Cisco-IOS-XR-sysadmin-fm', True, is_config=False),
            _MetaInfoClassMember('name', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                A descriptive name for the fault
                ''',
                'name',
                'Cisco-IOS-XR-sysadmin-fm', False, is_config=False),
            ],
            'Cisco-IOS-XR-sysadmin-fm',
            'brief',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-sysadmin-fm'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_fm',
            is_config=False,
        ),
    },
    'Fm.Agents.FmTable.Entry.Detail' : {
        'meta_info' : _MetaInfoClass('Fm.Agents.FmTable.Entry.Detail', REFERENCE_CLASS,
            ''' ''',
            False, 
            [
            _MetaInfoClassMember('fm_subsystem_id', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Fault sub-system identifier
                ''',
                'fm_subsystem_id',
                'Cisco-IOS-XR-sysadmin-fm', False, is_config=False),
            _MetaInfoClassMember('fm_fault_type', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Fault type identifier
                ''',
                'fm_fault_type',
                'Cisco-IOS-XR-sysadmin-fm', False, is_config=False),
            _MetaInfoClassMember('fm_fault_tag', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Fault tag identifier
                ''',
                'fm_fault_tag',
                'Cisco-IOS-XR-sysadmin-fm', False, is_config=False),
            _MetaInfoClassMember('name', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                A descriptive name for the fault
                ''',
                'name',
                'Cisco-IOS-XR-sysadmin-fm', False, is_config=False),
            _MetaInfoClassMember('description', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Description of the fault
                ''',
                'description',
                'Cisco-IOS-XR-sysadmin-fm', False, is_config=False),
            _MetaInfoClassMember('detection_logic', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Fault detection logic
                ''',
                'detection_logic',
                'Cisco-IOS-XR-sysadmin-fm', False, is_config=False),
            _MetaInfoClassMember('corr_obj_qualifier', REFERENCE_ENUM_CLASS, 'FmCorrelationObjQualifierT', 'fm_correlation_obj_qualifier_t',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_fm', 'FmCorrelationObjQualifierT',
                [], [],
                '''                The qualifier for the object used for correlation.
                ''',
                'corr_obj_qualifier',
                'Cisco-IOS-XR-sysadmin-fm', False, is_config=False),
            ],
            'Cisco-IOS-XR-sysadmin-fm',
            'detail',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-sysadmin-fm'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_fm',
            is_config=False,
        ),
    },
    'Fm.Agents.FmTable.Entry.CausalList' : {
        'meta_info' : _MetaInfoClass('Fm.Agents.FmTable.Entry.CausalList', REFERENCE_LIST,
            '''Causal list of fault ids for the specified fault.''',
            False, 
            [
            _MetaInfoClassMember('fm_subsystem_id', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Fault sub-system identifier
                ''',
                'fm_subsystem_id',
                'Cisco-IOS-XR-sysadmin-fm', True, is_config=False),
            _MetaInfoClassMember('fm_fault_type', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Fault type identifier
                ''',
                'fm_fault_type',
                'Cisco-IOS-XR-sysadmin-fm', True, is_config=False),
            _MetaInfoClassMember('fm_fault_tag', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Fault tag identifier
                ''',
                'fm_fault_tag',
                'Cisco-IOS-XR-sysadmin-fm', True, is_config=False),
            ],
            'Cisco-IOS-XR-sysadmin-fm',
            'causal_list',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-sysadmin-fm'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_fm',
            is_config=False,
        ),
    },
    'Fm.Agents.FmTable.Entry.DependencyList' : {
        'meta_info' : _MetaInfoClass('Fm.Agents.FmTable.Entry.DependencyList', REFERENCE_LIST,
            '''Dependency list of fault ids.''',
            False, 
            [
            _MetaInfoClassMember('fm_subsystem_id', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Fault sub-system identifier
                ''',
                'fm_subsystem_id',
                'Cisco-IOS-XR-sysadmin-fm', True, is_config=False),
            _MetaInfoClassMember('fm_fault_type', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Fault type identifier
                ''',
                'fm_fault_type',
                'Cisco-IOS-XR-sysadmin-fm', True, is_config=False),
            _MetaInfoClassMember('fm_fault_tag', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Fault tag identifier
                ''',
                'fm_fault_tag',
                'Cisco-IOS-XR-sysadmin-fm', True, is_config=False),
            ],
            'Cisco-IOS-XR-sysadmin-fm',
            'dependency_list',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-sysadmin-fm'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_fm',
            is_config=False,
        ),
    },
    'Fm.Agents.FmTable.Entry.PropagationList' : {
        'meta_info' : _MetaInfoClass('Fm.Agents.FmTable.Entry.PropagationList', REFERENCE_LIST,
            '''Propagation list of fault agents.''',
            False, 
            [
            _MetaInfoClassMember('fm_subsystem_id', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Fault sub-system identifier
                ''',
                'fm_subsystem_id',
                'Cisco-IOS-XR-sysadmin-fm', True, is_config=False),
            _MetaInfoClassMember('fm_fault_type', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Fault type identifier
                ''',
                'fm_fault_type',
                'Cisco-IOS-XR-sysadmin-fm', True, is_config=False),
            _MetaInfoClassMember('fm_fault_tag', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Fault tag identifier
                ''',
                'fm_fault_tag',
                'Cisco-IOS-XR-sysadmin-fm', True, is_config=False),
            _MetaInfoClassMember('remote_agent_id', ATTRIBUTE, 'str', 'fm_agent_id_t',
                None, None,
                [], [],
                '''                The remote agent id assocaited with this fault.
                ''',
                'remote_agent_id',
                'Cisco-IOS-XR-sysadmin-fm', False, is_config=False),
            ],
            'Cisco-IOS-XR-sysadmin-fm',
            'propagation_list',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-sysadmin-fm'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_fm',
            is_config=False,
        ),
    },
    'Fm.Agents.FmTable.Entry.NotificationList' : {
        'meta_info' : _MetaInfoClass('Fm.Agents.FmTable.Entry.NotificationList', REFERENCE_LIST,
            '''Notification list of fault agents.''',
            False, 
            [
            _MetaInfoClassMember('fm_subsystem_id', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Fault sub-system identifier
                ''',
                'fm_subsystem_id',
                'Cisco-IOS-XR-sysadmin-fm', True, is_config=False),
            _MetaInfoClassMember('fm_fault_type', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Fault type identifier
                ''',
                'fm_fault_type',
                'Cisco-IOS-XR-sysadmin-fm', True, is_config=False),
            _MetaInfoClassMember('fm_fault_tag', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Fault tag identifier
                ''',
                'fm_fault_tag',
                'Cisco-IOS-XR-sysadmin-fm', True, is_config=False),
            _MetaInfoClassMember('remote_agent_id', ATTRIBUTE, 'str', 'fm_agent_id_t',
                None, None,
                [], [],
                '''                The remote agent id assocaited with this fault.
                ''',
                'remote_agent_id',
                'Cisco-IOS-XR-sysadmin-fm', False, is_config=False),
            ],
            'Cisco-IOS-XR-sysadmin-fm',
            'notification_list',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-sysadmin-fm'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_fm',
            is_config=False,
        ),
    },
    'Fm.Agents.FmTable.Entry.EscalationList' : {
        'meta_info' : _MetaInfoClass('Fm.Agents.FmTable.Entry.EscalationList', REFERENCE_LIST,
            '''escalation list of fault agents.''',
            False, 
            [
            _MetaInfoClassMember('fm_subsystem_id', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Fault sub-system identifier
                ''',
                'fm_subsystem_id',
                'Cisco-IOS-XR-sysadmin-fm', True, is_config=False),
            _MetaInfoClassMember('fm_fault_type', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Fault type identifier
                ''',
                'fm_fault_type',
                'Cisco-IOS-XR-sysadmin-fm', True, is_config=False),
            _MetaInfoClassMember('fm_fault_tag', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Fault tag identifier
                ''',
                'fm_fault_tag',
                'Cisco-IOS-XR-sysadmin-fm', True, is_config=False),
            _MetaInfoClassMember('remote_agent_id', ATTRIBUTE, 'str', 'fm_agent_id_t',
                None, None,
                [], [],
                '''                The remote agent id assocaited with this fault.
                ''',
                'remote_agent_id',
                'Cisco-IOS-XR-sysadmin-fm', False, is_config=False),
            ],
            'Cisco-IOS-XR-sysadmin-fm',
            'escalation_list',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-sysadmin-fm'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_fm',
            is_config=False,
        ),
    },
    'Fm.Agents.FmTable.Entry.Faults.Active.Brief' : {
        'meta_info' : _MetaInfoClass('Fm.Agents.FmTable.Entry.Faults.Active.Brief', REFERENCE_LIST,
            ''' ''',
            False, 
            [
            _MetaInfoClassMember('object_id', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                The fault object ID
                ''',
                'object_id',
                'Cisco-IOS-XR-sysadmin-fm', True, is_config=False),
            _MetaInfoClassMember('fault_timestamp', ATTRIBUTE, 'str', 'fm_timestamp_t',
                None, None,
                [], [b'\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(\\.\\d+)?(Z|[\\+\\-]\\d{2}:\\d{2})'],
                '''                The fault occurence timestamp
                ''',
                'fault_timestamp',
                'Cisco-IOS-XR-sysadmin-fm', False, is_config=False),
            ],
            'Cisco-IOS-XR-sysadmin-fm',
            'brief',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-sysadmin-fm'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_fm',
            is_config=False,
        ),
    },
    'Fm.Agents.FmTable.Entry.Faults.Active.Detail' : {
        'meta_info' : _MetaInfoClass('Fm.Agents.FmTable.Entry.Faults.Active.Detail', REFERENCE_LIST,
            ''' ''',
            False, 
            [
            _MetaInfoClassMember('object_id', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                The fault object ID
                ''',
                'object_id',
                'Cisco-IOS-XR-sysadmin-fm', True, is_config=False),
            _MetaInfoClassMember('fm_subsystem_id', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Fault sub-system identifier
                ''',
                'fm_subsystem_id',
                'Cisco-IOS-XR-sysadmin-fm', False, is_config=False),
            _MetaInfoClassMember('fm_fault_type', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Fault type identifier
                ''',
                'fm_fault_type',
                'Cisco-IOS-XR-sysadmin-fm', False, is_config=False),
            _MetaInfoClassMember('fm_fault_tag', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Fault tag identifier
                ''',
                'fm_fault_tag',
                'Cisco-IOS-XR-sysadmin-fm', False, is_config=False),
            _MetaInfoClassMember('fault_severity', ATTRIBUTE, 'int', 'uint16',
                None, None,
                [('0', '65535')], [],
                '''                The severity of the fault reported out
                ''',
                'fault_severity',
                'Cisco-IOS-XR-sysadmin-fm', False, is_config=False),
            _MetaInfoClassMember('fault_state', REFERENCE_ENUM_CLASS, 'FmFaultStateT', 'fm_fault_state_t',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_fm', 'FmFaultStateT',
                [], [],
                '''                The state of the fault.
                ''',
                'fault_state',
                'Cisco-IOS-XR-sysadmin-fm', False, is_config=False),
            _MetaInfoClassMember('fault_agent_id', ATTRIBUTE, 'str', 'fm_agent_id_t',
                None, None,
                [], [],
                '''                The agent id associated with the fault
                ''',
                'fault_agent_id',
                'Cisco-IOS-XR-sysadmin-fm', False, is_config=False),
            _MetaInfoClassMember('fault_timestamp', ATTRIBUTE, 'str', 'fm_timestamp_t',
                None, None,
                [], [b'\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(\\.\\d+)?(Z|[\\+\\-]\\d{2}:\\d{2})'],
                '''                The fault occurence timestamp
                ''',
                'fault_timestamp',
                'Cisco-IOS-XR-sysadmin-fm', False, is_config=False),
            _MetaInfoClassMember('fault_timer_state', ATTRIBUTE, 'bool', 'boolean',
                None, None,
                [], [],
                '''                The state of the timer associated with this fault
                ''',
                'fault_timer_state',
                'Cisco-IOS-XR-sysadmin-fm', False, is_config=False),
            _MetaInfoClassMember('fault_processed', ATTRIBUTE, 'bool', 'boolean',
                None, None,
                [], [],
                '''                The fault is acted on
                ''',
                'fault_processed',
                'Cisco-IOS-XR-sysadmin-fm', False, is_config=False),
            _MetaInfoClassMember('mitigation_result', REFERENCE_ENUM_CLASS, 'FmActionResultT', 'fm_action_result_t',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_fm', 'FmActionResultT',
                [], [],
                '''                The result of the mitigation action on the fault.
                ''',
                'mitigation_result',
                'Cisco-IOS-XR-sysadmin-fm', False, is_config=False),
            _MetaInfoClassMember('recovery_result', REFERENCE_ENUM_CLASS, 'FmActionResultT', 'fm_action_result_t',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_fm', 'FmActionResultT',
                [], [],
                '''                The result of the recovery action on the fault.
                ''',
                'recovery_result',
                'Cisco-IOS-XR-sysadmin-fm', False, is_config=False),
            _MetaInfoClassMember('correlation_result', REFERENCE_ENUM_CLASS, 'FmActionResultT', 'fm_action_result_t',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_fm', 'FmActionResultT',
                [], [],
                '''                The result of the correlation action on the fault.
                ''',
                'correlation_result',
                'Cisco-IOS-XR-sysadmin-fm', False, is_config=False),
            _MetaInfoClassMember('alarm_result', REFERENCE_ENUM_CLASS, 'FmActionResultT', 'fm_action_result_t',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_fm', 'FmActionResultT',
                [], [],
                '''                The result of the alarm action on the fault.
                ''',
                'alarm_result',
                'Cisco-IOS-XR-sysadmin-fm', False, is_config=False),
            _MetaInfoClassMember('default_result', REFERENCE_ENUM_CLASS, 'FmActionResultT', 'fm_action_result_t',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_fm', 'FmActionResultT',
                [], [],
                '''                The result of the default action on the fault.
                ''',
                'default_result',
                'Cisco-IOS-XR-sysadmin-fm', False, is_config=False),
            _MetaInfoClassMember('opaque_data_len', ATTRIBUTE, 'int', 'uint16',
                None, None,
                [('0', '65535')], [],
                '''                The length of opaque data bytes.
                ''',
                'opaque_data_len',
                'Cisco-IOS-XR-sysadmin-fm', False, is_config=False),
            _MetaInfoClassMember('occurrence_count', ATTRIBUTE, 'int', 'uint64',
                None, None,
                [('0', '18446744073709551615')], [],
                '''                The occurrence count of the fault
                ''',
                'occurrence_count',
                'Cisco-IOS-XR-sysadmin-fm', False, is_config=False),
            _MetaInfoClassMember('history_state', REFERENCE_ENUM_CLASS, 'FmHistoryStateT', 'fm_history_state_t',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_fm', 'FmHistoryStateT',
                [], [],
                '''                The history state of the fault.
                ''',
                'history_state',
                'Cisco-IOS-XR-sysadmin-fm', False, is_config=False),
            ],
            'Cisco-IOS-XR-sysadmin-fm',
            'detail',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-sysadmin-fm'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_fm',
            is_config=False,
        ),
    },
    'Fm.Agents.FmTable.Entry.Faults.Active' : {
        'meta_info' : _MetaInfoClass('Fm.Agents.FmTable.Entry.Faults.Active', REFERENCE_CLASS,
            ''' ''',
            False, 
            [
            _MetaInfoClassMember('brief', REFERENCE_LIST, 'Brief', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_fm', 'Fm.Agents.FmTable.Entry.Faults.Active.Brief',
                [], [],
                '''                ''',
                'brief',
                'Cisco-IOS-XR-sysadmin-fm', False, is_config=False),
            _MetaInfoClassMember('detail', REFERENCE_LIST, 'Detail', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_fm', 'Fm.Agents.FmTable.Entry.Faults.Active.Detail',
                [], [],
                '''                ''',
                'detail',
                'Cisco-IOS-XR-sysadmin-fm', False, is_config=False),
            ],
            'Cisco-IOS-XR-sysadmin-fm',
            'active',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-sysadmin-fm'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_fm',
            is_config=False,
        ),
    },
    'Fm.Agents.FmTable.Entry.Faults.History.Brief' : {
        'meta_info' : _MetaInfoClass('Fm.Agents.FmTable.Entry.Faults.History.Brief', REFERENCE_LIST,
            ''' ''',
            False, 
            [
            _MetaInfoClassMember('object_id', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                The fault object ID
                ''',
                'object_id',
                'Cisco-IOS-XR-sysadmin-fm', True, is_config=False),
            _MetaInfoClassMember('fault_timestamp', ATTRIBUTE, 'str', 'fm_timestamp_t',
                None, None,
                [], [b'\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(\\.\\d+)?(Z|[\\+\\-]\\d{2}:\\d{2})'],
                '''                The fault occurence timestamp
                ''',
                'fault_timestamp',
                'Cisco-IOS-XR-sysadmin-fm', False, is_config=False),
            ],
            'Cisco-IOS-XR-sysadmin-fm',
            'brief',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-sysadmin-fm'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_fm',
            is_config=False,
        ),
    },
    'Fm.Agents.FmTable.Entry.Faults.History.Detail' : {
        'meta_info' : _MetaInfoClass('Fm.Agents.FmTable.Entry.Faults.History.Detail', REFERENCE_LIST,
            ''' ''',
            False, 
            [
            _MetaInfoClassMember('object_id', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                The fault object ID
                ''',
                'object_id',
                'Cisco-IOS-XR-sysadmin-fm', True, is_config=False),
            _MetaInfoClassMember('fm_subsystem_id', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Fault sub-system identifier
                ''',
                'fm_subsystem_id',
                'Cisco-IOS-XR-sysadmin-fm', False, is_config=False),
            _MetaInfoClassMember('fm_fault_type', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Fault type identifier
                ''',
                'fm_fault_type',
                'Cisco-IOS-XR-sysadmin-fm', False, is_config=False),
            _MetaInfoClassMember('fm_fault_tag', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Fault tag identifier
                ''',
                'fm_fault_tag',
                'Cisco-IOS-XR-sysadmin-fm', False, is_config=False),
            _MetaInfoClassMember('fault_severity', ATTRIBUTE, 'int', 'uint16',
                None, None,
                [('0', '65535')], [],
                '''                The severity of the fault reported out
                ''',
                'fault_severity',
                'Cisco-IOS-XR-sysadmin-fm', False, is_config=False),
            _MetaInfoClassMember('fault_state', REFERENCE_ENUM_CLASS, 'FmFaultStateT', 'fm_fault_state_t',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_fm', 'FmFaultStateT',
                [], [],
                '''                The state of the fault.
                ''',
                'fault_state',
                'Cisco-IOS-XR-sysadmin-fm', False, is_config=False),
            _MetaInfoClassMember('fault_agent_id', ATTRIBUTE, 'str', 'fm_agent_id_t',
                None, None,
                [], [],
                '''                The agent id associated with the fault
                ''',
                'fault_agent_id',
                'Cisco-IOS-XR-sysadmin-fm', False, is_config=False),
            _MetaInfoClassMember('fault_timestamp', ATTRIBUTE, 'str', 'fm_timestamp_t',
                None, None,
                [], [b'\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(\\.\\d+)?(Z|[\\+\\-]\\d{2}:\\d{2})'],
                '''                The fault occurence timestamp
                ''',
                'fault_timestamp',
                'Cisco-IOS-XR-sysadmin-fm', False, is_config=False),
            _MetaInfoClassMember('fault_timer_state', ATTRIBUTE, 'bool', 'boolean',
                None, None,
                [], [],
                '''                The state of the timer associated with this fault
                ''',
                'fault_timer_state',
                'Cisco-IOS-XR-sysadmin-fm', False, is_config=False),
            _MetaInfoClassMember('fault_processed', ATTRIBUTE, 'bool', 'boolean',
                None, None,
                [], [],
                '''                The fault is acted on
                ''',
                'fault_processed',
                'Cisco-IOS-XR-sysadmin-fm', False, is_config=False),
            _MetaInfoClassMember('mitigation_result', REFERENCE_ENUM_CLASS, 'FmActionResultT', 'fm_action_result_t',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_fm', 'FmActionResultT',
                [], [],
                '''                The result of the mitigation action on the fault.
                ''',
                'mitigation_result',
                'Cisco-IOS-XR-sysadmin-fm', False, is_config=False),
            _MetaInfoClassMember('recovery_result', REFERENCE_ENUM_CLASS, 'FmActionResultT', 'fm_action_result_t',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_fm', 'FmActionResultT',
                [], [],
                '''                The result of the recovery action on the fault.
                ''',
                'recovery_result',
                'Cisco-IOS-XR-sysadmin-fm', False, is_config=False),
            _MetaInfoClassMember('correlation_result', REFERENCE_ENUM_CLASS, 'FmActionResultT', 'fm_action_result_t',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_fm', 'FmActionResultT',
                [], [],
                '''                The result of the correlation action on the fault.
                ''',
                'correlation_result',
                'Cisco-IOS-XR-sysadmin-fm', False, is_config=False),
            _MetaInfoClassMember('alarm_result', REFERENCE_ENUM_CLASS, 'FmActionResultT', 'fm_action_result_t',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_fm', 'FmActionResultT',
                [], [],
                '''                The result of the alarm action on the fault.
                ''',
                'alarm_result',
                'Cisco-IOS-XR-sysadmin-fm', False, is_config=False),
            _MetaInfoClassMember('default_result', REFERENCE_ENUM_CLASS, 'FmActionResultT', 'fm_action_result_t',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_fm', 'FmActionResultT',
                [], [],
                '''                The result of the default action on the fault.
                ''',
                'default_result',
                'Cisco-IOS-XR-sysadmin-fm', False, is_config=False),
            _MetaInfoClassMember('opaque_data_len', ATTRIBUTE, 'int', 'uint16',
                None, None,
                [('0', '65535')], [],
                '''                The length of opaque data bytes.
                ''',
                'opaque_data_len',
                'Cisco-IOS-XR-sysadmin-fm', False, is_config=False),
            _MetaInfoClassMember('occurrence_count', ATTRIBUTE, 'int', 'uint64',
                None, None,
                [('0', '18446744073709551615')], [],
                '''                The occurrence count of the fault
                ''',
                'occurrence_count',
                'Cisco-IOS-XR-sysadmin-fm', False, is_config=False),
            _MetaInfoClassMember('history_state', REFERENCE_ENUM_CLASS, 'FmHistoryStateT', 'fm_history_state_t',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_fm', 'FmHistoryStateT',
                [], [],
                '''                The history state of the fault.
                ''',
                'history_state',
                'Cisco-IOS-XR-sysadmin-fm', False, is_config=False),
            ],
            'Cisco-IOS-XR-sysadmin-fm',
            'detail',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-sysadmin-fm'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_fm',
            is_config=False,
        ),
    },
    'Fm.Agents.FmTable.Entry.Faults.History' : {
        'meta_info' : _MetaInfoClass('Fm.Agents.FmTable.Entry.Faults.History', REFERENCE_CLASS,
            ''' ''',
            False, 
            [
            _MetaInfoClassMember('brief', REFERENCE_LIST, 'Brief', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_fm', 'Fm.Agents.FmTable.Entry.Faults.History.Brief',
                [], [],
                '''                ''',
                'brief',
                'Cisco-IOS-XR-sysadmin-fm', False, is_config=False),
            _MetaInfoClassMember('detail', REFERENCE_LIST, 'Detail', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_fm', 'Fm.Agents.FmTable.Entry.Faults.History.Detail',
                [], [],
                '''                ''',
                'detail',
                'Cisco-IOS-XR-sysadmin-fm', False, is_config=False),
            ],
            'Cisco-IOS-XR-sysadmin-fm',
            'history',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-sysadmin-fm'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_fm',
            is_config=False,
        ),
    },
    'Fm.Agents.FmTable.Entry.Faults' : {
        'meta_info' : _MetaInfoClass('Fm.Agents.FmTable.Entry.Faults', REFERENCE_CLASS,
            ''' ''',
            False, 
            [
            _MetaInfoClassMember('active', REFERENCE_CLASS, 'Active', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_fm', 'Fm.Agents.FmTable.Entry.Faults.Active',
                [], [],
                '''                ''',
                'active',
                'Cisco-IOS-XR-sysadmin-fm', False, is_config=False),
            _MetaInfoClassMember('history', REFERENCE_CLASS, 'History', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_fm', 'Fm.Agents.FmTable.Entry.Faults.History',
                [], [],
                '''                ''',
                'history',
                'Cisco-IOS-XR-sysadmin-fm', False, is_config=False),
            ],
            'Cisco-IOS-XR-sysadmin-fm',
            'faults',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-sysadmin-fm'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_fm',
            is_config=False,
        ),
    },
    'Fm.Agents.FmTable.Entry.WaitingList.Brief' : {
        'meta_info' : _MetaInfoClass('Fm.Agents.FmTable.Entry.WaitingList.Brief', REFERENCE_LIST,
            ''' ''',
            False, 
            [
            _MetaInfoClassMember('fm_subsystem_id', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Fault sub-system identifier
                ''',
                'fm_subsystem_id',
                'Cisco-IOS-XR-sysadmin-fm', True, is_config=False),
            _MetaInfoClassMember('fm_fault_type', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Fault type identifier
                ''',
                'fm_fault_type',
                'Cisco-IOS-XR-sysadmin-fm', True, is_config=False),
            _MetaInfoClassMember('fm_fault_tag', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Fault tag identifier
                ''',
                'fm_fault_tag',
                'Cisco-IOS-XR-sysadmin-fm', True, is_config=False),
            _MetaInfoClassMember('object_id', ATTRIBUTE, 'str', 'fm_object_id_t',
                None, None,
                [], [],
                '''                The object Id of the entity that generated the fault.
                ''',
                'object_id',
                'Cisco-IOS-XR-sysadmin-fm', False, is_config=False),
            _MetaInfoClassMember('fault_timestamp', ATTRIBUTE, 'str', 'fm_timestamp_t',
                None, None,
                [], [b'\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(\\.\\d+)?(Z|[\\+\\-]\\d{2}:\\d{2})'],
                '''                The timestamp at which the fault occurred.
                ''',
                'fault_timestamp',
                'Cisco-IOS-XR-sysadmin-fm', False, is_config=False),
            _MetaInfoClassMember('fault_state', REFERENCE_ENUM_CLASS, 'FmFaultStateT', 'fm_fault_state_t',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_fm', 'FmFaultStateT',
                [], [],
                '''                The state pf tje causal fault.
                ''',
                'fault_state',
                'Cisco-IOS-XR-sysadmin-fm', False, is_config=False),
            _MetaInfoClassMember('fault_count', ATTRIBUTE, 'int', 'uint64',
                None, None,
                [('0', '18446744073709551615')], [],
                '''                Count of occurrence of the fault event.
                ''',
                'fault_count',
                'Cisco-IOS-XR-sysadmin-fm', False, is_config=False),
            _MetaInfoClassMember('fault_flag', ATTRIBUTE, 'int', 'uint64',
                None, None,
                [('0', '18446744073709551615')], [],
                '''                FM correlation engine flag, internal.
                ''',
                'fault_flag',
                'Cisco-IOS-XR-sysadmin-fm', False, is_config=False),
            ],
            'Cisco-IOS-XR-sysadmin-fm',
            'brief',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-sysadmin-fm'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_fm',
            is_config=False,
        ),
    },
    'Fm.Agents.FmTable.Entry.WaitingList.Entry_' : {
        'meta_info' : _MetaInfoClass('Fm.Agents.FmTable.Entry.WaitingList.Entry_', REFERENCE_LIST,
            ''' ''',
            False, 
            [
            _MetaInfoClassMember('fm_subsystem_id', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Fault sub-system identifier
                ''',
                'fm_subsystem_id',
                'Cisco-IOS-XR-sysadmin-fm', True, is_config=False),
            _MetaInfoClassMember('fm_fault_type', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Fault type identifier
                ''',
                'fm_fault_type',
                'Cisco-IOS-XR-sysadmin-fm', True, is_config=False),
            _MetaInfoClassMember('fm_fault_tag', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Fault tag identifier
                ''',
                'fm_fault_tag',
                'Cisco-IOS-XR-sysadmin-fm', True, is_config=False),
            _MetaInfoClassMember('object_id', ATTRIBUTE, 'str', 'fm_object_id_t',
                None, None,
                [], [],
                '''                The object Id of the entity that generated the fault.
                ''',
                'object_id',
                'Cisco-IOS-XR-sysadmin-fm', False, is_config=False),
            _MetaInfoClassMember('fault_timestamp', ATTRIBUTE, 'str', 'fm_timestamp_t',
                None, None,
                [], [b'\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(\\.\\d+)?(Z|[\\+\\-]\\d{2}:\\d{2})'],
                '''                The timestamp at which the fault occurred.
                ''',
                'fault_timestamp',
                'Cisco-IOS-XR-sysadmin-fm', False, is_config=False),
            _MetaInfoClassMember('fault_state', REFERENCE_ENUM_CLASS, 'FmFaultStateT', 'fm_fault_state_t',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_fm', 'FmFaultStateT',
                [], [],
                '''                The state pf tje causal fault.
                ''',
                'fault_state',
                'Cisco-IOS-XR-sysadmin-fm', False, is_config=False),
            _MetaInfoClassMember('fault_count', ATTRIBUTE, 'int', 'uint64',
                None, None,
                [('0', '18446744073709551615')], [],
                '''                Count of occurrence of the fault event.
                ''',
                'fault_count',
                'Cisco-IOS-XR-sysadmin-fm', False, is_config=False),
            _MetaInfoClassMember('fault_flag', ATTRIBUTE, 'int', 'uint64',
                None, None,
                [('0', '18446744073709551615')], [],
                '''                FM correlation engine flag, internal.
                ''',
                'fault_flag',
                'Cisco-IOS-XR-sysadmin-fm', False, is_config=False),
            ],
            'Cisco-IOS-XR-sysadmin-fm',
            'entry',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-sysadmin-fm'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_fm',
            is_config=False,
        ),
    },
    'Fm.Agents.FmTable.Entry.WaitingList' : {
        'meta_info' : _MetaInfoClass('Fm.Agents.FmTable.Entry.WaitingList', REFERENCE_CLASS,
            ''' ''',
            False, 
            [
            _MetaInfoClassMember('brief', REFERENCE_LIST, 'Brief', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_fm', 'Fm.Agents.FmTable.Entry.WaitingList.Brief',
                [], [],
                '''                ''',
                'brief',
                'Cisco-IOS-XR-sysadmin-fm', False, is_config=False),
            _MetaInfoClassMember('entry', REFERENCE_LIST, 'Entry_', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_fm', 'Fm.Agents.FmTable.Entry.WaitingList.Entry_',
                [], [],
                '''                ''',
                'entry',
                'Cisco-IOS-XR-sysadmin-fm', False, is_config=False),
            ],
            'Cisco-IOS-XR-sysadmin-fm',
            'waiting_list',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-sysadmin-fm'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_fm',
            is_config=False,
        ),
    },
    'Fm.Agents.FmTable.Entry' : {
        'meta_info' : _MetaInfoClass('Fm.Agents.FmTable.Entry', REFERENCE_LIST,
            ''' ''',
            False, 
            [
            _MetaInfoClassMember('fm_subsystem_id', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Fault sub-system identifier
                ''',
                'fm_subsystem_id',
                'Cisco-IOS-XR-sysadmin-fm', True, is_config=False),
            _MetaInfoClassMember('fm_fault_type', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Fault type identifier
                ''',
                'fm_fault_type',
                'Cisco-IOS-XR-sysadmin-fm', True, is_config=False),
            _MetaInfoClassMember('fm_fault_tag', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Fault tag identifier
                ''',
                'fm_fault_tag',
                'Cisco-IOS-XR-sysadmin-fm', True, is_config=False),
            _MetaInfoClassMember('detail', REFERENCE_CLASS, 'Detail', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_fm', 'Fm.Agents.FmTable.Entry.Detail',
                [], [],
                '''                ''',
                'detail',
                'Cisco-IOS-XR-sysadmin-fm', False, is_config=False),
            _MetaInfoClassMember('causal_list', REFERENCE_LIST, 'CausalList', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_fm', 'Fm.Agents.FmTable.Entry.CausalList',
                [], [],
                '''                Causal list of fault ids for the specified fault.
                ''',
                'causal_list',
                'Cisco-IOS-XR-sysadmin-fm', False, is_config=False),
            _MetaInfoClassMember('dependency_list', REFERENCE_LIST, 'DependencyList', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_fm', 'Fm.Agents.FmTable.Entry.DependencyList',
                [], [],
                '''                Dependency list of fault ids.
                ''',
                'dependency_list',
                'Cisco-IOS-XR-sysadmin-fm', False, is_config=False),
            _MetaInfoClassMember('propagation_list', REFERENCE_LIST, 'PropagationList', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_fm', 'Fm.Agents.FmTable.Entry.PropagationList',
                [], [],
                '''                Propagation list of fault agents.
                ''',
                'propagation_list',
                'Cisco-IOS-XR-sysadmin-fm', False, is_config=False),
            _MetaInfoClassMember('notification_list', REFERENCE_LIST, 'NotificationList', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_fm', 'Fm.Agents.FmTable.Entry.NotificationList',
                [], [],
                '''                Notification list of fault agents.
                ''',
                'notification_list',
                'Cisco-IOS-XR-sysadmin-fm', False, is_config=False),
            _MetaInfoClassMember('escalation_list', REFERENCE_LIST, 'EscalationList', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_fm', 'Fm.Agents.FmTable.Entry.EscalationList',
                [], [],
                '''                escalation list of fault agents.
                ''',
                'escalation_list',
                'Cisco-IOS-XR-sysadmin-fm', False, is_config=False),
            _MetaInfoClassMember('faults', REFERENCE_CLASS, 'Faults', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_fm', 'Fm.Agents.FmTable.Entry.Faults',
                [], [],
                '''                ''',
                'faults',
                'Cisco-IOS-XR-sysadmin-fm', False, is_config=False),
            _MetaInfoClassMember('waiting_list', REFERENCE_CLASS, 'WaitingList', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_fm', 'Fm.Agents.FmTable.Entry.WaitingList',
                [], [],
                '''                ''',
                'waiting_list',
                'Cisco-IOS-XR-sysadmin-fm', False, is_config=False),
            ],
            'Cisco-IOS-XR-sysadmin-fm',
            'entry',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-sysadmin-fm'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_fm',
            is_config=False,
        ),
    },
    'Fm.Agents.FmTable' : {
        'meta_info' : _MetaInfoClass('Fm.Agents.FmTable', REFERENCE_CLASS,
            ''' ''',
            False, 
            [
            _MetaInfoClassMember('brief', REFERENCE_LIST, 'Brief', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_fm', 'Fm.Agents.FmTable.Brief',
                [], [],
                '''                ''',
                'brief',
                'Cisco-IOS-XR-sysadmin-fm', False, is_config=False),
            _MetaInfoClassMember('entry', REFERENCE_LIST, 'Entry', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_fm', 'Fm.Agents.FmTable.Entry',
                [], [],
                '''                ''',
                'entry',
                'Cisco-IOS-XR-sysadmin-fm', False, is_config=False),
            ],
            'Cisco-IOS-XR-sysadmin-fm',
            'fm_table',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-sysadmin-fm'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_fm',
            is_config=False,
        ),
    },
    'Fm.Agents.FmInternals.Detail.Rules' : {
        'meta_info' : _MetaInfoClass('Fm.Agents.FmInternals.Detail.Rules', REFERENCE_LIST,
            '''list of fault rule declaring callbacks''',
            False, 
            [
            _MetaInfoClassMember('fault_location', ATTRIBUTE, 'str', 'fm_location_t',
                None, None,
                [], [],
                '''                The location associated with the fault
                ''',
                'fault_location',
                'Cisco-IOS-XR-sysadmin-fm', False, is_config=False),
            _MetaInfoClassMember('rule_cb', ATTRIBUTE, 'int', 'uint64',
                None, None,
                [('0', '18446744073709551615')], [],
                '''                The callback function that declares the fault
                ''',
                'rule_cb',
                'Cisco-IOS-XR-sysadmin-fm', False, is_config=False),
            ],
            'Cisco-IOS-XR-sysadmin-fm',
            'rules',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-sysadmin-fm'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_fm',
            is_config=False,
        ),
    },
    'Fm.Agents.FmInternals.Detail' : {
        'meta_info' : _MetaInfoClass('Fm.Agents.FmInternals.Detail', REFERENCE_LIST,
            ''' ''',
            False, 
            [
            _MetaInfoClassMember('fm_subsystem_id', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Fault sub-system identifier
                ''',
                'fm_subsystem_id',
                'Cisco-IOS-XR-sysadmin-fm', True, is_config=False),
            _MetaInfoClassMember('fm_fault_type', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Fault type identifier
                ''',
                'fm_fault_type',
                'Cisco-IOS-XR-sysadmin-fm', True, is_config=False),
            _MetaInfoClassMember('fm_fault_tag', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Fault tag identifier
                ''',
                'fm_fault_tag',
                'Cisco-IOS-XR-sysadmin-fm', True, is_config=False),
            _MetaInfoClassMember('rules', REFERENCE_LIST, 'Rules', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_fm', 'Fm.Agents.FmInternals.Detail.Rules',
                [], [],
                '''                list of fault rule declaring callbacks
                ''',
                'rules',
                'Cisco-IOS-XR-sysadmin-fm', False, is_config=False),
            _MetaInfoClassMember('common_action', ATTRIBUTE, 'int', 'uint16',
                None, None,
                [('0', '65535')], [],
                '''                Common action data
                ''',
                'common_action',
                'Cisco-IOS-XR-sysadmin-fm', False, is_config=False),
            _MetaInfoClassMember('opaque_action', ATTRIBUTE, 'int', 'uint16',
                None, None,
                [('0', '65535')], [],
                '''                opaque action data
                ''',
                'opaque_action',
                'Cisco-IOS-XR-sysadmin-fm', False, is_config=False),
            _MetaInfoClassMember('mitigation_cb', ATTRIBUTE, 'int', 'uint64',
                None, None,
                [('0', '18446744073709551615')], [],
                '''                Pointer to the mitigation callback function.
                ''',
                'mitigation_cb',
                'Cisco-IOS-XR-sysadmin-fm', False, is_config=False),
            _MetaInfoClassMember('recovery_cb', ATTRIBUTE, 'int', 'uint64',
                None, None,
                [('0', '18446744073709551615')], [],
                '''                Pointer to the recovery callback function.
                ''',
                'recovery_cb',
                'Cisco-IOS-XR-sysadmin-fm', False, is_config=False),
            _MetaInfoClassMember('alarm_severity_dirty', ATTRIBUTE, 'bool', 'boolean',
                None, None,
                [], [],
                '''                Flag indicates if alarm severity is dirty
                ''',
                'alarm_severity_dirty',
                'Cisco-IOS-XR-sysadmin-fm', False, is_config=False),
            _MetaInfoClassMember('disable_action', ATTRIBUTE, 'bool', 'boolean',
                None, None,
                [], [],
                '''                Flag indicates all actions are disabled.
                ''',
                'disable_action',
                'Cisco-IOS-XR-sysadmin-fm', False, is_config=False),
            _MetaInfoClassMember('repeat_action', ATTRIBUTE, 'bool', 'boolean',
                None, None,
                [], [],
                '''                Flag indicates all actions are repeated.
                ''',
                'repeat_action',
                'Cisco-IOS-XR-sysadmin-fm', False, is_config=False),
            _MetaInfoClassMember('has_causal_list', ATTRIBUTE, 'bool', 'boolean',
                None, None,
                [], [],
                '''                Flag indicates if causal list is present.
                ''',
                'has_causal_list',
                'Cisco-IOS-XR-sysadmin-fm', False, is_config=False),
            _MetaInfoClassMember('parser_tag', ATTRIBUTE, 'int', 'uint64',
                None, None,
                [('0', '18446744073709551615')], [],
                '''                The parser tag of the XML parser.
                ''',
                'parser_tag',
                'Cisco-IOS-XR-sysadmin-fm', False, is_config=False),
            _MetaInfoClassMember('parser_tag_string', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                The parser tag string.
                ''',
                'parser_tag_string',
                'Cisco-IOS-XR-sysadmin-fm', False, is_config=False),
            ],
            'Cisco-IOS-XR-sysadmin-fm',
            'detail',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-sysadmin-fm'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_fm',
            is_config=False,
        ),
    },
    'Fm.Agents.FmInternals' : {
        'meta_info' : _MetaInfoClass('Fm.Agents.FmInternals', REFERENCE_CLASS,
            ''' ''',
            False, 
            [
            _MetaInfoClassMember('detail', REFERENCE_LIST, 'Detail', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_fm', 'Fm.Agents.FmInternals.Detail',
                [], [],
                '''                ''',
                'detail',
                'Cisco-IOS-XR-sysadmin-fm', False, is_config=False),
            ],
            'Cisco-IOS-XR-sysadmin-fm',
            'fm_internals',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-sysadmin-fm'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_fm',
            is_config=False,
        ),
    },
    'Fm.Agents.FmAlarmMapping.Detail' : {
        'meta_info' : _MetaInfoClass('Fm.Agents.FmAlarmMapping.Detail', REFERENCE_LIST,
            ''' ''',
            False, 
            [
            _MetaInfoClassMember('fm_subsystem_id', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Fault sub-system identifier
                ''',
                'fm_subsystem_id',
                'Cisco-IOS-XR-sysadmin-fm', True, is_config=False),
            _MetaInfoClassMember('fm_fault_type', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Fault type identifier
                ''',
                'fm_fault_type',
                'Cisco-IOS-XR-sysadmin-fm', True, is_config=False),
            _MetaInfoClassMember('fm_fault_tag', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Fault tag identifier
                ''',
                'fm_fault_tag',
                'Cisco-IOS-XR-sysadmin-fm', True, is_config=False),
            _MetaInfoClassMember('alarm_group', ATTRIBUTE, 'int', 'uint16',
                None, None,
                [('0', '65535')], [],
                '''                The alarm grouping for this fault.
                ''',
                'alarm_group',
                'Cisco-IOS-XR-sysadmin-fm', False, is_config=False),
            _MetaInfoClassMember('alarm_severity', ATTRIBUTE, 'int', 'uint16',
                None, None,
                [('0', '65535')], [],
                '''                The alarm severity for this fault.
                ''',
                'alarm_severity',
                'Cisco-IOS-XR-sysadmin-fm', False, is_config=False),
            ],
            'Cisco-IOS-XR-sysadmin-fm',
            'detail',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-sysadmin-fm'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_fm',
            is_config=False,
        ),
    },
    'Fm.Agents.FmAlarmMapping' : {
        'meta_info' : _MetaInfoClass('Fm.Agents.FmAlarmMapping', REFERENCE_CLASS,
            ''' ''',
            False, 
            [
            _MetaInfoClassMember('detail', REFERENCE_LIST, 'Detail', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_fm', 'Fm.Agents.FmAlarmMapping.Detail',
                [], [],
                '''                ''',
                'detail',
                'Cisco-IOS-XR-sysadmin-fm', False, is_config=False),
            ],
            'Cisco-IOS-XR-sysadmin-fm',
            'fm_alarm_mapping',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-sysadmin-fm'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_fm',
            is_config=False,
        ),
    },
    'Fm.Agents.FmStatistics.Detail' : {
        'meta_info' : _MetaInfoClass('Fm.Agents.FmStatistics.Detail', REFERENCE_LIST,
            ''' ''',
            False, 
            [
            _MetaInfoClassMember('fm_subsystem_id', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Fault sub-system identifier
                ''',
                'fm_subsystem_id',
                'Cisco-IOS-XR-sysadmin-fm', True, is_config=False),
            _MetaInfoClassMember('fm_fault_type', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Fault type identifier
                ''',
                'fm_fault_type',
                'Cisco-IOS-XR-sysadmin-fm', True, is_config=False),
            _MetaInfoClassMember('fm_fault_tag', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Fault tag identifier
                ''',
                'fm_fault_tag',
                'Cisco-IOS-XR-sysadmin-fm', True, is_config=False),
            _MetaInfoClassMember('threshold_count', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                Threshold count for the fault
                ''',
                'threshold_count',
                'Cisco-IOS-XR-sysadmin-fm', False, is_config=False),
            _MetaInfoClassMember('all_object_occur_count', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                Object occurrence count.
                ''',
                'all_object_occur_count',
                'Cisco-IOS-XR-sysadmin-fm', False, is_config=False),
            _MetaInfoClassMember('declared_count', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                Number of times the fault is declared.
                ''',
                'declared_count',
                'Cisco-IOS-XR-sysadmin-fm', False, is_config=False),
            _MetaInfoClassMember('cleared_count', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                Number of times the fault is cleared.
                ''',
                'cleared_count',
                'Cisco-IOS-XR-sysadmin-fm', False, is_config=False),
            _MetaInfoClassMember('info_count', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                Number of times the fault is info.
                ''',
                'info_count',
                'Cisco-IOS-XR-sysadmin-fm', False, is_config=False),
            _MetaInfoClassMember('hold_time', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                The hold time in ms for soaking the fault.
                ''',
                'hold_time',
                'Cisco-IOS-XR-sysadmin-fm', False, is_config=False),
            ],
            'Cisco-IOS-XR-sysadmin-fm',
            'detail',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-sysadmin-fm'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_fm',
            is_config=False,
        ),
    },
    'Fm.Agents.FmStatistics' : {
        'meta_info' : _MetaInfoClass('Fm.Agents.FmStatistics', REFERENCE_CLASS,
            ''' ''',
            False, 
            [
            _MetaInfoClassMember('detail', REFERENCE_LIST, 'Detail', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_fm', 'Fm.Agents.FmStatistics.Detail',
                [], [],
                '''                ''',
                'detail',
                'Cisco-IOS-XR-sysadmin-fm', False, is_config=False),
            ],
            'Cisco-IOS-XR-sysadmin-fm',
            'fm_statistics',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-sysadmin-fm'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_fm',
            is_config=False,
        ),
    },
    'Fm.Agents' : {
        'meta_info' : _MetaInfoClass('Fm.Agents', REFERENCE_LIST,
            ''' ''',
            False, 
            [
            _MetaInfoClassMember('location', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                ''',
                'location',
                'Cisco-IOS-XR-sysadmin-fm', True, is_config=False),
            _MetaInfoClassMember('process', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                ''',
                'process',
                'Cisco-IOS-XR-sysadmin-fm', True, is_config=False),
            _MetaInfoClassMember('subsystem', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                ''',
                'subsystem',
                'Cisco-IOS-XR-sysadmin-fm', True, is_config=False),
            _MetaInfoClassMember('agent', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                ''',
                'agent',
                'Cisco-IOS-XR-sysadmin-fm', True, is_config=False),
            _MetaInfoClassMember('fm_initials', REFERENCE_CLASS, 'FmInitials', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_fm', 'Fm.Agents.FmInitials',
                [], [],
                '''                ''',
                'fm_initials',
                'Cisco-IOS-XR-sysadmin-fm', False, is_config=False),
            _MetaInfoClassMember('fm_table', REFERENCE_CLASS, 'FmTable', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_fm', 'Fm.Agents.FmTable',
                [], [],
                '''                ''',
                'fm_table',
                'Cisco-IOS-XR-sysadmin-fm', False, is_config=False),
            _MetaInfoClassMember('fm_internals', REFERENCE_CLASS, 'FmInternals', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_fm', 'Fm.Agents.FmInternals',
                [], [],
                '''                ''',
                'fm_internals',
                'Cisco-IOS-XR-sysadmin-fm', False, is_config=False),
            _MetaInfoClassMember('fm_alarm_mapping', REFERENCE_CLASS, 'FmAlarmMapping', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_fm', 'Fm.Agents.FmAlarmMapping',
                [], [],
                '''                ''',
                'fm_alarm_mapping',
                'Cisco-IOS-XR-sysadmin-fm', False, is_config=False),
            _MetaInfoClassMember('fm_statistics', REFERENCE_CLASS, 'FmStatistics', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_fm', 'Fm.Agents.FmStatistics',
                [], [],
                '''                ''',
                'fm_statistics',
                'Cisco-IOS-XR-sysadmin-fm', False, is_config=False),
            ],
            'Cisco-IOS-XR-sysadmin-fm',
            'agents',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-sysadmin-fm'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_fm',
            is_config=False,
        ),
    },
    'Fm' : {
        'meta_info' : _MetaInfoClass('Fm', REFERENCE_CLASS,
            '''Sysadmin fault management operational data model''',
            False, 
            [
            _MetaInfoClassMember('agents', REFERENCE_LIST, 'Agents', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_fm', 'Fm.Agents',
                [], [],
                '''                ''',
                'agents',
                'Cisco-IOS-XR-sysadmin-fm', False, is_config=False),
            ],
            'Cisco-IOS-XR-sysadmin-fm',
            'fm',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-sysadmin-fm'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_fm',
            is_config=False,
        ),
    },
}
_meta_table['Fm.Agents.FmTable.Entry.Faults.Active.Brief']['meta_info'].parent =_meta_table['Fm.Agents.FmTable.Entry.Faults.Active']['meta_info']
_meta_table['Fm.Agents.FmTable.Entry.Faults.Active.Detail']['meta_info'].parent =_meta_table['Fm.Agents.FmTable.Entry.Faults.Active']['meta_info']
_meta_table['Fm.Agents.FmTable.Entry.Faults.History.Brief']['meta_info'].parent =_meta_table['Fm.Agents.FmTable.Entry.Faults.History']['meta_info']
_meta_table['Fm.Agents.FmTable.Entry.Faults.History.Detail']['meta_info'].parent =_meta_table['Fm.Agents.FmTable.Entry.Faults.History']['meta_info']
_meta_table['Fm.Agents.FmTable.Entry.Faults.Active']['meta_info'].parent =_meta_table['Fm.Agents.FmTable.Entry.Faults']['meta_info']
_meta_table['Fm.Agents.FmTable.Entry.Faults.History']['meta_info'].parent =_meta_table['Fm.Agents.FmTable.Entry.Faults']['meta_info']
_meta_table['Fm.Agents.FmTable.Entry.WaitingList.Brief']['meta_info'].parent =_meta_table['Fm.Agents.FmTable.Entry.WaitingList']['meta_info']
_meta_table['Fm.Agents.FmTable.Entry.WaitingList.Entry_']['meta_info'].parent =_meta_table['Fm.Agents.FmTable.Entry.WaitingList']['meta_info']
_meta_table['Fm.Agents.FmTable.Entry.Detail']['meta_info'].parent =_meta_table['Fm.Agents.FmTable.Entry']['meta_info']
_meta_table['Fm.Agents.FmTable.Entry.CausalList']['meta_info'].parent =_meta_table['Fm.Agents.FmTable.Entry']['meta_info']
_meta_table['Fm.Agents.FmTable.Entry.DependencyList']['meta_info'].parent =_meta_table['Fm.Agents.FmTable.Entry']['meta_info']
_meta_table['Fm.Agents.FmTable.Entry.PropagationList']['meta_info'].parent =_meta_table['Fm.Agents.FmTable.Entry']['meta_info']
_meta_table['Fm.Agents.FmTable.Entry.NotificationList']['meta_info'].parent =_meta_table['Fm.Agents.FmTable.Entry']['meta_info']
_meta_table['Fm.Agents.FmTable.Entry.EscalationList']['meta_info'].parent =_meta_table['Fm.Agents.FmTable.Entry']['meta_info']
_meta_table['Fm.Agents.FmTable.Entry.Faults']['meta_info'].parent =_meta_table['Fm.Agents.FmTable.Entry']['meta_info']
_meta_table['Fm.Agents.FmTable.Entry.WaitingList']['meta_info'].parent =_meta_table['Fm.Agents.FmTable.Entry']['meta_info']
_meta_table['Fm.Agents.FmTable.Brief']['meta_info'].parent =_meta_table['Fm.Agents.FmTable']['meta_info']
_meta_table['Fm.Agents.FmTable.Entry']['meta_info'].parent =_meta_table['Fm.Agents.FmTable']['meta_info']
_meta_table['Fm.Agents.FmInternals.Detail.Rules']['meta_info'].parent =_meta_table['Fm.Agents.FmInternals.Detail']['meta_info']
_meta_table['Fm.Agents.FmInternals.Detail']['meta_info'].parent =_meta_table['Fm.Agents.FmInternals']['meta_info']
_meta_table['Fm.Agents.FmAlarmMapping.Detail']['meta_info'].parent =_meta_table['Fm.Agents.FmAlarmMapping']['meta_info']
_meta_table['Fm.Agents.FmStatistics.Detail']['meta_info'].parent =_meta_table['Fm.Agents.FmStatistics']['meta_info']
_meta_table['Fm.Agents.FmInitials']['meta_info'].parent =_meta_table['Fm.Agents']['meta_info']
_meta_table['Fm.Agents.FmTable']['meta_info'].parent =_meta_table['Fm.Agents']['meta_info']
_meta_table['Fm.Agents.FmInternals']['meta_info'].parent =_meta_table['Fm.Agents']['meta_info']
_meta_table['Fm.Agents.FmAlarmMapping']['meta_info'].parent =_meta_table['Fm.Agents']['meta_info']
_meta_table['Fm.Agents.FmStatistics']['meta_info'].parent =_meta_table['Fm.Agents']['meta_info']
_meta_table['Fm.Agents']['meta_info'].parent =_meta_table['Fm']['meta_info']
