
'''
This is auto-generated file,
which includes metadata for module Cisco_IOS_XR_dwdm_ui_cfg
'''

from ydk._core._dm_meta_info import _MetaInfoClassMember, _MetaInfoClass, _MetaInfoEnum
from ydk._core._dm_meta_info import ATTRIBUTE, REFERENCE_LIST, REFERENCE_LEAFLIST, REFERENCE_BITS, REFERENCE_UNION
from ydk._core._dm_meta_info import REFERENCE_CLASS, REFERENCE_IDENTITY_CLASS, REFERENCE_ENUM_CLASS, ANYXML_CLASS
from ydk._core._importer import _yang_ns

_meta_table = {
    'PrbsPattern' : _MetaInfoEnum('PrbsPattern',
        'ydk.models.cisco_ios_xr.Cisco_IOS_XR_dwdm_ui_cfg', 'PrbsPattern',
        '''Prbs pattern''',
        {
            'none':'none',
            'null':'null',
            'pn11':'pn11',
            'pn23':'pn23',
            'pn31':'pn31',
        }, 'Cisco-IOS-XR-dwdm-ui-cfg', _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-dwdm-ui-cfg']),
    'Proactive' : _MetaInfoEnum('Proactive',
        'ydk.models.cisco_ios_xr.Cisco_IOS_XR_dwdm_ui_cfg', 'Proactive',
        '''Proactive''',
        {
            'default':'default',
            'graceful':'graceful',
        }, 'Cisco-IOS-XR-dwdm-ui-cfg', _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-dwdm-ui-cfg']),
    'ExpectedTti' : _MetaInfoEnum('ExpectedTti',
        'ydk.models.cisco_ios_xr.Cisco_IOS_XR_dwdm_ui_cfg', 'ExpectedTti',
        '''Expected tti''',
        {
            'expected-tti-ascii':'expected_tti_ascii',
            'expected-tti-hex':'expected_tti_hex',
        }, 'Cisco-IOS-XR-dwdm-ui-cfg', _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-dwdm-ui-cfg']),
    'Fec' : _MetaInfoEnum('Fec',
        'ydk.models.cisco_ios_xr.Cisco_IOS_XR_dwdm_ui_cfg', 'Fec',
        '''Fec''',
        {
            'none':'none',
            'standard':'standard',
            'enhanced':'enhanced',
            'high-gain-hd':'high_gain_hd',
            'long-haul-hd':'long_haul_hd',
            'high-gain-sd':'high_gain_sd',
            'long-haul-sd':'long_haul_sd',
            'ci-bch':'ci_bch',
            'high-gain-multivendor-hd':'high_gain_multivendor_hd',
            '15sd-fec-de':'Y_15sd_fec_de',
            '15sd-fec':'Y_15sd_fec',
        }, 'Cisco-IOS-XR-dwdm-ui-cfg', _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-dwdm-ui-cfg']),
    'Framing' : _MetaInfoEnum('Framing',
        'ydk.models.cisco_ios_xr.Cisco_IOS_XR_dwdm_ui_cfg', 'Framing',
        '''Framing''',
        {
            'opu1e':'opu1e',
            'opu2e':'opu2e',
        }, 'Cisco-IOS-XR-dwdm-ui-cfg', _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-dwdm-ui-cfg']),
    'OtuThreshold' : _MetaInfoEnum('OtuThreshold',
        'ydk.models.cisco_ios_xr.Cisco_IOS_XR_dwdm_ui_cfg', 'OtuThreshold',
        '''Otu threshold''',
        {
            'prefec-sd':'prefec_sd',
            'prefec-sf':'prefec_sf',
            'otu-sd':'otu_sd',
            'otu-sf':'otu_sf',
        }, 'Cisco-IOS-XR-dwdm-ui-cfg', _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-dwdm-ui-cfg']),
    'DwdmLoopback' : _MetaInfoEnum('DwdmLoopback',
        'ydk.models.cisco_ios_xr.Cisco_IOS_XR_dwdm_ui_cfg', 'DwdmLoopback',
        '''Dwdm loopback''',
        {
            'none':'none',
            'line':'line',
            'internal':'internal',
        }, 'Cisco-IOS-XR-dwdm-ui-cfg', _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-dwdm-ui-cfg']),
    'Efec' : _MetaInfoEnum('Efec',
        'ydk.models.cisco_ios_xr.Cisco_IOS_XR_dwdm_ui_cfg', 'Efec',
        '''Efec''',
        {
            'none':'none',
            'i.4':'i__DOT__4',
            'i.7':'i__DOT__7',
        }, 'Cisco-IOS-XR-dwdm-ui-cfg', _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-dwdm-ui-cfg']),
    'OduAlarm' : _MetaInfoEnum('OduAlarm',
        'ydk.models.cisco_ios_xr.Cisco_IOS_XR_dwdm_ui_cfg', 'OduAlarm',
        '''Odu alarm''',
        {
            'oci':'oci',
            'odu-ais':'odu_ais',
            'lck':'lck',
            'odu-bdi':'odu_bdi',
            'odu-sf':'odu_sf',
            'odu-sd':'odu_sd',
            'plm':'plm',
            'odu-tim':'odu_tim',
        }, 'Cisco-IOS-XR-dwdm-ui-cfg', _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-dwdm-ui-cfg']),
    'PrbsMode' : _MetaInfoEnum('PrbsMode',
        'ydk.models.cisco_ios_xr.Cisco_IOS_XR_dwdm_ui_cfg', 'PrbsMode',
        '''Prbs mode''',
        {
            'source':'source',
            'sink':'sink',
            'source-sink':'source_sink',
            'invalid':'invalid',
        }, 'Cisco-IOS-XR-dwdm-ui-cfg', _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-dwdm-ui-cfg']),
    'TxTti' : _MetaInfoEnum('TxTti',
        'ydk.models.cisco_ios_xr.Cisco_IOS_XR_dwdm_ui_cfg', 'TxTti',
        '''Tx tti''',
        {
            'tx-tti-ascii':'tx_tti_ascii',
            'tx-tti-hex':'tx_tti_hex',
        }, 'Cisco-IOS-XR-dwdm-ui-cfg', _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-dwdm-ui-cfg']),
    'OtuAlarm' : _MetaInfoEnum('OtuAlarm',
        'ydk.models.cisco_ios_xr.Cisco_IOS_XR_dwdm_ui_cfg', 'OtuAlarm',
        '''Otu alarm''',
        {
            'los':'los',
            'lof':'lof',
            'lom':'lom',
            'iae':'iae',
            'otu-bdi':'otu_bdi',
            'otu-tim':'otu_tim',
            'otu-sf':'otu_sf',
            'otu-sd':'otu_sd',
            'fec-mismatch':'fec_mismatch',
            'prefec-sd-ber':'prefec_sd_ber',
            'prefec-sf-ber':'prefec_sf_ber',
        }, 'Cisco-IOS-XR-dwdm-ui-cfg', _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-dwdm-ui-cfg']),
    'DwdmAdminState' : _MetaInfoEnum('DwdmAdminState',
        'ydk.models.cisco_ios_xr.Cisco_IOS_XR_dwdm_ui_cfg', 'DwdmAdminState',
        '''Dwdm admin state''',
        {
            'out-of-service':'out_of_service',
            'in-service':'in_service',
            'maintenance':'maintenance',
            'in-service-config-allowed':'in_service_config_allowed',
        }, 'Cisco-IOS-XR-dwdm-ui-cfg', _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-dwdm-ui-cfg']),
    'OduThreshold' : _MetaInfoEnum('OduThreshold',
        'ydk.models.cisco_ios_xr.Cisco_IOS_XR_dwdm_ui_cfg', 'OduThreshold',
        '''Odu threshold''',
        {
            'odu-sd':'odu_sd',
            'odu-sf':'odu_sf',
        }, 'Cisco-IOS-XR-dwdm-ui-cfg', _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-dwdm-ui-cfg']),
    'WaveChannelNum' : _MetaInfoEnum('WaveChannelNum',
        'ydk.models.cisco_ios_xr.Cisco_IOS_XR_dwdm_ui_cfg', 'WaveChannelNum',
        '''Wave channel num''',
        {
            'default':'default',
            'channel-wavelength':'channel_wavelength',
            'channel-frequency':'channel_frequency',
            '100mhz-frequency':'Y_100mhz_frequency',
        }, 'Cisco-IOS-XR-dwdm-ui-cfg', _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-dwdm-ui-cfg']),
}
