
'''
This is auto-generated file,
which includes metadata for module Cisco_IOS_XR_pfm_oper
'''

from ydk._core._dm_meta_info import _MetaInfoClassMember, _MetaInfoClass, _MetaInfoEnum
from ydk._core._dm_meta_info import ATTRIBUTE, REFERENCE_LIST, REFERENCE_LEAFLIST, REFERENCE_BITS, REFERENCE_UNION
from ydk._core._dm_meta_info import REFERENCE_CLASS, REFERENCE_IDENTITY_CLASS, REFERENCE_ENUM_CLASS, ANYXML_CLASS
from ydk._core._importer import _yang_ns

_meta_table = {
    'PlatformFaultManager.Exclude.FaultType1s.FaultType1.FaultType2s.FaultType2.FaultType3s.FaultType3.Racks.Rack.Slots.Slot.FaultSummary' : {
        'meta_info' : _MetaInfoClass('PlatformFaultManager.Exclude.FaultType1s.FaultType1.FaultType2s.FaultType2.FaultType3s.FaultType3.Racks.Rack.Slots.Slot.FaultSummary', REFERENCE_CLASS,
            '''Table of Hardware Summary''',
            False, 
            [
            _MetaInfoClassMember('severity-critical-count', ATTRIBUTE, 'int', 'int32',
                None, None,
                [('-2147483648', '2147483647')], [],
                '''                Fault Severity Critical count
                ''',
                'severity_critical_count',
                'Cisco-IOS-XR-pfm-oper', False, is_config=False),
            _MetaInfoClassMember('severity-emergency-or-alert-count', ATTRIBUTE, 'int', 'int32',
                None, None,
                [('-2147483648', '2147483647')], [],
                '''                Fault Severity Emergency count
                ''',
                'severity_emergency_or_alert_count',
                'Cisco-IOS-XR-pfm-oper', False, is_config=False),
            _MetaInfoClassMember('total', ATTRIBUTE, 'int', 'int32',
                None, None,
                [('-2147483648', '2147483647')], [],
                '''                Faulty Hardware total count
                ''',
                'total',
                'Cisco-IOS-XR-pfm-oper', False, is_config=False),
            _MetaInfoClassMember('severity-error-count', ATTRIBUTE, 'int', 'int32',
                None, None,
                [('-2147483648', '2147483647')], [],
                '''                Fault Severity Error count
                ''',
                'severity_error_count',
                'Cisco-IOS-XR-pfm-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-pfm-oper',
            'fault-summary',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-pfm-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_pfm_oper',
            is_config=False,
        ),
    },
    'PlatformFaultManager.Exclude.FaultType1s.FaultType1.FaultType2s.FaultType2.FaultType3s.FaultType3.Racks.Rack.Slots.Slot.HardwareFaultDevices.HardwareFaultDevice.HardwareFaultType' : {
        'meta_info' : _MetaInfoClass('PlatformFaultManager.Exclude.FaultType1s.FaultType1.FaultType2s.FaultType2.FaultType3s.FaultType3.Racks.Rack.Slots.Slot.HardwareFaultDevices.HardwareFaultDevice.HardwareFaultType', REFERENCE_LIST,
            '''Table of Hardware Failure Type''',
            False, 
            [
            _MetaInfoClassMember('hw-fault-type', ATTRIBUTE, 'str', 'xr:Cisco-ios-xr-string',
                None, None,
                [], [b'[\\w\\-\\.:,_@#%$\\+=\\|;]+'],
                '''                hw fault type list
                ''',
                'hw_fault_type',
                'Cisco-IOS-XR-pfm-oper', True, is_config=False),
            _MetaInfoClassMember('condition-description', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Faulty Hardware Condition Description
                ''',
                'condition_description',
                'Cisco-IOS-XR-pfm-oper', False, is_config=False),
            _MetaInfoClassMember('condition-name', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Faulty Hardware Condition Name
                ''',
                'condition_name',
                'Cisco-IOS-XR-pfm-oper', False, is_config=False),
            _MetaInfoClassMember('device-key', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Faulty Hardware Device Key
                ''',
                'device_key',
                'Cisco-IOS-XR-pfm-oper', False, is_config=False),
            _MetaInfoClassMember('device-version', ATTRIBUTE, 'int', 'int32',
                None, None,
                [('-2147483648', '2147483647')], [],
                '''                Faulty Hardware Device Version
                ''',
                'device_version',
                'Cisco-IOS-XR-pfm-oper', False, is_config=False),
            _MetaInfoClassMember('condition-raised-timestamp', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Fault Raised Timestamp
                ''',
                'condition_raised_timestamp',
                'Cisco-IOS-XR-pfm-oper', False, is_config=False),
            _MetaInfoClassMember('process-id', ATTRIBUTE, 'int', 'int32',
                None, None,
                [('-2147483648', '2147483647')], [],
                '''                Faulty Hardware Process ID
                ''',
                'process_id',
                'Cisco-IOS-XR-pfm-oper', False, is_config=False),
            _MetaInfoClassMember('device-description', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Faulty Hardware Device Description
                ''',
                'device_description',
                'Cisco-IOS-XR-pfm-oper', False, is_config=False),
            _MetaInfoClassMember('condition-severity', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Faulty Hardware Condition Severity
                ''',
                'condition_severity',
                'Cisco-IOS-XR-pfm-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-pfm-oper',
            'hardware-fault-type',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-pfm-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_pfm_oper',
            is_config=False,
        ),
    },
    'PlatformFaultManager.Exclude.FaultType1s.FaultType1.FaultType2s.FaultType2.FaultType3s.FaultType3.Racks.Rack.Slots.Slot.HardwareFaultDevices.HardwareFaultDevice' : {
        'meta_info' : _MetaInfoClass('PlatformFaultManager.Exclude.FaultType1s.FaultType1.FaultType2s.FaultType2.FaultType3s.FaultType3.Racks.Rack.Slots.Slot.HardwareFaultDevices.HardwareFaultDevice', REFERENCE_LIST,
            '''Table of Hardware Failure Device''',
            False, 
            [
            _MetaInfoClassMember('hw-fault-device', ATTRIBUTE, 'str', 'xr:Cisco-ios-xr-string',
                None, None,
                [], [b'[\\w\\-\\.:,_@#%$\\+=\\|;]+'],
                '''                hw fault device list
                ''',
                'hw_fault_device',
                'Cisco-IOS-XR-pfm-oper', True, is_config=False),
            _MetaInfoClassMember('hardware-fault-type', REFERENCE_LIST, 'HardwareFaultType', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_pfm_oper', 'PlatformFaultManager.Exclude.FaultType1s.FaultType1.FaultType2s.FaultType2.FaultType3s.FaultType3.Racks.Rack.Slots.Slot.HardwareFaultDevices.HardwareFaultDevice.HardwareFaultType',
                [], [],
                '''                Table of Hardware Failure Type
                ''',
                'hardware_fault_type',
                'Cisco-IOS-XR-pfm-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-pfm-oper',
            'hardware-fault-device',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-pfm-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_pfm_oper',
            is_config=False,
        ),
    },
    'PlatformFaultManager.Exclude.FaultType1s.FaultType1.FaultType2s.FaultType2.FaultType3s.FaultType3.Racks.Rack.Slots.Slot.HardwareFaultDevices' : {
        'meta_info' : _MetaInfoClass('PlatformFaultManager.Exclude.FaultType1s.FaultType1.FaultType2s.FaultType2.FaultType3s.FaultType3.Racks.Rack.Slots.Slot.HardwareFaultDevices', REFERENCE_CLASS,
            '''Table of Hardware Failure''',
            False, 
            [
            _MetaInfoClassMember('hardware-fault-device', REFERENCE_LIST, 'HardwareFaultDevice', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_pfm_oper', 'PlatformFaultManager.Exclude.FaultType1s.FaultType1.FaultType2s.FaultType2.FaultType3s.FaultType3.Racks.Rack.Slots.Slot.HardwareFaultDevices.HardwareFaultDevice',
                [], [],
                '''                Table of Hardware Failure Device
                ''',
                'hardware_fault_device',
                'Cisco-IOS-XR-pfm-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-pfm-oper',
            'hardware-fault-devices',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-pfm-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_pfm_oper',
            is_config=False,
        ),
    },
    'PlatformFaultManager.Exclude.FaultType1s.FaultType1.FaultType2s.FaultType2.FaultType3s.FaultType3.Racks.Rack.Slots.Slot' : {
        'meta_info' : _MetaInfoClass('PlatformFaultManager.Exclude.FaultType1s.FaultType1.FaultType2s.FaultType2.FaultType3s.FaultType3.Racks.Rack.Slots.Slot', REFERENCE_LIST,
            '''Name''',
            False, 
            [
            _MetaInfoClassMember('slot', ATTRIBUTE, 'str', 'xr:Cisco-ios-xr-string',
                None, None,
                [], [b'[\\w\\-\\.:,_@#%$\\+=\\|;]+'],
                '''                Slot name
                ''',
                'slot',
                'Cisco-IOS-XR-pfm-oper', True, is_config=False),
            _MetaInfoClassMember('fault-summary', REFERENCE_CLASS, 'FaultSummary', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_pfm_oper', 'PlatformFaultManager.Exclude.FaultType1s.FaultType1.FaultType2s.FaultType2.FaultType3s.FaultType3.Racks.Rack.Slots.Slot.FaultSummary',
                [], [],
                '''                Table of Hardware Summary
                ''',
                'fault_summary',
                'Cisco-IOS-XR-pfm-oper', False, is_config=False),
            _MetaInfoClassMember('hardware-fault-devices', REFERENCE_CLASS, 'HardwareFaultDevices', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_pfm_oper', 'PlatformFaultManager.Exclude.FaultType1s.FaultType1.FaultType2s.FaultType2.FaultType3s.FaultType3.Racks.Rack.Slots.Slot.HardwareFaultDevices',
                [], [],
                '''                Table of Hardware Failure
                ''',
                'hardware_fault_devices',
                'Cisco-IOS-XR-pfm-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-pfm-oper',
            'slot',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-pfm-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_pfm_oper',
            is_config=False,
        ),
    },
    'PlatformFaultManager.Exclude.FaultType1s.FaultType1.FaultType2s.FaultType2.FaultType3s.FaultType3.Racks.Rack.Slots' : {
        'meta_info' : _MetaInfoClass('PlatformFaultManager.Exclude.FaultType1s.FaultType1.FaultType2s.FaultType2.FaultType3s.FaultType3.Racks.Rack.Slots', REFERENCE_CLASS,
            '''Table of slots''',
            False, 
            [
            _MetaInfoClassMember('slot', REFERENCE_LIST, 'Slot', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_pfm_oper', 'PlatformFaultManager.Exclude.FaultType1s.FaultType1.FaultType2s.FaultType2.FaultType3s.FaultType3.Racks.Rack.Slots.Slot',
                [], [],
                '''                Name
                ''',
                'slot',
                'Cisco-IOS-XR-pfm-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-pfm-oper',
            'slots',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-pfm-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_pfm_oper',
            is_config=False,
        ),
    },
    'PlatformFaultManager.Exclude.FaultType1s.FaultType1.FaultType2s.FaultType2.FaultType3s.FaultType3.Racks.Rack' : {
        'meta_info' : _MetaInfoClass('PlatformFaultManager.Exclude.FaultType1s.FaultType1.FaultType2s.FaultType2.FaultType3s.FaultType3.Racks.Rack', REFERENCE_LIST,
            '''Number''',
            False, 
            [
            _MetaInfoClassMember('rack', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                Rack number
                ''',
                'rack',
                'Cisco-IOS-XR-pfm-oper', True, is_config=False),
            _MetaInfoClassMember('slots', REFERENCE_CLASS, 'Slots', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_pfm_oper', 'PlatformFaultManager.Exclude.FaultType1s.FaultType1.FaultType2s.FaultType2.FaultType3s.FaultType3.Racks.Rack.Slots',
                [], [],
                '''                Table of slots
                ''',
                'slots',
                'Cisco-IOS-XR-pfm-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-pfm-oper',
            'rack',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-pfm-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_pfm_oper',
            is_config=False,
        ),
    },
    'PlatformFaultManager.Exclude.FaultType1s.FaultType1.FaultType2s.FaultType2.FaultType3s.FaultType3.Racks' : {
        'meta_info' : _MetaInfoClass('PlatformFaultManager.Exclude.FaultType1s.FaultType1.FaultType2s.FaultType2.FaultType3s.FaultType3.Racks', REFERENCE_CLASS,
            '''Table of racks''',
            False, 
            [
            _MetaInfoClassMember('rack', REFERENCE_LIST, 'Rack', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_pfm_oper', 'PlatformFaultManager.Exclude.FaultType1s.FaultType1.FaultType2s.FaultType2.FaultType3s.FaultType3.Racks.Rack',
                [], [],
                '''                Number
                ''',
                'rack',
                'Cisco-IOS-XR-pfm-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-pfm-oper',
            'racks',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-pfm-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_pfm_oper',
            is_config=False,
        ),
    },
    'PlatformFaultManager.Exclude.FaultType1s.FaultType1.FaultType2s.FaultType2.FaultType3s.FaultType3' : {
        'meta_info' : _MetaInfoClass('PlatformFaultManager.Exclude.FaultType1s.FaultType1.FaultType2s.FaultType2.FaultType3s.FaultType3', REFERENCE_LIST,
            '''Table of Hardware Failure Device''',
            False, 
            [
            _MetaInfoClassMember('hw-fault-type3', ATTRIBUTE, 'str', 'xr:Cisco-ios-xr-string',
                None, None,
                [], [b'[\\w\\-\\.:,_@#%$\\+=\\|;]+'],
                '''                hw fault 3
                ''',
                'hw_fault_type3',
                'Cisco-IOS-XR-pfm-oper', True, is_config=False),
            _MetaInfoClassMember('racks', REFERENCE_CLASS, 'Racks', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_pfm_oper', 'PlatformFaultManager.Exclude.FaultType1s.FaultType1.FaultType2s.FaultType2.FaultType3s.FaultType3.Racks',
                [], [],
                '''                Table of racks
                ''',
                'racks',
                'Cisco-IOS-XR-pfm-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-pfm-oper',
            'fault-type3',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-pfm-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_pfm_oper',
            is_config=False,
        ),
    },
    'PlatformFaultManager.Exclude.FaultType1s.FaultType1.FaultType2s.FaultType2.FaultType3s' : {
        'meta_info' : _MetaInfoClass('PlatformFaultManager.Exclude.FaultType1s.FaultType1.FaultType2s.FaultType2.FaultType3s', REFERENCE_CLASS,
            '''Table of Hardware Failure Device''',
            False, 
            [
            _MetaInfoClassMember('fault-type3', REFERENCE_LIST, 'FaultType3', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_pfm_oper', 'PlatformFaultManager.Exclude.FaultType1s.FaultType1.FaultType2s.FaultType2.FaultType3s.FaultType3',
                [], [],
                '''                Table of Hardware Failure Device
                ''',
                'fault_type3',
                'Cisco-IOS-XR-pfm-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-pfm-oper',
            'fault-type3s',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-pfm-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_pfm_oper',
            is_config=False,
        ),
    },
    'PlatformFaultManager.Exclude.FaultType1s.FaultType1.FaultType2s.FaultType2.Racks.Rack.Slots.Slot.FaultSummary' : {
        'meta_info' : _MetaInfoClass('PlatformFaultManager.Exclude.FaultType1s.FaultType1.FaultType2s.FaultType2.Racks.Rack.Slots.Slot.FaultSummary', REFERENCE_CLASS,
            '''Table of Hardware Summary''',
            False, 
            [
            _MetaInfoClassMember('severity-critical-count', ATTRIBUTE, 'int', 'int32',
                None, None,
                [('-2147483648', '2147483647')], [],
                '''                Fault Severity Critical count
                ''',
                'severity_critical_count',
                'Cisco-IOS-XR-pfm-oper', False, is_config=False),
            _MetaInfoClassMember('severity-emergency-or-alert-count', ATTRIBUTE, 'int', 'int32',
                None, None,
                [('-2147483648', '2147483647')], [],
                '''                Fault Severity Emergency count
                ''',
                'severity_emergency_or_alert_count',
                'Cisco-IOS-XR-pfm-oper', False, is_config=False),
            _MetaInfoClassMember('total', ATTRIBUTE, 'int', 'int32',
                None, None,
                [('-2147483648', '2147483647')], [],
                '''                Faulty Hardware total count
                ''',
                'total',
                'Cisco-IOS-XR-pfm-oper', False, is_config=False),
            _MetaInfoClassMember('severity-error-count', ATTRIBUTE, 'int', 'int32',
                None, None,
                [('-2147483648', '2147483647')], [],
                '''                Fault Severity Error count
                ''',
                'severity_error_count',
                'Cisco-IOS-XR-pfm-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-pfm-oper',
            'fault-summary',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-pfm-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_pfm_oper',
            is_config=False,
        ),
    },
    'PlatformFaultManager.Exclude.FaultType1s.FaultType1.FaultType2s.FaultType2.Racks.Rack.Slots.Slot.HardwareFaultDevices.HardwareFaultDevice.HardwareFaultType' : {
        'meta_info' : _MetaInfoClass('PlatformFaultManager.Exclude.FaultType1s.FaultType1.FaultType2s.FaultType2.Racks.Rack.Slots.Slot.HardwareFaultDevices.HardwareFaultDevice.HardwareFaultType', REFERENCE_LIST,
            '''Table of Hardware Failure Type''',
            False, 
            [
            _MetaInfoClassMember('hw-fault-type', ATTRIBUTE, 'str', 'xr:Cisco-ios-xr-string',
                None, None,
                [], [b'[\\w\\-\\.:,_@#%$\\+=\\|;]+'],
                '''                hw fault type list
                ''',
                'hw_fault_type',
                'Cisco-IOS-XR-pfm-oper', True, is_config=False),
            _MetaInfoClassMember('condition-description', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Faulty Hardware Condition Description
                ''',
                'condition_description',
                'Cisco-IOS-XR-pfm-oper', False, is_config=False),
            _MetaInfoClassMember('condition-name', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Faulty Hardware Condition Name
                ''',
                'condition_name',
                'Cisco-IOS-XR-pfm-oper', False, is_config=False),
            _MetaInfoClassMember('device-key', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Faulty Hardware Device Key
                ''',
                'device_key',
                'Cisco-IOS-XR-pfm-oper', False, is_config=False),
            _MetaInfoClassMember('device-version', ATTRIBUTE, 'int', 'int32',
                None, None,
                [('-2147483648', '2147483647')], [],
                '''                Faulty Hardware Device Version
                ''',
                'device_version',
                'Cisco-IOS-XR-pfm-oper', False, is_config=False),
            _MetaInfoClassMember('condition-raised-timestamp', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Fault Raised Timestamp
                ''',
                'condition_raised_timestamp',
                'Cisco-IOS-XR-pfm-oper', False, is_config=False),
            _MetaInfoClassMember('process-id', ATTRIBUTE, 'int', 'int32',
                None, None,
                [('-2147483648', '2147483647')], [],
                '''                Faulty Hardware Process ID
                ''',
                'process_id',
                'Cisco-IOS-XR-pfm-oper', False, is_config=False),
            _MetaInfoClassMember('device-description', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Faulty Hardware Device Description
                ''',
                'device_description',
                'Cisco-IOS-XR-pfm-oper', False, is_config=False),
            _MetaInfoClassMember('condition-severity', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Faulty Hardware Condition Severity
                ''',
                'condition_severity',
                'Cisco-IOS-XR-pfm-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-pfm-oper',
            'hardware-fault-type',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-pfm-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_pfm_oper',
            is_config=False,
        ),
    },
    'PlatformFaultManager.Exclude.FaultType1s.FaultType1.FaultType2s.FaultType2.Racks.Rack.Slots.Slot.HardwareFaultDevices.HardwareFaultDevice' : {
        'meta_info' : _MetaInfoClass('PlatformFaultManager.Exclude.FaultType1s.FaultType1.FaultType2s.FaultType2.Racks.Rack.Slots.Slot.HardwareFaultDevices.HardwareFaultDevice', REFERENCE_LIST,
            '''Table of Hardware Failure Device''',
            False, 
            [
            _MetaInfoClassMember('hw-fault-device', ATTRIBUTE, 'str', 'xr:Cisco-ios-xr-string',
                None, None,
                [], [b'[\\w\\-\\.:,_@#%$\\+=\\|;]+'],
                '''                hw fault device list
                ''',
                'hw_fault_device',
                'Cisco-IOS-XR-pfm-oper', True, is_config=False),
            _MetaInfoClassMember('hardware-fault-type', REFERENCE_LIST, 'HardwareFaultType', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_pfm_oper', 'PlatformFaultManager.Exclude.FaultType1s.FaultType1.FaultType2s.FaultType2.Racks.Rack.Slots.Slot.HardwareFaultDevices.HardwareFaultDevice.HardwareFaultType',
                [], [],
                '''                Table of Hardware Failure Type
                ''',
                'hardware_fault_type',
                'Cisco-IOS-XR-pfm-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-pfm-oper',
            'hardware-fault-device',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-pfm-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_pfm_oper',
            is_config=False,
        ),
    },
    'PlatformFaultManager.Exclude.FaultType1s.FaultType1.FaultType2s.FaultType2.Racks.Rack.Slots.Slot.HardwareFaultDevices' : {
        'meta_info' : _MetaInfoClass('PlatformFaultManager.Exclude.FaultType1s.FaultType1.FaultType2s.FaultType2.Racks.Rack.Slots.Slot.HardwareFaultDevices', REFERENCE_CLASS,
            '''Table of Hardware Failure''',
            False, 
            [
            _MetaInfoClassMember('hardware-fault-device', REFERENCE_LIST, 'HardwareFaultDevice', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_pfm_oper', 'PlatformFaultManager.Exclude.FaultType1s.FaultType1.FaultType2s.FaultType2.Racks.Rack.Slots.Slot.HardwareFaultDevices.HardwareFaultDevice',
                [], [],
                '''                Table of Hardware Failure Device
                ''',
                'hardware_fault_device',
                'Cisco-IOS-XR-pfm-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-pfm-oper',
            'hardware-fault-devices',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-pfm-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_pfm_oper',
            is_config=False,
        ),
    },
    'PlatformFaultManager.Exclude.FaultType1s.FaultType1.FaultType2s.FaultType2.Racks.Rack.Slots.Slot' : {
        'meta_info' : _MetaInfoClass('PlatformFaultManager.Exclude.FaultType1s.FaultType1.FaultType2s.FaultType2.Racks.Rack.Slots.Slot', REFERENCE_LIST,
            '''Name''',
            False, 
            [
            _MetaInfoClassMember('slot', ATTRIBUTE, 'str', 'xr:Cisco-ios-xr-string',
                None, None,
                [], [b'[\\w\\-\\.:,_@#%$\\+=\\|;]+'],
                '''                Slot name
                ''',
                'slot',
                'Cisco-IOS-XR-pfm-oper', True, is_config=False),
            _MetaInfoClassMember('fault-summary', REFERENCE_CLASS, 'FaultSummary', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_pfm_oper', 'PlatformFaultManager.Exclude.FaultType1s.FaultType1.FaultType2s.FaultType2.Racks.Rack.Slots.Slot.FaultSummary',
                [], [],
                '''                Table of Hardware Summary
                ''',
                'fault_summary',
                'Cisco-IOS-XR-pfm-oper', False, is_config=False),
            _MetaInfoClassMember('hardware-fault-devices', REFERENCE_CLASS, 'HardwareFaultDevices', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_pfm_oper', 'PlatformFaultManager.Exclude.FaultType1s.FaultType1.FaultType2s.FaultType2.Racks.Rack.Slots.Slot.HardwareFaultDevices',
                [], [],
                '''                Table of Hardware Failure
                ''',
                'hardware_fault_devices',
                'Cisco-IOS-XR-pfm-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-pfm-oper',
            'slot',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-pfm-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_pfm_oper',
            is_config=False,
        ),
    },
    'PlatformFaultManager.Exclude.FaultType1s.FaultType1.FaultType2s.FaultType2.Racks.Rack.Slots' : {
        'meta_info' : _MetaInfoClass('PlatformFaultManager.Exclude.FaultType1s.FaultType1.FaultType2s.FaultType2.Racks.Rack.Slots', REFERENCE_CLASS,
            '''Table of slots''',
            False, 
            [
            _MetaInfoClassMember('slot', REFERENCE_LIST, 'Slot', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_pfm_oper', 'PlatformFaultManager.Exclude.FaultType1s.FaultType1.FaultType2s.FaultType2.Racks.Rack.Slots.Slot',
                [], [],
                '''                Name
                ''',
                'slot',
                'Cisco-IOS-XR-pfm-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-pfm-oper',
            'slots',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-pfm-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_pfm_oper',
            is_config=False,
        ),
    },
    'PlatformFaultManager.Exclude.FaultType1s.FaultType1.FaultType2s.FaultType2.Racks.Rack' : {
        'meta_info' : _MetaInfoClass('PlatformFaultManager.Exclude.FaultType1s.FaultType1.FaultType2s.FaultType2.Racks.Rack', REFERENCE_LIST,
            '''Number''',
            False, 
            [
            _MetaInfoClassMember('rack', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                Rack number
                ''',
                'rack',
                'Cisco-IOS-XR-pfm-oper', True, is_config=False),
            _MetaInfoClassMember('slots', REFERENCE_CLASS, 'Slots', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_pfm_oper', 'PlatformFaultManager.Exclude.FaultType1s.FaultType1.FaultType2s.FaultType2.Racks.Rack.Slots',
                [], [],
                '''                Table of slots
                ''',
                'slots',
                'Cisco-IOS-XR-pfm-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-pfm-oper',
            'rack',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-pfm-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_pfm_oper',
            is_config=False,
        ),
    },
    'PlatformFaultManager.Exclude.FaultType1s.FaultType1.FaultType2s.FaultType2.Racks' : {
        'meta_info' : _MetaInfoClass('PlatformFaultManager.Exclude.FaultType1s.FaultType1.FaultType2s.FaultType2.Racks', REFERENCE_CLASS,
            '''Table of racks''',
            False, 
            [
            _MetaInfoClassMember('rack', REFERENCE_LIST, 'Rack', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_pfm_oper', 'PlatformFaultManager.Exclude.FaultType1s.FaultType1.FaultType2s.FaultType2.Racks.Rack',
                [], [],
                '''                Number
                ''',
                'rack',
                'Cisco-IOS-XR-pfm-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-pfm-oper',
            'racks',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-pfm-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_pfm_oper',
            is_config=False,
        ),
    },
    'PlatformFaultManager.Exclude.FaultType1s.FaultType1.FaultType2s.FaultType2' : {
        'meta_info' : _MetaInfoClass('PlatformFaultManager.Exclude.FaultType1s.FaultType1.FaultType2s.FaultType2', REFERENCE_LIST,
            '''Table of Hardware Failure Device''',
            False, 
            [
            _MetaInfoClassMember('hw-fault-type2', ATTRIBUTE, 'str', 'xr:Cisco-ios-xr-string',
                None, None,
                [], [b'[\\w\\-\\.:,_@#%$\\+=\\|;]+'],
                '''                hw fault 2
                ''',
                'hw_fault_type2',
                'Cisco-IOS-XR-pfm-oper', True, is_config=False),
            _MetaInfoClassMember('fault-type3s', REFERENCE_CLASS, 'FaultType3s', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_pfm_oper', 'PlatformFaultManager.Exclude.FaultType1s.FaultType1.FaultType2s.FaultType2.FaultType3s',
                [], [],
                '''                Table of Hardware Failure Device
                ''',
                'fault_type3s',
                'Cisco-IOS-XR-pfm-oper', False, is_config=False),
            _MetaInfoClassMember('racks', REFERENCE_CLASS, 'Racks', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_pfm_oper', 'PlatformFaultManager.Exclude.FaultType1s.FaultType1.FaultType2s.FaultType2.Racks',
                [], [],
                '''                Table of racks
                ''',
                'racks',
                'Cisco-IOS-XR-pfm-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-pfm-oper',
            'fault-type2',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-pfm-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_pfm_oper',
            is_config=False,
        ),
    },
    'PlatformFaultManager.Exclude.FaultType1s.FaultType1.FaultType2s' : {
        'meta_info' : _MetaInfoClass('PlatformFaultManager.Exclude.FaultType1s.FaultType1.FaultType2s', REFERENCE_CLASS,
            '''Table of Hardware Failure Device''',
            False, 
            [
            _MetaInfoClassMember('fault-type2', REFERENCE_LIST, 'FaultType2', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_pfm_oper', 'PlatformFaultManager.Exclude.FaultType1s.FaultType1.FaultType2s.FaultType2',
                [], [],
                '''                Table of Hardware Failure Device
                ''',
                'fault_type2',
                'Cisco-IOS-XR-pfm-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-pfm-oper',
            'fault-type2s',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-pfm-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_pfm_oper',
            is_config=False,
        ),
    },
    'PlatformFaultManager.Exclude.FaultType1s.FaultType1.Racks.Rack.Slots.Slot.FaultSummary' : {
        'meta_info' : _MetaInfoClass('PlatformFaultManager.Exclude.FaultType1s.FaultType1.Racks.Rack.Slots.Slot.FaultSummary', REFERENCE_CLASS,
            '''Table of Hardware Summary''',
            False, 
            [
            _MetaInfoClassMember('severity-critical-count', ATTRIBUTE, 'int', 'int32',
                None, None,
                [('-2147483648', '2147483647')], [],
                '''                Fault Severity Critical count
                ''',
                'severity_critical_count',
                'Cisco-IOS-XR-pfm-oper', False, is_config=False),
            _MetaInfoClassMember('severity-emergency-or-alert-count', ATTRIBUTE, 'int', 'int32',
                None, None,
                [('-2147483648', '2147483647')], [],
                '''                Fault Severity Emergency count
                ''',
                'severity_emergency_or_alert_count',
                'Cisco-IOS-XR-pfm-oper', False, is_config=False),
            _MetaInfoClassMember('total', ATTRIBUTE, 'int', 'int32',
                None, None,
                [('-2147483648', '2147483647')], [],
                '''                Faulty Hardware total count
                ''',
                'total',
                'Cisco-IOS-XR-pfm-oper', False, is_config=False),
            _MetaInfoClassMember('severity-error-count', ATTRIBUTE, 'int', 'int32',
                None, None,
                [('-2147483648', '2147483647')], [],
                '''                Fault Severity Error count
                ''',
                'severity_error_count',
                'Cisco-IOS-XR-pfm-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-pfm-oper',
            'fault-summary',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-pfm-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_pfm_oper',
            is_config=False,
        ),
    },
    'PlatformFaultManager.Exclude.FaultType1s.FaultType1.Racks.Rack.Slots.Slot.HardwareFaultDevices.HardwareFaultDevice.HardwareFaultType' : {
        'meta_info' : _MetaInfoClass('PlatformFaultManager.Exclude.FaultType1s.FaultType1.Racks.Rack.Slots.Slot.HardwareFaultDevices.HardwareFaultDevice.HardwareFaultType', REFERENCE_LIST,
            '''Table of Hardware Failure Type''',
            False, 
            [
            _MetaInfoClassMember('hw-fault-type', ATTRIBUTE, 'str', 'xr:Cisco-ios-xr-string',
                None, None,
                [], [b'[\\w\\-\\.:,_@#%$\\+=\\|;]+'],
                '''                hw fault type list
                ''',
                'hw_fault_type',
                'Cisco-IOS-XR-pfm-oper', True, is_config=False),
            _MetaInfoClassMember('condition-description', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Faulty Hardware Condition Description
                ''',
                'condition_description',
                'Cisco-IOS-XR-pfm-oper', False, is_config=False),
            _MetaInfoClassMember('condition-name', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Faulty Hardware Condition Name
                ''',
                'condition_name',
                'Cisco-IOS-XR-pfm-oper', False, is_config=False),
            _MetaInfoClassMember('device-key', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Faulty Hardware Device Key
                ''',
                'device_key',
                'Cisco-IOS-XR-pfm-oper', False, is_config=False),
            _MetaInfoClassMember('device-version', ATTRIBUTE, 'int', 'int32',
                None, None,
                [('-2147483648', '2147483647')], [],
                '''                Faulty Hardware Device Version
                ''',
                'device_version',
                'Cisco-IOS-XR-pfm-oper', False, is_config=False),
            _MetaInfoClassMember('condition-raised-timestamp', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Fault Raised Timestamp
                ''',
                'condition_raised_timestamp',
                'Cisco-IOS-XR-pfm-oper', False, is_config=False),
            _MetaInfoClassMember('process-id', ATTRIBUTE, 'int', 'int32',
                None, None,
                [('-2147483648', '2147483647')], [],
                '''                Faulty Hardware Process ID
                ''',
                'process_id',
                'Cisco-IOS-XR-pfm-oper', False, is_config=False),
            _MetaInfoClassMember('device-description', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Faulty Hardware Device Description
                ''',
                'device_description',
                'Cisco-IOS-XR-pfm-oper', False, is_config=False),
            _MetaInfoClassMember('condition-severity', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Faulty Hardware Condition Severity
                ''',
                'condition_severity',
                'Cisco-IOS-XR-pfm-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-pfm-oper',
            'hardware-fault-type',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-pfm-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_pfm_oper',
            is_config=False,
        ),
    },
    'PlatformFaultManager.Exclude.FaultType1s.FaultType1.Racks.Rack.Slots.Slot.HardwareFaultDevices.HardwareFaultDevice' : {
        'meta_info' : _MetaInfoClass('PlatformFaultManager.Exclude.FaultType1s.FaultType1.Racks.Rack.Slots.Slot.HardwareFaultDevices.HardwareFaultDevice', REFERENCE_LIST,
            '''Table of Hardware Failure Device''',
            False, 
            [
            _MetaInfoClassMember('hw-fault-device', ATTRIBUTE, 'str', 'xr:Cisco-ios-xr-string',
                None, None,
                [], [b'[\\w\\-\\.:,_@#%$\\+=\\|;]+'],
                '''                hw fault device list
                ''',
                'hw_fault_device',
                'Cisco-IOS-XR-pfm-oper', True, is_config=False),
            _MetaInfoClassMember('hardware-fault-type', REFERENCE_LIST, 'HardwareFaultType', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_pfm_oper', 'PlatformFaultManager.Exclude.FaultType1s.FaultType1.Racks.Rack.Slots.Slot.HardwareFaultDevices.HardwareFaultDevice.HardwareFaultType',
                [], [],
                '''                Table of Hardware Failure Type
                ''',
                'hardware_fault_type',
                'Cisco-IOS-XR-pfm-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-pfm-oper',
            'hardware-fault-device',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-pfm-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_pfm_oper',
            is_config=False,
        ),
    },
    'PlatformFaultManager.Exclude.FaultType1s.FaultType1.Racks.Rack.Slots.Slot.HardwareFaultDevices' : {
        'meta_info' : _MetaInfoClass('PlatformFaultManager.Exclude.FaultType1s.FaultType1.Racks.Rack.Slots.Slot.HardwareFaultDevices', REFERENCE_CLASS,
            '''Table of Hardware Failure''',
            False, 
            [
            _MetaInfoClassMember('hardware-fault-device', REFERENCE_LIST, 'HardwareFaultDevice', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_pfm_oper', 'PlatformFaultManager.Exclude.FaultType1s.FaultType1.Racks.Rack.Slots.Slot.HardwareFaultDevices.HardwareFaultDevice',
                [], [],
                '''                Table of Hardware Failure Device
                ''',
                'hardware_fault_device',
                'Cisco-IOS-XR-pfm-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-pfm-oper',
            'hardware-fault-devices',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-pfm-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_pfm_oper',
            is_config=False,
        ),
    },
    'PlatformFaultManager.Exclude.FaultType1s.FaultType1.Racks.Rack.Slots.Slot' : {
        'meta_info' : _MetaInfoClass('PlatformFaultManager.Exclude.FaultType1s.FaultType1.Racks.Rack.Slots.Slot', REFERENCE_LIST,
            '''Name''',
            False, 
            [
            _MetaInfoClassMember('slot', ATTRIBUTE, 'str', 'xr:Cisco-ios-xr-string',
                None, None,
                [], [b'[\\w\\-\\.:,_@#%$\\+=\\|;]+'],
                '''                Slot name
                ''',
                'slot',
                'Cisco-IOS-XR-pfm-oper', True, is_config=False),
            _MetaInfoClassMember('fault-summary', REFERENCE_CLASS, 'FaultSummary', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_pfm_oper', 'PlatformFaultManager.Exclude.FaultType1s.FaultType1.Racks.Rack.Slots.Slot.FaultSummary',
                [], [],
                '''                Table of Hardware Summary
                ''',
                'fault_summary',
                'Cisco-IOS-XR-pfm-oper', False, is_config=False),
            _MetaInfoClassMember('hardware-fault-devices', REFERENCE_CLASS, 'HardwareFaultDevices', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_pfm_oper', 'PlatformFaultManager.Exclude.FaultType1s.FaultType1.Racks.Rack.Slots.Slot.HardwareFaultDevices',
                [], [],
                '''                Table of Hardware Failure
                ''',
                'hardware_fault_devices',
                'Cisco-IOS-XR-pfm-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-pfm-oper',
            'slot',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-pfm-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_pfm_oper',
            is_config=False,
        ),
    },
    'PlatformFaultManager.Exclude.FaultType1s.FaultType1.Racks.Rack.Slots' : {
        'meta_info' : _MetaInfoClass('PlatformFaultManager.Exclude.FaultType1s.FaultType1.Racks.Rack.Slots', REFERENCE_CLASS,
            '''Table of slots''',
            False, 
            [
            _MetaInfoClassMember('slot', REFERENCE_LIST, 'Slot', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_pfm_oper', 'PlatformFaultManager.Exclude.FaultType1s.FaultType1.Racks.Rack.Slots.Slot',
                [], [],
                '''                Name
                ''',
                'slot',
                'Cisco-IOS-XR-pfm-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-pfm-oper',
            'slots',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-pfm-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_pfm_oper',
            is_config=False,
        ),
    },
    'PlatformFaultManager.Exclude.FaultType1s.FaultType1.Racks.Rack' : {
        'meta_info' : _MetaInfoClass('PlatformFaultManager.Exclude.FaultType1s.FaultType1.Racks.Rack', REFERENCE_LIST,
            '''Number''',
            False, 
            [
            _MetaInfoClassMember('rack', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                Rack number
                ''',
                'rack',
                'Cisco-IOS-XR-pfm-oper', True, is_config=False),
            _MetaInfoClassMember('slots', REFERENCE_CLASS, 'Slots', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_pfm_oper', 'PlatformFaultManager.Exclude.FaultType1s.FaultType1.Racks.Rack.Slots',
                [], [],
                '''                Table of slots
                ''',
                'slots',
                'Cisco-IOS-XR-pfm-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-pfm-oper',
            'rack',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-pfm-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_pfm_oper',
            is_config=False,
        ),
    },
    'PlatformFaultManager.Exclude.FaultType1s.FaultType1.Racks' : {
        'meta_info' : _MetaInfoClass('PlatformFaultManager.Exclude.FaultType1s.FaultType1.Racks', REFERENCE_CLASS,
            '''Table of racks''',
            False, 
            [
            _MetaInfoClassMember('rack', REFERENCE_LIST, 'Rack', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_pfm_oper', 'PlatformFaultManager.Exclude.FaultType1s.FaultType1.Racks.Rack',
                [], [],
                '''                Number
                ''',
                'rack',
                'Cisco-IOS-XR-pfm-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-pfm-oper',
            'racks',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-pfm-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_pfm_oper',
            is_config=False,
        ),
    },
    'PlatformFaultManager.Exclude.FaultType1s.FaultType1' : {
        'meta_info' : _MetaInfoClass('PlatformFaultManager.Exclude.FaultType1s.FaultType1', REFERENCE_LIST,
            '''Table of Hardware Failure Device''',
            False, 
            [
            _MetaInfoClassMember('hw-fault-type1', ATTRIBUTE, 'str', 'xr:Cisco-ios-xr-string',
                None, None,
                [], [b'[\\w\\-\\.:,_@#%$\\+=\\|;]+'],
                '''                hw fault 1
                ''',
                'hw_fault_type1',
                'Cisco-IOS-XR-pfm-oper', True, is_config=False),
            _MetaInfoClassMember('fault-type2s', REFERENCE_CLASS, 'FaultType2s', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_pfm_oper', 'PlatformFaultManager.Exclude.FaultType1s.FaultType1.FaultType2s',
                [], [],
                '''                Table of Hardware Failure Device
                ''',
                'fault_type2s',
                'Cisco-IOS-XR-pfm-oper', False, is_config=False),
            _MetaInfoClassMember('racks', REFERENCE_CLASS, 'Racks', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_pfm_oper', 'PlatformFaultManager.Exclude.FaultType1s.FaultType1.Racks',
                [], [],
                '''                Table of racks
                ''',
                'racks',
                'Cisco-IOS-XR-pfm-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-pfm-oper',
            'fault-type1',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-pfm-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_pfm_oper',
            is_config=False,
        ),
    },
    'PlatformFaultManager.Exclude.FaultType1s' : {
        'meta_info' : _MetaInfoClass('PlatformFaultManager.Exclude.FaultType1s', REFERENCE_CLASS,
            '''Table of Hardware Failure Device''',
            False, 
            [
            _MetaInfoClassMember('fault-type1', REFERENCE_LIST, 'FaultType1', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_pfm_oper', 'PlatformFaultManager.Exclude.FaultType1s.FaultType1',
                [], [],
                '''                Table of Hardware Failure Device
                ''',
                'fault_type1',
                'Cisco-IOS-XR-pfm-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-pfm-oper',
            'fault-type1s',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-pfm-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_pfm_oper',
            is_config=False,
        ),
    },
    'PlatformFaultManager.Exclude' : {
        'meta_info' : _MetaInfoClass('PlatformFaultManager.Exclude', REFERENCE_CLASS,
            '''Exclude specic hw fault ''',
            False, 
            [
            _MetaInfoClassMember('fault-type1s', REFERENCE_CLASS, 'FaultType1s', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_pfm_oper', 'PlatformFaultManager.Exclude.FaultType1s',
                [], [],
                '''                Table of Hardware Failure Device
                ''',
                'fault_type1s',
                'Cisco-IOS-XR-pfm-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-pfm-oper',
            'exclude',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-pfm-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_pfm_oper',
            is_config=False,
        ),
    },
    'PlatformFaultManager.Racks.Rack.Slots.Slot.FaultSummary' : {
        'meta_info' : _MetaInfoClass('PlatformFaultManager.Racks.Rack.Slots.Slot.FaultSummary', REFERENCE_CLASS,
            '''Table of Hardware Summary''',
            False, 
            [
            _MetaInfoClassMember('severity-critical-count', ATTRIBUTE, 'int', 'int32',
                None, None,
                [('-2147483648', '2147483647')], [],
                '''                Fault Severity Critical count
                ''',
                'severity_critical_count',
                'Cisco-IOS-XR-pfm-oper', False, is_config=False),
            _MetaInfoClassMember('severity-emergency-or-alert-count', ATTRIBUTE, 'int', 'int32',
                None, None,
                [('-2147483648', '2147483647')], [],
                '''                Fault Severity Emergency count
                ''',
                'severity_emergency_or_alert_count',
                'Cisco-IOS-XR-pfm-oper', False, is_config=False),
            _MetaInfoClassMember('total', ATTRIBUTE, 'int', 'int32',
                None, None,
                [('-2147483648', '2147483647')], [],
                '''                Faulty Hardware total count
                ''',
                'total',
                'Cisco-IOS-XR-pfm-oper', False, is_config=False),
            _MetaInfoClassMember('severity-error-count', ATTRIBUTE, 'int', 'int32',
                None, None,
                [('-2147483648', '2147483647')], [],
                '''                Fault Severity Error count
                ''',
                'severity_error_count',
                'Cisco-IOS-XR-pfm-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-pfm-oper',
            'fault-summary',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-pfm-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_pfm_oper',
            is_config=False,
        ),
    },
    'PlatformFaultManager.Racks.Rack.Slots.Slot.HardwareFaultDevices.HardwareFaultDevice.HardwareFaultType' : {
        'meta_info' : _MetaInfoClass('PlatformFaultManager.Racks.Rack.Slots.Slot.HardwareFaultDevices.HardwareFaultDevice.HardwareFaultType', REFERENCE_LIST,
            '''Table of Hardware Failure Type''',
            False, 
            [
            _MetaInfoClassMember('hw-fault-type', ATTRIBUTE, 'str', 'xr:Cisco-ios-xr-string',
                None, None,
                [], [b'[\\w\\-\\.:,_@#%$\\+=\\|;]+'],
                '''                hw fault type list
                ''',
                'hw_fault_type',
                'Cisco-IOS-XR-pfm-oper', True, is_config=False),
            _MetaInfoClassMember('condition-description', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Faulty Hardware Condition Description
                ''',
                'condition_description',
                'Cisco-IOS-XR-pfm-oper', False, is_config=False),
            _MetaInfoClassMember('condition-name', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Faulty Hardware Condition Name
                ''',
                'condition_name',
                'Cisco-IOS-XR-pfm-oper', False, is_config=False),
            _MetaInfoClassMember('device-key', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Faulty Hardware Device Key
                ''',
                'device_key',
                'Cisco-IOS-XR-pfm-oper', False, is_config=False),
            _MetaInfoClassMember('device-version', ATTRIBUTE, 'int', 'int32',
                None, None,
                [('-2147483648', '2147483647')], [],
                '''                Faulty Hardware Device Version
                ''',
                'device_version',
                'Cisco-IOS-XR-pfm-oper', False, is_config=False),
            _MetaInfoClassMember('condition-raised-timestamp', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Fault Raised Timestamp
                ''',
                'condition_raised_timestamp',
                'Cisco-IOS-XR-pfm-oper', False, is_config=False),
            _MetaInfoClassMember('process-id', ATTRIBUTE, 'int', 'int32',
                None, None,
                [('-2147483648', '2147483647')], [],
                '''                Faulty Hardware Process ID
                ''',
                'process_id',
                'Cisco-IOS-XR-pfm-oper', False, is_config=False),
            _MetaInfoClassMember('device-description', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Faulty Hardware Device Description
                ''',
                'device_description',
                'Cisco-IOS-XR-pfm-oper', False, is_config=False),
            _MetaInfoClassMember('condition-severity', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Faulty Hardware Condition Severity
                ''',
                'condition_severity',
                'Cisco-IOS-XR-pfm-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-pfm-oper',
            'hardware-fault-type',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-pfm-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_pfm_oper',
            is_config=False,
        ),
    },
    'PlatformFaultManager.Racks.Rack.Slots.Slot.HardwareFaultDevices.HardwareFaultDevice' : {
        'meta_info' : _MetaInfoClass('PlatformFaultManager.Racks.Rack.Slots.Slot.HardwareFaultDevices.HardwareFaultDevice', REFERENCE_LIST,
            '''Table of Hardware Failure Device''',
            False, 
            [
            _MetaInfoClassMember('hw-fault-device', ATTRIBUTE, 'str', 'xr:Cisco-ios-xr-string',
                None, None,
                [], [b'[\\w\\-\\.:,_@#%$\\+=\\|;]+'],
                '''                hw fault device list
                ''',
                'hw_fault_device',
                'Cisco-IOS-XR-pfm-oper', True, is_config=False),
            _MetaInfoClassMember('hardware-fault-type', REFERENCE_LIST, 'HardwareFaultType', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_pfm_oper', 'PlatformFaultManager.Racks.Rack.Slots.Slot.HardwareFaultDevices.HardwareFaultDevice.HardwareFaultType',
                [], [],
                '''                Table of Hardware Failure Type
                ''',
                'hardware_fault_type',
                'Cisco-IOS-XR-pfm-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-pfm-oper',
            'hardware-fault-device',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-pfm-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_pfm_oper',
            is_config=False,
        ),
    },
    'PlatformFaultManager.Racks.Rack.Slots.Slot.HardwareFaultDevices' : {
        'meta_info' : _MetaInfoClass('PlatformFaultManager.Racks.Rack.Slots.Slot.HardwareFaultDevices', REFERENCE_CLASS,
            '''Table of Hardware Failure''',
            False, 
            [
            _MetaInfoClassMember('hardware-fault-device', REFERENCE_LIST, 'HardwareFaultDevice', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_pfm_oper', 'PlatformFaultManager.Racks.Rack.Slots.Slot.HardwareFaultDevices.HardwareFaultDevice',
                [], [],
                '''                Table of Hardware Failure Device
                ''',
                'hardware_fault_device',
                'Cisco-IOS-XR-pfm-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-pfm-oper',
            'hardware-fault-devices',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-pfm-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_pfm_oper',
            is_config=False,
        ),
    },
    'PlatformFaultManager.Racks.Rack.Slots.Slot' : {
        'meta_info' : _MetaInfoClass('PlatformFaultManager.Racks.Rack.Slots.Slot', REFERENCE_LIST,
            '''Name''',
            False, 
            [
            _MetaInfoClassMember('slot', ATTRIBUTE, 'str', 'xr:Cisco-ios-xr-string',
                None, None,
                [], [b'[\\w\\-\\.:,_@#%$\\+=\\|;]+'],
                '''                Slot name
                ''',
                'slot',
                'Cisco-IOS-XR-pfm-oper', True, is_config=False),
            _MetaInfoClassMember('fault-summary', REFERENCE_CLASS, 'FaultSummary', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_pfm_oper', 'PlatformFaultManager.Racks.Rack.Slots.Slot.FaultSummary',
                [], [],
                '''                Table of Hardware Summary
                ''',
                'fault_summary',
                'Cisco-IOS-XR-pfm-oper', False, is_config=False),
            _MetaInfoClassMember('hardware-fault-devices', REFERENCE_CLASS, 'HardwareFaultDevices', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_pfm_oper', 'PlatformFaultManager.Racks.Rack.Slots.Slot.HardwareFaultDevices',
                [], [],
                '''                Table of Hardware Failure
                ''',
                'hardware_fault_devices',
                'Cisco-IOS-XR-pfm-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-pfm-oper',
            'slot',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-pfm-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_pfm_oper',
            is_config=False,
        ),
    },
    'PlatformFaultManager.Racks.Rack.Slots' : {
        'meta_info' : _MetaInfoClass('PlatformFaultManager.Racks.Rack.Slots', REFERENCE_CLASS,
            '''Table of slots''',
            False, 
            [
            _MetaInfoClassMember('slot', REFERENCE_LIST, 'Slot', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_pfm_oper', 'PlatformFaultManager.Racks.Rack.Slots.Slot',
                [], [],
                '''                Name
                ''',
                'slot',
                'Cisco-IOS-XR-pfm-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-pfm-oper',
            'slots',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-pfm-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_pfm_oper',
            is_config=False,
        ),
    },
    'PlatformFaultManager.Racks.Rack' : {
        'meta_info' : _MetaInfoClass('PlatformFaultManager.Racks.Rack', REFERENCE_LIST,
            '''Number''',
            False, 
            [
            _MetaInfoClassMember('rack', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                Rack number
                ''',
                'rack',
                'Cisco-IOS-XR-pfm-oper', True, is_config=False),
            _MetaInfoClassMember('slots', REFERENCE_CLASS, 'Slots', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_pfm_oper', 'PlatformFaultManager.Racks.Rack.Slots',
                [], [],
                '''                Table of slots
                ''',
                'slots',
                'Cisco-IOS-XR-pfm-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-pfm-oper',
            'rack',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-pfm-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_pfm_oper',
            is_config=False,
        ),
    },
    'PlatformFaultManager.Racks' : {
        'meta_info' : _MetaInfoClass('PlatformFaultManager.Racks', REFERENCE_CLASS,
            '''Table of racks''',
            False, 
            [
            _MetaInfoClassMember('rack', REFERENCE_LIST, 'Rack', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_pfm_oper', 'PlatformFaultManager.Racks.Rack',
                [], [],
                '''                Number
                ''',
                'rack',
                'Cisco-IOS-XR-pfm-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-pfm-oper',
            'racks',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-pfm-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_pfm_oper',
            is_config=False,
        ),
    },
    'PlatformFaultManager' : {
        'meta_info' : _MetaInfoClass('PlatformFaultManager', REFERENCE_CLASS,
            '''PFM data space''',
            False, 
            [
            _MetaInfoClassMember('exclude', REFERENCE_CLASS, 'Exclude', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_pfm_oper', 'PlatformFaultManager.Exclude',
                [], [],
                '''                Exclude specic hw fault 
                ''',
                'exclude',
                'Cisco-IOS-XR-pfm-oper', False, is_config=False),
            _MetaInfoClassMember('racks', REFERENCE_CLASS, 'Racks', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_pfm_oper', 'PlatformFaultManager.Racks',
                [], [],
                '''                Table of racks
                ''',
                'racks',
                'Cisco-IOS-XR-pfm-oper', False, is_config=False),
            ],
            'Cisco-IOS-XR-pfm-oper',
            'platform-fault-manager',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-pfm-oper'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_pfm_oper',
            is_config=False,
        ),
    },
}
_meta_table['PlatformFaultManager.Exclude.FaultType1s.FaultType1.FaultType2s.FaultType2.FaultType3s.FaultType3.Racks.Rack.Slots.Slot.HardwareFaultDevices.HardwareFaultDevice.HardwareFaultType']['meta_info'].parent =_meta_table['PlatformFaultManager.Exclude.FaultType1s.FaultType1.FaultType2s.FaultType2.FaultType3s.FaultType3.Racks.Rack.Slots.Slot.HardwareFaultDevices.HardwareFaultDevice']['meta_info']
_meta_table['PlatformFaultManager.Exclude.FaultType1s.FaultType1.FaultType2s.FaultType2.FaultType3s.FaultType3.Racks.Rack.Slots.Slot.HardwareFaultDevices.HardwareFaultDevice']['meta_info'].parent =_meta_table['PlatformFaultManager.Exclude.FaultType1s.FaultType1.FaultType2s.FaultType2.FaultType3s.FaultType3.Racks.Rack.Slots.Slot.HardwareFaultDevices']['meta_info']
_meta_table['PlatformFaultManager.Exclude.FaultType1s.FaultType1.FaultType2s.FaultType2.FaultType3s.FaultType3.Racks.Rack.Slots.Slot.FaultSummary']['meta_info'].parent =_meta_table['PlatformFaultManager.Exclude.FaultType1s.FaultType1.FaultType2s.FaultType2.FaultType3s.FaultType3.Racks.Rack.Slots.Slot']['meta_info']
_meta_table['PlatformFaultManager.Exclude.FaultType1s.FaultType1.FaultType2s.FaultType2.FaultType3s.FaultType3.Racks.Rack.Slots.Slot.HardwareFaultDevices']['meta_info'].parent =_meta_table['PlatformFaultManager.Exclude.FaultType1s.FaultType1.FaultType2s.FaultType2.FaultType3s.FaultType3.Racks.Rack.Slots.Slot']['meta_info']
_meta_table['PlatformFaultManager.Exclude.FaultType1s.FaultType1.FaultType2s.FaultType2.FaultType3s.FaultType3.Racks.Rack.Slots.Slot']['meta_info'].parent =_meta_table['PlatformFaultManager.Exclude.FaultType1s.FaultType1.FaultType2s.FaultType2.FaultType3s.FaultType3.Racks.Rack.Slots']['meta_info']
_meta_table['PlatformFaultManager.Exclude.FaultType1s.FaultType1.FaultType2s.FaultType2.FaultType3s.FaultType3.Racks.Rack.Slots']['meta_info'].parent =_meta_table['PlatformFaultManager.Exclude.FaultType1s.FaultType1.FaultType2s.FaultType2.FaultType3s.FaultType3.Racks.Rack']['meta_info']
_meta_table['PlatformFaultManager.Exclude.FaultType1s.FaultType1.FaultType2s.FaultType2.FaultType3s.FaultType3.Racks.Rack']['meta_info'].parent =_meta_table['PlatformFaultManager.Exclude.FaultType1s.FaultType1.FaultType2s.FaultType2.FaultType3s.FaultType3.Racks']['meta_info']
_meta_table['PlatformFaultManager.Exclude.FaultType1s.FaultType1.FaultType2s.FaultType2.FaultType3s.FaultType3.Racks']['meta_info'].parent =_meta_table['PlatformFaultManager.Exclude.FaultType1s.FaultType1.FaultType2s.FaultType2.FaultType3s.FaultType3']['meta_info']
_meta_table['PlatformFaultManager.Exclude.FaultType1s.FaultType1.FaultType2s.FaultType2.FaultType3s.FaultType3']['meta_info'].parent =_meta_table['PlatformFaultManager.Exclude.FaultType1s.FaultType1.FaultType2s.FaultType2.FaultType3s']['meta_info']
_meta_table['PlatformFaultManager.Exclude.FaultType1s.FaultType1.FaultType2s.FaultType2.Racks.Rack.Slots.Slot.HardwareFaultDevices.HardwareFaultDevice.HardwareFaultType']['meta_info'].parent =_meta_table['PlatformFaultManager.Exclude.FaultType1s.FaultType1.FaultType2s.FaultType2.Racks.Rack.Slots.Slot.HardwareFaultDevices.HardwareFaultDevice']['meta_info']
_meta_table['PlatformFaultManager.Exclude.FaultType1s.FaultType1.FaultType2s.FaultType2.Racks.Rack.Slots.Slot.HardwareFaultDevices.HardwareFaultDevice']['meta_info'].parent =_meta_table['PlatformFaultManager.Exclude.FaultType1s.FaultType1.FaultType2s.FaultType2.Racks.Rack.Slots.Slot.HardwareFaultDevices']['meta_info']
_meta_table['PlatformFaultManager.Exclude.FaultType1s.FaultType1.FaultType2s.FaultType2.Racks.Rack.Slots.Slot.FaultSummary']['meta_info'].parent =_meta_table['PlatformFaultManager.Exclude.FaultType1s.FaultType1.FaultType2s.FaultType2.Racks.Rack.Slots.Slot']['meta_info']
_meta_table['PlatformFaultManager.Exclude.FaultType1s.FaultType1.FaultType2s.FaultType2.Racks.Rack.Slots.Slot.HardwareFaultDevices']['meta_info'].parent =_meta_table['PlatformFaultManager.Exclude.FaultType1s.FaultType1.FaultType2s.FaultType2.Racks.Rack.Slots.Slot']['meta_info']
_meta_table['PlatformFaultManager.Exclude.FaultType1s.FaultType1.FaultType2s.FaultType2.Racks.Rack.Slots.Slot']['meta_info'].parent =_meta_table['PlatformFaultManager.Exclude.FaultType1s.FaultType1.FaultType2s.FaultType2.Racks.Rack.Slots']['meta_info']
_meta_table['PlatformFaultManager.Exclude.FaultType1s.FaultType1.FaultType2s.FaultType2.Racks.Rack.Slots']['meta_info'].parent =_meta_table['PlatformFaultManager.Exclude.FaultType1s.FaultType1.FaultType2s.FaultType2.Racks.Rack']['meta_info']
_meta_table['PlatformFaultManager.Exclude.FaultType1s.FaultType1.FaultType2s.FaultType2.Racks.Rack']['meta_info'].parent =_meta_table['PlatformFaultManager.Exclude.FaultType1s.FaultType1.FaultType2s.FaultType2.Racks']['meta_info']
_meta_table['PlatformFaultManager.Exclude.FaultType1s.FaultType1.FaultType2s.FaultType2.FaultType3s']['meta_info'].parent =_meta_table['PlatformFaultManager.Exclude.FaultType1s.FaultType1.FaultType2s.FaultType2']['meta_info']
_meta_table['PlatformFaultManager.Exclude.FaultType1s.FaultType1.FaultType2s.FaultType2.Racks']['meta_info'].parent =_meta_table['PlatformFaultManager.Exclude.FaultType1s.FaultType1.FaultType2s.FaultType2']['meta_info']
_meta_table['PlatformFaultManager.Exclude.FaultType1s.FaultType1.FaultType2s.FaultType2']['meta_info'].parent =_meta_table['PlatformFaultManager.Exclude.FaultType1s.FaultType1.FaultType2s']['meta_info']
_meta_table['PlatformFaultManager.Exclude.FaultType1s.FaultType1.Racks.Rack.Slots.Slot.HardwareFaultDevices.HardwareFaultDevice.HardwareFaultType']['meta_info'].parent =_meta_table['PlatformFaultManager.Exclude.FaultType1s.FaultType1.Racks.Rack.Slots.Slot.HardwareFaultDevices.HardwareFaultDevice']['meta_info']
_meta_table['PlatformFaultManager.Exclude.FaultType1s.FaultType1.Racks.Rack.Slots.Slot.HardwareFaultDevices.HardwareFaultDevice']['meta_info'].parent =_meta_table['PlatformFaultManager.Exclude.FaultType1s.FaultType1.Racks.Rack.Slots.Slot.HardwareFaultDevices']['meta_info']
_meta_table['PlatformFaultManager.Exclude.FaultType1s.FaultType1.Racks.Rack.Slots.Slot.FaultSummary']['meta_info'].parent =_meta_table['PlatformFaultManager.Exclude.FaultType1s.FaultType1.Racks.Rack.Slots.Slot']['meta_info']
_meta_table['PlatformFaultManager.Exclude.FaultType1s.FaultType1.Racks.Rack.Slots.Slot.HardwareFaultDevices']['meta_info'].parent =_meta_table['PlatformFaultManager.Exclude.FaultType1s.FaultType1.Racks.Rack.Slots.Slot']['meta_info']
_meta_table['PlatformFaultManager.Exclude.FaultType1s.FaultType1.Racks.Rack.Slots.Slot']['meta_info'].parent =_meta_table['PlatformFaultManager.Exclude.FaultType1s.FaultType1.Racks.Rack.Slots']['meta_info']
_meta_table['PlatformFaultManager.Exclude.FaultType1s.FaultType1.Racks.Rack.Slots']['meta_info'].parent =_meta_table['PlatformFaultManager.Exclude.FaultType1s.FaultType1.Racks.Rack']['meta_info']
_meta_table['PlatformFaultManager.Exclude.FaultType1s.FaultType1.Racks.Rack']['meta_info'].parent =_meta_table['PlatformFaultManager.Exclude.FaultType1s.FaultType1.Racks']['meta_info']
_meta_table['PlatformFaultManager.Exclude.FaultType1s.FaultType1.FaultType2s']['meta_info'].parent =_meta_table['PlatformFaultManager.Exclude.FaultType1s.FaultType1']['meta_info']
_meta_table['PlatformFaultManager.Exclude.FaultType1s.FaultType1.Racks']['meta_info'].parent =_meta_table['PlatformFaultManager.Exclude.FaultType1s.FaultType1']['meta_info']
_meta_table['PlatformFaultManager.Exclude.FaultType1s.FaultType1']['meta_info'].parent =_meta_table['PlatformFaultManager.Exclude.FaultType1s']['meta_info']
_meta_table['PlatformFaultManager.Exclude.FaultType1s']['meta_info'].parent =_meta_table['PlatformFaultManager.Exclude']['meta_info']
_meta_table['PlatformFaultManager.Racks.Rack.Slots.Slot.HardwareFaultDevices.HardwareFaultDevice.HardwareFaultType']['meta_info'].parent =_meta_table['PlatformFaultManager.Racks.Rack.Slots.Slot.HardwareFaultDevices.HardwareFaultDevice']['meta_info']
_meta_table['PlatformFaultManager.Racks.Rack.Slots.Slot.HardwareFaultDevices.HardwareFaultDevice']['meta_info'].parent =_meta_table['PlatformFaultManager.Racks.Rack.Slots.Slot.HardwareFaultDevices']['meta_info']
_meta_table['PlatformFaultManager.Racks.Rack.Slots.Slot.FaultSummary']['meta_info'].parent =_meta_table['PlatformFaultManager.Racks.Rack.Slots.Slot']['meta_info']
_meta_table['PlatformFaultManager.Racks.Rack.Slots.Slot.HardwareFaultDevices']['meta_info'].parent =_meta_table['PlatformFaultManager.Racks.Rack.Slots.Slot']['meta_info']
_meta_table['PlatformFaultManager.Racks.Rack.Slots.Slot']['meta_info'].parent =_meta_table['PlatformFaultManager.Racks.Rack.Slots']['meta_info']
_meta_table['PlatformFaultManager.Racks.Rack.Slots']['meta_info'].parent =_meta_table['PlatformFaultManager.Racks.Rack']['meta_info']
_meta_table['PlatformFaultManager.Racks.Rack']['meta_info'].parent =_meta_table['PlatformFaultManager.Racks']['meta_info']
_meta_table['PlatformFaultManager.Exclude']['meta_info'].parent =_meta_table['PlatformFaultManager']['meta_info']
_meta_table['PlatformFaultManager.Racks']['meta_info'].parent =_meta_table['PlatformFaultManager']['meta_info']
