
'''
This is auto-generated file,
which includes metadata for module Cisco_IOS_XR_sysadmin_ds
'''

from ydk._core._dm_meta_info import _MetaInfoClassMember, _MetaInfoClass, _MetaInfoEnum
from ydk._core._dm_meta_info import ATTRIBUTE, REFERENCE_LIST, REFERENCE_LEAFLIST, REFERENCE_BITS, REFERENCE_UNION
from ydk._core._dm_meta_info import REFERENCE_CLASS, REFERENCE_IDENTITY_CLASS, REFERENCE_ENUM_CLASS, ANYXML_CLASS
from ydk._core._importer import _yang_ns

_meta_table = {
    'ServiceScope' : _MetaInfoEnum('ServiceScope',
        'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_ds', 'ServiceScope',
        ''' ''',
        {
            'None':'None_',
            'Rack':'Rack',
            'System':'System',
            'Node':'Node',
        }, 'Cisco-IOS-XR-sysadmin-ds', _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-sysadmin-ds']),
    'ProcessRole' : _MetaInfoEnum('ProcessRole',
        'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_ds', 'ProcessRole',
        ''' ''',
        {
            'NoRole':'NoRole',
            'Active':'Active',
            'Standby':'Standby',
            'None':'None_',
            'Unknown':'Unknown',
        }, 'Cisco-IOS-XR-sysadmin-ds', _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-sysadmin-ds']),
    'ProcessIssuRole' : _MetaInfoEnum('ProcessIssuRole',
        'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_ds', 'ProcessIssuRole',
        ''' ''',
        {
            'Primary':'Primary',
            'Secondary':'Secondary',
            'Tertiary':'Tertiary',
            'Unknown':'Unknown',
        }, 'Cisco-IOS-XR-sysadmin-ds', _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-sysadmin-ds']),
    'Services.AllLocations.Services_.Endpoint' : {
        'meta_info' : _MetaInfoClass('Services.AllLocations.Services_.Endpoint', REFERENCE_LIST,
            '''endpoint info for a service in DS''',
            False, 
            [
            _MetaInfoClassMember('scope', REFERENCE_ENUM_CLASS, 'ServiceScope', 'service-scope',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_ds', 'ServiceScope',
                [], [],
                '''                ''',
                'scope',
                'Cisco-IOS-XR-sysadmin-ds', False, is_config=False),
            _MetaInfoClassMember('ip', ATTRIBUTE, 'str', 'inet:ipv4-address',
                None, None,
                [], [b'(([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])(%[\\p{N}\\p{L}]+)?'],
                '''                ''',
                'ip',
                'Cisco-IOS-XR-sysadmin-ds', False, is_config=False),
            _MetaInfoClassMember('port', ATTRIBUTE, 'int', 'inet:port-number',
                None, None,
                [('0', '65535')], [],
                '''                ''',
                'port',
                'Cisco-IOS-XR-sysadmin-ds', False, is_config=False),
            _MetaInfoClassMember('role', REFERENCE_ENUM_CLASS, 'ProcessRole', 'process-role',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_ds', 'ProcessRole',
                [], [],
                '''                ''',
                'role',
                'Cisco-IOS-XR-sysadmin-ds', False, is_config=False),
            _MetaInfoClassMember('issu_role', REFERENCE_ENUM_CLASS, 'ProcessIssuRole', 'process-issu-role',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_ds', 'ProcessIssuRole',
                [], [],
                '''                ''',
                'issu_role',
                'Cisco-IOS-XR-sysadmin-ds', False, is_config=False),
            _MetaInfoClassMember('node', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Ethernet address of the node hosting the endpoint
                ''',
                'node',
                'Cisco-IOS-XR-sysadmin-ds', False, is_config=False),
            ],
            'Cisco-IOS-XR-sysadmin-ds',
            'endpoint',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-sysadmin-ds'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_ds',
            is_config=False,
        ),
    },
    'Services.AllLocations.Services_.Registrations' : {
        'meta_info' : _MetaInfoClass('Services.AllLocations.Services_.Registrations', REFERENCE_LIST,
            '''clients registered for a service in DS''',
            False, 
            [
            _MetaInfoClassMember('client', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                ''',
                'client',
                'Cisco-IOS-XR-sysadmin-ds', False, is_config=False),
            _MetaInfoClassMember('pid', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                ''',
                'pid',
                'Cisco-IOS-XR-sysadmin-ds', False, is_config=False),
            ],
            'Cisco-IOS-XR-sysadmin-ds',
            'registrations',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-sysadmin-ds'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_ds',
            is_config=False,
        ),
    },
    'Services.AllLocations.Services_' : {
        'meta_info' : _MetaInfoClass('Services.AllLocations.Services_', REFERENCE_LIST,
            ''' ''',
            False, 
            [
            _MetaInfoClassMember('name', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Name of the service
                ''',
                'name',
                'Cisco-IOS-XR-sysadmin-ds', True, is_config=False),
            _MetaInfoClassMember('endpoint', REFERENCE_LIST, 'Endpoint', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_ds', 'Services.AllLocations.Services_.Endpoint',
                [], [],
                '''                endpoint info for a service in DS
                ''',
                'endpoint',
                'Cisco-IOS-XR-sysadmin-ds', False, is_config=False),
            _MetaInfoClassMember('registrations', REFERENCE_LIST, 'Registrations', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_ds', 'Services.AllLocations.Services_.Registrations',
                [], [],
                '''                clients registered for a service in DS
                ''',
                'registrations',
                'Cisco-IOS-XR-sysadmin-ds', False, is_config=False),
            ],
            'Cisco-IOS-XR-sysadmin-ds',
            'services',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-sysadmin-ds'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_ds',
            is_config=False,
        ),
    },
    'Services.AllLocations' : {
        'meta_info' : _MetaInfoClass('Services.AllLocations', REFERENCE_LIST,
            ''' ''',
            False, 
            [
            _MetaInfoClassMember('location', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Node Location
                ''',
                'location',
                'Cisco-IOS-XR-sysadmin-ds', True, is_config=False),
            _MetaInfoClassMember('services', REFERENCE_LIST, 'Services_', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_ds', 'Services.AllLocations.Services_',
                [], [],
                '''                ''',
                'services',
                'Cisco-IOS-XR-sysadmin-ds', False, is_config=False),
            ],
            'Cisco-IOS-XR-sysadmin-ds',
            'all-locations',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-sysadmin-ds'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_ds',
            is_config=False,
        ),
    },
    'Services' : {
        'meta_info' : _MetaInfoClass('Services', REFERENCE_CLASS,
            '''Directory Services Entries''',
            False, 
            [
            _MetaInfoClassMember('all-locations', REFERENCE_LIST, 'AllLocations', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_ds', 'Services.AllLocations',
                [], [],
                '''                ''',
                'all_locations',
                'Cisco-IOS-XR-sysadmin-ds', False, is_config=False),
            ],
            'Cisco-IOS-XR-sysadmin-ds',
            'services',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-sysadmin-ds'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_ds',
            is_config=False,
        ),
    },
    'ServicesStats.Ds.Trace.Location.AllOptions.TraceBlocks' : {
        'meta_info' : _MetaInfoClass('ServicesStats.Ds.Trace.Location.AllOptions.TraceBlocks', REFERENCE_LIST,
            ''' ''',
            False, 
            [
            _MetaInfoClassMember('data', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Trace output block
                ''',
                'data',
                'Cisco-IOS-XR-sysadmin-ds', False, is_config=False),
            ],
            'Cisco-IOS-XR-sysadmin-ds',
            'trace-blocks',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-sysadmin-ds'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_ds',
            is_config=False,
        ),
    },
    'ServicesStats.Ds.Trace.Location.AllOptions' : {
        'meta_info' : _MetaInfoClass('ServicesStats.Ds.Trace.Location.AllOptions', REFERENCE_LIST,
            ''' ''',
            False, 
            [
            _MetaInfoClassMember('option', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                ''',
                'option',
                'Cisco-IOS-XR-sysadmin-ds', True, is_config=False),
            _MetaInfoClassMember('trace-blocks', REFERENCE_LIST, 'TraceBlocks', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_ds', 'ServicesStats.Ds.Trace.Location.AllOptions.TraceBlocks',
                [], [],
                '''                ''',
                'trace_blocks',
                'Cisco-IOS-XR-sysadmin-ds', False, is_config=False),
            ],
            'Cisco-IOS-XR-sysadmin-ds',
            'all-options',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-sysadmin-ds'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_ds',
            is_config=False,
        ),
    },
    'ServicesStats.Ds.Trace.Location' : {
        'meta_info' : _MetaInfoClass('ServicesStats.Ds.Trace.Location', REFERENCE_LIST,
            ''' ''',
            False, 
            [
            _MetaInfoClassMember('location_name', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                ''',
                'location_name',
                'Cisco-IOS-XR-sysadmin-ds', True, is_config=False),
            _MetaInfoClassMember('all-options', REFERENCE_LIST, 'AllOptions', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_ds', 'ServicesStats.Ds.Trace.Location.AllOptions',
                [], [],
                '''                ''',
                'all_options',
                'Cisco-IOS-XR-sysadmin-ds', False, is_config=False),
            ],
            'Cisco-IOS-XR-sysadmin-ds',
            'location',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-sysadmin-ds'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_ds',
            is_config=False,
        ),
    },
    'ServicesStats.Ds.Trace' : {
        'meta_info' : _MetaInfoClass('ServicesStats.Ds.Trace', REFERENCE_LIST,
            '''show traceable processes''',
            False, 
            [
            _MetaInfoClassMember('buffer', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                ''',
                'buffer',
                'Cisco-IOS-XR-sysadmin-ds', True, is_config=False),
            _MetaInfoClassMember('location', REFERENCE_LIST, 'Location', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_ds', 'ServicesStats.Ds.Trace.Location',
                [], [],
                '''                ''',
                'location',
                'Cisco-IOS-XR-sysadmin-ds', False, is_config=False),
            ],
            'Cisco-IOS-XR-sysadmin-ds',
            'trace',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-sysadmin-ds'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_ds',
            is_config=False,
        ),
    },
    'ServicesStats.Ds' : {
        'meta_info' : _MetaInfoClass('ServicesStats.Ds', REFERENCE_CLASS,
            ''' ''',
            False, 
            [
            _MetaInfoClassMember('trace', REFERENCE_LIST, 'Trace', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_ds', 'ServicesStats.Ds.Trace',
                [], [],
                '''                show traceable processes
                ''',
                'trace',
                'Cisco-IOS-XR-sysadmin-ds', False, is_config=False),
            ],
            'Cisco-IOS-XR-sysadmin-ds',
            'ds',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-sysadmin-ds'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_ds',
            is_config=False,
        ),
    },
    'ServicesStats.AllLocations.Stats' : {
        'meta_info' : _MetaInfoClass('ServicesStats.AllLocations.Stats', REFERENCE_LIST,
            ''' ''',
            False, 
            [
            _MetaInfoClassMember('name', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Name of the service
                ''',
                'name',
                'Cisco-IOS-XR-sysadmin-ds', True, is_config=False),
            _MetaInfoClassMember('published', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                number of endpoints published for this service
                ''',
                'published',
                'Cisco-IOS-XR-sysadmin-ds', False, is_config=False),
            _MetaInfoClassMember('deleted', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                number of endpoints deleted for this service
                ''',
                'deleted',
                'Cisco-IOS-XR-sysadmin-ds', False, is_config=False),
            _MetaInfoClassMember('modified', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                number of endpoints modified for this service
                ''',
                'modified',
                'Cisco-IOS-XR-sysadmin-ds', False, is_config=False),
            _MetaInfoClassMember('registered', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                number of clients registered for this service
                ''',
                'registered',
                'Cisco-IOS-XR-sysadmin-ds', False, is_config=False),
            _MetaInfoClassMember('unregistered', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                number of clients un-registered for this service
                ''',
                'unregistered',
                'Cisco-IOS-XR-sysadmin-ds', False, is_config=False),
            _MetaInfoClassMember('notifications', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                number of clients notified for this service
                ''',
                'notifications',
                'Cisco-IOS-XR-sysadmin-ds', False, is_config=False),
            _MetaInfoClassMember('remote_sent', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                number of remote service updates sent to remote nodes
                ''',
                'remote_sent',
                'Cisco-IOS-XR-sysadmin-ds', False, is_config=False),
            _MetaInfoClassMember('remote_recv', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                number of remote service received from remote nodes
                ''',
                'remote_recv',
                'Cisco-IOS-XR-sysadmin-ds', False, is_config=False),
            ],
            'Cisco-IOS-XR-sysadmin-ds',
            'stats',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-sysadmin-ds'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_ds',
            is_config=False,
        ),
    },
    'ServicesStats.AllLocations' : {
        'meta_info' : _MetaInfoClass('ServicesStats.AllLocations', REFERENCE_LIST,
            ''' ''',
            False, 
            [
            _MetaInfoClassMember('location', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                ''',
                'location',
                'Cisco-IOS-XR-sysadmin-ds', True, is_config=False),
            _MetaInfoClassMember('stats', REFERENCE_LIST, 'Stats', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_ds', 'ServicesStats.AllLocations.Stats',
                [], [],
                '''                ''',
                'stats',
                'Cisco-IOS-XR-sysadmin-ds', False, is_config=False),
            ],
            'Cisco-IOS-XR-sysadmin-ds',
            'all-locations',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-sysadmin-ds'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_ds',
            is_config=False,
        ),
    },
    'ServicesStats' : {
        'meta_info' : _MetaInfoClass('ServicesStats', REFERENCE_CLASS,
            '''Directory Services Stats''',
            False, 
            [
            _MetaInfoClassMember('ds', REFERENCE_CLASS, 'Ds', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_ds', 'ServicesStats.Ds',
                [], [],
                '''                ''',
                'ds',
                'Cisco-IOS-XR-sysadmin-ds', False, is_config=False),
            _MetaInfoClassMember('all-locations', REFERENCE_LIST, 'AllLocations', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_ds', 'ServicesStats.AllLocations',
                [], [],
                '''                ''',
                'all_locations',
                'Cisco-IOS-XR-sysadmin-ds', False, is_config=False),
            ],
            'Cisco-IOS-XR-sysadmin-ds',
            'services-stats',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-sysadmin-ds'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_sysadmin_ds',
            is_config=False,
        ),
    },
}
_meta_table['Services.AllLocations.Services_.Endpoint']['meta_info'].parent =_meta_table['Services.AllLocations.Services_']['meta_info']
_meta_table['Services.AllLocations.Services_.Registrations']['meta_info'].parent =_meta_table['Services.AllLocations.Services_']['meta_info']
_meta_table['Services.AllLocations.Services_']['meta_info'].parent =_meta_table['Services.AllLocations']['meta_info']
_meta_table['Services.AllLocations']['meta_info'].parent =_meta_table['Services']['meta_info']
_meta_table['ServicesStats.Ds.Trace.Location.AllOptions.TraceBlocks']['meta_info'].parent =_meta_table['ServicesStats.Ds.Trace.Location.AllOptions']['meta_info']
_meta_table['ServicesStats.Ds.Trace.Location.AllOptions']['meta_info'].parent =_meta_table['ServicesStats.Ds.Trace.Location']['meta_info']
_meta_table['ServicesStats.Ds.Trace.Location']['meta_info'].parent =_meta_table['ServicesStats.Ds.Trace']['meta_info']
_meta_table['ServicesStats.Ds.Trace']['meta_info'].parent =_meta_table['ServicesStats.Ds']['meta_info']
_meta_table['ServicesStats.AllLocations.Stats']['meta_info'].parent =_meta_table['ServicesStats.AllLocations']['meta_info']
_meta_table['ServicesStats.Ds']['meta_info'].parent =_meta_table['ServicesStats']['meta_info']
_meta_table['ServicesStats.AllLocations']['meta_info'].parent =_meta_table['ServicesStats']['meta_info']
