
'''
This is auto-generated file,
which includes metadata for module Cisco_IOS_XR_man_ems_cfg
'''

from ydk._core._dm_meta_info import _MetaInfoClassMember, _MetaInfoClass, _MetaInfoEnum
from ydk._core._dm_meta_info import ATTRIBUTE, REFERENCE_LIST, REFERENCE_LEAFLIST, REFERENCE_BITS, REFERENCE_UNION
from ydk._core._dm_meta_info import REFERENCE_CLASS, REFERENCE_IDENTITY_CLASS, REFERENCE_ENUM_CLASS, ANYXML_CLASS
from ydk._core._importer import _yang_ns

_meta_table = {
    'Dscp' : _MetaInfoEnum('Dscp',
        'ydk.models.cisco_ios_xr.Cisco_IOS_XR_man_ems_cfg', 'Dscp',
        ''' ''',
        {
            'default':'default',
            'af11':'af11',
            'af12':'af12',
            'af13':'af13',
            'af21':'af21',
            'af22':'af22',
            'af23':'af23',
            'af31':'af31',
            'af32':'af32',
            'af33':'af33',
            'af41':'af41',
            'af42':'af42',
            'af43':'af43',
            'cs1':'cs1',
            'cs2':'cs2',
            'cs3':'cs3',
            'cs4':'cs4',
            'cs5':'cs5',
            'cs6':'cs6',
            'cs7':'cs7',
            'ef':'ef',
        }, 'Cisco-IOS-XR-man-ems-cfg', _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-man-ems-cfg']),
    'GrpCTlsCipherDefault' : _MetaInfoEnum('GrpCTlsCipherDefault',
        'ydk.models.cisco_ios_xr.Cisco_IOS_XR_man_ems_cfg', 'GrpCTlsCipherDefault',
        '''Grp c tls cipher default''',
        {
            'disable':'disable',
            'enable':'enable',
        }, 'Cisco-IOS-XR-man-ems-cfg', _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-man-ems-cfg']),
    'Grpc.ServiceLayer' : {
        'meta_info' : _MetaInfoClass('Grpc.ServiceLayer', REFERENCE_CLASS,
            '''Service Layer''',
            False, 
            [
            _MetaInfoClassMember('enable', ATTRIBUTE, 'Empty', 'empty',
                None, None,
                [], [],
                '''                Enable ServiceLayer
                ''',
                'enable',
                'Cisco-IOS-XR-man-ems-cfg', False),
            ],
            'Cisco-IOS-XR-man-ems-cfg',
            'service-layer',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-man-ems-cfg'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_man_ems_cfg',
        ),
    },
    'Grpc.TlsCipher' : {
        'meta_info' : _MetaInfoClass('Grpc.TlsCipher', REFERENCE_CLASS,
            '''TLS ciphers''',
            False, 
            [
            _MetaInfoClassMember('default', REFERENCE_ENUM_CLASS, 'GrpCTlsCipherDefault', 'Grp-c-tls-cipher-default',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_man_ems_cfg', 'GrpCTlsCipherDefault',
                [], [],
                '''                Default of all ciphers.
                ''',
                'default',
                'Cisco-IOS-XR-man-ems-cfg', False),
            _MetaInfoClassMember('enable', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Enable ciphers if default is disabled.
                ''',
                'enable',
                'Cisco-IOS-XR-man-ems-cfg', False),
            _MetaInfoClassMember('disable', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Disable ciphers if default is enabled.
                ''',
                'disable',
                'Cisco-IOS-XR-man-ems-cfg', False),
            ],
            'Cisco-IOS-XR-man-ems-cfg',
            'tls-cipher',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-man-ems-cfg'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_man_ems_cfg',
        ),
    },
    'Grpc.Tls' : {
        'meta_info' : _MetaInfoClass('Grpc.Tls', REFERENCE_CLASS,
            '''Transport Layer Security (TLS)''',
            False, 
            [
            _MetaInfoClassMember('enable', ATTRIBUTE, 'Empty', 'empty',
                None, None,
                [], [],
                '''                Enable TLS
                ''',
                'enable',
                'Cisco-IOS-XR-man-ems-cfg', False),
            ],
            'Cisco-IOS-XR-man-ems-cfg',
            'tls',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-man-ems-cfg'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_man_ems_cfg',
        ),
    },
    'Grpc' : {
        'meta_info' : _MetaInfoClass('Grpc', REFERENCE_CLASS,
            '''GRPC configruation''',
            False, 
            [
            _MetaInfoClassMember('service-layer', REFERENCE_CLASS, 'ServiceLayer', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_man_ems_cfg', 'Grpc.ServiceLayer',
                [], [],
                '''                Service Layer
                ''',
                'service_layer',
                'Cisco-IOS-XR-man-ems-cfg', False),
            _MetaInfoClassMember('tls-cipher', REFERENCE_CLASS, 'TlsCipher', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_man_ems_cfg', 'Grpc.TlsCipher',
                [], [],
                '''                TLS ciphers
                ''',
                'tls_cipher',
                'Cisco-IOS-XR-man-ems-cfg', False),
            _MetaInfoClassMember('tls', REFERENCE_CLASS, 'Tls', '',
                'ydk.models.cisco_ios_xr.Cisco_IOS_XR_man_ems_cfg', 'Grpc.Tls',
                [], [],
                '''                Transport Layer Security (TLS)
                ''',
                'tls',
                'Cisco-IOS-XR-man-ems-cfg', False),
            _MetaInfoClassMember('port', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('10000', '57999')], [],
                '''                Server listening port
                ''',
                'port',
                'Cisco-IOS-XR-man-ems-cfg', False),
            _MetaInfoClassMember('vrf', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Server vrf name
                ''',
                'vrf',
                'Cisco-IOS-XR-man-ems-cfg', False),
            _MetaInfoClassMember('max-streams', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('1', '128')], [],
                '''                Maximum number of streaming gRPCs
                ''',
                'max_streams',
                'Cisco-IOS-XR-man-ems-cfg', False, default_value="32"),
            _MetaInfoClassMember('enable', ATTRIBUTE, 'Empty', 'empty',
                None, None,
                [], [],
                '''                Enable GRPC
                ''',
                'enable',
                'Cisco-IOS-XR-man-ems-cfg', False),
            _MetaInfoClassMember('max-streams-per-user', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('1', '128')], [],
                '''                Maximum number of streaming gRPCs per user
                ''',
                'max_streams_per_user',
                'Cisco-IOS-XR-man-ems-cfg', False, default_value="32"),
            _MetaInfoClassMember('max-request-per-user', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('1', '32')], [],
                '''                Maximum concurrent requests per user
                ''',
                'max_request_per_user',
                'Cisco-IOS-XR-man-ems-cfg', False),
            _MetaInfoClassMember('no-tls', ATTRIBUTE, 'Empty', 'empty',
                None, None,
                [], [],
                '''                No TLS
                ''',
                'no_tls',
                'Cisco-IOS-XR-man-ems-cfg', False),
            _MetaInfoClassMember('tls-trustpoint', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Trustpoint Name
                ''',
                'tls_trustpoint',
                'Cisco-IOS-XR-man-ems-cfg', False),
            _MetaInfoClassMember('dscp', REFERENCE_UNION, 'str', 'Dscp',
                None, None,
                [], [],
                '''                QoS marking DSCP to be set on transmitted gRPC
                ''',
                'dscp',
                'Cisco-IOS-XR-man-ems-cfg', False, [
                    _MetaInfoClassMember('dscp', REFERENCE_ENUM_CLASS, 'Dscp', 'enumeration',
                        'ydk.models.cisco_ios_xr.Cisco_IOS_XR_man_ems_cfg', 'Dscp',
                        [], [],
                        '''                        QoS marking DSCP to be set on transmitted gRPC
                        ''',
                        'dscp',
                        'Cisco-IOS-XR-man-ems-cfg', False),
                    _MetaInfoClassMember('dscp', ATTRIBUTE, 'int', 'uint32',
                        None, None,
                        [('0', '63')], [],
                        '''                        QoS marking DSCP to be set on transmitted gRPC
                        ''',
                        'dscp',
                        'Cisco-IOS-XR-man-ems-cfg', False),
                ]),
            _MetaInfoClassMember('address-family', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                Address family identifier type
                ''',
                'address_family',
                'Cisco-IOS-XR-man-ems-cfg', False),
            _MetaInfoClassMember('tls-mutual', ATTRIBUTE, 'Empty', 'empty',
                None, None,
                [], [],
                '''                TLS mutual authentication
                ''',
                'tls_mutual',
                'Cisco-IOS-XR-man-ems-cfg', False),
            _MetaInfoClassMember('max-request-total', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('1', '256')], [],
                '''                Maximum concurrent requests in total
                ''',
                'max_request_total',
                'Cisco-IOS-XR-man-ems-cfg', False),
            ],
            'Cisco-IOS-XR-man-ems-cfg',
            'grpc',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-man-ems-cfg'],
            'ydk.models.cisco_ios_xr.Cisco_IOS_XR_man_ems_cfg',
        ),
    },
}
_meta_table['Grpc.ServiceLayer']['meta_info'].parent =_meta_table['Grpc']['meta_info']
_meta_table['Grpc.TlsCipher']['meta_info'].parent =_meta_table['Grpc']['meta_info']
_meta_table['Grpc.Tls']['meta_info'].parent =_meta_table['Grpc']['meta_info']
