
'''
This is auto-generated file,
which includes metadata for module SNMPv2_MIB
'''

from ydk._core._dm_meta_info import _MetaInfoClassMember, _MetaInfoClass, _MetaInfoEnum
from ydk._core._dm_meta_info import ATTRIBUTE, REFERENCE_LIST, REFERENCE_LEAFLIST, REFERENCE_BITS, REFERENCE_UNION
from ydk._core._dm_meta_info import REFERENCE_CLASS, REFERENCE_IDENTITY_CLASS, REFERENCE_ENUM_CLASS, ANYXML_CLASS
from ydk._core._importer import _yang_ns

_meta_table = {
    'SnmpEnableAuthenTrapsType' : _MetaInfoEnum('SnmpEnableAuthenTrapsType',
        'ydk.models.cisco_ios_xr.SNMPv2_MIB', 'SnmpEnableAuthenTrapsType',
        ''' ''',
        {
            'enabled':'enabled',
            'disabled':'disabled',
        }, 'SNMPv2-MIB', _yang_ns.NAMESPACE_LOOKUP['SNMPv2-MIB']),
    'SNMPv2MIB.System' : {
        'meta_info' : _MetaInfoClass('SNMPv2MIB.System', REFERENCE_CLASS,
            ''' ''',
            False, 
            [
            _MetaInfoClassMember('sysDescr', ATTRIBUTE, 'str', 'sysDescrType',
                None, None,
                [('0', 255)], [],
                '''                ''',
                'sysdescr',
                'SNMPv2-MIB', False, is_config=False),
            _MetaInfoClassMember('sysObjectID', ATTRIBUTE, 'str', 'yang:object-identifier',
                None, None,
                [], [b'(([0-1](\\.[1-3]?[0-9]))|(2\\.(0|([1-9]\\d*))))(\\.(0|([1-9]\\d*)))*'],
                '''                ''',
                'sysobjectid',
                'SNMPv2-MIB', False, is_config=False),
            _MetaInfoClassMember('sysUpTime', ATTRIBUTE, 'int', 'yang:timeticks',
                None, None,
                [('0', '4294967295')], [],
                '''                ''',
                'sysuptime',
                'SNMPv2-MIB', False, is_config=False),
            _MetaInfoClassMember('sysContact', ATTRIBUTE, 'str', 'sysContactType',
                None, None,
                [('0', 255)], [],
                '''                ''',
                'syscontact',
                'SNMPv2-MIB', False, default_value="''"),
            _MetaInfoClassMember('sysName', ATTRIBUTE, 'str', 'sysNameType',
                None, None,
                [('0', 255)], [],
                '''                ''',
                'sysname',
                'SNMPv2-MIB', False, default_value="''"),
            _MetaInfoClassMember('sysLocation', ATTRIBUTE, 'str', 'sysLocationType',
                None, None,
                [('0', 255)], [],
                '''                ''',
                'syslocation',
                'SNMPv2-MIB', False, default_value="''"),
            _MetaInfoClassMember('sysServices', ATTRIBUTE, 'int', 'sysServicesType',
                None, None,
                [('0', '127')], [],
                '''                ''',
                'sysservices',
                'SNMPv2-MIB', False, is_config=False),
            _MetaInfoClassMember('sysORLastChange', ATTRIBUTE, 'int', 'yang:timestamp',
                None, None,
                [('0', '4294967295')], [],
                '''                ''',
                'sysorlastchange',
                'SNMPv2-MIB', False, is_config=False),
            ],
            'SNMPv2-MIB',
            'system',
            _yang_ns.NAMESPACE_LOOKUP['SNMPv2-MIB'],
            'ydk.models.cisco_ios_xr.SNMPv2_MIB',
        ),
    },
    'SNMPv2MIB.Snmp' : {
        'meta_info' : _MetaInfoClass('SNMPv2MIB.Snmp', REFERENCE_CLASS,
            ''' ''',
            False, 
            [
            _MetaInfoClassMember('snmpInPkts', ATTRIBUTE, 'int', 'yang:counter32',
                None, None,
                [('0', '4294967295')], [],
                '''                ''',
                'snmpinpkts',
                'SNMPv2-MIB', False, is_config=False),
            _MetaInfoClassMember('snmpInBadVersions', ATTRIBUTE, 'int', 'yang:counter32',
                None, None,
                [('0', '4294967295')], [],
                '''                ''',
                'snmpinbadversions',
                'SNMPv2-MIB', False, is_config=False),
            _MetaInfoClassMember('snmpInBadCommunityNames', ATTRIBUTE, 'int', 'yang:counter32',
                None, None,
                [('0', '4294967295')], [],
                '''                ''',
                'snmpinbadcommunitynames',
                'SNMPv2-MIB', False, is_config=False),
            _MetaInfoClassMember('snmpInBadCommunityUses', ATTRIBUTE, 'int', 'yang:counter32',
                None, None,
                [('0', '4294967295')], [],
                '''                ''',
                'snmpinbadcommunityuses',
                'SNMPv2-MIB', False, is_config=False),
            _MetaInfoClassMember('snmpInASNParseErrs', ATTRIBUTE, 'int', 'yang:counter32',
                None, None,
                [('0', '4294967295')], [],
                '''                ''',
                'snmpinasnparseerrs',
                'SNMPv2-MIB', False, is_config=False),
            _MetaInfoClassMember('snmpEnableAuthenTraps', REFERENCE_ENUM_CLASS, 'SnmpEnableAuthenTrapsType', 'snmpEnableAuthenTrapsType',
                'ydk.models.cisco_ios_xr.SNMPv2_MIB', 'SnmpEnableAuthenTrapsType',
                [], [],
                '''                ''',
                'snmpenableauthentraps',
                'SNMPv2-MIB', False, default_value='SNMPv2_MIB.SnmpEnableAuthenTrapsType.disabled'),
            _MetaInfoClassMember('snmpSilentDrops', ATTRIBUTE, 'int', 'yang:counter32',
                None, None,
                [('0', '4294967295')], [],
                '''                ''',
                'snmpsilentdrops',
                'SNMPv2-MIB', False, is_config=False),
            _MetaInfoClassMember('snmpProxyDrops', ATTRIBUTE, 'int', 'yang:counter32',
                None, None,
                [('0', '4294967295')], [],
                '''                ''',
                'snmpproxydrops',
                'SNMPv2-MIB', False, is_config=False),
            ],
            'SNMPv2-MIB',
            'snmp',
            _yang_ns.NAMESPACE_LOOKUP['SNMPv2-MIB'],
            'ydk.models.cisco_ios_xr.SNMPv2_MIB',
        ),
    },
    'SNMPv2MIB.SnmpSet' : {
        'meta_info' : _MetaInfoClass('SNMPv2MIB.SnmpSet', REFERENCE_CLASS,
            ''' ''',
            False, 
            [
            _MetaInfoClassMember('snmpSetSerialNo', ATTRIBUTE, 'int', 'SNMPv2_TC:TestAndIncr',
                None, None,
                [('0', '2147483647')], [],
                '''                ''',
                'snmpsetserialno',
                'SNMPv2-MIB', False, is_config=False),
            ],
            'SNMPv2-MIB',
            'snmpSet',
            _yang_ns.NAMESPACE_LOOKUP['SNMPv2-MIB'],
            'ydk.models.cisco_ios_xr.SNMPv2_MIB',
        ),
    },
    'SNMPv2MIB.SysORTable.SysOREntry' : {
        'meta_info' : _MetaInfoClass('SNMPv2MIB.SysORTable.SysOREntry', REFERENCE_LIST,
            ''' ''',
            False, 
            [
            _MetaInfoClassMember('sysORIndex', ATTRIBUTE, 'int', 'sysORIndexType',
                None, None,
                [('1', '2147483647')], [],
                '''                ''',
                'sysorindex',
                'SNMPv2-MIB', True),
            _MetaInfoClassMember('sysORID', ATTRIBUTE, 'str', 'yang:object-identifier',
                None, None,
                [], [b'(([0-1](\\.[1-3]?[0-9]))|(2\\.(0|([1-9]\\d*))))(\\.(0|([1-9]\\d*)))*'],
                '''                ''',
                'sysorid',
                'SNMPv2-MIB', False, is_config=False),
            _MetaInfoClassMember('sysORDescr', ATTRIBUTE, 'str', 'string',
                None, None,
                [(0, 255)], [],
                '''                ''',
                'sysordescr',
                'SNMPv2-MIB', False, is_config=False),
            _MetaInfoClassMember('sysORUpTime', ATTRIBUTE, 'int', 'yang:timestamp',
                None, None,
                [('0', '4294967295')], [],
                '''                ''',
                'sysoruptime',
                'SNMPv2-MIB', False, is_config=False),
            ],
            'SNMPv2-MIB',
            'sysOREntry',
            _yang_ns.NAMESPACE_LOOKUP['SNMPv2-MIB'],
            'ydk.models.cisco_ios_xr.SNMPv2_MIB',
        ),
    },
    'SNMPv2MIB.SysORTable' : {
        'meta_info' : _MetaInfoClass('SNMPv2MIB.SysORTable', REFERENCE_CLASS,
            ''' ''',
            False, 
            [
            _MetaInfoClassMember('sysOREntry', REFERENCE_LIST, 'SysOREntry', '',
                'ydk.models.cisco_ios_xr.SNMPv2_MIB', 'SNMPv2MIB.SysORTable.SysOREntry',
                [], [],
                '''                ''',
                'sysorentry',
                'SNMPv2-MIB', False),
            ],
            'SNMPv2-MIB',
            'sysORTable',
            _yang_ns.NAMESPACE_LOOKUP['SNMPv2-MIB'],
            'ydk.models.cisco_ios_xr.SNMPv2_MIB',
        ),
    },
    'SNMPv2MIB' : {
        'meta_info' : _MetaInfoClass('SNMPv2MIB', REFERENCE_CLASS,
            ''' ''',
            False, 
            [
            _MetaInfoClassMember('system', REFERENCE_CLASS, 'System', '',
                'ydk.models.cisco_ios_xr.SNMPv2_MIB', 'SNMPv2MIB.System',
                [], [],
                '''                ''',
                'system',
                'SNMPv2-MIB', False),
            _MetaInfoClassMember('snmp', REFERENCE_CLASS, 'Snmp', '',
                'ydk.models.cisco_ios_xr.SNMPv2_MIB', 'SNMPv2MIB.Snmp',
                [], [],
                '''                ''',
                'snmp',
                'SNMPv2-MIB', False),
            _MetaInfoClassMember('snmpSet', REFERENCE_CLASS, 'SnmpSet', '',
                'ydk.models.cisco_ios_xr.SNMPv2_MIB', 'SNMPv2MIB.SnmpSet',
                [], [],
                '''                ''',
                'snmpset',
                'SNMPv2-MIB', False),
            _MetaInfoClassMember('sysORTable', REFERENCE_CLASS, 'SysORTable', '',
                'ydk.models.cisco_ios_xr.SNMPv2_MIB', 'SNMPv2MIB.SysORTable',
                [], [],
                '''                ''',
                'sysortable',
                'SNMPv2-MIB', False),
            ],
            'SNMPv2-MIB',
            'SNMPv2-MIB',
            _yang_ns.NAMESPACE_LOOKUP['SNMPv2-MIB'],
            'ydk.models.cisco_ios_xr.SNMPv2_MIB',
        ),
    },
}
_meta_table['SNMPv2MIB.SysORTable.SysOREntry']['meta_info'].parent =_meta_table['SNMPv2MIB.SysORTable']['meta_info']
_meta_table['SNMPv2MIB.System']['meta_info'].parent =_meta_table['SNMPv2MIB']['meta_info']
_meta_table['SNMPv2MIB.Snmp']['meta_info'].parent =_meta_table['SNMPv2MIB']['meta_info']
_meta_table['SNMPv2MIB.SnmpSet']['meta_info'].parent =_meta_table['SNMPv2MIB']['meta_info']
_meta_table['SNMPv2MIB.SysORTable']['meta_info'].parent =_meta_table['SNMPv2MIB']['meta_info']
