
'''
This is auto-generated file,
which includes metadata for module SNMP_VIEW_BASED_ACM_MIB
'''

from ydk._core._dm_meta_info import _MetaInfoClassMember, _MetaInfoClass, _MetaInfoEnum
from ydk._core._dm_meta_info import ATTRIBUTE, REFERENCE_LIST, REFERENCE_LEAFLIST, REFERENCE_BITS, REFERENCE_UNION
from ydk._core._dm_meta_info import REFERENCE_CLASS, REFERENCE_IDENTITY_CLASS, REFERENCE_ENUM_CLASS, ANYXML_CLASS
from ydk._core._importer import _yang_ns

_meta_table = {
    'VacmAccessContextMatchType' : _MetaInfoEnum('VacmAccessContextMatchType',
        'ydk.models.cisco_ios_xr.SNMP_VIEW_BASED_ACM_MIB', 'VacmAccessContextMatchType',
        ''' ''',
        {
            'exact':'exact',
            'prefix':'prefix',
        }, 'SNMP-VIEW-BASED-ACM-MIB', _yang_ns.NAMESPACE_LOOKUP['SNMP-VIEW-BASED-ACM-MIB']),
    'VacmViewTreeFamilyTypeType' : _MetaInfoEnum('VacmViewTreeFamilyTypeType',
        'ydk.models.cisco_ios_xr.SNMP_VIEW_BASED_ACM_MIB', 'VacmViewTreeFamilyTypeType',
        ''' ''',
        {
            'included':'included',
            'excluded':'excluded',
        }, 'SNMP-VIEW-BASED-ACM-MIB', _yang_ns.NAMESPACE_LOOKUP['SNMP-VIEW-BASED-ACM-MIB']),
    'SNMPVIEWBASEDACMMIB.VacmSecurityToGroupTable.VacmSecurityToGroupEntry' : {
        'meta_info' : _MetaInfoClass('SNMPVIEWBASEDACMMIB.VacmSecurityToGroupTable.VacmSecurityToGroupEntry', REFERENCE_LIST,
            ''' ''',
            False, 
            [
            _MetaInfoClassMember('vacmSecurityModel', ATTRIBUTE, 'int', 'vacmSecurityModelType',
                None, None,
                [('1', '2147483647')], [],
                '''                ''',
                'vacmsecuritymodel',
                'SNMP-VIEW-BASED-ACM-MIB', True),
            _MetaInfoClassMember('vacmSecurityName', ATTRIBUTE, 'str', 'vacmSecurityNameType',
                None, None,
                [(1, 32)], [],
                '''                ''',
                'vacmsecurityname',
                'SNMP-VIEW-BASED-ACM-MIB', True),
            _MetaInfoClassMember('vacmGroupName', ATTRIBUTE, 'str', 'vacmGroupNameType',
                None, None,
                [(1, 32)], [],
                '''                ''',
                'vacmgroupname',
                'SNMP-VIEW-BASED-ACM-MIB', False, is_mandatory=True),
            _MetaInfoClassMember('vacmSecurityToGroupStorageType', REFERENCE_ENUM_CLASS, 'StorageType', 'SNMPv2_TC:StorageType',
                'ydk.models.cisco_ios_xr.SNMPv2_TC', 'StorageType',
                [], [],
                '''                ''',
                'vacmsecuritytogroupstoragetype',
                'SNMP-VIEW-BASED-ACM-MIB', False, default_value='SNMPv2_TC.StorageType.nonVolatile'),
            ],
            'SNMP-VIEW-BASED-ACM-MIB',
            'vacmSecurityToGroupEntry',
            _yang_ns.NAMESPACE_LOOKUP['SNMP-VIEW-BASED-ACM-MIB'],
            'ydk.models.cisco_ios_xr.SNMP_VIEW_BASED_ACM_MIB',
        ),
    },
    'SNMPVIEWBASEDACMMIB.VacmSecurityToGroupTable' : {
        'meta_info' : _MetaInfoClass('SNMPVIEWBASEDACMMIB.VacmSecurityToGroupTable', REFERENCE_CLASS,
            ''' ''',
            False, 
            [
            _MetaInfoClassMember('vacmSecurityToGroupEntry', REFERENCE_LIST, 'VacmSecurityToGroupEntry', '',
                'ydk.models.cisco_ios_xr.SNMP_VIEW_BASED_ACM_MIB', 'SNMPVIEWBASEDACMMIB.VacmSecurityToGroupTable.VacmSecurityToGroupEntry',
                [], [],
                '''                ''',
                'vacmsecuritytogroupentry',
                'SNMP-VIEW-BASED-ACM-MIB', False),
            ],
            'SNMP-VIEW-BASED-ACM-MIB',
            'vacmSecurityToGroupTable',
            _yang_ns.NAMESPACE_LOOKUP['SNMP-VIEW-BASED-ACM-MIB'],
            'ydk.models.cisco_ios_xr.SNMP_VIEW_BASED_ACM_MIB',
        ),
    },
    'SNMPVIEWBASEDACMMIB.VacmAccessTable.VacmAccessEntry' : {
        'meta_info' : _MetaInfoClass('SNMPVIEWBASEDACMMIB.VacmAccessTable.VacmAccessEntry', REFERENCE_LIST,
            ''' ''',
            False, 
            [
            _MetaInfoClassMember('vacmGroupName', ATTRIBUTE, 'str', 'vacmGroupNameType',
                None, None,
                [(1, 32)], [],
                '''                ''',
                'vacmgroupname',
                'SNMP-VIEW-BASED-ACM-MIB', True),
            _MetaInfoClassMember('vacmAccessContextPrefix', ATTRIBUTE, 'str', 'vacmAccessContextPrefixType',
                None, None,
                [('0', 32)], [],
                '''                ''',
                'vacmaccesscontextprefix',
                'SNMP-VIEW-BASED-ACM-MIB', True),
            _MetaInfoClassMember('vacmAccessSecurityModel', ATTRIBUTE, 'int', 'SNMP_FRAMEWORK_MIB:SnmpSecurityModel',
                None, None,
                [('0', '2147483647')], [],
                '''                ''',
                'vacmaccesssecuritymodel',
                'SNMP-VIEW-BASED-ACM-MIB', True),
            _MetaInfoClassMember('vacmAccessSecurityLevel', REFERENCE_ENUM_CLASS, 'SnmpSecurityLevel', 'SNMP_FRAMEWORK_MIB:SnmpSecurityLevel',
                'ydk.models.cisco_ios_xr.SNMP_FRAMEWORK_MIB', 'SnmpSecurityLevel',
                [], [],
                '''                ''',
                'vacmaccesssecuritylevel',
                'SNMP-VIEW-BASED-ACM-MIB', True),
            _MetaInfoClassMember('vacmAccessContextMatch', REFERENCE_ENUM_CLASS, 'VacmAccessContextMatchType', 'vacmAccessContextMatchType',
                'ydk.models.cisco_ios_xr.SNMP_VIEW_BASED_ACM_MIB', 'VacmAccessContextMatchType',
                [], [],
                '''                ''',
                'vacmaccesscontextmatch',
                'SNMP-VIEW-BASED-ACM-MIB', False, default_value='SNMP_VIEW_BASED_ACM_MIB.VacmAccessContextMatchType.exact'),
            _MetaInfoClassMember('vacmAccessReadViewName', ATTRIBUTE, 'str', 'vacmAccessReadViewNameType',
                None, None,
                [('0', 32)], [],
                '''                ''',
                'vacmaccessreadviewname',
                'SNMP-VIEW-BASED-ACM-MIB', False),
            _MetaInfoClassMember('vacmAccessWriteViewName', ATTRIBUTE, 'str', 'vacmAccessWriteViewNameType',
                None, None,
                [('0', 32)], [],
                '''                ''',
                'vacmaccesswriteviewname',
                'SNMP-VIEW-BASED-ACM-MIB', False),
            _MetaInfoClassMember('vacmAccessNotifyViewName', ATTRIBUTE, 'str', 'vacmAccessNotifyViewNameType',
                None, None,
                [('0', 32)], [],
                '''                ''',
                'vacmaccessnotifyviewname',
                'SNMP-VIEW-BASED-ACM-MIB', False),
            _MetaInfoClassMember('vacmAccessStorageType', REFERENCE_ENUM_CLASS, 'StorageType', 'SNMPv2_TC:StorageType',
                'ydk.models.cisco_ios_xr.SNMPv2_TC', 'StorageType',
                [], [],
                '''                ''',
                'vacmaccessstoragetype',
                'SNMP-VIEW-BASED-ACM-MIB', False, default_value='SNMPv2_TC.StorageType.nonVolatile'),
            ],
            'SNMP-VIEW-BASED-ACM-MIB',
            'vacmAccessEntry',
            _yang_ns.NAMESPACE_LOOKUP['SNMP-VIEW-BASED-ACM-MIB'],
            'ydk.models.cisco_ios_xr.SNMP_VIEW_BASED_ACM_MIB',
        ),
    },
    'SNMPVIEWBASEDACMMIB.VacmAccessTable' : {
        'meta_info' : _MetaInfoClass('SNMPVIEWBASEDACMMIB.VacmAccessTable', REFERENCE_CLASS,
            ''' ''',
            False, 
            [
            _MetaInfoClassMember('vacmAccessEntry', REFERENCE_LIST, 'VacmAccessEntry', '',
                'ydk.models.cisco_ios_xr.SNMP_VIEW_BASED_ACM_MIB', 'SNMPVIEWBASEDACMMIB.VacmAccessTable.VacmAccessEntry',
                [], [],
                '''                ''',
                'vacmaccessentry',
                'SNMP-VIEW-BASED-ACM-MIB', False),
            ],
            'SNMP-VIEW-BASED-ACM-MIB',
            'vacmAccessTable',
            _yang_ns.NAMESPACE_LOOKUP['SNMP-VIEW-BASED-ACM-MIB'],
            'ydk.models.cisco_ios_xr.SNMP_VIEW_BASED_ACM_MIB',
        ),
    },
    'SNMPVIEWBASEDACMMIB.VacmViewTreeFamilyTable.VacmViewTreeFamilyEntry' : {
        'meta_info' : _MetaInfoClass('SNMPVIEWBASEDACMMIB.VacmViewTreeFamilyTable.VacmViewTreeFamilyEntry', REFERENCE_LIST,
            ''' ''',
            False, 
            [
            _MetaInfoClassMember('vacmViewTreeFamilyViewName', ATTRIBUTE, 'str', 'vacmViewTreeFamilyViewNameType',
                None, None,
                [(1, 32)], [],
                '''                ''',
                'vacmviewtreefamilyviewname',
                'SNMP-VIEW-BASED-ACM-MIB', True),
            _MetaInfoClassMember('vacmViewTreeFamilySubtree', ATTRIBUTE, 'str', 'yang:object-identifier',
                None, None,
                [], [b'(([0-1](\\.[1-3]?[0-9]))|(2\\.(0|([1-9]\\d*))))(\\.(0|([1-9]\\d*)))*'],
                '''                ''',
                'vacmviewtreefamilysubtree',
                'SNMP-VIEW-BASED-ACM-MIB', True),
            _MetaInfoClassMember('vacmViewTreeFamilyMask', ATTRIBUTE, 'str', 'vacmViewTreeFamilyMaskType',
                None, None,
                [], [b'(([0-9a-fA-F]){2}(:([0-9a-fA-F]){2})*)?'],
                '''                ''',
                'vacmviewtreefamilymask',
                'SNMP-VIEW-BASED-ACM-MIB', False),
            _MetaInfoClassMember('vacmViewTreeFamilyType', REFERENCE_ENUM_CLASS, 'VacmViewTreeFamilyTypeType', 'vacmViewTreeFamilyTypeType',
                'ydk.models.cisco_ios_xr.SNMP_VIEW_BASED_ACM_MIB', 'VacmViewTreeFamilyTypeType',
                [], [],
                '''                ''',
                'vacmviewtreefamilytype',
                'SNMP-VIEW-BASED-ACM-MIB', False, default_value='SNMP_VIEW_BASED_ACM_MIB.VacmViewTreeFamilyTypeType.included'),
            _MetaInfoClassMember('vacmViewTreeFamilyStorageType', REFERENCE_ENUM_CLASS, 'StorageType', 'SNMPv2_TC:StorageType',
                'ydk.models.cisco_ios_xr.SNMPv2_TC', 'StorageType',
                [], [],
                '''                ''',
                'vacmviewtreefamilystoragetype',
                'SNMP-VIEW-BASED-ACM-MIB', False, default_value='SNMPv2_TC.StorageType.nonVolatile'),
            ],
            'SNMP-VIEW-BASED-ACM-MIB',
            'vacmViewTreeFamilyEntry',
            _yang_ns.NAMESPACE_LOOKUP['SNMP-VIEW-BASED-ACM-MIB'],
            'ydk.models.cisco_ios_xr.SNMP_VIEW_BASED_ACM_MIB',
        ),
    },
    'SNMPVIEWBASEDACMMIB.VacmViewTreeFamilyTable' : {
        'meta_info' : _MetaInfoClass('SNMPVIEWBASEDACMMIB.VacmViewTreeFamilyTable', REFERENCE_CLASS,
            ''' ''',
            False, 
            [
            _MetaInfoClassMember('vacmViewTreeFamilyEntry', REFERENCE_LIST, 'VacmViewTreeFamilyEntry', '',
                'ydk.models.cisco_ios_xr.SNMP_VIEW_BASED_ACM_MIB', 'SNMPVIEWBASEDACMMIB.VacmViewTreeFamilyTable.VacmViewTreeFamilyEntry',
                [], [],
                '''                ''',
                'vacmviewtreefamilyentry',
                'SNMP-VIEW-BASED-ACM-MIB', False),
            ],
            'SNMP-VIEW-BASED-ACM-MIB',
            'vacmViewTreeFamilyTable',
            _yang_ns.NAMESPACE_LOOKUP['SNMP-VIEW-BASED-ACM-MIB'],
            'ydk.models.cisco_ios_xr.SNMP_VIEW_BASED_ACM_MIB',
        ),
    },
    'SNMPVIEWBASEDACMMIB' : {
        'meta_info' : _MetaInfoClass('SNMPVIEWBASEDACMMIB', REFERENCE_CLASS,
            ''' ''',
            False, 
            [
            _MetaInfoClassMember('vacmSecurityToGroupTable', REFERENCE_CLASS, 'VacmSecurityToGroupTable', '',
                'ydk.models.cisco_ios_xr.SNMP_VIEW_BASED_ACM_MIB', 'SNMPVIEWBASEDACMMIB.VacmSecurityToGroupTable',
                [], [],
                '''                ''',
                'vacmsecuritytogrouptable',
                'SNMP-VIEW-BASED-ACM-MIB', False),
            _MetaInfoClassMember('vacmAccessTable', REFERENCE_CLASS, 'VacmAccessTable', '',
                'ydk.models.cisco_ios_xr.SNMP_VIEW_BASED_ACM_MIB', 'SNMPVIEWBASEDACMMIB.VacmAccessTable',
                [], [],
                '''                ''',
                'vacmaccesstable',
                'SNMP-VIEW-BASED-ACM-MIB', False),
            _MetaInfoClassMember('vacmViewTreeFamilyTable', REFERENCE_CLASS, 'VacmViewTreeFamilyTable', '',
                'ydk.models.cisco_ios_xr.SNMP_VIEW_BASED_ACM_MIB', 'SNMPVIEWBASEDACMMIB.VacmViewTreeFamilyTable',
                [], [],
                '''                ''',
                'vacmviewtreefamilytable',
                'SNMP-VIEW-BASED-ACM-MIB', False),
            ],
            'SNMP-VIEW-BASED-ACM-MIB',
            'SNMP-VIEW-BASED-ACM-MIB',
            _yang_ns.NAMESPACE_LOOKUP['SNMP-VIEW-BASED-ACM-MIB'],
            'ydk.models.cisco_ios_xr.SNMP_VIEW_BASED_ACM_MIB',
        ),
    },
}
_meta_table['SNMPVIEWBASEDACMMIB.VacmSecurityToGroupTable.VacmSecurityToGroupEntry']['meta_info'].parent =_meta_table['SNMPVIEWBASEDACMMIB.VacmSecurityToGroupTable']['meta_info']
_meta_table['SNMPVIEWBASEDACMMIB.VacmAccessTable.VacmAccessEntry']['meta_info'].parent =_meta_table['SNMPVIEWBASEDACMMIB.VacmAccessTable']['meta_info']
_meta_table['SNMPVIEWBASEDACMMIB.VacmViewTreeFamilyTable.VacmViewTreeFamilyEntry']['meta_info'].parent =_meta_table['SNMPVIEWBASEDACMMIB.VacmViewTreeFamilyTable']['meta_info']
_meta_table['SNMPVIEWBASEDACMMIB.VacmSecurityToGroupTable']['meta_info'].parent =_meta_table['SNMPVIEWBASEDACMMIB']['meta_info']
_meta_table['SNMPVIEWBASEDACMMIB.VacmAccessTable']['meta_info'].parent =_meta_table['SNMPVIEWBASEDACMMIB']['meta_info']
_meta_table['SNMPVIEWBASEDACMMIB.VacmViewTreeFamilyTable']['meta_info'].parent =_meta_table['SNMPVIEWBASEDACMMIB']['meta_info']
