
'''
This is auto-generated file,
which includes metadata for module SNMP_NOTIFICATION_MIB
'''

from ydk._core._dm_meta_info import _MetaInfoClassMember, _MetaInfoClass, _MetaInfoEnum
from ydk._core._dm_meta_info import ATTRIBUTE, REFERENCE_LIST, REFERENCE_LEAFLIST, REFERENCE_BITS, REFERENCE_UNION
from ydk._core._dm_meta_info import REFERENCE_CLASS, REFERENCE_IDENTITY_CLASS, REFERENCE_ENUM_CLASS, ANYXML_CLASS
from ydk._core._importer import _yang_ns

_meta_table = {
    'SnmpNotifyTypeType' : _MetaInfoEnum('SnmpNotifyTypeType',
        'ydk.models.cisco_ios_xr.SNMP_NOTIFICATION_MIB', 'SnmpNotifyTypeType',
        ''' ''',
        {
            'trap':'trap',
            'inform':'inform',
        }, 'SNMP-NOTIFICATION-MIB', _yang_ns.NAMESPACE_LOOKUP['SNMP-NOTIFICATION-MIB']),
    'SnmpNotifyFilterTypeType' : _MetaInfoEnum('SnmpNotifyFilterTypeType',
        'ydk.models.cisco_ios_xr.SNMP_NOTIFICATION_MIB', 'SnmpNotifyFilterTypeType',
        ''' ''',
        {
            'included':'included',
            'excluded':'excluded',
        }, 'SNMP-NOTIFICATION-MIB', _yang_ns.NAMESPACE_LOOKUP['SNMP-NOTIFICATION-MIB']),
    'SNMPNOTIFICATIONMIB.SnmpNotifyTable.SnmpNotifyEntry' : {
        'meta_info' : _MetaInfoClass('SNMPNOTIFICATIONMIB.SnmpNotifyTable.SnmpNotifyEntry', REFERENCE_LIST,
            ''' ''',
            False, 
            [
            _MetaInfoClassMember('snmpNotifyName', ATTRIBUTE, 'str', 'snmpNotifyNameType',
                None, None,
                [(1, 32)], [],
                '''                ''',
                'snmpnotifyname',
                'SNMP-NOTIFICATION-MIB', True),
            _MetaInfoClassMember('snmpNotifyTag', ATTRIBUTE, 'str', 'SNMP_TARGET_MIB:SnmpTagValue',
                None, None,
                [('0', 255)], [],
                '''                ''',
                'snmpnotifytag',
                'SNMP-NOTIFICATION-MIB', False),
            _MetaInfoClassMember('snmpNotifyType', REFERENCE_ENUM_CLASS, 'SnmpNotifyTypeType', 'snmpNotifyTypeType',
                'ydk.models.cisco_ios_xr.SNMP_NOTIFICATION_MIB', 'SnmpNotifyTypeType',
                [], [],
                '''                ''',
                'snmpnotifytype',
                'SNMP-NOTIFICATION-MIB', False, default_value='SNMP_NOTIFICATION_MIB.SnmpNotifyTypeType.trap'),
            _MetaInfoClassMember('snmpNotifyStorageType', REFERENCE_ENUM_CLASS, 'StorageType', 'SNMPv2_TC:StorageType',
                'ydk.models.cisco_ios_xr.SNMPv2_TC', 'StorageType',
                [], [],
                '''                ''',
                'snmpnotifystoragetype',
                'SNMP-NOTIFICATION-MIB', False, default_value='SNMPv2_TC.StorageType.nonVolatile'),
            ],
            'SNMP-NOTIFICATION-MIB',
            'snmpNotifyEntry',
            _yang_ns.NAMESPACE_LOOKUP['SNMP-NOTIFICATION-MIB'],
            'ydk.models.cisco_ios_xr.SNMP_NOTIFICATION_MIB',
        ),
    },
    'SNMPNOTIFICATIONMIB.SnmpNotifyTable' : {
        'meta_info' : _MetaInfoClass('SNMPNOTIFICATIONMIB.SnmpNotifyTable', REFERENCE_CLASS,
            ''' ''',
            False, 
            [
            _MetaInfoClassMember('snmpNotifyEntry', REFERENCE_LIST, 'SnmpNotifyEntry', '',
                'ydk.models.cisco_ios_xr.SNMP_NOTIFICATION_MIB', 'SNMPNOTIFICATIONMIB.SnmpNotifyTable.SnmpNotifyEntry',
                [], [],
                '''                ''',
                'snmpnotifyentry',
                'SNMP-NOTIFICATION-MIB', False),
            ],
            'SNMP-NOTIFICATION-MIB',
            'snmpNotifyTable',
            _yang_ns.NAMESPACE_LOOKUP['SNMP-NOTIFICATION-MIB'],
            'ydk.models.cisco_ios_xr.SNMP_NOTIFICATION_MIB',
        ),
    },
    'SNMPNOTIFICATIONMIB.SnmpNotifyFilterProfileTable.SnmpNotifyFilterProfileEntry' : {
        'meta_info' : _MetaInfoClass('SNMPNOTIFICATIONMIB.SnmpNotifyFilterProfileTable.SnmpNotifyFilterProfileEntry', REFERENCE_LIST,
            ''' ''',
            False, 
            [
            _MetaInfoClassMember('snmpTargetParamsName', ATTRIBUTE, 'str', 'snmpTargetParamsNameType',
                None, None,
                [(1, 32)], [],
                '''                ''',
                'snmptargetparamsname',
                'SNMP-NOTIFICATION-MIB', True),
            _MetaInfoClassMember('snmpNotifyFilterProfileName', ATTRIBUTE, 'str', 'snmpNotifyFilterProfileNameType',
                None, None,
                [(1, 32)], [],
                '''                ''',
                'snmpnotifyfilterprofilename',
                'SNMP-NOTIFICATION-MIB', False),
            _MetaInfoClassMember('snmpNotifyFilterProfileStorType', REFERENCE_ENUM_CLASS, 'StorageType', 'SNMPv2_TC:StorageType',
                'ydk.models.cisco_ios_xr.SNMPv2_TC', 'StorageType',
                [], [],
                '''                ''',
                'snmpnotifyfilterprofilestortype',
                'SNMP-NOTIFICATION-MIB', False, default_value='SNMPv2_TC.StorageType.nonVolatile'),
            ],
            'SNMP-NOTIFICATION-MIB',
            'snmpNotifyFilterProfileEntry',
            _yang_ns.NAMESPACE_LOOKUP['SNMP-NOTIFICATION-MIB'],
            'ydk.models.cisco_ios_xr.SNMP_NOTIFICATION_MIB',
        ),
    },
    'SNMPNOTIFICATIONMIB.SnmpNotifyFilterProfileTable' : {
        'meta_info' : _MetaInfoClass('SNMPNOTIFICATIONMIB.SnmpNotifyFilterProfileTable', REFERENCE_CLASS,
            ''' ''',
            False, 
            [
            _MetaInfoClassMember('snmpNotifyFilterProfileEntry', REFERENCE_LIST, 'SnmpNotifyFilterProfileEntry', '',
                'ydk.models.cisco_ios_xr.SNMP_NOTIFICATION_MIB', 'SNMPNOTIFICATIONMIB.SnmpNotifyFilterProfileTable.SnmpNotifyFilterProfileEntry',
                [], [],
                '''                ''',
                'snmpnotifyfilterprofileentry',
                'SNMP-NOTIFICATION-MIB', False),
            ],
            'SNMP-NOTIFICATION-MIB',
            'snmpNotifyFilterProfileTable',
            _yang_ns.NAMESPACE_LOOKUP['SNMP-NOTIFICATION-MIB'],
            'ydk.models.cisco_ios_xr.SNMP_NOTIFICATION_MIB',
            is_presence=True,
        ),
    },
    'SNMPNOTIFICATIONMIB.SnmpNotifyFilterTable.SnmpNotifyFilterEntry' : {
        'meta_info' : _MetaInfoClass('SNMPNOTIFICATIONMIB.SnmpNotifyFilterTable.SnmpNotifyFilterEntry', REFERENCE_LIST,
            ''' ''',
            False, 
            [
            _MetaInfoClassMember('snmpNotifyFilterProfileName', ATTRIBUTE, 'str', 'snmpNotifyFilterProfileNameType',
                None, None,
                [(1, 32)], [],
                '''                ''',
                'snmpnotifyfilterprofilename',
                'SNMP-NOTIFICATION-MIB', True),
            _MetaInfoClassMember('snmpNotifyFilterSubtree', ATTRIBUTE, 'str', 'yang:object-identifier',
                None, None,
                [], [b'(([0-1](\\.[1-3]?[0-9]))|(2\\.(0|([1-9]\\d*))))(\\.(0|([1-9]\\d*)))*'],
                '''                ''',
                'snmpnotifyfiltersubtree',
                'SNMP-NOTIFICATION-MIB', True),
            _MetaInfoClassMember('snmpNotifyFilterMask', ATTRIBUTE, 'str', 'snmpNotifyFilterMaskType',
                None, None,
                [], [b'(([0-9a-fA-F]){2}(:([0-9a-fA-F]){2})*)?'],
                '''                ''',
                'snmpnotifyfiltermask',
                'SNMP-NOTIFICATION-MIB', False),
            _MetaInfoClassMember('snmpNotifyFilterType', REFERENCE_ENUM_CLASS, 'SnmpNotifyFilterTypeType', 'snmpNotifyFilterTypeType',
                'ydk.models.cisco_ios_xr.SNMP_NOTIFICATION_MIB', 'SnmpNotifyFilterTypeType',
                [], [],
                '''                ''',
                'snmpnotifyfiltertype',
                'SNMP-NOTIFICATION-MIB', False, default_value='SNMP_NOTIFICATION_MIB.SnmpNotifyFilterTypeType.included'),
            _MetaInfoClassMember('snmpNotifyFilterStorageType', REFERENCE_ENUM_CLASS, 'StorageType', 'SNMPv2_TC:StorageType',
                'ydk.models.cisco_ios_xr.SNMPv2_TC', 'StorageType',
                [], [],
                '''                ''',
                'snmpnotifyfilterstoragetype',
                'SNMP-NOTIFICATION-MIB', False, default_value='SNMPv2_TC.StorageType.nonVolatile'),
            ],
            'SNMP-NOTIFICATION-MIB',
            'snmpNotifyFilterEntry',
            _yang_ns.NAMESPACE_LOOKUP['SNMP-NOTIFICATION-MIB'],
            'ydk.models.cisco_ios_xr.SNMP_NOTIFICATION_MIB',
        ),
    },
    'SNMPNOTIFICATIONMIB.SnmpNotifyFilterTable' : {
        'meta_info' : _MetaInfoClass('SNMPNOTIFICATIONMIB.SnmpNotifyFilterTable', REFERENCE_CLASS,
            ''' ''',
            False, 
            [
            _MetaInfoClassMember('snmpNotifyFilterEntry', REFERENCE_LIST, 'SnmpNotifyFilterEntry', '',
                'ydk.models.cisco_ios_xr.SNMP_NOTIFICATION_MIB', 'SNMPNOTIFICATIONMIB.SnmpNotifyFilterTable.SnmpNotifyFilterEntry',
                [], [],
                '''                ''',
                'snmpnotifyfilterentry',
                'SNMP-NOTIFICATION-MIB', False),
            ],
            'SNMP-NOTIFICATION-MIB',
            'snmpNotifyFilterTable',
            _yang_ns.NAMESPACE_LOOKUP['SNMP-NOTIFICATION-MIB'],
            'ydk.models.cisco_ios_xr.SNMP_NOTIFICATION_MIB',
            is_presence=True,
        ),
    },
    'SNMPNOTIFICATIONMIB' : {
        'meta_info' : _MetaInfoClass('SNMPNOTIFICATIONMIB', REFERENCE_CLASS,
            ''' ''',
            False, 
            [
            _MetaInfoClassMember('snmpNotifyTable', REFERENCE_CLASS, 'SnmpNotifyTable', '',
                'ydk.models.cisco_ios_xr.SNMP_NOTIFICATION_MIB', 'SNMPNOTIFICATIONMIB.SnmpNotifyTable',
                [], [],
                '''                ''',
                'snmpnotifytable',
                'SNMP-NOTIFICATION-MIB', False),
            _MetaInfoClassMember('snmpNotifyFilterProfileTable', REFERENCE_CLASS, 'SnmpNotifyFilterProfileTable', '',
                'ydk.models.cisco_ios_xr.SNMP_NOTIFICATION_MIB', 'SNMPNOTIFICATIONMIB.SnmpNotifyFilterProfileTable',
                [], [],
                '''                ''',
                'snmpnotifyfilterprofiletable',
                'SNMP-NOTIFICATION-MIB', False, is_presence=True),
            _MetaInfoClassMember('snmpNotifyFilterTable', REFERENCE_CLASS, 'SnmpNotifyFilterTable', '',
                'ydk.models.cisco_ios_xr.SNMP_NOTIFICATION_MIB', 'SNMPNOTIFICATIONMIB.SnmpNotifyFilterTable',
                [], [],
                '''                ''',
                'snmpnotifyfiltertable',
                'SNMP-NOTIFICATION-MIB', False, is_presence=True),
            ],
            'SNMP-NOTIFICATION-MIB',
            'SNMP-NOTIFICATION-MIB',
            _yang_ns.NAMESPACE_LOOKUP['SNMP-NOTIFICATION-MIB'],
            'ydk.models.cisco_ios_xr.SNMP_NOTIFICATION_MIB',
        ),
    },
}
_meta_table['SNMPNOTIFICATIONMIB.SnmpNotifyTable.SnmpNotifyEntry']['meta_info'].parent =_meta_table['SNMPNOTIFICATIONMIB.SnmpNotifyTable']['meta_info']
_meta_table['SNMPNOTIFICATIONMIB.SnmpNotifyFilterProfileTable.SnmpNotifyFilterProfileEntry']['meta_info'].parent =_meta_table['SNMPNOTIFICATIONMIB.SnmpNotifyFilterProfileTable']['meta_info']
_meta_table['SNMPNOTIFICATIONMIB.SnmpNotifyFilterTable.SnmpNotifyFilterEntry']['meta_info'].parent =_meta_table['SNMPNOTIFICATIONMIB.SnmpNotifyFilterTable']['meta_info']
_meta_table['SNMPNOTIFICATIONMIB.SnmpNotifyTable']['meta_info'].parent =_meta_table['SNMPNOTIFICATIONMIB']['meta_info']
_meta_table['SNMPNOTIFICATIONMIB.SnmpNotifyFilterProfileTable']['meta_info'].parent =_meta_table['SNMPNOTIFICATIONMIB']['meta_info']
_meta_table['SNMPNOTIFICATIONMIB.SnmpNotifyFilterTable']['meta_info'].parent =_meta_table['SNMPNOTIFICATIONMIB']['meta_info']
