
'''
This is auto-generated file,
which includes metadata for module tailf_aaa
'''

from ydk._core._dm_meta_info import _MetaInfoClassMember, _MetaInfoClass, _MetaInfoEnum
from ydk._core._dm_meta_info import ATTRIBUTE, REFERENCE_LIST, REFERENCE_LEAFLIST, REFERENCE_BITS, REFERENCE_UNION
from ydk._core._dm_meta_info import REFERENCE_CLASS, REFERENCE_IDENTITY_CLASS, REFERENCE_ENUM_CLASS, ANYXML_CLASS
from ydk._core._importer import _yang_ns

_meta_table = {
    'DataOperationType' : _MetaInfoEnum('DataOperationType',
        'ydk.models.cisco_ios_xr.tailf_aaa', 'DataOperationType',
        ''' ''',
        {
            'r':'r',
            'rx':'rx',
            'x':'x',
            'rw':'rw',
            'rwx':'rwx',
            'wx':'wx',
            'w':'w',
            'c':'c',
            'cr':'cr',
            'cu':'cu',
            'cd':'cd',
            'cx':'cx',
            'cru':'cru',
            'crd':'crd',
            'crx':'crx',
            'cud':'cud',
            'cux':'cux',
            'cdx':'cdx',
            'crud':'crud',
            'crux':'crux',
            'crdx':'crdx',
            'cudx':'cudx',
            'crudx':'crudx',
            'ru':'ru',
            'rd':'rd',
            'rud':'rud',
            'rux':'rux',
            'rdx':'rdx',
            'u':'u',
            'ud':'ud',
            'ux':'ux',
            'd':'d',
            'dx':'dx',
        }, 'tailf-aaa', _yang_ns.NAMESPACE_LOOKUP['tailf-aaa']),
    'CmdOperationType' : _MetaInfoEnum('CmdOperationType',
        'ydk.models.cisco_ios_xr.tailf_aaa', 'CmdOperationType',
        ''' ''',
        {
            'r':'r',
            'rx':'rx',
            'x':'x',
        }, 'tailf-aaa', _yang_ns.NAMESPACE_LOOKUP['tailf-aaa']),
    'Action' : _MetaInfoEnum('Action',
        'ydk.models.cisco_ios_xr.tailf_aaa', 'Action',
        ''' ''',
        {
            'accept':'accept',
            'reject':'reject',
            'accept_log':'accept_log',
        }, 'tailf-aaa', _yang_ns.NAMESPACE_LOOKUP['tailf-aaa']),
    'BuiltinModes' : _MetaInfoEnum('BuiltinModes',
        'ydk.models.cisco_ios_xr.tailf_aaa', 'BuiltinModes',
        ''' ''',
        {
            'exec':'exec_',
            'configure':'configure',
        }, 'tailf-aaa', _yang_ns.NAMESPACE_LOOKUP['tailf-aaa']),
    'BuiltinModes_' : _MetaInfoEnum('BuiltinModes_',
        'ydk.models.cisco_ios_xr.tailf_aaa', 'BuiltinModes_',
        ''' ''',
        {
            'exec':'exec_',
            'configure':'configure',
        }, 'tailf-aaa', _yang_ns.NAMESPACE_LOOKUP['tailf-aaa']),
    'Aaa.Authentication.Users.User' : {
        'meta_info' : _MetaInfoClass('Aaa.Authentication.Users.User', REFERENCE_LIST,
            ''' ''',
            False, 
            [
            _MetaInfoClassMember('name', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                ''',
                'name',
                'tailf-aaa', True),
            _MetaInfoClassMember('uid', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                ''',
                'uid',
                'tailf-aaa', False, default_value="9000"),
            _MetaInfoClassMember('gid', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                ''',
                'gid',
                'tailf-aaa', False, default_value="100"),
            _MetaInfoClassMember('password', ATTRIBUTE, 'str', 'passwdStr',
                None, None,
                [], [],
                '''                ''',
                'password',
                'tailf-aaa', False, is_mandatory=True),
            _MetaInfoClassMember('ssh_keydir', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                ''',
                'ssh_keydir',
                'tailf-aaa', False, default_value="'/home/sshdir'"),
            _MetaInfoClassMember('homedir', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                ''',
                'homedir',
                'tailf-aaa', False, default_value="'/home/homedir'"),
            ],
            'tailf-aaa',
            'user',
            _yang_ns.NAMESPACE_LOOKUP['tailf-aaa'],
            'ydk.models.cisco_ios_xr.tailf_aaa',
        ),
    },
    'Aaa.Authentication.Users' : {
        'meta_info' : _MetaInfoClass('Aaa.Authentication.Users', REFERENCE_CLASS,
            ''' ''',
            False, 
            [
            _MetaInfoClassMember('user', REFERENCE_LIST, 'User', '',
                'ydk.models.cisco_ios_xr.tailf_aaa', 'Aaa.Authentication.Users.User',
                [], [],
                '''                ''',
                'user',
                'tailf-aaa', False, max_elements=1024),
            ],
            'tailf-aaa',
            'users',
            _yang_ns.NAMESPACE_LOOKUP['tailf-aaa'],
            'ydk.models.cisco_ios_xr.tailf_aaa',
        ),
    },
    'Aaa.Authentication.Groups.Group' : {
        'meta_info' : _MetaInfoClass('Aaa.Authentication.Groups.Group', REFERENCE_LIST,
            ''' ''',
            False, 
            [
            _MetaInfoClassMember('name', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                ''',
                'name',
                'tailf-aaa', True),
            _MetaInfoClassMember('gid', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                ''',
                'gid',
                'tailf-aaa', False, default_value="100"),
            _MetaInfoClassMember('users', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                ''',
                'users',
                'tailf-aaa', False, default_value="'%%__system_user__%%'"),
            ],
            'tailf-aaa',
            'group',
            _yang_ns.NAMESPACE_LOOKUP['tailf-aaa'],
            'ydk.models.cisco_ios_xr.tailf_aaa',
        ),
    },
    'Aaa.Authentication.Groups' : {
        'meta_info' : _MetaInfoClass('Aaa.Authentication.Groups', REFERENCE_CLASS,
            ''' ''',
            False, 
            [
            _MetaInfoClassMember('group', REFERENCE_LIST, 'Group', '',
                'ydk.models.cisco_ios_xr.tailf_aaa', 'Aaa.Authentication.Groups.Group',
                [], [],
                '''                ''',
                'group',
                'tailf-aaa', False, max_elements=32),
            ],
            'tailf-aaa',
            'groups',
            _yang_ns.NAMESPACE_LOOKUP['tailf-aaa'],
            'ydk.models.cisco_ios_xr.tailf_aaa',
        ),
    },
    'Aaa.Authentication.Login.Group' : {
        'meta_info' : _MetaInfoClass('Aaa.Authentication.Login.Group', REFERENCE_CLASS,
            ''' ''',
            False, 
            [
            _MetaInfoClassMember('tacacs', ATTRIBUTE, 'Empty', 'empty',
                None, None,
                [], [],
                '''                ''',
                'tacacs',
                'tailf-aaa', False),
            ],
            'tailf-aaa',
            'group',
            _yang_ns.NAMESPACE_LOOKUP['tailf-aaa'],
            'ydk.models.cisco_ios_xr.tailf_aaa',
        ),
    },
    'Aaa.Authentication.Login' : {
        'meta_info' : _MetaInfoClass('Aaa.Authentication.Login', REFERENCE_CLASS,
            ''' ''',
            False, 
            [
            _MetaInfoClassMember('group', REFERENCE_CLASS, 'Group', '',
                'ydk.models.cisco_ios_xr.tailf_aaa', 'Aaa.Authentication.Login.Group',
                [], [],
                '''                ''',
                'group',
                'tailf-aaa', False),
            ],
            'tailf-aaa',
            'login',
            _yang_ns.NAMESPACE_LOOKUP['tailf-aaa'],
            'ydk.models.cisco_ios_xr.tailf_aaa',
        ),
    },
    'Aaa.Authentication' : {
        'meta_info' : _MetaInfoClass('Aaa.Authentication', REFERENCE_CLASS,
            ''' ''',
            False, 
            [
            _MetaInfoClassMember('users', REFERENCE_CLASS, 'Users', '',
                'ydk.models.cisco_ios_xr.tailf_aaa', 'Aaa.Authentication.Users',
                [], [],
                '''                ''',
                'users',
                'tailf-aaa', False),
            _MetaInfoClassMember('groups', REFERENCE_CLASS, 'Groups', '',
                'ydk.models.cisco_ios_xr.tailf_aaa', 'Aaa.Authentication.Groups',
                [], [],
                '''                ''',
                'groups',
                'tailf-aaa', False),
            _MetaInfoClassMember('login', REFERENCE_CLASS, 'Login', '',
                'ydk.models.cisco_ios_xr.tailf_aaa', 'Aaa.Authentication.Login',
                [], [],
                '''                ''',
                'login',
                'tailf-aaa', False),
            ],
            'tailf-aaa',
            'authentication',
            _yang_ns.NAMESPACE_LOOKUP['tailf-aaa'],
            'ydk.models.cisco_ios_xr.tailf_aaa',
        ),
    },
    'Aaa.Authorization.Cmdrules.Cmdrule' : {
        'meta_info' : _MetaInfoClass('Aaa.Authorization.Cmdrules.Cmdrule', REFERENCE_LIST,
            ''' ''',
            False, 
            [
            _MetaInfoClassMember('index', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                ''',
                'index',
                'tailf-aaa', True),
            _MetaInfoClassMember('context', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                ''',
                'context',
                'tailf-aaa', False, is_mandatory=True),
            _MetaInfoClassMember('command', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                ''',
                'command',
                'tailf-aaa', False, is_mandatory=True),
            _MetaInfoClassMember('group', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                ''',
                'group',
                'tailf-aaa', False, is_mandatory=True),
            _MetaInfoClassMember('ops', REFERENCE_ENUM_CLASS, 'CmdOperationType', 'cmdOperationType',
                'ydk.models.cisco_ios_xr.tailf_aaa', 'CmdOperationType',
                [], [],
                '''                ''',
                'ops',
                'tailf-aaa', False, is_mandatory=True),
            _MetaInfoClassMember('action', REFERENCE_ENUM_CLASS, 'Action', 'Action',
                'ydk.models.cisco_ios_xr.tailf_aaa', 'Action',
                [], [],
                '''                ''',
                'action',
                'tailf-aaa', False, is_mandatory=True),
            ],
            'tailf-aaa',
            'cmdrule',
            _yang_ns.NAMESPACE_LOOKUP['tailf-aaa'],
            'ydk.models.cisco_ios_xr.tailf_aaa',
        ),
    },
    'Aaa.Authorization.Cmdrules' : {
        'meta_info' : _MetaInfoClass('Aaa.Authorization.Cmdrules', REFERENCE_CLASS,
            ''' ''',
            False, 
            [
            _MetaInfoClassMember('cmdrule', REFERENCE_LIST, 'Cmdrule', '',
                'ydk.models.cisco_ios_xr.tailf_aaa', 'Aaa.Authorization.Cmdrules.Cmdrule',
                [], [],
                '''                ''',
                'cmdrule',
                'tailf-aaa', False),
            ],
            'tailf-aaa',
            'cmdrules',
            _yang_ns.NAMESPACE_LOOKUP['tailf-aaa'],
            'ydk.models.cisco_ios_xr.tailf_aaa',
        ),
    },
    'Aaa.Authorization.Datarules.Datarule' : {
        'meta_info' : _MetaInfoClass('Aaa.Authorization.Datarules.Datarule', REFERENCE_LIST,
            ''' ''',
            False, 
            [
            _MetaInfoClassMember('index', ATTRIBUTE, 'int', 'uint32',
                None, None,
                [('0', '4294967295')], [],
                '''                ''',
                'index',
                'tailf-aaa', True),
            _MetaInfoClassMember('namespace', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                ''',
                'namespace',
                'tailf-aaa', False, is_mandatory=True),
            _MetaInfoClassMember('context', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                ''',
                'context',
                'tailf-aaa', False, default_value="'*'"),
            _MetaInfoClassMember('keypath', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                ''',
                'keypath',
                'tailf-aaa', False, is_mandatory=True),
            _MetaInfoClassMember('group', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                ''',
                'group',
                'tailf-aaa', False, is_mandatory=True),
            _MetaInfoClassMember('ops', REFERENCE_ENUM_CLASS, 'DataOperationType', 'dataOperationType',
                'ydk.models.cisco_ios_xr.tailf_aaa', 'DataOperationType',
                [], [],
                '''                ''',
                'ops',
                'tailf-aaa', False, is_mandatory=True),
            _MetaInfoClassMember('action', REFERENCE_ENUM_CLASS, 'Action', 'Action',
                'ydk.models.cisco_ios_xr.tailf_aaa', 'Action',
                [], [],
                '''                ''',
                'action',
                'tailf-aaa', False, is_mandatory=True),
            ],
            'tailf-aaa',
            'datarule',
            _yang_ns.NAMESPACE_LOOKUP['tailf-aaa'],
            'ydk.models.cisco_ios_xr.tailf_aaa',
        ),
    },
    'Aaa.Authorization.Datarules' : {
        'meta_info' : _MetaInfoClass('Aaa.Authorization.Datarules', REFERENCE_CLASS,
            ''' ''',
            False, 
            [
            _MetaInfoClassMember('datarule', REFERENCE_LIST, 'Datarule', '',
                'ydk.models.cisco_ios_xr.tailf_aaa', 'Aaa.Authorization.Datarules.Datarule',
                [], [],
                '''                ''',
                'datarule',
                'tailf-aaa', False),
            ],
            'tailf-aaa',
            'datarules',
            _yang_ns.NAMESPACE_LOOKUP['tailf-aaa'],
            'ydk.models.cisco_ios_xr.tailf_aaa',
        ),
    },
    'Aaa.Authorization.Commands.Group' : {
        'meta_info' : _MetaInfoClass('Aaa.Authorization.Commands.Group', REFERENCE_CLASS,
            ''' ''',
            False, 
            [
            _MetaInfoClassMember('tacacs', ATTRIBUTE, 'Empty', 'empty',
                None, None,
                [], [],
                '''                ''',
                'tacacs',
                'tailf-aaa', False),
            _MetaInfoClassMember('none', ATTRIBUTE, 'Empty', 'empty',
                None, None,
                [], [],
                '''                ''',
                'none',
                'tailf-aaa', False),
            ],
            'tailf-aaa',
            'group',
            _yang_ns.NAMESPACE_LOOKUP['tailf-aaa'],
            'ydk.models.cisco_ios_xr.tailf_aaa',
        ),
    },
    'Aaa.Authorization.Commands' : {
        'meta_info' : _MetaInfoClass('Aaa.Authorization.Commands', REFERENCE_CLASS,
            ''' ''',
            False, 
            [
            _MetaInfoClassMember('group', REFERENCE_CLASS, 'Group', '',
                'ydk.models.cisco_ios_xr.tailf_aaa', 'Aaa.Authorization.Commands.Group',
                [], [],
                '''                ''',
                'group',
                'tailf-aaa', False),
            ],
            'tailf-aaa',
            'commands',
            _yang_ns.NAMESPACE_LOOKUP['tailf-aaa'],
            'ydk.models.cisco_ios_xr.tailf_aaa',
        ),
    },
    'Aaa.Authorization' : {
        'meta_info' : _MetaInfoClass('Aaa.Authorization', REFERENCE_CLASS,
            ''' ''',
            False, 
            [
            _MetaInfoClassMember('cmdrules', REFERENCE_CLASS, 'Cmdrules', '',
                'ydk.models.cisco_ios_xr.tailf_aaa', 'Aaa.Authorization.Cmdrules',
                [], [],
                '''                ''',
                'cmdrules',
                'tailf-aaa', False),
            _MetaInfoClassMember('datarules', REFERENCE_CLASS, 'Datarules', '',
                'ydk.models.cisco_ios_xr.tailf_aaa', 'Aaa.Authorization.Datarules',
                [], [],
                '''                ''',
                'datarules',
                'tailf-aaa', False),
            _MetaInfoClassMember('commands', REFERENCE_CLASS, 'Commands', '',
                'ydk.models.cisco_ios_xr.tailf_aaa', 'Aaa.Authorization.Commands',
                [], [],
                '''                ''',
                'commands',
                'tailf-aaa', False),
            ],
            'tailf-aaa',
            'authorization',
            _yang_ns.NAMESPACE_LOOKUP['tailf-aaa'],
            'ydk.models.cisco_ios_xr.tailf_aaa',
        ),
    },
    'Aaa.Accounting.Commands.Group' : {
        'meta_info' : _MetaInfoClass('Aaa.Accounting.Commands.Group', REFERENCE_CLASS,
            ''' ''',
            False, 
            [
            _MetaInfoClassMember('tacacs', ATTRIBUTE, 'Empty', 'empty',
                None, None,
                [], [],
                '''                ''',
                'tacacs',
                'tailf-aaa', False),
            ],
            'tailf-aaa',
            'group',
            _yang_ns.NAMESPACE_LOOKUP['tailf-aaa'],
            'ydk.models.cisco_ios_xr.tailf_aaa',
        ),
    },
    'Aaa.Accounting.Commands' : {
        'meta_info' : _MetaInfoClass('Aaa.Accounting.Commands', REFERENCE_CLASS,
            ''' ''',
            False, 
            [
            _MetaInfoClassMember('group', REFERENCE_CLASS, 'Group', '',
                'ydk.models.cisco_ios_xr.tailf_aaa', 'Aaa.Accounting.Commands.Group',
                [], [],
                '''                ''',
                'group',
                'tailf-aaa', False),
            ],
            'tailf-aaa',
            'commands',
            _yang_ns.NAMESPACE_LOOKUP['tailf-aaa'],
            'ydk.models.cisco_ios_xr.tailf_aaa',
        ),
    },
    'Aaa.Accounting' : {
        'meta_info' : _MetaInfoClass('Aaa.Accounting', REFERENCE_CLASS,
            ''' ''',
            False, 
            [
            _MetaInfoClassMember('commands', REFERENCE_CLASS, 'Commands', '',
                'ydk.models.cisco_ios_xr.tailf_aaa', 'Aaa.Accounting.Commands',
                [], [],
                '''                ''',
                'commands',
                'tailf-aaa', False),
            ],
            'tailf-aaa',
            'accounting',
            _yang_ns.NAMESPACE_LOOKUP['tailf-aaa'],
            'ydk.models.cisco_ios_xr.tailf_aaa',
        ),
    },
    'Aaa.Ios.Level' : {
        'meta_info' : _MetaInfoClass('Aaa.Ios.Level', REFERENCE_LIST,
            ''' ''',
            False, 
            [
            _MetaInfoClassMember('nr', ATTRIBUTE, 'int', 'levelInt',
                None, None,
                [('0', '15')], [],
                '''                ''',
                'nr',
                'tailf-aaa', True),
            _MetaInfoClassMember('secret', ATTRIBUTE, 'str', 'passwdStr',
                None, None,
                [], [],
                '''                ''',
                'secret',
                'tailf-aaa', False),
            _MetaInfoClassMember('password', ATTRIBUTE, 'str', 'passwdStr',
                None, None,
                [], [],
                '''                ''',
                'password',
                'tailf-aaa', False),
            _MetaInfoClassMember('prompt', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                ''',
                'prompt',
                'tailf-aaa', False, default_value="'\h# '"),
            ],
            'tailf-aaa',
            'level',
            _yang_ns.NAMESPACE_LOOKUP['tailf-aaa'],
            'ydk.models.cisco_ios_xr.tailf_aaa',
        ),
    },
    'Aaa.Ios.Privilege.Level.Command' : {
        'meta_info' : _MetaInfoClass('Aaa.Ios.Privilege.Level.Command', REFERENCE_LIST,
            ''' ''',
            False, 
            [
            _MetaInfoClassMember('name', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                ''',
                'name',
                'tailf-aaa', True),
            ],
            'tailf-aaa',
            'command',
            _yang_ns.NAMESPACE_LOOKUP['tailf-aaa'],
            'ydk.models.cisco_ios_xr.tailf_aaa',
        ),
    },
    'Aaa.Ios.Privilege.Level' : {
        'meta_info' : _MetaInfoClass('Aaa.Ios.Privilege.Level', REFERENCE_LIST,
            ''' ''',
            False, 
            [
            _MetaInfoClassMember('nr', ATTRIBUTE, 'int', 'levelInt',
                None, None,
                [('0', '15')], [],
                '''                ''',
                'nr',
                'tailf-aaa', True),
            _MetaInfoClassMember('command', REFERENCE_LIST, 'Command', '',
                'ydk.models.cisco_ios_xr.tailf_aaa', 'Aaa.Ios.Privilege.Level.Command',
                [], [],
                '''                ''',
                'command',
                'tailf-aaa', False),
            ],
            'tailf-aaa',
            'level',
            _yang_ns.NAMESPACE_LOOKUP['tailf-aaa'],
            'ydk.models.cisco_ios_xr.tailf_aaa',
        ),
    },
    'Aaa.Ios.Privilege' : {
        'meta_info' : _MetaInfoClass('Aaa.Ios.Privilege', REFERENCE_LIST,
            ''' ''',
            False, 
            [
            _MetaInfoClassMember('mode', REFERENCE_UNION, 'str', 'modeStr',
                None, None,
                [], [],
                '''                ''',
                'mode',
                'tailf-aaa', True, [
                    _MetaInfoClassMember('mode', ATTRIBUTE, 'str', 'string',
                        None, None,
                        [], [],
                        '''                        ''',
                        'mode',
                        'tailf-aaa', True),
                    _MetaInfoClassMember('mode', REFERENCE_ENUM_CLASS, 'BuiltinModes_', 'builtinModes',
                        'ydk.models.cisco_ios_xr.tailf_aaa', 'BuiltinModes_',
                        [], [],
                        '''                        ''',
                        'mode',
                        'tailf-aaa', True),
                ]),
            _MetaInfoClassMember('level', REFERENCE_LIST, 'Level', '',
                'ydk.models.cisco_ios_xr.tailf_aaa', 'Aaa.Ios.Privilege.Level',
                [], [],
                '''                ''',
                'level',
                'tailf-aaa', False, max_elements=15, min_elements=1),
            ],
            'tailf-aaa',
            'privilege',
            _yang_ns.NAMESPACE_LOOKUP['tailf-aaa'],
            'ydk.models.cisco_ios_xr.tailf_aaa',
        ),
    },
    'Aaa.Ios' : {
        'meta_info' : _MetaInfoClass('Aaa.Ios', REFERENCE_CLASS,
            ''' ''',
            False, 
            [
            _MetaInfoClassMember('level', REFERENCE_LIST, 'Level', '',
                'ydk.models.cisco_ios_xr.tailf_aaa', 'Aaa.Ios.Level',
                [], [],
                '''                ''',
                'level',
                'tailf-aaa', False, min_elements=2),
            _MetaInfoClassMember('privilege', REFERENCE_LIST, 'Privilege', '',
                'ydk.models.cisco_ios_xr.tailf_aaa', 'Aaa.Ios.Privilege',
                [], [],
                '''                ''',
                'privilege',
                'tailf-aaa', False),
            ],
            'tailf-aaa',
            'ios',
            _yang_ns.NAMESPACE_LOOKUP['tailf-aaa'],
            'ydk.models.cisco_ios_xr.tailf_aaa',
            is_presence=True,
        ),
    },
    'Aaa.DisasterRecovery' : {
        'meta_info' : _MetaInfoClass('Aaa.DisasterRecovery', REFERENCE_CLASS,
            ''' ''',
            False, 
            [
            _MetaInfoClassMember('username', ATTRIBUTE, 'str', 'leafref',
                None, None,
                [], [],
                '''                ''',
                'username',
                'Cisco-IOS-XR-sysadmin-aaa-disaster-recovery', False),
            _MetaInfoClassMember('password', ATTRIBUTE, 'str', 'tailf:md5-digest-string',
                None, None,
                [], [],
                '''                ''',
                'password',
                'Cisco-IOS-XR-sysadmin-aaa-disaster-recovery', False),
            ],
            'Cisco-IOS-XR-sysadmin-aaa-disaster-recovery',
            'disaster-recovery',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-sysadmin-aaa-disaster-recovery'],
            'ydk.models.cisco_ios_xr.tailf_aaa',
        ),
    },
    'Aaa.PrivilegedAccess' : {
        'meta_info' : _MetaInfoClass('Aaa.PrivilegedAccess', REFERENCE_CLASS,
            ''' ''',
            False, 
            [
            _MetaInfoClassMember('shell-access', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                ''',
                'shell_access',
                'Cisco-IOS-XR-sysadmin-aaa-aaa-show', False, is_config=False),
            _MetaInfoClassMember('first-user', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                ''',
                'first_user',
                'Cisco-IOS-XR-sysadmin-aaa-aaa-show', False, is_config=False),
            _MetaInfoClassMember('first-user-change', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                ''',
                'first_user_change',
                'Cisco-IOS-XR-sysadmin-aaa-aaa-show', False, is_config=False),
            _MetaInfoClassMember('current-disaster-recovery-user', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                ''',
                'current_disaster_recovery_user',
                'Cisco-IOS-XR-sysadmin-aaa-aaa-show', False, is_config=False),
            ],
            'Cisco-IOS-XR-sysadmin-aaa-aaa-show',
            'privileged-access',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-sysadmin-aaa-aaa-show'],
            'ydk.models.cisco_ios_xr.tailf_aaa',
            is_config=False,
        ),
    },
    'Aaa.CiscoIOSXRSysadminAaaAaaShowAccounting' : {
        'meta_info' : _MetaInfoClass('Aaa.CiscoIOSXRSysadminAaaAaaShowAccounting', REFERENCE_CLASS,
            ''' ''',
            False, 
            [
            _MetaInfoClassMember('log-data', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                ''',
                'log_data',
                'Cisco-IOS-XR-sysadmin-aaa-aaa-show', False, is_config=False),
            ],
            'Cisco-IOS-XR-sysadmin-aaa-aaa-show',
            'accounting',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-sysadmin-aaa-aaa-show'],
            'ydk.models.cisco_ios_xr.tailf_aaa',
            is_config=False,
        ),
    },
    'Aaa.UserGroup' : {
        'meta_info' : _MetaInfoClass('Aaa.UserGroup', REFERENCE_CLASS,
            ''' ''',
            False, 
            [
            _MetaInfoClassMember('grp-data', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                ''',
                'grp_data',
                'Cisco-IOS-XR-sysadmin-aaa-aaa-show', False, is_config=False),
            ],
            'Cisco-IOS-XR-sysadmin-aaa-aaa-show',
            'user-group',
            _yang_ns.NAMESPACE_LOOKUP['Cisco-IOS-XR-sysadmin-aaa-aaa-show'],
            'ydk.models.cisco_ios_xr.tailf_aaa',
            is_config=False,
        ),
    },
    'Aaa' : {
        'meta_info' : _MetaInfoClass('Aaa', REFERENCE_CLASS,
            ''' ''',
            False, 
            [
            _MetaInfoClassMember('authentication', REFERENCE_CLASS, 'Authentication', '',
                'ydk.models.cisco_ios_xr.tailf_aaa', 'Aaa.Authentication',
                [], [],
                '''                ''',
                'authentication',
                'tailf-aaa', False),
            _MetaInfoClassMember('authorization', REFERENCE_CLASS, 'Authorization', '',
                'ydk.models.cisco_ios_xr.tailf_aaa', 'Aaa.Authorization',
                [], [],
                '''                ''',
                'authorization',
                'tailf-aaa', False),
            _MetaInfoClassMember('accounting', REFERENCE_CLASS, 'Accounting', '',
                'ydk.models.cisco_ios_xr.tailf_aaa', 'Aaa.Accounting',
                [], [],
                '''                ''',
                'accounting',
                'tailf-aaa', False),
            _MetaInfoClassMember('ios', REFERENCE_CLASS, 'Ios', '',
                'ydk.models.cisco_ios_xr.tailf_aaa', 'Aaa.Ios',
                [], [],
                '''                ''',
                'ios',
                'tailf-aaa', False, is_presence=True),
            _MetaInfoClassMember('disaster-recovery', REFERENCE_CLASS, 'DisasterRecovery', '',
                'ydk.models.cisco_ios_xr.tailf_aaa', 'Aaa.DisasterRecovery',
                [], [],
                '''                ''',
                'disaster_recovery',
                'Cisco-IOS-XR-sysadmin-aaa-disaster-recovery', False),
            _MetaInfoClassMember('privileged-access', REFERENCE_CLASS, 'PrivilegedAccess', '',
                'ydk.models.cisco_ios_xr.tailf_aaa', 'Aaa.PrivilegedAccess',
                [], [],
                '''                ''',
                'privileged_access',
                'Cisco-IOS-XR-sysadmin-aaa-aaa-show', False, is_config=False),
            _MetaInfoClassMember('accounting', REFERENCE_CLASS, 'CiscoIOSXRSysadminAaaAaaShowAccounting', '',
                'ydk.models.cisco_ios_xr.tailf_aaa', 'Aaa.CiscoIOSXRSysadminAaaAaaShowAccounting',
                [], [],
                '''                ''',
                'cisco_ios_xr_sysadmin_aaa_aaa_show_accounting',
                'Cisco-IOS-XR-sysadmin-aaa-aaa-show', False, is_config=False),
            _MetaInfoClassMember('user-group', REFERENCE_CLASS, 'UserGroup', '',
                'ydk.models.cisco_ios_xr.tailf_aaa', 'Aaa.UserGroup',
                [], [],
                '''                ''',
                'user_group',
                'Cisco-IOS-XR-sysadmin-aaa-aaa-show', False, is_config=False),
            ],
            'tailf-aaa',
            'aaa',
            _yang_ns.NAMESPACE_LOOKUP['tailf-aaa'],
            'ydk.models.cisco_ios_xr.tailf_aaa',
        ),
    },
    'Alias' : {
        'meta_info' : _MetaInfoClass('Alias', REFERENCE_LIST,
            ''' ''',
            False, 
            [
            _MetaInfoClassMember('name', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                ''',
                'name',
                'tailf-aaa', True),
            _MetaInfoClassMember('expansion', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                ''',
                'expansion',
                'tailf-aaa', False, is_mandatory=True),
            ],
            'tailf-aaa',
            'alias',
            _yang_ns.NAMESPACE_LOOKUP['tailf-aaa'],
            'ydk.models.cisco_ios_xr.tailf_aaa',
        ),
    },
    'Session' : {
        'meta_info' : _MetaInfoClass('Session', REFERENCE_CLASS,
            ''' ''',
            False, 
            [
            _MetaInfoClassMember('complete-on-space', ATTRIBUTE, 'bool', 'boolean',
                None, None,
                [], [],
                '''                ''',
                'complete_on_space',
                'tailf-aaa', False),
            _MetaInfoClassMember('ignore-leading-space', ATTRIBUTE, 'bool', 'boolean',
                None, None,
                [], [],
                '''                ''',
                'ignore_leading_space',
                'tailf-aaa', False),
            _MetaInfoClassMember('idle-timeout', ATTRIBUTE, 'int', 'idle-timeout',
                None, None,
                [('0', '8192')], [],
                '''                ''',
                'idle_timeout',
                'tailf-aaa', False),
            _MetaInfoClassMember('paginate', ATTRIBUTE, 'bool', 'boolean',
                None, None,
                [], [],
                '''                ''',
                'paginate',
                'tailf-aaa', False),
            _MetaInfoClassMember('history', ATTRIBUTE, 'int', 'history',
                None, None,
                [('0', '8192')], [],
                '''                ''',
                'history',
                'tailf-aaa', False),
            _MetaInfoClassMember('autowizard', ATTRIBUTE, 'bool', 'boolean',
                None, None,
                [], [],
                '''                ''',
                'autowizard',
                'tailf-aaa', False),
            _MetaInfoClassMember('show-defaults', ATTRIBUTE, 'bool', 'boolean',
                None, None,
                [], [],
                '''                ''',
                'show_defaults',
                'tailf-aaa', False),
            _MetaInfoClassMember('display-level', ATTRIBUTE, 'int', 'display-level',
                None, None,
                [('1', '64')], [],
                '''                ''',
                'display_level',
                'tailf-aaa', False),
            _MetaInfoClassMember('prompt1', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                ''',
                'prompt1',
                'tailf-aaa', False),
            _MetaInfoClassMember('prompt2', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                ''',
                'prompt2',
                'tailf-aaa', False),
            ],
            'tailf-aaa',
            'session',
            _yang_ns.NAMESPACE_LOOKUP['tailf-aaa'],
            'ydk.models.cisco_ios_xr.tailf_aaa',
            is_presence=True,
        ),
    },
    'User.Alias' : {
        'meta_info' : _MetaInfoClass('User.Alias', REFERENCE_LIST,
            ''' ''',
            False, 
            [
            _MetaInfoClassMember('name', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                ''',
                'name',
                'tailf-aaa', True),
            _MetaInfoClassMember('expansion', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                ''',
                'expansion',
                'tailf-aaa', False, is_mandatory=True),
            ],
            'tailf-aaa',
            'alias',
            _yang_ns.NAMESPACE_LOOKUP['tailf-aaa'],
            'ydk.models.cisco_ios_xr.tailf_aaa',
        ),
    },
    'User.Session' : {
        'meta_info' : _MetaInfoClass('User.Session', REFERENCE_CLASS,
            ''' ''',
            False, 
            [
            _MetaInfoClassMember('complete-on-space', ATTRIBUTE, 'bool', 'boolean',
                None, None,
                [], [],
                '''                ''',
                'complete_on_space',
                'tailf-aaa', False),
            _MetaInfoClassMember('ignore-leading-space', ATTRIBUTE, 'bool', 'boolean',
                None, None,
                [], [],
                '''                ''',
                'ignore_leading_space',
                'tailf-aaa', False),
            _MetaInfoClassMember('idle-timeout', ATTRIBUTE, 'int', 'idle-timeout',
                None, None,
                [('0', '8192')], [],
                '''                ''',
                'idle_timeout',
                'tailf-aaa', False),
            _MetaInfoClassMember('paginate', ATTRIBUTE, 'bool', 'boolean',
                None, None,
                [], [],
                '''                ''',
                'paginate',
                'tailf-aaa', False),
            _MetaInfoClassMember('history', ATTRIBUTE, 'int', 'history',
                None, None,
                [('0', '8192')], [],
                '''                ''',
                'history',
                'tailf-aaa', False),
            _MetaInfoClassMember('autowizard', ATTRIBUTE, 'bool', 'boolean',
                None, None,
                [], [],
                '''                ''',
                'autowizard',
                'tailf-aaa', False),
            _MetaInfoClassMember('show-defaults', ATTRIBUTE, 'bool', 'boolean',
                None, None,
                [], [],
                '''                ''',
                'show_defaults',
                'tailf-aaa', False),
            _MetaInfoClassMember('display-level', ATTRIBUTE, 'int', 'display-level',
                None, None,
                [('1', '64')], [],
                '''                ''',
                'display_level',
                'tailf-aaa', False),
            _MetaInfoClassMember('prompt1', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                ''',
                'prompt1',
                'tailf-aaa', False),
            _MetaInfoClassMember('prompt2', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                ''',
                'prompt2',
                'tailf-aaa', False),
            ],
            'tailf-aaa',
            'session',
            _yang_ns.NAMESPACE_LOOKUP['tailf-aaa'],
            'ydk.models.cisco_ios_xr.tailf_aaa',
        ),
    },
    'User' : {
        'meta_info' : _MetaInfoClass('User', REFERENCE_LIST,
            ''' ''',
            False, 
            [
            _MetaInfoClassMember('name', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                ''',
                'name',
                'tailf-aaa', True),
            _MetaInfoClassMember('description', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                ''',
                'description',
                'tailf-aaa', False),
            _MetaInfoClassMember('alias', REFERENCE_LIST, 'Alias', '',
                'ydk.models.cisco_ios_xr.tailf_aaa', 'User.Alias',
                [], [],
                '''                ''',
                'alias',
                'tailf-aaa', False),
            _MetaInfoClassMember('session', REFERENCE_CLASS, 'Session', '',
                'ydk.models.cisco_ios_xr.tailf_aaa', 'User.Session',
                [], [],
                '''                ''',
                'session',
                'tailf-aaa', False),
            ],
            'tailf-aaa',
            'user',
            _yang_ns.NAMESPACE_LOOKUP['tailf-aaa'],
            'ydk.models.cisco_ios_xr.tailf_aaa',
        ),
    },
}
_meta_table['Aaa.Authentication.Users.User']['meta_info'].parent =_meta_table['Aaa.Authentication.Users']['meta_info']
_meta_table['Aaa.Authentication.Groups.Group']['meta_info'].parent =_meta_table['Aaa.Authentication.Groups']['meta_info']
_meta_table['Aaa.Authentication.Login.Group']['meta_info'].parent =_meta_table['Aaa.Authentication.Login']['meta_info']
_meta_table['Aaa.Authentication.Users']['meta_info'].parent =_meta_table['Aaa.Authentication']['meta_info']
_meta_table['Aaa.Authentication.Groups']['meta_info'].parent =_meta_table['Aaa.Authentication']['meta_info']
_meta_table['Aaa.Authentication.Login']['meta_info'].parent =_meta_table['Aaa.Authentication']['meta_info']
_meta_table['Aaa.Authorization.Cmdrules.Cmdrule']['meta_info'].parent =_meta_table['Aaa.Authorization.Cmdrules']['meta_info']
_meta_table['Aaa.Authorization.Datarules.Datarule']['meta_info'].parent =_meta_table['Aaa.Authorization.Datarules']['meta_info']
_meta_table['Aaa.Authorization.Commands.Group']['meta_info'].parent =_meta_table['Aaa.Authorization.Commands']['meta_info']
_meta_table['Aaa.Authorization.Cmdrules']['meta_info'].parent =_meta_table['Aaa.Authorization']['meta_info']
_meta_table['Aaa.Authorization.Datarules']['meta_info'].parent =_meta_table['Aaa.Authorization']['meta_info']
_meta_table['Aaa.Authorization.Commands']['meta_info'].parent =_meta_table['Aaa.Authorization']['meta_info']
_meta_table['Aaa.Accounting.Commands.Group']['meta_info'].parent =_meta_table['Aaa.Accounting.Commands']['meta_info']
_meta_table['Aaa.Accounting.Commands']['meta_info'].parent =_meta_table['Aaa.Accounting']['meta_info']
_meta_table['Aaa.Ios.Privilege.Level.Command']['meta_info'].parent =_meta_table['Aaa.Ios.Privilege.Level']['meta_info']
_meta_table['Aaa.Ios.Privilege.Level']['meta_info'].parent =_meta_table['Aaa.Ios.Privilege']['meta_info']
_meta_table['Aaa.Ios.Level']['meta_info'].parent =_meta_table['Aaa.Ios']['meta_info']
_meta_table['Aaa.Ios.Privilege']['meta_info'].parent =_meta_table['Aaa.Ios']['meta_info']
_meta_table['Aaa.Authentication']['meta_info'].parent =_meta_table['Aaa']['meta_info']
_meta_table['Aaa.Authorization']['meta_info'].parent =_meta_table['Aaa']['meta_info']
_meta_table['Aaa.Accounting']['meta_info'].parent =_meta_table['Aaa']['meta_info']
_meta_table['Aaa.Ios']['meta_info'].parent =_meta_table['Aaa']['meta_info']
_meta_table['Aaa.DisasterRecovery']['meta_info'].parent =_meta_table['Aaa']['meta_info']
_meta_table['Aaa.PrivilegedAccess']['meta_info'].parent =_meta_table['Aaa']['meta_info']
_meta_table['Aaa.CiscoIOSXRSysadminAaaAaaShowAccounting']['meta_info'].parent =_meta_table['Aaa']['meta_info']
_meta_table['Aaa.UserGroup']['meta_info'].parent =_meta_table['Aaa']['meta_info']
_meta_table['User.Alias']['meta_info'].parent =_meta_table['User']['meta_info']
_meta_table['User.Session']['meta_info'].parent =_meta_table['User']['meta_info']
