
'''
This is auto-generated file,
which includes metadata for module vplatform
'''

from ydk._core._dm_meta_info import _MetaInfoClassMember, _MetaInfoClass, _MetaInfoEnum
from ydk._core._dm_meta_info import ATTRIBUTE, REFERENCE_LIST, REFERENCE_LEAFLIST, REFERENCE_BITS, REFERENCE_UNION
from ydk._core._dm_meta_info import REFERENCE_CLASS, REFERENCE_IDENTITY_CLASS, REFERENCE_ENUM_CLASS, ANYXML_CLASS
from ydk._core._importer import _yang_ns

_meta_table = {
    'VirtualPlatform.Vplatform.Summary' : {
        'meta_info' : _MetaInfoClass('VirtualPlatform.Vplatform.Summary', REFERENCE_LIST,
            ''' ''',
            False, 
            [
            _MetaInfoClassMember('lines', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                ''',
                'lines',
                'vplatform', False, is_config=False),
            ],
            'vplatform',
            'summary',
            _yang_ns.NAMESPACE_LOOKUP['vplatform'],
            'ydk.models.cisco_ios_xr.vplatform',
            is_config=False,
        ),
    },
    'VirtualPlatform.Vplatform' : {
        'meta_info' : _MetaInfoClass('VirtualPlatform.Vplatform', REFERENCE_CLASS,
            ''' ''',
            False, 
            [
            _MetaInfoClassMember('summary', REFERENCE_LIST, 'Summary', '',
                'ydk.models.cisco_ios_xr.vplatform', 'VirtualPlatform.Vplatform.Summary',
                [], [],
                '''                ''',
                'summary',
                'vplatform', False, is_config=False),
            ],
            'vplatform',
            'vplatform',
            _yang_ns.NAMESPACE_LOOKUP['vplatform'],
            'ydk.models.cisco_ios_xr.vplatform',
            is_config=False,
        ),
    },
    'VirtualPlatform.Udi.History.UdiHis' : {
        'meta_info' : _MetaInfoClass('VirtualPlatform.Udi.History.UdiHis', REFERENCE_LIST,
            ''' ''',
            False, 
            [
            _MetaInfoClassMember('history_records', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                ''',
                'history_records',
                'vplatform', False, is_config=False),
            ],
            'vplatform',
            'udi_his',
            _yang_ns.NAMESPACE_LOOKUP['vplatform'],
            'ydk.models.cisco_ios_xr.vplatform',
            is_config=False,
        ),
    },
    'VirtualPlatform.Udi.History' : {
        'meta_info' : _MetaInfoClass('VirtualPlatform.Udi.History', REFERENCE_CLASS,
            ''' ''',
            False, 
            [
            _MetaInfoClassMember('udi_his', REFERENCE_LIST, 'UdiHis', '',
                'ydk.models.cisco_ios_xr.vplatform', 'VirtualPlatform.Udi.History.UdiHis',
                [], [],
                '''                ''',
                'udi_his',
                'vplatform', False, is_config=False),
            ],
            'vplatform',
            'history',
            _yang_ns.NAMESPACE_LOOKUP['vplatform'],
            'ydk.models.cisco_ios_xr.vplatform',
            is_config=False,
        ),
    },
    'VirtualPlatform.Udi' : {
        'meta_info' : _MetaInfoClass('VirtualPlatform.Udi', REFERENCE_CLASS,
            ''' ''',
            False, 
            [
            _MetaInfoClassMember('history', REFERENCE_CLASS, 'History', '',
                'ydk.models.cisco_ios_xr.vplatform', 'VirtualPlatform.Udi.History',
                [], [],
                '''                ''',
                'history',
                'vplatform', False, is_config=False),
            ],
            'vplatform',
            'udi',
            _yang_ns.NAMESPACE_LOOKUP['vplatform'],
            'ydk.models.cisco_ios_xr.vplatform',
            is_config=False,
        ),
    },
    'VirtualPlatform.Cpu.History.CpuUtl' : {
        'meta_info' : _MetaInfoClass('VirtualPlatform.Cpu.History.CpuUtl', REFERENCE_LIST,
            ''' ''',
            False, 
            [
            _MetaInfoClassMember('history_records', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                ''',
                'history_records',
                'vplatform', False, is_config=False),
            ],
            'vplatform',
            'cpu_utl',
            _yang_ns.NAMESPACE_LOOKUP['vplatform'],
            'ydk.models.cisco_ios_xr.vplatform',
            is_config=False,
        ),
    },
    'VirtualPlatform.Cpu.History' : {
        'meta_info' : _MetaInfoClass('VirtualPlatform.Cpu.History', REFERENCE_CLASS,
            ''' ''',
            False, 
            [
            _MetaInfoClassMember('cpu_utl', REFERENCE_LIST, 'CpuUtl', '',
                'ydk.models.cisco_ios_xr.vplatform', 'VirtualPlatform.Cpu.History.CpuUtl',
                [], [],
                '''                ''',
                'cpu_utl',
                'vplatform', False, is_config=False),
            ],
            'vplatform',
            'history',
            _yang_ns.NAMESPACE_LOOKUP['vplatform'],
            'ydk.models.cisco_ios_xr.vplatform',
            is_config=False,
        ),
    },
    'VirtualPlatform.Cpu' : {
        'meta_info' : _MetaInfoClass('VirtualPlatform.Cpu', REFERENCE_CLASS,
            ''' ''',
            False, 
            [
            _MetaInfoClassMember('history', REFERENCE_CLASS, 'History', '',
                'ydk.models.cisco_ios_xr.vplatform', 'VirtualPlatform.Cpu.History',
                [], [],
                '''                ''',
                'history',
                'vplatform', False, is_config=False),
            ],
            'vplatform',
            'cpu',
            _yang_ns.NAMESPACE_LOOKUP['vplatform'],
            'ydk.models.cisco_ios_xr.vplatform',
            is_config=False,
        ),
    },
    'VirtualPlatform.Processor.History.ProcInfo' : {
        'meta_info' : _MetaInfoClass('VirtualPlatform.Processor.History.ProcInfo', REFERENCE_LIST,
            ''' ''',
            False, 
            [
            _MetaInfoClassMember('history_records', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                ''',
                'history_records',
                'vplatform', False, is_config=False),
            ],
            'vplatform',
            'proc_info',
            _yang_ns.NAMESPACE_LOOKUP['vplatform'],
            'ydk.models.cisco_ios_xr.vplatform',
            is_config=False,
        ),
    },
    'VirtualPlatform.Processor.History' : {
        'meta_info' : _MetaInfoClass('VirtualPlatform.Processor.History', REFERENCE_CLASS,
            ''' ''',
            False, 
            [
            _MetaInfoClassMember('proc_info', REFERENCE_LIST, 'ProcInfo', '',
                'ydk.models.cisco_ios_xr.vplatform', 'VirtualPlatform.Processor.History.ProcInfo',
                [], [],
                '''                ''',
                'proc_info',
                'vplatform', False, is_config=False),
            ],
            'vplatform',
            'history',
            _yang_ns.NAMESPACE_LOOKUP['vplatform'],
            'ydk.models.cisco_ios_xr.vplatform',
            is_config=False,
        ),
    },
    'VirtualPlatform.Processor' : {
        'meta_info' : _MetaInfoClass('VirtualPlatform.Processor', REFERENCE_CLASS,
            ''' ''',
            False, 
            [
            _MetaInfoClassMember('history', REFERENCE_CLASS, 'History', '',
                'ydk.models.cisco_ios_xr.vplatform', 'VirtualPlatform.Processor.History',
                [], [],
                '''                ''',
                'history',
                'vplatform', False, is_config=False),
            ],
            'vplatform',
            'processor',
            _yang_ns.NAMESPACE_LOOKUP['vplatform'],
            'ydk.models.cisco_ios_xr.vplatform',
            is_config=False,
        ),
    },
    'VirtualPlatform.Memory.History.MemUsg' : {
        'meta_info' : _MetaInfoClass('VirtualPlatform.Memory.History.MemUsg', REFERENCE_LIST,
            ''' ''',
            False, 
            [
            _MetaInfoClassMember('history_records', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                ''',
                'history_records',
                'vplatform', False, is_config=False),
            ],
            'vplatform',
            'mem_usg',
            _yang_ns.NAMESPACE_LOOKUP['vplatform'],
            'ydk.models.cisco_ios_xr.vplatform',
            is_config=False,
        ),
    },
    'VirtualPlatform.Memory.History' : {
        'meta_info' : _MetaInfoClass('VirtualPlatform.Memory.History', REFERENCE_CLASS,
            ''' ''',
            False, 
            [
            _MetaInfoClassMember('mem_usg', REFERENCE_LIST, 'MemUsg', '',
                'ydk.models.cisco_ios_xr.vplatform', 'VirtualPlatform.Memory.History.MemUsg',
                [], [],
                '''                ''',
                'mem_usg',
                'vplatform', False, is_config=False),
            ],
            'vplatform',
            'history',
            _yang_ns.NAMESPACE_LOOKUP['vplatform'],
            'ydk.models.cisco_ios_xr.vplatform',
            is_config=False,
        ),
    },
    'VirtualPlatform.Memory' : {
        'meta_info' : _MetaInfoClass('VirtualPlatform.Memory', REFERENCE_CLASS,
            ''' ''',
            False, 
            [
            _MetaInfoClassMember('history', REFERENCE_CLASS, 'History', '',
                'ydk.models.cisco_ios_xr.vplatform', 'VirtualPlatform.Memory.History',
                [], [],
                '''                ''',
                'history',
                'vplatform', False, is_config=False),
            ],
            'vplatform',
            'memory',
            _yang_ns.NAMESPACE_LOOKUP['vplatform'],
            'ydk.models.cisco_ios_xr.vplatform',
            is_config=False,
        ),
    },
    'VirtualPlatform.Disk.History.DiskUtl' : {
        'meta_info' : _MetaInfoClass('VirtualPlatform.Disk.History.DiskUtl', REFERENCE_LIST,
            ''' ''',
            False, 
            [
            _MetaInfoClassMember('history_records', ATTRIBUTE, 'str', 'string',
                None, None,
                [], [],
                '''                ''',
                'history_records',
                'vplatform', False, is_config=False),
            ],
            'vplatform',
            'disk_utl',
            _yang_ns.NAMESPACE_LOOKUP['vplatform'],
            'ydk.models.cisco_ios_xr.vplatform',
            is_config=False,
        ),
    },
    'VirtualPlatform.Disk.History' : {
        'meta_info' : _MetaInfoClass('VirtualPlatform.Disk.History', REFERENCE_CLASS,
            ''' ''',
            False, 
            [
            _MetaInfoClassMember('disk_utl', REFERENCE_LIST, 'DiskUtl', '',
                'ydk.models.cisco_ios_xr.vplatform', 'VirtualPlatform.Disk.History.DiskUtl',
                [], [],
                '''                ''',
                'disk_utl',
                'vplatform', False, is_config=False),
            ],
            'vplatform',
            'history',
            _yang_ns.NAMESPACE_LOOKUP['vplatform'],
            'ydk.models.cisco_ios_xr.vplatform',
            is_config=False,
        ),
    },
    'VirtualPlatform.Disk' : {
        'meta_info' : _MetaInfoClass('VirtualPlatform.Disk', REFERENCE_CLASS,
            ''' ''',
            False, 
            [
            _MetaInfoClassMember('history', REFERENCE_CLASS, 'History', '',
                'ydk.models.cisco_ios_xr.vplatform', 'VirtualPlatform.Disk.History',
                [], [],
                '''                ''',
                'history',
                'vplatform', False, is_config=False),
            ],
            'vplatform',
            'disk',
            _yang_ns.NAMESPACE_LOOKUP['vplatform'],
            'ydk.models.cisco_ios_xr.vplatform',
            is_config=False,
        ),
    },
    'VirtualPlatform.Action.Udi' : {
        'meta_info' : _MetaInfoClass('VirtualPlatform.Action.Udi', REFERENCE_LIST,
            '''UDI Operations''',
            False, 
            [
            ],
            'vplatform',
            'udi',
            _yang_ns.NAMESPACE_LOOKUP['vplatform'],
            'ydk.models.cisco_ios_xr.vplatform',
            is_config=False,
        ),
    },
    'VirtualPlatform.Action' : {
        'meta_info' : _MetaInfoClass('VirtualPlatform.Action', REFERENCE_CLASS,
            ''' ''',
            False, 
            [
            _MetaInfoClassMember('udi', REFERENCE_LIST, 'Udi', '',
                'ydk.models.cisco_ios_xr.vplatform', 'VirtualPlatform.Action.Udi',
                [], [],
                '''                UDI Operations
                ''',
                'udi',
                'vplatform', False, max_elements=1, min_elements=1, is_config=False),
            ],
            'vplatform',
            'Action',
            _yang_ns.NAMESPACE_LOOKUP['vplatform'],
            'ydk.models.cisco_ios_xr.vplatform',
            is_config=False,
        ),
    },
    'VirtualPlatform' : {
        'meta_info' : _MetaInfoClass('VirtualPlatform', REFERENCE_CLASS,
            ''' ''',
            False, 
            [
            _MetaInfoClassMember('vplatform', REFERENCE_CLASS, 'Vplatform', '',
                'ydk.models.cisco_ios_xr.vplatform', 'VirtualPlatform.Vplatform',
                [], [],
                '''                ''',
                'vplatform',
                'vplatform', False, is_config=False),
            _MetaInfoClassMember('udi', REFERENCE_CLASS, 'Udi', '',
                'ydk.models.cisco_ios_xr.vplatform', 'VirtualPlatform.Udi',
                [], [],
                '''                ''',
                'udi',
                'vplatform', False, is_config=False),
            _MetaInfoClassMember('cpu', REFERENCE_CLASS, 'Cpu', '',
                'ydk.models.cisco_ios_xr.vplatform', 'VirtualPlatform.Cpu',
                [], [],
                '''                ''',
                'cpu',
                'vplatform', False, is_config=False),
            _MetaInfoClassMember('processor', REFERENCE_CLASS, 'Processor', '',
                'ydk.models.cisco_ios_xr.vplatform', 'VirtualPlatform.Processor',
                [], [],
                '''                ''',
                'processor',
                'vplatform', False, is_config=False),
            _MetaInfoClassMember('memory', REFERENCE_CLASS, 'Memory', '',
                'ydk.models.cisco_ios_xr.vplatform', 'VirtualPlatform.Memory',
                [], [],
                '''                ''',
                'memory',
                'vplatform', False, is_config=False),
            _MetaInfoClassMember('disk', REFERENCE_CLASS, 'Disk', '',
                'ydk.models.cisco_ios_xr.vplatform', 'VirtualPlatform.Disk',
                [], [],
                '''                ''',
                'disk',
                'vplatform', False, is_config=False),
            _MetaInfoClassMember('Action', REFERENCE_CLASS, 'Action', '',
                'ydk.models.cisco_ios_xr.vplatform', 'VirtualPlatform.Action',
                [], [],
                '''                ''',
                'action',
                'vplatform', False, is_config=False),
            ],
            'vplatform',
            'virtual-platform',
            _yang_ns.NAMESPACE_LOOKUP['vplatform'],
            'ydk.models.cisco_ios_xr.vplatform',
            is_config=False,
        ),
    },
}
_meta_table['VirtualPlatform.Vplatform.Summary']['meta_info'].parent =_meta_table['VirtualPlatform.Vplatform']['meta_info']
_meta_table['VirtualPlatform.Udi.History.UdiHis']['meta_info'].parent =_meta_table['VirtualPlatform.Udi.History']['meta_info']
_meta_table['VirtualPlatform.Udi.History']['meta_info'].parent =_meta_table['VirtualPlatform.Udi']['meta_info']
_meta_table['VirtualPlatform.Cpu.History.CpuUtl']['meta_info'].parent =_meta_table['VirtualPlatform.Cpu.History']['meta_info']
_meta_table['VirtualPlatform.Cpu.History']['meta_info'].parent =_meta_table['VirtualPlatform.Cpu']['meta_info']
_meta_table['VirtualPlatform.Processor.History.ProcInfo']['meta_info'].parent =_meta_table['VirtualPlatform.Processor.History']['meta_info']
_meta_table['VirtualPlatform.Processor.History']['meta_info'].parent =_meta_table['VirtualPlatform.Processor']['meta_info']
_meta_table['VirtualPlatform.Memory.History.MemUsg']['meta_info'].parent =_meta_table['VirtualPlatform.Memory.History']['meta_info']
_meta_table['VirtualPlatform.Memory.History']['meta_info'].parent =_meta_table['VirtualPlatform.Memory']['meta_info']
_meta_table['VirtualPlatform.Disk.History.DiskUtl']['meta_info'].parent =_meta_table['VirtualPlatform.Disk.History']['meta_info']
_meta_table['VirtualPlatform.Disk.History']['meta_info'].parent =_meta_table['VirtualPlatform.Disk']['meta_info']
_meta_table['VirtualPlatform.Action.Udi']['meta_info'].parent =_meta_table['VirtualPlatform.Action']['meta_info']
_meta_table['VirtualPlatform.Vplatform']['meta_info'].parent =_meta_table['VirtualPlatform']['meta_info']
_meta_table['VirtualPlatform.Udi']['meta_info'].parent =_meta_table['VirtualPlatform']['meta_info']
_meta_table['VirtualPlatform.Cpu']['meta_info'].parent =_meta_table['VirtualPlatform']['meta_info']
_meta_table['VirtualPlatform.Processor']['meta_info'].parent =_meta_table['VirtualPlatform']['meta_info']
_meta_table['VirtualPlatform.Memory']['meta_info'].parent =_meta_table['VirtualPlatform']['meta_info']
_meta_table['VirtualPlatform.Disk']['meta_info'].parent =_meta_table['VirtualPlatform']['meta_info']
_meta_table['VirtualPlatform.Action']['meta_info'].parent =_meta_table['VirtualPlatform']['meta_info']
