# This file was automatically generated by sub\epyqlib\epyqlib\cli\generateversion.py
__version_build_time__ = '2020-01-10T20:54:58.327229'

__version__ = '2020.1'
__sha__ = '5cb0602bc72c1420ebf1d53b7704825a787bfbc9'
__revision__ = '5cb0602bc72c1420ebf1d53b7704825a787bfbc9'
