
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-01-11T16:49:43-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "02a1ffc90679ac073b9f70f7dec7bb7aca16cf67",
 "version": "0.0.3-rc.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
