

// This file is autogenerated. DO NOT EDIT

#pragma once
#include <robotpy_build.h>

#include <..\..\_impl\include\frc\CounterBase.h>



namespace rpygen {

using namespace frc;

template <typename CxxBase>
struct Pyfrc__CounterBase : CxxBase {
    using CxxBase::CxxBase;



#ifndef RPYGEN_DISABLE_KGet_v
    int Get() const override {
PYBIND11_OVERLOAD_PURE_NAME(int, CxxBase, "get", Get,);
    }
#endif

#ifndef RPYGEN_DISABLE_Reset_v
    void Reset() override {
PYBIND11_OVERLOAD_PURE_NAME(void, CxxBase, "reset", Reset,);
    }
#endif

#ifndef RPYGEN_DISABLE_KGetPeriod_v
    double GetPeriod() const override {
PYBIND11_OVERLOAD_PURE_NAME(double, CxxBase, "getPeriod", GetPeriod,);
    }
#endif

#ifndef RPYGEN_DISABLE_SetMaxPeriod_d
    void SetMaxPeriod(double maxPeriod) override {
PYBIND11_OVERLOAD_PURE_NAME(void, CxxBase, "setMaxPeriod", SetMaxPeriod,maxPeriod);
    }
#endif

#ifndef RPYGEN_DISABLE_KGetStopped_v
    bool GetStopped() const override {
PYBIND11_OVERLOAD_PURE_NAME(bool, CxxBase, "getStopped", GetStopped,);
    }
#endif

#ifndef RPYGEN_DISABLE_KGetDirection_v
    bool GetDirection() const override {
PYBIND11_OVERLOAD_PURE_NAME(bool, CxxBase, "getDirection", GetDirection,);
    }
#endif



};

}; // namespace rpygen