language: python
sudo: required
dist: xenial

python:
  - "3.7"
  - "3.6"
  - "3.8"

matrix:
  fast_finish: true

# command to install dependencies
install:
  - pip install -U pip
  - ROBOTPY_NO_DEPS=1 pip install -r travis-requirements.txt
# command to run tests
script:
  - RUNCOVERAGE=1 tests/run_tests.sh

jobs:
  include:
  - stage: format-check
    python:
    - "3.6"
    install:
    - pip install black
    script:
    - black --check --diff .
  - stage: deploy
    if: tag IS present
    python: "3.7"
    install: skip
    script: skip
    deploy:
    - provider: pypi
      user: $PYPI_USERNAME
      password: $PYPI_PASSWORD
      distributions: sdist bdist_wheel
      on:
        tags: true

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/2fb1c026e64fdd70d27b
    on_success: change
    on_failure: always
    on_start: never
