
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-01-18T13:30:44+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "de84d7c1a42a5629781e350adb7f7ac00df29290",
 "version": "0.1.0b3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
