- project:
    templates:
      - check-requirements
      - openstack-cover-jobs-neutron
      - openstack-lower-constraints-jobs-neutron
      - openstack-python-jobs-neutron
      - openstack-python35-jobs-neutron
      - openstack-python36-jobs-neutron
      - openstack-python37-jobs-neutron
      - periodic-stable-jobs-neutron
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
    check:
      jobs:
        - legacy-neutron-fwaas-v2-dsvm-tempest
        - legacy-neutron-fwaas-dsvm-functional
        - legacy-grenade-dsvm-neutron-fwaas-multinode:
            voting: false
            irrelevant-files:
              - ^(test-|)requirements.txt$
              - ^setup.cfg$
        - legacy-neutron-fwaas-v2-dsvm-tempest-multinode:
            voting: false
    gate:
      jobs:
        - legacy-neutron-fwaas-v2-dsvm-tempest
        - legacy-neutron-fwaas-dsvm-functional
    experimental:
      jobs:
        - legacy-neutron-fwaas-dsvm-fullstack

- job:
    name: neutron-fwaas-fullstack
    parent: legacy-dsvm-base
    run: playbooks/neutron-fwaas-fullstack/run.yaml
    post-run: playbooks/neutron-fwaas-fullstack/post.yaml
    timeout: 7800
    required-projects:
      - openstack/devstack-gate
      - openstack/neutron
    irrelevant-files:
      - ^.*\.rst$
      - ^doc/.*$
      - ^neutron/locale/.*$
      - ^releasenotes/.*$


- job:
    name: neutron-fwaas-fullstack-python35
    parent: legacy-dsvm-base
    run: playbooks/legacy/neutron-fullstack-python35/run.yaml
    post-run: playbooks/legacy/neutron-fullstack-python35/post.yaml
    timeout: 7800
    required-projects:
      - openstack/devstack-gate
      - openstack/neutron
    irrelevant-files:
      - ^.*\.rst$
      - ^doc/.*$
      - ^neutron/locale/.*$
      - ^releasenotes/.*$
    voting: false
