
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-01-13T09:13:48-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "a918f7a89e2775034c6af919fa0f457b0706cd78",
 "version": "0.1.0a1.post23"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
