
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-01-19T11:37:37-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "3550397e0ef28f3872b26bae00c336856fab4125",
 "version": "0.0.48"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
