
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-01-16T16:26:56+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "5938d8052b593b193b3d8a4a63cc052aac8682ec",
 "version": "0.10.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
