
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-01-18T17:42:21-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "5b41cfb310ee814c5cc25a12b0a53365bf0b366f",
 "version": "1.0.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
