
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-12-10T16:06:53-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "9321c37e76ea6380699c3b983552977740d3404c",
 "version": "0.3.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
