
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-01-14T17:06:45-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "55e43dc81388b9f75b02977db3491f9c273ee5b7",
 "version": "1.0.0b6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
