[tool.poetry]
name = "template-ipython-magic"
version = "0.1.0"
description = "IPython magics to render cells as templates in a variety of different templating languages."
authors = ["Jez Cope <j.cope@erambler.co.uk>"]
readme = "README.md"
repository = "https://gitlab.com/jezcope/template-ipython-magic"
license = "LGPL-3.0-or-later"
packages = [
    { include = "template_magic" }
]

[tool.poetry.dependencies]
python = "^3.7"
ipython = "^7.11.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
jinja2 = "^2.10.3"
mako = "^1.1.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
