# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: streamlit/proto/NumberInput.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='streamlit/proto/NumberInput.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n!streamlit/proto/NumberInput.proto\"\xce\x01\n\x0bNumberInput\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05label\x18\x02 \x01(\t\x12#\n\x08int_data\x18\t \x01(\x0b\x32\x0f.IntNumberInputH\x00\x12\'\n\nfloat_data\x18\n \x01(\x0b\x32\x11.FloatNumberInputH\x00\x12\x0e\n\x06\x66ormat\x18\x08 \x01(\t\x12\x0f\n\x07has_min\x18\x0b \x01(\x08\x12\x0f\n\x07has_max\x18\x0c \x01(\x08\x42\x06\n\x04\x64\x61taJ\x04\x08\x03\x10\x04J\x04\x08\x04\x10\x05J\x04\x08\x05\x10\x06J\x04\x08\x06\x10\x07J\x04\x08\x07\x10\x08\"I\n\x0eIntNumberInput\x12\x0f\n\x07\x64\x65\x66\x61ult\x18\x01 \x01(\x12\x12\x0c\n\x04step\x18\x02 \x01(\x03\x12\x0b\n\x03min\x18\x03 \x01(\x12\x12\x0b\n\x03max\x18\x04 \x01(\x12\"K\n\x10\x46loatNumberInput\x12\x0f\n\x07\x64\x65\x66\x61ult\x18\x01 \x01(\x01\x12\x0c\n\x04step\x18\x02 \x01(\x01\x12\x0b\n\x03min\x18\x03 \x01(\x01\x12\x0b\n\x03max\x18\x04 \x01(\x01\x62\x06proto3'
)




_NUMBERINPUT = _descriptor.Descriptor(
  name='NumberInput',
  full_name='NumberInput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='NumberInput.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='label', full_name='NumberInput.label', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='int_data', full_name='NumberInput.int_data', index=2,
      number=9, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='float_data', full_name='NumberInput.float_data', index=3,
      number=10, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='format', full_name='NumberInput.format', index=4,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='has_min', full_name='NumberInput.has_min', index=5,
      number=11, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='has_max', full_name='NumberInput.has_max', index=6,
      number=12, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='data', full_name='NumberInput.data',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=38,
  serialized_end=244,
)


_INTNUMBERINPUT = _descriptor.Descriptor(
  name='IntNumberInput',
  full_name='IntNumberInput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='default', full_name='IntNumberInput.default', index=0,
      number=1, type=18, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='step', full_name='IntNumberInput.step', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='min', full_name='IntNumberInput.min', index=2,
      number=3, type=18, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='max', full_name='IntNumberInput.max', index=3,
      number=4, type=18, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=246,
  serialized_end=319,
)


_FLOATNUMBERINPUT = _descriptor.Descriptor(
  name='FloatNumberInput',
  full_name='FloatNumberInput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='default', full_name='FloatNumberInput.default', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='step', full_name='FloatNumberInput.step', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='min', full_name='FloatNumberInput.min', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='max', full_name='FloatNumberInput.max', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=321,
  serialized_end=396,
)

_NUMBERINPUT.fields_by_name['int_data'].message_type = _INTNUMBERINPUT
_NUMBERINPUT.fields_by_name['float_data'].message_type = _FLOATNUMBERINPUT
_NUMBERINPUT.oneofs_by_name['data'].fields.append(
  _NUMBERINPUT.fields_by_name['int_data'])
_NUMBERINPUT.fields_by_name['int_data'].containing_oneof = _NUMBERINPUT.oneofs_by_name['data']
_NUMBERINPUT.oneofs_by_name['data'].fields.append(
  _NUMBERINPUT.fields_by_name['float_data'])
_NUMBERINPUT.fields_by_name['float_data'].containing_oneof = _NUMBERINPUT.oneofs_by_name['data']
DESCRIPTOR.message_types_by_name['NumberInput'] = _NUMBERINPUT
DESCRIPTOR.message_types_by_name['IntNumberInput'] = _INTNUMBERINPUT
DESCRIPTOR.message_types_by_name['FloatNumberInput'] = _FLOATNUMBERINPUT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

NumberInput = _reflection.GeneratedProtocolMessageType('NumberInput', (_message.Message,), {
  'DESCRIPTOR' : _NUMBERINPUT,
  '__module__' : 'streamlit.proto.NumberInput_pb2'
  # @@protoc_insertion_point(class_scope:NumberInput)
  })
_sym_db.RegisterMessage(NumberInput)

IntNumberInput = _reflection.GeneratedProtocolMessageType('IntNumberInput', (_message.Message,), {
  'DESCRIPTOR' : _INTNUMBERINPUT,
  '__module__' : 'streamlit.proto.NumberInput_pb2'
  # @@protoc_insertion_point(class_scope:IntNumberInput)
  })
_sym_db.RegisterMessage(IntNumberInput)

FloatNumberInput = _reflection.GeneratedProtocolMessageType('FloatNumberInput', (_message.Message,), {
  'DESCRIPTOR' : _FLOATNUMBERINPUT,
  '__module__' : 'streamlit.proto.NumberInput_pb2'
  # @@protoc_insertion_point(class_scope:FloatNumberInput)
  })
_sym_db.RegisterMessage(FloatNumberInput)


# @@protoc_insertion_point(module_scope)
