__title__ = 'metrecord'
__description__ = 'Python SDK for metrecord.com'
__url__ = 'https://app.metrecord.com'
__version__ = '0.0.1'
__author__ = 'Ryan Baker'
__license__ = 'Apache 2.0'
__copyright__ = 'Copyright 2020 Ryan Baker'