# coding: utf-8

"""
    PSI Candidate Rest Eligibility Service

    PSIs REST based service to modify candidate test eligibilities.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import psi_eligibility
from psi_eligibility.models.error_model import ErrorModel  # noqa: E501
from psi_eligibility.rest import ApiException


class TestErrorModel(unittest.TestCase):
    """ErrorModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testErrorModel(self):
        """Test ErrorModel"""
        # FIXME: construct object with mandatory attributes with example values
        # model = psi_eligibility.models.error_model.ErrorModel()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
